### PR TITLE
[7.11.x] AF-1502: Update project branches on runtime even when they are modified out of the workbench

### PR DESCRIPTION
**Pull request by paulovmr**
Part of an ensemble:
* https://github.com/kiegroup/appformer/pull/455
* https://github.com/kiegroup/kie-wb-common/pull/2108

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins retest this

**Comment by barboras7** [comment]
jenkins retest this

**Comment by ederign** [comment]
According to paulo the compilation fail is unrelated.

**Pull request merged**
