### PR TITLE
JBPM-9273 System error occurred while adding deployment unit

### PR DESCRIPTION
**Pull request by bxf12315**
**Thank you for submitting this pull request**

**JIRA**: [JBPM-9273](https://issues.redhat.com/browse/JBPM-9273)

**Referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-integration/pull/2329
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://donwnload.here/something)

**VS Code**: [plugin](https://donwnload.here/something)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Review by nmirasch — APPROVED** [review]

**Comment by prashuts** [comment]
jenkins do fdb

**Review by prashuts — APPROVED** [review]
Looks good to me..

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by bxf12315** [comment]
jenkins do fdb

**Comment by bxf12315** [comment]
jenkins retest this

**Comment by prashuts** [comment]
verified - LGTM

**Pull request merged**
