### PR TITLE
[7.7.x] RHPAM-797: [Forms Migration Tool] Wrong type reference on some automatically generated SubForms

### PR DESCRIPTION
**Pull request by pefernan**
Copy of https://github.com/kiegroup/kie-wb-common/pull/1637

@jsoltes could you please review?

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins please execute full downstream build

**Comment by pefernan** [comment]
Jenkins please execute full downstream build

**Comment by pefernan** [comment]
Jenkins please execute full downstream build

**Comment by pefernan** [comment]
Jenkins please execute full downstream build

**Comment by pefernan** [comment]
Jenkins please execute full downstream build

**Comment by pefernan** [comment]
Jenkins please execute full downstream build

**Comment by pefernan** [comment]
jenkins please execute full downstream build

**Comment by pefernan** [comment]
jenkins please execute full downstream build

**Comment by pefernan** [comment]
jenkins please execute full downstream build

**Comment by pefernan** [comment]
jenkins please execute full downstream build

**Comment by pefernan** [comment]
Jenkins please execute full downstream build

**Comment by jsoltes** [comment]
@pefernan I wonder why we needed full downstream build for this. :)

**Comment by pefernan** [comment]
@jsoltes this change doesn't affect anything on the workbench so the downstream wasn't really needed here... but I prefer having all greens so nobody can complain if I merge this hehe :laughing:

**Comment by jsoltes** [comment]
@pefernan I understand, but I think we should use FDB wisely to save the jenkins capacity... And also, I could approve this 7 days ago. :)

**Comment by jsoltes** [comment]
@pefernan Looks good! can you just please add some default placeholder for migrated fields?

**Comment by pefernan** [comment]
@jsoltes changes added. Should we wait for the downstream build?

**Comment by pefernan** [comment]
jenkins retest this

**Pull request merged**
