### PR TITLE
DROOLS-4107: [DMN Designer] Change data type of decision table.

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-4107

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by danielzhe** [comment]
It worked without any error. Thank you.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Pull request merged**
