### PR TITLE
RHPAM-3190: Stunner - Error is displayed when using BPMN designer editor

### PR DESCRIPTION
**Pull request by karreiro**
**JIRA**: [RHPAM-3190](https://issues.redhat.com/browse/RHPAM-3190): RHPAM-3190: Stunner - Error is displayed when using BPMN designer editor

**Artifact (it happens on Business Central only)**: [WAR file v2](https://www.dropbox.com/s/mllt9lkwfj8ydt6/business-central-RHPAM-3190-2.war?dl=0)

**Before:**

**After:**

---

<pre>
To retest a PR or trigger a specific build please add a comment:

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</pre>

### CODE REVIEW

**Review by romartin — APPROVED** [review]

**Comment by LuboTerifaj** [comment]
Jenkins execute fdb

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @karreiro , unfortunately it's not possible to save the changes made in the process at all.

**Comment by karreiro** [comment]
Thanks for reporting, @LuboTerifaj.

The on-save-issue is fixed now. I've applied the fix on a separate commit and I've updated the PR description with the updated artifact.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Review by LuboTerifaj — APPROVED** [review]
Hello @karreiro ,

I didn't find any more issues.

Thanks for the fix!

**Pull request merged**
