### PR TITLE
JBPM-9755 - Support for node/events metadata attributes

### PR DESCRIPTION
**Pull request by Josephblt**
It is now possible to add metadata attributes to all nodes.

**JIRA**: [JBPM-9755](https://issues.redhat.com/browse/JBPM-9755)

**Referenced Pull Requests**:
https://github.com/kiegroup/kogito-editors-java/pull/64

**Business Central**: [WAR file](https://drive.google.com/file/d/1wII3aubAVdSiDYoN08ACxEmVBsYLGFxW/view?usp=sharing)

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins do cdb
Jenkins do fdb

**Comment by Josephblt** [comment]
Jenkins do fdb

**Review by romartin — APPROVED** [review]

**Comment by Josephblt** [comment]
Jenkins do fdb

**Comment by Josephblt** [comment]
Jenkins do fdb

**Comment by Josephblt** [comment]
Jenkins do fdb

**Comment by Josephblt** [comment]
Jenkins do fdb
Jenkins do cdb

**Comment by domhanak** [comment]
Any ideas about the FDB failiures? Could you please refire?

**Review by domhanak — APPROVED** [review]
LGTM.

*Acceptance criteria*
I was able to add Metadata attribute to every single available node from our Editor's palette in business central. :heavy_check_mark: 
I was not able to add metadata attributes to sequences. :heavy_check_mark: 
I was able to delete the metadata attributes properly. :heavy_check_mark: 
I was able to save process & the metadata attributes were correctly saved. :heavy_check_mark: 
I was not able to input name with invalid characters :heavy_check_mark: 

Example of a XML from node with metadata attributes:
```
<bpmn2:exclusiveGateway id="_454DE2BE-B158-4D04-B52E-FE3694FD319A">
      <bpmn2:extensionElements>
        <drools:metaData name="gate64">
          <drools:metaValue><![CDATA[gate64]]></drools:metaValue>
        </drools:metaData>
      </bpmn2:extensionElements>
    </bpmn2:exclusiveGateway>
    ```

**Comment by domhanak** [comment]
Please refire the FDB if it is necesarry, otherwise we should be good to merge. @inodeman

**Comment by Josephblt** [comment]
Jenkins do fdb

**Comment by Josephblt** [comment]
Jenkins do fdb

**Comment by Josephblt** [comment]
Jenkins do fdb

**Comment by hasys** [comment]
Hi @mareknovotny, @Josephblt, @romartin,

Looks like full downstream build is broken on some other repository:
<details>
  <summary>Error from the log file</summary>
  <pre>[INFO] Reactor Summary for jBPM Workitems 7.59.0-SNAPSHOT:
[INFO] 
[INFO] jBPM Workitems ..................................... SUCCESS [  7.212 s]
[INFO] Template Resources ................................. SUCCESS [  1.914 s]
[INFO] Archive ............................................ SUCCESS [ 31.991 s]
[INFO] Exec ............................................... SUCCESS [ 21.778 s]
[INFO] FTP ................................................ SUCCESS [ 15.916 s]
[INFO] Jabber ............................................. SUCCESS [ 13.482 s]
[INFO] Java ............................................... SUCCESS [ 19.671 s]
[INFO] JPA ................................................ SUCCESS [ 27.396 s]
[INFO] Parser ............................................. SUCCESS [ 11.949 s]
[INFO] RSS ................................................ SUCCESS [ 14.952 s]
[INFO] Transform .......................................... SUCCESS [  9.816 s]
[INFO] Google Calendar .................................... SUCCESS [ 17.568 s]
[INFO] Google Mail ........................................ SUCCESS [ 15.673 s]
[INFO] Google Sheets ...................................... SUCCESS [ 15.802 s]
[INFO] Google Tasks ....................................... SUCCESS [ 15.717 s]
[INFO] Google Drive ....................................... SUCCESS [ 19.685 s]
[INFO] Google Translate ................................... SUCCESS [ 14.654 s]
[INFO] IBM Watson ......................................... SUCCESS [ 16.135 s]
[INFO] Dropbox ............................................ SUCCESS [ 14.299 s]
[INFO] IFTTT .............................................. SUCCESS [ 15.004 s]
[INFO] Twitter ............................................ SUCCESS [ 15.871 s]
[INFO] Github ............................................. SUCCESS [ 16.491 s]
[INFO] Jira ............................................... SUCCESS [ 17.164 s]
[INFO] Ethereum ........................................... SUCCESS [ 24.866 s]
[INFO] Camel .............................................. SUCCESS [ 35.992 s]
[INFO] Weather Info ....................................... SUCCESS [ 19.141 s]
[INFO] Maven Embedder ..................................... SUCCESS [01:17 min]
[INFO] Slack .............................................. SUCCESS [ 14.206 s]
[INFO] PDF ................................................ SUCCESS [ 15.363 s]
[INFO] Execute SQL ........................................ SUCCESS [ 13.061 s]
[INFO] Riot Games ......................................... SUCCESS [ 15.894 s]
[INFO] Pastebin ........................................... SUCCESS [ 12.233 s]
[INFO] Vimeo .............................................. SUCCESS [ 13.257 s]
[INFO] Kafka .............................................. SUCCESS [ 14.653 s]
[INFO] Google Maps ........................................ SUCCESS [ 14.985 s]
[INFO] Okta ............................................... SUCCESS [ 15.459 s]
[INFO] Docker ............................................. SUCCESS [ 21.493 s]
[INFO] Long Running REST .................................. SUCCESS [01:15 min]
[INFO] Repository ......................................... SUCCESS [ 22.998 s]
[INFO] Repository SpringBoot .............................. SUCCESS [ 10.499 s]
[INFO] Repository WildFly ................................. SUCCESS [ 20.916 s]
[INFO] karaf-itests ....................................... SUCCESS [  9.807 s]
[INFO] jBPM :: WorkItem :: SpringBoot :: IntegrationTests . FAILURE [  6.675 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13:48 min
[INFO] Finished at: 2021-08-05T11:50:40-04:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "business-central" could not be activated because it does not exist.
[WARNING] The requested profile "wildfly" could not be activated because it does not exist.
[WARNING] The requested profile "sourcemaps" could not be activated because it does not exist.
[WARNING] The requested profile "no-showcase" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project jbpm-workitem-itests: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -&gt; [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project jbpm-workitem-itests: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
    at org.apache.maven.plugins.enforcer.EnforceMojo.execute (EnforceMojo.java:243)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] <a href="http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException">http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException</a>
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn &lt;args&gt; -rf :jbpm-workitem-itests
[INFO]  Archive artifact won't be executed
[ERROR]  [kiegroup/jbpm-work-items] error executing command 'mvn -e -nsu clean install -Dfull -Pbusiness-central,wildfly,sourcemaps,no-showcase -Dcontainer=wildfly -Dcontainer.profile=wildfly -Dintegration-tests=true -Dcargo.ignore.failures=true -Dmaven.test.failure.ignore=true -Dmaven.test.redirectTestOutputToFile=true -Dgwt.compiler.localWorkers=1 -Dwebdriver.firefox.bin=/opt/tools/firefox-60esr/firefox-bin -Dgwt.skipCompilation=true -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -s /home/jenkins/workspace/KIE/main/fdb/kie-wb-common-main.fdb@tmp/config1895249044218166231tmp -Dmaven.wagon.http.ssl.insecure=true'
[ERROR]  Command executions have failed, please review latest execution Error: [kiegroup/jbpm-work-items] error executing command 'mvn -e -nsu clean install -Dfull -Pbusiness-central,wildfly,sourcemaps,no-showcase -Dcontainer=wildfly -Dcontainer.profile=wildfly -Dintegration-tests=true -Dcargo.ignore.failures=true -Dmaven.test.failure.ignore=true -Dmaven.test.redirectTestOutputToFile=true -Dgwt.compiler.localWorkers=1 -Dwebdriver.firefox.bin=/opt/tools/firefox-60esr/firefox-bin -Dgwt.skipCompilation=true -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -s /home/jenkins/workspace/KIE/main/fdb/kie-wb-common-main.fdb@tmp/config1895249044218166231tmp -Dmaven.wagon.http.ssl.insecure=true'
</pre>
</details>

**Comment by domhanak** [comment]
jenkins do fdb

**Comment by romartin** [comment]
Hey guys,

The FDB is failing again and again but due to another reaons, not due to this PR updates. So I'll proceed on merging.

Thanks!

**Pull request merged**
