### PR TITLE
[7.14.x] JBPM-7997: garbled message in start process form when OS locale is Japanese

### PR DESCRIPTION
**Pull request by pefernan**
Backport of https://github.com/kiegroup/kie-wb-common/pull/2353

This is part of an ensemble, please merge with:
https://github.com/kiegroup/kie-wb-common/pull/2354
https://github.com/kiegroup/jbpm-wb/pull/1263

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute compile downstream build

**Comment by pefernan** [comment]
Jenkins execute compile downstream build

**Comment by mbiarnes** [comment]
Jenkins execute compile downstream build

**Comment by pefernan** [comment]
Jenkins execute compile downstream build

**Comment by pefernan** [comment]
it seems that jenkins is frozen, closing PR

**Pull request closed without merging**
