### PR TITLE
Make Name/documentation fields flat

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin, this is beginning of the migration to new models for both BC and Kogito.

For now it compiles and all tests passing. But at runtime I found an issue I will address next week.

What is done:
* General Set (Name and Documentation) is flat now, no usage of classes Name and Documentation.
* Marshallers works at runtime
* On the canvas I can't see name of the node any more. This is a bug I will start with next time.

Overall so far looks feasible and I think it's better to do on both for BC and Kogito because BC has much better test coverage so it's easier to catch bugs during migration before runtime tests.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by romartin** [comment]
hey @hasys 

Looking at code ,it looks good to me! I would say that once you're happy with this partial model updates, just please move the PR as a **regular PR**, and let us know to **start review**. I would vote for having this merged ASAP, and so we'll keep doing further iterations on the model updates, as commented.

Thanks!

**Comment by LuboTerifaj** [comment]
Hi @hasys , @romartin , is there a jira for this PR? Thanks!

**Comment by romartin** [comment]
just sending a reminder for myself in order to review this @romartin

**Comment by romartin** [comment]
@hasys can you move this to the new kogito-editors repository please? Thx!

**Comment by hasys** [comment]
This work will be continued under [BAPL-1658](https://issues.redhat.com/browse/BAPL-1658)

**Pull request closed without merging**
