### PR TITLE
Exclude not needed Hibernate deps

### PR DESCRIPTION
**Pull request by psiroky**
@wmedvede could you please take a look?

### CODE REVIEW

**Comment by manstis** [comment]
See https://github.com/kiegroup/kie-wb-common/pull/754 for build fix.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by wmedvede** [comment]
Hello @psiroky , thanks for the explanations regarding the hibernate deps.

I think the exclusion will have to be added also here

https://github.com/wmedvede/kie-wb-common/blob/3468925b9e39346b5f00ea382248292b3219123d/kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-backend/pom.xml#L193-L193

The hibernate-envers is algo being used at:

https://github.com/wmedvede/kie-wb-common/blob/3468925b9e39346b5f00ea382248292b3219123d/kie-wb-common-screens/kie-wb-common-data-modeller/kie-wb-common-data-modeller-client/pom.xml#L197-L197
but in this case only with test scope, so the exclusion is probably not requried here.

Thanks

**Comment by psiroky** [comment]
Thanks @wmedvede, I will take a look.

**Comment by psiroky** [comment]
@wmedvede I've removed the test scoped dependency as it is not used and added the second exclude.

**Comment by wmedvede** [comment]
@psiroky great, thanks.
+1 in case it requires it.

**Pull request merged**
