### PR TITLE
[JBPM-9163] Couldn't find any server running in 'development' mode ERROR after creating server template manually

### PR DESCRIPTION
**Pull request by elguardian**
added default mode to the server template

### CODE REVIEW

**Comment by Rikkola** [comment]
@barboras7 you are marked as the contact in the ticket. If your not the right person please help us find the right one :)

**Comment by barboras7** [comment]
Hi @Rikkola,
I reassigned the review to @Srihari1192. He's going to take a look at this :)

**Comment by Srihari1192** [comment]
Jenkins execute full downstream build

**Comment by Srihari1192** [comment]
Jenkins execute full downstream build

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by Srihari1192** [comment]
Jenkins execute full downstream build

**Comment by elguardian** [comment]
@Srihari1192 the only ones that matter are Pull Request Execution and sonar cloud. The rest are under test by prod team. you should not keep those in mind.

**Pull request merged**
