### PR TITLE
DROOLS-3467: [DMN Designer] Two vertical scrollbars

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-3467

You need to run `drools-wb-webapp` or `business-central` to see the fix.

### CODE REVIEW

**Comment by danielzhe** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by danielzhe** [comment]
Jenkins please retest this

**Comment by manstis** [comment]
@jomarko Could you please review (so we can get in for this Friday?!)

**Pull request merged**
