### PR TITLE
KOGITO-683 : Cannot Import Process : Import Fails

### PR DESCRIPTION
**Pull request by inodeman**
Hi @hasys @romartin can you check this PR?

### CODE REVIEW

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by inodeman** [comment]
Hi @romartin I checked with @tiagodolphine we saw that using MarshallingMessage by the InputAssignments would take a lot of refactoring, he suggestes I threw exception then catch it and construct a Marshalling Message, I tried that but then the import would fail, I am just using a Marshalling Message to log, in the future we can do a refactoring to propertly set, what do you think?

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@inodeman let's please have a quick call to discuss it, I would like to have some more detail before providing more feedback. So plz ping me when you've a chance.

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by inodeman** [comment]
Hi @romartin changed the null return to optional, can you check this PR please?

**Comment by romartin** [comment]
@LuboTerifaj @domhanak you want also to check this PR or can I already merge? Thx!

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by domhanak** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
FDB failed. Rerunning just to be sure, logs does give much info on the error.

```
Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.8.2:compile (gwt-compile) on project kie-wb-common-stunner-bpmn-kogito-runtime: Command failed with status 1
```

**Comment by romartin** [comment]
Hey @domhanak @inodeman 

I think I'm having the error in the FDB in this PR https://github.com/kiegroup/kie-wb-common/pull/3012
Trying to analyze it now... did you arlready found something @inodeman ?

**Comment by domhanak** [comment]
@romartin I think `error 137` suggests memory issues or insufficient memory

```
For reference the status code 137 (128 + 9) typically means (can differ between flavours of unix). That the process was terminated by receipt of a signal. In this case signal 9 which is SIGKILL and unblockable kill. 
```

**Comment by domhanak** [comment]
@mbiarnes  Hi Michael, could you please help with FDB errors here? I can't find any clue to pursue, i suspect the issue is with either:

- too much memory
`
 JVM will freely increase its memory up to the maximum heap size, but if there's not enough real memory, the OS will kill the process. However, if you reduce the max heap size, the JVM won't try to increase its memory so highly, so the OS won't worry about it enough to kill it.
`
- not enough memory

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by domhanak** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
@inodeman Hi Jaime, I managed to import the process from JIRA but I do see only empty diagram.

**Comment by domhanak** [comment]
I added
`
window.frames.editorFrame.contentWindow.gwtEditorBeans.get("BPMNDiagramEditor").get().getContent()
`
and I see
Screenshot from 2020-01-22 14-25-14

**Comment by inodeman** [comment]
Hi @domhanak , just tested it, seems something is conflicting when I rebased, let me check and make sure it works

**Comment by inodeman** [comment]
Hi @domhanak fixed the issue, the problem was that Kogito now can provide path, but the javascript used in Kogito Runtime web app needed to be updated, I added a temporary path, will update to use it properly on ticket https://issues.redhat.com/browse/KOGITO-631

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by domhanak** [comment]
@inodeman Cool, thanks. Gonna try again! :)

**Comment by domhanak** [comment]
@inodeman Ok, so it worked for me. However, I run into some issues.

- didn't open for the first time. Not sure if the gwt server didn't run yet but I managed to make it work.

- When I open test.html and load some diagram from the disk I see this in logs.:
```
TypeError: window.frames.editorFrame.contentWindow.gwtEditorBeans is undefined
```
evenutally the diagram loads.

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
**Still waiting for FDB** successful for merging ....

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Hi @romartin FDB is green now :-)

**Pull request merged**
