### PR TITLE
Fix failing test in DMNDeleteNodeToolboxActionTest

### PR DESCRIPTION
**Pull request by danielzhe**
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by danielzhe** [comment]
jenkins do fdb

**Review by manstis — APPROVED** [review]

**Review by vpellegrino — APPROVED** [review]

**Review by yesamer — APPROVED** [review]

**Comment by danielzhe** [comment]
Waiting for green to be 100% sure that it fixes before merge...

**Comment by danielzhe** [comment]
jenkins retest

**Comment by danielzhe** [comment]
Jenkins please retest this

**Comment by danielzhe** [comment]
Jenkins retest this

**Review by romartin — APPROVED** [review]

**Comment by danielzhe** [comment]
The failing test is not related:
Test Result (1 failure / +1)
org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT

**Comment by danielzhe** [comment]
@kiegroup/gatekeepers Merge, please. The failing test is not related (org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT)

**Pull request merged**
