### PR TITLE
JBPM-6325 New instance editor in radiogorup/listbox allows you to create invalid options.

### PR DESCRIPTION
**Pull request by alessioscalici**
**WARNING** to be merged after https://github.com/kiegroup/kie-wb-common/pull/1156
This is the same as https://github.com/kiegroup/kie-wb-common/pull/1162, pointing to **master** branch.

@pefernan @jsoltes can you take a look?

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
@jsoltes it cannot be tested for now, this annotations are processed on compile time and generate some code for the fields properties forms. We might think on a way to test all of these.

**Comment by jsoltes** [comment]
@pefernan I see.

**Comment by pefernan** [comment]
@jsoltes is it ok to merge?

**Comment by pefernan** [comment]
Thank you @alessioscalici

**Pull request merged**
