### PR TITLE
JBPM-9080: use proper test runner

### PR DESCRIPTION
**Pull request by jomarko**
Without using GwtMockitoTestRunner test of gwt components fails
For more details see https://issues.redhat.com/browse/JBPM-9080

### CODE REVIEW

**Comment by jomarko** [comment]
@mareknovotny sould you mind to have a look? this should solve the issue in daily build https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/daily-build/job/daily-build-pipeline-master/148/testReport/org.kie.workbench.common.stunner.bpmn.client.forms.fields.assignmentsEditor/AssignmentListItemWidgetViewImplTest/testNameChangeToMIVariableName/

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
jenkins please retest this

**Pull request merged**
