### PR TITLE
[7.3.x] JBPM-6284: Slider and Multiple SubForm break the consistency with "ReadOnly" and "ValidateOnChange" labels.

### PR DESCRIPTION
**Pull request by jsoltes**
This is a cherrypick from 7.2.x (https://github.com/kiegroup/kie-wb-common/pull/1040).

@manstis could you please review?

### CODE REVIEW

**Comment by manstis** [comment]
@jsoltes Please let me know when it's green and I'll merge..

**Comment by jsoltes** [comment]
@manstis sure

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
@manstis could you merge this please?

**Pull request merged**
