### PR TITLE
DROOLS-5332: [DMN Designer] Unable to open BKM editor

### PR DESCRIPTION
**Pull request by vpellegrino**
*Please refer to:* https://issues.redhat.com/browse/DROOLS-5332

*Defect description:* Fix introduced in https://issues.redhat.com/browse/DROOLS-5178 causes the `typeRef` to be null for output clauses

*Proposed solution:* Instead of setting typeRef to null, setting it to `<undefined>`

Now we are able to display BKM nodes properly:
image
image

### CODE REVIEW

**Comment by manstis** [comment]
Presumably, if the server-side marshaller, did not have the same issue the `typeRef` was always non-`null`. Therefore does this PR fix the _symptom_ of the issue that the client-side marshaller is not guaranteeing non-`null` values for some `typeRef`? Did you try opening **AND** saving the file attached to the JIRA? I wonder if the `null` `typeRef` could still cause problems when saving.

**Comment by vpellegrino** [comment]
> Presumably, if the server-side marshaller, did not have the same issue the `typeRef` was always non-`null`. Therefore does this PR fix the _symptom_ of the issue that the client-side marshaller is not guaranteeing non-`null` values for some `typeRef`? Did you try opening **AND** saving the file attached to the JIRA? I wonder if the `null` `typeRef` could still cause problems when saving.

Yes, the save it does not work. I assure the issue is still related to typeRef null values. 
@all what should be the right approach to be roboust against typeRef null values? 
Can you point me to some reference about what we are doing on server side.

**Comment by manstis** [comment]
Hi, @vpellegrino 

With the server-side marshalling of XML to an object model Errai calls objects' zero parameter constructors (for [example](https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/model/InputClauseLiteralExpression.java#L101)) when deserializing the objects in the browser following completion of the remote procedure call. i.e. [server side: XML -> POJO] -- serialised --> [browser: Errai calls zero-parameter constructor, Errai sets properties, object deserialisation complete]. Most zero parameter constructors for classes in the DMN model set non-`null` defaults for many fields (including `typeRef`).

Client-side marshalling does not call the zero-parameter constructors.

This _could_ be the explanation; however you don't say what object does not have the `typeRef` set or whether the `typeRef` is set but a component is `null` (localpart, alias etc) so it's difficult to say exactly what the fix should be.

Now you have identified that a `typeRef` is incorrectly `null` I would step through the client-side marshaller (it's probably a issue in the [converters](https://github.com/kiegroup/kie-wb-common/tree/master/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/model)) and identify why it was set to `null`.

IF everywhere uses [QNamePropertyConverter](https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/model/QNamePropertyConverter.java#L29) we should not have `null` values (as you can see the code should return an `UNDEFINED` value).

**Comment by vpellegrino** [comment]
@manstis please have a look now. I just want to be sure that setting `typeRef` to `<undefined>` it does not introduce again validation issue raised with https://issues.redhat.com/browse/DROOLS-5178
Could you please double check? Thanks

**Comment by manstis** [comment]
Hi @vpellegrino thank-you for the update. Whilst the update looks great, the JIRA mentioned in the comment on the changed line set me thinking.... 

We have the same [code](https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/DecisionTablePropertyConverter.java#L75) for the server-side marshalling that works OK. However even though we set it to `null` Errai would have called the default [constructor](https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/model/OutputClause.java#L81) when de-serializing the `OutputClause` object in the browser and hence set the `typeRef` [to](https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/property/dmn/QName.java#L38) `UNDEFINED` (as you are now explicitly doing in the client-side marshaller).

Therefore I think this PR is fine.

However think it worth a couple of checks:
- Can files saved with the client-side marshaller be re-opened in Business Central and the issue reported on DROOLS-5178 not be evident? i.e. by having a non-`null` `typeRef` are we re-introducing the original issue. I think we're OK as it appears we [consider](https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/model/QNamePropertyConverter.java#L54) `UNDEFINED` to be `null`. 
- Confirm the `OutputClause.typeRef` in Business Central, client-side, is indeed `UNDEFINED` as we expect.

I think it worth performing these two checks to put our minds at rest that we're not likely to be breaking anything with the change in this PR.

**Comment by vpellegrino** [comment]
> Hi @vpellegrino thank-you for the update. Whilst the update looks great, the JIRA mentioned in the comment on the changed line set me thinking....
> 
> We have the same [code](https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-dmn/kie-wb-common-dmn-backend/src/main/java/org/kie/workbench/common/dmn/backend/definition/v1_1/DecisionTablePropertyConverter.java#L75) for the server-side marshalling that works OK. However even though we set it to `null` Errai would have called the default [constructor](https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/model/OutputClause.java#L81) when de-serializing the `OutputClause` object in the browser and hence set the `typeRef` [to](https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/property/dmn/QName.java#L38) `UNDEFINED` (as you are now explicitly doing in the client-side marshaller).
> 
> Therefore I think this PR is fine.
> 
> However think it worth a couple of checks:
> 
> * Can files saved with the client-side marshaller be re-opened in Business Central and the issue reported on DROOLS-5178 not be evident? i.e. by having a non-`null` `typeRef` are we re-introducing the original issue. I think we're OK as it appears we [consider](https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/model/QNamePropertyConverter.java#L54) `UNDEFINED` to be `null`.
> * Confirm the `OutputClause.typeRef` in Business Central, client-side, is indeed `UNDEFINED` as we expect.
> 
> I think it worth performing these two checks to put our minds at rest that we're not likely to be breaking anything with the change in this PR.

Hi @manstis 

Let's start with an assumption:
With and Without my changes (starting from fresh master instance), I am not able to save on client-side (kogito-testing) the original `fraud.dmn` (downloaded from https://kiegroup.github.io/kogito-online/?file=https://gist.githubusercontent.com/r00ta/89e8688889a36e16d74789cf3bb92565/raw/ba345e57efef37b4d180dd725cebeb80b5e214b6/fraud.dmn#/editor/dmn) due to errors below:
```
Error: java.lang.ClassCastException
    at qcf_g$.aHb_g$ [as createError_0_g$] (Throwable.java:120)
    at qcf_g$.kHb_g$ [as initializeBackingError_0_g$] (Throwable.java:112)
    at qcf_g$.VGb_g$ (Throwable.java:66)
    at qcf_g$.zHb_g$ (Exception.java:29)
    at qcf_g$.pLc_g$ (RuntimeException.java:29)
    at new qcf_g$ (ClassCastException.java:27)
    at Dzm_g$ (InternalPreconditions.java:154)
    at Pzm_g$ (InternalPreconditions.java:138)
    at Ozm_g$ (InternalPreconditions.java:133)
    at Y6h_g$ (Cast.java:155)
    at c4M_g$ (UnaryTestsPropertyConverter.java:76)
    at v1M_g$ (ItemDefinitionPropertyConverter.java:129)
    at X61_g$ (DefinitionsConverter.java:164)
    at eEw_g$.kEw_g$ [as marshall_0_g$] (DMNMarshallerKogitoMarshaller.java:150)
    at oEw_g$.yEw_g$ [as marshall_0_g$] (Type_factory__o_k_w_c_d_w_k_c_c_c_DMNMarshallerKogitoMarshaller__quals__j_e_i_Any_j_e_i_Default.java:67)
    at kMw_g$.tMw_g$ [as marshall_1_g$] (DMNClientDiagramServiceImpl.java:234)
    at kMw_g$.M01_g$ [as lambda$2_166_g$] (DMNClientDiagramServiceImpl.java:202)
    at Function.t71_g$ (DMNClientDiagramServiceImpl.java:199)
    at lambda_0_g$ (Runtime.java:166)
    at new Promise (<anonymous>)
    at dQU_g$.hQU_g$ [as create_77_g$] (Promises.java:200)
    at kMw_g$.wMw_g$ [as transform_28_g$] (DMNClientDiagramServiceImpl.java:199)
    at AMw_g$.QMw_g$ [as transform_28_g$] (Type_factory__o_k_w_c_d_w_k_c_c_s_DMNClientDiagramServiceImpl__quals__j_e_i_Any_j_e_i_Default.java:83)
    at M21_g$.AOM_g$ [as getContent_5_g$] (AbstractDMNDiagramEditor.java:403)
    at M21_g$.mPM_g$ [as doSave_2_g$] (DMNDiagramEditor.java:234)
    at CPM_g$.DPM_g$ [as execute_3_g$] (DMNDiagramEditor.java:185)
    at s0U_g$ (ListBarWidgetImpl.java:466)
    at G1U_g$.H1U_g$ [as onClick_6_g$] (ListBarWidgetImpl.java:466)
    at qCh_g$.rCh_g$ [as dispatch_46_g$] (ClickEvent.java:56)
    at qCh_g$.sCh_g$ [as dispatch_2_g$] (ClickEvent.java:55)
    at qCh_g$.Ju_g$ [as dispatch_1_g$] (GwtEvent.java:76)
    at vMh_g$ (EventBus.java:40)
    at XMh_g$.GMh_g$ [as doFire_0_g$] (SimpleEventBus.java:193)
    at XMh_g$.MMh_g$ [as fireEvent_4_g$] (SimpleEventBus.java:88)
    at kMh_g$.nMh_g$ [as fireEvent_1_g$] (HandlerManager.java:127)
    at lMn_g$.wPc_g$ [as fireEvent_1_g$] (Widget.java:129)
    at qBh_g$ (DomEvent.java:125)
    at lMn_g$.EPc_g$ [as onBrowserEvent_0_g$] (Widget.java:177)
    at IRi_g$ (DOM.java:1481)
    at HRi_g$ (DOM.java:1420)
    at HTMLButtonElement.ZXi_g$ (DOMImplStandard.java:317)
    at jag_g$ (Impl.java:309)
    at mag_g$ (Impl.java:361)
    at HTMLButtonElement.<anonymous> (Impl.java:78)
```

So, about the checks you are asking:
1) How can I verify DROOLS-5178 non-regression if I am not able to save the original `fraud.dmn` and to reopen it on Business Central?
2) If I understand correctly your request, I can confirm that I am able to check that the typeref for the output clause is `<UNDEFINED` for both Business Central and on client-side (after my changes).

**Comment by manstis** [comment]
Hi @vpellegrino,

Thank-you for your comments.

Given "With and Without my changes... I am not able to save on client-side" then we're not able to test anything relating to "Save". IDK this was the situation. I assume the saving issue will be tracked as a new JIRA. If both Business Central and _kogito_ (with your changes) give an `OutputClause` with `typeRef` of `<UNDEFINED>` then great! We know the operation is consistent.

**Comment by vpellegrino** [comment]
To be honest, I am not sure

> Thank-you @vpellegrino; following our conversation the code change is fine. Should there be some form of test for the change to protect against future regressions? IDK if the class has existing tests? It was difficult to unit test client-side marshallers and it might therefore be necessary to write a new Selenium test? I think @jomarko will have good ideas about how best to address this.

To be Honest, I am not sure what kind of tests might be added as *unit* tests.
I am not an expert on Selenium automation suite, but maybe, a Selenium test case, that reproduces the original issue, could be added. Let's see what @jomarko thinks.

**Comment by manstis** [comment]
@vpellegrino Hello, I was meaning put a unit test [here](https://github.com/kiegroup/kie-wb-common/tree/master/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/converters/model) for `DecisionTablePropertyConverter` to verify the `typeRef` is `UNDEFINED`.

**Comment by vpellegrino** [comment]
Thank you for your suggestions @manstis 
Please let me know if there is anything else to improve there

**Comment by vpellegrino** [comment]
Unfortunately there is some issue while testing client side marshaller, both with GWT life cycle and mocking static methods used by the converter.
My suggestion is to cover this part with a selenium test case. 
About saving issue, I am going to track a JIRA defect and link it to this one.

**Comment by karreiro** [comment]
Jenkins please retests this.

**Comment by karreiro** [comment]
Jenkins please retests this.

**Comment by vpellegrino** [comment]
@kiegroup/gatekeepers hi, could you please merge it?

**Pull request merged**
