### PR TITLE
Kogito 198 - Removing Submarine Diagram/Metadata and Refactor Stunner Submarine Extension

### PR DESCRIPTION
**Pull request by tiagodolphine**

### CODE REVIEW

**Comment by tiagodolphine** [comment]
@manstis can you please take a look on this PR, I removed the Submarine Diagram/Metadata and changed Stunner submarine module to kogito.

**Comment by tiagodolphine** [comment]
@manstis I fixed the tests and rebased with DROOLS-3727.
Just to let you know this PR will rename/remove the submarine stuff from stunner module, but it is missing the **kie-wb-common-submarine** that will be refactored on a new PR. 
Thanks.

**Comment by tiagodolphine** [comment]
last commit rebased and solved conflicts.

**Comment by manstis** [comment]
LGTM @tiagodolphine merge whenever you please.

**Pull request merged**
