### PR TITLE
JBPM-8734 Stunner - Date/Time widget reset time zone value to default…

### PR DESCRIPTION
**Pull request by treblereel**
… for existing notifications

JIRA: https://issues.jboss.org/browse/JBPM-8734

### CODE REVIEW

**Comment by treblereel** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @treblereel,

build is generated, but verification is blocked by Workbench issue: https://issues.jboss.org/browse/JBPM-8750

**Comment by treblereel** [comment]
> Hi @treblereel,
> 
> build is generated, but verification is blocked by Workbench issue: https://issues.jboss.org/browse/JBPM-8750

omg, could i fix it somehow or i need to wait ?

**Comment by treblereel** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by treblereel** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Build is not generated due to network issues.

<details>
  <summary>Error log</summary>
  <pre>20:05:17 [INFO] Drools Workbench - WebApp .......................... FAILURE [32:04 min]
20:05:17 [INFO] ------------------------------------------------------------------------
20:05:17 [INFO] BUILD FAILURE
20:05:17 [INFO] ------------------------------------------------------------------------
20:05:17 [INFO] Total time: 01:04 h
20:05:17 [INFO] Finished at: 2019-08-29T16:05:16-04:00
20:05:18 [INFO] Final Memory: 614M/1764M
20:05:18 [INFO] ------------------------------------------------------------------------
20:05:18 [WARNING] The requested profile "business-central" could not be activated because it does not exist.
20:05:18 [WARNING] The requested profile "wildfly" could not be activated because it does not exist.
20:05:18 [WARNING] The requested profile "sourcemaps" could not be activated because it does not exist.
20:05:18 [ERROR] Failed to execute goal org.kie:kie-gwthelper-maven-plugin:1.3:add-source (add-source) on project drools-wb-webapp: Execution add-source of goal org.kie:kie-gwthelper-maven-plugin:1.3:add-source failed: Plugin org.kie:kie-gwthelper-maven-plugin:1.3 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven:maven-model-builder:jar:3.6.0 from/to central (https://repo.maven.apache.org/maven2): Read timed out -> [Help 1]
20:05:18 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.kie:kie-gwthelper-maven-plugin:1.3:add-source (add-source) on project drools-wb-webapp: Execution add-source of goal org.kie:kie-gwthelper-maven-plugin:1.3:add-source failed: Plugin org.kie:kie-gwthelper-maven-plugin:1.3 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven:maven-model-builder:jar:3.6.0 from/to central (https://repo.maven.apache.org/maven2): Read timed out
20:05:18     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
20:05:18     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
20:05:18     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
20:05:18     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
20:05:18     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
20:05:18     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
20:05:18     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
20:05:18     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
20:05:18     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
20:05:18     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
20:05:18     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
20:05:18     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
20:05:18     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
20:05:18     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
20:05:18     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
20:05:18     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
20:05:18     at java.lang.reflect.Method.invoke (Method.java:498)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
20:05:18 Caused by: org.apache.maven.plugin.PluginExecutionException: Execution add-source of goal org.kie:kie-gwthelper-maven-plugin:1.3:add-source failed: Plugin org.kie:kie-gwthelper-maven-plugin:1.3 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven:maven-model-builder:jar:3.6.0 from/to central (https://repo.maven.apache.org/maven2): Read timed out
20:05:18     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:106)
20:05:18     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
20:05:18     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
20:05:18     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
20:05:18     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
20:05:18     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
20:05:18     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
20:05:18     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
20:05:18     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
20:05:18     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
20:05:18     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
20:05:18     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
20:05:18     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
20:05:18     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
20:05:18     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
20:05:18     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
20:05:18     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
20:05:18     at java.lang.reflect.Method.invoke (Method.java:498)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
20:05:18 Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.kie:kie-gwthelper-maven-plugin:1.3 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven:maven-model-builder:jar:3.6.0 from/to central (https://repo.maven.apache.org/maven2): Read timed out
20:05:18     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:218)
20:05:18     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:149)
20:05:18     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm (DefaultMavenPluginManager.java:403)
20:05:18     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm (DefaultMavenPluginManager.java:374)
20:05:18     at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm (DefaultBuildPluginManager.java:231)
20:05:18     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:102)
20:05:18     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
20:05:18     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
20:05:18     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
20:05:18     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
20:05:18     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
20:05:18     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
20:05:18     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
20:05:18     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
20:05:18     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
20:05:18     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
20:05:18     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
20:05:18     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
20:05:18     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
20:05:18     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
20:05:18     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
20:05:18     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
20:05:18     at java.lang.reflect.Method.invoke (Method.java:498)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
20:05:18 Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.apache.maven:maven-model-builder:jar:3.6.0 from/to central (https://repo.maven.apache.org/maven2): Read timed out
20:05:18     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:422)
20:05:18     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:224)
20:05:18     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:338)
20:05:18     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:210)
20:05:18     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:149)
20:05:18     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm (DefaultMavenPluginManager.java:403)
20:05:18     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm (DefaultMavenPluginManager.java:374)
20:05:18     at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm (DefaultBuildPluginManager.java:231)
20:05:18     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:102)
20:05:18     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
20:05:18     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
20:05:18     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
20:05:18     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
20:05:18     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
20:05:18     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
20:05:18     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
20:05:18     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
20:05:18     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
20:05:18     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
20:05:18     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
20:05:18     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
20:05:18     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
20:05:18     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
20:05:18     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
20:05:18     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
20:05:18     at java.lang.reflect.Method.invoke (Method.java:498)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
20:05:18     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
20:05:18 Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache.maven:maven-model-builder:jar:3.6.0 from/to central (https://repo.maven.apache.org/maven2): Read timed out
20:05:18     at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed (ArtifactTransportListener.java:52)
20:05:18     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:365)
20:05:18     at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
20:05:18     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
20:05:18     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
20:05:18     at java.lang.Thread.run (Thread.java:748)
20:05:18 Caused by: org.apache.maven.wagon.TransferFailedException: Read timed out
20:05:18     at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData (AbstractHttpClientWagon.java:1068)
20:05:18     at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData (AbstractHttpClientWagon.java:962)
20:05:18     at org.apache.maven.wagon.StreamWagon.getInputStream (StreamWagon.java:126)
20:05:18     at org.apache.maven.wagon.StreamWagon.getIfNewer (StreamWagon.java:88)
20:05:18     at org.apache.maven.wagon.StreamWagon.get (StreamWagon.java:61)
20:05:18     at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run (WagonTransporter.java:567)
20:05:18     at org.eclipse.aether.transport.wagon.WagonTransporter.execute (WagonTransporter.java:435)
20:05:18     at org.eclipse.aether.transport.wagon.WagonTransporter.get (WagonTransporter.java:412)
20:05:18     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask (BasicRepositoryConnector.java:453)
20:05:18     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:360)
20:05:18     at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
20:05:18     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
20:05:18     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
20:05:18     at java.lang.Thread.run (Thread.java:748)
20:05:18 Caused by: java.net.SocketTimeoutException: Read timed out
20:05:18     at java.net.SocketInputStream.socketRead0 (Native Method)
20:05:18     at java.net.SocketInputStream.socketRead (SocketInputStream.java:116)
20:05:18     at java.net.SocketInputStream.read (SocketInputStream.java:171)
20:05:18     at java.net.SocketInputStream.read (SocketInputStream.java:141)
20:05:18     at sun.security.ssl.InputRecord.readFully (InputRecord.java:465)
20:05:18     at sun.security.ssl.InputRecord.read (InputRecord.java:503)
20:05:18     at sun.security.ssl.SSLSocketImpl.readRecord (SSLSocketImpl.java:975)
20:05:18     at sun.security.ssl.SSLSocketImpl.readDataRecord (SSLSocketImpl.java:933)
20:05:18     at sun.security.ssl.AppInputStream.read (AppInputStream.java:105)
20:05:18     at org.apache.maven.wagon.providers.http.httpclient.impl.io.SessionInputBufferImpl.streamRead (SessionInputBufferImpl.java:139)
20:05:18     at org.apache.maven.wagon.providers.http.httpclient.impl.io.SessionInputBufferImpl.fillBuffer (SessionInputBufferImpl.java:155)
20:05:18     at org.apache.maven.wagon.providers.http.httpclient.impl.io.SessionInputBufferImpl.readLine (SessionInputBufferImpl.java:284)
20:05:18     at org.apache.maven.wagon.providers.http.httpclient.impl.conn.DefaultHttpResponseParser.parseHead (DefaultHttpResponseParser.java:140)
20:05:18     at org.apache.maven.wagon.providers.http.httpclient.impl.conn.DefaultHttpResponseParser.parseHead (DefaultHttpResponseParser.java:57)
20:05:18     at org.apache.maven.wagon.providers.http.httpclient.impl.io.AbstractMessageParser.parse (AbstractMessageParser.java:261)
20:05:19     at org.apache.maven.wagon.providers.http.httpclient.impl.DefaultBHttpClientConnection.receiveResponseHeader (DefaultBHttpClientConnection.java:165)
20:05:19     at org.apache.maven.wagon.providers.http.httpclient.impl.conn.CPoolProxy.receiveResponseHeader (CPoolProxy.java:167)
20:05:19     at org.apache.maven.wagon.providers.http.httpclient.protocol.HttpRequestExecutor.doReceiveResponse (HttpRequestExecutor.java:272)
20:05:19     at org.apache.maven.wagon.providers.http.httpclient.protocol.HttpRequestExecutor.execute (HttpRequestExecutor.java:124)
20:05:19     at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.execute (MainClientExec.java:271)
20:05:19     at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.ProtocolExec.execute (ProtocolExec.java:184)
20:05:19     at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec.execute (RetryExec.java:88)
20:05:19     at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RedirectExec.execute (RedirectExec.java:110)
20:05:19     at org.apache.maven.wagon.providers.http.httpclient.impl.client.InternalHttpClient.doExecute (InternalHttpClient.java:184)
20:05:19     at org.apache.maven.wagon.providers.http.httpclient.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:82)
20:05:19     at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.execute (AbstractHttpClientWagon.java:834)
20:05:19     at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData (AbstractHttpClientWagon.java:985)
20:05:19     at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData (AbstractHttpClientWagon.java:962)
20:05:19     at org.apache.maven.wagon.StreamWagon.getInputStream (StreamWagon.java:126)
20:05:19     at org.apache.maven.wagon.StreamWagon.getIfNewer (StreamWagon.java:88)
20:05:19     at org.apache.maven.wagon.StreamWagon.get (StreamWagon.java:61)
20:05:19     at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run (WagonTransporter.java:567)
20:05:19     at org.eclipse.aether.transport.wagon.WagonTransporter.execute (WagonTransporter.java:435)
20:05:19     at org.eclipse.aether.transport.wagon.WagonTransporter.get (WagonTransporter.java:412)
20:05:19     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask (BasicRepositoryConnector.java:453)
20:05:19     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:360)
20:05:19     at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
20:05:19     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
20:05:19     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
20:05:19     at java.lang.Thread.run (Thread.java:748)
20:05:19 [ERROR] 
20:05:19 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
20:05:19 [ERROR] 
20:05:19 [ERROR] For more information about the errors and possible solutions, please read the following articles:
20:05:19 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
20:05:19 [ERROR] 
20:05:19 [ERROR] After correcting the problems, you can resume the build with the command
20:05:19 [ERROR]   mvn <goals> -rf :drools-wb-webapp
20:05:19 Unexpected error while executing the Downstream repositories builder for PR builds! Error while executing Maven process, non-zero exit code!
20:05:19 java.lang.RuntimeException: Error while executing Maven process, non-zero exit code!
20:05:19 	at org.kie.jenkinsci.plugins.kieprbuildshelper.MavenProject.build(MavenProject.java:68)
20:05:19 	at org.kie.jenkinsci.plugins.kieprbuildshelper.AbstractPRBuilder.perform(AbstractPRBuilder.java:130)
20:05:19 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
20:05:19 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
20:05:19 	at hudson.model.Build$BuildExecution.build(Build.java:206)
20:05:19 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
20:05:19 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
20:05:19 	at hudson.model.Run.execute(Run.java:1724)
20:05:19 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
20:05:19 	at hudson.model.ResourceController.execute(ResourceController.java:97)
20:05:19 	at hudson.model.Executor.run(Executor.java:429)
20:05:19 Build step 'Build dependent downstream repositories (for PR builds)' marked build as failure
20:05:19 Terminating xvnc.
20:05:19 $ vncserver -kill :63
20:05:19 Killing Xvnc process ID 10166
20:05:21 Recording test results
20:05:28 Skipping publisher since build result is FAILURE
20:05:28 Skipping publisher since build result is FAILURE
20:05:28 Archiving artifacts
20:05:49 Adding one-line test results to commit status...
20:05:49 Setting status of 755d8db358d6a711040896f358cb4bb87e2621f0 to FAILURE with url https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-common-downstream-pullrequests/320/ and message: 'Build finished. 3575 tests run, 9 skipped, 0 failed.'
20:05:49 Using context: Linux - full downstream
20:05:49 [WS-CLEANUP] Deleting project workspace...
20:05:49 [WS-CLEANUP] Deferred wipeout is used...
20:05:49 [WS-CLEANUP] done
20:05:49 Finished: FAILURE</pre>
</details>

Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @tiagodolphine, @inodeman, @Josephblt,

can I ask you to take a look as well? Thank you!

**Comment by hasys** [comment]
Not sure, why I got notification here, but it looks like it is good, since this issues looks like is the same with: https://github.com/kiegroup/kie-wb-common/pull/3286 I am closing this PR as duplicated. @handreyrc, please reopen this PR if it is not. Thank you!

**Pull request closed without merging**
