### PR TITLE
JBPM-8153 Container is removed from UI even though it was not possibl…

### PR DESCRIPTION
**Pull request by bxf12315**
…e to stop it.

**Thank you for submitting this pull request**

**JIRA**: [https://issues.redhat.com/browse/JBPM-8153](JBPM-8153)

**Referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-integration/pull/2276
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://donwnload.here/something)

**VS Code**: [plugin](https://donwnload.here/something)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by bxf12315** [comment]
Jenkins run cdb

**Comment by bxf12315** [comment]
Jenkins run cdb

**Review by sutaakar — APPROVED** [review]

**Review by nmirasch — APPROVED** [review]
LGTM

**Comment by elguardian** [comment]
@nmirasch  this is not really my repo. kie server is already merge. Do you mind to check and merge this one ?

**Pull request merged**
