### PR TITLE
Updating Spanish translation

### PR DESCRIPTION
**Pull request by albfan**
Now Zanata is decommissioned, looking for a temporal way to update translations. Starting from Spanish as it is my native language.

I was not sure about lines like:

    # ctx::sourcefile::Navigation Menu (system details)

so I prefer to keep it. @manstis  Let me know if they don't make sense, I can rework and remove it.

### CODE REVIEW

**Comment by kie-ci2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by manstis** [comment]
ok to test.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by albfan** [comment]
@jomarko Now the size of the task is clear. I looked into all the i18n dirs and found all the *.properties files needed to be translated.

Most of them are uptodate, but for your first screenshot:

kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/resources/org/kie/workbench/common/stunner/bpmn/resources/i18n/StunnerBPMNConstants.properties

it is a +400 keys not translated at all.

**Comment by jomarko** [comment]
@albfan I agree, I posted screenshots just for a record. To prevent someone seeing merged this and thinking all is translated now. Thank you for your PR once more time.

**Comment by albfan** [comment]
I'm trying to build a script util to report missing keywords by language.(Poor's man memsource)

**Pull request merged**
