### PR TITLE
[7.7.x][optional?] RHPAM-1010: Stunner - MI SubProcess CompletionCondition is not stored

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi @romartin @hasys 
Please see my comments in https://issues.jboss.org/browse/RHPAM-1010 and proceed accordingly if this will be in for the 7.0.2

Thanks.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
This was the failing test this time

org.kie.wb.test.rest.functional.JobIntegrationTest.org.kie.wb.test.rest.functional.JobIntegrationTest
org.kie.wb.test.rest.functional.ProjectIntegrationTest.org.kie.wb.test.rest.functional.ProjectIntegrationTest
org.kie.wb.test.rest.functional.RepositoryIntegrationTest.org.kie.wb.test.rest.functional.RepositoryIntegrationTest
org.kie.wb.test.rest.functional.RepositoryIntegrationTest.org.kie.wb.test.rest.functional.RepositoryIntegrationTest
org.kie.wb.test.rest.security.ProjectAccessIntegrationTest.org.kie.wb.test.rest.security.ProjectAccessIntegrationTest

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
werid, this was the build result now

No identified problem
No problems were identified. If you know why this problem occurred, please add a suitable Cause for it.

Let's give it another try

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
Hi @hasys , Edson is asking about this. If you can take a look it'll be much appreciated.
And yes, I know, it has been next impossible to get greens this days :(

**Comment by hasys** [comment]
Hi @wmedvede,

I am waiting primarily for available binary file. Since it is in progress I am not able to test it manually. But I found a previou

**Pull request merged**
