### PR TITLE
JBPM-9376: Stunner - Confirm changes by clicking outside the Inline text editor

### PR DESCRIPTION
**Pull request by handreyrc**
Hey @romartin, @karreiro, @LuboTerifaj: Please, could you review this PR? 

**JIRA**: [JBPM-9376](https://issues.redhat.com/browse/JBPM-9376)

**Business Central**: [WAR file](https://drive.google.com/file/d/1OXkcNlz6hmkS8FI2aqx00dMgPrtoMZ6t/view?usp=sharing)

**VS Code**: [plugin](https://drive.google.com/file/d/1Dl0Fk3KUuNAVRFBuUB7a4fuG7HhFT1mS/view?usp=sharing)

Thanks!

### CODE REVIEW

**Comment by handreyrc** [comment]
Jenkins run fdb

**Review by karreiro — APPROVED** [review]
Thank you, @handreyrc! :-)

**Review by romartin — APPROVED** [review]
Thanks @inodeman , good job!

**Comment by romartin** [comment]
Please @LuboTerifaj can you provide feedback on this? Would be great having this merged for today's cutoff. Thanks!!

**Review by LuboTerifaj — APPROVED** [review]
Hello @handreyrc , 

I didn't find any issues and it looks good to me.

Thanks!

**Pull request merged**
