### PR TITLE
KOGITO-991: VSCode - BPMN modeler global vs process variables

### PR DESCRIPTION
**Pull request by handreyrc**

### CODE REVIEW

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
@romartin, @inodeman Could you please review this PR?

**Comment by romartin** [comment]
@domhanak @LuboTerifaj adding both as reviewers because it affects both kogito and BC. Thanks!

**Comment by domhanak** [comment]
I was able to select Advanced tab in Business central.
I was able to open it and close it.
I was able to add Global Variable, Remove it, Save it, Edit it.

Tested in Chrome and Firefox.

One second and I ll report if VSCode is ok :)

**Comment by domhanak** [comment]
With VSCode I still have the issues with Adding Removing and Deleting. Visually it happens.
But the changes are not persisted. I tried losing focus, opening multiple times, saving multiple times, editing diagram; nothing helped.

Issues one:
1. Create fresh diagram
2. Add simple flow and add global variable(s) under Advanced tab
3. Save and close
4. Open and inspect Global Variables under Advanced tab
Result: There is no variable(s) shown in the panel, but when you check BPMN file the variable(s) are present in the file.
JIRA: https://issues.redhat.com/browse/KOGITO-1509

**Comment by handreyrc** [comment]
Hey @domhanak, I checked the issue you mentioned above and it seems a properties panel issue for me. The same is happening to the process variables. I also found out that this is a focus issue. If immediatelly after opening any file with global or process variables defined and then open the properties panel, they won't be loaded.  However, after opening the file, if you click on any empty area of the canvas and only then open the properties panel, they will be properly loaded and displayed.
@romartin, @domhanak  What do you think?

**Comment by romartin** [comment]
Hey @domhanak @handreyrc 

Yep, as @handreyrc already pointed out, there is acutally a bug on the VSCode editor which makes the properties/explorer panel not working properly, once opening, see [KOGITO-1425](https://issues.redhat.com/browse/KOGITO-1425)

We're actually working on fixing it guys, for now the workaround is just to click first on the canvas!! 

Thx!

**Comment by romartin** [comment]
please @domhanak @LuboTerifaj could you please prioritze this review again? See [above comment](https://github.com/kiegroup/kie-wb-common/pull/3214#issuecomment-601734453), the byg on VSCode is not related to this. Also this PR is blocking another one... thx in advance!

**Pull request merged**
