### PR TITLE
[7.30.x] RHPAM-2317 - Users cannot find the properties menu unless it's pointed out to them

### PR DESCRIPTION
**Pull request by Josephblt**
**This is part of an ensemble (DO NOT MERGE BEFORE THIS):**
**https://github.com/kiegroup/appformer/pull/849**

https://issues.jboss.org/browse/RHPAM-2317

This adds the possibility of having different labels and tooltips for the docks which was not supported.

Some small adjustments due to sonar cloud fail.

Wider test coverage
Change to method name in a test.
Unnecessary code removed.

Video (Updated - Tooltip shows Properties instead of Open properties panel):
https://drive.google.com/file/d/1AbYsbhHG2RfZJjtSz3Kb2cKyQJG6tLsB/view?usp=sharing

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
@romartin @Josephblt Based on this PR does https://github.com/kiegroup/kie-wb-common/pull/3021 need cherry-picking to 7.30.x. too? Nobody's said anything to me about it.

**Comment by romartin** [comment]
hey @manstis 
Well not sure about https://github.com/kiegroup/kie-wb-common/pull/3021 .... we're cherry-picking this in order to have this feature ready for next 7.6 release. Were you depending on this? I also didn't know sorry. Talk to @etirelli or @krisv but I'm fine with also cherry-picking https://github.com/kiegroup/kie-wb-common/pull/3021 if you need it for 7.6 release, it doesn't look risky at all.

**Comment by Josephblt** [comment]
Hello @manstis, @romartin. #3021 does the same as this, but on the DMN Editor. So I would vote for it to be included as well. If that's the case, yes it needs to be cherry picked to 7.30.x.

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
@LuboTerifaj thanks a lot! good job!
@Josephblt please keep an eye on the builds statuses and lemme know once this is ready to merge, thanks!

**Comment by romartin** [comment]
Hey @mareknovotny @mbiarnes 
Plz there are a few PRs, like this one, in which the regular J builds are failing due to timeout issues (`"Build timed out (after 120 minutes). Marking the build as aborted"`). Please we need to the successful builds in order to merge this today, can you please take a look or increase the timeout values, if you think so? Thx in advance!

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by Josephblt** [comment]
Jenkins please retest this

**Pull request merged**
