### PR TITLE
KOGITO-5016: Remove Kogito-related modules from v7 stream

### PR DESCRIPTION
**Pull request by caponetto**
**Thank you for submitting this pull request**

**JIRA**: [KOGITO-5016](https://issues.redhat.com/browse/KOGITO-5016)

**Parent Pull Request**:

- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1637

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Comment by romartin** [comment]
Hey @caponetto @tiagobento - please see my comment https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1637/#issuecomment-832357125

**Review by karreiro — COMMENTED** [review]
Thank you, @caponetto.

I just tried to run `mvn clean gwt:run` on `kie-wb-common-dmn-webapp-standalone`, but I'm getting an error. Am I missing something?

Thanks again!

**Comment by caponetto** [comment]
Hi @karreiro! Thanks for checking this!
I had removed the maven profile that configured `gwt:run` for `kie-wb-common-dmn-webapp-standalone` just because the `id` is `kogito`. I've put that back in and now it is working normally. I haven't changed the profile id though, since I'm not sure if it is being used elsewhere.

Can you please try again?

Screenshot from 2021-05-06 08-59-11

**Review by tomasdavidorg — APPROVED** [review]

**Comment by caponetto** [comment]
Despite ❌, [the last](https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-common-master.pr/37/console) `Linux - Pull Request` has completed successfully.

**Review by yesamer — APPROVED** [review]

**Review by karreiro — APPROVED** [review]
Thank you, @caponetto! It works now 🚀

**Pull request merged**
