### PR TITLE
[AF-2422] Fixed path issues (Windows OS)

### PR DESCRIPTION
**Pull request by caponetto**
**Task**: [AF-2422](https://issues.redhat.com/browse/AF-2422)

**Issue**: Business central is not starting up properly in Windows OS due to path issues.

**Expected behavior**: Starting up business central normally.

### CODE REVIEW

**Comment by ederign** [comment]
@caponetto can you please provide also a war for this?
@Rikkola would you mind to please verify if this fixes your issue?

**Comment by ederign** [comment]
@caponetto can you please provide also a war for this?
@Rikkola would you mind to please verify if this fixes your issue?

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by caponetto** [comment]
Here's [a war file](https://drive.google.com/open?id=1W-YtD1uMGoh4qO5ljzQMS_WAuUd3nCoz) with the changes included.

**Comment by caponetto** [comment]
The failed test is unrelated (it has failed in other PR as well).

**Comment by caponetto** [comment]
Jenkins retest this please

**Comment by ederign** [comment]
Test fail are not related and we got a green fdb

**Pull request merged**
