### PR TITLE
DROOLS-4819: Do not change expand/collapse state when edit mode is ca…

### PR DESCRIPTION
**Pull request by jomarko**
…nceled

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by jomarko** [comment]
@danielzhe just friendly reminder, if you can have a look on this PR.

**Pull request merged**
