### PR TITLE
AF-2514 : Execution Server UI breaks if connected to a KIE Server that has a KContainer deployed that its jar is not on BC internal Maven repo

### PR DESCRIPTION
**Pull request by akumar074**
* If container-alias is not available for a container, then the ContainerSpec is created with ContainerSpecId.

Deployable WAR: https://drive.google.com/open?id=15xPtrTK2vR8DpYe-Fcy8TUDbFk-VwOY7

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
jenkins retest this please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
jenkins retest this please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
jenkins retest this please

**Comment by akumar074** [comment]
Jenkins retest this please

**Comment by akumar074** [comment]
The test failures for Linux - full downstream and Linux-Pull Request seems unrelated to the changes.

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
jenkins retest this please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
jenkins retest this please

**Comment by akumar074** [comment]
> Thanks for the PR @akumar074. I have a few questions, is there any test to check this? Also, `container.getContainerName()` is always not null? In this case only with the ContainerID will be enough to prevent UI to crash?

Thanks for the review @adrielparedes . The container.getContainerName() can be null if we miss the container-alias name in the Curl command. The container id is always present in this scenario. We can create Container cards for container id when the container name is not available.

**Comment by adrielparedes** [comment]
@akumar074 great so we only need the test, thanks!

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by adrielparedes** [comment]
@akumar074 are you sure you are using the right formatter? I can see spaces between brackets

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
> @akumar074 are you sure you are using the right formatter? I can see spaces between brackets
Yeah, I fixed that. Thanks for noticing it.

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Pull request merged**
