### PR TITLE
JBPM-5862-2: Stunner - Diagram tree explorer improvements.

### PR DESCRIPTION
**Pull request by alepintus**
Refactored code to improve the performance of the uberfire tree and stunner tree explorer.
For more information see [this ticket](https://issues.jboss.org/browse/JBPM-5862).

Should be merged with [this PR of uberfire](https://github.com/AppFormer/uberfire/pull/731
) as they have compilation dependencies.

@romartin can you please review this PR?

Thanks.

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
ok to test

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
@romartin Don't forget to include @hasys on Stunner PRs (I merged this as the UF one was merged).

**Pull request merged**
