### PR TITLE
[AF-2382] Store last space opened in browser cookie

### PR DESCRIPTION
**Pull request by gabriel376**
[AF-2382 Store last space opened in browser cookie](https://issues.redhat.com/browse/AF-2382)

Depends on https://github.com/kiegroup/appformer/pull/870

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
Hi @paulovmr, @gabriel376,
before these PRs are merged, QE needs to fix testing framework as this is a breaking change. I will fix this in the beginning of the next week.

**Comment by barboras7** [comment]
Hi guys, 
I checked the feature manually and I think that there one issue with this implementation. Let's take this workflow:

1. User **testUser1** opens the business central, creates a space **space1**, works in this space and then logs out.
2. User **testUser2** logs in to the business central, clicks "Projects" and is redirected into the **space1**

IMHO, this is not really the desired behavior. If we want to store last space opened, this space should be relevant for the user that is currently logged in. What do you think?

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by gabriel376** [comment]
Hi @barboras7,
Good catch! I sent a new commit to solve this issue. Now cookies are store per user.
Thank you!

**Comment by barboras7** [comment]
@gabriel376 , thanks for the fix, works like a charm!

Please, wait with the merging until QE has adjusted the Selenium framework (I hope to have it done by this Wednesday)

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
Hi @barboras7 how is the testing going? Please let me know when merge this.

**Comment by barboras7** [comment]
Hi @ederign,

I approved the changes 6 days ago. I only rerun the full downstream build so that we see it green before the merge. From my point of view, we are ready to merge this.

**Comment by ederign** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
Unrelated test failure.

**Pull request merged**
