### PR TITLE
JBPM-8817 : Prevent Unnecesary Listeners to get added everytime a user performs a click

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin can you check this PR?

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin, as discussed on the call this fix looks legit. Should we proceed with PR review or it needs more love from @inodeman before we continue?

**Comment by romartin** [comment]
@hasys @inodeman 
I would vote for closing this PR and just open a new once with the right fix again, but also up to you guys. Anyway this PR has nothing to review, yet @hasys , thanks for asking.

**Comment by inodeman** [comment]
PR Closed, fixed by PR https://github.com/kiegroup/kie-wb-common/pull/2983

**Pull request closed without merging**
