### PR TITLE
JBPM-7782 - Possibility of deactivate a kie-container in order to avo…

### PR DESCRIPTION
**Pull request by mswiderski**
…id creation of new instances but permit to finish active instances

depends on 
https://github.com/kiegroup/droolsjbpm-integration/pull/1591
https://github.com/kiegroup/jbpm/pull/1341

@cristianonicolai could you please have a look?

there is a third button (next to start and stop) on container view that allows to activate/deactivate container.
image

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by jhrcek** [comment]
The only thing that's failing are selenium tests because they missed the path to firefox binary (related to my recent upgrade of selenium version). I fixed that [here](https://github.com/kiegroup/kie-jenkins-scripts/pull/340) so Jenkins execute full downstream build to check if the issue is fixed.

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
@bsremac would you also have a look at this?

**Comment by bsremac** [comment]
@mswiderski Sure. As soon as I have all the binaries available from the full downstream build, I will give it a go.

**Comment by jhrcek** [comment]
@bsremac the binaries are available [here](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-common-downstream-pullrequests/86/). There are still selenium test failures in full downstream build, because it timed out after 15 seconds of  waiting for the home page to load (as you can see in the screenshot which are always captured after failure in selenium tests - provided that browser started at all :) ) 15 seconds is a lot, but not sure if this is an issue with jenkins or just business-central being too slow..

**Comment by bsremac** [comment]
@mswiderski Looks very good from the UI side. Tried a handful of scenarios and couldn't break it :)
Probably would add a task to add one happy path Selenium test to cover this feature from the UI side.

**Pull request merged**
