### PR TITLE
BAPL-1113 Designer - Data Object and Association

### PR DESCRIPTION
**Pull request by treblereel**
JIRA: https://issues.redhat.com/browse/BAPL-1113

Known issues:
* We can't find a way to add a validation to Name property  for pattern "^$|[a-zA-Z0-9_]+", so it ll be added later
* If Process Variable and DataObject have the same name, ProcessVariable ll be used

missed tests ll be added later

### CODE REVIEW

**Comment by treblereel** [comment]
jenkins execute full downstream build

**Comment by treblereel** [comment]
Jenkins retest this

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by treblereel** [comment]
jenkins execute full downstream build

**Comment by treblereel** [comment]
Jenkins retest please

**Comment by treblereel** [comment]
Jenkins retest please

**Comment by treblereel** [comment]
Jenkins retest please

**Pull request closed without merging**
