### PR TITLE
DROOLS-1626: Kie-server management: Pressing upgrade throws an error

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/DROOLS-1626

Before:
hy

After:
goron

### CODE REVIEW

**Comment by karreiro** [comment]
@paulovmr Could you please take a look? :-)

**Comment by manstis** [comment]
@hasys @karreiro @paulovmr Hi.. do you know if QE review "KIE Server" PRs before merge?!

**Comment by paulovmr** [comment]
Hi @manstis , I don't know...

**Comment by triceo** [comment]
@manstis We do. Although due to public holidays and PTOs this week, it is unlikely anyone would be available. :-(

**Comment by manstis** [comment]
@triceo So you're OK things being merged w/o QE approval atm?

**Comment by triceo** [comment]
@manstis It would be nice if big items could be held for the few days - but assuming they can't, feel free to merge things without QE's approval.

**Comment by manstis** [comment]
@karreiro Hi matey.. please see @triceo comments and let me know if this can wait..

**Comment by etirelli** [comment]
@triceo because this is a bug that users hit easily and we have a community release cutting this Friday, I will ask this PR to be merged with the review from @paulovmr only. Please ask your team to still review it next week and if they find additional problems @karreiro will fix it.

**Pull request merged**
