### PR TITLE
DROOLS-2848 : Make the Verifier Web Worker connector reusable for different V&V types

### PR DESCRIPTION
**Pull request by Rikkola**
Follow up for: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/800

https://issues.jboss.org/browse/DROOLS-2848
https://issues.jboss.org/browse/DROOLS-2849

Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/809
https://github.com/kiegroup/kie-wb-common/pull/2073
https://github.com/kiegroup/drools-wb/pull/919
https://github.com/kiegroup/optaplanner-wb/pull/302
https://github.com/kiegroup/kie-wb-distributions/pull/802

### CODE REVIEW

**Comment by jomarko** [comment]
@manstis @Rikkola due to recent troubles with compiling webapps I decided to run dependencyConvergence check over touched modules on got this, would you mind to have a look? Not saying is blocker from merge just want to discuss:
```
[WARNING] 
Dependency convergence error for org.ow2.asm:asm:5.0.3 paths to dependency are:
+-org.kie.workbench.services:kie-wb-common-verifier-reporting-client:7.12.0-SNAPSHOT
  +-com.google.gwt.gwtmockito:gwtmockito:1.1.6
    +-com.google.gwt:gwt-dev:2.8.2
      +-org.ow2.asm:asm:5.0.3
and
+-org.kie.workbench.services:kie-wb-common-verifier-reporting-client:7.12.0-SNAPSHOT
  +-com.google.gwt.gwtmockito:gwtmockito:1.1.6
    +-com.google.gwt:gwt-dev:2.8.2
      +-org.ow2.asm:asm-util:5.0.3
        +-org.ow2.asm:asm-tree:5.0.3
          +-org.ow2.asm:asm:5.0.3
and
+-org.kie.workbench.services:kie-wb-common-verifier-reporting-client:7.12.0-SNAPSHOT
  +-com.google.gwt.gwtmockito:gwtmockito:1.1.6
    +-com.google.gwt:gwt-dev:2.8.2
      +-org.eclipse.jetty:jetty-annotations:9.2.14.v20151106
        +-org.ow2.asm:asm:5.0.1

[WARNING] 
Dependency convergence error for com.google.jsinterop:jsinterop-annotations:1.0.1 paths to dependency are:
+-org.kie.workbench.services:kie-wb-common-verifier-reporting-client:7.12.0-SNAPSHOT
  +-org.jboss.errai:errai-common:4.4.0-20180913.134540-4
    +-com.google.jsinterop:jsinterop-annotations:1.0.1
and
+-org.kie.workbench.services:kie-wb-common-verifier-reporting-client:7.12.0-SNAPSHOT
  +-org.jboss.errai:errai-common:4.4.0-20180913.134540-4
    +-com.google.elemental2:elemental2-dom:1.0.0-beta-1
      +-com.google.jsinterop:jsinterop-annotations:1.0.1
and
+-org.kie.workbench.services:kie-wb-common-verifier-reporting-client:7.12.0-SNAPSHOT
  +-org.jboss.errai:errai-common:4.4.0-20180913.134540-4
    +-com.google.elemental2:elemental2-dom:1.0.0-beta-1
      +-com.google.jsinterop:base:1.0.0-beta-1
        +-com.google.jsinterop:jsinterop-annotations:1.0.1
and
+-org.kie.workbench.services:kie-wb-common-verifier-reporting-client:7.12.0-SNAPSHOT
  +-org.jboss.errai:errai-common:4.4.0-20180913.134540-4
    +-com.google.elemental2:elemental2-dom:1.0.0-beta-1
      +-com.google.elemental2:elemental2-core:1.0.0-beta-1
        +-com.google.jsinterop:jsinterop-annotations:1.0.1
and
+-org.kie.workbench.services:kie-wb-common-verifier-reporting-client:7.12.0-SNAPSHOT
  +-org.jboss.errai:errai-common:4.4.0-20180913.134540-4
    +-com.google.elemental2:elemental2-dom:1.0.0-beta-1
      +-com.google.elemental2:elemental2-promise:1.0.0-beta-1
        +-com.google.jsinterop:jsinterop-annotations:1.0.1
and
+-org.kie.workbench.services:kie-wb-common-verifier-reporting-client:7.12.0-SNAPSHOT
  +-com.google.gwt:gwt-user:2.8.2
    +-com.google.jsinterop:jsinterop-annotations:1.0.1
and
+-org.kie.workbench.services:kie-wb-common-verifier-reporting-client:7.12.0-SNAPSHOT
  +-com.google.gwt:gwt-user:2.8.2
    +-com.google.jsinterop:jsinterop-annotations:1.0.2

[WARNING] 
Dependency convergence error for org.ow2.asm:asm-commons:5.0.3 paths to dependency are:
+-org.kie.workbench.services:kie-wb-common-verifier-reporting-client:7.12.0-SNAPSHOT
  +-com.google.gwt.gwtmockito:gwtmockito:1.1.6
    +-com.google.gwt:gwt-dev:2.8.2
      +-org.ow2.asm:asm-commons:5.0.3
and
+-org.kie.workbench.services:kie-wb-common-verifier-reporting-client:7.12.0-SNAPSHOT
  +-com.google.gwt.gwtmockito:gwtmockito:1.1.6
    +-com.google.gwt:gwt-dev:2.8.2
      +-org.eclipse.jetty:jetty-annotations:9.2.14.v20151106
        +-org.ow2.asm:asm-commons:5.0.1

```

**Comment by Rikkola** [comment]
@jomarko Well I took a quick look and I could at least remove gwt-dev dependency since it was not needed, but gwt-user issues are still there. However the gwt-user is set to provided.

**Comment by Rikkola** [comment]
Docker tests failing.

Jenkins please retest.

**Comment by Rikkola** [comment]
Jenkins please retest.

**Pull request merged**
