### PR TITLE
DROOLS-5737: [DMN Designer] change in Decision Navigator does not dirty context

### PR DESCRIPTION
**Pull request by danielzhe**
**JIRA**: [DROOLS-5737](https://issues.redhat.com/browse/DROOLS-5737)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by jstastny-cz** [comment]
jenkins do fdb

**Comment by jstastny-cz** [comment]
Please check the compilation. 
```
[2020-10-30T23:05:28.742Z] [INFO] --- maven-checkstyle-plugin:3.0.0:check (validate) @ kie-wb-common-dmn-client ---
[2020-10-30T23:05:36.880Z] [INFO] There is 1 error reported by Checkstyle 8.19 with /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-master.pr/kie-wb-common-dmn/kie-wb-common-dmn-client/target/checkstyle-rules.xml ruleset.
[2020-10-30T23:05:36.880Z] [ERROR] src/test/java/org/kie/workbench/common/dmn/client/docks/navigator/tree/DecisionNavigatorTreeViewTest.java:[24,8] (imports) UnusedImports: Unused import - javax.enterprise.event.Event.

```

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by jstastny-cz** [comment]
jenkins do fdb

**Comment by jstastny-cz** [comment]
jenkins do fdb

**Review by karreiro — COMMENTED** [review]
Thank you for this PR, @danielzhe!

However, I've noticed the issue still happens on this scenario:



I believe we could mark the editor as dirty every time the `DMNDiagramSelected` is triggered. Wdyt? :-)

**Review by karreiro — APPROVED** [review]
Thank you for the changes, @danielzhe. But, I'm still able to reproduce the issue :( see:



However, I believe this issue seems a bit out of the scope of DROOLS-5737, so I've raised this other JIRA https://issues.redhat.com/browse/DROOLS-5805 to address it.

**Comment by karreiro** [comment]
Jenkins retest this.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by jstastny-cz** [comment]
@karreiro @danielzhe  I don't think it's out of scope, I think it falls under the category "change in decision navigator". Please include the fix for that issue already in this PR.

**Comment by danielzhe** [comment]
@karreiro Changes applied! The idea about this commit is that now we calculate the hash code based on the DMNDiagrams that we have. You'll notice that we only update the `originalHash` if it's not set yet. This is because the diagram is reloaded every time we change between DMN diagrams and so the `originalHash` was recalculated.

Consider that user have those two diagrams:

- Diagram A
- Diagram B

Old scenario:
1. He made some changes in "A" and switch to "B"
2. The hash `originalHash` is recalculated **considering only the current diagram**, so looks like there is no new changes;

New scenario "bugged":
1. He made some changes in "A" and switch to "B"
2. The hash `originalHash` is recalculated but now **considering ALL the diagrams** (the correct way). 
But the issue is that in this scenario we recalculate and update the hashcode but now we are considering the changes made on "A", so when user tries to [save the file, it will looks like there's no changes](https://github.com/kiegroup/kie-wb-common/blob/6af88762c5006e515a29418c902cd4b59e0ca375/kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/main/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditor.java#L689).

New fixed scenario:
1. He made some changes in "A" and switch to "B"
2. The `originalHash` keeps the same (set at when the **file is loaded or saved**)

Let me know if this is clear or you or @jstastny-cz have any doubt.

**Comment by jstastny-cz** [comment]
@danielzhe checkstyle issue blocking the build:
```
[2020-11-11T16:51:40.717Z] [INFO] --- maven-checkstyle-plugin:3.0.0:check (validate) @ kie-wb-common-dmn-client ---
[2020-11-11T16:51:46.009Z] [INFO] There is 1 error reported by Checkstyle 8.19 with /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-master.pr/kie-wb-common-dmn/kie-wb-common-dmn-client/target/checkstyle-rules.xml ruleset.
[2020-11-11T16:51:46.009Z] [ERROR] src/test/java/org/kie/workbench/common/dmn/client/docks/navigator/drds/DMNDiagramsSessionTest.java:[50,15] (imports) UnusedImports: Unused import - org.mockito.Matchers.any.
```

Please after fixing that run also FDB `jenkins do fdb`

**Comment by danielzhe** [comment]
jenkins do fdb

**Review by jstastny-cz — APPROVED** [review]
I think the dirty context works correctly now, enforcing save or discard. LGTM.

**Review by karreiro — APPROVED** [review]
Thank you for the changes, @danielzhe!

**Pull request merged**
