### PR TITLE
JBPM-6766: Editing values in fields with options (ListBox, RadioGroup, MultipleSubform) throws exception.

### PR DESCRIPTION
**Pull request by pefernan**
@wmedvede @jsoltes could you please review?

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@jsoltes good find! fixed!

**Comment by jsoltes** [comment]
@pefernan the regression is fixed! Also the edit works in new forms, however there is a compatibility issue with older forms - if you already have a form with added field of a radiogroup with int, char, BigInteger, byte or long binding, it throws exception on edit...

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
DO NOT MERGE, PLEASE

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Pull request merged**
