### PR TITLE
[7.7.x] RHPAM-517 (JBPM-7012): Stunner - After morph it is not possible to put node inside of subprocess

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/RHPAM-517

This is the corollary of https://github.com/kiegroup/kie-wb-common/pull/1645 for 7.7.x

(cherry picked from commit 6cd92c1772186793655bc115fb35a69a85bb83cb)

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@manstis the build is ok but waiting for @hasys to approve in order to merge. thx

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Pull request merged**
