### PR TITLE
RHPAM-3434: BPMN Editor - Cannot properly edit Expressions in the Data Assignments

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin, @domhanak, it is cherry-pick of https://github.com/kiegroup/kie-wb-common/pull/3556

**JIRA**: [RHPAM-3434](https://issues.redhat.com/browse/RHPAM-3434)

**Business Central**: [WAR file](https://drive.google.com/file/d/1qzeOIVt1a4TBA7iGK0vfBRLpTntKEAMr/view?usp=sharing)

**VS Code**: not needed

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by hasys** [comment]
jenkins do cdb

**Review by domhanak — APPROVED** [review]

**Comment by hasys** [comment]
Hi @domhanak,

there are failing Selenium tests. Looks like unrelated issue to me. What should we do with it?

<details>
  <summary>Click to expand</summary>
  <pre>
Failed

org.kie.workbench.common.stunner.kogito.client.selenium.BPMNDesignerKogitoSeleniumIT.org.kie.workbench.common.stunner.kogito.client.selenium.BPMNDesignerKogitoSeleniumIT

Error Message

java.net.SocketTimeoutException: Read timed out

Stacktrace

io.github.bonigarcia.wdm.WebDriverManagerException: java.net.SocketTimeoutException: Read timed out
	at org.kie.workbench.common.stunner.kogito.client.selenium.BPMNDesignerKogitoSeleniumIT.setupClass(BPMNDesignerKogitoSeleniumIT.java:95)
Caused by: java.net.SocketTimeoutException: Read timed out
	at org.kie.workbench.common.stunner.kogito.client.selenium.BPMNDesignerKogitoSeleniumIT.setupClass(BPMNDesignerKogitoSeleniumIT.java:95)

Standard Output

2021-02-15 08:43:56,669 [main] ERROR Error HTTP 403 executing GET https://api.github.com/repos/mozilla/geckodriver/releases HTTP/1.1
2021-02-15 08:43:56,674 [main] WARN  There was an error managing geckodriver 0.26.0 (Error HTTP 403 executing GET https://api.github.com/repos/mozilla/geckodriver/releases HTTP/1.1) ... trying again using mirror
2021-02-15 08:44:28,924 [main] WARN  There was an error managing geckodriver 0.26.0 (Read timed out) ... trying again using latest from cache
2021-02-15 08:45:12,721 [main] ERROR There was an error managing geckodriver (latest version) (Read timed out)
java.net.SocketTimeoutException: Read timed out
</pre>
</details>

We need to retrigger or it's ok?

**Comment by hasys** [comment]
Full compile also failded due to unrelated issues, retriggering.

<details>
  <summary>Console log</summary>
  <pre>14:06:22  [INFO] ------------------------------------------------------------------------
14:06:22  [INFO] BUILD FAILURE
14:06:22  [INFO] ------------------------------------------------------------------------
14:06:22  [INFO] Total time:  03:54 min (Wall Clock)
14:06:22  [INFO] Finished at: 2021-02-15T09:03:10-05:00
14:06:22  [INFO] ------------------------------------------------------------------------
14:06:22  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install (default-install) on project business-central: Failed to install artifact org.kie:business-central:war:wildfly19:7.48.1-SNAPSHOT: No space left on device -> [Help 1]
14:06:22  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install (default-install) on project business-central: Failed to install artifact org.kie:business-central:war:wildfly19:7.48.1-SNAPSHOT: No space left on device
14:06:22      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
14:06:22      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
14:06:22      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
14:06:22      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
14:06:22      at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
14:06:22      at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
14:06:22      at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
14:06:22      at java.util.concurrent.FutureTask.run (FutureTask.java:266)
14:06:22      at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
14:06:22      at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
14:06:23      at java.tee: write error
22:45:50  Cancelling nested steps due to timeout
22:45:50  Sending interrupt signal to process
22:46:10  After 20s process did not stop</pre>
</details>

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
Jenkins retest this

**Review by romartin — APPROVED** [review]

**Comment by hasys** [comment]
Jenkins retest this

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
jenkins do cdb

**Comment by romartin** [comment]
jenkins do cdb

**Comment by hasys** [comment]
Compile build failed due to issues in drools:

<details>
  <summary>Stacktrace</summary>
  <pre>23:04:31  [INFO] Reactor Summary for Drools and jBPM Tools multiproject 7.48.1-SNAPSHOT:
23:04:31  [INFO] 
23:04:31  [INFO] Drools and jBPM Tools multiproject ................. SUCCESS [  2.607 s]
23:04:31  [INFO] Drools, jBPM and Guvnor plugins for Eclipse ........ SUCCESS [  1.576 s]
23:04:31  [INFO] KIE :: Eclipse :: Common ........................... SUCCESS [ 11.833 s]
23:04:31  [INFO] Drools :: Eclipse :: Base .......................... FAILURE [  6.176 s]
23:04:31  [INFO] Drools :: Eclipse :: Base feature .................. SKIPPED
23:04:31  [INFO] Drools :: Eclipse :: Base test ..................... SKIPPED
23:04:31  [INFO] Drools :: Eclipse :: Webdav for Guvnor tools ....... SUCCESS [ 11.781 s]
23:04:31  [INFO] Drools :: Eclipse :: Guvnor tools .................. SUCCESS [  8.399 s]
23:04:31  [INFO] Drools :: Eclipse :: Guvnor tools feature .......... SUCCESS [  0.494 s]
23:04:31  [INFO] Drools :: Eclipse :: Guvnor tools test ............. SUCCESS [  2.898 s]
23:04:31  [INFO] jBPM :: Eclipse :: Base ............................ SKIPPED
23:04:31  [INFO] jBPM :: Eclipse :: Base feature .................... SKIPPED
23:04:31  [INFO] Drools :: Eclipse :: Common feature ................ SUCCESS [  0.633 s]
23:04:31  [INFO] KIE :: Eclipse :: Kie Navigator .................... SKIPPED
23:04:31  [INFO] Drools :: Eclipse :: Kie Navigator feature ......... SKIPPED
23:04:31  [INFO] org.jboss.tools.runtime.drools.detector ............ SKIPPED
23:04:31  [INFO] org.jboss.tools.runtime.drools.detector.feature .... SKIPPED
23:04:31  [INFO] Drools :: Eclipse :: Update site ................... SKIPPED
23:04:31  [INFO] Drools and jBPM tools distribution ................. SKIPPED
23:04:31  [INFO] ------------------------------------------------------------------------
23:04:31  [INFO] BUILD FAILURE
23:04:31  [INFO] ------------------------------------------------------------------------
23:04:31  [INFO] Total time:  06:47 min (Wall Clock)
23:04:31  [INFO] Finished at: 2021-02-25T18:01:08-05:00
23:04:31  [INFO] ------------------------------------------------------------------------
23:04:31  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.0.0:compile (default-compile) on project org.drools.eclipse: Compilation failure: Compilation failure: 
23:04:31  [ERROR] /home/jenkins/workspace/KIE/7.48.x/compile/kie-wb-common-7.48.x.compile/kiegroup_droolsjbpm-tools/drools-eclipse/org.drools.eclipse/src/main/java/org/drools/eclipse/editors/completion/RuleCompletionProcessor.java:[1164] 
23:04:31  [ERROR] 	context.setInterceptors(dialect.getInterceptors());
23:04:31  [ERROR] 	                                ^^^^^^^^^^^^^^^
23:04:31  [ERROR] The method getInterceptors() is undefined for the type MVELDialect
23:04:31  [ERROR] 1 problem (1 error)
23:04:31  [ERROR] -> [Help 1]
23:04:31  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.0.0:compile (default-compile) on project org.drools.eclipse: Compilation failure
23:04:31      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
23:04:31      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
23:04:31      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
23:04:31      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
23:04:31      at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
23:04:31      at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
23:04:31      at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
23:04:31      at java.util.concurrent.FutureTask.run (FutureTask.java:266)
23:04:31      at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
23:04:31      at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
23:04:31      at java.lang.Thread.run (Thread.java:748)
23:04:31  Caused by: copied.org.apache.maven.plugin.CompilationFailureException: Compilation failure
23:04:31      at copied.org.apache.maven.plugin.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:420)
23:04:31      at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.execute (AbstractOsgiCompilerMojo.java:293)
23:04:31      at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
23:04:31      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
23:04:31      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
23:04:31      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
23:04:31      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
23:04:31      at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
23:04:31      at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
23:04:31      at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
23:04:31      at java.util.concurrent.FutureTask.run (FutureTask.java:266)
23:04:31      at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
23:04:31      at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
23:04:31      at java.lang.Thread.run (Thread.java:748)
23:04:31  [ERROR] 
23:04:31  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
23:04:31  [ERROR] 
23:04:31  [ERROR] For more information about the errors and possible solutions, please read the following articles:
23:04:31  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
23:04:31  [ERROR] 
23:04:31  [ERROR] After correcting the problems, you can resume the build with the command
23:04:31  [ERROR]   mvn <args> -rf :org.drools.eclipse</pre>
</details>

**Comment by hasys** [comment]
jenkins do cdb

**Comment by romartin** [comment]
@hasys lemme know when it's ready to merge please. Thanks!

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
jenkins do cdb

**Pull request merged**
