### PR TITLE
replaced origin-repository.jboss.org by repository.jboss.org

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mareknovotny** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
ok to test

**Comment by domhanak** [comment]
@mbiarnes can this be closed?

**Comment by mareknovotny** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
@domhanak I would rather see it merged than closed, the URL in original source here should not be used

**Comment by manstis** [comment]
@winklerm Could you please review/approve?

**Pull request merged**
