### PR TITLE
AF-1910: Localization of Library.properties

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko if you know somebody else in QE is better suited to test please say and I'll change the reviewer. It'll be hard to test without performing a full "release" build when we get translations from Zanata so it might be best to wait for the next pre-release and test then.

**Comment by jomarko** [comment]
@manstis thank you, I checked the jira and as it is tightly related to Library, I think it should be reviewed by someone from appformer team, @barboras7 @tomasdavidorg could someone of you have a look on this PR please?

**Comment by tomasdavidorg** [comment]
Looks good to me. :slightly_smiling_face: Thanks.

**Comment by paulovmr** [comment]
jenkins retest this
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Pull request merged**
