### PR TITLE
JBPM-6052 Stunner: fixing toolbar panel that was missing with fixed palette

### PR DESCRIPTION
**Pull request by tiagodolphine**
Fix for the reopened issue JBPM-6052 according to the comment of @manstis regarding the commit [1]. 
Now the palette is fixed and the toolbar is not missed, tested on the project, standalone and kie-drools-wb. Some videos were attached to the JIRA [2]. If it is ok after the merge it is necessary the port back to the 7.3.x.

@ibek @hasys can you please help to validate.

Thanks.

**[1]** https://github.com/kiegroup/kie-wb-common/commit/9fe2a86f4609968fd030ae8ff5be308b92d3470a
**[2]** https://issues.jboss.org/browse/JBPM-6052

### CODE REVIEW

**Comment by tiagodolphine** [comment]
Jenkins retest this.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
Please let me know when this is green and I'll merge.

**Comment by manstis** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
(Damn I assumed it was the full downstream that failed...)

**Comment by manstis** [comment]
I find the DMN Editor completely unusable with this PR (and https://github.com/kiegroup/kie-wb-common/pull/1119 applied). Sorry... I will try the "Standalone Stunner" editor too (but the DMN one is based on that so expecting much the same).

**Comment by manstis** [comment]
palette-floating-bottom-left

**Comment by manstis** [comment]
horizontal-scroll-bar and other content obscured

**Comment by tiagodolphine** [comment]
Hi @manstis I will test here with the https://github.com/kiegroup/kie-wb-common/pull/1119 to see what is happening.

**Comment by tiagodolphine** [comment]
@manstis I've tested here the stunner standalone is ok, the problem is on the dmn with a strange behavior the palette is not initializing on the proper position. I will fix it, thanks again to raise up the issue.

**Comment by manstis** [comment]
Hi @tiagobento thanks for taking a look.

Before the PRs relating to the "palette" the DMN editor worked OK but does not now.

You can "see" the problem by running the DMN editor (standalone) [showcase](https://github.com/kiegroup/kie-wb-common/tree/master/kie-wb-common-dmn/kie-wb-common-dmn-webapp). In addition to the "palette" not being correctly positioned (until the panel is resized) when editing a DMN node the DOM "flow" is now wrong. If you add a "decision" node; then click on it and the "edit" toolbox control (cog/spanner, I forget which) you'll see the second screenshot I attached. Select something from the drop-down. The screen used to flow: drop-down, Lienzo panel, red button. Depending on which PRs are merged you get one of the following:

1) Flow correct, but floating/overlapping the toolbox control.

2) Drop-down OK, but horizontal scrollbar present and red-button behind Lienzo panel.

The DMN editor is re-using the View's _main panel_ to hold the "detail" editor. See [here](https://github.com/kiegroup/kie-wb-common/blob/master/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/BaseNavigateCommand.java#L106) (and the following methods that set the content and hide the "palette").

I may be cannibalising the _main panel_ for DMN's purposes too much! ;-)

**Comment by tiagodolphine** [comment]
Hi @manstis @romartin I've just updated this PR with some modification in order to solve DMN issues on the palette and on Expression Editor. Can you please take a look. @manstis I don't know how was the screen layout on the Expression Editor but I noticed a problem, the Canvas on the editor is "fixed" so if we scroll the panel the behavior is not good, in my opinion... and I didn't find how to make it relative instead of fixed even changing the CSS, I think is should be some configuration on the 

> BaseExpressionEditorViewImpl

.

**Comment by romartin** [comment]
Hey @tiagodolphine ,
Only tested for now the "project showcase" but found a couple of bugs:

1.- The screen selector drop-down appears on back on the palette, which makes the texts not completely visible, see screenshot:

screenshot from 2017-09-06 19-56-56

2.- Once working with more than one Stunner editors, the palette only appears in the last opened one, see screenshot where the first opened editor does not has palette:
 
screenshot from 2017-09-06 19-57-12

**Comment by tiagodolphine** [comment]
@romartin Ok, thanks I will check these issues you've found !

**Comment by romartin** [comment]
Hey @tiagodolphine ! 

Well not sure if it's related to your task, but running the "standalone showcase" using the latest master branch, noticed the toolbar is no longer there - cannot execute validations, undo, redo's etc :( 

Please can you take a look at it too?
screenshot from 2017-09-06 20-35-07

Ping me whatever you need np!
Thanks!

**Comment by tiagodolphine** [comment]
@romartin this PR is to solve this issue related to the missing toolbar.

**Comment by manstis** [comment]
@romartin I think the hidden Toolbar is entirely caused by these "Palette" changes :-(

IMO the ```canvas-view``` is positioned relative (to it's parent, at 0,0) which for "Project" is great - as it fits the top of the Editor view; whereas for "standalone" (with the Toolbar) it's still at 0,0 and hiding the toolbar.

**Comment by manstis** [comment]
@tiagodolphine Here's a screenshot of the DMN editor with this PR applied.

I've also removed the ```fixed``` scroll panel issue (which is something @karreiro is to look into for me).

screenshot from 2017-09-06 19-52-29

**Comment by manstis** [comment]
I'm inclined to say revert the commits relating to the Palette fixes until a solution is identified.

**Comment by romartin** [comment]
@tiagodolphine @manstis I'm agree on reverting changes yeah, this kind of fixes need testing and require some fine-tunning time, meanwhile we need that toolbar's buttons, so +1 for me! This way @tiagodolphine can look at it and no pressures :)

**Comment by tiagodolphine** [comment]
@manstis yeah, let's revert the commit 21fa7410ece16686383f150f5b17002611f08196 , I can open other PR for this revert, ok?

**Comment by tiagodolphine** [comment]
@romartin @manstis I have updated this PR, can you please take a look and help to test and validate, since this palette changes are very sensible. 
@manstis about the Expression Editor on the DMN, I don't know how it should be can you please check that on this branch to see if this is as expected or not.

Thank you !!

**Comment by tiagodolphine** [comment]
Jenkins retest this.

**Comment by romartin** [comment]
@tiagodolphine it seems it's missing to fix a checkstyle violation

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @tiagodolphine 

As commented on IRC, missing the palette:

palette-missing

**Comment by tiagodolphine** [comment]
Hi @romartin, I have made a refactory and now I'm not using the `position:fixed` to make the palette fixed on the screen because this was causing problem with the notification panel of uberfire that was being overlapped as we talked before, and changing `z-index` was not a good idea that was aligned with @ederign.
Now the palette position is recalculated on the scroll of the panel in this way we can keep the `position:relative`. I have tested Standalone, Project and DMN showcases, there were attached to the JIRA (https://issues.jboss.org/browse/JBPM-6052) videos of each test.

@manstis about the DMN can you please check it and main the  Expression Editor. 

Thank you all.

**Tests** :
https://issues.jboss.org/secure/attachment/12425381/project_Screencast_28-09-2017.webm
https://issues.jboss.org/secure/attachment/12425382/standalone_Screencast_28-09-2017.webm
https://issues.jboss.org/secure/attachment/12425383/dmn_Screencast_28-09-2017.webm

**Comment by tiagodolphine** [comment]
Jenkins retest this.

**Comment by romartin** [comment]
thanks for the updates @tiagodolphine , just testing it, but will take a while, I'll test all 3 showcases (dmn, standalone and project) and finally the workbench using different browsers.
Will let you know  asap! Thx!

**Comment by romartin** [comment]
@tiagodolphine Just a clue - you can see this working in our CI environment, if you need so, this way probably you can use it to compare `css` etc....

**Comment by tiagodolphine** [comment]
Hey @romartin just pushed the fix, there was css properties that was missing on the palette panel. 

```-moz-user-select: -moz-none;
    -khtml-user-select: none;
    -webkit-user-select: none;
    /* Introduced in IE 10.
       See http://ie.microsoft.com/testdrive/HTML5/msUserSelect/
    */
    -ms-user-select: none;
    user-select: none;```

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @tiagodolphine, I tried full downstream build and it looks like when you have to Stunner instances one of them won't show main palette: 
image
image
Can reproduce it on both Chrome and Firefox.

**Comment by tiagodolphine** [comment]
Hi @hasys, yeah we have noticed that and opened a new JIRA for that https://issues.jboss.org/browse/JBPM-6419. It seems that this bug is happening on the master branch as well, so it is not related to this JIRA. 
Can you confirm that testing the master?
Thanks !

**Comment by hasys** [comment]
@tiagodolphine, yes, sorry. I can reproduce it on Master as well. I tried it with other types of assets as well and it works without any issues. So only two+ instances of Stunner causing this issue.

@manstis, @tiagodolphine  I guess, it is ready to go, thank you.

**Pull request merged**
