### PR TITLE
DROOLS-2903 : Update test result panel with new UX/UI

### PR DESCRIPTION
**Pull request by Rikkola**
Bundle:
https://github.com/kiegroup/kie-wb-common/pull/2182
https://github.com/kiegroup/drools-wb/pull/960

### CODE REVIEW

**Comment by kkufova** [comment]
@Rikkola, is this ready for review?

**Comment by Rikkola** [comment]
@kkufova Sure. I'll be squashing the commits and perhaps cleaning up the code, but if you want to test it go ahead. There should be no changes.

**Comment by kkufova** [comment]
@Rikkola, the build fails locally with
```
Found 2 illegal transitive type dependencies in artifact 'org.kie.workbench.screens:kie-wb-common-workbench-client:jar:7.14.0-SNAPSHOT':
1.) org.guvnor.messageconsole.events.PublishBatchMessagesEvent
2.) org.guvnor.messageconsole.events.SystemMessage
```
Could you please take a look?

**Comment by Rikkola** [comment]
@kkufova what your proposing sounds reasonable and doable.

**Comment by kkufova** [comment]
@Rikkola, there's a build failure, could you please take a look?

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project kie-wb-common-workbench-client: Compilation failure: Compilation failure: 
[ERROR] /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-pullrequests/kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingViewImpl.java:[29,40] package org.dashbuilder.displayer.client does not exist
[ERROR] /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-pullrequests/kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/test/TestRunnerReportingViewImpl.java:[74,5] cannot find symbol
[ERROR]   symbol:   class DisplayerLocator
[ERROR]   location: class org.kie.workbench.common.workbench.client.test.TestRunnerReportingViewImpl
```

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by gitgabrio** [comment]
@Rikkola 
Am I wrong or all the views/screens have been implemented outside drools-wb ?
Is there any technical reason on doing that?

**Comment by kkufova** [comment]
@Rikkola, Toni, are you planning to incorporate the suggestions in [this](https://github.com/kiegroup/kie-wb-common/pull/2182#pullrequestreview-165964894) comment? There's a bunch of new commits, but none of them implements the suggested improvements.

**Comment by gitgabrio** [comment]
@Rikkola @danielezonca @kkufova 
That PR works, so since we hare in hurry it is fine for me to merge.
I have some appoints, though:
1) we have package with specific names (handlers, events, etc) so I'm expecting  an "Handler" class (ScenarioSimulationDocksHandler) to be in the "handlers" package, and the "Event" ones (OnHideScenarioSimulationDockEvent, OnShowScenarioSimulationDockEvent) to be in the "events"
2) one of the key feature for code maintainability is consistence - there is not much overall drools-wb for historical reason, but at least inside this module we should strive to keep it; **if there is not a technical reason**, I would prefer that, whenever we have time, the erray event/observe would be removed for the management of that right panel dock, and replaced with the GWT event/handler used everywhere else in the module

**Comment by danielezonca** [comment]
@gitgabrio 
I agree with your both your suggestions. Can you please open a Jira to track them?
If it is fine for you to merge please approve it

**Comment by gitgabrio** [comment]
@manstis 
Could you please merge this, squashing commits? Thx!

**Comment by Rikkola** [comment]
@gitgabrio the reason why the screens are not in drools-wb is that they are shared screens for any KIE services/screens that can run tests or show test results.

**Pull request merged**
