### PR TITLE
JBPM-5649: [Stunner] Fixing test compilation.

### PR DESCRIPTION
**Pull request by romartin**
Hey @pefernan @wmedvede 
Sorry something broken once merging this https://github.com/kiegroup/kie-wb-common/pull/1509 (Promised the Jenkins was green)
This is the fix.
Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Anyway @hasys @evacchi , I don't understand why the `BPMNDiagramMarshallerBase` has been copy/pasted... now we have this class as a copy of  `BPMNDiagramMarshallerTest`, why? Should we remove one of those, isn't it? Thx!

**Comment by evacchi** [comment]
I think `BPMNDiagramMarshallerBase` it's a partial copy of  `BPMNDiagramMarshallerTest` and both ` BPMNDiagramMarshallerTest` and  `BPMNDirectDiagramMarshallerTest` will be eventually dropped; can @hasys confirm?

**Comment by hasys** [comment]
Hi @evacchi, @romartin,

Yes, @evacchi you are correct. It is partial copy and `BPMNDiagramMarshallerTest` with `BPMNDirectDiagramMarshallerTest` will be dropped as soon as we will finish migration to new tests structure. We will try to do it ASAP, but it is a huge task and we have to do a lot of staff in parallel, so it will take some time. But any way it should be finished before GA (as part of features verification).

**Pull request merged**
