### PR TITLE
JBPM-9851: Refactor message bundles to match the *Constants.properties convention

### PR DESCRIPTION
**Pull request by hasys**
**JIRA**: [JBPM-9851](https://issues.redhat.com/browse/JBPM-9851)

Hi @romartin, @mareknovotny, I renamed constants file to follow the conventions *Constants.properties Also I updated package to follow the others files with constants and removed 3 files which translated to unsupported locales.

Thank you!

**Business Central**: [WAR file](https://drive.google.com/file/d/1CmeecWHKpNyTkOYuznD0Q-QDsPbZKRtV/view?usp=sharing)

I tested the WAR it still shows the notifications:
image

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by hasys** [comment]
jenkins do fdb

**Comment by hasys** [comment]
jenkins do cdb

**Review by romartin — APPROVED** [review]
Great, thanks @hasys !

**Review by mbiarnes — APPROVED** [review]
LGTM

**Comment by hasys** [comment]
FDB is red due to unrelated unstable tests:

<details>
  <summary>Failed tests</summary>
  <pre>org.kie.wb.test.rest.functional.ProjectIntegrationTest.testDeployProjectSnapshotTwice
org.kie.wb.test.rest.functional.ProjectIntegrationTest.removeBranchUndefined
org.kie.wb.test.rest.functional.ProjectIntegrationTest.testInstallProjectSnapshotTwice
org.kie.wb.test.rest.functional.ProjectIntegrationTest.org.kie.wb.test.rest.functional.ProjectIntegrationTest
org.kie.wb.test.websocket.WebSocketAccessIntegrationTest.testControllerConnection[user: NO_REST]</pre>
</details>

**Pull request merged**
