### PR TITLE
JBPM-7082: Stunner - Designer doesn't restore previous version of a process

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/JBPM-7082 (second commit contains the fix).

Depends on https://github.com/kiegroup/kie-wb-common/pull/1575

I will rebase once the former is merged.

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by romartin** [comment]
oopos @manstis I just merged the dependant PR and now it does not allows me to merge this one....

**Comment by manstis** [comment]
@romartin Tssk tssk you are a naughty boy ;-)

I stated in the PR description that this PR would need rebasing after the other PR was merged; so np.

**Comment by romartin** [comment]
@manstis sorry read the description so fast.... :+1: got it!

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
