### PR TITLE
JBPM-5796: Stunner - Hide BackgroundSet properties on all BPMN nodes

### PR DESCRIPTION
**Pull request by jlindop**

### CODE REVIEW

**Comment by manstis** [comment]
@jlindop Hi.. I know @romartin has an open PR that adds an additional node (Embedded Sub-process, IIRC). Did you want to defer merge of this until his PR is merged and you include the new node type in this PR?

**Comment by jlindop** [comment]
@romartin About @manstis' comment above: are you ok for this PR to be merged before you create an Embedded SubProcess PR? I've made a small change to BaseSubprocess.java, so if you've also made changes to this base class, you'd need to rebase on top of this if it gets merged before you create your Embedded SubProcess PR.

**Comment by jlindop** [comment]
@hasys  Yes, that's a good idea, so that we keep track of the requirement. Will you create a Jira - thanks  (:

**Comment by romartin** [comment]
Hey @jlindop @manstis , sure no problem! In fact my PR currently present is not adding the subprocess yet, it's just about rules, I'm planning to work on lienzo first this week and merge the subprocess on next week, as anyway we're not going to include it on the release. So go ahead! Thanks!

**Pull request merged**
