### PR TITLE
JBPM-8227 - Exclude RestEasy dependencies

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@jhrcek @nmirasch @jstastny-cz @rhtevan can you please help to check this PR, it should fix the controller issue, but test failures seem unrelated.

**Comment by jhrcek** [comment]
There's ~100 stunner tests failed, which seem unrelated to this fix.

Also full downstream build has unrelated failures in [org.jbpm.designer.web.server.TransformerServletTest](http://janhrcek.cz/random-failures/#/class/org.jbpm.designer.web.server.TransformerServletTest) which has been failing on master too for a couple of days. @tsurdilo not sure if you're still maintainer of jbpm-designer, but could you please take a look at those failures or delegate this to someone?

**Comment by cristianonicolai** [comment]
@jhrcek thanks. The reason I started to suspect about this was because of this line in the logs:
`WFLYRS0018: Explicit usage of Jackson annotation in a JAX-RS deployment; the system will disable JSON-B processing for the current deployment. Consider setting the 'resteasy.preferJacksonOverJsonB' property to 'false' to restore JSON-B.`

**Comment by sutaakar** [comment]
Could be replaced by https://github.com/kiegroup/droolsjbpm-integration/pull/1723

**Comment by pefernan** [comment]
@cristianonicolai good catch! this works fine for me.

**Comment by wmedvede** [comment]
Hi @jhrcek @pefernan @nmirasch , it seems like full build failed as usual, but artifacts were generated.
Would you mind  @jhrcek check if generated artifacts are good enough for final check/test and please prioritize merging this PR?
Thanks!

**Comment by krisv** [comment]
Merging since this is blocking testing.

**Comment by jhrcek** [comment]
@wmedvede I checked the business-central war archived in the PR job and it works fine.

**Pull request merged**
