### PR TITLE
DROOLS-5096: [DMN Decision] Properties: Increase Question max length

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/DROOLS-5096

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
@jomarko I think it's probably a good idea to include both "Question" and "Answer" in the documentation. Can you please create a new JIRA and we'll double check with @etirelli in one of our scrum meetings. Thanks.

**Comment by manstis** [comment]
FDB errors relate to https://issues.redhat.com/browse/RHDM-1267

**Comment by jomarko** [comment]
@manstis done, see your inbox

**Pull request merged**
