### PR TITLE
JBPM-6108 ObjectSelector should not appear in Form-modeler editor

### PR DESCRIPTION
**Pull request by alessioscalici**
**WARNING**: to be merged with https://github.com/kiegroup/appformer/pull/93
and with https://github.com/kiegroup/kie-wb-common/pull/1025

These are the same changes as https://github.com/kiegroup/kie-wb-common/pull/1025, pointing to the master branch

@pefernan @jsoltes FYI

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
@alessioscalici Hi, could you please advise the status of this PR?

You say it has to be merged with #969 however that PR has been closed; so IDK what to do.

**Comment by alessioscalici** [comment]
@manstis comments updated, I had to close #969  the PR and open two new PRs, sorry.
Correct PRs to merge are #1024 , #1025 , https://github.com/kiegroup/appformer/pull/93

**Comment by manstis** [comment]
@alessioscalici Thank-you for the clarification.

https://github.com/kiegroup/appformer/pull/93 is failing to build; you may need to rebase your PRs.

Please let me know when all green and I'll merge.

**Pull request merged**
