### PR TITLE
JBPM-9586 - BPMN editor [Business Central]: Missing structureRef for …

### PR DESCRIPTION
**Pull request by Josephblt**
…Message when creating process

StructureRefs included in Message related Item Definitions.

**JIRA**: [JBPM-9586](https://issues.redhat.com/browse/JBPM-9586)

**Business Central**: [WAR file](https://drive.google.com/file/d/13_d1rku8DmE5x6tFUAniegvGsD95ZrGv/view?usp=sharing)

**VS Code**: [plugin](https://drive.google.com/file/d/1WRQk9Ame71ZGMYsITdwTf_r_hkY5CsYH/view?usp=sharing)

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins retest this
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins retest this

**Comment by Josephblt** [comment]
Hello @LuboTerifaj, updated everything. VSCode extension, Business Central war, so this is ready to test. Thanks.

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fd
Jenkins retest thisb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Hello @LuboTerifaj, @romartin. This is ready for review. Thanks.

**Review by romartin — APPROVED** [review]
LGTM, thanks @Josephblt !

@LuboTerifaj please try to give priority to this ticket, as it's targeting RHPAM 7.10.1, and so we'll have to cherry-pick it ASAP.

Thanks guys!

**Review by LuboTerifaj — APPROVED** [review]
Hello @Josephblt ,

It looks good to me.

Thank you!

**Pull request merged**
