### PR TITLE
AF-1632: [Form Modeler] Error appears after clicking New Instance in MultipleSubForm Field properties modal window

### PR DESCRIPTION
**Pull request by pefernan**
@jsoltes I think you are the reviewer for this issue right?

This is part of an ensemble, please merge with:
https://github.com/kiegroup/kie-wb-common/pull/2205
https://github.com/kiegroup/jbpm-wb/pull/1222

### CODE REVIEW

**Comment by pefernan** [comment]
please jenkins execute full downstream build

**Comment by pefernan** [comment]
DO NOT MERGE! I need to fix a small issue on jbpm-wb

**Comment by pefernan** [comment]
please jenkins execute full downstream build

**Comment by pefernan** [comment]
please jenkins execute full downstream build

**Comment by pefernan** [comment]
please jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by pefernan** [comment]
please jenkins execute full downstream build

**Comment by pefernan** [comment]
@jsoltes I see, updated the code. Let's see

**Comment by jsoltes** [comment]
jenkins please retest this

**Comment by pefernan** [comment]
please jenkins execute full downstream build

**Pull request merged**
