### PR TITLE
JBPM-9232 GAV not found in the Maven repository Error while creating …

### PR DESCRIPTION
**Pull request by bxf12315**
…deployment unit from business-central UI

### CODE REVIEW

**Comment by bxf12315** [comment]
Jenkins execute full downstream build please

**Comment by bxf12315** [comment]
Jenkins execute full downstream build please

**Comment by jstastny-cz** [comment]
jenkins execute full downstream build please

**Comment by bxf12315** [comment]
> (I want to r

I'm not sure, I will investigate it.

**Comment by prashuts** [comment]
And facing issue while adding Deployment Unit , enter dummy GAV details manually and click finish.
Created JIRA for the same - https://issues.redhat.com/browse/JBPM-9273

@bxf12315 Let us know if you have any update on this.

**Comment by bxf12315** [comment]
> Looks good - verified that for a GAV not present in maven repository that BC is configured to use there's a warning dialog informing about the situation, but can be overruled to continue with such deployment.
> 
> One thing though - after the warning is confirmed (I want to really create such deployment), the dialog disappears and it takes a while before the deployment is created - during that time user can interact with the original form. Can we add a wait spinner or something?
> 
> gav-not-exists

about this one, I suggest you split it to another issue. WDYT?

**Comment by jstastny-cz** [comment]
jenkins retest this

**Pull request merged**
