### PR TITLE
Update kie-takari-plugin dependency resolution to run maven compiler …

### PR DESCRIPTION
**Pull request by cristianonicolai**
…tests in offline mode

### CODE REVIEW

**Comment by jhrcek** [comment]
@cristianonicolai I think this is good to merge

**Comment by cristianonicolai** [comment]
thanks @jhrcek. @mbiarnes let's keep an eye in the kieAll build to confirm it fixes the issue there.

**Comment by mbiarnes** [comment]
@cristianonicolai @jhrcek the build started before you merged the PR. The test failed again because this PR was not merged in master by the time. We have to wait until tomorrow :)

**Comment by jhrcek** [comment]
@cristianonicolai looking at the builds from last 4 days the same failures seem to be still present:
https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/kieAllBuild-master/job/kieAllBuild-master/340/artifact/kie-wb-common/kie-wb-common-services/kie-wb-common-services-backend/target/


Also (probably unrelated to this PR) the daily [kieAllBuild](https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/kieAllBuild-master/job/kieAllBuild-master/) is now failing with

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project optaplanner-wb-solver-editor-backend: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
05:20:29.490 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project optaplanner-wb-solver-editor-backend: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
```
@yurloc would this be something you'd be able to fix?

**Comment by yurloc** [comment]
@jhrcek The enforcer failure is now fixed by merging kiegroup/droolsjbpm-build-bootstrap#763.

**Comment by jhrcek** [comment]
@yurloc thank you

**Pull request merged**
