### PR TITLE
[7.3.x] JBPM-6164: Stunner - Adding new nodes from toolbox can fail with containment rule violations

### PR DESCRIPTION
**Pull request by alepintus**
@romartin Cherry pick from #1127

### CODE REVIEW

**Comment by romartin** [comment]
ok to test

**Comment by manstis** [comment]
@hasys Please let me know your opinion on you reviewing cherry-picks... 

ATM I am assigning you PRs for review regardless of whether they're cherry-picks of not.

**Comment by romartin** [comment]
@hasys need your review here please, thanks!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
CC @hasys

**Comment by manstis** [comment]
Please check with @mbiarnes 7.3.x is not frozen.. this will need to now target 7.4.x.

**Comment by romartin** [comment]
Closing this pull request as this branch has been already frozen.
@alepintus will let you know if need to provide it for 7.4.x, it's still under decision. Thx!

**Pull request closed without merging**
