### PR TITLE
JBPM-9256 - Link Events

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin, @LuboTerifaj, @domhanak 

Screenshot 2020-07-24 at 15 58 24

in this PR still missing some tests (I will use Sonar Cloud for better orientation) but it already works, I tried execute generated process and it was successfully executed.

Next week I will work on tests (including more End2End scenarios) for this PR and will try to find answers on questions from the jira [issue](https://issues.redhat.com/browse/BAPL-1296?focusedCommentId=14292719&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14292719), but I think we can split the work in parts and after addition tests will be ready just proceed with this PR and move other task (like validation) to the next tasks to avoid busy last week before merge. WDYT?

## Tested End to End scenarios
https://github.com/bpmn-tutorials/LinkEvents

## WAR file to test
https://drive.google.com/file/d/14e0tD1idOSvbhKrpIs2mSIciLtBA6g8n/view?usp=sharing
Keep in mind it contains engine fix from https://github.com/kiegroup/jbpm/pull/1718

### CODE REVIEW

**Comment by domhanak** [comment]
Code looks good to me, let me know about the artifacts, I see one test failure so I wait fro you to fix it before I run fdb for war.

**Comment by hasys** [comment]
Jenkins execute compile downstream build

**Comment by hasys** [comment]
Hi @domhanak, all is ready, reported known issues:
### Related but not blocking
[JBPM-9260](https://issues.redhat.com/browse/JBPM-9260) - Link events has reverted multiple source/target behavior
[JBPM-9265](https://issues.redhat.com/browse/JBPM-9265) - Empty Link Event name is a valid link name
[JBPM-9261](https://issues.redhat.com/browse/JBPM-9261) - It is not clear that Link Event located in different sub-processs level from Validation message
### Kogito
[KOGITO-2955](https://issues.redhat.com/browse/KOGITO-2955) - Catch Link events do not have Source tag
### Unrelated
[JBPM-9270](https://issues.redhat.com/browse/JBPM-9270) - Sequence flows loosing it's dock points

See more info, tested End To End scenarios and for WAR file here: https://github.com/kiegroup/kie-wb-common/pull/3367#issue-456308526

Thank you!

**Comment by mbiarnes** [comment]
Jenkins run compile downstream build

**Comment by mbiarnes** [comment]
Trigger-Test-Build

**Comment by hasys** [comment]
Jenkins execute compile downstream build

**Comment by domhanak** [comment]
@hasys Hi, I verified that:

    Catch and Throw Links should be present in the palette and can be used for process modelling :heavy_check_mark: 
    Event should have Node Name, Documentation, Reference Name :heavy_check_mark: 
    MAY NOT be used on the boundary :heavy_check_mark: 
    Throw doesn't have outgoing Sequence Flow :heavy_check_mark: 
    Catch doesn't have incoming Sequence Flow :heavy_check_mark: 

I was able to build & deploy all processes from https://github.com/bpmn-tutorials/LinkEvents :heavy_check_mark: 

Thanks for reporting the issues, I would suggest raising severity of https://issues.redhat.com/browse/JBPM-9260 to critical for this feature.

Proceeding to do sanity check for VSCode and  I ll let you know.

**Comment by domhanak** [comment]
Jenkins execute compile downstream build

**Comment by hasys** [comment]
Hi @domhanak,

great job, thank you!

About Kogito: keep in mind that runtime is not working there yet for Link Events. I reported an issue about it:
* [KOGITO-2943](https://issues.redhat.com/browse/KOGITO-2943) - Link events doesn't work in Kogito

**Comment by hasys** [comment]
Jenkins execute compile downstream build

**Comment by romartin** [comment]
Hey @hasys @domhanak I'm not yet merging because of I see it sholud be good to be merged with the engine fix, but anyway I'm fine with merging it anyway, so please guys lemme know your opinion, for now I'll wait.

Thanks both!!

**Pull request merged**
