### PR TITLE
JBPM-8214: fix IndexOutOfBound exception when adding item arbitrarily in TreeExplorer

### PR DESCRIPTION
**Pull request by xiezhang7**

### CODE REVIEW

**Comment by xiezhang7** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
There is issue with Java Runtime Environment, so need to rebuild it again.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @xiezhang7 ,

Did you started to work on the changes I suggested? Asking because I'm considering to merge this commit as it is, it fixes the bug which I'm always facing as well and would be nice delivering my PR on top of it, and then creating a new ticket for the improvement suggested and working on it in another branch... well up to you, if you think  you're close to complete it, I can wait a few more, otherwise, lemme know if it's good for you merging this and moving the suggestion into a new ticket/PR

Thanks!

**Comment by xiezhang7** [comment]
> Hey @xiezhang7 ,
> 
> Did you started to work on the changes I suggested? Asking because I'm considering to merge this commit as it is, it fixes the bug which I'm always facing as well and would be nice delivering my PR on top of it, and then creating a new ticket for the improvement suggested and working on it in another branch... well up to you, if you think you're close to complete it, I can wait a few more, otherwise, lemme know if it's good for you merging this and moving the suggestion into a new ticket/PR
> 
> Thanks!

Hi @romartin ,

I would like to have this PR merged and work on the changes you suggested in a new RP.
So please feel free to merge this PR.

Thanks.

**Comment by romartin** [comment]
Great, sounds good @xiezhang7 , thanks !
So please, feel tree to open a new ticket by yourself and start to work on it once possible. 
Again, good job, and thanks! :+1:

**Pull request merged**
