### PR TITLE
DROOLS-2343: [DMN Designer] Closing Context editor causes error

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-2343

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Pull request merged**
