### PR TITLE
KOGITO-2644: Add auto start property for adhoc subprocess

### PR DESCRIPTION
**Pull request by handreyrc**
Hey @romartin, @inodeman: Please could you review this PR?

### CODE REVIEW

**Comment by handreyrc** [comment]
Link to the artifacts for testing:

https://drive.google.com/file/d/1wonvyVwI7C5hX_W_SUDEDR1ZmI8gpsDL/view?usp=sharing

Thanks

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by romartin** [comment]
Jenkins retest this

**Comment by romartin** [comment]
Jenkins execute compile downstream build

**Comment by handreyrc** [comment]
@romartin, We have the builds green for this one!
Thanks

**Comment by romartin** [comment]
Please @inodeman missing your review here. Thanks!

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Please @inodeman missing your review here. Thanks!

**Comment by romartin** [comment]
Hey @handreyrc ,

I see the full downstream failing in the `stunner-showcase-project` module... any ideas why? Thx

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@handreyrc it looks the memory has been increased on CI stuff.. so let's try the FDB again! If it gets green, please lemme know and I'll merge. Thanks!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Hey @romartin, We have all green! 
Thanks!

**Pull request merged**
