### PR TITLE
Revert "JBPM-9273 System error occurred while adding deployment unit"

### PR DESCRIPTION
**Pull request by bxf12315**
This reverts commit c2fda7a88672fd491a64e3482f833f2657d500a2.

**Thank you for submitting this pull request**

**JIRA**: [JBPM-9273](https://issues.redhat.com/browse/JBPM-9273)

**Referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-integration/pull/2349
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://donwnload.here/something)

**VS Code**: [plugin](https://donwnload.here/something)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by bxf12315** [comment]
jenkins do cdb

**Comment by bxf12315** [comment]
jenkins do cdb

**Comment by bxf12315** [comment]
jenkins do cdb

**Comment by bxf12315** [comment]
jenkins do cdb

**Comment by bxf12315** [comment]
jenkins do cdb

**Comment by bxf12315** [comment]
jenkins do fdb

**Comment by bxf12315** [comment]
jenkins do fdb

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
jenkins do fdb

**Comment by sutaakar** [comment]
Looks ok, need to wait for FDB to check that it doesn't bring any regression.
@bxf12315 please cherrypick to 7.48.x too

**Comment by mareknovotny** [comment]
the failures are not related to this change but they need to be corrected too as the jira URL and authentication is probably outdated. Anyway such external URL checking should be avoided. 
`java.lang.RuntimeException: Failed to contact Jira on URL:https://issues.jboss.org/rest/api/2/issue/GUVNOR-2542, HTTP error code : 401`

**Review by sutaakar — APPROVED** [review]

**Comment by bxf12315** [comment]
jenkins do fdb

**Pull request merged**
