### PR TITLE
annotation based marshalling for Process and UserTask

### PR DESCRIPTION
**Pull request by treblereel**
DO NOT MERGE !!!

Proposed implementation of annotation-based marshalling for Process and UserTask

How to run:

The only difference with the original scenario is the need to clone and install the marshalling library,
you can find the details here https://github.com/treblereel/jackson-xml

I left original marshalling to be able to compare it with the new one.

So please take a look and leave your feedback here

ps: i am going to improve some parts in a couple of days 

online demo: https://kogito.cloud-fr1.unispace.io/

### CODE REVIEW

**Comment by romartin** [comment]
@hasys you can use this for our further work on BPMN marhsallers! :+1:

**Comment by domhanak** [comment]
@romartin @treblereel Does this PR serve any purpose. It is stale. Please advice how to proceed with this PR or close it. Thanks.

**Comment by treblereel** [comment]
@domhanak nope, it shows how https://github.com/treblereel/mapper-xml can be used instead of jasonix based marshallers. Please, keep this PR as is.

**Comment by romartin** [comment]
thanks @treblereel for the feedback, also thanks @domhanak for pointing this out.

I will let @hasys to take the decision here. He's actually working on the new BPMN marshallers, and I think he already did similar as this PR is doing, so I'll let him to take the decision whetever to close it now or keep it open for further use.

Pleaes @hasys let us know your feedback.

Thanks guys!

**Comment by hasys** [comment]
Yes, I am actively working with examples from this PR. However I can close it since code still will be there and I still will be able to check it.

**Pull request closed without merging**
