### PR TITLE
JBPM-9393 'Add Deployment unit' Fields are missing while creating new

### PR DESCRIPTION
**Pull request by bxf12315**
**Thank you for submitting this pull request**

**JIRA**: [JBPM-9393](https://issues.redhat.com/browse/JBPM-9393)

**Referenced Pull Requests**:
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://donwnload.here/something)

**VS Code**: [plugin](https://donwnload.here/something)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by bxf12315** [comment]
jenkins do fdb

**Comment by bxf12315** [comment]
jenkins do fdb

**Comment by bxf12315** [comment]
jenkins retest this

**Comment by bxf12315** [comment]
jenkins retest this

**Comment by prashuts** [comment]
jenkins do fdb

**Comment by prashuts** [comment]
@bxf12315 can you please look into 'Linux - Pull Request' failures

**Comment by bxf12315** [comment]
jenkins retest this

**Comment by prashuts** [comment]
Blocked for verifying PR by https://issues.redhat.com/browse/RHPAM-3111.
@bxf12315  Please have a look

**Review by nmirasch — COMMENTED** [review]
@bxf12315 missing some test addition here

**Comment by bxf12315** [comment]
> issues.redhat.com/browse/RHPAM-3111

According to what we discussed,RHPAM-3111 is not a block issue for the PR. please review it.

**Comment by bxf12315** [comment]
jenkins do cdb

**Comment by bxf12315** [comment]
jenkins retest this

**Comment by bxf12315** [comment]
jenkins retest this

**Comment by bxf12315** [comment]
jenkins do cdb

**Comment by bxf12315** [comment]
jenkins do cdb

**Comment by bxf12315** [comment]
jenkins do cdb

**Comment by bxf12315** [comment]
jenkins do cdb

**Review by nmirasch — APPROVED** [review]
LGTM

**Comment by prashuts** [comment]
Good to go.

**Comment by prashuts** [comment]
Blocked to verify PR due to https://issues.redhat.com/browse/BXMSPROD-1067

**Comment by bxf12315** [comment]
jenkins do cdb

**Comment by Ginxo** [comment]
jenkins do fdb

**Review by prashuts — APPROVED** [review]
LGTM

**Pull request merged**
