### PR TITLE
[DO NOT MERGE] Trial of OOME fix

### PR DESCRIPTION
**Pull request by manstis**
@hasys This contains a potential fix for the CM OOME; could you give it a kick when time permits before I submit as a real solution - it'll need moving back to Lienzo after @romartin has moved KIE to Lienzo 2.0.285-RELEASE.

### CODE REVIEW

**Comment by manstis** [comment]
@hasys This is revision on the original PR. 

Would you mind giving it a kick when you feel like wasting an hour before lunch; and have nothing else to do?

**Comment by hasys** [comment]
Hi @manstis,
thank you, it feel like Case Management is more smooth now, but I am still able to reproduce OOM exception. My Google Chrome is freezes and kill page with Showcase Project after some time.

But it's happens only if I open Preview&Explorer panel. After some movements memory usage is growing from ~400Mb to 1.8Gb and fail with OOM. I am not sure what is the reason. In this situation, probably Explorer also can be a reason of this error.

Another test: I reached about 1.2Gb of used memory and close Case Management, after several seconds (10-15s) memory reach 1.3Gb of used memory. So I guess this memory leak is quite serious problem :(

**Comment by hasys** [comment]
I found Stack Trace in my Chrome console, hope it will helpful:
```
ErraiConsoleLogHandler.java:91 Error caused by: JavaScriptException: (RangeError) : Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
    at Ud_g$ (NativeContext2D.java:408)
    at Cb_g$._b_g$ [as getImageData_0_g$] (Context2D.java:346)
    at NNN_g$.hOb_g$ [as init_13_g$] (ColorMapBackedPicker.java:83)
    at NNN_g$.bOb_g$ (ColorMapBackedPicker.java:71)
    at NNN_g$ (CaseManagementColorMapBackedPicker.java:34)
    at SNN_g$.YNN_g$ [as makeColorMapBackedPicker_0_g$] (CaseManagementDockingAndContainmentControlImpl.java:108)
    at SNN_g$.FNb_g$ [as dragStart_1_g$] (WiresDockingAndContainmentControlImpl.java:123)
    at SNN_g$.VNN_g$ [as dragStart_1_g$] (CaseManagementDockingAndContainmentControlImpl.java:44)
    at QNb_g$.UNb_g$ [as dragStart_1_g$] (WiresShapeControlImpl.java:78)
    at IIb_g$.QIb_g$ [as startDrag_0_g$] (WiresShape.java:313)
    at Q_b_g$ (DragContext.java:109)
    at h0b_g$.n0b_g$ [as doDragStart_0_g$] (LienzoHandlerManager.java:508)
    at h0b_g$.o0b_g$ [as doPrepareDragging_0_g$] (LienzoHandlerManager.java:647)
    at h0b_g$.y0b_g$ [as onNodeMouseMove_1_g$] (LienzoHandlerManager.java:744)
    at s1b_g$.t1b_g$ [as onMouseMove_1_g$] (LienzoHandlerManager.java:210)
    at Hlg_g$.Ilg_g$ [as dispatch_62_g$] (MouseMoveEvent.java:56)
    at Hlg_g$.Jlg_g$ [as dispatch_2_g$] (MouseMoveEvent.java:55)
    at Hlg_g$.Ss_g$ [as dispatch_1_g$] (GwtEvent.java:76)
    at tqg_g$ (EventBus.java:40)
    at Vqg_g$.Eqg_g$ [as doFire_0_g$] (SimpleEventBus.java:193)
    at Vqg_g$.Kqg_g$ [as fireEvent_3_g$] (SimpleEventBus.java:88)
    at iqg_g$.lqg_g$ [as fireEvent_1_g$] (HandlerManager.java:127)
    at A_M_g$._2b_g$ [as fireEvent_1_g$] (Widget.java:129)
    at wfg_g$ (DomEvent.java:125)
    at A_M_g$.h3b_g$ [as onBrowserEvent_0_g$] (Widget.java:177)
    at fAh_g$ (DOM.java:1481)
    at eAh_g$ (DOM.java:1420)
    at HTMLDivElement.wGh_g$ (DOMImplStandard.java:317)
    at zMe_g$ (Impl.java:239)
    at CMe_g$ (Impl.java:291)
    at HTMLDivElement.<anonymous> (Impl.java:77)
``

**Comment by manstis** [comment]
@hasys Thank-you for spending more time on this (important) issue.

I agree; without the "Explorer" dock open memory did not pass beyond ~400MB adding 10's of Stages and Activities and shuffling them around. Opening the "Explorer" dock and performing a few shuffles saw memory here explode beyond 2GB! At least it helps me focus my attention..

**Comment by manstis** [comment]
@hasys OK.. I removed the "Explorer" Tree and memory usage remains (relatively!) low; not surpassing ~400MB once user interaction stops and GC does it's job (peeks ~450MB during a "drag" - which is probably the image data used to detect "drop" zones) but falls shortly after the drag completes.. so something is wrong with the "Explorer"!

**Comment by hasys** [comment]
@manstis, wow... It's interesting. I guess in this case Stunner create and doesn't clean up huge DOM, at least JS memory (almost) not growing when I open Explorer&Preview panel

**Comment by manstis** [comment]
@hasys OK. The issue seems to be caused by SVG's for the "glyphs" shown throughout the application.

I have modified this PR to remove the surplus `````` elements from the DOM but memory is not released for ```data:image/svg+xml;base64``` URLs. If I change the URL to use (something like) ```/favicon.ico``` memory usage does not balloon and is released correctly when the Explorer/Preview dock closed. Googling reveals ```base64``` URLs seem to present a problem :-(

**Comment by manstis** [comment]
@hasys @romartin OK.. this seems to be a good fix for Explorer releasing resources; and not creating "billions" of ```Pictures``` as the Graph changes in response to nodes being added, deleted or updated. You should observe:-

1. `````` elements are created in ```<body>``` for each "Palette" glyph. They are created before the "Palette" is shown and remain after it is hidden. Ideally I'd like to tidy this up to create and destroy on demand. This PR does not address this issue.
2. A `````` element is created during a "drag" from the "Palette" to the editor. This PR ensures the element is destroyed when the "drag" operation completes.
3. Explorer creates a number of `````` elements for each item in the Graph. This PR however ensures successive elements are not created when new nodes are added, deleted or updated. All elements are released when the Explorer is closed.

Note, the browser does not release memory when SVGs are used (BPMN) but you can observer consumed memory remains pretty static when using PNG (CM).

**Comment by romartin** [comment]
@manstis  ohh Mike great job! thanks for these missing clean-ups and the researching too! :) So finally do you want to merge it, right? For me should be ok! Le'ts wait for @hasys :) 
Thanks guys!!

**Comment by manstis** [comment]
Closed and replaced with https://github.com/kiegroup/kie-wb-common/pull/743 ready for merge!

**Pull request closed without merging**
