### PR TITLE
BAPL-1593: Stunner designer ignores 'jbpm.enable.multi.con=true'

### PR DESCRIPTION
**Pull request by handreyrc**
@romartin, @inodeman: Please, could you review this PR?

### CODE REVIEW

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
artifacts ready for testing @LuboTerifaj , thanks!!

**Comment by romartin** [comment]
can you maybe @handreyrc  or @inodeman upload a WAR for testing this plz? So @LuboTerifaj  can go ahead with the review. Thx!

**Comment by romartin** [comment]
Hey @LuboTerifaj 

About the warning message that appears on BC - it comes from the server, and it's because you didn't set the jbpm.enable.multi.con=true while running the server. From the editor point of view, we don't have control over this.

About the unit tests.. well it's not easy to test this, it's just an annotations and our unit tests are not covering this.

So what's maybe missing to check are both issues about BC deployment and VSCode extension, could you please check it @handreyrc ?

**Comment by hasys** [comment]
Hi @LuboTerifaj, @romartin, @handreyrc, my 2c:
* First two points are expected and discussed in [RHPAM-2656](https://issues.redhat.com/browse/RHPAM-2656), you need to use `-Djbpm.enable.multi.con=true` when starting Business Central to use this property at the runtime.

It is not perfect and it is better to check backend property in Stunner as well, but it is not possible now and make no sense for the Kogito since there are no Server side at all, so the decision "just" to relax rules was was made. So, since this was asked by customers this solution is the only way to deliver the feature. Let's be agile and deliver feature by parts :)

* VS Code extension
looks like branch was created for 7.41 and you build VS Code plugin when master was on 7.42 so probably that's why you didn't notice the change. @handreyrc please, can you attach the VSIX for easier tests? 

* I think unit tests should tests logic, but this is declarative way of "programming" I think we shouldn't writer unit tests for declarative code like we are not doing for HTML, CSS, setters and getters. What do you think?

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute fdb

**Comment by romartin** [comment]
Jenkins execute fdb

**Comment by romartin** [comment]
Hey @LuboTerifaj 

Artifacts for testing this PR uploaded:

- [BC WAR](https://drive.google.com/file/d/1nGE5-XUQmwkoF5FsuxTl6hdc_BqMy-gK/view?usp=sharing)
- [VSCode extension](https://drive.google.com/file/d/1nGE5-XUQmwkoF5FsuxTl6hdc_BqMy-gK/view?usp=sharing)

So ready for testing! 
Thanks!

**Comment by romartin** [comment]
Jenkins execute cdb

**Comment by LuboTerifaj** [comment]
Hey @handreyrc , @romartin ,

full downstream build is failing because of out of memory issue. I have reported it here: https://issues.redhat.com/browse/BXMSPROD-980

I will test the PR with uploaded war in Roger's [comment](https://github.com/kiegroup/kie-wb-common/pull/3368#issuecomment-680524151) above.

Thanks!

**Review by LuboTerifaj — APPROVED** [review]
Hello @handreyrc , @romartin , @hasys ,

I agree with your comments above.

I didn't find any more issues, so the PR looks good to me.

Thank you!

**Comment by romartin** [comment]
tthanks @LuboTerifaj !

**Pull request merged**
