### PR TITLE
AF-2504 :Adding description when creating new Space using Business Central

### PR DESCRIPTION
**Pull request by RishiRajAnand**
- Add description field to the new space form
- Add description to the spaces listing
- Edit space description in ProjectScreen.
AF-2504
Related PR
https://github.com/kiegroup/appformer/pull/981

### CODE REVIEW

**Comment by Srihari1192** [comment]
@RishiRajAnand Please find the observations:
1.Edit icon is not present for existing Space.
2.Cancel button is not present , in case of user wish to cancel editing description.
Screenshot from 2020-06-03 13-32-52

Note: Review in progress

**Comment by Srihari1192** [comment]
@ALL suggestion..would be good on showing description on hovering on Space in space listing page....something like inside project list page 
Screenshot from 2020-06-03 14-57-04

**Comment by RishiRajAnand** [comment]
> @ALL suggestion..would be good on showing description on hovering on Space in space listing page....something like inside project list page
> Screenshot from 2020-06-03 14-57-04

Nice observation @Srihari1192 . Let me know when you are done testing, I'll include these changes for you to verify then.

**Comment by Srihari1192** [comment]
@ALL suggestion..would be good on showing description on hovering on Space in space listing page....something like inside project list page 
Screenshot from 2020-06-03 14-57-04


> > @ALL suggestion..would be good on showing description on hovering on Space in space listing page....something like inside project list page
> > Screenshot from 2020-06-03 14-57-04
> 
> Nice observation @Srihari1192 . Let me know when you are done testing, I'll include these changes for you to verify then.

@RishiRajAnand testing is done..you can include your changes

**Comment by RishiRajAnand** [comment]
I have already pushed the changes, Lets wait for FDB

**Comment by RishiRajAnand** [comment]
Jenkins execute full downstream build

**Comment by RishiRajAnand** [comment]
failures seems unrelated, running again

**Comment by RishiRajAnand** [comment]
Jenkins execute full downstream build

**Comment by RishiRajAnand** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
Two unrelated test failures.

**Pull request merged**
