### PR TITLE
BAPL-941  Export diagrams to SVG cherry-pick JBPM-6110 to 7.7.x

### PR DESCRIPTION
**Pull request by tiagodolphine**
Cherry-pick JBPM-6110 commit 9d9122532bd69240109963757af70b60d69e4eba to 7.7.x.
@romartin

### CODE REVIEW

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build.

**Comment by romartin** [comment]
@tiagodolphine does it depends on any other PR/s?

**Comment by tiagodolphine** [comment]
@romartin the PRs from Appformer and Lienzo were already merged before opening the 7.7.x , so no need to create PRs.
Anyway I thinks it is better a quick review before merging, @LuboTerifaj  can you help on this? This is just a cherry-pick from the PR you already tested.
Thanks.

**Comment by romartin** [comment]
@tiagodolphine yeah sure, makes sense! thanks for the feedback :+1:

**Comment by romartin** [comment]
Hey @tiagodolphine , sorry my fault, I told you to use an `BAPL` ticket for the cherry-picks to 7.7.x, but I was wrong, it **must be an `RHBA`**. 
Can you please close the one you created and open an RHBA for this? Also change the commit and PR messages please... sorry for the inconveniences!

**Comment by tiagodolphine** [comment]
@romartin ok created a new PR https://github.com/kiegroup/kie-wb-common/pull/1577

**Pull request closed without merging**
