### PR TITLE
JBPM 8622: Stunner - missing freetext called element (e.g. unknown or # {...} for Reusable sub-process	

### PR DESCRIPTION
**Pull request by inodeman**
@romartin can you review this PR? Changed type of control so that it allows for a New.. option, search for a previous value and ability to unset a value. Control handled those cases automatically, also please advise about unit tests as I did not find a way to test the control, I will keep looking

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@inodeman please as commented, do the rebase (and squash) and let us know once it's ready, including the builds ok for testing. 
thx!

**Comment by inodeman** [comment]
Hi @romartin I rebased it 7 remove unnecesary commits, can you review this PR again?

**Comment by inodeman** [comment]
Jenkins please retest this

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
### Check list
- [x] ACKs are set
- [x] Affected version is set property
- [x] Is realization aligned to jira description?
- [x] Both Jenkins jobs are green

### Code review
- [x] Code coverage
- [x] License headers
- [x] Static analyser gates
- [x] Code Style

### Acceptance Criteria
> * It should be possible to select different process
> * It should be possible to use Process variable as Called Element
> * Both test should be executed

- [x] Tested with full downstream build
  - [x] Firefox
  - [x] Chrome

### Found issues
>  **Blocker**, **Critical** and **Major** bugs and **Blocker** and **Critical** enhancements should be fixed before merge.

#### Unrelated issues
* [JBPM-8678](https://issues.jboss.org/browse/JBPM-8678) - Add in-line edit-ability to tables
* [JBPM-8679](https://issues.jboss.org/browse/JBPM-8679) - Script Task prints Errors on process save
* [JBPM-8680](https://issues.jboss.org/browse/JBPM-8680) - Process with Reusable sub-process print errors to the server log

### Used resources
Processes for quick test can be found here: https://github.com/bpmn-tutorials/ReusableSub-Process

**Pull request merged**
