### PR TITLE
KOGITO-6704: Fix long DMN data type constraint documentation

### PR DESCRIPTION
**Pull request by jomarko**
Backport of https://github.com/kiegroup/kie-tools/pull/833/files

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by yesamer** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Jenkins do fdb

**Review by yesamer — APPROVED** [review]

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge.

**Pull request merged**
