### PR TITLE
JBPM-6589: Field Settings lost after moving on layout

### PR DESCRIPTION
**Pull request by pefernan**
@jsoltes Could you please take a look?

This PR is a part of an ensemble, please merge with:
https://github.com/AppFormer/uberfire/pull/907
https://github.com/kiegroup/kie-wb-common/pull/1287

### CODE REVIEW

**Comment by jsoltes** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
@jsoltes let's see if we manage to have a green on the full downstream build :S

**Comment by jsoltes** [comment]
@pefernan it looks like some configuration problem in jenkins...

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Pull request merged**
