### PR TITLE
Revert "JBPM-8153 Container is removed from UI even though it was not…

### PR DESCRIPTION
**Pull request by bxf12315**
… possible to stop it."

This reverts commit 39dfa50616926d658acc01ce8a8a90735b8d46d4.

**Thank you for submitting this pull request**

**JIRA**: [JBPM-8153](https://issues.redhat.com/browse/JBPM-8153)

**Referenced Pull Requests**:
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://donwnload.here/something)

**VS Code**: [plugin](https://donwnload.here/something)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by sutaakar** [comment]
jenkins do cdb

**Comment by sutaakar** [comment]
jenkins do cdb

**Review by pefernan — APPROVED** [review]
+1 when green

**Review by nmirasch — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins do fdb

**Pull request merged**
