### PR TITLE
[JBPM-8780] Total pages for pagination is not working for limits.

### PR DESCRIPTION
**Pull request by marcuscarvalho**
The issue is addressed at https://issues.jboss.org/browse/JBPM-8780

### CODE REVIEW

**Comment by kie-ci7** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by ederign** [comment]
@tomasdavidorg are you the best to verify this?

**Comment by tomasdavidorg** [comment]
Looks good to me. Thanks :slightly_smiling_face:

**Comment by marcuscarvalho** [comment]
Thanks @adrielparedes @ederign @tomasdavidorg

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by ederign** [comment]
@marcuscarvalho thanks for this!

**Pull request merged**
