### PR TITLE
[DO NOT MERGE] AF-2833 : Conscious language initiative kie-wb-common and kie-wb-playground

### PR DESCRIPTION
**Pull request by akumar074**
**JIRA**: 
[AF-2833](https://issues.redhat.com/browse/AF-2833)
[AF-2829](https://issues.redhat.com/browse/AF-2829)

**referenced Pull Requests**: 
* https://github.com/kiegroup/kie-soup/pull/217
* https://github.com/kiegroup/appformer/pull/1149
* https://github.com/kiegroup/kie-wb-playground/pull/116
* https://github.com/kiegroup/optaplanner-wb/pull/400
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1708
* https://github.com/kiegroup/drools-wb/pull/1508
* https://github.com/kiegroup/jbpm-designer/pull/912
* https://github.com/kiegroup/jbpm-wb/pull/1508
* https://github.com/kiegroup/kie-wb-distributions/pull/1117

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by tiagobento** [comment]
@karreiro @romartin This is ready for review. Can you please take a look asap?

**Review by karreiro — COMMENTED** [review]
@tiagobento @akumar074 I believe this ensemble has different branch names across repositories (for example, this PR has the branch name `AF-2833` and the `droolsjbpm-build-bootstrap` branch name is `AF-2829`).

I believe we need the same name to successfully run the full downstream build (FDB). Initially, I assumed that it was fine because branches were independent, but as I couldn't built the `kie-wb-common` PR locally I assume they actually depend on each other.

So, should we use the same name? (in other to unsure the FDB is running).

**Comment by akumar074** [comment]
@karreiro, Thanks for taking a look. I named the branches based on the JIRA issues specific to the repositories. I wasn't sure why FDB was failing as I had referenced all other PRs in descriptions, but if this is the reason maybe we can rename all the branches to `AF-2829` (parent JIRA). 
^ @tiagobento

**Comment by akumar074** [comment]
@karreiro @tiagobento @romartin @barboras7 
I have raised a new set of PRs with `AF-2829` branch name and assigned you for review. Please take a look at https://github.com/kiegroup/kie-wb-common/pull/3665

**Pull request closed without merging**
