### PR TITLE
RHPAM-2859 :Number of assets displayed for a project doesn't matches the count displayed

### PR DESCRIPTION
**Pull request by RishiRajAnand**
**Thank you for submitting this pull request**

**RHPAM-2859**: https://issues.redhat.com/browse/RHPAM-2859

How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by RishiRajAnand** [comment]
jenkins retest this

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Review by paulovmr — APPROVED** [review]

**Comment by barboras7** [comment]
Hi @RishiRajAnand,
I tried the business central from the FDB. I am experiencing one issue. Here are the steps to reproduce:

1. Log in to business central
2. Go to Projects
3. Open MySpace
4. Click Try Samples and choose Employee Rostering
5. Click Add asset and choose DRL
6. Provide the DRL name and click Ok

There are two things that happen when I follow the above mentioned steps to reproduce:

- I get a notification about successful creation of the asset, but the Loading popup is present and the asset never appears (see the screenshot, this happens almost every time)
- sometimes, the DRL is created and the window where the editor should be is visible, but the editor is not there and when I try to close the DRL, I get the dialog about unsaved changes

Screenshot from 2020-10-19 14-14-49

I tried the above mentioned steps to reproduce with the 7.9.0 CR1 and I don't see the issue there.

**Review by barboras7 — APPROVED** [review]

**Comment by RishiRajAnand** [comment]
@paulovmr please note that the above issue is temporary and caused due to slowdown of https://repository.jboss  server. Should work fine now :)

**Comment by mareknovotny** [comment]
we need backport to 7.44.x branch too ;) @RishiRajAnand

**Pull request merged**
