### PR TITLE
DROOLS-4461: Show date picker for LocalDate

### PR DESCRIPTION
**Pull request by jomarko**
Ensemble together with:
- https://github.com/kiegroup/drools/pull/3064
- https://github.com/kiegroup/drools-wb/pull/1369
- https://github.com/kiegroup/kie-docs/pull/2786

For more details see https://issues.redhat.com/browse/DROOLS-4461

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by karreiro** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by Rikkola** [comment]
@jomarko So I got an error with these PRs using the templated editor in the https://issues.redhat.com/browse/DROOLS-5509 example.

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
Jenkins do full downstream build

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Opened more than half a year. Closing without a replacement.

**Pull request closed without merging**
