### PR TITLE
RHPAM-884 - Ad-Hoc Subprocess - autostart property for script task

### PR DESCRIPTION
**Pull request by Josephblt**
https://issues.jboss.org/browse/RHPAM-884

Ad-Hoc Autostart property is now available in script tasks.

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Hello @romartin, saw your comment on the JIRA about the urgency on this. Seemed quick, so I went ahead and implemented it. Fell free to add the people whom it may concern.

**Comment by romartin** [comment]
As the J builds are a bit old.. lemme guys re-fire them. Once everything ok I'll merge. Thx!

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Pull request merged**
