### PR TITLE
DROOLS-4396: Focus expression grid after search is closed

### PR DESCRIPTION
**Pull request by jomarko**
For more details see the jira https://issues.jboss.org/browse/DROOLS-4396

The PR is dependent on #2791

### CODE REVIEW

**Comment by jomarko** [comment]
@karreiro I would like to ask you for review. However as it is based on you PR, I created just draft PR without test, just to find out what do you think about my proposed approach to solve this.

**Comment by karreiro** [comment]
Thank you, @jomarko. The proposed approach makes sense. Great job adding the default interface ;-)

Unfortunately, I'm going to commit changes in my PR that will generate some conflicts here (nothing that invalidates your approach). So, I think you could wait a little bit, before writing the unit tests to avoid new conflicts hehe (I will commit my changes by tomorrow until the EOD).

Anyhow, the draft is ✅ approved for now ;-)

**Comment by jomarko** [comment]
@karreiro thank you for review. I will wait for your changes and then resolve conflicts and add unit tests.

**Comment by jomarko** [comment]
@karreiro may I ask you for a re-review?

**Pull request merged**
