### PR TITLE
[7.5.x] GUVNOR-3486: [Guided Decision Table Graph] Refresh after removal of table

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-3486

This is the corollary of https://github.com/kiegroup/kie-wb-common/pull/1316 for 7.5.x

(cherry picked from commit 2a38bfed0f546b386ee3a35b894c9c320ad604b3)

### CODE REVIEW

**Comment by manstis** [comment]
Part of an ensemble:
- https://github.com/kiegroup/kie-wb-common/pull/1319
- https://github.com/kiegroup/drools-wb/pull/732

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
The broken test is not related to this PR, see:
```

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
