### PR TITLE
JBPM-7294 [RHPAM-1065] (Stunner) - Catching Error event on canvas

### PR DESCRIPTION
**Pull request by Josephblt**
Created a new role to identify all base elements.
And removed this role from the element that can't be contained.
This way all rules and decorations using the role "all" aren't affected.

Issue:
[RHPAM-1065](https://issues.jboss.org/browse/RHPAM-1065)
[JBPM-7294](https://issues.jboss.org/browse/JBPM-7294)

7.7.x Branch PR's:
kiegroup/kie-wb-common
#1998 

Master PR's:
kiegroup/kie-wb-common
[this one](https://github.com/kiegroup/kie-wb-common/pull/1979)

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Hey @romartin. All fixed now according to what you suggested. Can you please review it? Thanks.

**Comment by Josephblt** [comment]
Jenkins retest this

**Comment by romartin** [comment]
ok to test

**Comment by hasys** [comment]
Hi @Josephblt, I guess this PR should be closed as we decided to postpone this feature, am I correct?

**Comment by romartin** [comment]
@Josephblt yeah I'm asking same Q as @hasys - can we close this PR and create a ticket for this, if it does not exist? Sorry I don't remember the status for this...

**Comment by hasys** [comment]
This PR is outdated and can be closed.

**Pull request closed without merging**
