### PR TITLE
GUVNOR-3128: Store Guvnor ALA state using VFS (#1018)

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit d19f700e29ca5c9d1a1a590e15ad380074aeb83a)

### CODE REVIEW

**Comment by wmedvede** [comment]
@porcelli This is the peer PR for the already merged into 7.2.x branch:
    https://github.com/kiegroup/kie-wb-common/pull/1018

Would you mind review?
Thanks

depends on:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/498
https://github.com/kiegroup/guvnor/pull/489

**Comment by wmedvede** [comment]
jenkins retest this

**Comment by wmedvede** [comment]
this has now failed because of this

13:34:51 [INFO] Total time: 11:24 min (Wall Clock)
13:34:51 [INFO] Finished at: 2017-08-04T09:34:51-04:00
13:34:53 [INFO] Final Memory: 1085M/1950M
13:34:53 [INFO] ------------------------------------------------------------------------
13:34:53 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project kie-wb-common-forms-jbpm-integration-api: Compilation failure
13:34:53 [ERROR] /home/jenkins/workspace/kie-wb-common-downstream-pullrequests/kie-wb-common-forms/kie-wb-common-forms-integrations/kie-wb-common-forms-jbpm-integration/kie-wb-common-forms-jbpm-integration-api/src/main/java/org/kie/workbench/common/forms/jbpm/model/authoring/document/definition/DocumentFieldDefinition.java:[29,1] Internal error in org.kie.workbench.common.forms.adf.processors.FormDefinitionsProcessorjava.lang.ExceptionInInitializerError
13:34:53 [ERROR] at org.kie.workbench.common.forms.adf.processors.FormDefinitionsProcessor.writeTemplate(FormDefinitionsProcessor.java:674)
13:34:53 [ERROR] at org.kie.workbench.common.forms.adf.processors.FormDefinitionsProcessor.extracFormFields(FormDefinitionsProcessor.java:633)
13:34:53 [ERROR] at org.kie.workbench.common.forms.adf.processors.FormDefinitionsProcessor.extractParentFormFields(FormDefinitionsProcessor.java:420)
13:34:53 [ERROR] at org.kie.workbench.common.forms.adf.processors.FormDefinitionsProcessor.processFormDefinition(FormDefinitionsProcessor.java:344)
13:34:53 [ERROR] at org.kie.workbench.common.forms.adf.processors.FormDefinitionsProcessor.processFormDefinitions(FormDefinitionsProcessor.java:323)
13:34:53 [ERROR] at org.kie.workbench.common.forms.adf.processors.FormDefinitionsProcessor.processWithExceptions(FormDefinitionsProcessor.java:129)
13:34:53 [ERROR] at org.uberfire.annotations.processors.AbstractErrorAbsorbingProcessor.process(AbstractErrorAbsorbingProcessor.java:78)
13:34:53 [ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
13:34:53 [ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
13:34:53 [ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
13:34:53 [ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
13:34:53 [ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
13:34:53 [ERROR] at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
13:34:53 [ERROR] at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
13:34:53 [ERROR] at com.sun.tools.javac.main.Main.compile(Main.java:523)
13:34:53 [ERROR] at c

**Comment by wmedvede** [comment]
weird, wondering if this PR now needs to be rebased again against master

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins please execute full downstream build

**Pull request merged**
