### PR TITLE
Stunner maven-surefire-plugin configurations for kie-wb-common-stunner-bpmn-backend module

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi @hasys  @romartin @tiagodolphine @xiezhang7 
This PR has the memory settings for the maven-surefire-plugin discussed in the JIRA.
Independently of the additional findings I think it will be nice/required to have this at least to be sure the UserTaskTest don't run out of memory.

Would you mind take a look?
Thanks

**Comment by xiezhang7** [comment]
Hi , I have tested. With this fix, all the tests will pass on my local machine. Thanks @wmedvede .

**Comment by romartin** [comment]
please @xiezhang7 approve this PR  once you feel happy with it, thanks!

**Comment by manstis** [comment]
@hasys if you're ok with this please approve and I'll merge.

We have enough failing PRs in this repository due to this!

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
@wmedvede Please let me know when the FDB is green and I'll happily merge...

**Comment by wmedvede** [comment]
Hi @manstis  full build failed as usual but in un-related tests
I believe we can go ahead with the merge.

Thanks!

Test Result (11 failures / ±0)
org.jbpm.designer.web.server.TransformerServletTest.testScalePDFImage[0]
org.jbpm.designer.web.server.TransformerServletTest.testSharePdf[0]
org.jbpm.designer.web.server.TransformerServletTest.testSharePng[0]
org.jbpm.designer.web.server.TransformerServletTest.testTransformToPdf[0]
org.jbpm.designer.web.server.TransformerServletTest.testTransformToPng[0]
org.jbpm.designer.web.server.TransformerServletTest.testScalePDFImage[1]
org.jbpm.designer.web.server.TransformerServletTest.testSharePdf[1]
org.jbpm.designer.web.server.TransformerServletTest.testSharePng[1]
org.jbpm.designer.web.server.TransformerServletTest.testTransformToPdf[1]
org.jbpm.designer.web.server.TransformerServletTest.testTransformToPng[1]
org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded

**Comment by hasys** [comment]
Hi @mareknovotny, @jhrcek,

tests mentioned in previous comment https://github.com/kiegroup/kie-wb-common/pull/2478#issuecomment-463586740 failing only on Jenkins. Is it some configuration issue?

**Comment by jhrcek** [comment]
@hasys It looks like configuration issue to me, but I don't know how to fix it.
From the [history of these failures](http://janhrcek.cz/random-failures/#/class/org.jbpm.designer.web.server.TransformerServletTest) I see that they started failing on 2019-01-04 which I believe is around the date when kie-jenkins was migrated to upshift.
These tests are not failing in QE jenkins environment. I compared the configuration of [PR builder job](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-common-downstream-pullrequests)(has failures) and [QE community tests job](https://rhba-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/BxMS/job/RHPAM-master-nightly/job/baseline/job/blessed-community-tests-bcentral-legacy-designer-baseline)(doesn't have failures) and didn't find any relevant difference.

Maybe let's ask @cimbalek if he ever saw this kind of error which looks like the cause of those tests failures:

```
java.awt.AWTError: Can't connect to X11 window server using ':49' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
```

**Comment by romartin** [comment]
can I merge guys??

**Comment by wmedvede** [comment]
> @hasys It looks like configuration issue to me, but I don't know how to fix it.
> From the [history of these failures](http://janhrcek.cz/random-failures/#/class/org.jbpm.designer.web.server.TransformerServletTest) I see that they started failing on 2019-01-04 which I believe is around the date when kie-jenkins was migrated to upshift.
> These tests are not failing in QE jenkins environment. I compared the configuration of [PR builder job](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-common-downstream-pullrequests)(has failures) and [QE community tests job](https://rhba-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/BxMS/job/RHPAM-master-nightly/job/baseline/job/blessed-community-tests-bcentral-legacy-designer-baseline)(doesn't have failures) and didn't find any relevant difference.
> 
> Maybe let's ask @cimbalek if he ever saw this kind of error which looks like the cause of those tests failures:
> 
> ```
> java.awt.AWTError: Can't connect to X11 window server using ':49' as the value of the DISPLAY variable.
> 	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
> ```

Hi @hasys @jhrcek , not sure if I understand. But this failing tests reported by @jhrcek are not related with the stunner project, and the changes in this PR apply only for a particular internal stunner module.

**Comment by jhrcek** [comment]
@wmedvede yes, those failures are unrelated and shouldn't block merging this PR.

**Comment by wmedvede** [comment]
Hello @manstis , would you mind merge this PR?
Thanks!

**Comment by manstis** [comment]
Jenkins please retest this.

@wmedvede Please let me know when at least one of the builds is green.

**Comment by wmedvede** [comment]
@manstis ah, you relaunched a new bulid? but all was ok. I'll keep an eye on this

**Comment by hasys** [comment]
Unstable tests failed, fix for them provided by https://github.com/kiegroup/kie-wb-common/pull/2484

@manstis WDYT should we rerun this PR one more time any way?

**Comment by manstis** [comment]
@hasys I think we should always strive for a green build....

Jenkins please retest this (even if test may fail until #2484 is merged!)

**Comment by hasys** [comment]
Agree, @manstis sounds good to me.

**Comment by wmedvede** [comment]
@manstis @hasys  fix provided by #2484 not solve all the issues, only the "random tests faiures", but no the "UserTaskTest" memory issues. I'd still suggest merging this.

**Comment by manstis** [comment]
@wmedvede OK.. given this contains no _code_ changes; I agree.

Could you ping me when the local build completes (success or failure) and I'll merge.

**Comment by wmedvede** [comment]
Jenkins please retest this

**Comment by wmedvede** [comment]
bad luck
:15:42 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15:15:42 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15:15:42 	at java.lang.Thread.run(Thread.java:748)
15:15:42 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to kie-psi-rhel7-xlarge-3369
15:15:42 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
15:15:42 		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
15:15:42 		at hudson.remoting.Channel.call(Channel.java:908)
15:15:42 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
15

**Comment by wmedvede** [comment]
Jenkins please retest this

**Comment by wmedvede** [comment]
nice
07:24:07  > git fetch --tags --progress https://github.com/kiegroup/kie-wb-common.git +refs/pull/*:refs/remotes/origin/pr/*
07:24:08 ERROR: Error fetching remote repo 'origin'
07:24:08 hudson.plugins.git.GitException: Failed to fetch from https://github.com/kiegroup/kie-wb-common.git
07:24:08 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:862)
07:24:08 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1129)
07:24:08 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1160)
07:24:08 	at hudson.scm.SCM.checkout(SCM.java:495)

**Comment by wmedvede** [comment]
Jenkins please retest this

**Comment by wmedvede** [comment]
Jenkins please retest this

**Comment by wmedvede** [comment]
@romartin looks like this PR will never got the greens again.
Even so, considering that it was green in the past, and we all know that this only configuration won't generate any problems I'd strongly suggest to merge to facilitate others life while the real problem "UserTaskTest" is investigated.

Thanks.

p.s. looks like it's generating problems in @treblereel PR
https://github.com/kiegroup/kie-wb-common/pull/2480#issuecomment-465217846

**Comment by wmedvede** [comment]
Master is not blocked any more, branches for 7.1.8.x were already created.

**Comment by romartin** [comment]
@wmedvede last try....

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by jhrcek** [comment]
I am trying one way to fix TransformerServletTest failures in full downstream jobs.
The failures seem to be cause by xvnc server (which starts X11 Window server) fails to start, which causes initialization failure in that test class.  One tweak in job configuration should fix that. This is entirely unrelated to this PR. I'm just using it as a vehicle to confirm my theory.. 
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
GWT compiler crashed:
```
[INFO] # A fatal error has been detected by the Java Runtime Environment:
[INFO] #
[INFO] #  SIGSEGV (0xb) at pc=0x00007f8e67b705d3, pid=4651, tid=0x00007f8e4adcc700
[INFO] #
[INFO] # JRE version: Java(TM) SE Runtime Environment (8.0_202-b08) (build 1.8.0_202-b08)
[INFO] # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.202-b08 mixed mode linux-amd64 compressed oops)
[INFO] # Problematic frame:
[INFO] # V  [libjvm.so+0x4115d3]  ciObjectFactory::create_new_metadata(Metadata*)+0x333
[INFO] #
[INFO] # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
[INFO] #
[INFO] # An error report file with more information is saved as:
[INFO] # /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-downstream-pullrequests/downstream-repos/optaplanner-wb/optaplanner-wb-ui/target/hs_err_pid4651.log
[INFO] #
[INFO] # Compiler replay data is saved as:
[INFO] # /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-downstream-pullrequests/downstream-repos/optaplanner-wb/optaplanner-wb-ui/target/replay_pid4651.log
[INFO] #
[INFO] # If you would like to submit a bug report, please visit:
[INFO] #   http://bugreport.java.com/bugreport/crash.jsp
```

Jenkins execute full downstream build

**Pull request merged**
