### PR TITLE
AF-1143: Not possible to work with repository with project having invalid/missing pom.xml

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/AF-1143

Fixes an issue @jhrcek found. Looks like this area tends to break easily.

Any reviews are welcomed @barboras7 @paulovmr

### CODE REVIEW

**Comment by barboras7** [comment]
Jenkins execute full downstream build

**Comment by barboras7** [comment]
Thanks @Rikkola, tried locally and the issue is fixed.

**Comment by jhrcek** [comment]
Full build green, let's just make repo build green as well
jenkins retest this

**Comment by jhrcek** [comment]
Double green! @manstis can you merge, please?

**Pull request merged**
