### PR TITLE
[RHPAM-1564] Exception while deployment of kjar in RHPAM 7.0.2

### PR DESCRIPTION
**Pull request by elguardian**
setting the content type of the request from UI to avoid kie-server marshalling error

### CODE REVIEW

**Comment by elguardian** [comment]
@karreiro @cimbalek  can anyone review this ?

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by sutaakar** [comment]
Jenkins execute full downstream build

**Comment by sutaakar** [comment]
Checked on local build against steps to reproduce from JIRA, works correctly with changes.

**Pull request merged**
