### PR TITLE
KOGITO-3998 - It's not possible to save arrow edits

### PR DESCRIPTION
**Pull request by Josephblt**
Model was not being updated after changes were made to the sequence flow.

**JIRA**: [KOGITO-3998](https://issues.redhat.com/browse/KOGITO-3998)

**Business Central**: [WAR file](https://drive.google.com/file/d/1JHgi6W8A3LkALKb64LMSpqcOcBdMhuIs/view?usp=sharing)

**VS Code**: [plugin](https://drive.google.com/file/d/1VxptH083cAxu87CXMJ_YdldbE_6WhA3n/view?usp=sharing)

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Review by handreyrc — APPROVED** [review]
Hey @Josephblt, Great job! 
It's fixed.

**Comment by romartin** [comment]
@LuboTerifaj @domhanak can you please guys dome some review for this? We would like to include this in the RHPAM 7.10 release, so would appreciate early feedback!
Thanks in advance!

**Review by ljmotta — APPROVED** [review]
LGTM. It's fixed on the Online Editor. Thanks @Josephblt !

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hi @Josephblt , @romartin ,

I have found just one issue:

- In DMN editor, associations are never saved. Dialogue window with successful save operation is shown, however once the editor is closed and then opened back, these associations (arrows) are in the initial state.

Thank you!

**Comment by romartin** [comment]
Hey @LuboTerifaj 

Thanks for the quick review. 

Looking at the fix, I don't think the issue on DMN is related to this one. 

Could you please @Josephblt verify? I don't think we're on time to fix the DMN issue, if it's not related, but at least we'll be able to report it and go ahead with this fix.

Thx guys!

**Comment by romartin** [comment]
Hey @Josephblt 

Can you please share feedback here with @LuboTerifaj ?

As far as I know, the issue on DMN is NOT related, so you're reporting a new ticket and also working for a fix, but in a dfferent PR. So I understand we could try to get this fix merged for the release, it's quite important and eventhough it's still some issue there, we're much better than before.

Thanks guys!!

**Comment by Josephblt** [comment]
Hello @romartin, @LuboTerifaj. Here is the new Jira for us to track the DMN Editor problem.
https://issues.redhat.com/browse/JBPM-9528
If you agree @LuboTerifaj please approve this and we can go ahead with merge. Thanks guys.

**Review by LuboTerifaj — APPROVED** [review]
Since the found issue will be fixed in separate jira, I am approving the PR. Thanks!

**Comment by manstis** [comment]
Hi @romartin @Josephblt @LuboTerifaj I just happened to see this.

I'm confident you already have it covered but please be sure to liaise with @danielzhe and/or @karreiro about the DMN issue.

**Comment by Josephblt** [comment]
Hello @manstis. I've talked to @danielzhe and he confirmed the issues exists.

**Pull request merged**
