### PR TITLE
JBPM-9424 - Stunner does not read all parameters defined in WID

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin, @LuboTerifaj, @domhanak I synchronized with engine and moved WID to separated files. Please, see **PR implementation details** section and let me know what do you think about this solution and I will continue my tests. Thank you!

**JIRA**: [JBPM-9424](https://issues.redhat.com/browse/JBPM-9424)

**Business Central**: [WAR](https://drive.google.com/file/d/1B1lYyGLHhfS6dDazcqM0spQ9VRDE6Bsh/view?usp=sharing)

**VS Code**: not affected

### PR implementation details
* When you create new process several WID files created:
  * WorkDefinitions.wid
  * BusinessRuleTask.wid
  * DecisionTask.wid
  * Email.wid
  * Rest.wid
  * WebService.wid
* Custom tasks categories and tasks icons now updated and synchronized with engine as well:
image
* There is still some differences between Designer WID and engine WIDs:
  * User friendly layout in designer's version and generated layout in engine's WID
  * Designer's WID doesn't have `mavenDependencies` property since we don't know with which one version of Business Central it will be used. This property will be added automatically during Custom Task WIH installation.
* Now when you install new Custom task it will be overridden by business central so issues like [JBPM-9106](https://issues.redhat.com/browse/JBPM-9106), won't affect new projects anymore. 
* Also I didn't update Milestone and Log tasks since I didn't found WID in the engine. See [engine repository](https://github.com/kiegroup/jbpm/blob/7.44.x/jbpm-workitems/jbpm-workitems-rest)

Thank you! PR is ready for review.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by romartin** [comment]
Hey @hasys 

Thanks for this work! At least it's good to see proposals for solutions, so well done :+1: 

I'm still thinking about defaulting to the creation of several wid files, on per each custom task (work item). For now I don't see any implications, also if you test and ensure that this way, once deploying custom tasks in BC, we'll have no issues due to duplication of declarations, looks good. 

Anyway I would prefer to double check this, as usually in the BC lifecycle, the .wid files are being created by the designer, as user should start by modelling, so I understand that at least the engine is consuming those wid files, from the VFS, and so let's ask  @cristianonicolai or @krisv if that looks good for the runtime side as well. Any feedback on thsi guys? I would like to be sure we're not breaking something with this fix :)

Last Q @hasys - does this change only applies to BC? Will kogito editors still be providing a single wid file?

Thanks!

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
Hi @romartin,

this multi file structure is not new, when you install new Custom Task or create new WID asset in business central it will create separate WID file in the same **global** directory.

I tested separate files before, and in this PR nothing changed from this point of view.

About Kogito: this PR is Business Central specific, Kogito isn't affected and separate issue will handle it.

Thank you!

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
Builds restarted due to unstable CI:
<details>
  <summary>Stacktrace</summary>
  <pre>groovy.lang.MissingPropertyException: No such property: owner for class: java.util.AbstractMap$SimpleImmutableEntry
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
    at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.getProperty(DefaultInvoker.java:39)
    at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
    at githubscm.getForkedProjectName(githubscm.groovy:204)
    at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.find(CpsDefaultGroovyMethods:4061)
    at githubscm.getForkedProjectName(githubscm.groovy:204)
    at ___cps.transform___(Native Method)
    at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
    at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
    at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
    at sun.reflect.GeneratedMethodAccessor428.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
    at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
    at com.cloudbees.groovy.cps.Next.step(Next.java:83)
    at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
    at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
    at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
    at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
    at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
    at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
    at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
    at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
    at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
    at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
    at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE</pre>
</details>

**Comment by domhanak** [comment]
jenkins do cdb

**Comment by hasys** [comment]
<details>
  <summary>Stack trace of Compile build failure</summary>
  <pre>groovy.lang.MissingPropertyException: No such property: owner for class: java.util.AbstractMap$SimpleImmutableEntry
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
    at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.getProperty(DefaultInvoker.java:39)
    at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
    at githubscm.getForkedProjectName(githubscm.groovy:204)
    at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.find(CpsDefaultGroovyMethods:4061)
    at githubscm.getForkedProjectName(githubscm.groovy:204)
    at ___cps.transform___(Native Method)
    at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
    at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
    at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
    at sun.reflect.GeneratedMethodAccessor428.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
    at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
    at com.cloudbees.groovy.cps.Next.step(Next.java:83)
    at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
    at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
    at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
    at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
    at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
    at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
    at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
    at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
    at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
    at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
    at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
    at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE</pre>
</details>

Issue is fixed now by https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/5c016699706abbc6d2a88f7cf1fecf6f1be749a0

jenkins do cdb

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @hasys ,

I have found a few issues. See my comments below:

- Just an observation, the custom tasks are not under one single category "Custom tasks", but they are in individual categories.  Only Log task is under "CUSTOMTASKS" category. I know this is caused by properties defined in WID, but shouldn't be they better placed, especially when custom tasks are not installed yet?

- Just for the record, Decision and Business rule tasks are missing "Language" data input since it is not present in engine either.

- WebService, Decision and BusinessRule tasks use different naming on the canvas. They are not consistent.

- The generated documentation contains huge thumbnails. The issue is present also on master. It should be fixed asap, especially once this PR will be merged:
   - See already reported issue for more details: https://issues.redhat.com/browse/RHPAM-2759
 
 - If you didn't close a WID and try to install related Custom task from project Settings, an error message is shown: "User has updated the following resource default://master@MySpace/project/global/WID_NAME.wid."
   - This should be resolved to avoid confusion.
 
- If a user installs all Custom tasks and then uninstalls them from project Settings, all WID files are removed from the project. As a result, Custom tasks are no longer available in the palette.
 
 - If you close the process with Custom tasks, delete/uninstall all work item definitions,  reopen the process, download the process, import the process back and install WIDs back, the nodes are no more Custom tasks, they are just "None tasks".
   - Data is not present in bpmn source after downloading it.
   - This should be resolved to prevent users from data loss.
 
 - If you install Custom tasks from Project Settings first and then create a business process. WIDs are not created in the project at all, hence Custom tasks that haven't been installed yet are missing in the Palette.  
 
 - In Case project, there are created two different common WIDs as it is also on master, but one of them still contains custom task definitions. Is there any reason why they are needed there, or should they rather be removed?

Thank you!

**Comment by hasys** [comment]
Hi @LuboTerifaj, great catches! But sorry it is not clear for me what kind of changes do you require. There are many notes, some of them just an observation, some of them just for the record, some issues reproducible on master branch. Can I ask you to specify what should I change to get approve for this PR?

I will add my comments meanwhile inline: 

> Hello @hasys ,
> 
> I have found a few issues. See my comments below:
> 
>     * Just an observation, the custom tasks are not under one single category "Custom tasks", but they are in individual categories.  Only Log task is under "CUSTOMTASKS" category. I know this is caused by properties defined in WID, but shouldn't be they better placed, especially when custom tasks are not installed yet?

I think it's better to keep WID synchronized with engine. If you think it will be good to change categories, we will need to create 2 PR for engine and for the Designer, also keep in mind that it can cause potential backward compatibility issues so I suggest to discuss potential improvements in separate jira issue.

>     * Just for the record, Decision and Business rule tasks are missing "Language" data input since it is not present in engine either.

True, WID in Designer was aligned with Engine. Since "Language" property missing on the engine side it is "missing" in Designer as well.

>     * WebService, Decision and BusinessRule tasks use different naming on the canvas. They are not consistent.

This is know unrelated issue see [JBPM-7072](https://issues.redhat.com/browse/JBPM-7072) and unrelated to this PR.

>     * The generated documentation contains huge thumbnails. The issue is present also on master. It should be fixed asap, especially once this PR will be merged:
>       
>       * See already reported issue for more details: https://issues.redhat.com/browse/RHPAM-2759

This is reproducible on master as well. Not sure it should be fixed in this PR.

>     * If you didn't close a WID and try to install related Custom task from project Settings, an error message is shown: "User has updated the following resource default://master@MySpace/project/global/WID_NAME.wid."
>       
>       * This should be resolved to avoid confusion.

This is default Business Central behavior, when you override file by another operation all open assets will show this dialog, not sure what should be resolved in this PR.

>     * If a user installs all Custom tasks and then uninstalls them from project Settings, all WID files are removed from the project. As a result, Custom tasks are no longer available in the palette.

Yes, it is caused by moving WID to separate files to align with Engine behavior. Not sure how it should be handled in this PR. Also, if user removed Custom tasks I think user don't need it in this project. Keep in mind that tasks removed on project level only so in projects where user didn't remove Custom tasks or in the any new project Custom tasks present as usual. 

>     * If you close the process with Custom tasks, delete/uninstall all work item definitions,  reopen the process, download the process, import the process back and install WIDs back, the nodes are no more Custom tasks, they are just "None tasks".
>       
>       * Data is not present in bpmn source after downloading it.
>       * This should be resolved to prevent users from data loss.

It is same as on the master branch and we have separate jira issue for it, see [KOGITO-3528](https://issues.redhat.com/browse/KOGITO-3528) I don't think it should be fixed in this PR.

>     * If you install Custom tasks from Project Settings first and then create a business process. WIDs are not created in the project at all, hence Custom tasks that haven't been installed yet are missing in the Palette.

This is same behavior as on master. I don't think it should be fixed in this PR.

>     * In Case project, there are created two different common WIDs as it is also on master, but one of them still contains custom task definitions. Is there any reason why they are needed there, or should they rather be removed?

This issue present on the master as well, but I think I can unify Case project with normal project, remove duplicated file and move WIDs to separate files as it is done for the normal project in this PR. WDYT?
 
> Thank you!

Thank you @LuboTerifaj, great job! My idea is to move unrelated/not new issues to jira and discuss it there. But in this PR we can fix the last great catch only: 
>     * In Case project, there are created two different common WIDs as it is also on master, but one of them still contains custom task definitions. Is there any reason why they are needed there, or should they rather be removed?

WDYT?

**Comment by LuboTerifaj** [comment]
Hello @hasys,

Here is the clarification of my previous [comment](https://github.com/kiegroup/kie-wb-common/pull/3473#pullrequestreview-534540905):

1. I have put the comment there for discussing possible enhancements.
2. I have put the comment there for preventing from undesired changes.

3. On master, Decision and BusinessRule tasks contain spaces in their names and WebService has totally different name (WS) on canvas, so it is different on master. I am also not referring to the difference between the palette and canvas, but the difference between the nodes on canvas. The issue you have linked ([JBPM-7072](https://issues.redhat.com/browse/JBPM-7072)) is different.

4. "Huge thumbnails issue", there is nothing to resolve in this PR. However, the issue will be visible as soon as a user will open Documentation for any process with service tasks. The issue was not present before this PR (without additional Custom tasks installation). The severity of linked issue should be increased once this PR is merged. I have mentioned it to pay extra attention to it.

5. "Installing Custom task when WID is open", with this change it is much more probable that users will open WID to find out whether everything is set as it is supposed to and if they find out that it isn't, they can experience the issue. See my previous description for more details.
   - I know the issue is not directly related to Designer itself, however the UX of installing Custom tasks will be changed and it shouldn't.
   - If you think this is correct behaviour at the time of PR merging, I can report it in separate jira.

6. "removing/uninstalling the WIDs", with the changes, Custom tasks can become unavailable. A user will end in different state after uninstalling Custom tasks from Project settings in comparison with initial state, what should not happen at all from my point of view.

7. The issue is not present on master because Custom tasks definitions are in different file that are not removed with Custom tasks uninstallation. [KOGITO-3528](https://issues.redhat.com/browse/KOGITO-3528) applies only to Custom tasks that are not present in initial state. Therefore it should be resolved.

8. Yeah you are right, this one is present also on master. I will report the separate jira for that.

9. I am not sure what do you mean, but the solution should be to minimize amount of WIDs to only needed WIDs.

To **summarize** the points above, these **issues should be fixed** from my point of view: 3., 6., 7. and 9.:
 - WebService, Decision and BusinessRule tasks use different naming on the canvas. They are not consistent.
 - If a user installs all Custom tasks and then uninstalls them from project Settings, all WID files are removed from the project. As a result, Custom tasks are no longer available in the palette.
 - If you close the process with Custom tasks, delete/uninstall all work item definitions, reopen the process, download the process, import the process back and install WIDs back, the nodes are no more Custom tasks, they are just "None tasks".
    - Data is not present in bpmn source after downloading it.
    - This should be resolved to prevent users from data loss.    
- In Case project, there are created two different common WIDs as it is also on master, but one of them still contains custom task definitions. The amount of WIDs should be reduced only to those needed.

**Issues** that **needs to be reported** if not fixed in this PR: 5. and 8.:
- If you didn't close a WID and try to install related Custom task from project Settings, an error message is shown: "User has updated the following resource default://master@MySpace/project/global/WID_NAME.wid."
- If you install Custom tasks from Project Settings first and then create a business process. WIDs are not created in the project at all, hence Custom tasks that haven't been installed yet are missing in the Palette.

Thank you!

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
Hi @romartin, @LuboTerifaj,

I moved all WIDs back to single file as discussed. I updated link to the WAR file as well so PR is ready for re review. Thank you!

Some screenshots:
image
image
image

**Comment by romartin** [comment]
great, thanks a lot  @hasys !!! Anyway let you know that you did a great job, so rather than finally moving back to a single wid file, thanks for your commitment!!
CC @LuboTerifaj

**Review by romartin — APPROVED** [review]

**Comment by hasys** [comment]
Hi @mareknovotny, just FYI looks like Full Compile Build is not stable (see stack trace with an error). I will try to re-trigger the build in case it is a one time random issue. Thank you!

<details>
  <summary>Stack trace</summary>
  <pre>
Adding one-line test results to commit status...
Setting status of 8a9c7fbeffb61a96ecb0e4cc0edf876ae9b2eceb to FAILURE with url https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/compile/job/kie-wb-common-master.compile/41/ and message: 'Build finished. No test results found.'
Using context: Linux - Compile Downstream Build
groovy.lang.MissingPropertyException: No such property: owner for class: java.util.AbstractMap$SimpleImmutableEntry
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.getProperty(DefaultInvoker.java:39)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at githubscm.getForkedProjectName(githubscm.groovy:222)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.find(CpsDefaultGroovyMethods:4061)
	at githubscm.getForkedProjectName(githubscm.groovy:222)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at sun.reflect.GeneratedMethodAccessor474.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE</pre>
</details>

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
Full compile build has same issue as above. Should be fixed by https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/120

jenkins do cdb

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
Hi @romartin, @LuboTerifaj,

it's all green again! :)

**Comment by romartin** [comment]
CC @LuboTerifaj

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @hasys ,

The issues I have found:

- If you install and then uninstall Custom tasks, after closing and opening the process back, all Custom task thumbnails (except Log and Milestone) are the same in palette as well as on canvas. 

- The order of Custom tasks in palette is different with every process opening.
  
Default Rest Custom task has additional `Content` parameter in Input Data Assignments in comparison with installed Rest Custom task. Do you know why there is this difference?
 
 The issue that needs to be reported:
 - If you install the Custom tasks before creating a process, only installed Custom tasks are present in palette. All predefined default Custom tasks, not previously installed in the project settings are missing.
   - It is present also on master.
 - The issues from my previous comment: "_needs to be reported_" section.
 - WebService, Decision and BusinessRule tasks use different naming on the canvas. They are not consistent.
   - It hasn't been fixed since the previous comment.

Thank you!

**Review by LuboTerifaj — APPROVED** [review]
Hello @hasys ,

since the the found issues are not as significant as the one currently being fixed, I have reported them in separate jiras:
- [JBPM-9494](https://issues.redhat.com/browse/JBPM-9494) _Custom task thumbnails are the same after updating WIDs_
- [JBPM-9495](https://issues.redhat.com/browse/JBPM-9495) _The order of Custom tasks in palette is different with every process opening_

Found issues that are present also on master have been reported here:

- [JBPM-9496](https://issues.redhat.com/browse/JBPM-9496) _Custom tasks installation removes default Custom tasks from palette_
- [JBPM-9497](https://issues.redhat.com/browse/JBPM-9497) _Custom tasks use various naming on canvas_
- [JBPM-9498](https://issues.redhat.com/browse/JBPM-9498) _Custom task uninstalling shows an error message in case its WID is open_

Thank you!

**Comment by hasys** [comment]
Great, thank you @LuboTerifaj!

Hi @romartin, pr is ready for merge, thank you!

**Pull request merged**
