### PR TITLE
KOGITO-937: [DMN Designer] Decision Navigator dock position per channel

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/KOGITO-937

**_How to test (for speed and simplicity)_**

1. `mvn clean install -DskipTests -Dgwt.compiler.skip=true` the `kie-wb-common-dmn` module.
2. `mvn clean install` the `kie-wb-common-dmn-webapp-kogito-runtime` module.
3. Fetch the latest `kogito-tooling` [repository](https://github.com/kiegroup/kogito-tooling.git).
4. Update the version of DMN used [in](https://github.com/kiegroup/kogito-tooling/blob/master/packages/kie-bc-editors-unpacked/pom.xml#L40) `packages/kie-bc-editors-unpacked/pom.xml`
5. `cd kogito-tooling`
6. `yarn run init`
7. `yarn run build:prod`
8. Follow the [README](https://github.com/kiegroup/kogito-tooling/blob/master/README.md) to test in VSCode and GitHub (Decision Navigator should be on the RIGHT).
9. Unzip `kie-wb-common-dmn-webapp-kogito-runtime`
10. Double click `index.html` (Decision Navigator should be on the LEFT).
11. Running `drools-wb-webapp` (or Business Central) Decision Navigator should be on the LEFT.

### CODE REVIEW

**Comment by jomarko** [comment]
Simplicity in 11 steps? :D

**Comment by jomarko** [comment]
I realized this will break my tests https://github.com/kiegroup/kie-wb-common/pull/3067, once we merge one of PRs, we need to rerun tests before merging the second one.

**Comment by manstis** [comment]
@jomarko Why will it break the tests in #3067?

The Decision Navigator elements and ids are the same so won't the selectors still match?

**Comment by jomarko** [comment]
The icon for expanding changed

**Comment by manstis** [comment]
@jomarko FYI this PR has been merged so #3067 will need updating.

**Pull request merged**
