### PR TITLE
JBPM-5818 - Stunner - Add Intermediate Timer Event

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by jlindop** [comment]
@tsurdilo I was expecting this to be a Boundary event, but maybe I've got that wrong.
Also should the icon on the palette and the node be the clock from https://github.com/romartin/stunner-sandbox/blob/master/bpmn-icons/Brian/feb2017/Events/Event%20Subtypes/clock-o.svg

**Comment by tsurdilo** [comment]
@jlindop during marshalling intermediate events that are docked are converted to boundary events.
About the svg - my assumption was that we would revise and update the svg of all events, as i think none of the available ones use the correct svg.

**Comment by tsurdilo** [comment]
@hasys updated - thanks.

**Comment by tsurdilo** [comment]
@hasys Sorry I don't follow. I can create a timer event -> task -> timer event through the menu. Also can Start -> Task -> intermediate timer.

**Comment by tsurdilo** [comment]
@hasys found the connection rules for sequence flows as we discussed - amended. let me know if there is anything else. thanks.

**Comment by hasys** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
jenkins fail not related to this module.

**Comment by tsurdilo** [comment]
jenkins please retest this

**Comment by tsurdilo** [comment]
can this be merged? its been approved

**Pull request merged**
