### PR TITLE
Stunner - (Un)Marshaller tests for End Events

### PR DESCRIPTION
**Pull request by LuboTerifaj**

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
Note, that new marshaller tests are commented out because they are failing. Reported Jira about it: https://issues.jboss.org/browse/JBPM-7312

**Comment by LuboTerifaj** [comment]
Hi @romartin, @evacchi, @hasys 
Can you please have a look?
Thank you!

**Comment by evacchi** [comment]
Hi @LuboTerifaj code looks fine as usual, I'll folow up with a fix as soon as this gets merged!

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins please retest this

**Pull request merged**
