### PR TITLE
[AF-1600] 7.11.x  Fix MavenRestClientTest on jenkins

### PR DESCRIPTION
**Pull request by desmax74**
Fix the load of the Pom in the Arquillian Test when it runs on Jenkins @porcelli @jhrcek @domhanak @mbiarnes

### CODE REVIEW

**Comment by domhanak** [comment]
@desmax74 Hi! This should probably go to master branch only

**Comment by desmax74** [comment]
@domhanak doesn't fail on 7.11.x ?

**Comment by domhanak** [comment]
@desmax74 Yes but the issue is not a blocker and 7.11.x is in blocker phase only :)

**Comment by desmax74** [comment]
@domhanak ok I'll close this PR

**Comment by domhanak** [comment]
@desmax74 this is probably a blocker right now feel free to reopen

**Pull request closed without merging**
