### PR TITLE
JBPM-9242 : Stunner - Not all illegal characters are removed from Data Object name

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin can you review this PR?

**Thank you for submitting this pull request**

**JIRA**: [JBPM-9242](https://issues.redhat.com/browse/JBPM-9242)

**Referenced Pull Requests**:
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://donwnload.here/something)

**VS Code**: [plugin](https://donwnload.here/something)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by inodeman** [comment]
Jenkins retest this

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by hasys** [comment]
Hi @inodeman, looks good to me thank you!

Just a question: if we need it only on Client side, did you consider [com.google.gwt.http.client.URL](http://www.gwtproject.org/javadoc/latest/com/google/gwt/http/client/URL.html)? We have another StringUtils which is not supposed to work on server side and only for GWT/client side related features. See [StringUtils](https://github.com/kiegroup/kie-wb-common/blob/5d6e16565ffaa25869f9e103b3308efb95257749/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/StringUtils.java)

**Comment by inodeman** [comment]
> Hi @inodeman, looks good to me thank you!
> 
> Just a question: if we need it only on Client side, did you consider [com.google.gwt.http.client.URL](http://www.gwtproject.org/javadoc/latest/com/google/gwt/http/client/URL.html)? We have another StringUtils which is not supposed to work on server side and only for GWT/client side related features. See [StringUtils](https://github.com/kiegroup/kie-wb-common/blob/5d6e16565ffaa25869f9e103b3308efb95257749/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/StringUtils.java)

Hi @hasys looked at your comment, did it this way since I was already calling that method for illegal chars. Let me know if ok

**Comment by inodeman** [comment]
Hi @LuboTerifaj @hasys artifacts can be found here. https://drive.google.com/drive/folders/1UmNHTcZ-rpgYcDB2rLwubB3ARhCMB_Zv?usp=sharing

**Review by LuboTerifaj — COMMENTED** [review]
Hello @inodeman ,

I have found two issues:

- The warning message in Business central doesn't contain information about characters that are going to be removed. The message contains only this String: `([space], #, :, [quotes])`.
  - I would either specify what characters will be removed or I would remove this part of the message totally to avoid confusion. 
- VScode doesn't show warning message at all.

Is it possible to fix any of these issues in this pull request?

Thank you!

**Comment by inodeman** [comment]
Jenkins retest this

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by inodeman** [comment]
Hi @LuboTerifaj please find new artifacts here. https://drive.google.com/drive/folders/1im-f0Fk-PO3XiB-Dr_A9GqX8cHVgQenS?usp=sharing I fixed the messaging issue, now only a message about wong name will appear mentioning that any illegal chars will be replaced by "-". The notifications on Kogito I remember was not available, I talked to @romartin and I am researching if I can introduce, but right now to the best of my knowledge there are no notifications on Kogito still. I am researching a PR that seems to have introduced them a few days ago, not sure if we should aim for notifications on this ticket or open up another one later.

**Comment by inodeman** [comment]
Hi @LuboTerifaj let me know about latest artifacts so @romartin can merge if all ok

**Comment by romartin** [comment]
@hasys @LuboTerifaj please remember this review. thx

**Review by hasys — APPROVED** [review]
Hi @inodeman,

I tested Business Central and Visual Code plugin, looks and works good. Thank you!

**Comment by romartin** [comment]
thanks @hasys ! just missing your final words @LuboTerifaj ... :)
thanks guys

**Comment by romartin** [comment]
@LuboTerifaj please don't forget to look at this. thx!

**Comment by LuboTerifaj** [comment]
Hello @inodeman , I cannot open any process in VSCode extension linked in your [comment](https://github.com/kiegroup/kie-wb-common/pull/3555#issuecomment-796955690) above. Can you please have a look at it and let me know once it is ready to review? Thank you!

**Review by LuboTerifaj — APPROVED** [review]
Hello @inodeman ,

I had some local issue with VSCode. I double checked it and it works now for me as mentioned on gchat.

I didn't find any other issues on 7.52.0.SNAPSHOT and in VSCode.

I have reported the one present in VSCode here:
[KOGITO-4850](https://issues.redhat.com/browse/KOGITO-4850) _Warning message is missing when illegal characters are removed from DO_

If there are no any further changes, once the builds are green, it will be ready to merge. However, please ensure the expected behaviour described in jira is the same on 7.53.0.SNAPSHOT in comparison with 7.52.0.SNAPSHOT.

cc @hasys , @romartin 

Thank you!

**Comment by inodeman** [comment]
Jenkins retest this

**Comment by inodeman** [comment]
Jenkins retest this

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by inodeman** [comment]
Hi @LuboTerifaj please find new artifacts here. https://drive.google.com/drive/folders/1UmNHTcZ-rpgYcDB2rLwubB3ARhCMB_Zv?usp=sharing I tested them again as as far as I can tell they work as expected. Let me know, thanks

**Comment by hasys** [comment]
Full Downstream Build failed due to unrelated selenium tests from another project:
<details>
  <summary>org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest</summary>
  <pre>Error Message

Drone creation request timed out after 60 seconds. Make sure that browser or remote server in case of remotely executed driver is running and communication with Drone haven't failed.

Stacktrace

org.jboss.arquillian.drone.impl.DroneTimeoutException: Drone creation request timed out after 60 seconds. Make sure that browser or remote server in case of remotely executed driver is running and communication with Drone haven't failed.
Caused by: java.util.concurrent.TimeoutException

Standard Output

Drone: downloading geckodriver-v0.26.0-linux64.tar.gz from https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz to /home/jenkins/.arquillian/drone/firefox/0.26.0/geckodriver-v0.26.0-linux64.tar.gz 
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Standard Error

Apr 01, 2021 5:57:46 PM org.jboss.arquillian.drone.webdriver.factory.remote.reusable.ReusedSessionPermanentFileStorage readStore
INFO: Reused session store is not available at /home/jenkins/.drone-webdriver-session-store, a new one will be created.
Apr 01, 2021 5:57:46 PM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
Apr 01, 2021 5:57:46 PM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
Apr 01, 2021 5:57:47 PM org.arquillian.spacelift.Spacelift$SpaceliftInstance <init>
INFO: Initialized Spacelift from defaults, workspace: /home/jenkins/workspace/KIE/master/fdb/kie-wb-common-master.fdb/bc/kiegroup_kie_wb_distributions/business-central-tests/business-central-tests-gui, cache: /home/jenkins/.spacelift/cache
Apr 01, 2021 5:58:46 PM org.jboss.arquillian.core.impl.ObserverImpl resolveArguments
WARNING: Argument 1 for ReusableRemoteWebDriverExtension.destroyLastRemoteWebDriver is null. It won't be invoked.
</pre>
</details>

**Pull request merged**
