### PR TITLE
Stunner - Start Events (Un)Marshaller tests

### PR DESCRIPTION
**Pull request by hasys**
Hi @evacchi, @jiripetrlik, @LuboTerifaj, @domhanak, @alepintus 

there are (Un)marshaller tests for Start events (45 in total). It should cover all Start events:
* Every Start Events type with all **empty** properties on **Top Level Process**
* Every Start Events type with all **filled** properties on **Top Level Process**
* Every Start Events type with all **empty** properties on **Subprocess level**
* Every Start Events type with all **filled** properties on **Subprocess level**
* Every Start Events type are tested with both New and Old (Un)Marshallers
* Migration tests for Every Start Events (with all listed above variations) also provided.

@jiripetrlik, @LuboTerifaj, @domhanak  Also there are some refactorizations for (Un)Marshaller tests, I hope we can write all brand new tests for all nodes with suggested structure during Product verification. Because:
* we will be sure that everything is covered
* it is easy with this new structure
* it is much clear what is already tested and what is not.
* it will be very easy to migrate from one (un)marshaller to another.

 So, let me know if you have any questions/suggestions how to improve/simplify it.

@evacchi @jiripetrlik 
* There are some failing tests with New (Un)Marshalling and 2 Migration tests. We should revise them before merge (or disable  new marshaller and migration tests for this PR).
* Provided tests are testing with two preconditions:
  * If it can be (un)marshalled inside of one subprocess it will be marshalled for any subprocess
  * Multiple levels of nesting subprocesses have same parsing mechanism as for single level of subprocess

Also reported one new issue about missing properties: [JBPM-7038](https://issues.jboss.org/browse/JBPM-7038)

CC @romartin @triceo It took some time to make this refactorization, but from now it will be much easier to add new nodes to check that everything is fine with old/new (Un)Marshaller and during migration from old to new (Un)Marshaller as well.

### CODE REVIEW

**Comment by evacchi** [comment]
hey @hasys ! very good job here!
How can we proceed for bug fixes? Shall I open a PR to your fork?

So, as far as tests are concerned:
- NPEs. I think I can fix those, that's pretty easy

these are cases where the marshaller does not save some field, so re-unmarshalling won't work:
- IndexOutOfBoundsException in DefinitionResolver. Something possibly strange going on here. Apparently when unmarshall from our own marshalling routine the ID for the BPMNDiagram elementRef is not set. However, even if I try and fix that, the list of Diagrams is still empty :(
- IndexOutOfBoundsException in AssingmentsInfos.java:
  so apparently there are DataOutputs whose sourceRef is an empty list...

**Comment by hasys** [comment]
Hi @evacchi,

thank you for the feedback. I see two ways:
* Ignore new (un)marshaller tests and migration tests in this PR and merge. And uncomment them in future PR with (un)marshaller fixes.
* Fix issues in separate PRs and merge this PR when your fixes will be done.

Up to you, I am OK with both solutions.

**Comment by evacchi** [comment]
Hi @hasys,
let's try with option (1), let's get this merged ASAP, then I'll do another PR with fixes. BTW I'm already on it

**Comment by evacchi** [comment]
@hasys I fixed the bugs faster than I thought, opened a PR to your branch. You decide what it's better :-)

**Comment by hasys** [comment]
Hi @evacchi,

thank you for your notes, applied.

Also, I disable new (un)marshaller and migration tests for now, you can enable it in PR with your fixes. Thank you!

@romartin This PR is ready to go if you OK with it.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin, @evacchi,

there are some network issues not related to this PR.

Jenkins execute full downstream build

**Comment by hasys** [comment]
Build failed with:
```13:10:01 Caused by: java.io.IOException: Backing channel 'ci-rhos-rhel7-xlarge-1883' is disconnected.```

It is not related to this PR, let's try again.

Jenkins execute full downstream build

**Pull request merged**
