### PR TITLE
Update LibraryConstants.properties English wording

### PR DESCRIPTION
**Pull request by danial-k**

### CODE REVIEW

**Comment by kie-ci8** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by manstis** [comment]
ok to test

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by danial-k** [comment]
Hi @paulovmr I don't seem to be able to access the build output at rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com presumably because of permissions, any tips on how I could investigate?

**Comment by mareknovotny** [comment]
@danial-k  sorry but our CI is behind VPN
the build failed due your PR branch name, you should read our contribution guideline - https://github.com/kiegroup/droolsjbpm-build-bootstrap/#working-with-git 
the good practice is to create a topic branch and do not push from master branch directly ;)
If you can resend this PR from a topic branch our CI will not fail due that.

**Comment by domhanak** [comment]
@paulovmr As I see you approved, can this be merged?

**Comment by paulovmr** [comment]
Closing this because of CI failure due to improper source branch.

**Pull request closed without merging**
