### PR TITLE
[7.7.x] JBPM-7162: Stunner - Make canvas size configurable (via workbench preferences) (#1714)

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
@romartin @hasys Hello, this is the peer PR for the already merged into master https://github.com/kiegroup/kie-wb-common/pull/1714.
Would you mind review?

Thanks.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @hasys , my PR that fixes the memory leaks depends on this, so I need this merged into 7.7.x in order to create my PR.... not sure if you'll have a chance to approve this during this weekend, so I can merge it and then provide my PR for the leaks.... 
Take into account this is just a cherry-pick, we just tested this on mater, so there should be not much risk...
Thanks in advance!

**Comment by romartin** [comment]
Just tested the generated WAR and it works fine. Merging.

**Comment by romartin** [comment]
@wmedvede I'll merge as I need it urgently, but you should create an `RHPAM` ticket for this, not a `JBPM` one. Please create it and resolve it, but this way this task will appear in the release notes for the 7.0 GA.

**Pull request merged**
