### PR TITLE
RHPAM-2874 - Updating Process ID to unsupported value breaks the process

### PR DESCRIPTION
**Pull request by hasys**
See [detailed comment](https://issues.redhat.com/browse/RHPAM-2874?focusedCommentId=14097641&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14097641) with all explanation.

Just one more note here: I fixed some incorrect PowerMock imports it shouldn't have any affect on test, just clean up, and definitely have no affect on the product code so I guess we should be fine with it.

I already tested Business Central build locally, so I believe this PR is ready for review as soon as builds are ready. Thank you!

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
test full downstream production build

**Comment by Ginxo** [comment]
Jenkins retest please

**Comment by Ginxo** [comment]
test full downstream production build

**Comment by Ginxo** [comment]
relaunched due to jenkins forced restarting

**Comment by Ginxo** [comment]
jenkins execute full downstream production build

**Comment by hasys** [comment]
Looks like I need to rebase this PR. Going to do it.

<details>
  <summary>Error log</summary>
  <pre>[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15:16 min
[INFO] Finished at: 2020-05-25T06:14:07-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project drools-wb-dtable-xls-editor-client: Compilation failure: Compilation failure: 
[ERROR] /home/jenkins/workspace/KIE/master/upstream-downstream/kie-wb-common.downstream.production/kiegroup_drools-wb/drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-client/src/main/java/org/drools/workbench/screens/dtablexls/client/handlers/NewDecisionTableXLSHandler.java:[117,24] cannot find symbol
[ERROR]   symbol:   method getFilenameSelectedToUpload()
[ERROR]   location: variable uploadWidget of type org.kie.workbench.common.widgets.client.widget.AttachmentFileWidget
[ERROR] /home/jenkins/workspace/KIE/master/upstream-downstream/kie-wb-common.downstream.production/kiegroup_drools-wb/drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-client/src/main/java/org/drools/workbench/screens/dtablexls/client/handlers/NewDecisionTableXLSHandler.java:[117,78] cannot find symbol
[ERROR]   symbol:   method getFilenameSelectedToUpload()
[ERROR]   location: variable uploadWidget of type org.kie.workbench.common.widgets.client.widget.AttachmentFileWidget
[ERROR] /home/jenkins/workspace/KIE/master/upstream-downstream/kie-wb-common.downstream.production/kiegroup_drools-wb/drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-client/src/main/java/org/drools/workbench/screens/dtablexls/client/handlers/NewDecisionTableXLSHandler.java:[131,29] cannot find symbol
[ERROR]   symbol:   method getFilenameSelectedToUpload()
[ERROR]   location: variable uploadWidget of type org.kie.workbench.common.widgets.client.widget.AttachmentFileWidget
[ERROR] -> [Help 1]</pre>
</details>

**Comment by hasys** [comment]
jenkins execute full downstream production build

**Comment by hasys** [comment]
Build fixed by https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1331

**Comment by hasys** [comment]
jenkins execute full downstream production build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
jenkins execute full downstream production build

**Comment by hasys** [comment]
Hi @LuboTerifaj,

as discussed this PR is ready for review. War can be downloaded [here](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/upstream-downstream/job/kie-wb-common.downstream/181/artifact/kiegroup_kie-wb-distributions/business-central-parent/business-central-distribution-wars/business-central/target/) and tests passed in repo build.

Sonar Cloud complaining on constant which were there before my changes, I didn't introduce it by my PR.

Thank you!

**Comment by hasys** [comment]
Hi @LuboTerifaj, full downstream build was done without my changes, since it is already 7.39, but my changes done on 7.38. Rebased and starting builds again. Sorry for inconvenience.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Full downstream build is green, but already removed because new build stores only last 10 and there where much more runs from Friday.

Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
I tried steps to reproduce, they were fixed but going beyond and trying do BUILD the project with process that has ID `testProject.processName~!@#$%^&*()+`-={}[]:"|;'\<>?,./_` the build failed.

I imported Mortgage_Process example
Changed ID to `testProject.processName~!@#$%^&*()+`-={}[]:"|;'\<>?,./_`
Saved and reopened.
Tried ot build but the build failed"
```
09:58:09,928 ERROR [org.drools.core.xml.ExtensibleXmlParser] (default task-10) Node Info: id:testProject.processName~!@#$%^&*()+`-={}[]:"|;'\<>?,./_ name:MortgageApprovalProcess 
Parser message: (null: 75, 254): cvc-datatype-valid.1.2.1: 'testProject.processName~!@#$%^&*()+`-={}[]:"|;'\<>?,./_' is not a valid value for 'NCName'.
09:58:09,928 ERROR [org.drools.core.xml.ExtensibleXmlParser] (default task-10) Node Info: id:testProject.processName~!@#$%^&*()+`-={}[]:"|;'\<>?,./_ name:MortgageApprovalProcess 
Parser message: (null: 75, 254): cvc-attribute.3: The value 'testProject.processName~!@#$%^&*()+`-={}[]:"|;'\<>?,./_' of attribute 'id' on element 'bpmn2:process' is not valid with respect to its type, 'ID'.
09:58:09,933 ERROR [org.drools.core.xml.ExtensibleXmlParser] (default task-10) Node Info: id:_w2U-QaSmEeqFCojObw0iDQ name: 
Parser message: (null: 419, 137): cvc-datatype-valid.1.2.1: 'testProject.processName~!@#$%^&*()+`-={}[]:"|;'\<>?,./_' is not a valid value for 'QName'.
09:58:09,934 ERROR [org.drools.core.xml.ExtensibleXmlParser] (default task-10) Node Info: id:_w2U-QaSmEeqFCojObw0iDQ name: 
Parser message: (null: 419, 137): cvc-attribute.3: The value 'testProject.processName~!@#$%^&*()+`-={}[]:"|;'\<>?,./_' of attribute 'bpmnElement' on element 'bpmndi:BPMNPlane' is not valid with respect to its type, 'QName'.
09:58:09,954 ERROR [org.drools.compiler.kie.builder.impl.KieProject] (default task-10) Unable to build KieBaseModel:defaultKieBase
[4,69]: [ERR 101] Line 4:69 no viable alternative at input ''
[4,65]: [ERR 102] Line 4:65 mismatched input '|' in rule "RuleFlow-Split-testProject.processName~!@#$%^&*()+`-={}[]:"
[0,0]: Unexpected error: null
[0,0]: Parser returned a null Package
```

**Comment by hasys** [comment]
Hi @domhanak, thank you for review!

Yes, it is expected behavior. Main point of this PR is do not let user to break the process till it is not possible to open it.

So before this PR if you set up incorrect ID it wasn't possible to reopen process (XML editor will be opened instead), now you can reopen it and change the ID back to the correct value.

We discussed the ability to remove all non-ID symbols, but not all of them can cause broken process (some of them only error messages in the console) and potentially users already have it in their process ID and using it in the production, so we decided too let the user to put "incorrect" symbols for backward compatibility.

Fix build is not part of this PR and designer project in general.

**Comment by domhanak** [comment]
Ah, okay. If that's the case - it works. Apologies the Expected results in RHPAM mention that you should be able to build the project.

**Comment by hasys** [comment]
Thank you @domhanak,

the PR is ready to go, @romartin thank you!

**Pull request merged**
