### PR TITLE
JBPM-9627 Stunner - Update Message events marshaller tests for struct…

### PR DESCRIPTION
**Pull request by LuboTerifaj**
…ureRef element

**JIRA**: [JBPM-9627](https://issues.redhat.com/browse/JBPM-9627)

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
Hello @Josephblt , @romartin , can you please have a look at this PR? There is no need to test anything since I've just updated the tests. Thank you!

**Comment by LuboTerifaj** [comment]
jenkins retest this

**Comment by LuboTerifaj** [comment]
jenkins do fdb

**Review by Josephblt — APPROVED** [review]

**Comment by LuboTerifaj** [comment]
Jenkins retest this

**Comment by LuboTerifaj** [comment]
Jenkins execute fdb

**Review by romartin — APPROVED** [review]
LGTM, thanks @LuboTerifaj !

**Pull request merged**
