### PR TITLE
KOGITO-6323: Render DMN association waypoints

### PR DESCRIPTION
**Pull request by jomarko**
For more details see:
- https://issues.redhat.com/browse/KOGITO-6323

**Referenced Pull Requests**:
* Backport of https://github.com/kiegroup/kogito-tooling/pull/749

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Jenkins do fdb

**Review by yesamer — APPROVED** [review]
@jomarko Thank you!

**Comment by jomarko** [comment]
Closing this PR. In kie-wb-common we miss:
- https://github.com/kiegroup/kogito-editors-java/commit/c91e9343de8069a3c09504a145c5150734f636f8
- https://issues.redhat.com/browse/KOGITO-5119

**Pull request closed without merging**
