### PR TITLE
KOGITO-4197: [DMN Designer] DMN 1.1 model can not be fixed to proper DMN 1.2

### PR DESCRIPTION
**Pull request by karreiro**
**JIRA**: [KOGITO-4197](https://issues.redhat.com/browse/KOGITO-4197) - [DMN Designer] DMN 1.1 model can not be fixed to proper DMN 1.2

**VS Code**: [plugin](https://www.dropbox.com/s/849xubznssst8zx/plugin-KOGITO-4197.vsix?dl=0)

The fix lives into https://github.com/kiegroup/kie-wb-common/pull/3543/commits/f9fcb0ed26a5dd00639d741587d5df54431d851e and https://github.com/kiegroup/kie-wb-common/pull/3543/commits/44f341fd059f3f254943f6ea26cee456de987f44 (the rest of this PR introduce updates in the test suite assets).

Screen Shot 2021-01-18 at 20 00 11

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins retest this.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by karreiro** [comment]
Jenkins retest this.

**Review by jomarko — APPROVED** [review]
Thank you @karreiro

**Review by danielzhe — APPROVED** [review]

**Pull request merged**
