### PR TITLE
BXMSPROD-685: fixing Mocks after Weld 3.1.5.SP1 upgrade

### PR DESCRIPTION
**Pull request by mareknovotny**
**Thank you for submitting this pull request**

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-685

**Referenced Pull Requests**:
* parent PR kiegroup/droolsjbpm-build-bootstrap#1320

<pre>
To retest a PR or trigger a specific build please add a comment:

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</pre>

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
@tiagobento @adrielparedes so everything looks fine except these 80 failures here (proved by FDB from parent PR)
Now the question is why is happening the NPE in uberfire-cdi-backend which causes the test environments here are not initiated properly. The problem is that [org.uberfire.backend.server.cdi.workspace.WorkspaceScopedExtension](https://github.com/kiegroup/appformer/blob/master/uberfire-backend/uberfire-backend-cdi/src/main/java/org/uberfire/backend/server/cdi/workspace/WorkspaceScopedExtension.java#L40)

```
Suppressed: java.lang.NullPointerException
		at org.jboss.weld.metadata.TypeStore.add(TypeStore.java:50)
		at org.jboss.weld.bootstrap.events.BeforeBeanDiscoveryImpl.addScope(BeforeBeanDiscoveryImpl.java:90)
		at org.uberfire.backend.server.cdi.workspace.WorkspaceScopedExtension.beforeBeanDiscovery(WorkspaceScopedExtension.java:40)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
		at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
		at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
		at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
		at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
		at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
		at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
		at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
		at org.jboss.weld.util.Observers.notify(Observers.java:166)
		at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
		at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
		at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
		at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
		at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
		at org.jboss.weld.bootstrap.events.AbstractDefinitionContainerEvent.fire(AbstractDefinitionContainerEvent.java:44)
		... 23 more
```

**Comment by tiagobento** [comment]
\@mareknovotny I can't find the original logs of these failures. Can you please re-trigger the build so I have access to the full logs?

@mareknovotny From my understanding and looking at the source code, the only NPE that can be happening at `org.jboss.weld.metadata.TypeStore.add(TypeStore.java:50)` is from `annotation.annotationType()` being null. This however, looks impossible, since `annotation` is an instance of `NormalScopeLiteral`, whose implementation of `annotationType()` comes from `AnnotationLiteral`, on `cdi-api-2.0.SP1.jar`. This implementation never allows its return to be null, though. I'll need to see the full logs to search for more information.

See the code below:

`BeforeBeanDiscoveryImpl `
image

`TypeStore`
image

`AnnotationLiteral`
image

**Comment by tiagobento** [comment]
@mareknovotny I just found out that the new AnnotationLiteral implementation added to Errai is clashing with the one from `cdi-api`.

**Comment by tiagobento** [comment]
@mareknovotny Just tested it and I can confirm that excluding `errai-javax-enterprise` form the classpath during these tests executions make the issue go away. Be aware that since we now have conflicting implementation of `AnnotationLiteral` (one on `cdi-api` and another on `errai-javax-enterprise`), it might be a good idea to double-check whether `errai-javax-enterprise` is making its way to our WARs or not, since the same issue might happen during runtime if it is.

**Comment by mareknovotny** [comment]
ok, good finding. the question is now, do we need that Errai dependency at all if it works with exclusion? Originally @adrielparedes tried to customize the Errai javax-enterprise module to be up to date with the new Weld SPI/Implementation and javax EE specs. here is the commit https://github.com/errai/errai/pull/388/commits/e6053e0d8bb8dac1d1069c05dbe1e206543a4e79 for the context

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by tiagobento** [comment]
@mareknovotny Well, my understanding of this module is that it's there to "mock" some of Java EE during GWT compilation, since the classes it contains are not emulated by GWT standard libraries. While it is _necessary_ to have it on the "classpath" for GWT compilation, it's important to **not** have this module included in our WARs, since it may cause undesirable clashes like this one that was happening in some tests. So to summarise, this module should be included on the frontend, but not on the backend.

**Comment by mareknovotny** [comment]
> @mareknovotny Well, my understanding of this module is that it's there to "mock" some of Java EE during GWT compilation, since the classes it contains are not emulated by GWT standard libraries. While it is _necessary_ to have it on the "classpath" for GWT compilation, it's important to **not** have this module included in our WARs, since it may cause undesirable clashes like this one that was happening in some tests. So to summarise, this module should be included on the frontend, but not on the backend.
> 
OK, now i got it, thanks for explanation @tiagobento

**Comment by mareknovotny** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
Jenkins retest this

**Review by yesamer — APPROVED** [review]

**Pull request merged**
