### PR TITLE
JBPM-8961 : Stunner designer strips square brackets characters - HT Notification

### PR DESCRIPTION
**Pull request by handreyrc**
@romartin, @inodeman Could you please review this PR?

### CODE REVIEW

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
> Hey @handreyrc
> 
> Good job, thanks! Code looks good to me, although artifacts are not still generated on Jenkins so I cannot test the runtime.
> 
> Anyway, can you please check if this bug also applies to the "kogito" webapp? Please ask me or @inodeman how to run it, if you don't know yet. In case the bug also applies for the "kogito" webapp too, it means the bug is also present on the "client side" marshallers, so it would be good to do the fix too on that implementation (those are present in the [kie-wb-common-stunner-bpmn-marshalling](https://github.com/kiegroup/kie-wb-common/tree/master/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling) module).
> 
> Can you pleasa also check?
> 
> Thanks and good job again!

Hey @romartin and @inodeman, I've just mirrored the fix to kogito. Please could you review it?

**Comment by romartin** [comment]
Jenkins retest this

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@LuboTerifaj just did a mistake, sorry :( This PR was still not approved by you... sorry, got confused with tabs :(

Can you please test it anyway, in our master stream, for example in our CD/CI, and let us know somehting plz? If it's causing any issue, we'll report and start fixing it.

Sorry for the inconveniences agian.
Thx

**Pull request merged**
