### PR TITLE
KOGITO-4265: Verify decision service input data order in properties p…

### PR DESCRIPTION
**Pull request by jomarko**
…anel

For more details see: https://issues.redhat.com/browse/KOGITO-4265

**JIRA**: [KOGITO-4265](https://issues.redhat.com/browse/KOGITO-4265)

**Referenced Pull Requests**:
* #3549 

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by danielzhe** [comment]
@jomarko Let me know if you want to merge it. Any improvement to my PR is welcome! Thank you!

**Comment by jomarko** [comment]
@vpellegrino may I ask you for review too? As I touched you did some changes in the time of my absence last year.

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by vpellegrino** [comment]
> @vpellegrino may I ask you for review too? As I touched code you did some changes in the time of my absence last year.

sure, I am going to review it

**Review by vpellegrino — APPROVED** [review]
PR looks fine, thanks @jomarko

**Review by danielzhe — APPROVED** [review]
Thank you very much, @jomarko

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
