### PR TITLE
[7.52.x] JBPM-9695 - DMN - Data Types shortcuts do not work anymore

### PR DESCRIPTION
**Pull request by hasys**
**JIRA**: [RHDM-1650](https://issues.redhat.com/browse/RHDM-1650)

**Business Central**: [WAR file](https://drive.google.com/file/d/1a-J-Eh47huKeP0MWpe8NQuJi5NyzAlkc/view?usp=sharing)

**VS Code**: [plugin](https://drive.google.com/file/d/1M57RvF9FrucO81GIBuxaa34x_AO6zSN0/view?usp=sharing)

Hi @jomarko, @karreiro, @romartin this is a cherry-pick of https://github.com/kiegroup/kie-wb-common/pull/3604.
VS Code plugin TBD, checking which branch should be used to build Kogito-tooling for 7.52.x. 

Thank you!

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
Hi @karreiro, @jomarko, @romartin VS Code plugin uploaded. Thank you!

**Review by karreiro — APPROVED** [review]
Thank you, @hasys! Great stuff 🚀

**Comment by hasys** [comment]
Hi @karreiro, @romartin, @jomarko, builds just failed without any error message.

@mareknovotny, @mbiarnes, are 7.52.x builds unstable? I will retrigger builds anyway, let's see the results.
There are link to builds logs if still available:
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/7.52.x/job/compile/job/kie-wb-common-7.52.x.compile/3/console
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/7.52.x/job/pullrequest/job/kie-wb-common-7.52.x.pr/5/console

**Comment by hasys** [comment]
jenkins do cdb

**Review by jomarko — APPROVED** [review]
Data types shortcuts works both Business Central and VS Code. Thank you @hasys

**Comment by hasys** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
There are in both ref. links this:
```
22:58:05  [INFO]  [kiegroup/optaplanner] Checking out project
22:58:05  [ERROR]  You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.
```
which implies we are overloading Github APIs after our outage. So need to wait and retrigger again if it is failing with the same error @karreiro @hasys

**Review by romartin — APPROVED** [review]

**Pull request merged**
