### PR TITLE
[7.7.x] RHPAM-765 (JBPM-7084): Stunner - you need to reopen process to see previous version of the process

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/JBPM-7084

This is the corollary of https://github.com/kiegroup/kie-wb-common/pull/1575 for 7.7.x.

(cherry picked from commit 1715a2df157da9df99cfe21c3a7efbbc0b8f6bf3)

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
wars generated, checking

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Pull request merged**
