### PR TITLE
KOGITO-404: [DMN Designer] Investigate files that cannot be opened

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/KOGITO-404

Unit tests to be covered by https://issues.jboss.org/browse/KOGITO-406

To test please try to open the `paymentDate.dmn` file attached to the [JIRA](https://issues.jboss.org/secure/attachment/12456352/paymentDate.dmn).

Unit tests to be covered by https://issues.jboss.org/browse/KOGITO-406

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko This PR is good to review.

**Comment by manstis** [comment]
@jomarko Please see the PR description.

Unit testing of the client side marshaller has it's own JIRA as it requires research. 

The JIRA this PR represents is linked to the marshalling JIRA.

**Comment by jomarko** [comment]
The issue above seems to be unrelated to this PR https://issues.jboss.org/browse/KOGITO-503 however it needs to be resolved before merging this PR.

**Comment by manstis** [comment]
@jomarko I tried `paymentDate.dmn` with `kie-wb-common-webapp-kogito-testing` and it opens OK. I also tried the file attached to https://issues.jboss.org/browse/KOGITO-503 and it opened OK too. I suspect there is an issue with the DMN editor integration. Is it possible to test these PRs with `kie-wb-common-webapp-kogito-testing` for now?

**Comment by jomarko** [comment]
@manstis lease share steps how.

**Comment by manstis** [comment]
@jomarko I'll send you an email.

**Pull request merged**
