### PR TITLE
JBPM-6325 New instance editor in radiogorup/listbox allows you to create invalid options. 7.3.x

### PR DESCRIPTION
**Pull request by alessioscalici**
**WARNING** to be merged after https://github.com/kiegroup/kie-wb-common/pull/1157
This is the same as https://github.com/kiegroup/kie-wb-common/pull/1161, pointing to **7.3.x** branch

@pefernan @jsoltes FYI

### CODE REVIEW

**Comment by pefernan** [comment]
@jsoltes it cannot be tested for now, this annotations are processed on compile time and generate some code for the fields properties forms. We might think on a way to test all of these.

**Comment by jsoltes** [comment]
@pefernan I see, in that case jenkins execute full downstream build

**Comment by pefernan** [comment]
@jsoltes is it ok to merge?

**Comment by pefernan** [comment]
Thank you @alessioscalici

**Pull request merged**
