### PR TITLE
[7.52.x] RHPAM-3588: Erase of WID 'nodes' types

### PR DESCRIPTION
**Pull request by handreyrc**
Hey @romartin, please could you ckeck this cherry-pick from master?

**JIRA**: [RHPAM-3588](https://issues.redhat.com/browse/RHPAM-3588)

**Business Central**: [WAR file](https://drive.google.com/file/d/1y7jdzuQGzKyufzpGy-kIYT935g5tM9Eo/view?usp=sharing)

**Referenced Pull Requests**:
* https://github.com/kiegroup/kie-wb-common/pull/3599

Thanks

### CODE REVIEW

**Comment by handreyrc** [comment]
jenkins do fdb

**Review by romartin — APPROVED** [review]
Thanks @handreyrc !

@domhanak this is the cherry-pick we'd been talking about, please some early review appreciated!

Thanks!

**Comment by handreyrc** [comment]
jenkins retest this

**Comment by handreyrc** [comment]
jenkins do fdb

**Comment by handreyrc** [comment]
jenkins retest this

**Comment by handreyrc** [comment]
jenkins retest this

**Comment by handreyrc** [comment]
jenkins do fdb

**Review by domhanak — APPROVED** [review]

**Pull request merged**
