### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by mareknovotny** [comment]
```
Test Result ("2 failures / +2")
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testLibraryPerspectiveWithHeader
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest
```

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins please retest this
jenkins execute full downstream build

**Comment by jomarko** [comment]
@pefernan agree definitely, and trying to get green build intensively.

**Comment by mareknovotny** [comment]
Compilation error in kie-wb-distributions repo? :(

**Comment by jomarko** [comment]
Some inappropriate merge somewhere?

**Comment by mareknovotny** [comment]
This added the not found classes kiegroup/appformer/pull/861 so probably a glitch with the partial merge at the time of launched build.

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@mareknovotny please merge when you have a moment.

**Pull request merged**
