### PR TITLE
Kogito-4978 : Stunner - Make new nodes editable automatically

### PR DESCRIPTION
**Pull request by inodeman**
**Thank you for submitting this pull request**

**JIRA**: [KOGITO-4978](https://issues.redhat.com/browse/KOGITO-4978)

**Referenced Pull Requests**:
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://donwnload.here/something)

**VS Code**: [plugin](https://donwnload.here/something)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by inodeman** [comment]
Jenkins do fdb

**Comment by romartin** [comment]
This must be TESTED in CHROME & FF

**Comment by inodeman** [comment]
Jenkins retest this

**Comment by inodeman** [comment]
Jenkins do fdb

**Comment by inodeman** [comment]
Hi @romartin tested in both Chrome and Firefox. Artifacts can be found here. https://drive.google.com/drive/folders/1zF8JxV0phIgRFJktqFwiUp3SjITc0oEy?usp=sharing

**Pull request closed without merging**
