### PR TITLE
[7.67.x] KOGITO-7067: [DMN Designer] DMN Editor: Slowness while opening large DMN file

### PR DESCRIPTION
**Pull request by danielzhe**
Cherry-pick of: https://github.com/kiegroup/kie-wb-common/pull/3734

### CODE REVIEW

**Review by jomarko — APPROVED** [review]

**Review by jomarko — APPROVED** [review]

**Comment by danielzhe** [comment]
@kiegroup/gatekeepers Merge, please. The JDK 8 is not green because of https://github.com/kiegroup/kie-wb-common/pull/3755

**Review by mariofusco — APPROVED** [review]

**Comment by fantonangeli** [comment]
Hi @danielzhe, I'm not sure I a good fit for a review on your Java PR.
I think it would be better to ask someone else.

**Review by jomarko — APPROVED** [review]

**Review by jomarko — COMMENTED** [review]
Now the java8 build seems to have different fail

**Review by yesamer — APPROVED** [review]

**Comment by danielzhe** [comment]
@jomarko GC overhead limit exceeded. I don't think this error is related.

**Review by jomarko — APPROVED** [review]

**Pull request merged**
