### PR TITLE
KOGITO-466 - Process with Reusable sub-process print errors to the server log

### PR DESCRIPTION
**Pull request by Josephblt**
https://issues.redhat.com/browse/KOGITO-466

This is just a follow up on this:
https://issues.redhat.com/browse/JBPM-8680

Same functionality, different marshaller.

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by Josephblt** [comment]
SonarCloude is failing due to code duplication. This is happening because we have duplication between old and Kogito marshallers. The modules containing the old ones are going to be dropped, so there is no need in making efforts to fix this.

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by Josephblt** [comment]
Hello @domhanak. Could you please review this thanks.

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Please @domhanak missing review. Thanks!

**Pull request merged**
