### PR TITLE
DROOLS-6739 : Inaccurate alert about duplicate rule name after copying rule

### PR DESCRIPTION
**Pull request by Rikkola**
**Thank you for submitting this pull request**

**JIRA**: [DROOLS-6739](https://issues.redhat.com/browse/DROOLS-6739)

**Business Central**: [WAR file](https://donwnload.here/something)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by barboras7** [comment]
jenkins run fdb

**Comment by barboras7** [comment]
Hi @Rikkola,

I watched the video attached to the original Jira, but I was not able to reproduce the issue with Guided Rule Template. However, I was able to reproduce it with some other assets. See the details below.

When I was testing a business central without your changes, I was able to reproduce the issue as follows:

- I could always reproduce the issue on  Guided Rule (always = in an empty project with just one guided rule, also on the Mortgage_Process sample project, on any of the guided rules provided)
- I could reproduce the issue on Guided Decision Table asset (in the Mortgage_Process sample project)

With the business central from this PR, this is what I found:

- the issue is fixed for both Guided Rules and Guided Decision Tables (both in empty project and in Mortgage_Process sample project), I tested both suffexes and prefixes and everything works fine

I encountered one issue in your fix, following are the steps to reproduce:

- In some space, import a sample project Mortgage_Process
- Filter out the "Decision" assets
- Open the guided rule named "RetractValidationErr"
- Click "Copy"
- For the copy name, enter "RetractValidationErr"
As a result, you are able to make a copy of the guided rule with the same name as the original guided rule. This should not be allowed. Should this be fixed as part of this PR or should I create a new Jira for this?

**Comment by barboras7** [comment]
Hi @Rikkola,
any update on this?

**Comment by Rikkola** [comment]
@barboras7 I had a long break. Now taking a look.

**Comment by barboras7** [comment]
@Rikkola no rush at all :slightly_smiling_face: I was just checking if you haven't overlooked the notification, take as much time as you need

**Comment by Rikkola** [comment]
@barboras7 I tested. I suspect the copy works since the file is copied to a different package. However this change should not introduce the bug so we should fix in a separate one.

**Comment by barboras7** [comment]
Were you able to reproduce the original issue for the guided rule template, please? I am able to reproduce the issue for guided rule (I tested against 7.12 CR) but it only happens to me with guided rule, not guided rule template. 
Screenshot from 2022-01-12 11-36-57

**Comment by Rikkola** [comment]
@barboras7 Actually nope, I had to use a guided rule too.

**Review by barboras7 — APPROVED** [review]

**Review by yesamer — APPROVED** [review]

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers Can I get a merge please.

**Pull request merged**
