### PR TITLE
RHDM-1144: [DMN Designer] List Java field is not converted to DMN collection

### PR DESCRIPTION
**Pull request by danielzhe**

### CODE REVIEW

**Comment by jomarko** [comment]
@danielzhe we have some minor issue in code probably:
```
23:49:29 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (validate) on project kie-wb-common-dmn-backend: You have 1 Checkstyle violation. -> [Help 1]
```

**Comment by danielzhe** [comment]
@jomarko Thank you and sorry about that. It's fixed now.

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by danielzhe** [comment]
@jomarko Thank you. I think it should be handled.

**Comment by jomarko** [comment]
@danielzhe ok, I created https://issues.redhat.com/browse/RHDM-1203

**Comment by danielzhe** [comment]
@jomarko Maybe I can handle this issue in this PR. I'm checking...

**Comment by danielzhe** [comment]
@karreiro Is ready to your review. The issue will be handled in another PR, after this PR was merged. Thank you!

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by danielzhe** [comment]
@manstis Merge, please.

**Pull request merged**
