### PR TITLE
[AF-2216] Generic Error Pop Up when server is shutdown

### PR DESCRIPTION
**Pull request by gabriel376**
**[AF-2216](https://issues.jboss.org/browse/AF-2216) Generic Error Pop Up when server is shutdown**

**Issue:**
A Generic Error Pop Up is show when server is shutdown

**Solution:**
Show an appropriated pop up to user when server is shutdown

**Edge Cases:**
* on HA environments
* when server is shutdown in the middle of some operation that shows Busy Pop Up (for example, when creating a new Project). In this case, Busy Pop Up is never closed and the application hangs

**Notes:**
* tested on HA environment and didn't find any issues
* created a new pop up "*Could not connect to server. This very likely means a network problem. Do you want to reload the application?*" similar to an existing pop up that is shown when session timeouts "*Invalid response received from the server. This very likely means that you have been logged out due to inactivity. Do you want to log in again?*"
* I could not find a better way to identify that server is shutdown inside Catch-All logic. Errai is able to identify that server got disconnected and to notify this event (see ClientMessageBusImpl.java), but this happens after Catch-All handle the exception
* created a queue system to avoid multiple popups to show one on top of another. This way, the next popup will shown when user closes the first one, as in a FIFO system

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
Hi @gabriel376,
I tried the fix manually and I am still getting an unexpected error with no information about the shutdown of server. Which server did you use? I was working with wildfly 14.

**Comment by gabriel376** [comment]
Hi @barboras7 
I am using **wildfly-17.0.1.Final** and BC built from master branch.
Can you check your logs to see what Javascript error are you getting ?
Thank you!

**Comment by dgutierr** [comment]
@gabriel376 mind to add @lclay2 as a reviewer please and not merge under she approves?

**Comment by lclay2** [comment]
@gabriel376 or @dgutierr  is there a screenshot or video that I could look at, either here or on the jira? Thanks

**Comment by gabriel376** [comment]
@lclay2 what do you exactly need ?

**Comment by barboras7** [comment]
Hi @gabriel376,
I also tried with wildfly-17.0.1.Final. 

What I am trying to reproduce the issue:

1. Log in to the business central
2. Stop the server (I am getting a `java.lang.IllegalStateException: FileSystem is closed.` in the server log and Unexpected error with the following details: ` | Uncaught exception: Error parsing JSON: SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data`)
3. When I close the Unexpected error dialog and try to navigate in the business central, after multiple steps (does not happen after one or two clicks) I get a "Loading" popup and can not do anything in the business central and I can not see why the popup is there.

**Comment by gabriel376** [comment]
@barboras7 please send me the link to the war file you used, so I can reproduce the issue

**Comment by lclay2** [comment]
UX recommends that someone from Docs review the error message content. @csherrar  - could you please verify the message content - the cause of this might not be network problems. Conditional acceptance, pending content review. Thanks.

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
Hi @gabriel376,
here's a link to the war file [AF-2216 war](https://drive.google.com/file/d/1UvyPlLfJ9LCl6T05PaG9oDldo5dBWMts/view?usp=sharing). I built it locally from this PR.

**Comment by gabriel376** [comment]
Hi @barboras7 
I could not reproduce the issue using your .war file
Please send me an invite for a call so we can work together on this issue

**Comment by gabriel376** [comment]
Pushed new commit to fix issue on Firefox browser.
Fix now works on Google Chrome and Firefox.

Tested on:
* Google Chrome Version 77.0.3865.75 (Official Build) (64-bit)
* Firefox 68.0.2 (64-bit)

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
jenkins execute full downstream build

**Pull request merged**
