### PR TITLE
[7.3.x] JBPM-6457 - Variables with same name but in different scopes causes I…

### PR DESCRIPTION
**Pull request by tsurdilo**
…llegalArgumentExceptions by XmlParser

### CODE REVIEW

**Comment by romartin** [comment]
Hey @tsurdilo , sounds good, will give it a quick try right now, thanks! BTW just a Q plz - this should be merged into `master `too, or does it only applies for this branch?

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @tsurdilo, thank you. I don't see an Exception any more in Designer and in Stunner as well. But now message about variables duplication is shown in Server log only [1]. I guess it will be nice to display this message in Validation and in messages as well. What do you think? Is it possible?

So, short recap:
1. Designer write some message [1] on save action in server log, but no notifications in Validation or Messages on save, on validation and on compile time (Build&Deploy) as well.
2. Stunner don't notify about duplicated variables names at all.
Is it possible to notify use on Validation about duplicate variables names if it is not possible to use it? Or don't print error in Server log if duplicate variables names are possible.
[1]
```
10:19:48,193 ERROR [org.drools.core.xml.ExtensibleXmlParser] (Thread-214) Process Info: id:rrrow.a, pkg:com.myteam.rrrow, name:a, version:1.0
Node Info: id:testIt name:
Parser message: (null: 36, 68): cvc-id.2: There are multiple occurrences of ID value 'testIt'.
10:19:48,193 ERROR [org.drools.core.xml.ExtensibleXmlParser] (Thread-214) Process Info: id:rrrow.a, pkg:com.myteam.rrrow, name:a, version:1.0
Node Info: id:testIt name:
Parser message: (null: 36, 68): cvc-attribute.3: The value 'testIt' of attribute 'id' on element 'bpmn2:property' is not valid with respect to its type, 'ID'.
10:19:48,207 ERROR [org.drools.core.xml.ExtensibleXmlParser] (Thread-214) Process Info: id:rrrow.a, pkg:com.myteam.rrrow, name:a, version:1.0
Node Info: id:testIt name:
Parser message: (null: 36, 68): cvc-id.2: There are multiple occurrences of ID value 'testIt'.
10:19:48,207 ERROR [org.drools.core.xml.ExtensibleXmlParser] (Thread-214) Process Info: id:rrrow.a, pkg:com.myteam.rrrow, name:a, version:1.0
Node Info: id:testIt name:
Parser message: (null: 36, 68): cvc-attribute.3: The value 'testIt' of attribute 'id' on element 'bpmn2:property' is not valid with respect to its type, 'ID'.
```

**Comment by tsurdilo** [comment]
@romartin yes its there https://github.com/kiegroup/kie-wb-common/pull/1195

**Comment by tsurdilo** [comment]
@hasys yes I agree. Could you please create a jira for it so I can work on these improvements and track work? Thanks!

**Comment by romartin** [comment]
@hasys missing for your approval to merge. Thanks!

**Pull request merged**
