### PR TITLE
RHPAM-461: Two different radiogroups with the same name have the same id.

### PR DESCRIPTION
**Pull request by pefernan**
@kkufova could you please review?

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
Making executive decision to merge even though F-DS-B is failing (careful not to trigger Jenkins!)

**Pull request merged**
