### PR TITLE
KOGITO-3853: [DMN Designer] Move the structure option to top of the Data Type drop-down

### PR DESCRIPTION
**Pull request by karreiro**
**JIRA**: [KOGITO-3853](https://issues.redhat.com/browse/KOGITO-3853): [DMN Designer] Move the structure option to top of the Data Type drop-down

**VSCode**: [plugin.vsix](https://www.dropbox.com/s/hub3dri81go89gj/plugin-KOGITO-3853.vsix?dl=0)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Review by vpellegrino — APPROVED** [review]
It looks great to me,
thanks @karreiro

**Review by jomarko — APPROVED** [review]
works fine, thank you @karreiro

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Pull request merged**
