### PR TITLE
JBPM-6914 (RHPAM-457): Changes in options are saved on cancel

### PR DESCRIPTION
**Pull request by pefernan**
@jsoltes could you take a look?

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@jsoltes I think now it works fine, triggered the downstream build again and see if you can reproduce it.

**Comment by jsoltes** [comment]
@pefernan well, the thing I mention is still there. But it is a hazy area, since the embedded editor has it's own ok and cancel buttons. So if I edit line and click ok and then click cancel on the FieldProperties dialog, should it be saved or not? The current behavior is that it gets saved.

**Comment by pefernan** [comment]
@jsoltes it shouldn't be saved, but I tried and it doesn't save the changes. What browser are you using?

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins retest this please

**Comment by pefernan** [comment]
Jenkins retest this please

**Pull request merged**
