### PR TITLE
JBPM-9532 : Recusivity issue on form generation

### PR DESCRIPTION
**Pull request by akumar074**
> Currently, when we are generating a form when we have 2 data objects which reference each other or have cyclic reference, the engine enters into an infinite loop. 
> To fix this issue, we have come up with a way to track the cyclic reference in the field and  skip the form generation for field when we encounter the cycle.

Screenshot: https://drive.google.com/file/d/1x_YYhokF8VAz_TYp4xlhRCKl8Kwcqeiv/view?usp=sharing

**JIRA**: 
[JBPM-9532](https://issues.redhat.com/browse/JBPM-9532)
[RHPAM-3366](https://issues.redhat.com/browse/RHPAM-3366)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins do fdb

**Comment by akumar074** [comment]
@pefernan @jstastny-cz Sorry, I had to recreate this new PR due to some issue. I have added the test as well. Please take a look and review this PR.
Original Pull Request: https://github.com/kiegroup/kie-wb-common/pull/3696
Thanks

**Comment by akumar074** [comment]
Jenkins do fdb

**Comment by akumar074** [comment]
Jenkins do fdb

**Comment by akumar074** [comment]
Jenkins retest this

**Review by pefernan — APPROVED** [review]

**Comment by jstastny-cz** [comment]
There is an issue when using task forms and the recursion is not using the type itself, but rather List<>.

See attached example, generation of forms hangs for P2 and P5.
[formmodeler-recursive.zip](https://github.com/kiegroup/kie-wb-common/files/7733629/formmodeler-recursive.zip)

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
@jstastny-cz I have updated the code and it fixes the issues you mentioned about task inputs and List. We are able to generate the forms properly now.

**Comment by jstastny-cz** [comment]
Just for sake of tracking:
I tried the example with latest FDB, forms generation completes successfully in all the modeled cases.

Investigating further issues potentially exposed by this fix. Those issues will most probably not be in the fix itself, but rather a general recursion issue. If that's the case will create follow-up Jiras.

**Review by jstastny-cz — APPROVED** [review]
Approving the fix, good to merge.

As for the other mentioned recursion issues, I've created [JBPM-9984](https://issues.redhat.com/browse/JBPM-9984) for tracking.

**Pull request merged**
