### PR TITLE
AF-2799 Update kie-wb-common unit tests deprecated classes

### PR DESCRIPTION
**Pull request by jomarko**
**Thank you for submitting this pull request**

**Jira**: [AF-2799](https://issues.redhat.com/browse/AF-2799)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
There is a compilation error on master
```
22:17:51  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project optaplanner-core: Compilation failure: Compilation failure: 
22:17:51  [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-master.pr/kiegroup_optaplanner/optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/uni/DroolsUniCondition.java:[226,26] wrong number of type arguments; required 2
22:17:51  [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-master.pr/kiegroup_optaplanner/optaplanner-core/src/main/java/org/optaplanner/core/impl/score/stream/drools/uni/DroolsUniCondition.java:[310,22] wrong number of type arguments; required 2
22:17:51  [ERROR] -> [Help 1]
22:17:51  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project optaplanner-core: Compilation failure
```

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by ederign** [comment]
@caponetto can you please review this?

**Review by caponetto — APPROVED** [review]
Thanks @jomarko for this effort! It looks great to me.

**Review by Srihari1192 — APPROVED** [review]
LGTM

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
