### PR TITLE
JBPM-6265: Inserting missed dependencies on stunner project showcase

### PR DESCRIPTION
**Pull request by tiagodolphine**
The root cause of the exception when starting up the UI on the showcase was a dependecy injection that couldn't be made, the bean **org.kie.workbench.common.screens.impl.LibraryServiceImpl** was not present on the CDI context due to the missing dependencry **kie-wb-common-library-backend**. Besides, it was be added other dependency **kie-wb-common-examples-screen-backend** that was needed by the **LibraryServiceImpl**.

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by tiagodolphine** [comment]
@romartin the build on jenkins have failed, but when looking on the main build of the project it has failed there, so I think the problem is on master.

**Comment by manstis** [comment]
@tiagobento Hi, "indexing" tests are a little unstable. If that was the only failing test then we'd normally re-trigger the build with "Jenkins retest this" (there's a RegEx that is matched, I think it needs to include "Jenkins" and "retest" @psiroky could advise if you want to know).

However the other failing tests are a lot more serious.. so @desmax74 @porcelli looks like some Maven Builder related tests are failing (and I know you had some _fun_ with these...) @tiagodolphine let them take a look.

**Comment by romartin** [comment]
yes @manstis @tiagodolphine , I faced same issues guys, the tests are unstable due to the indexer

**Comment by tiagodolphine** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Pull request merged**
