### PR TITLE
RHPAM-3232 : Error on migrate a git project from version 6.4 to 7.8.1

### PR DESCRIPTION
**Pull request by akumar074**
* fixed Boolean Class cast

**JIRA**: [RHPAM-3232](https://issues.redhat.com/browse/RHPAM-3232)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins run fdb

**Review by tomasdavidorg — APPROVED** [review]
Looks good to me when the build is green.

**Review by adrielparedes — APPROVED** [review]

**Comment by adrielparedes** [comment]
Looks great, lets way for green before merging, good job @akumar074

**Comment by akumar074** [comment]
PR build test failure is unrelated. There's already a PR for the fix that test https://github.com/kiegroup/appformer/pull/1188

**Comment by akumar074** [comment]
Jenkins retest this

**Pull request merged**
