### PR TITLE
[8.0.x] JBPM-6047: Uploaded documents not visible on Documents tab on process Instance details

### PR DESCRIPTION
**Pull request by pefernan**
@hasys can you take a look?

This is part of an ensemble, merge with:
https://github.com/kiegroup/jbpm/pull/981
https://github.com/kiegroup/kie-wb-common/pull/1160
https://github.com/kiegroup/jbpm-form-modeler/pull/142
https://github.com/kiegroup/jbpm-wb/pull/873

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins retest this

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
@pefernan Could you please follow up these PRs? They're getting old and should really be merged.

**Pull request merged**
