### PR TITLE
AF-2693: Add a system parameter to customize the number of assets in each page

### PR DESCRIPTION
**Pull request by akumar074**
- Added a new property in project preferences to configure the number of assets per page in the project screen
 - Property can be set with _"org.kie.library.assets_per_page"_ at WAR startup
 - The default value for the property is 15

**JIRA**: [AF-2693](https://issues.redhat.com/browse/AF-2693)

**referenced Pull Request**: https://github.com/kiegroup/appformer/pull/1083

**Business Central War**: [Download](https://drive.google.com/file/d/1U95fsGvygHVs8xTMwzcKtZ9Ji4gbt4jw/view?usp=sharing)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
jenkins do fdb

**Comment by akumar074** [comment]
jenkins do fdb

**Comment by akumar074** [comment]
jenkins do fdb

**Comment by akumar074** [comment]
jenkins do fdb

**Comment by akumar074** [comment]
jenkins do fdb

**Comment by akumar074** [comment]
@tomasdavidorg @paulovmr I have added the deployable WAR file to the test.

**Comment by tomasdavidorg** [comment]
Hi @akumar074 , thanks I will take a look on this PR tomorrow.

**Review by tomasdavidorg — APPROVED** [review]

**Comment by paulovmr** [comment]
jenkins do fdb

**Review by paulovmr — APPROVED** [review]

**Comment by akumar074** [comment]
Jenkins retest this

**Pull request merged**
