### PR TITLE
[DO NOT MERGE]  logback-test to increase logging level on the PomEditorTestWithGit 

### PR DESCRIPTION
**Pull request by desmax74**
[DO NOT MERGE]

### CODE REVIEW

**Comment by desmax74** [comment]
Jenkins retest this

**Comment by desmax74** [comment]
jenkins test this

**Comment by desmax74** [comment]
jenkins full downstream build

**Comment by jhrcek** [comment]
@desmax74 it's: Jenkins execute full downstream build :) (or jenkins retest this to run the build for this repo only)

**Comment by desmax74** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
jenkins retest this

**Comment by jhrcek** [comment]
@desmax74 
Two comments - 
1) I can't find any debug logs in the build console, probably because you put logback-test.xml into different module than in which the test class is.

You put it in `kie-wb-common-cli/kie-wb-common-cli-tools/kie-wb-common-cli-pom-migration/src/test/resources/logback-test.xml`

But I think to see any debug logs for that test you have to put it in module where the test class is: `kie-wb-common-services/kie-wb-common-services-backend/src/test/resources/logback-test.xml`

2) It seems like 60 minutes timeout for building kie-wb-common is not enough. Looking at build history of https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-common-pullrequests/ there are 8 timeouts out of 23 builds. I'll submit a PR to override this default temporarily before tweaking the performance of the build in other ways.

**Comment by jhrcek** [comment]
PR with timeout increase was merged. 
jenkins retest this

**Comment by jhrcek** [comment]
My change broke the PR builder jobs :O Fix merged, trying again:
jenkins retest this

**Comment by jhrcek** [comment]
@desmax74 I believe this PR is no longer needed and can be closed.

**Pull request closed without merging**
