### PR TITLE
JBPM-9117 : Stunner - Error message when creating process variable without Data Type

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin can you review this PR?

### CODE REVIEW

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by inodeman** [comment]
Hi @romartin added a special test case that checks for variable with only name

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hey @inodeman , full downstream build is missing. I cannot test the PR.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Closing as it's a duplicate for https://github.com/kiegroup/kie-wb-common/pull/3305

**Pull request closed without merging**
