### PR TITLE
JBPM-7723 - Change ServerManagementBrowserPresenter to Dependent scope

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by porcelli** [comment]
@cristianonicolai I won't be able to remember, sooooo long ago :)

with that said, it might be an optimization.. but need track the scope of the root element of the UI, as if it's `ApplicationScoped` we won't have multiple instances of the `Dependend` scope leftover (it might consume a lot of memory if these dependend components are leaked)

**Comment by cristianonicolai** [comment]
well if that is a potential issue, then it wont be the only place in the console to be affected by that, there is a significant amount of _WorkbenchScreen_ using a _Depedent_ scope. 
@bsremac is there any sort of test case for the server management UI that could be verified in here? Not sure if you or someone else was checking that in the past. Although the change is trivial we need to check the behavior still consistent.

**Comment by bsremac** [comment]
@cristianonicolai We have got one happy-path Selenium test which goes through the options in this perspective and tests basic functions. I can build _kie-wb_ locally off the PR and run that test, but that test won't be able to expose the type of potential issues discussed above, of course.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by bsremac** [comment]
@cristianonicolai I've built _kie-wb_ locally and run the happy-path test against the _Execution Servers_ perspective. The test is passing.

**Comment by cristianonicolai** [comment]
@bsremac thanks

**Pull request merged**
