### PR TITLE
BAQE-400: Remove unused imports (fix)

### PR DESCRIPTION
**Pull request by romartin**
Hey @jomarko @tiagodolphine @manstis 

Sorry after merging a few PRs together the full build got broken due to some `unused imports` check failed. Here is the fix. 

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Sorry guys was my fault as I merged another PR on top of the @jomarko one without running again the full build... :( Anyway I'm keeping an eye on this build, once green will merge, hope will be soon
Thx

**Comment by romartin** [comment]
oops `A fatal error has been detected by the Java Runtime Environment`

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
Come on Jenkins... there are people waiting for this to be merged!

**Comment by romartin** [comment]
Sorry @manstis ! The JVM crashed again! :(
Anyway it's failing the full build, I mean you can run the regular build locally and it works.. if that helps

**Pull request merged**
