### PR TITLE
[7.0.x] Library fixes and improvements

### PR DESCRIPTION
**Pull request by paulovmr**
Cherry picked from master (https://github.com/kiegroup/kie-wb-common/pull/782).

GUVNOR-3009: [Library] Create a root screen on library (tiles) to navigate and create Organizational Units (Teams)
GUVNOR-3007: [Library] Save the project explorer state (opened/closed) by user
GUVNOR-2905: Library: Remove the "Open Project Editor" button from the project explorer.
GUVNOR-3005: Remove search textbox from the menu header
JBPM-5661: [Security management] Library perspective allows to create a project even if it is disabled

### CODE REVIEW

**Comment by paulovmr** [comment]
Depends on: https://github.com/kiegroup/guvnor/pull/444

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
@Rikkola If you could take a look, just cherry picking my previous commits to 7.0.x.

**Comment by manstis** [comment]
@paulovmr Unfortunately this has merge conflicts :-(

I've merged the related guvnor PR https://github.com/kiegroup/guvnor/pull/444

**Comment by paulovmr** [comment]
@manstis Conflicts resolved :)

**Pull request merged**
