### PR TITLE
JBPM-7565 Stunner - Create Marshaller tests for Rest Service Task

### PR DESCRIPTION
**Pull request by LuboTerifaj**
Ignored tests because of issues:
https://issues.jboss.org/browse/JBPM-7072 - see my comment
https://issues.jboss.org/browse/JBPM-7726

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
Hello @evacchi @manstis 

Can you please have a look and merge it, if it is OK? It's just tests, but contains changes needed for my other PRs.

Thank you!

**Comment by LuboTerifaj** [comment]
Hi @evacchi 
I think it is good to ignore just failing tests. Not failing tests are testing new Marshaller. But if you stand for ignore the whole test class I can change it.

Otherwise, can we merge this PR? @romartin ?

Thank you.

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by LuboTerifaj** [comment]
Hi @hasys 
 
Can you have a look please?

Thanks.

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by hasys** [comment]
Hi @manstis, this PR is ready to go, thank you.

**Pull request merged**
