### PR TITLE
JBPM-7318: Stunner - 'Task name' is for internal use and mustn't beditable for ServiceTasks

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit 494af6734577c62360c8aee62c403dc8792d3354)

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @wmedvede ,
All good for me, except the ticket specified in the commit name... :) Can you please use some `JBPM` instead of an `RHPAM`?  Thx!

**Comment by wmedvede** [comment]
@romartin @hasys Wow! a green/green! I think it's a good moment to merge this!

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Pull request merged**
