### PR TITLE
JBPM-8738 Stunner - There is no validation of datatype in Name Imports

### PR DESCRIPTION
**Pull request by Josephblt**
https://issues.redhat.com/browse/JBPM-8738

This adds a combo box with a few default class types and still allows for a custom one to be created. Similar to the combo box used to Global Variables types. Class Name, Location and Namespace fields do not accept invalid chars. There is regex validation as well for names started with numbers, spaces, etc. Basically the fields accept java valid names (check [specification](https://docs.oracle.com/javase/specs/jls/se7/html/jls-3.html#jls-3.8) for details).

[Business Central](https://drive.google.com/file/d/1aYqqrR3aUnPSDinI7rqps3YjpVm9dpvN/view?usp=sharing)
[VS Code](https://drive.google.com/file/d/1JYCWfDGZhtO_t_L4Fx7mU6G5UtFkVOqD/view?usp=sharing)

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
some test failures here - - build was UNSTABLE

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by Josephblt** [comment]
Hello @romartin. Could you please review this. Thanks.

**Comment by romartin** [comment]
@domhanak @LuboTerifaj this applies to both kogito and BC, adding you as reviewers. Thx!

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hi @Josephblt please have a look at my [comment](https://issues.redhat.com/browse/JBPM-8738?focusedCommentId=14001743&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14001743).

**Comment by romartin** [comment]
Hey @LuboTerifaj @Josephblt thanks for the review but this is not in the "urgent list" for DevPreview scope now, so please do not yet spend time on it, thanks in advance!!

**Comment by Josephblt** [comment]
Jenkins execute compile downstream build

**Comment by Josephblt** [comment]
Jenkins execute compile downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute compile downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute compile downstream build

**Comment by Josephblt** [comment]
Hello @LuboTerifaj, @romartin. Ready for review. Thanks.
Links:
[Business Central](https://drive.google.com/file/d/1yi9b20r31vvq1URfFzon5Ehnx019RXfb/view?usp=sharing)
[VS Code](https://drive.google.com/file/d/1XbpEazg0kKuPYdJLe1WHIHwwbeHVdOV0/view?usp=sharing)

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute compile downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute compile downstream build

**Comment by Josephblt** [comment]
Jenkins do fdb

**Comment by Josephblt** [comment]
Jenkins do cdb

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins run cdb
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by LuboTerifaj** [comment]
Hello @Josephblt , can you please resolve conflicts with master branch? Thanks!

**Comment by domhanak** [comment]
stale PR cc @romartin

**Pull request closed without merging**
