### PR TITLE
JBPM-9381 : Stunner - Data Object's Name with new line characters breaks the process

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin @LuboTerifaj Can you check this PR. Fixes the issue in both BC and Kogito.

### CODE REVIEW

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by inodeman** [comment]
Hi @LuboTerifaj @romartin Artifacts uploaded to: https://drive.google.com/drive/folders/1im-f0Fk-PO3XiB-Dr_A9GqX8cHVgQenS?usp=sharing

**Comment by LuboTerifaj** [comment]
Hello @inodeman , VSCode extension doesn't work for me locally. Did you test it or is there just an issue in my local environment? Thanks!

**Comment by domhanak** [comment]
@LuboTerifaj @inodeman Same here, provided VSIX file does not load editors, only scesim is loaded.

**Review by LuboTerifaj — COMMENTED** [review]
Hello @inodeman ,

I didn't test Kogito yet since it doesn't wok. See my previous [comment](https://github.com/kiegroup/kie-wb-common/pull/3437#issuecomment-698836247).

I have found two issues:
- Server log contains error messages.
- It is not possible to select Data Object in assignments: an unexpected error occurs. 
I think we can postpone them since by this fix we won't get broken processes.

I have reported issues above in a single jira:
- [RHPAM-3205](https://issues.redhat.com/browse/RHPAM-3205) Data Object has different Name on Canvas than in Properties panel

I will approve the PR once the Kogito is tested as well. Can you please have a look at the extension and let me know if the issue is only on my local machine?

Thank you!

**Comment by hasys** [comment]
Hi @inodeman, shouldn't we just remove new line from the name? If I correct Data Objects name it is like variable name and is used as ID in the engine, so new line have no meaning there in my opinion. Anyway &newLine; is not valid XML escape value so no other product will handle it as well, if it is necessary to keep the new line in the name I suggest to replace it by `&#10;` WDYT?

**Comment by inodeman** [comment]
Hi @hasys removing it so it gets merged. I think it is best to remove for now as you suggest. DO behave special as they have to share the same id and name and internally the Eclipse classes seem to break if there is something in them. Will test both scenarios

**Comment by inodeman** [comment]
Hi @LuboTerifaj working on it. We will remove the newline character for now. The problem is the Eclipse classes. Next week I can work on a more permanent solution.

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by inodeman** [comment]
Hi @LuboTerifaj @lazarotti @romartin sending PR. Will upload artifacts shortly. Verified works on BC and Kogito (WebApp and VSCode)

**Comment by inodeman** [comment]
Hi @LuboTerifaj @romartin @lazarotti please find artifacts here.  https://drive.google.com/drive/folders/1im-f0Fk-PO3XiB-Dr_A9GqX8cHVgQenS?usp=sharing

**Review by romartin — APPROVED** [review]
Great, looks good to me! thanks @inodeman

**Review by LuboTerifaj — APPROVED** [review]
Hello @inodeman ,

I have found one issue, but it is present also on master:
[JBPM-9391](https://issues.redhat.com/browse/JBPM-9391) _Data Objects in Assignments disappear once the process is saved_

It looks good to me.

Thanks!

**Comment by romartin** [comment]
thanks a lot @LuboTerifaj for the early review!!

**Pull request merged**
