### PR TITLE
RHPAM-3437 - BPMN editor [Business Central]: Missing structureRef for Message when creating process

### PR DESCRIPTION
**Pull request by Josephblt**
This is just a cherry-pick from this PR https://github.com/kiegroup/kie-wb-common/pull/3564

**JIRA**: [RHPAM-3437](https://issues.redhat.com/browse/RHPAM-3437)

**Business Central**: [WAR file](https://drive.google.com/file/d/1_P7GmSJQ9UM1P_uWjoA-MQW7DsPNloxn/view?usp=sharing)

**VS Code**: [plugin](https://drive.google.com/file/d/1Ht1oLuXCVQc2hHU8axoWW_z4fa_MCqCx/view?usp=sharing)

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins run cdb

**Review by romartin — APPROVED** [review]
Quicky approving as I see it's just a cherry-pick. Thanks @Josephblt

**Comment by Josephblt** [comment]
Hello @LuboTerifaj. If you could give this priority, that would be great. Thanks.

**Review by LuboTerifaj — APPROVED** [review]
It looks good to me. Thanks!

**Comment by Josephblt** [comment]
Hello @romartin . This is ready to merge. Thanks

**Pull request merged**
