### PR TITLE
DROOLS-5619: [DMN Designer] Copy/paste is not working for Decision & BusinessKnowledgeModel nodes

### PR DESCRIPTION
**Pull request by romartin**
Hey @danielzhe @jomarko 

Here is the fix for [DROOLS-5619](https://issues.redhat.com/browse/DROOLS-5619)

Sorry for the amount of changed files, in fact the fix was just about a few lines, but also as we stil are in the release slot, I used this work to drop some deprecated annotation `@PropertySet`, and also update the model classes accordingly.

Anyway, I've been testing both BPMN and DMN editors again, by creating/saving/loading diagrams, copy/pasting, using forms, etc, and I didn't found any further issues, hope everything is working properly again :)

CC @karreiro 

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute fdb

**Comment by romartin** [comment]
Jenkins execute cdb

**Review by danielzhe — APPROVED** [review]
Thank you, @romartin !
It's working good now!

**Review by karreiro — APPROVED** [review]
Thank you, @romartin. LGTM, and it solves the issue :)

**Comment by romartin** [comment]
thanks @danielzhe  @karreiro for your help! and sorry for inconveniences again!!

**Comment by karreiro** [comment]
No worries, @romartin! :-) Thank you for the quick fix :-)

**Pull request merged**
