### PR TITLE
JBPM-10193: UI error: unexpected system error occurred when access Form asset and also Task form which have listbox component

### PR DESCRIPTION
**Pull request by bxf12315**
**Thank you for submitting this pull request**

**JIRA**: [JBPM-10193](https://issues.redhat.com/browse/JBPM-10193)

**Referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2383
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://donwnload.here/something)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by bxf12315** [comment]
jenkins retest this

**Comment by bxf12315** [comment]
jenkins do fdb

**Comment by bxf12315** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by bxf12315** [comment]
jenkins retest this

**Comment by bxf12315** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
@bxf12315 there is some API incompatibility in kie-wb-common-dmn-webapp-kogito-marshaller module

```
[2023-09-26T01:40:02.815Z] [ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate (generate-javascript) on project kie-wb-common-dmn-webapp-kogito-marshaller: Execution generate-javascript of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate failed: An API incompatibility was encountered while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate: java.lang.ExceptionInInitializerError: null
```

**Comment by bxf12315** [comment]
jenkins retest this

**Comment by bxf12315** [comment]
> @bxf12315 there is some API incompatibility in kie-wb-common-dmn-webapp-kogito-marshaller module
> 
> ```
> [2023-09-26T01:40:02.815Z] [ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate (generate-javascript) on project kie-wb-common-dmn-webapp-kogito-marshaller: Execution generate-javascript of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate failed: An API incompatibility was encountered while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate: java.lang.ExceptionInInitializerError: null
> ```

I tried to update maven-jaxb2-plugin : https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2382.
Can the PR build will include this one ?

**Comment by mareknovotny** [comment]
yes, if it is the same branch name it will be taken into PR CI build.

jenkins retest this please

**Comment by bxf12315** [comment]
> yes, if it is the same branch name it will be taken into PR CI build.
> 
> jenkins retest this please
same issue，https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2382 change not work in the PR build.
`22:48:26  [INFO] --- maven-jaxb2-plugin:0.14.0:generate (generate-javascript) @ kie-wb-common-dmn-webapp-kogito-marshaller ---
22:48:27  Sep 27, 2023 10:48:26 AM com.sun.xml.bind.v2.runtime.reflect.opt.Injector <clinit>
22:48:27  SEVERE: null
22:48:27  java.security.PrivilegedActionException: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)`

**Comment by bxf12315** [comment]
jenkins retest this please

**Comment by bxf12315** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
@bxf12315 you need to have all PRs on the same user:branch and then the FDB on parent PR take them into FDB.
You did here as https://github.com/Cory-jbpm/kie-wb-common/tree/JBPM-10193 and top parent PR as https://github.com/bxf12315/droolsjbpm-build-bootstrap/tree/JBPM-10193

so there are different authors according to Github and PRs won't be in PR CI or in FDB CI.
Change this or https://github.com/bxf12315/droolsjbpm-build-bootstrap/tree/JBPM-10193 to the same github author fork

**Comment by bxf12315** [comment]
jenkins retest this please

**Comment by bxf12315** [comment]
jenkins do fdb

**Review by paulovmr — APPROVED** [review]

**Review by tomasdavidorg — APPROVED** [review]

**Pull request merged**
