### PR TITLE
[Do not merge] [7.48.x] RHDM-1458: [DMN Designer] Multiple DRDs support - The undo/read are lost when user changes between diagrams

### PR DESCRIPTION
**Pull request by danielzhe**
**JIRA**: [RHDM-1458](https://issues.redhat.com/browse/RHDM-1458)

Cherry-pick from: https://github.com/kiegroup/kie-wb-common/pull/3520

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins do fdb

**Review by jomarko — APPROVED** [review]
@danielzhe thank you, please do not merge until 7.48.x is open for changes.

**Review by karreiro — APPROVED** [review]
Thank you, @danielzhe!

**Review by jomarko — CHANGES_REQUESTED** [review]
We can not merge this 
https://github.com/kiegroup/kie-wb-common/pull/3551

**Comment by jomarko** [comment]
We should close this PR. We do not target the fix for 7.48.x anymore.

**Pull request closed without merging**
