### PR TITLE
JBPM-8572: Stunner - missing Abort parent property for Reusable sub-process

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi @romartin @hasys would you mind review this PR?

Thanks

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by wmedvede** [comment]
Hi @romartin @hasys , full-build failed but artifacts were generated.

**Comment by hasys** [comment]
Hi @wmedvede thank you looks and works good, thank you! Just one question: how **Abort Parent** property depends on **Independent** property? I didn't found it in Jira description.

Also, @LuboTerifaj, @xiezhang7, can I ask you also take a look at CM part of this PR? Thank you!

### Check list
- [x] ACKs are set
- [x] Affected version is set property
- [ ] Is realization aligned to jira description?
- [ ] Is CM verified?
  - [ ] CM
- [x] Both Jenkins jobs are green
  * Known selenium issue: [BAQE-999](https://issues.jboss.org/browse/BAQE-999)

### Code review
- [x] Code coverage
- [x] License headers
- [x] Static analyser gates
- [x] Code Style

### Acceptance Criteria
> Should be listed there (or linked to jira)

- [x] Tested with full downstream build
  - [x] Firefox
  - [x] Chrome

### Found issues
>  **Blocker**, **Critical** and **Major** bugs and **Blocker** and **Critical** enhancements should be fixed before merge.
* None

### Used resources
Processes for quick test can be found here: https://github.com/bpmn-tutorials/AbortParent

**Comment by wmedvede** [comment]
> Hi @wmedvede thank you looks and works good, thank you! Just one question: how **Abort Parent** property depends on **Independent** property? I didn't found it in Jira description.
> 
> Also, @LuboTerifaj, @xiezhang7, can I ask you also take a look at CM part of this PR? Thank you!
> 
> ### Check list
> * [x]  ACKs are set
> * [x]  Affected version is set property
> * [x]  Is realization aligned to jira description?
> * [ ]  Is CM verified?
>   
>   * [ ]  CM
> * [x]  Both Jenkins jobs are green
>   
>   * Known selenium issue: [BAQE-999](https://issues.jboss.org/browse/BAQE-999)
> 
> ### Code review
> * [x]  Code coverage
> * [x]  License headers
> * [x]  Static analyser gates
> * [x]  Code Style
> 
> ### Acceptance Criteria
> > * Set Abort Parent to _true_ and link process with error, process should stop at runtime on ReUsable sub-process activity
> > * Set Abort Parent to _false_ and link process with error, process should continue despite of the error inside of process linked by ReUsable sub-process
> > * Set Abort Parent to _true_ and link process without errors, process should continue when ReUsable sub-process finished it's execution.
> > * If Independent property of ReUsable sub-process is set to _true_, Abort Parent property shouldn't be active.
> 
> * [x]  Tested with full downstream build
>   
>   * [x]  Firefox
>   * [x]  Chrome
> 
> ### Found issues
> > **Blocker**, **Critical** and **Major** bugs and **Blocker** and **Critical** enhancements should be fixed before merge.
> 
> * None
> 
> ### Used resources
> Processes for quick test can be found here: https://github.com/bpmn-tutorials/AbortParent

Hi @hasys , the JIRA description was updated accordingly https://issues.jboss.org/browse/JBPM-8572

**Comment by xiezhang7** [comment]
@LuboTerifaj It looks good to me. Thanks.

**Pull request merged**
