### PR TITLE
JBPM-6457 - Variables with same name but in different scopes causes I…

### PR DESCRIPTION
**Pull request by tsurdilo**
…llegalArgumentExceptions by XmlParser

### CODE REVIEW

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
@hasys could you please have a look? This applies the same change we did already in jbpm-designer for the process data event listener. I did not know before one exists here as well :) thanks.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @tsurdilo, thank you. Same notes as for https://github.com/kiegroup/kie-wb-common/pull/1196

**Comment by tsurdilo** [comment]
@hasys left comment there. @romartin could you approve this one as well as the 7.3.x one ? Thanks.

**Pull request merged**
