### PR TITLE
JBPM-8308: Add missing dependencies for JDK 11

### PR DESCRIPTION
**Pull request by LuboTerifaj**
Missing dependencies for annotation and jaxb.

### CODE REVIEW

**Comment by hasys** [comment]
Hi @pefernan, @romartin,

@LuboTerifaj added all missing dependencies for Forms to fix build on Java 11.

It also includes dependency added in https://github.com/kiegroup/kie-wb-common/pull/2491/files in the same lines, so it shouldn't create any conflicts.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@LuboTerifaj thank you!

**Comment by pefernan** [comment]
+1 to merge and close this [one](https://github.com/kiegroup/kie-wb-common/pull/2491/files) after merge

**Comment by pefernan** [comment]
@LuboTerifaj @hasys is it ok to merge this finally?

**Comment by hasys** [comment]
Hi @pefernan, yes, it is ready to go. Thank you!

**Pull request merged**
