### PR TITLE
JBPM-8369: Stunner - Add marshaller test cases for Event sub-process

### PR DESCRIPTION
**Pull request by LuboTerifaj**
Marshaller test cases for Event sub-process.

Old marshaller has a bug, therefore one test is ignored.
For more information see: https://issues.jboss.org/browse/JBPM-8467

@wmedvede , @hasys can you have a look please?

Thanks!

### CODE REVIEW

**Comment by hasys** [comment]
Hi @LuboTerifaj,

I wasn't able to build it locally, probably there are some conflicts with master, let's try again:

Jenkins retest please

**Comment by hasys** [comment]
Hi @LuboTerifaj,

when I imported test BPMN file to the business central I can see among others an empty Event sub-process above some other nodes: 
image
 
image

Is it expected? Should we test also that sub-process contains nodes it should contain?

**Comment by LuboTerifaj** [comment]
Hello @hasys ,

Woow, when I was modelling testing process, it didn't look like this. This must be a bug.

If you look at _SUBPROCESS_LEVEL_SUBPROCESS_WITH_EDGES_ node with id `_CFA473E5-6CEC-4DE8-A387-F76E49A5FF00` in eventSubProcesses.bpmn file, it contains these four nodes, which are displayed in top-level process in the designer.

Also tests are passing, so I don't know where is the issue.

**Comment by LuboTerifaj** [comment]
Reported issue: https://issues.jboss.org/browse/JBPM-8488
I will update the PR with proper bpmn file.

**Comment by LuboTerifaj** [comment]
Hi @wmedvede , did you have a chance to look at this PR? Thanks!

**Comment by wmedvede** [comment]
> Hi @LuboTerifaj,
> 
> when I imported test BPMN file to the business central I can see among others an empty Event sub-process above some other nodes:
> image
> 
> image
> 
> Is it expected? Should we test also that sub-process contains nodes it should contain?

@LuboTerifaj  which version did you use for generating this test process? I mean, an earlier business-central version, or a compiled version with the last fixes in master?

**Comment by LuboTerifaj** [comment]
Hello @wmedvede , 
Did you use bpmn file from the last commit? I have checked it and it is not broken any more. For more information see comments above.

Thanks!

**Comment by LuboTerifaj** [comment]
Hi @wmedvede is there anything blocking this PR or can it be merged? Thank you!

**Comment by LuboTerifaj** [comment]
Hi @Josephblt ,

can you have a look at this PR? It can resolve some failing tests in you https://github.com/kiegroup/kie-wb-common/pull/2635 PR.

@romartin it would be great to have this merged then.

Thank you!

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Sorry @LuboTerifaj , all fine yep, merging! Thanks!

**Pull request merged**
