### PR TITLE
AF-1132/1134: Not clear that deployment fails if no Kie Server configured

### PR DESCRIPTION
**Pull request by tiagobento**
See:
- https://issues.jboss.org/browse/AF-1134
- https://issues.jboss.org/browse/AF-1132

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by tiagobento** [comment]
Jenkins execute full downstream build

**Comment by tiagobento** [comment]
Jenkins execute full downstream build

**Comment by tiagobento** [comment]
@cristianonicolai Can you merge this please?

**Pull request merged**
