### PR TITLE
AF-2127: Stateless Library

### PR DESCRIPTION
**Pull request by paulovmr**
Part of an ensemble:
* https://github.com/kiegroup/kie-wb-common/pull/2808
* https://github.com/kiegroup/kie-wb-distributions/pull/954

Removed Library preferences that saved the last opened space, last opened branches and last project explorer dock state to improve performance.

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Hi @paulovmr, I am testing the image and I can see some problems:

1. After opening the Project perspective, there is empty space view displayed for a little while. Then the page is refreshed and the Spaces view with current spaces is displayed.
2. When you delete a space, other user is not redirected to the Spaces view. Even after it is completely removed.

I have tried both cases in the previous version and they worked correctly.

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Hello @paulovmr,
sharing some details about the issue number one:

1. After Projects perspective is opened, empty Spaces view is displayed with Loading popup

2. Then there is an empty screen

3. Then the Spaces view with spaces is opened-

**Comment by tomasdavidorg** [comment]
Have you fixed the second issue? I tried the new war and it is gone.

**Comment by paulovmr** [comment]
@tomasdavidorg Thanks for the test. I did a rebase, so I think that might have fixed it. About the blinking I think it is fine, it is really fast just to draw the page.

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
TEst failure is fixed here: Fixed here kiegroup/kie-wb-common#2821

**Pull request merged**
