### PR TITLE
Ignore some tests for IBM jdk

### PR DESCRIPTION
**Pull request by jomarko**
@triceo @barboras7 please have a look, should I file also bug in our Jira or are the mentioned existing issues in external tracking systems enough?

@manstis @etirelli also you may be interested in.

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by etirelli** [comment]
@tarilabs we will need to look into this...

**Comment by jomarko** [comment]
@triceo thanks for the feedback, I incorporated it, would you mind second round of review please?

**Comment by jomarko** [comment]
@manstis would you mind to merge please?

**Pull request merged**
