### PR TITLE
JBPM-8740 - Stunner - Imports dialogue doesn't provide help for existing types

### PR DESCRIPTION
**Pull request by Josephblt**
https://issues.redhat.com/browse/JBPM-8740

This adds a combo box with a few default class types and still allows for a custom one to be created. Similar to the combo box used to Global Variables types.

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hey @Josephblt , @romartin, missing FDB here.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hi @domhanak , since you already did a review of this PR, I've removed myself as the reviewer.

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
Build is failing. Please take a look.

Otherwise looks good. I was able to see my DataObjects in `Imports` dialogue.

**Comment by romartin** [comment]
yeah please @Josephblt , let me know when builds are green and I'll merge! Thanks in advance!

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by Josephblt** [comment]
Jenkins please retest this

**Pull request merged**
