### PR TITLE
JBPM-9472 - Stunner - Data I/O support for all Intermediate Events

### PR DESCRIPTION
**Pull request by Josephblt**
For all intermediate events these Data Assignments can be set:
Catching events: Data Output Assignments
Throwing events: Data Input Assignments

**JIRA**: [JBPM-9472](https://issues.redhat.com/browse/JBPM-9472)

***Business Central**: [WAR file](https://drive.google.com/file/d/1Rhf5R9xdfxgL6PyZxClFbNDrTuEsogja/view?usp=sharing)

**VS Code**: [plugin](https://drive.google.com/file/d/10HsHespt1aWGfIMpB4e8PJbKPAP2kQZP/view?usp=sharing)

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins run cdb

**Comment by Josephblt** [comment]
Build: josephblt/JBPM-9472

**Comment by Josephblt** [comment]
Hello @LuboTerifaj. This is still missing some test coverage, but is ready for testing. Thanks.

**Comment by romartin** [comment]
Hey @hasys , would really appreciate yoru feedback here too, if you have some time... thanks!! :+1:

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins retest this

**Comment by hasys** [comment]
Hi @Josephblt,

great clean up thank you!

Sonar complains about missing branch coverage, all of it comes from Equals/HashCode methods. You actually already have tests for it: kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/HashCodeAndEqualityTest.java all you need is try to add non empty Data I/O and/or one/couple test with different Data I/O. I think it is good to have branch coverage and it shouldn't be difficult there.

Otherwise code looks good to me, I will do some End to End tests now, but I not expect issues there, just double check the full picture so you can add tests and work on builds. Thank you!

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by hasys** [comment]
Hi @Josephblt, @elguardian, @domhanak,

sending what I have on End to End test so far. I think it's better to continue investigations especially with Re-Usable sub-process, Conditional Events, Compensation event, Message Events as well as some addition work on community documentation is needed.

So far I found several potential blockers (can be handled as separate PRs and some of them can be moved to Known issues for 7.10):
## Potential Blockers
* **UI** if you set custom data i/o in End Error Event you will break the process.
* **Engine** Re-usable sub-process do not return any implicit data.
* **Engine** `event`implicit variable returns `null` for some nodes, but according to the jira issue it should be available for all Intermediate Catch Event types. See list below for more details.
* **Engine** I wasn't able to get stable working process with Boundary Intermediate Conditional Event

## Full notes
* Link event
  * **UI** shouldn't have Data IO at all (both Intermediate and Boundary). It doesn't work at runtime, and not planned.
* Timer event
  * **Engine** what `event` implicit variable returns? (it was java.lang.Long variable with value 7)
  * What random variable name returns? (it was java.lang.Long variable with value 13)
* Signal event
  * **Engine** `event` implicit variable returns `null`.
* Error event
  * **UI** if you set custom data i/o in End Error Event you will break the process. Just set up Data i/o, save and reopen the process. Probably it is because IntermediateErrorEventThrowing.java is missing [here](https://github.com/kiegroup/kie-wb-common/tree/a537b35f46445bdddd72576799f02c255e184a22/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition).
  * **Engine** Doesn't work on re-usable subprocess (I tested only Error on re-usable sub-process), only custom data is working
  * **Engine** `event` implicit variable returns `null`.
* Escalation event
  * **Engine** `event` implicit variable returns `null`.
* Message event
  * Only tested with most important `nodeInstance` implicit variable due to hard of automation.
    * To test start the process and send `Message-message1` as signal to trigger the Message Event. 
* Compensation event
  * `nodeInstance` implicit variable do not transfer data as expected
  * `signal` implicit variable get's not unique `Compensation` value
* Conditional event - needs more tests (!)
  * **Error** I am doing something wrong or Boundary Intermediate Conditional Event do not work, when I click on start process button, start new process dialogue is not closed. In the console log I can see correct output following by long error log.

**Comment by domhanak** [comment]
Jenkins run fdb

**Comment by romartin** [comment]
oh @hasys nice findings above!

I would vote for opening a ticket with all this information and reassign properly. WDYT?

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Review by hasys — APPROVED** [review]
After discussion PR looks good to me, will report issues as separate tasks. Thank you @Josephblt , good job!

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Review by domhanak — APPROVED** [review]
LGTM.

I was able to use these changes to properly implement use cases defined in https://issues.redhat.com/browse/JBPM-9411 engine requirement.
I can now add DataInput assignments for all throwing events using designer.
I can now add DataOutput assignments for all catching events using designer.

Issues discovered by @hasys were agreed to be handled as separate issues.

**Comment by romartin** [comment]
great, thanks guys, nice job!! :+1: 

@Josephblt @hasys plz if you see the CI builds completed and I didn't yet merged, ping me and I'll proceed with merge!

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Pull request merged**
