### PR TITLE
Project/Teams metrics dashboard fixes (7.3.x)

### PR DESCRIPTION
**Pull request by dgutierr**
@paulovmr Can you review & approve please. This is targeted for 7.0.0. LA => tomorrow EOD :-)

Thanx!

PS: depends on https://github.com/dashbuilder/dashbuilder/pull/378

### CODE REVIEW

**Comment by dgutierr** [comment]
@kkufova  Can you review & approve please?

**Comment by kkufova** [comment]
@dgutierr, the displayed time in the slider is a great fix, thanks! However, the pie charts still don't work; after clicking any part of any pie chart, nothing happens :-(

**Comment by dgutierr** [comment]
@kkufova  it should work now.

**Comment by kkufova** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
This will need to target 7.4.x (if any 7.x branch at all)

**Pull request closed without merging**
