### PR TITLE
AF-822: Fix null in error message when uploading non-existing file

### PR DESCRIPTION
**Pull request by tomasdavidorg**
https://github.com/AppFormer/uberfire/pull/901

### CODE REVIEW

**Comment by manstis** [comment]
@tomasdavidorg Approved, but I'd be interested in understanding why [this](https://github.com/AppFormer/uberfire/blob/f8f3737a854dc64f1075b076514c8630bf3da5f2/uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/editors/defaulteditor/DefaultEditorFileUploadBase.java#L90) is not called when a file is uploaded and the validation performed in the super-class.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@manstis I had a look and I am not sure what is the problem with the place you pointed. The method `isValid` seems to me as initializing the `FileUpload` widget, that seems to me appropriate for handling empty / not empty file name. Maybe the problem is that `FileUpload` combine both Presenter and View principles?

**Comment by manstis** [comment]
@jomarko Hi.. my issue was that ```DefaultEditorFileUploadBase.isValid()``` performs the ```null```/empty check on the filename and reports that a file has not been selected. This validation happens when the ```FORM``` is submitted. However this is not called until after ```NewFileUploader``` tries to extract the file extension from a ```null``` filename - which caused the NPE. So.... the fix seems OK now on reflection.

**Pull request merged**
