### PR TITLE
[DROOLS-3321] Add GWT feature to kie-wb-common-command-api

### PR DESCRIPTION
**Pull request by gitgabrio**
@kkufova @manstis @danielezonca 

Scope of this PR is to add "GWT" feature to the kie-wb-common-command-api

### CODE REVIEW

**Comment by gitgabrio** [comment]
jenkins please restart this

**Comment by manstis** [comment]
Jenkins please retest this.

^^ @gitgabrio It's "retest" not "restart".

**Comment by Rikkola** [comment]
The test is broken in master.

**Comment by gitgabrio** [comment]
Jenkins please retest this.

**Comment by gitgabrio** [comment]
@manstis 
Hi. Could you please merge this, squashing commits? Thanks!

**Pull request merged**
