### PR TITLE
JBPM-6165 enabling tab and shift+tab on numeric inputs

### PR DESCRIPTION
**Pull request by alessioscalici**
This changes enable using tab and shift+tab to switch form fields focus

@pefernan @jsoltes could you please have a look?

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@manstis could you please merge this?

**Pull request merged**
