### PR TITLE
[7.7.x] RHPAM-753 - Extend test coverage for Parallel & Exclusive & Inclusive gateways

### PR DESCRIPTION
**Pull request by domhanak**
cherry-picks #1543 and #1560 into 7.7.x

@romartin

### CODE REVIEW

**Comment by domhanak** [comment]
jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @domhanak @hasys , although it's just about tests, not sure if for merging into `7.7.x` you need a `RHBA` ticket, instead of the `JBPM` one, can you please confirm? @krisv do we need all cherry-picks be linked to `RHBA` tickets, or in that case (just tests) can we go ahead with the `JBPM`?

**Comment by domhanak** [comment]
jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @domhanak, @romartin,

I agree with both :) Tests should present in 7.7.x, but if we need RHBA jira issue to follow formal process, I guess it is not an issue as well. It is about several minutes to create it.

**Comment by krisv** [comment]
Normal process is indeed to clone it to an RHBA issue as well.  For test only changes you don't need to request the acks (but since we don't yet require acks at this point anyway it's not a difference).

**Comment by romartin** [comment]
So please @domhanak , you should create a RHBA ticket and then change this PR title and the commit message as well (it still references the JBPM ticket). Thanks!

**Comment by domhanak** [comment]
@romartin I am on it :)

**Comment by domhanak** [comment]
@romartin I did change the name and commit messages - jira is RHPAM-753 and now this PR also cherry picks #1560 as it is part of the JBPM-7092

**Comment by domhanak** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
@romartin So the failures are related to new marshaller bug that was already fixed by @evacchi but that will not be ported to 7.7.x branch. Am I correct? Let me know, if yes I am going to Ignore the part that tests the new marshaller

**Comment by evacchi** [comment]
```
org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=0, size=0
	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:352)
	at org.kie.workbench.common.stunner.bpmn.backend.converters.tostunner.DefinitionResolver.findPlane(DefinitionResolver.java:160)
	at org.kie.workbench.common.stunner.bpmn.backend.converters.tostunner.DefinitionResolver.<init>(DefinitionResolver.java:67)
	at org.kie.workbench.common.stunner.bpmn.backend.BPMNDirectDiagramMarshaller.unmarshall(BPMNDirectDiagramMarshaller.java:136)
``

@domhanak yes most probably same issue

**Comment by domhanak** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
Jenkins execute full downstream build

**Pull request merged**
