### PR TITLE
[7.7.x] RHPAM-1104: Stunner - 'Task name' is for internal use and mustn't be editable for ServiceTasks

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi @romartin @hasys let's this PR build, etc., and have this prepared just in case there are time for any last moment cherry-pick into the 7.0.0.GA.

**Comment by wmedvede** [comment]
well, to late to get this into the 7.0.0, but let's keep this to merge it in as soon we get the green light for starting the 7.0.1

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
Hello @hasys @romartin , I believe this PR is not  "temporal" any more and we would like to have this in for the upcoming 7.0.1.
@romartin would you mind take a look? (@hasys has already approved)
Thanks.

**Comment by romartin** [comment]
Hey @krisv 
I think to get this merged it's missing some ACK here -> https://issues.jboss.org/browse/RHPAM-1104, the `devel` one, is it? Can you set it please? Thx

**Pull request merged**
