### PR TITLE
JBPM-5724: Empty rectangle added to canvas after hitting Esc in the Component Editor.

### PR DESCRIPTION
**Pull request by pefernan**
@jsoltes @manstis could you review?

### CODE REVIEW

**Comment by jsoltes** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins execute full downstream build. If the only failures are the known REST tests in ```kie-wb-distributions``` this can be merged after @jsoltes has approved.

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
jenkins execute full downstream build

**Pull request merged**
