### PR TITLE
DROOLS-5197,5744 - DMN Enumeration constraint editor small enhancements

### PR DESCRIPTION
**Pull request by jomarko**
As part of this PR we:
- prevent user from defining same enumeration item multiple times: https://issues.redhat.com/browse/DROOLS-5197
- commit all enumeration items in edit mode by click on single checkbox: https://issues.redhat.com/browse/DROOLS-5744

**Thank you for submitting this pull request**

**JIRA**: [DROOLS-5197](https://issues.redhat.com/browse/DROOLS-5197)
**JIRA**: [DROOLS-5744](https://issues.redhat.com/browse/DROOLS-5744)

**Referenced Pull Requests**:
* backport of https://github.com/kiegroup/kogito-editors-java/pull/169

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Review by yesamer — APPROVED** [review]
@jomarko thank you

**Comment by jomarko** [comment]
Jenkins do fdb

**Review by barboras7 — APPROVED** [review]
Looks good, thank you @jomarko

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
