### PR TITLE
Adding missing deps to fix the stunner showcases

### PR DESCRIPTION
**Pull request by pefernan**
@manstis @barboras7 @wmedvede @romartin 
This fixes the deps issues on the stunner showcases

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by wmedvede** [comment]
Hello @pefernan , It looks like @tiagodolphine  faced this issue in the stunner-standalone-showcase too.
Could you please apply the fix there too?
Thanks!

**Comment by manstis** [comment]
@wmedvede This PR fixes both (I checked both earlier before approving this PR).

**Comment by pefernan** [comment]
@manstis @wmedvede yes, it fixes both errors :)

**Comment by tiagodolphine** [comment]
@wmedvede yes I faced issues running stunner showcases and my local fix was exactly this one @pefernan sent on the PR.
Thanks

**Pull request merged**
