### PR TITLE
JBPM-9853 : Text Annotation causes ERROR: Attribute 'name' is not allowed to appear in element 'bpmn2:textAnnotation'

### PR DESCRIPTION
**Pull request by inodeman**
**Thank you for submitting this pull request**

**JIRA**: [JBPM-9853](https://issues.redhat.com/browse/JBPM-9853)

**Referenced Pull Requests**:
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://drive.google.com/drive/folders/1n6N-OrrZzGU_z1Sg5UaHEc-yYLmL9Uwz?usp=sharing)

**VS Code**: [plugin](https://donwnload.here/something)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by inodeman** [comment]
Hi @romartin can you review this PR? Will upload war shortly after build finishes

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by inodeman** [comment]
War file can be found here. https://drive.google.com/drive/folders/1n6N-OrrZzGU_z1Sg5UaHEc-yYLmL9Uwz?usp=sharing

**Comment by romartin** [comment]
Thanks for the PR @inodeman . See my comment in the ticket, I understand we also shoud PR this for the kogito stream. Does it makes sense to you guys?
BTW @handreyrc @LuboTerifaj assigning to you the review guys. Thx!

**Comment by handreyrc** [comment]
Hey @inodeman great job! 

I agree with @romartin, in my opinion it is applicable to kogito editors as well. 
Just let me know if we will handle this in a new JIRA and we can move forward with this PR.

Thanks for your work here.

**Comment by inodeman** [comment]
Hi @handreyrc will do, after this gets merged, I will create another PR for the other repo

**Comment by romartin** [comment]
@handreyrc @LuboTerifaj please guys, review necessary here, deadline is this week.

**Comment by LuboTerifaj** [comment]
Hello @inodeman , @romartin I am looking at the issue. Thanks!

**Review by handreyrc — APPROVED** [review]
Thanks @inodeman!

**Comment by romartin** [comment]
ok thanks @LuboTerifaj , please remember the deadline for this is this week, so early feedback will be appreciated

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @inodeman ,

There are error messages in server.log for many cases. For example, create a process Start event -> User task -> End event that contains Text Annotation. 
```
[org.drools.core.xml.ExtensibleXmlParser] (Thread-127) Process Info: id:proj.proc, pkg:com.myspace.proj, name:proc, version:1.0 
Node Info: id:_4084A1BC-5DE9-4976-856A-2B581042F90D name:
Parser message: (null: 93, 66): cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.omg.org/spec/BPMN/20100524/MODEL":endEvent}'. One of '{"http://www.omg.org/spec/BPMN/20100524/MODEL":artifact}' is expected.
```

Would it be also possible to add some test cases for the bug fix?

Thank you!

**Comment by inodeman** [comment]
Hi @LuboTerifaj server log messages should be analized further, I will look at them but I think they should be reported on another ticket. I added code to verify we are not setting the name now on a test case. Will upload War when build finishes

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by inodeman** [comment]
Hi @LuboTerifaj War file can be found here. https://drive.google.com/drive/folders/1n6N-OrrZzGU_z1Sg5UaHEc-yYLmL9Uwz?usp=sharing

**Comment by LuboTerifaj** [comment]
Hello @inodeman , the war is missing in drive you have linked above. FDB doesn't contain war either. Could you please upload it? Thank you!

**Comment by inodeman** [comment]
Hi @LuboTerifaj sorry, seems it got stuck, it is uploaded now

**Comment by LuboTerifaj** [comment]
Hello @inodeman , @romartin , 

I just checked the behaviour on the latest 7.59.0 snapshot and I couldn't have reproduced the issue described in the jira. I have also tried to create a process from scratch and the error message was not shown in server.log when I clicked the validate button.

However, the error message described in jira is there when you import the project. The error messages I mentioned in my previous [comment](https://github.com/kiegroup/kie-wb-common/pull/3669#pullrequestreview-733070752) are also in server.log, but they are shown when you click on validate button.

I built the business-central war locally, but I am not sure the changes from this PR got in since the behaviour was the same as in the snapshot.

First of all, we need to clarify the scope of the bug fix in the jira since there are two issues as I already described:

- error messages in server.log after importing the project
- error messages after validation (clicking on validate button or save the process)

Afterwards, we can check if this PR fulfills the expected result from the jira. Once the jira description is clear and the PR is ready, please don't forget to upload the business-central war in case it is not already archived in FDB.

Thank you!

**Comment by inodeman** [comment]
Hi @LuboTerifaj War is uploaded now to here. https://drive.google.com/drive/folders/1n6N-OrrZzGU_z1Sg5UaHEc-yYLmL9Uwz?usp=sharing

**Comment by inodeman** [comment]
jenkins retest this

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by LuboTerifaj** [comment]
Hello @inodeman , @romartin ,

neither error messages on import nor error messages on validation are fixed as I already described in my previous [comment](https://github.com/kiegroup/kie-wb-common/pull/3669#issuecomment-902045186).

I cannot approve the pull-request.

**Comment by inodeman** [comment]
Hi @LuboTerifaj as mentioned before, you wont see any changes when importing since the project was created before the change it does contain the name attribute. The only change this PR did is, if you create a new process it dont generate the name attribute and you wont see the error message. As to your message that the main branch does not contain the error, I checked another build that was based on the main branch and the error does happen, are you sure the build you mention is from the main branch? If so, if you could send it to me, I will verify

**Comment by inodeman** [comment]
Hi @LuboTerifaj  just tested the War I uploaded, I can verify error log still shows, but XML does not contain the name attribute, I will research why that is.

**Comment by LuboTerifaj** [comment]
@inodeman great, please let me know once it is ready to review again. Thanks!

**Comment by LuboTerifaj** [comment]
Hello @inodeman , as we discussed on the meeting, I have updated the expected result in the jira. Please let me know when the PR is ready to test. Thank you!

**Comment by inodeman** [comment]
Hi @LuboTerifaj @romartin even after my change that does not save the name attribute the error still coming from Drools class, I have debugged it and the class throwing the exception does not get an incorrect XML, so not sure how to fix it. I will keep trying but so far have not succeed

**Comment by mareknovotny** [comment]
any progress on this? @inodeman @LuboTerifaj ?

**Comment by inodeman** [comment]
Hi @mareknovotny, we agreed with @romartin that we should not work on this further. This PR fixes the issue that is: It now does not save the name attribute, but somehow the error message is still showing, to fix it would mean fixing a class from Drools.

**Comment by hasys** [comment]
> Hello @inodeman , as we discussed on the meeting, I have updated the expected result in the jira. Please let me know when the PR is ready to test. Thank you!

@LuboTerifaj, @inodeman,

if I correct this PR wasn't and won't be changed any further so it is ready to go, right?

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @hasys ,

the issue is not fixed. See https://github.com/kiegroup/kie-wb-common/pull/3669#issuecomment-902045186, https://github.com/kiegroup/kie-wb-common/pull/3669#issuecomment-903707075 and other comments above.

Thanks!

**Comment by hasys** [comment]
Wasn't there an agreement to move Drools related changes to separate PR? I thought it is what this comment is about: https://github.com/kiegroup/kie-wb-common/pull/3669#issuecomment-908440422 isn't it? Or I misunderstood something on the meeting?

**Comment by LuboTerifaj** [comment]
Hello @hasys , yes, I have created a separate jira for that: [JBPM-9876](https://issues.redhat.com/browse/JBPM-9876). However the issue [JBPM-9853](https://issues.redhat.com/browse/JBPM-9853) is not fixed either.

**Comment by hasys** [comment]
@inodeman, @LuboTerifaj,

if issue with incorrect XML on Stunner side was fixed and now we are dealing with Drools backend part, I suggest to merge this PR and report issue to Drools.

Acceptance Criteria/Expected Result should be changed from not produce error to Designer produce BPMN 2.0 valid XML for annotations since issue is on Drools Backend which is our of control of BPMN Designer.

Does it make sense?

**Comment by inodeman** [comment]
> @inodeman, @LuboTerifaj,
> 
> if issue with incorrect XML on Stunner side was fixed and now we are dealing with Drools backend part, I suggest to merge this PR and report issue to Drools.
> 
> Acceptance Criteria/Expected Result should be changed from not produce error to Designer produce BPMN 2.0 valid XML for annotations since issue is on Drools Backend which is our of control of BPMN Designer.
> 
> Does it make sense?

Hi @hasys totally agree with you, what do you think @LuboTerifaj ?

**Comment by LuboTerifaj** [comment]
Hello @inodeman , @hasys , the issue has been already closed. Feel free to open a separate issue for incorrect XML. Thanks!

**Pull request closed without merging**
