### PR TITLE
[GUVNOR-2996]: Artifact Repository Preferences added

### PR DESCRIPTION
**Pull request by adrielparedes**
Artifact Repository Preferences added into menu

Depends on: https://github.com/kiegroup/guvnor/pull/447

### CODE REVIEW

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by manstis** [comment]
@karreiro @adrielparedes Please advise when this can be merged.

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by adrielparedes** [comment]
@manstis @ederign @karreiro conflicts merged

**Pull request merged**
