### PR TITLE
JBPM-6594: Stunner - StartNoneEvent, IsInterrupting attribute, and data output don't apply

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin  @hasys , would you mind review this PR?
Thanks.

**Comment by wmedvede** [comment]
this were the errors

org.kie.workbench.common.services.backend.compiler.nio.kie.KieDefaultMavenCompilerTest.buildWithJGitDecoratorTest:

org.uberfire.java.nio.IOException: java.io.IOException: Failed to open server socket for /127.0.0.1:9418
	at java.net.PlainSocketImpl.socketBind(Native Method)

org.kie.workbench.common.services.backend.compiler.nio.kie.KieDefaultMavenCompilerTest.buildWithPullRebaseUberfireTest

org.uberfire.java.nio.IOException: java.io.IOException: Failed to open server socket for /127.0.0.1:9418
	at java.net.PlainSocketImpl.socketBind(Native Method)

**Comment by wmedvede** [comment]
let's give it another try

jenkins retest this

**Comment by romartin** [comment]
jenkins execute full downstream build

**Pull request merged**
