### PR TITLE
[8.0.x] JBPM-6283: Changing binding in the fields resets all properties to default values.

### PR DESCRIPTION
**Pull request by pefernan**
@jsoltes could you review it?

### CODE REVIEW

**Comment by jsoltes** [comment]
@pefernan can you please fix the conflicts?

**Comment by pefernan** [comment]
@jsoltes done

**Comment by pefernan** [comment]
@jsoltes review again

**Comment by pefernan** [comment]
@hasys could you review?

**Comment by manstis** [comment]
Waiting on @hasys

**Pull request merged**
