### PR TITLE
JBPM-7936: palette structure - just one hierarchy level degree

### PR DESCRIPTION
**Pull request by xiezhang7**

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by manstis** [comment]
Ok to test.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @mareknovotny, another green full downstream without war files.

**Comment by xiezhang7** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@hasys just as a reminder - this is ready for review. Thanks!!

**Comment by romartin** [comment]
@xiezhang7 @LuboTerifaj artifacts are generated, let's try to move this forward please.. :+1:  Thanks guys!

**Comment by romartin** [comment]
Jenkins retest this

**Comment by xiezhang7** [comment]
Hi @LuboTerifaj ,

I have tested the war for wildfly14. Case modeler is an experimental feature which is not enabled by default.

1. Please set property “appformer.experimental.features=true” when start the server. 
See [Case modeler as experimental feature](https://docs.google.com/document/d/1xt01Ku3sMZ9xssO0ZvMPPmII2M_Sz4pD1l0nKvqv4Vk/edit)

2. Please enable "case modeler" as an experimental feature:
"Settings" -> "Experimental" -> enable "Case Management Editor (Preview)" and "Case Management Resource Type (Preview)"

3. Create asset of "Case Management (Preview)".

In terms of "Case definition", I don't really know what it is. I guess it is an unrelated feature.

Thanks.

**Comment by LuboTerifaj** [comment]
Hello @xiezhang7 

yeah, I didn't realize it, that I need to enable experimental feature.

Regarding to case definitions, it must be caused by this PR, since the issue is not present on master.

Can you have a look?

Otherwise, it looks good.

Thanks.

**Comment by xiezhang7** [comment]
Hi @LuboTerifaj ,

I tested with [business-central-webapp-7.15.0-20181128.073433-62.war](https://repository.jboss.org/nexus/content/groups/public/org/kie/business-central-webapp/7.15.0-SNAPSHOT/business-central-webapp-7.15.0-20181128.073433-62.war) and [business-central-webapp-7.16.0-20181123.204428-1.war](https://repository.jboss.org/nexus/content/groups/public/org/kie/business-central-webapp/7.16.0-SNAPSHOT/business-central-webapp-7.16.0-20181123.204428-1.war) which are not related to this pull request. 
In both cases, experimental features framework is not enabled (i.e. without property “appformer.experimental.features=true”). 
The issue you mentioned can be reproduced in both cases. There are two "Case definition (legacy)" assets. But there are no assets with name "Case definition".
 
In this pull request, only one java class which is for palette is changed. I don't think it has anything to do with other assets. 

I guess the code that generates the assets is from appformer, so I am not sure what caused this issue. 
@romartin @pefernan do you have any idea what could cause this issue?

Thanks.

**Comment by romartin** [comment]
Hey @xiezhang7  @LuboTerifaj 

So the issue is that the assets appear twice?? if so, TBH I don't know the reason... but @xiezhang7  is right when saying that this PR only changes the palette, has nothing to do with the assets themselves...so I would propose to open a tnew ticket for master branmch if that issue persists, and try to move this one about the palette forward anyway.

**Comment by romartin** [comment]
The full build is not yet ready, let's try again.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Pull request merged**
