### PR TITLE
KOGITO-3696: DMN Editor regression failing display edge when xml missing DMNDI

### PR DESCRIPTION
**Pull request by karreiro**
**JIRA**: [KOGITO-3696](https://issues.redhat.com/browse/KOGITO-3696): DMN Editor regression failing display edge when xml missing DMNDI

**VS Code**: [plugin](https://www.dropbox.com/s/x1vsvyzlommqd3d/plugin-KOGITO-3696.vsix?dl=0)

**Asset to test the PR**: [canDrink.dmn](https://issues.redhat.com/secure/attachment/12500383/canDrink.dmn)

Screen Shot 2020-11-06 at 01 39 37

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Review by vpellegrino — APPROVED** [review]
LGTM, good job @karreiro

**Review by danielzhe — APPROVED** [review]

**Pull request merged**
