### PR TITLE
[JBPM-8727] Analyze and fix unit tests that related to server controller

### PR DESCRIPTION
**Pull request by elguardian**
resolving artifact through maven build instead aether

### CODE REVIEW

**Comment by elguardian** [comment]
Jenkins this is ok to test.

**Comment by elguardian** [comment]
@ohonchar this should fix the test. don't know if the other artifact generated by aether would need the same strategy though

**Comment by ohonchar** [comment]
Tested, all tests in `kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend` passed

**Comment by elguardian** [comment]
@ohonchar anyprogress with the review of this one ?

**Comment by ohonchar** [comment]
> @ohonchar anyprogress with the review of this one ?

@elguardian tested, approve from my side

**Comment by ohonchar** [comment]
@cristianonicolai could u please review this. Thnx

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
@elguardian sorry for the late reply, this PR probably needs rebasing now. Overall looks good to me, just waiting for a green build.

**Comment by elguardian** [comment]
@cristianonicolai seems ok to me. not needed to rebase

**Pull request merged**
