### PR TITLE
KOGITO-841: Documentation Links popup is not readable in DMN VS Code Extension

### PR DESCRIPTION
**Pull request by danielzhe**
This fix also will impact all popups, which I think it is a good thing.

### CODE REVIEW

**Comment by danielzhe** [comment]
I noticed that `AbstractPopoverViewImpl` doesn't have any test at all. Do you think I should cover the class with new tests? I think this class will be deprecated soon since it uses deprecated `org.jboss.errai.common.client.dom.Div`, so I didn't do it because I don't know if this effort is valid now. @manstis

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by danielzhe** [comment]
@manstis I decided to make the test for `AbstractPopoverViewImpl` with a small refactor, since  `NameAndUrlPopoverViewImplTest.testShow()` would required some refactors too, since it calls `superShow()` and we don't have access to the options there.

**Comment by jomarko** [comment]
### Manual tests
- [ ] Firefox
- [ ] Chrome
- [ ] VS Code

**Pull request merged**
