### PR TITLE
[AF-2058] Fixing the OpenShift client API compatibility issue after upgraded io.fabric8 kubernetes client to 4.6.0

### PR DESCRIPTION
**Pull request by rhtevan**
Followed by the original PR for [AF-2058] Provide alternative implementation of uberfire-nio2-impls b…acked by OCP/K8S

Signed-off-by: Evan Zhang <evan.zhang@redhat.com>

### CODE REVIEW

**Comment by kie-ci9** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by mareknovotny** [comment]
ok to test

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
@ederign Can you please take a look?

**Pull request merged**
