### PR TITLE
DROOLS-3895: [DMN Designer] TextAreas can no longer be multi-line

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-3895

Part of an ensemble:

- https://github.com/kiegroup/appformer/pull/684
- https://github.com/kiegroup/kie-wb-common/pull/2615

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by manstis** [comment]
Yay @karreiro the fix works then :-)

Without these PRs you CANNOT have multi-linr text in a `TextArea` as pressing `<Enter>` flushes the content and exits _edit_ mode.

**Comment by manstis** [comment]
Hi @jomarko Good spot regarding the Decision Table's `Description` column.

The reason was that it did not use a "line-break" word wrapper. I have however changed the `Description` column to use the same formatting as the both the `InputClause` and `OutputClause` columns. Which is also now consistent with every other place we use a `TextAreaSingletonDOMElementFactory` (i.e. "in-cell `TextArea` editor).

**Comment by jomarko** [comment]
@manstis thank you for changes, I am not going to re-review.

**Pull request merged**
