### PR TITLE
[7.7.x] RHPAM-790: Stunner - Cancel Activity doesn't persist after save process

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin @hasys would you mind review this PR?
Thanks.

NOTE: as we discussed with  @romartin optimal solution is not possible to be implemented with the time being for the 7.0.1, and likely nor for the 7.0.2. But the implemented solution is still good with the alternatives we have right not.
The following https://issues.jboss.org/browse/RHPAM-790 was opened for tracking/implementing the "optimal" solution.

Current solution "shows" and "hides" the CancelActivity" attribute based on the "context"
See screenshots below.

cancellingdocked

cancellingnotdocked

**Comment by wmedvede** [comment]
@romartin would you mind take a look in case there are any missing Aks https://issues.jboss.org/browse/RHPAM-790.

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by wmedvede** [comment]
*) first build failed due to "Build timed out"
*) full downstream was o "ok".
I think we can go ahead with just the downstream == green for doing review and merge.
Thanks.

**Comment by romartin** [comment]
missing @hasys review sorry

**Comment by hasys** [comment]
Hi @jsoltes,

can you take a look?

**Comment by jsoltes** [comment]
@hasys I will try.

**Comment by romartin** [comment]
Jenkins please retest this

**Pull request merged**
