### PR TITLE
[7.3.x] JBPM-6104: Stunner - not possible to remove container with not empty container inside

### PR DESCRIPTION
**Pull request by alepintus**
@romartin Cherry pick from https://github.com/kiegroup/kie-wb-common/pull/1122

### CODE REVIEW

**Comment by romartin** [comment]
ok to test

**Comment by manstis** [comment]
@hasys I assume you want to review this too.

**Comment by romartin** [comment]
CC @manstis  well that's just the cherry-pick... was approved on master already

**Comment by romartin** [comment]
@manstis @hasys anyway for me,as more people can test it again much better :)

**Comment by manstis** [comment]
@hasys Did you want to approve cherry-picks too?

**Comment by romartin** [comment]
Yes please @hasys , let's try to close tasks otherwise this never ends....  thanks!

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
@hasys  please we need this merged asap! It's a critical issue for next LA release. Can you do the review?

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
@hasys please we need this merged asap, can you please do the review? Thanks!

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin, @alepintus, sorry for the delay. Works good, thank you!

**Comment by romartin** [comment]
@hasys missing to click on `approve`! :)

**Comment by romartin** [comment]
@hasys :+1:

**Pull request merged**
