### PR TITLE
JBPM-8925 - Users do not understand how to add nodes to the diagram

### PR DESCRIPTION
**Pull request by Josephblt**
https://issues.jboss.org/browse/JBPM-8925

Added Screen with hint on how to start.
Added tooltips with hints on how to proceed.
All editors start as a blank/empty canvas.
Suuport custom messages for each editor.
Supported editors are BPMN, DMN, CM-CD.

Old Video:
https://drive.google.com/open?id=13aj65YdVV8ERln4kyDjB48iy4CGCvNzs

**Video for the final implementaion (Business Process / Case Definition / Case Management Preview):
https://drive.google.com/file/d/1kO6kBOFd1gGWx-AtHpl9mN-qmBF4lst4/view?usp=sharing**

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by LuboTerifaj** [comment]
@Josephblt 

fyi, once #3012 will be merged, dragging from the toolbox menu should work.

**Comment by bdellasc** [comment]
Is there any way to see how the implementation will render before I approve? Looking back at the last video that @romartin posted on November 9 (https://issues.jboss.org/browse/RHPAM-2318), I have concerns about how the empty state (before any nodes are added to the canvas) is rendered as large outlined text. Has this since been aligned to the Marvel mockup?

**Comment by lclay2** [comment]
@LuboTerifaj @romartin, Could you please post a video or gif of the implemented updates that @bdellasc designed, [Marvel mockup](https://marvelapp.com/9ca3e3d/screen/62342328), so he can review the PR. We understand that the tooltip changes will not get implemented, but want to verify the inclusion of the other elements. Thanks!

**Comment by Josephblt** [comment]
Hello @lclay2 @bdellasc. Yes I uploaded the video with the final implementation. Mind there are no tooltips. And @bdellasc that video @romartin posted wasn't really accurate. It was just to show me what his implementation was all about. Consider the video in the PR description please. Thanks guys. Sorry for delay, it took me a while to see the comments.

**Comment by manstis** [comment]
@jomarko Did you want to check from a DMN perspective?

**Comment by bdellasc** [comment]
> https://drive.google.com/file/d/13aj65YdVV8ERln4kyDjB48iy4CGCvNzs/view?usp=sharing

Looks great! Thanks for adding the video. I'll approve it now.

**Comment by Josephblt** [comment]
Hello @LuboTerifaj, @romartin, @bdellasc, @jomarko. I updated the PR there are still code changes pending and the tests. But the functionality is ready to test.

Removed the tooltip functionality. 

Differentiating Case Definition and BPMN Definition on code is not possible at the moment. There are some options to do this, but they are all somewhat risky to implement at this point. So instead of adding an unfinished/buggy feature I decided to keep the same message for all editors ([See result in this video](https://drive.google.com/file/d/1kO6kBOFd1gGWx-AtHpl9mN-qmBF4lst4/view?usp=sharing**)). Yes we can change those to custom ones in the future, I kept the code there.

Fixed the Case Definition. Before I updated the PR the Ad-Hoc property on the diagram level was not checked.

So please guys if you could check for the functionality that would be great.

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Hello @LuboTerifaj, @romartin, @bdellasc, @jomarko. Ready to test. We are a little short on tests, but I don't think there is time. Ready to test.

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
hey @jomarko , missing your final review here, this is already merged on 7.30.x branch so we're interested also on merging here, in master, in otder to have samecodebase ASAP.
Can you please provide some feedback?
Thanks!

**Pull request merged**
