### PR TITLE
RHPAM-2432 it is possible to break process by setting incorrect called element

### PR DESCRIPTION
**Pull request by hasys**
To test this PR I used `testProject.processName~!@#$%^&*()+``-={}[]:"|;'\<>?,./_` and full business central build. Works to me now.

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by kie-ci10** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by manstis** [comment]
ok to test

**Comment by hasys** [comment]
Hi @manstis, @mareknovotny, am I missed some changes in our workflow or why it is needed "ok to test" for my PRs? I checked KIE Group groups and I am in developers group there.

**Comment by mareknovotny** [comment]
there is no change in the workflow. it seems this now started. We know at least about one additional one so @mbiarnes will look at it

**Comment by hasys** [comment]
Tested with VS Code as well. 
Called element is set and process reopened:
obrazek

**Comment by hasys** [comment]
Hi @rsynek,

Full Downstream Build failed due to Optaplanner Web tests. Is it broken master or random fail and just rerun should be enough?

<details>
  <summary>Click to expand</summary>
  <pre>13:34:27 Xvfb exited with a non zero exit code.
13:34:27 
13:34:27 There was a problem spawning Xvfb.
13:34:27 
13:34:27 This is likely a problem with your system, permissions, or installation of Xvfb.
13:34:27 
13:34:27 ----------
13:34:27 
13:34:27 Error: _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
13:34:27 _XSERVTransMakeAllCOTSServerListeners: server already running
13:34:27 (EE) 
13:34:27 Fatal server error:
13:34:27 (EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
13:34:27 
13:34:27 ----------
13:34:27 
13:34:27 Platform: linux (Debian - 9.9)
13:34:27 Cypress Version: 3.6.0
13:34:27 [ERROR] Command execution failed.
13:34:27 org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
13:34:27     at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
13:34:27     at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
13:34:27     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:764)
13:34:27     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:711)
13:34:27     at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:289)
13:34:27     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
13:34:27     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
13:34:27     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
13:34:27     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
13:34:27     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
13:34:27     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
13:34:27     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
13:34:27     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
13:34:27     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
13:34:27     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
13:34:27     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
13:34:27     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
13:34:27     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
13:34:27     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
13:34:27     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
13:34:27     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
13:34:27     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
13:34:27     at java.lang.reflect.Method.invoke (Method.java:498)
13:34:27     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
13:34:27     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
13:34:27     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
13:34:27     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
13:34:27 [INFO] 
13:34:27 [INFO] ------------------------------------------------------------------------
13:34:27 [INFO] Skipping OptaWeb Employee Rostering as a Service Distribution
13:34:27 [INFO] This project has been banned from the build due to previous failures.
13:34:27 [INFO] ------------------------------------------------------------------------
13:34:27 [INFO] ------------------------------------------------------------------------
13:34:27 [INFO] Reactor Summary:
13:34:27 [INFO] 
13:34:27 [INFO] OptaWeb Employee Rostering as a Service Parent ..... SUCCESS [  3.255 s]
13:34:27 [INFO] OptaWeb Employee Rostering as a Service React Frontend SUCCESS [04:06 min]
13:34:27 [INFO] OptaWeb Employee Rostering as a Service Spring Boot Backend SUCCESS [01:18 min]
13:34:27 [INFO] OptaWeb Employee Rostering as a Service Benchmark .. SUCCESS [01:53 min]
13:34:27 [INFO] OptaWeb Employee Rostering as a Service Documentation SUCCESS [ 14.959 s]
13:34:27 [INFO] OptaWeb Employee Rostering as a Service Standalone . FAILURE [01:01 min]
13:34:27 [INFO] OptaWeb Employee Rostering as a Service Distribution SKIPPED
13:34:27 [INFO] ------------------------------------------------------------------------
13:34:27 [INFO] BUILD FAILURE
13:34:27 [INFO] ------------------------------------------------------------------------
13:34:27 [INFO] Total time: 08:38 min
13:34:27 [INFO] Finished at: 2020-04-14T09:35:38-04:00
13:34:28 [INFO] Final Memory: 216M/1855M
13:34:28 [INFO] ------------------------------------------------------------------------
13:34:28 [WARNING] The requested profile "business-central" could not be activated because it does not exist.
13:34:28 [WARNING] The requested profile "wildfly" could not be activated because it does not exist.
13:34:28 [WARNING] The requested profile "sourcemaps" could not be activated because it does not exist.
13:34:28 [WARNING] The requested profile "no-showcase" could not be activated because it does not exist.
13:34:28 [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (run-cypress-tests) on project optaweb-employee-rostering-standalone: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
13:34:28 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (run-cypress-tests) on project optaweb-employee-rostering-standalone: Command execution failed.
13:34:28     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
13:34:28     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
13:34:28     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
13:34:28     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
13:34:28     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
13:34:28     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
13:34:28     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
13:34:28     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
13:34:28     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
13:34:28     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
13:34:28     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
13:34:28     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
13:34:28     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
13:34:28     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
13:34:28     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
13:34:28     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
13:34:28     at java.lang.reflect.Method.invoke (Method.java:498)
13:34:28     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
13:34:28     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
13:34:28     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
13:34:28     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
13:34:28 Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
13:34:28     at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:302)
13:34:28     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
13:34:28     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
13:34:28     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
13:34:28     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
13:34:28     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
13:34:28     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
13:34:28     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
13:34:28     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
13:34:28     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
13:34:28     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
13:34:28     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
13:34:28     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
13:34:28     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
13:34:28     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
13:34:28     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
13:34:28     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
13:34:28     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
13:34:28     at java.lang.reflect.Method.invoke (Method.java:498)
13:34:28     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
13:34:28     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
13:34:28     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
13:34:28     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
13:34:28 Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
13:34:28     at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
13:34:28     at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
13:34:28     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:764)
13:34:28     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:711)
13:34:28     at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:289)
13:34:28     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
13:34:28     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
13:34:28     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
13:34:28     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
13:34:28     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
13:34:28     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
13:34:28     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
13:34:28     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
13:34:28     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
13:34:28     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
13:34:28     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
13:34:28     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
13:34:28     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
13:34:28     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
13:34:28     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
13:34:28     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
13:34:28     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
13:34:28     at java.lang.reflect.Method.invoke (Method.java:498)
13:34:28     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
13:34:28     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
13:34:28     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
13:34:28     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
13:34:28 [ERROR] 
13:34:28 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
13:34:28 [ERROR] 
13:34:28 [ERROR] For more information about the errors and possible solutions, please read the following articles:
13:34:28 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
13:34:28 [ERROR] 
13:34:28 [ERROR] After correcting the problems, you can resume the build with the command
13:34:28 [ERROR]   mvn <goals> -rf :optaweb-employee-rostering-standalone
13:34:28 [INFO] Stopping all processes ...
13:34:28 [INFO] Stopping process: Run application
13:34:28 [INFO] Stopped process: Run application
13:34:28 Unexpected error while executing the Downstream repositories builder for PR builds! Error while executing Maven process, non-zero exit code!
13:34:28 java.lang.RuntimeException: Error while executing Maven process, non-zero exit code!
13:34:28 	at org.kie.jenkinsci.plugins.kieprbuildshelper.MavenProject.build(MavenProject.java:68)
13:34:28 	at org.kie.jenkinsci.plugins.kieprbuildshelper.AbstractPRBuilder.perform(AbstractPRBuilder.java:115)
13:34:28 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
13:34:28 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
13:34:28 	at hudson.model.Build$BuildExecution.build(Build.java:206)
13:34:28 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
13:34:28 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
13:34:28 	at hudson.model.Run.execute(Run.java:1810)
13:34:28 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
13:34:28 	at hudson.model.ResourceController.execute(ResourceController.java:97)
13:34:28 	at hudson.model.Executor.run(Executor.java:429)
13:34:28 Build step 'Build dependent downstream repositories (for PR builds)' marked build as failure
13:34:28 Terminating xvnc.
13:34:28 $ vncserver -kill :99
13:34:28 Killing Xvnc process ID 10242
13:34:30 Recording test results
13:34:38 Skipping publisher since build result is FAILURE
13:34:38 Skipping publisher since build result is FAILURE
13:34:38 Archiving artifacts
13:34:58 Adding one-line test results to commit status...
13:34:58 Setting status of 1983c304f3a6c6bacad2e635a95f6a0c445914a0 to FAILURE with url https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-common-downstream-pullrequests/1157/ and message: 'Build finished. 6975 tests run, 10 skipped, 0 failed.'
13:34:58 Using context: Linux - full downstream
13:34:58 [WS-CLEANUP] Deleting project workspace...
13:34:58 [WS-CLEANUP] Deferred wipeout is used...
13:34:58 [WS-CLEANUP] done
13:34:58 Finished: FAILURE</pre>
</details>

**Comment by rsynek** [comment]
@hasys from the error message it looks like an issue in the docker container. Never seen this before nor am aware of any change; we use the same version of the Cypress docker image since the Cypress UI tests were introduced. The build before and the build after passed (including the Cypress test). I wonder if there can be some kind of clash between `vncserver` running on the host and `xvfb` running inside the Cypress container.

**Comment by hasys** [comment]
Ok thank you @rsynek will try to restart Full Downstream Build.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by rsynek** [comment]
@hasys if it ever happens again, please let me know and I will investigate further and try to fix it.

**Comment by hasys** [comment]
Hi @LuboTerifaj,

great findings. But I tested master branch and can reproduce it as well. If it is not a regression and not part of the Jira's acceptance criteria, why should we fix it in this PR?

**Comment by hasys** [comment]
Great job, thank you @LuboTerifaj!

@romartin your turn. Red `Linux - full downstream (new)` is an experiment and can be ignored for now, see regular `Linux - full downstream` is green. Thank you!

**Comment by romartin** [comment]
hey @hasys , code looks good! Could it be possible to include or update some existing test for this?

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin, all is green and we can proceed with merging.
image

**full doewnstream (new)** is experimental and can be ignored for now. Thank you!

**Pull request merged**
