### PR TITLE
JBPM-9502: Stunner - Unexpected system error when deleting any node on canvas

### PR DESCRIPTION
**Pull request by danielzhe**
**JIRA**: [JBPM-9502](https://issues.redhat.com/browse/JBPM-9502)
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by danielzhe** [comment]
jenkins do fdb

**Comment by danielzhe** [comment]
I don't think those 4 failing tests are related. I saw those tests failing in others PRs today:
org.kie.workbench.common.services.backend.compiler.ConcurrentBuildTest.buildFourProjectsInFourThread
org.kie.workbench.common.services.backend.compiler.ConcurrentBuildTest.buildFourProjectsInTheSameThread
org.kie.workbench.common.services.backend.compiler.ConcurrentBuildTest.buildFourProjectsInFourThreadCompletableFuture
org.kie.workbench.common.services.backend.compiler.plugin.KieMetadataTest.compileAndLoadKieJarMetadataAllResourcesPackagedJar

**Review by romartin — COMMENTED** [review]
Hey @danielzhe ,

Great job! It looks a great fix, much better than the one we talked aobut, so thanks! 

Anyway I see a couple of methods not being tested yet, like the `destroy`. Could you please add just a few more test cases covering that?

Thanks :+1:

**Comment by romartin** [comment]
Thanks!! 
Waiting for the builds now, but looks good :)

**Comment by danielzhe** [comment]
jenkins retest this

**Review by romartin — APPROVED** [review]

**Comment by danielzhe** [comment]
jenkins do fdb

**Comment by danielzhe** [comment]
jenkins retest this

**Comment by romartin** [comment]
Hey @jstastny-cz 

Could you help on the QE side review for this PR, please? Otherwise, could you please reassign properly?

Please notice that's **HIGH PRIORITY**, as this ticket is expected to be fixed during actual week, and so present on the next RHPAM 7.10 release as well.

Thanks in advance!!

**Comment by danielzhe** [comment]
jenkins do fdb

**Comment by jstastny-cz** [comment]
@danielzhe builds are failing due to
```
[2020-12-14T21:05:56.350Z] [INFO] --- maven-checkstyle-plugin:3.0.0:check (validate) @ kie-wb-common-stunner-client-common ---
[2020-12-14T21:05:57.276Z] [INFO] There are 2 errors reported by Checkstyle 8.19 with /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-master.pr/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/target/checkstyle-rules.xml ruleset.
[2020-12-14T21:05:57.276Z] [ERROR] src/test/java/org/kie/workbench/common/stunner/core/client/canvas/DeleteNodeConfirmationImplTest.java:[33,8] (imports) UnusedImports: Unused import - org.kie.workbench.common.stunner.core.client.session.impl.InstanceUtils.
[2020-12-14T21:05:57.276Z] [ERROR] src/test/java/org/kie/workbench/common/stunner/core/client/canvas/DeleteNodeConfirmationImplTest.java:[56,15] (imports) UnusedImports: Unused import - org.mockito.Mockito.doCallRealMethod.
```
Please fix that and run builds (including FDB) again. Thanks.

**Comment by danielzhe** [comment]
jenkins do fd

**Comment by danielzhe** [comment]
jenkins do fdb

**Comment by romartin** [comment]
Hey @jstastny-cz 

Artifacts should be ready for testing now. Please would appreciate early review tomorrow, we're trying to include this in the 7.10 cutoff.

Thanks in advance!

**Review by jstastny-cz — APPROVED** [review]
LGTM, I can't reproduce the original issue, node operations works fine in both dmn and bpmn editors in BC.

**Pull request merged**
