### PR TITLE
[7.23.x] RHDM-967: [DMN Designer] Data Type reference to itself

### PR DESCRIPTION
**Pull request by karreiro**
See: https://issues.jboss.org/browse/RHDM-967

### CODE REVIEW

**Comment by jomarko** [comment]
@manstis may I ask you for reassigning the review to @Bonuseto ?

**Comment by Bonuseto** [comment]
jenkins execute full downstream build

**Comment by karreiro** [comment]
Jenkins please execute full downstream build.

**Comment by karreiro** [comment]
Jenkins please execute full downstream build.

**Pull request merged**
