### PR TITLE
GUVNOR-3531: Workbench navigation - An error popup appears, if unsaved data, when navigating to the Projects screen

### PR DESCRIPTION
**Pull request by paulovmr**
RHBPMS-4895: [Library] Javascript error when canceling navigation to Library perspective

### CODE REVIEW

**Comment by manstis** [comment]
@paulovmr Please let me know when green.

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
@manstis ready to merge :)

**Pull request merged**
