### PR TITLE
KOGITO-1660 Fire multiple times type property dropdown is too small

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin, @domhanak, @tomasdavidorg,

it is a quick fix, but I think it is good enough, since we will fully rework forms in near future.

image

VSIX for tests can be downloaded here: https://drive.google.com/file/d/1AVtusv1reXlrGELES-HPUS8wN0DXogeY/view?usp=sharing

There how it is looks like now in the Business Central:
image
I didn't build it locally just tricked css styles directly on running instance.

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins retest please

**Comment by romartin** [comment]
Thanks @hasys .

Please lemme know when it's ready for merging.

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin, I rebased to the master and pushed again.

Before I pushed Full Downstream was green and regular was red, now it is quite the reverse :D Does green Full Downstream before counts, or we need it green again? :)

**Comment by hasys** [comment]
Full downstream build failed due to unrelated out of memory, should be fine after rebuild.
```
[INFO] # There is insufficient memory for the Java Runtime Environment to continue.
[INFO] # Native memory allocation (mmap) failed to map 962068480 bytes for committing reserved memory.
[INFO] # An error report file with more information is saved as:
[INFO] # /home/jenkins/workspace/KIE/master/fullDownstream/new-FDB-kie-wb-common-master.downstream/hs_err_pid13021.log
[ERROR] Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000731580000, 962068480, 0) failed; error='Cannot allocate memory' (errno=12)
```

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute compile downstream build

**Comment by romartin** [comment]
As just a single html file changed, no need for waiting for all builds, right @hasys , merging! Thanks a lot, great work again.

**Pull request merged**
