### PR TITLE
JBPM-7409: Stunner - MI SubProcess CompletionCondition is not stored

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit b68066233fc1dbe69a79393912d30dd91a69c7c7)

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi  @romartin @hasys would you mind review?
Thanks.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Pull request merged**
