### PR TITLE
JBPM-8824 ExtensibleXmlParser error thrown for valid process with dyn…

### PR DESCRIPTION
**Pull request by treblereel**
…amic user assignment
JIRA : https://issues.jboss.org/browse/JBPM-8824

### CODE REVIEW

**Comment by treblereel** [comment]
@romartin ^^

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by treblereel** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@romartin @hasys plz review

**Comment by hasys** [comment]
Looks like master is broken and War file is not generated, waiting for master stabilization.

**Comment by hasys** [comment]
### Check list
- [x] ACKs are set
- [x] Is realization aligned to jira description?
- [x] Both Jenkins jobs are green
  * [BAQE-999](https://issues.jboss.org/browse/BAQE-999) known selenium instability.

### Code review
- [x] Code coverage
- [x] License headers
- [x] Static analyser gates
- [x] Code Style

### Acceptance Criteria
> Should be listed there (or linked to jira)

- [x] Tested with full downstream build
  - [x] Firefox
  - [x] Chrome

### Found issues
>  **Blocker**, **Critical** and **Major** bugs and **Blocker** and **Critical** enhancements should be fixed before merge.
* None

**Pull request merged**
