### PR TITLE
[7.7.x] RHPAM-899: Execution Servers: ContainerNotFound error thrown when removing the container

### PR DESCRIPTION
**Pull request by karreiro**
See: https://issues.jboss.org/browse/RHPAM-899

---

Cherry picked from https://github.com/kiegroup/kie-wb-common/pull/1865

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by karreiro** [comment]
@jomarko [here](https://www.dropbox.com/s/k4x37b9ykken438/kie-wb-7.7.1-SNAPSHOT-wildfly11.war?dl=0) is the war to the 7.7.x branch.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
@jomarko Since the https://github.com/kiegroup/kie-wb-common/pull/1865 is approved, I tried the war above locally, and today is the dead line for 7.0.1. I'm merging this one.

**Comment by jomarko** [comment]
@karreiro ok, thanks, I set the fix version into [RHPAM-899](https://issues.jboss.org/browse/RHPAM-899)

**Pull request merged**
