### PR TITLE
KOGITO-3274: [DMN Designer] Read-only mode - Connectors appear differently on read-only mode

### PR DESCRIPTION
**Pull request by danielzhe**
**JIRA**: [KOGITO-3274](https://issues.redhat.com/browse/KOGITO-3274)

**Business Central**: [WAR file](https://drive.google.com/file/d/1oLrCHqIL8rKKW1DkOgbmF4gEA--GHMde/view?usp=sharing)

**VS Code**: [plugin](https://drive.google.com/file/d/1HF-yRBYvtLBte9_gbhE12l8NOO28O0T2/view?usp=sharing)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by danielzhe** [comment]
Who can we assign from QE here, @karreiro ?

**Comment by jomarko** [comment]
@danielzhe @karreiro hello and thank you for PR. As said in jira. Please proceed without QE on this PR. QE will verify just the official product jira.

For the record.
I checked the code briefly. No comments. I did no manual check.

Thank you.

**Comment by karreiro** [comment]
jenkins retest this
jenkins do fdb

**Comment by karreiro** [comment]
@danielzhe I believe the broken tests in the CI are related to this PR:

```
org.kie.workbench.common.dmn.showcase.client.backward.compatibility.DMNBackwardCompatibilityIT.testDMN13Assets
org.kie.workbench.common.dmn.showcase.client.backward.compatibility.DMNBackwardCompatibilityIT.testDMN11Assets
org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.testDMNModelWithoutDMNDI_KOGITO3696
```

Could you please double-check them?

**Comment by danielzhe** [comment]
Thank you, I'm checking those tests. @karreiro

**Review by karreiro — APPROVED** [review]
Thank you, @danielzhe.

**Comment by karreiro** [comment]
jenkins do fdb

**Comment by karreiro** [comment]
jenkins do fdb

**Review by vpellegrino — APPROVED** [review]
LGTM, thanks @danielzhe

**Pull request merged**
