### PR TITLE
[7.44.x] RHPAM-2802 - Save and Rename of DMN/BPMN leads to Unexpected error

### PR DESCRIPTION
**Pull request by Josephblt**
**JIRA**: [RHPAM-2802](https://issues.redhat.com/browse/RHPAM-2802)

This is just a cherry-pick for back-porting purposes.

**Referenced Pull Requests**:
* https://github.com/kiegroup/kie-wb-common/pull/3440

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Review by romartin — APPROVED** [review]

**Comment by romartin** [comment]
Please @domhanak @LuboTerifaj would appreciate early review for this, the deadline is tomorrow... thanks!

**Comment by romartin** [comment]
Assigning to @LuboTerifaj as @domhanak is on vacation

**Review by barboras7 — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
