### PR TITLE
GUVNOR-3468: GridLienzoPanel/GridLienzoScrollUI: Improve re-usability

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/GUVNOR-3468

guvnor-3468

---

Part of an ensemble:
- https://github.com/AppFormer/uberfire/pull/826
- https://github.com/kiegroup/kie-wb-common/pull/1158
- https://github.com/kiegroup/drools-wb/pull/611

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@karreiro Sweet... When I first saw the video I thought you'd added scrollbars to the "outer" window.. but running locally it's as "[sweet as a nut](http://www.urbandictionary.com/define.php?term=sweet%20as%20a%20nut)"

**Comment by jomarko** [comment]
@karreiro this is dependent on https://github.com/AppFormer/uberfire/pull/826, right? Please let me know once you are done there, because currently I see different output:
Chrome:
screenshot from 2017-09-13 14-11-33
screenshot from 2017-09-13 14-11-21

Firefox:
screenshot from 2017-09-13 14-10-28
screenshot from 2017-09-13 14-10-12

**Comment by karreiro** [comment]
Hi @manstis, I think that everything is fixed now. Could you please take a look?

**Comment by karreiro** [comment]
Hi @jomarko. Yes, this PR depends on https://github.com/AppFormer/uberfire/pull/826 and it's done.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
