### PR TITLE
[7.3.x] Align check style plugin to current IDE styles

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin, @pefernan, @manstis this commit is the same as for master branch (but with it's own Import  Reordering run)

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by romartin** [comment]
@hasys please move this asap!

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Closing this since 7.3 branch is dead. PR for 7.4 created: https://github.com/kiegroup/kie-wb-common/pull/1268

**Pull request closed without merging**
