### PR TITLE
RHDM-886: specify the Maven compiler plugin version

### PR DESCRIPTION
**Pull request by almope**
RHDM-886: specify the Maven compiler plugin version with version.compiler.plugin

parent PR
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1027

### CODE REVIEW

**Comment by mareknovotny** [comment]
Can you @desmax74 review this too ?

**Comment by desmax74** [comment]
@mareknovotny I'm on PTO for two weeks, maybe @porcelli could review the changes.

**Comment by mareknovotny** [comment]
Jenkins please retest this

**Comment by mareknovotny** [comment]
Jenkins please retest this

once again to ask for a ci run, as there is NPE in test execution

**Pull request merged**
