### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@hasys hello, I am using just `mvn dependency:analyze`, let me know if you have more questions.

**Comment by hasys** [comment]
@jomarko do you use ignore non compile as well? Like `mvn dependency:analyze -DignoreNonCompile` because if not it can cause issues with runtime dependencies (some runtime dependencies can be incorrectly marked as unused).

**Comment by jomarko** [comment]
@hasys I was not using that option, thank you

**Pull request merged**
