### PR TITLE
JBPM-6108 ObjectSelector should not appear in Form-modeler editor

### PR DESCRIPTION
**Pull request by alessioscalici**
**WARNING**: to be merged with https://github.com/kiegroup/appformer/pull/93
and with https://github.com/kiegroup/kie-wb-common/pull/1024

Removed ObjectSelector related code from the project

@pefernan @jsoltes can you give  look?

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by jsoltes** [comment]
jenkins execute full downstream build

**Comment by jsoltes** [comment]
@alessioscalici or @pefernan could you please also fix the full downstream build? Some changes in appformer are possibly breaking some other repo.

**Comment by jsoltes** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
@manstis could you please merge this?

**Comment by manstis** [comment]
@pefernan With pleasure when https://github.com/kiegroup/appformer/pull/93 is approved and green.

**Comment by pefernan** [comment]
@alessioscalici could you please close this PR?

**Comment by alessioscalici** [comment]
@pefernan sorry, I thought I already closed it but the close request did never reach github :sweat_smile:

**Pull request closed without merging**
