### PR TITLE
RHPAM-1861: [GSS](7.3.1) Multiple Selector throws error on edit.

### PR DESCRIPTION
**Pull request by jesuino**

### CODE REVIEW

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by ederign** [comment]
please jenkins retest this

**Comment by tomasdavidorg** [comment]
please jenkins retest this

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Looks good to me.

**Pull request merged**
