### PR TITLE
JBPM-5604 Subform rename or its new copy is not reflected in the parent form 7.3.x

### PR DESCRIPTION
**Pull request by alessioscalici**
**WARNING** this is the same as https://github.com/kiegroup/kie-wb-common/pull/1153, pointing to 7.3.x branch.

@pefernan @jsoltes could you please review?

### CODE REVIEW

**Comment by manstis** [comment]
@alessioscalici You really need to see these PRs through to completion!

**Comment by jsoltes** [comment]
@alessioscalici could you please resolve conflicts on this one?

**Comment by alessioscalici** [comment]
@jsoltes @pefernan @manstis I added tests and fixed conflicts

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by jsoltes** [comment]
jenkins retest this

**Comment by jsoltes** [comment]
@pefernan I believe this only waits for your approval, Pere...

**Pull request merged**
