### PR TITLE
JBPM-6698: Stunner - Improve available signals calculation in signal Events

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin , @hasys , would you mind review this PR?
Thanks.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
same here, jbpm designer VFS related failing tests
org.jbpm.designer.web.preprocessing.impl.JbpmPreprocessingUnitVFSSpacesTest.testInstallDefaultWids

Failing for the past 4 builds (Since Unstable#468 )
Took 10 ms.
Error Message

expected:<3> but was:<1>
Stacktrace

java.lang.AssertionError: expected:<3> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
same here @hasys , artifacts now generated, plz would like to merge this, if possible, before leaving. Thanks!

**Comment by wmedvede** [comment]
merge conflicts fixed

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
As @hasys is on PTO I've tested it and works fine. Merging...

**Pull request merged**
