### PR TITLE
JBPM-8221 - Imports property for Process

### PR DESCRIPTION
**Pull request by Josephblt**
https://issues.jboss.org/browse/JBPM-8221

It is possible to import classes and namespaces in Process Nodes.

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Hello @romartin. Build succesfull. Time to assign some reviewers. Thanks

**Comment by romartin** [comment]
Please @hasys or @LuboTerifaj , this review is really **URGENT**, can you give it top priority? Thanks in advance!

**Comment by romartin** [comment]
Please @LuboTerifaj or @hasys , REVIEW PENDING - URGENT. Thanks!!

**Comment by hasys** [comment]
### Check list
- [x] ACKs are set
- [x] Affected version is set property
- [x] Is realization aligned to jira description?
- [x] Both Jenkins jobs are green

### Code review
- [x] Code coverage
- [x] License headers
- [x] Static analyser gates
- [x] Code Style

### Acceptance Criteria
> * FQN of class can be defined in Imports dialogue and class name can be used in scripts without package
> * WSDL imports can be specified. It  should be possible to invoke Web Service and got response.

- [x] Tested with full downstream build
  - [x] Firefox
  - [x] Chrome

### Found issues
>  **Blocker**, **Critical** and **Major** bugs and **Blocker** and **Critical** enhancements should be fixed before merge.
* It is possible to save empty Class Name Import. Process with empty Class Name Import doesn't build with not clear message:
  * [KBase: defaultKieBase]: unable to parse xml : Exception class org.xml.sax.SAXParseException : <import> requires a 'name' attribute
* There is no validation of datatype in Name Imports
* It is possible to set the same import twice (doesn't cause any build/runtime issues)
* Rename "Default Imports" to something like "Data Type Imports" or "Class Imports"
* There is no help with "known" types. For example if I will create a Data Object with FQN some.package.SomeType I am not able to select this type and have to type it manually. It was possible in the old designer.
* Imports are missing in the process documentation

### Used resources
Processes for quick test can be found here: https://github.com/bpmn-tutorials/Imports

**Comment by hasys** [comment]
### Reported issues:

* [JBPM-8737](https://issues.jboss.org/browse/JBPM-8737) - Process with empty Class Name Import doesn't build
* [JBPM-8741](https://issues.jboss.org/browse/JBPM-8741) - Documentation doesn't have Imports property
* [JBPM-8740](https://issues.jboss.org/browse/JBPM-8740) - Imports dialogue doesn't provide help for existing types
* [JBPM-8738](https://issues.jboss.org/browse/JBPM-8738) - There is no validation of datatype in Name Imports
* [JBPM-8739](https://issues.jboss.org/browse/JBPM-8739) - Imports has not clear titles

**Pull request merged**
