### PR TITLE
JBPM-6702 Issues once resizing a shape: fix connections positions

### PR DESCRIPTION
**Pull request by tiagodolphine**
The `MagnetConnection` locations in the edge are now updated to the current shape magnet position after resize. You can resize a shape with connections, save the diagram and open again to check the new positions.

@romartin 
@LuboTerifaj

### CODE REVIEW

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @tiagodolphine , all good for me thanks! Although at some point I would like to move all this logic from the `ResizeControl` to some core command... but we already talked about that, let's do it in future iterations :)
Thx!

**Comment by tiagodolphine** [comment]
hey @romartin yeah, totally agree with you on that, there are lot of logic on the Control, and it is better to create a command. Anyway may be an improvement task after GA.
Thx.

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj  when you have time to review this one, waiting your approval to merge.
Thanks !

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj thanks for the review, yeah I saw that, but it is not related to this PR, it is related to the JBPM-6491 / RHPAM-468. Let's keep there to handle this issue.
Thanks !

**Comment by tiagodolphine** [comment]
Hey as we discussed on the meeting I'll provide the fix to the issue @LuboTerifaj in here mentioned https://github.com/kiegroup/kie-wb-common/pull/1743 .

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Pull request merged**
