### PR TITLE
JBPM-7160: [Forms Migration Tool] Wrong type reference on some automatically generated SubForms

### PR DESCRIPTION
**Pull request by pefernan**
@jsoltes could you please review?

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins please execute full downstream build

**Comment by pefernan** [comment]
Jenkins please execute full downstream build

**Comment by jsoltes** [comment]
jenkins please execute full downstream build

**Comment by pefernan** [comment]
jenkins please execute full downstream build

**Comment by pefernan** [comment]
jenkins please execute full downstream build

**Comment by pefernan** [comment]
jenkins please execute full downstream build

**Comment by pefernan** [comment]
jenkins retest this

**Pull request merged**
