### PR TITLE
AF-1424: Support SSH keystore with workbench

### PR DESCRIPTION
**Pull request by pefernan**
AF-1274: SSH Keystore UI

@ederign @domhanak could you please take a look?

This is part of an ensemble, please merge with:
https://github.com/kiegroup/appformer/pull/492
https://github.com/kiegroup/kie-wb-common/pull/2177
https://github.com/kiegroup/kie-wb-distributions/pull/829
https://github.com/kiegroup/drools-wb/pull/959
https://github.com/kiegroup/jbpm-wb/pull/1215
https://github.com/kiegroup/optaplanner-wb/pull/308
https://github.com/kiegroup/kie-docs/pull/1156

### CODE REVIEW

**Comment by domhanak** [comment]
@pefernan  I think you need to rebase on master to include a fix that should make this build

**Comment by domhanak** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
jenkins retest this please

**Pull request merged**
