### PR TITLE
[7.59.x] JBPM-9532 : Recusivity issue on form generation

### PR DESCRIPTION
**Pull request by akumar074**
> Currently, when we are generating a form when we have 2 data objects which reference each other or have cyclic reference, the engine enters into an infinite loop.
> To fix this issue, we have come up with a way to track the cyclic reference in the field and skip the form generation for field when we encounter the cycle.

**JIRA**: 
[JBPM-9532](https://issues.redhat.com/browse/JBPM-9532)
[RHPAM-3366](https://issues.redhat.com/browse/RHPAM-3366)

**Original Pull Request**:
* https://github.com/kiegroup/kie-wb-common/pull/3713

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins do fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins do fdb

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins do fdb

**Comment by akumar074** [comment]
@jstastny-cz FDB test failure seems random and unrelated to the change please take a look.

**Review by jstastny-cz — APPROVED** [review]
Tested using the example project, works fine. Thank you.

**Review by pefernan — APPROVED** [review]
+1

**Pull request merged**
