### PR TITLE
AF-1610: using maven embedded when not in offline mode, so external dependencies are resolved as expected.

### PR DESCRIPTION
**Pull request by porcelli**
fix for issues pointed by @wmedvede 

@ederign @desmax74 @jhrcek could you please take a look? thx!

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi, @ederign , @desmax74 , @jhrcek ,  @porcelli 
I'll try to build and try this locally too.

**Comment by porcelli** [comment]
Jenkins execute full downstream build

**Comment by desmax74** [comment]
@porcelli @wmedvede @ederign @jhrcek It's ok for me

**Comment by ederign** [comment]
Fulldownstream is green, regular is on jan's list (Random failures).

**Pull request merged**
