### PR TITLE
[7.7.x ] Add migration tool tests

### PR DESCRIPTION
**Pull request by tomasdavidorg**
Depends on https://github.com/kiegroup/kie-wb-common/pull/1788

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
jenkins retest this

**Comment by tomasdavidorg** [comment]
jenkins retest this

**Comment by tomasdavidorg** [comment]
jenkins retest this

**Comment by tomasdavidorg** [comment]
jenkins retest this

**Comment by tomasdavidorg** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by jhrcek** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
What about PR #1788 review? @jhrcek, @desmax74 could you look at it too, as without that PR we can't merge it

**Comment by jhrcek** [comment]
@mareknovotny I think that change is the part of this PR. So if we merge this one, https://github.com/kiegroup/kie-wb-common/pull/1788 can be closed.

**Comment by mareknovotny** [comment]
I see, I didn't realize it

**Pull request merged**
