### PR TITLE
Show "indexing in progress" screen before project indexed and fix bug deleting projects

### PR DESCRIPTION
**Pull request by mbarkley**

### CODE REVIEW

**Comment by mbarkley** [comment]
Related:
https://github.com/errai/errai/pull/333
https://github.com/kiegroup/appformer/pull/223
https://github.com/kiegroup/kie-wb-common/pull/1475

**Comment by mbarkley** [comment]
This follows up on the asset list indexing fix, and restores the screen for the index waiting. Also includes a fix for deleting projects that I ran into during testing.

@paulovmr @adrielparedes Would either of you mind reviewing this?

**Comment by jsoltes** [comment]
jenkins please execute full downstream build

**Comment by mbarkley** [comment]
Jenkins, please execute full downstream build.

**Comment by mbarkley** [comment]
Jenkins, execute full downstream build.

**Comment by mbarkley** [comment]
The test that fails downstream doesn't depend on any of the changed maven modules.

**Pull request merged**
