### PR TITLE
AF-1874-Add_string_cut_library_widgets

### PR DESCRIPTION
**Pull request by ohonchar**

### CODE REVIEW

**Comment by ederign** [comment]
hi @srambach could you please take a look at this?

**Comment by ederign** [comment]
please jenkins retest this

**Comment by srambach** [comment]
I can't run it to check, but the CSS looks good to me! 👍

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by ohonchar** [comment]
@paulovmr are those errors related to my changes?

**Comment by paulovmr** [comment]
@ohonchar I don't think so. I will re-run the build just to make sure.

jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by ohonchar** [comment]
jenkins execute full downstream build

**Comment by ohonchar** [comment]
@paulovmr it has some problem with `17:53:47 [INFO] Kie Workbench - Common - DMN - Showcase webapp ..... FAILURE [02:31 min]`

**Comment by ohonchar** [comment]
jenkins execute full downstream build

**Comment by ohonchar** [comment]
@paulovmr could u please look on build once again? thnx

**Comment by ohonchar** [comment]
@ederign could u please look on this build, if u can merge it? Thnx

**Pull request merged**
