### PR TITLE
AF-2572 : Invalid username in git commit history of svg when saving a BPMN file

### PR DESCRIPTION
**Pull request by akumar074**
* Adding Author details to AbstractVFSDiagramService to create() and saveOrUpdateSvg()

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
Jenkins retest this please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by ederign** [comment]
@caponetto can you please take a look at this?

**Pull request merged**
