### PR TITLE
AF-2011: Redeploy does not abort running process instances when their process definition is deleted

### PR DESCRIPTION
**Pull request by pefernan**
@paulovmr @domhanak would you mind take a look?

This is part of an ensemble, please merge with:
https://github.com/kiegroup/kie-wb-common/pull/2681
https://github.com/kiegroup/droolsjbpm-integration/pull/1839

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
@domhanak downstream failed due to unrelated tests but the artifacts are there!

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by pefernan** [comment]
jenkins please retest this

**Comment by domhanak** [comment]
jenkins please retest this

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Pull request merged**
