### PR TITLE
[7.0.x] JBPM-5913: Stunner - Fix icons for End Events

### PR DESCRIPTION
**Pull request by jlindop**
Cherry-pick to 7.0.x

### CODE REVIEW

**Comment by jlindop** [comment]
Jenkins please retest this

**Comment by jlindop** [comment]
@manstis Ready to merge, when you get a chance. Thanks.

**Comment by romartin** [comment]
Hey @jlindop @tsurdilo @manstis 
I have built several times to this to check if was my fault but I think that commit has broken something. See last comments on [the ticket](https://issues.jboss.org/browse/JBPM-5913). On the toolbox the icon for end event does not appear, and the tree explorer the icon is not the good one.
If you dont have time to fix, I would probably say to revert this... what you think guys? 
Thx!

**Comment by manstis** [comment]
@jlindop @tsurdilo Can you confirm @romartin comment? I think we've missed the CR2 release window to revert anything so suggest, if there is an issue, a new PR be submitted.

**Comment by jlindop** [comment]
@romartin @manstis Thanks Roger, I just checked as well and you're right. I'll create a new Jira and PR to fix the toolbox and explorer icons.

**Pull request merged**
