### PR TITLE
[7.7.x] RHPAM-1015: Improve computation performance

### PR DESCRIPTION
**Pull request by romartin**
Hey @hasys

Re-opened this without the lienzo changes, and it works thesame yeah. Anyway here are some of the improvements about computation performance that we should include ASAP. See https://issues.jboss.org/browse/RHPAM-1015

These fixes improve the performance in general, but the better results are on FF and IE, you can compare with some previous version too... It's still slow on Chrome in Mac, so ee'll keep working on a few more improvements during next days.

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins please retest this
Jenkins execute full downstream build

**Comment by romartin** [comment]
BTW @hasys  - about the "grey" icons that appear initially and about the lag on mouse move I'm agree as well. We're going to fix both issues in some next commit soon, we're already working on those. Thanks for the feedback again!

**Comment by hasys** [comment]
@romartin, yes it is dashed, but it looks like double dashed line which is correct for intermediate events, but not correct for Start events. Is it possible to quick fix using CSS?

**Comment by romartin** [comment]
@hasys ohhh good point.... mmm lemme think, it's not just css, it's due to the structure of the svg shape also...

**Comment by romartin** [comment]
@hasys I'd been testing and well, it could be done by adding another `path` into the SVG for events and doing some trick... it's not just CSS sorry :( On the other hand adding another element into the SVG implies more processing, so slower performance... 
This thing about dashed events has to be "undone" at some point anyway, once we fix some issues on lienzo side, so I'm wondering if we can move forward with double dashed lines at that point for GA, rather than introduce now another path and more CSS...
@hasys @krisv WDYT?

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
or any other ideas?

**Comment by hasys** [comment]
I am agree with @krisv. Thank you @romartin, good job! Will take a quick look to the full downstream build when it finish and will approve this PR.

**Comment by romartin** [comment]
Hey @hasys  @krisv 
Thanks guys!! Just created https://issues.jboss.org/browse/JBPM-7306 for this.

**Comment by romartin** [comment]
thanks @hasys for keeping an eye here, I'm also looking the build :) Remember will merge as well these ones -> https://github.com/kiegroup/kie-wb-common/pull/1828

**Comment by romartin** [comment]
Ok @hasys  , so as expected it was a conflict on two tests, just fixed. Will run the J build to ensure tests are ok. No need downstream one again, as just changed  2 test classes. Thanks!

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Fixed a couple of tests, it was my fault when rebasing sorry. Tested locally and everything is fine. This can be merged once J is green. Thanks! CC @krisv

**Comment by krisv** [comment]
jenkins retest this

**Comment by hasys** [comment]
Hi @krisv, @adrielparedes, not sure, but it looks like we have a compilation error here caused by
this PR https://github.com/kiegroup/kie-wb-common/commit/f873da2c2da440c3f7f5c1ee7140c216732e25cd on this line: https://github.com/kiegroup/kie-wb-common/blame/7.7.x/kie-wb-common-screens/kie-wb-common-library/kie-wb-common-library-client/src/main/java/org/kie/workbench/common/screens/library/client/screens/importrepository/ImportPresenter.java#L318

**Comment by hasys** [comment]
@krisv, @adrielparedes, probably, we are missing this PR in 7.7.x branch: https://github.com/errai/errai/pull/343

**Comment by manstis** [comment]
On 7.7.x this is missing: https://github.com/errai/errai/pull/345/

This new method is used in https://github.com/kiegroup/kie-wb-common/pull/1823 that has been merged.

**Comment by mbiarnes** [comment]
@krisv @adrielparedes @hasys the tag thta is building right now has the errai version 4.2.1.Final. This Final version has not this commit [ errai/errai#343](https://github.com/errai/errai/pull/343)
If we do a temp version of errai of today kie 7.7.x uses errai 4.2.x  - and there is neither this commit.

**Comment by romartin** [comment]
Jenkins please  retest this

**Pull request merged**
