### PR TITLE
GUVNOR-3011: Stunner - Deploy fails on Tomcat.

### PR DESCRIPTION
**Pull request by romartin**
Hey @manstis @psiroky @mswiderski 

Here is the fix for the failed deployment on tomcat. See comments [here](https://issues.jboss.org/browse/GUVNOR-3011).

I have tried either both stunner showcases and the wf/tomcat distributions for kie-wb, all good, lemme know if any issues please!.

Thanks!
Roger

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@mswiderski I'll defer approval to you; since you've experienced the issue.

**Comment by mswiderski** [comment]
I haven't tried this on tomcat but +1 at using only client side to avoid server side CDI dependencies

**Comment by psiroky** [comment]
I don't really understand the code, but I agree that this better that adding the deps into the WAR.

**Comment by manstis** [comment]
OK, so I'll merge.. as everyone seems happy with @romartin fix.. but nobody knows (other than @romartin) if it's fixed anything ;-)

**Comment by mswiderski** [comment]
I am building everything locally to test this

**Comment by psiroky** [comment]
@romartin please make sure to create PR for master as well.

**Comment by romartin** [comment]
sure @psiroky ! working on it 
Thanks @manstis @mswiderski for you help!

**Pull request merged**
