### PR TITLE
RHPAM-2695: Component timer expression contains errors

### PR DESCRIPTION
**Pull request by handreyrc**
Hey @romartin, @inodeman: Could you review this PR please?

### CODE REVIEW

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
@romartin, @inodeman :  The SonarCloud is not detecting Unit tests for this implementation for some reason. As you can see I updated the tests with enhancemets I made and the tests are being executed as expected.
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 38.179 s - in org.kie.workbench.common.stunner.bpmn.forms.validation.timerEditor.TimerSettingsValueValidatorTest

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Hey @LuboTerifaj, I understand your point and I agree with you. However, I think we have to take into account what kind of expressions are currently supported by the engine as well. 
I tested many formats of expressions by changing it manualy in the xml, then deploying it and finally starting the process on business central.
Considering the scope of the original issue, these are the formats of expressions supported by the engine I could identify:
R5/2020-05-01T15:45:00Z/PT5S
R5/2020-02-07T15:36-04:00/PT5S
R/P1D
R3/PT8M3S

I tested some of the expressions you listed above. If I did it right these are the results when you try to deploy them as a repeatable interval (timeCycle):

R5/20300802T22:30:00+02:00/PT5S
[KBase: defaultKieBase]: Process 'SimpleTimerProcess' [bugtimer.SimpleTimerProcess]: Node 'MyTask' [1] Could not parse delay 'R5/20300802T22:30:00+02:00/PT5S': Text '20300802T22:30:00+02:00' could not be parsed at index 0

R5/2030-08T24:59:00Z/PT5S
[KBase: defaultKieBase]: Process 'SimpleTimerProcess' [bugtimer.SimpleTimerProcess]: Node 'MyTask' [1] Could not parse delay 'R5/2030-08T24:59:00Z/PT5S': Text '2030-08T24:59:00Z' could not be parsed at index 7

R5/2030-254T22:30:00+02:00/PT5S	
[KBase: defaultKieBase]: Process 'SimpleTimerProcess' [bugtimer.SimpleTimerProcess]: Node 'MyTask' [1] Could not parse delay 'R5/2030-254T22:30:00+02:00/PT5S': Text '2030-254T22:30:00+02:00' could not be parsed at index 7

R5/2030365T22:30:00+02:00/PT5S
[KBase: defaultKieBase]: Process 'SimpleTimerProcess' [bugtimer.SimpleTimerProcess]: Node 'MyTask' [1] Could not parse delay 'R5/2030365T22:30:00+02:00/PT5S': Text '2030365T22:30:00+02:00' could not be parsed at index 0

WDYT @LuboTerifaj and @romartin?

**Comment by romartin** [comment]
Hey @LuboTerifaj @handreyrc 

Thanks both for the great testing and analysis job!! :+1: 

As @handreyrc ponted out above:
* if the engine does not support some syntax - is fine the editor preveting from using it
* if the engine does support some syntax - the editor cannot prevent from using it

So please @handreyrc , just try to make the missing ones (engine supported) to work on the editor, and I would say we're ready to go.

Makes sense guys?

Thanks again, great job!

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Hey @LuboTerifaj and  @romartin, following the idea that we should support only the expressions supported by engine. I did some improments.
1) Period validation mask updated to the format "PnYnMnWnDTnHnMnS". 
e.g.  
* P1Y2M3DT2H30M2S
2) Date-Time validation mask updated to the format "YYYY-MM-DDTHH:MM[:SS[.nnn]|[Z]]|[+/-HH:MM]".
e.g. 
* 2030-08-20T17:59Z
* 2020-05-01T15:45:00Z
* 2020-02-07T15:36-04:00 
* 2020-05-12T18:25:00+02:00
* 2020-05-24T20:15:00.000+00:00
3) Basic validation of date and time values added. All the validation is being done via Regexp even in other parts of the code, we are not using a real calendar for that so we have some limitations here or we will have extremelly complex exprssions to maintain.
4) Info text/help information was updated.

Now the following expressions, which are supported by the engine are valid in stunner:
* R/P1D
* R3/PT8M3S
* R5/2020-05-01T15:45:00Z/PT5S
* R5/2020-02-07T15:36-04:00/PT5S
* R1/2020-05-24T20:15:00.000+00:00/PT5S
* R1/2020-05-12T18:25:00+02:00/PT5S
* R5/2021-04-14T08:15:00Z/P1Y2M3DT2H30M2S
* R5/2030-08-20T22:14-00:30/PT5S
* R5/2020-12-01T23:50:01Z/PT5S
* R5/2021-04-14T08:15:00Z/2021-04-15T08:15:00Z
* R5/2030-08-20T17:59Z/PT5S
* R2/PT3S/2021-04-15T08:15:00Z

Please, could you review the again?

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
jenkins execute full downstream production build

**Comment by romartin** [comment]
Please @handreyrc

Keep an eye on this PR and try to get the artifacts ready from testing, from any of the builds. Once artifacts ready please ping @LuboTerifaj to start the review.

I've just fired the production build, see comment above

Thanks guys!

**Comment by handreyrc** [comment]
jenkins execute full downstream production build

**Comment by handreyrc** [comment]
Jenkins execute Full downstream build

**Comment by handreyrc** [comment]
jenkins execute full downstream production build

**Comment by handreyrc** [comment]
Jenkins execute Full downstream build

**Comment by romartin** [comment]
Please @handreyrc ensure this is rebased from master again, as we're now on the next snaphost version... and also please re-fire the CI builds, thx!

**Comment by handreyrc** [comment]
Hey @LuboTerifaj, we have the FDB green  and ready for review! Thanks.

**Comment by romartin** [comment]
pleaes @LuboTerifaj missing review.

**Comment by LuboTerifaj** [comment]
Hi @romartin, @handreyrc  missing FDB here.

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Please @handreyrc try to upload the artifacts somewhere in case Jenkisn is not generiting the artifacts, so @LuboTerifaj  can start testing, we're really close to the due date for this. And please keep both in touch tomorrow for moving this stuff forwrad. Thanks a lot guys!

**Comment by handreyrc** [comment]
@romartin, @LuboTerifaj : I've generated the artifacts locally and they are available through the link:
https://drive.google.com/open?id=1pxDiBetKOr4F38nwCP8qJRACXWE91rBI

**Comment by LuboTerifaj** [comment]
Hi @handreyrc ,

I just went through all expressions mentioned above and it was not possible to deploy the project with those values:
  - `ERROR [org.drools.compiler.kie.builder.impl.KieProject] (default task-10) Unable to build KieBaseModel:defaultKieBase
[-1,-1]: Process 'PROCESS_NAME' [PROEJCT_NAME.PROCESS_NAME]: Node 'null' [4] Could not parse date 'EXPRESSION': Error parsing time string: [ EXPRESSION ]` 

The only value that I could have used was that one mentioned in my previous comment:
  - Using fractions at _seconds_ position using either comma or dot separator. For example: "P5Y1M4DT13H30M8,4S"

Thanks!

**Comment by romartin** [comment]
ok thanks guys for this work, let's check this on Mon again.

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
@LuboTerifaj, @romartin the code have been updated to support fractions in the duration part of ISO expressions like "P5Y1M4DT13H30M8,4S".
Note: The engine only supports fractions for "Seconds", all the other parameters only support integer values.
Link for testing:
https://drive.google.com/file/d/1e8TKfbNeyI-gQYQywypMnM0GUhZ82Ryf/view?usp=sharing

**Comment by romartin** [comment]
great, thanks @inodeman !

Please @LuboTerifaj , urgent review :) thanks!

**Pull request merged**
