### PR TITLE
AF-1645: Error when deleting modified project

### PR DESCRIPTION
**Pull request by paulovmr**
Part of an ensemble:
* https://github.com/kiegroup/kie-wb-common/pull/2194
* https://github.com/kiegroup/optaplanner-wb/pull/312

### CODE REVIEW

**Comment by paulovmr** [comment]
Hi @ederign @barboras7 , if you could take a look, please. Thanks!

**Comment by barboras7** [comment]
Jenkins execute full downstream build

**Comment by barboras7** [comment]
Hi @paulovmr,
the issue is fixed on kie-wb, however I'm still getting an error on kie-drools-wb. I believe that the fix should apply to both, right? 

Following the same steps to reproduce as in the original issue, this is the error I am getting:
`{"ToSubject":"org.kie.workbench.common.services.refactoring.service.AssetsUsageService:RPC.getAssetUsages:java.lang.String:org.kie.workbench.common.services.refactoring.service.ResourceType:org.uberfire.backend.vfs.Path::72:RespondTo:RPC"} | Uncaught exception: Client-side exception occurred although RPC call succeeded. Caused by: (TypeError) : a is null`

**Comment by paulovmr** [comment]
@barboras7 Thanks for catching it. This is a different issue actually, only happens if the edited asset is a data object. I also opened [this PR](https://github.com/kiegroup/optaplanner-wb/pull/312) to fix it.

Jenkins execute full downstream build

**Comment by barboras7** [comment]
Jenkins execute full downstream build

**Comment by barboras7** [comment]
Thanks @paulovmr. Both issues are fixed, approving :+1:

**Comment by barboras7** [comment]
@manstis could you please merge this ensemble?

**Pull request merged**
