### PR TITLE
AF-610: [Layout editor] CSS edition

### PR DESCRIPTION
**Pull request by dgutierr**
@pefernan This contains the changes related to https://github.com/kiegroup/appformer/pull/188 

Take a look please at the LayoutGeneratorDriver interface which is the mechanism to customize the layout generator behaviour.

### CODE REVIEW

**Comment by kkufova** [comment]
@dgutierr, please rebase to master to prevent the build fail. This [PR](https://github.com/kiegroup/kie-wb-common/pull/1432) (already merged) should fix it. :-)

**Comment by pefernan** [comment]
jenkins please execute full downstream build

**Comment by pefernan** [comment]
@jsoltes could you please review too?

**Comment by jsoltes** [comment]
@pefernan reviewing...

**Comment by jsoltes** [comment]
looks like there is some problem with building gwt showcases... 
jenkins please execute full downstream build

**Comment by kkufova** [comment]
You don't need to build `kie-wb-common`, the showcase is available in AppFormer.

**Comment by kkufova** [comment]
@dgutierr, could you please have a look at these build errors?

**Comment by jsoltes** [comment]
jenkins please execute full downstream build

**Comment by dgutierr** [comment]
@kkufova I fixed a CDI injection error. Build is working now.

**Comment by jsoltes** [comment]
jenkins please execute full downstream build

**Comment by pefernan** [comment]
@dgutierr something weird happens on the build, kie-wb build fails due to an OutOfMemoryException while GWT compilation (also in my computer). Must say that jbpm-wb-showcase builds well.

**Comment by kkufova** [comment]
@dgutierr, @pefernan, I can confirm, the build is failing locally due to an OOM error for me as well.

**Comment by pefernan** [comment]
@dgutierr works well in jbpm-wb. For me ok to merge after the kie-wb build issue is fixed.

**Comment by jsoltes** [comment]
@dgutierr @pefernan  just a note, I would like to have a look on the kie-wb result of the full downstream build before it gets merged, so please don't merge it right after it gets fixed...

**Comment by dgutierr** [comment]
@kkufova @pefernan @jsoltes I verified the build in failing with the OOM error => https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-common-downstream-pullrequests/611/console

It requires further investigation. I'll ask @mbarkley about it.

**Comment by dgutierr** [comment]
@kkufova @pefernan @jsoltes Finally, I managed to fix it. The solution was to remove a parametrized type injected in an constructor => https://github.com/kiegroup/appformer/pull/188/files#diff-f796c1d10f3d4f5fed9f27200a42ee11R108

This was causing a bug in Errai's code generator. MaxB has the details.

**Comment by kkufova** [comment]
jenkins execute full downstream build

**Comment by kkufova** [comment]
jenkins execute full downstream build

**Comment by dgutierr** [comment]
@ederign A test is failing on jenkins because a random false negative => org.kie.workbench.common.services.refactoring.backend.server.drl.IndexDrlLHSTypeFieldTest.testIndexDrlLHSTypeField

This is an old known issue we have found several times in the recent past. @kkufova can you confirm please?

**Comment by kkufova** [comment]
I can confirm. We were dealing with the exact same thing here not that long ago: https://github.com/kiegroup/kie-wb-common/pull/1335. I don't think there is any solution available yet, I guess there is no other option than to try retesting until the build passes.

**Pull request merged**
