### PR TITLE
[7.3.x] JBPM-6409: In taskforms data inputs (if different than outpus) should be readonly by default. (Also fixes JBPM-5742)

### PR DESCRIPTION
**Pull request by pefernan**
Copy of https://github.com/kiegroup/kie-wb-common/pull/1186

@jsoltes could you please take a look?

This is part of an ensemble, merge with:
https://github.com/kiegroup/kie-wb-common/pull/1187
https://github.com/kiegroup/jbpm-designer/pull/666
https://github.com/kiegroup/jbpm-wb/pull/904

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by jsoltes** [comment]
@pefernan It looks like the full downstream build won't pass, because there are some compilation failures in designer...

**Comment by pefernan** [comment]
@jsoltes they are already fixed... (look at https://github.com/kiegroup/jbpm-designer/pull/666)...

**Comment by jsoltes** [comment]
jenkins execute full downstream build

**Pull request merged**
