### PR TITLE
[7.48.x] JBPM-9627 Stunner - Update Message events marshaller tests f…

### PR DESCRIPTION
**Pull request by LuboTerifaj**
…or structureRef element

JIRA: [JBPM-9627](https://issues.redhat.com/browse/JBPM-9627)

This is a cherry-pick for https://github.com/kiegroup/kie-wb-common/pull/3576

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
Hello @Josephblt , @romartin can you please have a look at this? It is just a cherry-pick. Thanks!

**Comment by LuboTerifaj** [comment]
Jenkins execute fdb

**Review by Josephblt — APPROVED** [review]

**Comment by LuboTerifaj** [comment]
Jenkins build test failures are caused by the fact that [PR3575](https://github.com/kiegroup/kie-wb-common/pull/3575) is not merged yet. Once it is merged, the tests should pass.

**Comment by LuboTerifaj** [comment]
#3575 needs to be merged first.

**Review by romartin — APPROVED** [review]

**Comment by romartin** [comment]
@LuboTerifaj just merged the dependant PR: https://github.com/kiegroup/kie-wb-common/pull/3575
Lemme know when I can merge this, do you want to refire the normal build?
Thanks!

**Comment by LuboTerifaj** [comment]
Jenkins retest this

**Comment by LuboTerifaj** [comment]
Hey @romartin , the builds are green, hence the pull-request is ready to merge. Thanks!

**Pull request merged**
