### PR TITLE
DROOLS-4081: [DMN Designer] Constraints are allowed for inappropriate data types

### PR DESCRIPTION
**Pull request by danielzhe**
See https://issues.jboss.org/browse/DROOLS-4081

### CODE REVIEW

**Comment by danielzhe** [comment]
Thank you, @jomarko . Issue fixed. Ready for you re-review.

**Comment by jomarko** [comment]
@danielzhe there are conflicts, I resolved locally so will proceed with review, just letting you know.

**Comment by danielzhe** [comment]
Jenkins please retest this

**Comment by danielzhe** [comment]
@manstis Merge, please.

**Pull request merged**
