### PR TITLE
JBPM-5917 Change the order of "Tools" and data object/process variable dropdown

### PR DESCRIPTION
**Pull request by alessioscalici**
@pefernan @jsoltes could you please give a look?
**WARNING**: to be merged with  https://github.com/kiegroup/kie-wb-common/pull/1021

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by jsoltes** [comment]
@alessioscalici @pefernan one more thought - maybe now that master is 8.0.0-SNAPSHOT, this should be cherry-picked to 7.2.x branch, too?

**Comment by pefernan** [comment]
@jsoltes @alessioscalici  I think we should provide PR's for 7.2 & 8.0

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Pull request merged**
