### PR TITLE
BAPL-1742: Drop Case Management (Tech Preview) editor

### PR DESCRIPTION
**Pull request by romartin**
Hey @LuboTerifaj 

Please see https://issues.redhat.com/browse/BAPL-1742

Assembly with:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1541
- https://github.com/kiegroup/kie-wb-common/pull/3504
- https://github.com/kiegroup/kie-wb-distributions/pull/1072

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
jenkins do fdb

**Comment by Ginxo** [comment]
@romartin can you please rebase this PR? thanks

**Comment by romartin** [comment]
jenkins do fdb

**Review by hasys — APPROVED** [review]
Looks good to me, thank you @romartin

**Comment by romartin** [comment]
Hey  @LuboTerifaj 

I've uploaded the WAR in case the CI artifacts gets automatically removed, alhtough they're still available. The BC WAR is here: https://drive.google.com/file/d/1JOfS5FxopFhR95fQIJLKl70TSEx7WT-7/view?usp=sharing

Please remember that this just removes code, the code for an editor which was even prevsiouly removed from being used in BC (kirill did that a few weeks ago), so everything should be as before, this PR should not affect functionality at all.

Please lemme know something on this ASAP!
Thanks!

**Review by LuboTerifaj — APPROVED** [review]
Hello @romartin ,

I didn't find any issues.

It looks good to me.

Thank you!

**Pull request merged**
