### PR TITLE
[7.5.x] RHDM-255: [IE11] An error occurs when creating new space in the business central

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by karreiro** [comment]
The broken test is not related to this PR:
```
org.guvnor.ala.wildfly.executor.tests.WildflyRuntimeTest.waitForAppBuildTest
```

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by paulovmr** [comment]
Jenkins please retest this.

**Comment by paulovmr** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
The broken test is not related to this PR:
```
org.kie.workbench.common.stunner.bpmn.backend.service.indexing.BpmnFileIndexerTest.testBpmnIndexing
```

**Comment by paulovmr** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
The broken test is not related to this PR:
```
org.guvnor.ala.wildfly.executor.tests.WildflyRuntimeTest.waitForAppBuildTest
```

**Pull request merged**
