### PR TITLE
RHBPMS-4805: Start form won't render, if it contains fields of BigDecimal, Character, Byte or Short type.

### PR DESCRIPTION
**Pull request by pefernan**
RHBPMS-4805: Start form won't render, if it contains fields of BigDecimal, Character, Byte or Short type.

This PR is part of an ensemble:
https://github.com/kiegroup/kie-wb-common/pull/960
https://github.com/kiegroup/appformer/pull/92

### CODE REVIEW

**Comment by pefernan** [comment]
@jsoltes could you take a look?

**Comment by jsoltes** [comment]
jenkins execute full downstream build

**Comment by jsoltes** [comment]
jenkins execute full dowstream build

**Comment by jsoltes** [comment]
jenkins execute full downstream build

**Comment by jsoltes** [comment]
one more because of the errai/errai#268 > jenkins execute full downstream build

**Pull request merged**
