### PR TITLE
DROOLS-1946: DMN Editor

### PR DESCRIPTION
**Pull request by manstis**
Moving my fork into ```kiegroup/master``` to facilitate improved ongoing development and contribution.

The DMN Editor is not added as a dependency to any downstream webapp so remains "invisible".

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
