### PR TITLE
RHPAM-3131 - Stunner - Case Management properties are missing in Case definition

### PR DESCRIPTION
**Pull request by Josephblt**
Due to performance reasons, in some cases, elements were not refreshed after field changes preventing the evaluation of their filters.
This fix consists of a mandatory refresh for any elements with available filters.

**JIRA**:
[RHPAM-3131](https://issues.redhat.com/browse/RHPAM-3131)

**Artifacts**:
[Business Central](https://drive.google.com/file/d/17oDO890_mvwcZWUq9n9rggKrOFS_ogLz/view?usp=sharing)

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins run cdb

**Comment by Josephblt** [comment]
Hello @LuboTerifaj. The war is in the PR description. Thanks.

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @Josephblt ,

Ad-hoc property should be set to true instead of false as described in [RHAPM-3131](https://issues.redhat.com/browse/RHPAM-3131).

Otherwise it looks good to me.

Thanks!

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Hello @LuboTerifaj, all set now. The artifacts are in the PR description. Thanks.

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fd
Jenkins retest thisb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by LuboTerifaj** [comment]
Hello @Josephblt ,

it is not possible to open Case Management (Preview asset). Runtime exception occurs:
`java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException:-1`

I checked it on master and there is also exception, but a different one:
`java.lang.RuntimeException: java.util.NoSuchElementException:No value present`

Would it be possible to fix it in this PR?

Thanks!

**Comment by LuboTerifaj** [comment]
@Josephblt , regarding my previous comment, if you prefer to not include the fix in this PR, I can report it in separate issue of course.

**Review by LuboTerifaj — APPROVED** [review]
The issue mentioned in my previous comments is reported here: https://issues.redhat.com/browse/JBPM-9350

I didn't find any more issues.

**Pull request merged**
