### PR TITLE
Clean up kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client dependencies

### PR DESCRIPTION
**Pull request by jomarko**
@mareknovotny may I ask you for a review once the full downstream build is green?

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Failed tests:
```
org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testStandaloneEditorPerspective
```

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Failed tests:
```
org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded
org.kie.wb.selenium.ui.LoginIntegrationTest.loginAndLogout
org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testStandaloneEditorPerspective
```

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@mareknovotny could you please merge?

**Comment by jomarko** [comment]
@mareknovotny I guess this is fine to merge, even now when master is "broken" due to ip-boms upgrade. But leaving decision up to you.

**Pull request merged**
