### PR TITLE
DROOLS-2548 : java.lang.IllegalStateException: Unknown PartType: dialect

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-2548

https://github.com/kiegroup/kie-wb-common/pull/2762
https://github.com/kiegroup/drools-wb/pull/1194

### CODE REVIEW

**Comment by Rikkola** [comment]
@manstis @Bonuseto Here, instead of adding support for the attributes I reused the list of ignored attributes the rest of the rule assets use. This is since at the moment we do not do any searches with these attributes.

**Comment by Rikkola** [comment]
jenkins execute full downstream build

**Comment by Bonuseto** [comment]
jenkins execute full downstream build

**Comment by Rikkola** [comment]
@kkufova Here is another bundle if you don't mind.

**Comment by Rikkola** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
@Rikkola Please give me a nudge when this is ready for merge (looks like you're waiting for a FDB?)

**Comment by Rikkola** [comment]
@manstis This can be merged. The reason I started the FDB was just to get wars for faster testing.

**Pull request merged**
