### PR TITLE
[7.7.x] Stunner - throwing intermediate events tests (#1633)

### PR DESCRIPTION
**Pull request by LuboTerifaj**
(cherry picked from commit 9e691ba)

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
Hi @romartin 
Can you please have a look?
Thank you.

**Comment by romartin** [comment]
Hey @LuboTerifaj 
Will close this PR as we're on blockers only mode. Also because it's already merged. Lemme know if any issues on closing these kind of PRs only about tests for `7.7.x`, we can reopen and merge if necessary, np.

**Comment by hasys** [comment]
Hi @romartin,

In my opinion tests only changes can't introduce new regressions. Also, we need tests merged and executed on our Jenkins with 7.7.x build to attach it to report about designer verification. So, I guess we can merge this PR with tests and any further tests only PRs as well.

**Comment by romartin** [comment]
Hey @hasys @LuboTerifaj 
Yeah I'm agree on merging just tests, but lemme just double check this with @etirelli and @krisv  - can we merge PRs in 7.7.x if they're only about tests? Although not having the ACKs?

**Comment by etirelli** [comment]
Yes, test and docs PRs can always be merged.

**Comment by romartin** [comment]
Reopening

**Pull request merged**
