### PR TITLE
AF-1865: [Streamline Development Lifcycle] Fix backguard compatibilities and improve 'dev mode' deployment policy

### PR DESCRIPTION
**Pull request by pefernan**
This change adds some improvements, the changes are:
- Ability to deploy SNAPSHOT and non-SNAPSHOT modules on DEVELOPMENT mode KieServers
- Changed default module version to  1.0.0-SNAPSHOT

This is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-integration/pull/1747
https://github.com/kiegroup/kie-wb-common/pull/2497
https://github.com/kiegroup/kie-docs/pull/1409

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by jhrcek** [comment]
I'm trying to fix TransformerServletTest failures.
I manually disabled "Run Xvnc during build" in kie-wb-common-downstream-pullrequests.
Jenkins execute full downstream build to see if those failures disappear.

**Comment by jhrcek** [comment]
Just got reminded that disabling xvnc entirely in the job will probably cause the selenium tests to fail. I'll let that job finish to confirm that. Starting another build with the following change:
enable xvnc, but use `-Djava.awt.headless=true` in the downstream repos build command.
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@jhrcek thank you!

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Pull request merged**
