### PR TITLE
JBPM-7861: case modeler as an experimental feature

### PR DESCRIPTION
**Pull request by xiezhang7**

### CODE REVIEW

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by xiezhang7** [comment]
Hi @romartin ,

I added the annotation to CaseManagementDiagramEditor and CaseManagementDiagramResourceType.
Could you please check if this is the right?

I don't know how to test it. Do I need to remove some code in order to hide "case modeler"?

Thanks.

**Comment by romartin** [comment]
ok to test

**Comment by romartin** [comment]
Hey @xiezhang7 , as commented see the last comments [on the ticket](https://issues.jboss.org/browse/JBPM-7861), I just added some details there, hope this will help to move forward. Thx!

**Comment by xiezhang7** [comment]
Jenkins execute full downstream build

**Comment by xiezhang7** [comment]
Hi @romartin @hasys @LuboTerifaj ,

I have tested case modeler as experimental feature. I created a doc to describe the behavior: [Case modeler as experimental feature](https://docs.google.com/document/d/1xt01Ku3sMZ9xssO0ZvMPPmII2M_Sz4pD1l0nKvqv4Vk) .

The doc for experimental feature framework is [here](https://github.com/kiegroup/kie-docs/blob/e2db705a64c798b2cf7466961553e9820269a661/doc-content/shared-kie-docs/src/main/asciidoc/Workbench/ExperimentalFeatures/ExperimentalFeatures-section.adoc) .

Please let me know if there is any problem.

Thanks.

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Please @LuboTerifaj @hasys this is also urgent... can you please take a look ASAP? Thanks!

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins retest please

**Comment by xiezhang7** [comment]
Jenkins execute full downstream build

**Comment by xiezhang7** [comment]
Jenkins retest please

**Comment by xiezhang7** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@hasys I'm checking this right now, gimme a min

**Comment by pefernan** [comment]
@hasys did you tried it with the latest changes?

**Comment by hasys** [comment]
Hi @pefernan, no, TBH I missed it, I thought PR is in final state and did review with version before new changes were applied. So now, I can see @xiezhang7, sent some changes so, lets wait for full downstream and test it again. Sorry for inconvenience.

**Comment by pefernan** [comment]
@hasys I'm building locally to see if I can test it. I fixed an error that could explain #1
#2 is normal, with the resource enabled it is possible to create it but it should open the default editor (but no error should appear)

**Comment by xiezhang7** [comment]
Hi @hasys ,  
I saw the broken downstream build was fixed, but I could not rebuild this pull request. 
Then I rebased the branch to include the latest changes in master branch, so that this pull request would be rebuilt.
So I didn't really change anything. But it now contains the latest changes in master.

**Comment by pefernan** [comment]
@hasys 
1.- it seems that the Case Management Resource Type is not experimental, so the new AssetScreen always will be present on the list
2.- it seems that AbstractProjectDiagramNewResourceHandler is making a placemanager.goto specifying the editor id instead of using the resource path, that is causing the ActivityNotFoundException, we should check if specifying the editor is necessary. Making a goto to an experimental activity (disabled) causes that. This is a known limitation
3.- Already explained, if assets exist they appear on the library and project explorer. If you think we might change this we can open a JIRA and fix it for next sprint

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins retest this

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
Failing tests are unrelated:
```
Test Result (3 failures / -1)
org.kie.workbench.common.screens.server.management.backend.EmbeddedControllerIT.testEmbeddedEndpointsUsingRest
org.kie.workbench.common.screens.server.management.backend.EmbeddedControllerIT.testEmbeddedNotificationsUsingWebSocket
org.kie.workbench.common.screens.server.management.backend.EmbeddedControllerIT.testEmbeddedEndpointsUsingWebSocket
```

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by manstis** [comment]
@pefernan Merged as we know the builds will fail....

@mswiderski has stated the tests will fail until [this](https://github.com/kiegroup/kie-wb-common/pull/2242) is merged.

**Pull request merged**
