### PR TITLE
Clean up kie-wb-common-dmn-client dependencies

### PR DESCRIPTION
**Pull request by jomarko**
@mareknovotny may I ask you for a review once full downstream build is green?

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by mareknovotny** [comment]
3 failed tests are very the same on both of your PRs, I think they are not related. 
The FDB failure seems to me known too

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@mareknovotny so, do you think it is fine to merge or should I get green full downstream build?

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
have you tried to run locally these 3 selenium tests too?

**Comment by jomarko** [comment]
@mareknovotny I did, however not with changes from this PR. I used master as the tests fails on plenty PRs. Not just mine. Picture show what command I used to run tests and the build passed message.

Screenshot from 2019-06-19 15-28-31

**Comment by jomarko** [comment]
Failed tests:
```
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testContentManagerPerspective
org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testStandaloneEditorPerspective
```

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@mareknovotny could you please merge?

**Pull request merged**
