### PR TITLE
AF-1113: Display Git external URLs on Project Settings

### PR DESCRIPTION
**Pull request by tiagobento**
See: https://issues.jboss.org/browse/AF-1113

1113-gif

### CODE REVIEW

**Comment by ederign** [comment]
@tomasdavidorg this PR is WIP, @tiagobento is working on a suggestion for UXD

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by tiagobento** [comment]
@ederign @porcelli @tomasdavidorg UX changes applied.

**Comment by tiagobento** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
@tiagobento please ping me as soon as you fix the conflicts.

**Comment by tiagobento** [comment]
@ederign Resolved.

**Pull request merged**
