### PR TITLE
JBPM-9276 - Stunner Empty ErrorRef for the Error Start Event produces build errors

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin,

I tested Kogito and XML looks good, will build Business Central locally to perform some End to End tests and will move it to full review. For now code is ready for the review.

Hi @domhanak, @LuboTerifaj, do we need your review here or we can assign it to two Software Engineers?

Thank you!

## Business Central
https://drive.google.com/file/d/1OUikD9cxc008URF85eLjrfggPVueKLTK/view?usp=sharing

## VS Code extension
https://drive.google.com/file/d/1ZvjXoy2St0A_J1gSXiQsxsgVmVFqUfVo/view?usp=sharing

## Repository for tests
https://github.com/bpmn-tutorials/EmptyErrorTest

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute compile downstream build

**Comment by hasys** [comment]
Hi @romartin, @LuboTerifaj, @domhanak,

I noticed some differences between XMLs generated by Legacy and New designers:
* Legacy designer using only one shared Error xml node for all Events with empty error reference.
* Stunner generates individual Error xml nodes for each Event with empty error reference.

I didn't found any differences at runtime though. I used [this](https://github.com/bpmn-tutorials/EmptyErrorTest/) (also mentioned in PR description) repo to test several Error Events at runtime and both processes (generated in Legacy and in Stunner) produced the same result:

**Console log for the process created in the Legacy designer**
```
12:03:13,647 WARN  [org.kie.server.services.jbpm.ui.FormServiceBase] (default task-19) Unable to find form to render for process 'LegacyNoNameErrorHandling'
12:03:14,571 INFO  [stdout] (default task-19) Script2: error handling
12:03:14,632 INFO  [stdout] (default task-19) Script3: error handling
```

**Console log for the process created in the Stunner**
```
12:03:19,280 WARN  [org.kie.server.services.jbpm.ui.FormServiceBase] (default task-19) Unable to find form to render for process 'StunnerNoNameErrorHandling'
12:03:20,254 INFO  [stdout] (default task-19) Script3: error handling
12:03:20,264 INFO  [stdout] (default task-19) Script2: error handling
```

Since I can't see any difference at runtime and I didn't found any information in BPMN 2.0 specification how empty error reference should be addressed I think there is no need to fix it in this PR.

Thank you! This PR is ready for the review.

**Comment by hasys** [comment]
@romartin this PR is ready for merge.

@romartin, @domhanak thank you!

**Comment by romartin** [comment]
thanks a lot for the great work guys! 
@hasys @domhanak

**Pull request merged**
