### PR TITLE
DROOLS-5128: Update com.google.elemental2 and com.google.jsinterop versions

### PR DESCRIPTION
**Pull request by jomarko**
Ensemble:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1259
- https://github.com/kiegroup/appformer/pull/936

For more details see https://issues.redhat.com/browse/DROOLS-5128

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Unrelated test failure:
`org.kie.wb.test.rest.functional.ProjectIntegrationTest.testCreateProjectMinimal`

The build passed on `droolsjbpm-build-bootstrap` part

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Ready for re-review

**Comment by ederign** [comment]
@barboras7 can you kindly review also this one? there is a green build on appformer one.

**Comment by ederign** [comment]
@jesuino could you please also review this one?

**Pull request merged**
