### PR TITLE
[7.23.x] JBPM-8445: Stunner -  unable to set cycle timer with cron expression

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit 65d2735ccca46d6a8f47d4daaeaac5f9d787ca87)

depends on:

https://github.com/kiegroup/kie-soup/pull/105
https://github.com/kiegroup/drools/pull/2447

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
@hasys full-bld failed in non related tests but artifacts were generated.

**Comment by wmedvede** [comment]
@romartin @hasys  I've just pushed and additional commit (only a test was modified) for considering the daylight summer time.

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
@romartin  @hasys 

great! this last full-bld is green.

So this is current status:

1) this PR: has the two greens
2) related https://github.com/kiegroup/drools/pull/2447:  has the two greens
3) related https://github.com/kiegroup/kie-soup/pull/105: (local bld green and known issues in the full-bld)

I believe this assembly is ready to go, ideally ASAP before we get into an eventual merge conflict with any other last moment 7.23.x merge, and we have to start this never ending build cycle again.

Thanks!
Thanks!

**Pull request merged**
