### PR TITLE
DROOLS-2394: [DMN Designer] Rename of output changes back to link

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-2394

Video [here](https://www.youtube.com/watch?v=2c8CbigbS-M).

### CODE REVIEW

**Comment by romartin** [comment]
Sorry @manstis waiting for https://github.com/kiegroup/kie-wb-common/pull/1527 to fix the issue. Will fire a rebuild once merged, waiting for J to complete.

**Comment by romartin** [comment]
sorry for the inconveniences, I'm tracking https://github.com/kiegroup/kie-wb-common/pull/1527 too, no worries, once green will merge. Thanks!

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@manstis fixed! Sorry (again)! :+1:

**Comment by manstis** [comment]
@romartin Damn you starting a full downstream... :-(

**Comment by romartin** [comment]
@manstis it's free!! why not? :)

**Comment by jomarko** [comment]
@manstis is there something you hoped will be hidden from full downstream build? :)

jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
