### PR TITLE
BAPL-764: [Stunner] Added missing dependency to forms-backend-services in the showcase modules

### PR DESCRIPTION
**Pull request by romartin**
Hey @pefernan @hasys @jomarko @manstis 

I was not able to run the showcases for BPMN or DMN, I guess that's something related to this https://github.com/kiegroup/kie-wb-common/pull/1492

Anyway no worries, feel free to merge it if it makes sense for you. At least it makes my webapps startt working again. This should not affect the downstream repos.

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
@alepintus @tiagodolphine @evacchi @Josephblt  FYI

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@romartin thank you! I thought I changed all showcases.

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
