### PR TITLE
Fix Windows-specific test failures

### PR DESCRIPTION
**Pull request by mackaypeter**
Some minor fixes for Windows-specific test failures.

### CODE REVIEW

**Comment by manstis** [comment]
@tsurdilo Could you please review/approve.

**Comment by yurloc** [comment]
We're on Java 8. Let's use `System.lineSeparator()` instead of `System.getProperty("line.separator")`. Wdyt @mackaypeter?

**Comment by jhrcek** [comment]
@mackaypeter Could you please rebase this PR onto latest master (and possibly all related PRs)? We don't want to lose all the windows stabilization you did, but we also need the full downstream build of all affected kiegroup repos to pass for this and related PRs. Now it's failing with
```
0 Unexpected error while executing the Downstream repositories builder for PR builds! PR 1204 for repo GitHubRepository{owner='kiegroup', name='kie-wb-common'} is not automatically mergeable. Please fix the conflicts first!
```

**Comment by mackaypeter** [comment]
@jhrcek I think the failure you're referring to occurred before my last commit, but I did another rebase just to make sure.

**Pull request merged**
