### PR TITLE
JBPM-9021: Connector issues: Edge w/o target node fix.

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/JBPM-9021

This PR specifically fixes "[About the error](https://issues.redhat.com/browse/JBPM-9021?focusedCommentId=13967032&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13967032)". i.e. a connector with no target node connected.

### CODE REVIEW

**Comment by jomarko** [comment]
### Acceptance test

- [ ] input -> null
- [ ] decision -> null
- [ ] bkm -> null
- [ ] ks -> null
- [ ] ds -> null
- [ ] decision -> decision
- [ ] input -> decision
- [ ] bkm -> decision
- [ ] ks -> decision
- [ ] input -> decision in ds
- [ ] ds -> decision in ds
- [ ] decison in ds -> decision out of ds
- [ ] decison in ds -> decision in ds

**Comment by mbiarnes** [comment]
@manstis should we wait (in this case) until it is green before merging?

**Comment by manstis** [comment]
Merged ahead of Jenkins to allow release to proceed.

(Confirmed full build succeeds locally).

**Comment by manstis** [comment]
All `kie-wb-common` tests were [green](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-common-pullrequests/1572/testReport/).. Just the two known issues were evident.

**Pull request merged**
