### PR TITLE
[7.5.1] Backport: JBPM-8780, JBPM-8825, JBPM-8784

### PR DESCRIPTION
**Pull request by caponetto**
**Jira**: [RHPAM-2308](https://issues.jboss.org/browse/RHPAM-2308)

**Backport**: 
- [JBPM-8780](https://issues.jboss.org/browse/JBPM-8780)
- [JBPM-8825](https://issues.jboss.org/browse/JBPM-8825)
- [JBPM-8784](https://issues.jboss.org/browse/JBPM-8784)

**Related PRs**:
- https://github.com/kiegroup/appformer/pull/816
- https://github.com/kiegroup/kie-wb-common/pull/2938

### CODE REVIEW

**Comment by caponetto** [comment]
Hi @marcuscarvalho 
I've backported your fixes to branch 7.26.x
Can you please take a look?

**Comment by marcuscarvalho** [comment]
Hi @caponetto 
Are you going to backport these changes too? https://github.com/kiegroup/appformer/pull/803/files

**Comment by caponetto** [comment]
@marcuscarvalho Yep, check this [PR](https://github.com/kiegroup/appformer/pull/816). I also mentioned you there.

**Comment by marcuscarvalho** [comment]
Looks good to me. Thank you @caponetto

**Comment by caponetto** [comment]
Jenkins retest this please

**Pull request merged**
