### PR TITLE
JBPM-7405 Stunner - Improve usability for connector bendpoints

### PR DESCRIPTION
**Pull request by tiagodolphine**
Increase the selection area for the bendpoints
Add a bendpoint with the simple drag action on the connector (UX improvements)
Customize bendpoints and magnets styling (UX improvements)

@LuboTerifaj
@romartin

related https://github.com/kiegroup/lienzo-core/pull/58

### CODE REVIEW

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj thanks for the review ! About your comments:
- Now to add a bend point you should click and drag on the connector. This was done because it was on the JIRA [JBPM-7405](https://issues.jboss.org/browse/JBPM-7405) -> _"In order to improve the connection handling, I think that it's better to add a split point with the simple drag action instead of the double click."_ I kept the double-click as well, but I can remove it if we decide it is better.
- I'll check and fix the unselect of the connector and bend points when selecting another node, this should not happen.
- And the last point, I agree the connection point should be filled (not empty) in this case in the same way as when you select a magnet on the shape, since it indicates that it is connected. I'll fix that.

Thanks!

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj pushed the fixes and the full downstream is ok.

**Comment by tiagodolphine** [comment]
Hey @LuboTerifaj this is ready to review, when you have a chance.
Thanks.

**Comment by LuboTerifaj** [comment]
Hey @tiagodolphine 

Relating to my last point, it also happens, when you create an boundary event on task in sub-process:
_Steps to reproduce:_

1. Create event sub-process for instance
2. Create end event connected with this sub-process
3. Create at least two bend points on this sequence flow
4. Create task inside sub-process or an event. If you created only event (not boundary) go to the step 6
5. Create an boundary event on this task
6. Move with sub-process

Thanks.

**Comment by LuboTerifaj** [comment]
Hi @tiagodolphine 

Just question. I found out, that last issue that I mentioned is also on master. So if you don't have time to fix this, I can open a Jira for that. Just let me know.

Thank you!

**Comment by tiagodolphine** [comment]
Hey @LuboTerifaj about your comments:
* Testing here I'm able to click and drag on the connector to create the bendpoints [video](https://issues.jboss.org/secure/attachment/12439638/bendpoints.webm) what browser are you using on the tests? Do you have any suggestion to improve the usability? now it is necessary some "delay" 150ms after click to drag... I can try to decrese this delay and see if it gets better.
* About the wrong bendpoints movements on subprocess/boundary events I was able to reproduce but as you said this is not related to this PR, so IMO it is better to open a new JIRA for this issue then we can prioritze on the backlog.

**Comment by tiagodolphine** [comment]
Hi @romartin can you help to review this one, this is easy you can do with just one hand :)

**Comment by romartin** [comment]
hey @tiagodolphine @LuboTerifaj thanks for your good work here again!

I just did the review for this and here are my comments:

- when dragging a connection, which is initially attached into some shape's magnet, and dropping into an "empty" area (no magnet, so setting the connection to `null`), the CP is not "filled" until unselecting and selecting the connector again, see the following screenshot. Is that expected or an issue? anyway for me a minor one, if so

screenshot from 2018-08-23 02-19-50

- About the usability improvement for creating new CPs:
-- Agree with @LuboTerifaj - sometimes it works fine and sometimes it doesn't, for me. I mean when clinking and start dragging at some connector's line point, in order to create a  new CP and move it,  sometimes it just creates it, so I've to start dragging again, instead of also updating its location as my initial drag event was at
-- for me still doesn't result intuitive that you can create new CPs by just click+drag on some empty line's segment point. IMO we're missing an small detail, which old designer already does, that is about showing  the actual mouse pointer location, when over a connector, by using some marker. For  example see the following screenshot, did on the old designer, that shows a YELLOW point as while moving the mouse over the line. We could do the same in Stunner/Lienzo, WDYT?

screenshot from 2018-08-23 02-22-53

Now I'm starting the code review...

Anyway it looks great @tiagodolphine , nice job :+1: 

Thanks!!

**Comment by LuboTerifaj** [comment]
Reported issue about moving bend points while moving with activity:
https://issues.jboss.org/browse/JBPM-7677

**Comment by tiagodolphine** [comment]
hey @LuboTerifaj @romartin thanks you both for the review and suggestions.
I removed the timer, so now there will be no delay do click + drag do add the bendpoint + I'm working to add the "transient" bendpoint while the mouse is over the connector. I'll let you know when the PR is updated.
Lubo thanks to open the JIRA.

**Comment by romartin** [comment]
great @LuboTerifaj @tiagodolphine thanks.

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins retest this

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins retest this

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins retest this

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins retest this

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj @romartin I've updated the PR and the full downstream is completed. 
Now there will be a new "transient" bendpoint when the mouse is over the connector indicating that you can create a bendoint in that location. I removed the timer when click/drag to make it faster. I addition I removed the double-click to create a bendpoint, so now the doble-click just removes an existing bendpoint

Thanks.

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hello @tiagodolphine 

I have found one more issue:

If there are two bend points pretty close to the each other, when pointing to the left one, right one is selected. After trying to move with left one, right point is being moved.

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins retest this

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj, about your comments:
- I decreased the delay as much as it worked to have the click to select the connector, otherwise, there will be no way to select the connector, in case the user does not want to create a new benpoint just select the connector. Any other modification or improvement on this I think it is better to open a new JIRA.
- I applied the suggestion to show points on the sequence flow if the mouse is over the connector, in this case, the transient + all other points will be shown, even the connector is not selected. And in case the connector is selected all the points will be shown even if the mouse is not over the connector.l
- Yeah, it is not possible to creat a bendpoint with a simple click, that is used to select the connector, the long click/mouse down + drag is creating the bendpoint.
- The issue with tow bendoints close to each other is better/solved I descreased the selection offset in this way the selection is more accurate, the mouse should be closer to the bendpoints to be selected.
- The issue with 2 sequence flows close to each other should be solved, because there is a control to only show the transient point on one connector.

@LuboTerifaj take this review and let me know if you think this is ok to be merged, I mean if there is no blocker issue, at this point I spent a lot of time on this issue and we need to decide if this is ok to enter on the CR2 or not. Anyway we can make more improvements always and keep them on new JIRAs, my point is if it is worth to include this on the CR2, because I need to go to other issues.

Thanks for all your comments and work on this.

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj thanks again for the review!
I'll take a look on these issues you found if they are simple to fix I'll provide today the fix, but I'll let you know if they got complicated then I suggest to open a new JIRA, let's see.

**Comment by LuboTerifaj** [comment]
Ok @tiagodolphine 

Thank you very much!

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins retest this

**Comment by tiagodolphine** [comment]
Jenkins retest this

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
@LuboTerifaj I pushed the fixes to your last comment, let's see if it is better now, please test with more than one connector over each other and the bendpoints.
Thanks.

**Comment by LuboTerifaj** [comment]
Hello @tiagodolphine 

I have found four issues totally, but I will open Jira for three of them, because they are not blockers and I think, they are more likely about UX.
I will do that as soon as there will be no Jira outage. I will also link them to this PR.

Unfortunately there is one issue, which is not present on master and need to be fixed. I am sorry, that I didn't catch it earlier.

- Undo operation for bend points does not work as expected. If there is one bend point on sequence flow, after undo operation, the sequence flow has the same source and target (start event on the picture).
Before:
screenshot from 2018-09-07 10-38-10
After:
screenshot from 2018-09-07 10-38-37

If there are more than one bend points, target of sequence flow is canvas.
Before:
screenshot from 2018-09-07 10-39-08
After:
screenshot from 2018-09-07 10-39-18


It is also not possible to do redo action after that. An error window is displayed.
screenshot from 2018-09-07 11-03-37

Thank you!

**Comment by LuboTerifaj** [comment]
Hi @tiagodolphine 

As promised, here you can find reported issues: https://issues.jboss.org/browse/JBPM-7733

Thanks.

**Comment by tiagodolphine** [comment]
Jenkins retest this

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj updated the PR with the fix to the undo/redo issue, great catch, by the way, this error was caused by the order on the commands being executed.

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj thanks for all the reviews 

@romartin I applied your comments as well, is it ok for approval? 
@wmedvede since @romartin is not able to review all the PRs, can you give a quick look on this, just o have other developer approval.
Thanks.

**Comment by tiagodolphine** [comment]
Hi @manstis now the PR is approved, can you please merge it when you have a chance.
Thanks.

**Comment by tiagodolphine** [comment]
@manstis indeed, I asked if @wmedvede can approve that since he had made the review on this one. 
I'll let you know when I got the approval. 
thanks !!

**Comment by wmedvede** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
@wmedvede @manstis it is green again

**Pull request merged**
