### PR TITLE
JBPM-8168: switch between case and process

### PR DESCRIPTION
**Pull request by xiezhang7**
Assembly:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/956
https://github.com/kiegroup/kie-wb-common/pull/2645
https://github.com/kiegroup/kie-wb-distributions/pull/922

### CODE REVIEW

**Comment by xiezhang7** [comment]
Assembly:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/956
https://github.com/kiegroup/kie-wb-common/pull/2645
https://github.com/kiegroup/kie-wb-distributions/pull/922

**Comment by xiezhang7** [comment]
Jenkins execute full downstream build

**Comment by xiezhang7** [comment]
Hi @romartin @LuboTerifaj , this pull request is for [JBPM-8168](https://issues.jboss.org/browse/JBPM-8168). Thanks.

**Comment by romartin** [comment]
Hey @xiezhang7 

Cannot compile it locally neither :(

```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-1:testCompile (default-testCompile) on project kie-wb-common-stunner-project-client: Compilation failure: Compilation failure: 
[ERROR] /home/roger/development/romartin/kie-wb-common/kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditorTest.java:[407,24] method addMainEditorPage in interface org.kie.workbench.common.widgets.metadata.client.KieEditorWrapperView cannot be applied to given types;
[ERROR]   required: com.google.gwt.user.client.ui.IsWidget
[ERROR]   found: org.kie.workbench.common.stunner.project.client.editor.AbstractProjectDiagramEditor.View,java.util.Optional<java.lang.String>
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] /home/roger/development/romartin/kie-wb-common/kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditorTest.java:[445,24] method addMainEditorPage in interface org.kie.workbench.common.widgets.metadata.client.KieEditorWrapperView cannot be applied to given types;
[ERROR]   required: com.google.gwt.user.client.ui.IsWidget
[ERROR]   found: org.kie.workbench.common.stunner.project.client.editor.AbstractProjectDiagramEditor.View,java.util.Optional<java.lang.String>
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] /home/roger/development/romartin/kie-wb-common/kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-project/kie-wb-common-stunner-project-client/src/test/java/org/kie/workbench/common/stunner/project/client/editor/AbstractProjectDiagramEditorTest.java:[470,24] method addMainEditorPage in interface org.kie.workbench.common.widgets.metadata.client.KieEditorWrapperView cannot be applied to given types;
[ERROR]   required: com.google.gwt.user.client.ui.IsWidget
[ERROR]   found: org.kie.workbench.common.stunner.project.client.editor.AbstractProjectDiagramEditor.View,java.util.Optional<java.lang.String>
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
```
Please let us know when compilation works and builds are generating artifacts.

Thanks!

**Comment by xiezhang7** [comment]
Jenkins execute full downstream build

**Comment by xiezhang7** [comment]
> [ERROR]     'dependencies.dependency.version' for org.kie.workbench.stunner:kie-wb-common-stunner-case-mgmt-project-backend:jar is missing. @ org.kie.workbench.stunner:kie-wb-common-stunner-showcase-project:[unknown-version], /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-downstream-pullrequests/kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project/pom.xml, line 769, column 17

@romartin @LuboTerifaj It seems pull request https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/956 doesn't work for the build, although I added the "[Assembly](https://github.com/kiegroup/kie-wb-common/pull/2645#issuecomment-493171288)" comment.

**Comment by xiezhang7** [comment]
Jenkins execute full downstream build

**Pull request closed without merging**
