### PR TITLE
FIX-MASTER-BPMN_STAND-ALONE-TEST: Fixes Compilation Error while runinng tests due to constructor not being found

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin can you review and approve this PR ASAP as it is an issue on master?

### CODE REVIEW

**Comment by inodeman** [comment]
Jenkins execute full downstream build.

**Comment by inodeman** [comment]
Jenkins execute full downstream build.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins execute full downstream build.

**Comment by domhanak** [comment]
@romartin @inodeman Please update or close this PR.

**Comment by romartin** [comment]
yeah @inodeman , does this still applies? if so, can you please rebase and update it? Thanks!

**Comment by mareknovotny** [comment]
is this still relevant PR? Rebase and update it if possible otherwise CLOSE it!

**Comment by romartin** [comment]
hey @inodeman 
Is this PR still relevant?

**Comment by inodeman** [comment]
Closing, not relevant anymore

**Pull request closed without merging**
