### PR TITLE
JBPM-9536 After click refresh button, the container will disable

### PR DESCRIPTION
**Pull request by bxf12315**
**Thank you for submitting this pull request**

**JIRA**: [JBPM-9273](https://issues.redhat.com/browse/JBPM-9273)

**Referenced Pull Requests**:
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://donwnload.here/something)

**VS Code**: [plugin](https://donwnload.here/something)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by bxf12315** [comment]
jenkins do cdb

**Comment by prashuts** [comment]
jenkins do fdb

**Comment by bxf12315** [comment]
jenkins do fdb

**Comment by prashuts** [comment]
jenkins do fdb

**Comment by prashuts** [comment]
Verified with following cases  :-
1**.Project - Evaluation Process**
        Cases : _Deploy , start , stop , Refresh , Remove , Deactivate_
2.**Project - Mortgages**        
		Cases : _Deploy , start , stop , Refresh , Remove, Deactivate_
3.**Empty Project (No asset)**
		Cases : _Deploy , Start , Stop , Refresh , Remove, Deactivate_
4.**Non Existing Containers -** 
		Case _Deploy_: Add Deployment Unit and see failure popup 'The 'Start Deployment Unit' operation has failed in 1 server instance(s).' and expected Rest response
			 <response type="FAILURE" msg="Container dummy is not instantiated."/> ,
		Case _Start_ - Button Disabled
		Case _Stop_ - Button Disabled
		Case _Deactivate_- Button Disabled
		Case _Remove_ - Expected Deployment unit must be deleted

**Review by prashuts — APPROVED** [review]

**Pull request closed without merging**
