### PR TITLE
AF-2056 and AF-2057

### PR DESCRIPTION
**Pull request by paulovmr**
AF-2056: Error dialog when adding space contributor [Cat1]
AF-2057: Verify graceful degradation for users list on authoring

Now it is possible to insert any name when adding/editing a space contributor, the users are only suggested during typing. This was done because it is not guaranteed that the list of users will be available for query in any environment.

Part of an ensemble:
* https://github.com/kiegroup/appformer/pull/727
* https://github.com/kiegroup/kie-wb-common/pull/2736

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by ederign** [comment]
@tomasdavidorg I added @barboras7 here because is on contributors side.

If you can verify that this also fix 2056 it would be awesome.

**Comment by barboras7** [comment]
Hi @ederign,

@tomasdavidorg will take care of both this PR and [the related PR](https://github.com/kiegroup/appformer/pull/727) as they are both related to HA

**Comment by ederign** [comment]
please jenkins execute the full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by domhanak** [comment]
jenkins execute full downstream build

**Pull request merged**
