### PR TITLE
AF-1199: Batch mode of migration tool does not ignore pom migration p…

### PR DESCRIPTION
**Pull request by tomasdavidorg**
…rompt

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
@desmax74 @mbarkley Could you please have a look?

**Comment by tomasdavidorg** [comment]
For 7.7.x https://github.com/kiegroup/kie-wb-common/pull/1788

**Comment by desmax74** [comment]
@tomasdavidorg which is the purpose of the change ? If you want to skip entirely the pom migration you could do in the run method, avoiding the execution of the migrate method

**Comment by tomasdavidorg** [comment]
@desmax74 It is a definition of the batch mode which should do all the task without human intervention.
@mbarkley I am currently writing some tests for the tool so I would keep the mode because of testing purposes.

**Comment by desmax74** [comment]
@tomasdavidorg is ok from my side

**Comment by tomasdavidorg** [comment]
This has been already merged with https://github.com/kiegroup/kie-wb-common/pull/1876. Closing this.

**Pull request closed without merging**
