### PR TITLE
JBPM-9840 - Review container status refresh

### PR DESCRIPTION
**Pull request by cristianonicolai**
**Thank you for submitting this pull request**

**JIRA**: [JBPM-9840](https://issues.redhat.com/browse/JBPM-9840)

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins run fdb

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins run fdb

**Review by bxf12315 — APPROVED** [review]

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by bxf12315** [comment]
jenkins please retest this

**Comment by sutaakar** [comment]
@cristianonicolai In `production` mode with active process instance when you click on Stop button for container, the Kie server container fails to stop (that is expected), however the BC UI considers the container as stopped:
image
In such case it is possible to click on Remove button, causing an error and putting BC UI into inconsistent state (UI shows no containers in Execution servers page but clicking on Kie server shows existing container).

**Comment by cristianonicolai** [comment]
@sutaakar I think the issue there is that on that page, we're removing a container config/definition. Meaning that any other kie server won't start it or will remove it. In the server details page, we drill down into a server specific. In there it makes sense that is showing a container instance that could not be removed. I believe that if you try this via REST API, the behaviour would be the same.

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins run fdb

**Comment by cristianonicolai** [comment]
jenkins run fdb

**Comment by cristianonicolai** [comment]
jenkins run fdb

**Review by sutaakar — APPROVED** [review]

**Pull request merged**
