### PR TITLE
[7.44.x] Revert "DROOLS-5458 : Project broken after test scenario run with possibly a class-loading issue"

### PR DESCRIPTION
**Pull request by Rikkola**
DROOLS-5743 : Performing test is slow in Business central

This reverts commit 04764c519223089c0fc16c6824e0d1a94ceeeee6.

(cherry picked from commit f62373cc0d0e714b0eac2adf90cacc347ac641ab)

Revert "DROOLS-5458 : Project broken after test scenario run with possibly a class-loading issue"

DROOLS-5743 : Performing test is slow in Business central

**JIRA**: [DROOLS-5743](https://issues.redhat.com/browse/DROOLS-5743)

**Referenced Pull Requests**:
* https://github.com/kiegroup/kie-wb-common/pull/3485
* https://github.com/kiegroup/drools-wb/pull/1442

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
jenkins retest this

**Comment by yesamer** [comment]
jenkins retest this

**Review by yesamer — APPROVED** [review]

**Comment by yesamer** [comment]
Asked @karreiro to review it in order to have 2 eng. approvals

**Comment by yesamer** [comment]
jenkins retest this please

**Review by karreiro — APPROVED** [review]
Thank you, @Rikkola!

**Review by tomasdavidorg — APPROVED** [review]

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers Can I get a merge please.

**Comment by manstis** [comment]
@Rikkola Same question about the "Maven Build (8)" check.

**Comment by Rikkola** [comment]
jenkins retest this

**Comment by Rikkola** [comment]
@manstis And green here. I could use a merge thank you.

**Pull request merged**
