### PR TITLE
JBPM-6315 - JBPM-6404 RadioGroup and ListBox widgets not being set

### PR DESCRIPTION
**Pull request by alessioscalici**
**WARNING** this is the same as https://github.com/kiegroup/kie-wb-common/pull/1179, pointing to 7.3.x

This PR fixes both the following issues:

https://issues.jboss.org/browse/JBPM-6315
https://issues.jboss.org/browse/JBPM-6404

@pefernan @jsoltes could you please review?

### CODE REVIEW

**Comment by jsoltes** [comment]
jenkins execute full downstream build

**Comment by jsoltes** [comment]
@alessioscalici @pefernan ad JBPM-6315 issue, there is one more thing that could be improved. I am getting this error, when I put a number that is out of boundaries of Integer:
image
I think there could be something more readable like: Please input integer...

**Comment by pefernan** [comment]
@jsoltes are you using new forms or reusing an old project forms?

**Comment by jsoltes** [comment]
@pefernan this happens also when i generate new forms

**Comment by pefernan** [comment]
@jsoltes got it, I think that error is not related to this issue, I should check but I guess it might happen on master. I think that the converters for numerics widgets are breaking, I'll check how to deal with that.

**Comment by pefernan** [comment]
@jsoltes can we create a specific JIRA for that issue. I see that's a generic issue not related to this PR

**Comment by jsoltes** [comment]
@pefernan ok

**Comment by pefernan** [comment]
so @jsoltes is it ok to merge?

**Comment by pefernan** [comment]
@alessioscalici thank you

**Pull request merged**
