### PR TITLE
[7.30.x] JBPM-8835 : Improve performance of Copy / Paste, Click Performance, Dragging, Creating, Sequence Flow Create and More

### PR DESCRIPTION
**Pull request by inodeman**
This is the cherry pick for https://github.com/kiegroup/kie-wb-common/pull/2983

### CODE REVIEW

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by inodeman** [comment]
Hi @mareknovotny build aborted for timeout, can you increase it?

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by romartin** [comment]
Hey @mareknovotny @mbiarnes 
Plz there are a few PRs, like this one, in which the regular J builds are failing due to timeout issues (`"Build timed out (after 120 minutes). Marking the build as aborted"`). Please we need to the successful builds in order to merge this today, can you please take a look or increase the timeout values, if you think so? Thx in advance!

**Comment by mareknovotny** [comment]
guys @inodeman @romartin the build is now green, but generally we should not increase timeout just because it is hit
The root cause why it was hit is more important and where in the build.
If we do increase everytime it is hit it could be that in the build is problem in an analysis or test itself, like concurrent access or some other problem. 2 hours for anything could be enough for any component build or we need to have a justification for that.

**Comment by hasys** [comment]
@mareknovotny it is kind of game I remember we already increase several times timeouts and it was decreased back by someone, we increasing and someone decreasing. I remember Full Downstream Build took about 4 hours some time ago. Was it really so improved that 2 hours is good enough now?

**Comment by hasys** [comment]
Hi @inodeman,

looks and works good now, but I found one regression, see:
* [RHPAM-2536](https://issues.jboss.org/browse/RHPAM-2536) - gateways default route dropdown options are not populated after gateway created 

I think it shouldn't block this PR from merging.

What remains TO DO:
* Finish spreadsheet with numbers what was improved
* Update Requirements with information what was actually done
* Notify Doc team (and update Requirements as well) about HiDPI enabled by default, it is quite big change and should be mentioned in release notes for sure.
* Fix mentioned bug as separate PR on master.

Thank you Jaime!

### Check list
- [x] ACKs are set
- [x] Affected version is set property
- [ ] Doc team notified?
- [ ] Is realization aligned to jira description?
- [x] Are DMN and CM verified?
  - [x] DMN
  - [x] CM
- [x] Both Jenkins jobs are green

### Code review
- [x] Code coverage
- [x] License headers
- [x] Static analyser gates
- [x] Code Style

### Acceptance Criteria
> Numbers can be found in [Spreadsheet](https://docs.google.com/spreadsheets/d/1RpKQOFdKmNhSpTyJpzAhfM9xSveTB73x53UNxl_Ha3E) and in [Doc](https://docs.google.com/document/d/1fnBWesk3esequngxU08GOTbrVXX4cRUq_oo59Krnh9Y/edit)
> Regression testing with the different canvas areas:
> * Basic operations: All nodes types and annotation can be added, morphing, connecting, quick menu working, forms works
> * Advanced operations: containment, boundary events, canvas navigation, runtime, validation, copy-paste
> * Work with two processes at the same time
> * Basic process executed at runtime

- [x] Tested with full downstream build
  - [x] Firefox
  - [x] Chrome

### Found issues
>  **Blocker**, **Critical** and **Major** bugs and **Blocker** and **Critical** enhancements should be fixed before merge.
* [RHPAM-2536](https://issues.jboss.org/browse/RHPAM-2536) - gateways default route dropdown options are not populated after gateway created 


### Used resources
Processes for quick test can be found here: Large process from the [Performance issue](https://issues.jboss.org/browse/RHPAM-1976) can be used for testing.

**Comment by mareknovotny** [comment]
@hasys I am not aware there were someone changing timeouts at all.

https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-common-pullrequests/configure-readonly/ shows the timeout is set to elastic value of 250% of previous green build(s) and if there is no successful build it will use 120 minutes. And that is the default value for all jobs and the case in this 7.30.x branch as there were no green build for long time.

**Comment by hasys** [comment]
@mareknovotny ok, anyway it looks like 120 minutes for timeout is not enough, if build takes 119 minutes.

**Comment by mareknovotny** [comment]
tagging @mbiarnes here for raising the default

**Pull request merged**
