### PR TITLE
[7.26.x] DROOLS-4545: Do not show Analysis Complete for Illegal Verifier State…

### PR DESCRIPTION
**Pull request by jomarko**
… (#2914)

This is cherry-pick of a commit https://github.com/kiegroup/kie-wb-common/commit/dbb3976a347f7ea62f986e54b54a25500d35b1c2

Dependent on: #2952

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Failed test
```
 org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded
```

jenkins execute full downstream build

**Comment by Rikkola** [comment]
Again. This I don't think we can ignore or remove since it is Selenium. If we fix this the second Selenium test we have will fail and so on until there are 0 left.

> org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@mareknovotny this was small enhancement that is not crucial for DROOLS-4545-7.26.x. As the cut-off for 7.5.1 is gone, should I close this?

**Comment by jomarko** [comment]
@mareknovotny does the thumb up mean you vote for closing?

**Comment by mareknovotny** [comment]
@jomarko yes, I can't access now jboss.org jira, but the jira issues was moved from 7.26.x if i recall correctly so backporting is not needed

**Comment by jomarko** [comment]
Closing due to the comment above.

**Pull request closed without merging**
