### PR TITLE
[7.x] RHPAM-3480 : Error logged if reusable subprocess has some dataInput mapping but no dataOutput mapping in stunner

### PR DESCRIPTION
**Pull request by inodeman**
**Thank you for submitting this pull request**

**JIRA**: [JBPM-0000](https://issues.redhat.com/browse/JBPM-0000)

**Referenced Pull Requests**:
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://donwnload.here/something)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by romartin** [comment]
hey @inodeman @LuboTerifaj 
How is this going guys? We're close to deadlines again, please let's consider this a priority. 
Thanks!

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by inodeman** [comment]
Hi @romartin @LuboTerifaj  fdb is failing for something unrelated as shown n screenshot. The provided war seems to have issues as  Lubo also experienced issues on Wildfly23 as I did. I will retrigger

**Review by LuboTerifaj — APPROVED** [review]
Hello @inodeman , the business-central.war is finally generated properly. I didn't find any issues. Thanks!

**Comment by romartin** [comment]
thanks guys!

**Pull request merged**
