### PR TITLE
JBPM-5643: Stunner - Add Catching Intermediate Signal Event

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
This is the random failing tst, this time.

org.kie.workbench.common.stunner.bpmn.backend.service.indexing.BpmnFileIndexerTest.testBpmnIndexing

java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at 

Hello @hasys  sorry for the inconvenient (and for bothering), but following @manstis directions could you please add the @Ignore to the tst above, and take a look if there's a way to improve the random failing. I could see that you had done some there. Locally worked well, but seems to still have a piece of random failure effect.

Thanks.

**Comment by wmedvede** [comment]
In mean time let's give this PR another try.

jenkins retest this

**Comment by jhrcek** [comment]
@wmedvede We've known for a long time (and confirmed by collecting some test failure statistics, see http://janhrcek.cz/random-failures/) that these indexing tests are failing randomly. @ederign promised he'd take a look at those failures soon and in cooperation with him QE would propagate his fix to other repositories. There are about 20 tests across the codebase failing for similar reason.

**Comment by wmedvede** [comment]
@romartin @manstis Seems like there's green right now. I'd suggest to merge this already approved PR.
(well, the approvals are really here https://github.com/kiegroup/kie-wb-common/pull/1261)
Thanks

**Pull request merged**
