### PR TITLE
Fix for ECJ - GWT conflict

### PR DESCRIPTION
**Pull request by manstis**

### CODE REVIEW

**Comment by wmedvede** [comment]
@manstis could you finally start the showcases in SDM? I could never make them run locally, I'm always getting 
`r.bpmn.definition.EndTerminateEvent.description]
[ERROR] java.util.concurrent.ExecutionException: java.lang.RuntimeException: The following dependency problems were found:
[ERROR] 	Unsatisfied constructor dependency @Default org.kie.workbench.common.stunner.bpmn.factory.BPMNGraphFactory for Class @Any @Default org.kie.workbench.common.stunner.cm.factory.CaseManagementGraphFactoryImpl.
[ERROR] 
[ERROR] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[`

**Comment by manstis** [comment]
@wmedvede I had the same error here; but weirdly building master (with the ecj version upgrade rolled back) and then master again (with the ecj upgrade) and this PR it worked fine. I'll try again tomorrow with .m2 deleted...

**Comment by Rikkola** [comment]
If this fixes the build I think we can merge it in for now and then fix the exceptions.

**Comment by domhanak** [comment]
@Rikkola Yes, please! + 1 for merging this asap, builds are red for 3 days now on every PR

**Comment by mareknovotny** [comment]
@manstis can we merge this? or you still are verifying the PR?

**Comment by manstis** [comment]
@mackaypeter @wmedvede @Rikkola @porcelli Whilst the ECJ fix works for most webapps it breaks Stunner (BPMN, CM, -project and -standalone). I've been trying to find a solution however at present found nothing. I spoke to @etirelli about it as I need to get back to DMN JIRAs. So, we can merge all these PRs but Stunner will be broken.

**Comment by manstis** [comment]
@mackaypeter @wmedvede @Rikkola @porcelli This [commit](https://github.com/kiegroup/kie-wb-common/pull/2099/commits/1f3bb2da660ab6df26edd714756b4ae5a59defef) fixes showcase-standalone. Please verify and duplicate on showcase-project.

**Comment by jomarko** [comment]
I can confirm this fixes **kie-wb-common-dmn showcase** and **kie-wb-common-stunner standalone showcase**, while **kie-wb-common-stunner project showcase** can be compiled but not run as **mvn clean gwt:run**.

**Comment by manstis** [comment]
@jomarko I've not completed the same changes to **project** showcase. I'd hoped someone else may have done it while I was at my daughters school.. but I'm doing it now and will add a new commit.

**Comment by jomarko** [comment]
@manstis I just put comment to keep information flow, I was trying to understand how this exclusion helps by looking into **mvn dependency:tree** before I would just blindly copy your changes to projects showcase. But have to admit, even trying hard, still not sure how this works.

**Comment by manstis** [comment]
@jomarko @wmedvede @gitgabrio This PR now contains fixes (verified to work, ```mvn clean process-resources gwt:run```) for both ```-standalone``` and ```-project``` stunner showcases. If you can verify too; then this PR can be merged.

**Comment by manstis** [comment]
Reverted my last 2 commits as they did not fix ```-project```

If this build goes "green" I'll merge so ```master``` at least compiles and we'll need to fix later :-(

**Comment by wmedvede** [comment]
@manstis yes, I couldn't make run the project showcase with the 3rd commit. +1 to rolling back and not block the building issue

**Comment by tiagodolphine** [comment]
@wmedvede can you please take a look on  https://github.com/kiegroup/kie-wb-common/pull/2112 all the showcases are running ok `mvn clean process-resources gwt:run`, I hope it helps.

**Comment by wmedvede** [comment]
Hi, @manstis @tiagobento 
the fix proposed in #2112 falls more or less in the combination of try&erros we did before. We can at least start the WB, but as soon we create and try to build a process we get this error
[INFO] 2018-09-12 17:45:33,098 [default task-81] INFO  Asset lookup result: project [git://MySpace/aaa] is indexed with 0 index hits.
[INFO] 2018-09-12 17:45:33,407 [EJB default - 1] ERROR Unable to load dialect 'org.drools.compiler.rule.builder.dialect.java.JavaDialectConfiguration:java:org.drools.compiler.rule.builder.dialect.java.JavaDialectConfiguration'
[INFO] java.lang.RuntimeException: Unable to load dialect 'org.drools.compiler.rule.builder.dialect.java.JavaDialectConfiguration:java:org.drools.compiler.rule.builder.dialect.java.JavaDialectConfiguration'

And this is because the ecj is being excluded from the generated .war file.
But since several people were was spending time on this with no luck, I believe we should move this PR forward since the showcases are not delivered to clients.

**Comment by manstis** [comment]
Closing in preference of https://github.com/kiegroup/kie-wb-common/pull/2112

**Pull request closed without merging**
