### PR TITLE
RHPAM-2957 : Business Central does not remember the last branch used on log out

### PR DESCRIPTION
**Pull request by RishiRajAnand**
**JIRA**: https://issues.redhat.com/browse/RHPAM-2957

Referenced Pull Requests:

https://github.com/kiegroup/appformer/pull/1045

- Added functionality to save last project and branch in cookie.
- BC will automatically redirect to last project and branch after a logout.
- Saving last branch for all projects in browser cookie, The expiry of Cookie has been set to 7 days for now to prevent less frequently used projects from overwhelming browser cookie store.

### CODE REVIEW

**Comment by RishiRajAnand** [comment]
@paulovmr I will push the test cases in a while .

**Comment by RishiRajAnand** [comment]
Jenkins execute full downstream build

**Comment by RishiRajAnand** [comment]
@paulovmr I added the unit tests to confirm setting and clearing of project and branch cookies.

**Comment by RishiRajAnand** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
> y one comment, could you ple

@paulovmr I have pushed the test case. Thanks

**Comment by barboras7** [comment]
Jenkins run fdb

**Comment by barboras7** [comment]
Hi @RishiRajAnand,
the PR looks good to me. Just two comments:

- it would be nice if the last branch was saved for all projects, not just for the last one opened
- @ederign @adrielparedes is this feature safe for HA? I remember that there were some issues with HA that were related to saving business central state

**Comment by RishiRajAnand** [comment]
Hi @barboras7, +1 for preserving last branch for all projects. I am working on implementation and will push the changes soon

**Comment by paulovmr** [comment]
Hi @barboras7 , before we had a problem with HA because this information was saved in the shared niogit directory. Since now the implementation uses cookies, it shouldn't be a problem.

**Comment by RishiRajAnand** [comment]
Hi @paulovmr @barboras7 , I just pushed the changes that allows saving last used branch for all project.

**Comment by RishiRajAnand** [comment]
@paulovmr I have also set the expiry date for these Project cookies to 7 days to to prevent less frequently used projects from overwhelming browser cookie store. This should help in case user has too many projects.

**Comment by paulovmr** [comment]
Jenkins run fdb

**Review by barboras7 — APPROVED** [review]

**Review by ederign — APPROVED** [review]

**Pull request merged**
