### PR TITLE
Move GWT compilation and WAR creation for -runtime to the default profile

### PR DESCRIPTION
**Pull request by manstis**
@ederign @tiagobento FYI

### CODE REVIEW

**Comment by manstis** [comment]
@ederign Well.. this is green :-)

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by tiagobento** [comment]
Jenkins please execute full downstream build.

**Comment by tiagobento** [comment]
Looks like there's an error on FDB. See https://gist.github.com/tiagobento/05eb89b62ab665b2d8e8d9400bc7c213

@manstis Any idea of what it could be?

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@tiagobento Nope, not seen that before.. I've re-triggered FDB as the whole log was no longer accessible.. let us see what the New Year brings for us!

**Comment by manstis** [comment]
@tiagobento It seems to be an issue with the build order of modules when the build is performed in parallel and `maven-invoker` plugin is used.. See https://issues.apache.org/jira/browse/MINVOKER-191

I am moving the DMN integration tests to a new _root_ level module (vs being an integration test in `kie-wb-common-dmn-webapp-kogito-common`). Let's see if that fixes things.

**Comment by manstis** [comment]
@tiagobento Let's see if https://github.com/kiegroup/kie-wb-common/pull/3095 is OK.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@porcelli @ederign This is ready for your approval (please!)

**Comment by porcelli** [comment]
adding @mareknovotny in the loop

**Comment by ederign** [comment]
@mareknovotny please take a look at this when you have a chance!

**Comment by mareknovotny** [comment]
hmm, so what this brings us in 7.x stream ? I would still keep it from default build workflow in 7.x

**Comment by manstis** [comment]
Hi @mareknovotny AFAIU the `kogitio-tooling` team want the webapp used by the VSCode plugin and Chrome Github extension to be built as part of the default build so their process to assemble the plugin/extension can use an artifact available in Maven rather than building from source. At the moment the webapp they need is only generated when the `kogito` profile is used.

I'll let @ederign and/or @porcelli comment further on the whys and wherefores to fully address your question (via email to BSIG as requested).

**Comment by mareknovotny** [comment]
@manstis I understood that from @porcelli's comment, but the inclusion in our v7 stream is dangerous and not wanted

**Comment by tiagobento** [comment]
@mareknovotny Actually we're not looking for integrating both builds, we just need the WARs of `.Final` versions would be complete for us to assemble the extensions properly when fetching them from the Maven repository.

Local testing and development would be performed normally as Maven looks to the .m2 folder before trying and fetching artifacts from remote repositories.

**Comment by jomarko** [comment]
Hi everyone, my question is different, if we do not merge this PR, do we somewhere run build & tests of the **kie-wb-common-webapp-kogito-runtime** module automatically on a regular basis?

**Comment by manstis** [comment]
Hi @jomarko ATM `kie-wb-common-dmn-webapp-kogito-runtime` **IS NOT** built (nor tests executed) anywhere automatically on any basis yet alone regular! The intent of this PR was to add such automation to the default build however it is clearly being discouraged.

IDK whether having another Jenkins pipeline for kogito authoring is required!? I see `kogito-tooling` **IS NOT** part of the default build and therefore perhaps the build etc of `kie-wb-common-dmn-webapp-kogito-runtime` (and BPMN and scesim's equivalents) are best added to the `kogito-tooling` CI pipeline (using whatever profile necessary to ensure their activation)?

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@ederign @porcelli @mareknovotny PR updated to only compile `-webapp`'s in the community (or technically non-`productized` invocations of the build). This now includes all -webapps that are not required by production.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
