### PR TITLE
AF-1204: Project list is slowly loaded after space is opened

### PR DESCRIPTION
**Pull request by mbarkley**
Partial fix for slow loading of project list. There still a noticeable delay as every project in a space must be loaded on the server before anything is sent/displayed on the client. I'm looking into a fix for that, but wanted to send this partial solution in case I do not solve the remaining issue soon enough.

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by mbarkley** [comment]
@ederign @paulovmr @adrielparedes I still have time to make changes to this if one of you can review it today.

**Comment by karreiro** [comment]
@paulovmr Can we merge this PR?

**Comment by ederign** [comment]
@paulovmr or @karreiro can you please do a rebase of this?

**Comment by paulovmr** [comment]
@ederign I've rebased the PR into this new one: https://github.com/kiegroup/kie-wb-common/pull/1903, so you can close this and merge the other when the build passes.

**Comment by ederign** [comment]
thanks @paulovmr

**Pull request closed without merging**
