### PR TITLE
AF-2418: Compute Overview page index dynamically

### PR DESCRIPTION
**Pull request by jomarko**
Ensemble together with:
https://github.com/kiegroup/appformer/pull/878

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
Failed test
```
org.guvnor.ala.services.rest.tests.RestRuntimeProvisioningImplTest.testAPI
```

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
error in build
```
13:51:24 [ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.8.2:compile (gwt-compile) on project kie-wb-common-stunner-showcase-project: Command failed with status 137 -> [Help 1]
```

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by mbiarnes** [comment]
jenkins execute full downstream build

**Comment by Rikkola** [comment]
For some reason it is not finding the Overview tab for me. I'll check if it is something I have locally messing it up.

**Comment by jomarko** [comment]
@Rikkola seems you are correct and it still doesn't work, checking

**Comment by Rikkola** [comment]
More details about my issues with it: It actually mentioned to me that it can not find tab named Overview, but I did saw the i18n name was set correctly in the tabs.

**Comment by Rikkola** [comment]
@jomarko one option is to check out what the overview tab index is when it is added into the tabs and then use that index for select.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@Rikkola it should be fixed now.

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
