### PR TITLE
[7.2.x] JBPM-6284: Slider and Multiple SubForm break the consistency with "ReadOnly" and "ValidateOnChange" labels.

### PR DESCRIPTION
**Pull request by pefernan**
There was some wrong setting on the @formfield annotations for that classes. Fixed
@jsoltes could you review?

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins please execute full downstream build

**Comment by pefernan** [comment]
jenkins please execute full downstream build

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins please execute full downstream build

**Comment by pefernan** [comment]
@manstis this is failing because of an unrelated test so... bad luck

**Comment by pefernan** [comment]
jenkins please execute full downstream build

**Comment by manstis** [comment]
jenkins please execute full downstream build

**Comment by manstis** [comment]
@pefernan Unfortunately you'll need to change this PR to now target 7.3.x :-(

**Comment by jsoltes** [comment]
@manstis can you please merge this? maybe @pefernan can cherrypick it to 7.3.x later when he comes back from vacation...

**Comment by manstis** [comment]
@jsoltes AFAIK it'd be pretty pointless merging this to 7.2.x as the release is almost out the door; and 7.3.x will come from a different branch..  that said it will do no harm either.. as long as @pefernan remembers to cherry-pick to 7.3.x too... so merging.

**Comment by jsoltes** [comment]
@manstis thanks. Actually as pere will be away for some time, I can cherry-pick it to 7.3.x myself.

**Pull request merged**
