### PR TITLE
KOGITO-3152: [DMN Designer] PMML support - function parameters generation

### PR DESCRIPTION
**Pull request by yesamer**
Follow up of KOGITO-2895 (PR is based on KOGITO-2895 changes)
Only PMML Field models with `usageType = "active" or null` should be considered.

**JIRA**: [KOGITO-3152](https://issues.redhat.com/browse/KOGITO-3152)

**Referenced Pull Requests**:
https://github.com/kiegroup/appformer/pull/1041
https://github.com/kiegroup/kie-wb-common/pull/3410
https://github.com/kiegroup/kogito-tooling/pull/266

**Business Central**: [WAR file](https://donwnload.here/something)

**VS Code**: [plugin](https://donwnload.here/something)

<pre>
To retest a PR or trigger a specific build please add a comment:

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</pre>

### CODE REVIEW

**Review by jstastny-cz — APPROVED** [review]

**Comment by jstastny-cz** [comment]
jenkins do fdb

**Review by jstastny-cz — APPROVED** [review]

**Review by tiagobento — APPROVED** [review]

**Review by karreiro — APPROVED** [review]
Thank you, @yesamer!

**Comment by yesamer** [comment]
Thank you @karreiro and @tiagobento. In your opinion, can we merge it? Not sure if is possibile, considering the code freezing.

**Comment by jstastny-cz** [comment]
@yesamer this is a bug fix, I'd say it's fine to merge before the code freeze.

**Comment by yesamer** [comment]
@kiegroup/gatekeepers Can you please merge it?

**Pull request merged**
