### PR TITLE
JBPM-6405 - On second generation of taskforms some of them disappear from library 7.3.x

### PR DESCRIPTION
**Pull request by alessioscalici**
**WARNING** To be merged with https://github.com/kiegroup/jbpm-designer/pull/671

This PR changes are the same as https://github.com/kiegroup/kie-wb-common/pull/1224 and https://github.com/kiegroup/kie-wb-common/pull/1230, pointing to 7.3.x

@pefernan @jsoltes FYI

### CODE REVIEW

**Comment by pefernan** [comment]
Comment merge with: https://github.com/kiegroup/jbpm-designer/pull/670

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@alessioscalici could you please provide this PR for 7.4.x branch?

**Comment by alessioscalici** [comment]
@pefernan done, https://github.com/kiegroup/kie-wb-common/pull/1230

**Pull request closed without merging**
