### PR TITLE
DROOLS-2954: [DMN Designer] [IE11] Custom data type select box not rendered correctly after change

### PR DESCRIPTION
**Pull request by danielzhe**

### CODE REVIEW

**Comment by jomarko** [comment]
@danielzhe I found an issue that user can not see all item definitions, see the attached picture bellow. It is an issue both for IE11 and Edge.
screenshot from 2018-10-08 09-58-30

**Comment by danielzhe** [comment]
Humm.. that's new. I'll check it. Thanks @jomarko

**Comment by danielzhe** [comment]
Thanks for the review, @jomarko ! I've found the same issue that you reported in Firefox too even without the changes made by this PR. Should we open a new Jira for this or I investigate further and fix
in this PR? Thank you.

**Comment by jomarko** [comment]
@danielzhe yes, please open new issue.

**Comment by danielzhe** [comment]
@manstis merge, please. Thank you!

**Pull request merged**
