### PR TITLE
DROOLS-5775: Test Scenario does not support nested Enum type attributes

### PR DESCRIPTION
**Pull request by yesamer**
To enable nested java classes in `getSuperTypes()` logic, it's required to retrieve the full qualified class name of the given factName and pass it to the `getUpdates()`, instead of the factName
An example: in case of factName `Customer.Category` neested class, `getUpdates` required the complete class name `com.Customer$Category` instead of the factName canonical name previously passed `Customer.Category`

**JIRA**: [DROOLS-5775](https://issues.redhat.com/browse/DROOLS-5775)

**Referenced Pull Requests**:
* https://github.com/kiegroup/drools/pull/3201
* https://github.com/kiegroup/kie-wb-common/pull/3470
* https://github.com/kiegroup/drools-wb/pull/1440

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Review by Rikkola — APPROVED** [review]

**Review by karreiro — APPROVED** [review]
Thank you, @yesamer! LGTM :-)

**Review by jstastny-cz — APPROVED** [review]

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins retest this please

**Pull request merged**
