### PR TITLE
JBPM-7752 Stunner - Create Marshaller tests for Escalation Start Events

### PR DESCRIPTION
**Pull request by LuboTerifaj**

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
Hi @evacchi @romartin 

Can you have a look also at this PR?

Thank you.

**Comment by LuboTerifaj** [comment]
Hi @hasys 
 
Can you have a look please?

Thanks.

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Pull request merged**
