### PR TITLE
Excluding ECJ dependency on the webapps due to version conflicts

### PR DESCRIPTION
**Pull request by tiagodolphine**
Hey @manstis I don't know if this already fixed on the PR you've opened, testing here locally simply excluding the ECJ from the dependencies that contained it solved the problems on the GWT compilation. 
I this is already fixed I can close the PR, no problem.
Thanks

### CODE REVIEW

**Comment by manstis** [comment]
@tiagobento This is identical to something I tried a while ago; but both me, @jomarko and @wmedvede found the Stunner ```-project``` showcase failed to run with a ```mvn clean process-resources gwt:run```. Have you tried this? I will fetch your PR and try none the less (and to be honest hoping it works!)

**Comment by tiagodolphine** [comment]
@manstis the `mvn gwt:run` worked here.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by manstis** [comment]
ok to test.

**Comment by wmedvede** [comment]
Hi @tiagodolphine ,I'll check this locally. But, did you try also if the project-showcase work?
i.e., starting the showcase, creating a project, create a project, and be sure the project builds?

**Comment by manstis** [comment]
@tiagodolphine I tried the ```-project``` showcase however it is not possible to build projects successfully:
```
2018-09-12 16:47:43,490 [Thread-4578] ERROR Unable to index 'default://master@MySpace/example-Mortgages/src/main/java/mortgages/mortgages/IncomeSource.java'.
[INFO] java.lang.RuntimeException: Unable to load dialect 'org.drools.compiler.rule.builder.dialect.java.JavaDialectConfiguration:java:org.drools.compiler.rule.builder.dialect.java.JavaDialectConfiguration'
[INFO] 	at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.addDialect(KnowledgeBuilderConfigurationImpl.java:375) ~[drools-compiler-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.buildDialectConfigurationMap(KnowledgeBuilderConfigurationImpl.java:361) ~[drools-compiler-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.init(KnowledgeBuilderConfigurationImpl.java:224) ~[drools-compiler-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.init(KnowledgeBuilderConfigurationImpl.java:184) ~[drools-compiler-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.<init>(KnowledgeBuilderConfigurationImpl.java:152) ~[drools-compiler-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.drools.compiler.kie.builder.impl.KieBuilderImpl.compileJavaClasses(KieBuilderImpl.java:636) ~[drools-compiler-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.drools.compiler.kie.builder.impl.KieBuilderImpl.buildAll(KieBuilderImpl.java:233) ~[drools-compiler-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.drools.compiler.kie.builder.impl.KieBuilderImpl.buildAll(KieBuilderImpl.java:184) ~[drools-compiler-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.drools.compiler.kie.builder.impl.KieBuilderImpl.getKieModule(KieBuilderImpl.java:438) ~[drools-compiler-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.drools.compiler.kie.builder.impl.KieBuilderImpl.getKieModuleIgnoringErrors(KieBuilderImpl.java:433) ~[drools-compiler-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.kie.workbench.common.services.backend.builder.core.Builder.getKieModuleIgnoringErrors(Builder.java:578) ~[kie-wb-common-services-backend-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.kie.workbench.common.services.backend.builder.service.BuildInfoImpl.getKieModuleIgnoringErrors(BuildInfoImpl.java:41) ~[kie-wb-common-services-backend-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.kie.workbench.common.services.backend.project.ModuleClassLoaderHelper.getModuleClassLoader(ModuleClassLoaderHelper.java:40) ~[kie-wb-common-services-backend-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.kie.workbench.common.services.backend.project.ModuleClassLoaderHelper$Proxy$_$$_WeldClientProxy.getModuleClassLoader(Unknown Source) ~[kie-wb-common-services-backend-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.kie.workbench.common.screens.datamodeller.backend.server.indexing.JavaFileIndexer.getModuleClassLoader(JavaFileIndexer.java:154) ~[kie-wb-common-data-modeller-backend-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.kie.workbench.common.screens.datamodeller.backend.server.indexing.JavaFileIndexer.fillIndexBuilder(JavaFileIndexer.java:135) ~[kie-wb-common-data-modeller-backend-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.kie.workbench.common.services.refactoring.backend.server.indexing.AbstractFileIndexer.toKObject(AbstractFileIndexer.java:78) ~[kie-wb-common-refactoring-backend-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.kie.workbench.common.screens.datamodeller.backend.server.indexing.JavaFileIndexer$Proxy$_$$_WeldClientProxy.toKObject(Unknown Source) [kie-wb-common-data-modeller-backend-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.uberfire.ext.metadata.io.IndexerDispatcher$IndexerJob.processNew(IndexerDispatcher.java:255) [uberfire-metadata-commons-io-2.9.0-SNAPSHOT.jar:2.9.0-SNAPSHOT]
[INFO] 	at org.uberfire.ext.metadata.io.IndexableIOEvent$NewFileEvent.apply(IndexableIOEvent.java:62) ~[uberfire-metadata-commons-io-2.9.0-SNAPSHOT.jar:2.9.0-SNAPSHOT]
[INFO] 	at org.uberfire.ext.metadata.io.IndexerDispatcher$IndexerJob.processEvent(IndexerDispatcher.java:235) [uberfire-metadata-commons-io-2.9.0-SNAPSHOT.jar:2.9.0-SNAPSHOT]
[INFO] 	at org.uberfire.ext.metadata.io.IndexerDispatcher$IndexerJob.processEvents(IndexerDispatcher.java:211) [uberfire-metadata-commons-io-2.9.0-SNAPSHOT.jar:2.9.0-SNAPSHOT]
[INFO] 	at org.uberfire.ext.metadata.io.IndexerDispatcher$IndexerJob.get(IndexerDispatcher.java:188) [uberfire-metadata-commons-io-2.9.0-SNAPSHOT.jar:2.9.0-SNAPSHOT]
[INFO] 	at org.uberfire.ext.metadata.io.IndexerDispatcher$IndexerJob.get(IndexerDispatcher.java:159) [uberfire-metadata-commons-io-2.9.0-SNAPSHOT.jar:2.9.0-SNAPSHOT]
[INFO] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[na:1.8.0_171]
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
[INFO] 	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
[INFO] Caused by: java.lang.RuntimeException: The Eclipse JDT Core jar is not in the classpath
[INFO] 	at org.drools.compiler.rule.builder.dialect.java.JavaDialectConfiguration.setCompiler(JavaDialectConfiguration.java:117) ~[drools-compiler-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.drools.compiler.rule.builder.dialect.java.JavaDialectConfiguration.init(JavaDialectConfiguration.java:78) ~[drools-compiler-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.addDialect(KnowledgeBuilderConfigurationImpl.java:371) ~[drools-compiler-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
[INFO] 	... 27 common frames omitted
```

**Comment by wmedvede** [comment]
@manstis @tiagodolphine   I got same error likely at the the same time. I've added my comments here #2099

**Comment by wmedvede** [comment]
I'm a bit lost right now.
So @manstis closes this #2099 with his ECJ fixes for kie-wb-commons, likely in favor of this one?

**Comment by tiagodolphine** [comment]
Closing this PR the fix will be provided on https://github.com/errai/errai/pull/360

**Pull request closed without merging**
