### PR TITLE
[7.52.x] RHPAM-3544 - Data Object editor removes imports when saving

### PR DESCRIPTION
**Pull request by Josephblt**
**JIRA**: [RHPAM-3544](https://issues.redhat.com/browse/RHPAM-3544)
**JIRA**: [JBPM-9715](https://issues.redhat.com/browse/JBPM-9715)

**Referenced Pull Requests**:
* https://github.com/kiegroup/kie-wb-common/pull/3628

**Business Central**: [WAR file](https://donwnload.here/something)

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins run cdb

**Comment by jstastny-cz** [comment]
@Josephblt please indicate the target branch in PR's title.

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by romartin** [comment]
hey @Josephblt , what's missing here? just waiting for reviews? CC @jstastny-cz @Rikkola

**Comment by Josephblt** [comment]
Hello @romartin. There is a discussion about this here. I'm waiting for feedback.

**Comment by romartin** [comment]
hey @Josephblt 

thanks for the feedback. Just merged the commit in master: https://github.com/kiegroup/kie-wb-common/pull/3628

Not merging this until having the OK on this branch, I think CR1 is still on progress. So let's wait until the branch is "unfeezed".

CC @jstastny-cz @Rikkola can you please guys approve this cherry-pick once possible?

Thanks!

**Review by Rikkola — APPROVED** [review]

**Review by jstastny-cz — APPROVED** [review]
LGTM

**Comment by romartin** [comment]
Jenkins run fdb

**Comment by romartin** [comment]
Hey @Josephblt 

I'm re-runnign the build in order to see everything is on place. The branch is open again for mergin, so please let me know when this is ready.

Thanks!

**Comment by Josephblt** [comment]
Jenkins retest this
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Pull request merged**
