### PR TITLE
[JBPM-9464] Kie server notification causes bad status in BC

### PR DESCRIPTION
**Pull request by elguardian**
Jira: https://issues.redhat.com/browse/JBPM-9464

Current implementation does not work very well with update notifications on the fly from kie server due to a lot of refreshing.
depends on https://github.com/kiegroup/droolsjbpm-integration/pull/2327

### CODE REVIEW

**Comment by elguardian** [comment]
@nmirasch Te he puesto en este jira para que le des un vistazo. El sistema de updates que se ha implemetando a nivel de BC HA daba estados erroneos en los servidores y hacía mucho blink en la UI. Este jira va a encaminado a simplicar el sistema de @Observers y actualizar la pantalla solo en caso necesario eliminando el blink.

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins run fdb

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
Jenkins run fdb

**Comment by sutaakar** [comment]
@elguardian Can you please rebase?

**Comment by elguardian** [comment]
@sutaakar rebased

**Comment by sutaakar** [comment]
Jenkins run fdb

**Comment by domhanak** [comment]
@elguardian @nmirasch please advice what to do with this PR, it is getting stale.

**Comment by nmirasch** [comment]
@domhanak I guess @elguardian is not around, I think he will back in 10 days more or less. I would say we need his input to know what to do with this dev.

**Comment by mareknovotny** [comment]
as https://github.com/kiegroup/droolsjbpm-integration/pull/2327 was closed i think this is for closing too, right @elguardian ?

**Pull request closed without merging**
