### PR TITLE
[7.7.x] AF-1246: Full screen mode should close/collapse all panels

### PR DESCRIPTION
**Pull request by paulovmr**
Cherry-picked from https://github.com/kiegroup/kie-wb-common/pull/1901.

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
Hi @barboras7, if you could please check this one. Thanks!

**Comment by ederign** [comment]
please jenkins retest this

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Pull request merged**
