### PR TITLE
[7.52.x] KOGITO-5003: DMN editor removing edges for duplicate Decision Nodes on canvas

### PR DESCRIPTION
**Pull request by danielzhe**
This is cherry-pick from 
https://github.com/kiegroup/kie-wb-common/pull/3645
https://github.com/kiegroup/kogito-editors-java/pull/52

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by jstastny-cz** [comment]
compilation failure
```
[2021-06-22T23:15:11.892Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project kie-wb-common-dmn-client: Compilation failure
[2021-06-22T23:15:11.892Z] /home/jenkins/workspace/KIE/7.52.x/pullrequest/kie-wb-common-7.52.x.pr/bc/kiegroup_kie_wb_common/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/marshaller/unmarshall/nodes/NodeConnectorTest.java:[117,46] method newEdge in class org.kie.workbench.common.dmn.client.marshaller.unmarshall.nodes.NodeConnector cannot be applied to given types;
[2021-06-22T23:15:11.892Z]   required: double,double
[2021-06-22T23:15:11.892Z]   found: no arguments
[2021-06-22T23:15:11.892Z]   reason: actual and formal argument lists differ in length
```

**Comment by danielzhe** [comment]
jenkins do fdb

**Review by karreiro — APPROVED** [review]
Thank you, @danielzhe.

**Comment by karreiro** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
the failed tests were fixed in https://github.com/kiegroup/drools-wb/pull/1501

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by jstastny-cz** [comment]
Downloading FDB, will report on testing results shortly.

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by karreiro** [comment]
jenkins do fdb

**Pull request merged**
