### PR TITLE
RHPAM-2910: BPMN Editor - Rule Flow Group should show from which project ruleflow group is loaded 

### PR DESCRIPTION
**Pull request by Josephblt**
This is just a cherry-pick.

**JIRA**:

[RHPAM-2910](https://issues.redhat.com/browse/RHPAM-2910 )

**referenced Pull Requests**: 
* https://github.com/kiegroup/kie-wb-common/pull/3325

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute compile downstream build

**Review by LuboTerifaj — APPROVED** [review]

**Review by romartin — APPROVED** [review]

**Pull request merged**
