### PR TITLE
[7.14.x] JBPM-7997: garbled message in start process form when OS locale is Japanese

### PR DESCRIPTION
**Pull request by pefernan**
Copied from https://github.com/kiegroup/kie-wb-common/pull/2354 due to some issues with jenkins.

@jsoltes @ederign would you mind review again??

This is part of an ensemble, please merge with:
https://github.com/kiegroup/kie-wb-common/pull/2358
https://github.com/kiegroup/jbpm-wb/pull/1263
https://github.com/kiegroup/kie-docs/pull/1320

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by mbiarnes** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by ederign** [comment]
test fail is not related.

**Pull request merged**
