### PR TITLE
JBPM-6605: Stunner - Data input don't apply for EndNoneEvent and EndTerminateEvent

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
oh sorry @wmedvede , you'll have to fix the conflicts here, just merged the PR from @alepintus  and this one complains now.

**Comment by wmedvede** [comment]
@romartin all conflicts merged. Let's try to merge this so I can send the PR with the EndErrorEvent

**Comment by romartin** [comment]
missing for @hasys approval to merge

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Pull request merged**
