### PR TITLE
JBPM-8164: expose the editor as tech preview on the workbench

### PR DESCRIPTION
**Pull request by xiezhang7**
Assembly:
https://github.com/kiegroup/kie-wb-common/pull/2432
https://github.com/kiegroup/kie-wb-distributions/pull/870

### CODE REVIEW

**Comment by xiezhang7** [comment]
Hi @romartin @LuboTerifaj , this pull request is for [JBPM-8164](https://issues.jboss.org/browse/JBPM-8164). I only removed the experimental framework. The tech preview permission has been done in [PR#1775](https://github.com/kiegroup/kie-wb-common/pull/1775) already. Thanks.

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by xiezhang7** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Thanks for the changes @xiezhang7 , it looks good now.

**Pull request merged**
