### PR TITLE
[7.3.x] JBPM-6470: Password displayed in clear text while creating datasource in kie-workbench.

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit f794ea9dca3775ac3afd4a2dca4ae631aa2ca542)

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @nmirasch would you mind review this PR?
Thanks!

**Comment by wmedvede** [comment]
Hello @manstis  In case we are in time, It'll be nice to have this merged for the 7.3.x
Thanks.

**Comment by manstis** [comment]
Please check with @mbiarnes 7.3.x is not frozen.. this will need to now target 7.4.x.

**Comment by manstis** [comment]
@wmedvede Sorry.. just saw your comment (after I'd added mine).. I am speaking with @mbiarnes on IRC but he's said 7.3.x is now dead.

**Pull request closed without merging**
