### PR TITLE
JBPM-6753: Rename server capabilities

### PR DESCRIPTION
**Pull request by jomarko**
Replace terms:
- Rule with Decision
- Planning with Planner

@karreiro would you mind have a look please?

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by manstis** [comment]
@jomarko Did I miss any of your "green" PRs?

**Comment by jomarko** [comment]
@manstis this is ready for merge, P.S. nothing missed.

**Pull request merged**
