### PR TITLE
JBPM-8825: Resets current page when user searches by term.

### PR DESCRIPTION
**Pull request by marcuscarvalho**
The current page is not resetting when the user searches by term. It can cause an error if the page does not exist.

You can find the steps to reproduce this issue at JBPM-8825.

### CODE REVIEW

**Comment by kie-ci8** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by domhanak** [comment]
ok to test

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by marcuscarvalho** [comment]
Hi @ederig, do you know why the build is failing? I don't have access to Jenkins to check.

**Comment by mareknovotny** [comment]
@marcuscarvalho you should get as a PR sender an email with the log and if you are on Redhat VPN you could see the link of test results.
I can see the referenced Jenkins test results were cleaned for some reason.

Jenkins retest this please.
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Pull request merged**
