### PR TITLE
JBPM-7282: Stunner - Cannot import mortgages process (#1904)

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit 32ee37f0d961408c4852edfce95a0a0e82540033)

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi @romartin @hasys this is the peer PR for the already merged into 7.7.x  #1904 
would you mind review and merge?
Thanks

**Comment by hasys** [comment]
Hi @LuboTerifaj,

you already reviewed cherry-pick of this PR, can I ask you to deal with it as well?

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Pull request merged**
