### PR TITLE
== DO NOT MERGE == KOGITO-460: [DMN Designer] Cannot add imported models

### PR DESCRIPTION
**Pull request by manstis**
**== DO NOT MERGE ==** 

See https://issues.jboss.org/browse/KOGITO-460

Waiting for https://github.com/kiegroup/kogito-tooling/pull/40

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by jomarko** [comment]
When I try to import [file](https://issues.jboss.org/secure/attachment/12457621/8DCEBB11-E2C8-4E83-B37C-4E10C63DEFAA.dmn) produced by **kie-wb-common-dmn-webapp-kogito-testing** into third party editor. I get an errors:
Screenshot from 2019-11-19 11-37-44

**Comment by jomarko** [comment]
Opening in old one business-central shows an [error](https://issues.jboss.org/secure/attachment/12457623/error.log) in server log.

**Pull request closed without merging**
