### PR TITLE
KOGITO-1183: BPMN Editor - Imports not working.

### PR DESCRIPTION
**Pull request by romartin**
Hey @inodeman @domhanak @LuboTerifaj 

Here is the fix for BOTH: [KOGITO-1183](https://issues.redhat.com/browse/KOGITO-1183) and [JBPM-9076](https://issues.redhat.com/browse/JBPM-9076)

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@LuboTerifaj  @domhanak 

This PR is ready for testing. I should be quite easy from the UI to test,  I already did again to ensure it works:

1. just create a new process
2. add some imports
3. save, 
4. reopen
5. check those imports are still there. 

That will ensure the marshalling support that was missing for imports is now present. Please also remeber BC should be also retested.

Thanks!!

**Comment by LuboTerifaj** [comment]
Reported issue: https://issues.redhat.com/browse/KOGITO-1621

**Comment by romartin** [comment]
Hey @LuboTerifaj 

I'd been rebasing this PR, I think that's the reason why you was not able to save any change in the process. I've also tested it on top of latest master upstream and upload some example video, which shows how properties are updated and saved properly, see [this comment](https://issues.redhat.com/browse/KOGITO-1621?focusedCommentId=14016192&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14016192).

Also, I was not able to reproduce the issue [you mention](https://github.com/kiegroup/kie-wb-common/pull/3241#pullrequestreview-381968150) about the dropdown list and the remove button - what you mean by an "empty" data data type? Can you please give me some steps to reproduce? Anyway, if that's still reproducible, maybe we can report this issue and let this PR go, which at least makes the imports properly to work again. WDYT?

Thanks!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @LuboTerifaj this is ready to test again please

BTW the sonarcloud duplication checks are ok, we've duplication code on the marshallers, so nothing to do there for now. 

thanks!

**Comment by LuboTerifaj** [comment]
Hey @romartin , please see my [comment](https://issues.redhat.com/browse/KOGITO-1183?focusedCommentId=14018801&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14018801). Thank you!

**Comment by romartin** [comment]
Hey @LuboTerifaj 

Great catches!!! I was able to reproce all above 3 issues. I'm trying to fix the one about duplicated data types, which is "brreaking" the list component, I would suggest to report the other ones for some future work anyway. 

So will let you know something ASAP, thianks for the great testing being done here as well!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @LuboTerifaj 

I've updated this PR by rebasing it and also fixing the issue you mentioned in the comment above, which was about the widget getting broken when duplicating some of the imports:
* The issue was present for any of boith `default imports` or `wsdl imports`, and it was not possible to delete the items after introducing some duplication (even custom data types or not as well)
* The fix for the issue is not ideal, as it allows duplications, but at least the components doesn't gets broken and the user is able to fix, by updating or removing the import, in case of duplication. 

So I think we can report any other issues, and if you agree, go ahead with this. WDYT?

Thanks!

**Comment by romartin** [comment]
@LuboTerifaj artifacts generated

**Comment by romartin** [comment]
Jenkins retest this

**Comment by LuboTerifaj** [comment]
FDB is missing. Jenkins execute full downstream build

**Comment by romartin** [comment]
Oh @LuboTerifaj I forgot to update the headers sorry, but this will imply to rebuild everything and tomorrow is last chance of having this merged, so I would prefer trying to merge this as it is. I've updated IntelliJ to update headers for next times, but I don't think that should block it.

And yeah, I didn't fixed the CM, I just fixed the issue about duplicating imports, which has not trivial, so I had no more time.

So what's missing? Are you agree on approving/merging?

Thx!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@LuboTerifaj rebased and fixed headers!! thanks!

**Comment by romartin** [comment]
thanks @LuboTerifaj !

**Pull request merged**
