### PR TITLE
JBPM-8436: Read-only user can delete fields in Data Object

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @nmirasch @kkufova would you mind review this PR?
Thanks

**Comment by wmedvede** [comment]
jenkins retest this

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by kkufova** [comment]
@wmedvede, is any other PR in a different repository associated with this? I built this PR locally and the bug is still present (it is possible to delete data object's fields in Data Modeler).

**Comment by wmedvede** [comment]
@kkufova no additional PRs related to this. How are you reproducing the issue? Using business-central ? or using a development showcase?

**Comment by wmedvede** [comment]
Un-related failure during full build, let's give it a second try
10:11:46 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
10:11:46 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
10:11:46 Build step 'Build dependent downstream repositories (for PR builds)' marked build as failure
10:11:46 Terminating xvnc.
10:11:46 FATAL: Remote call on kie-psi-rhel7-xlarge-xmem-6390 failed. The channel is closing down or has closed down
10:11:46 java.io.EOFException
10:11:46 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2680)
10:11:46 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3155)
10:

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by kkufova** [comment]
@wmedvede, I built this PR + `kie-wb-distributions` to get a full WAR file of Business Central. Other than that, I used the steps to reproduce written in the Jira.

**Comment by wmedvede** [comment]
artifacts were generated, failures are in non related tests

**Comment by tomasdavidorg** [comment]
Hi @wmedvede, I tested the war from full downstream build and it works as expected. I have on only one comment: There is possibility to change the data object by OptaPlanner dock. If you click on Planning Entity or Planning solution, it will change the source content. Do you think that this could be also disabled when the permissions are set to read only? Thanks.

**Comment by wmedvede** [comment]
@kkufova @tomasdavidorg  I've downloaded the generated artifacts and it works well. To check it you need a user with "analyst" role, and disable the "Project Update" grant for the role analyst.

I believe there could have been a mistake in the middle since I set a wrong jira number in the PR/commit description. The real jira number and branch number is "JBPM-8436" , BUT y typed 
 "JBPM-8463" by mistake, and I have also a branch with this number "JBPM-8463" that has nothing, and probably you got the wrong branch because of this? 
Anyway, fist of all I'll set the correct correct jira number "JBPM-8436". So I'll have to change the commit description locally and push it again.

**Comment by wmedvede** [comment]
> Hi @wmedvede, I tested the war from full downstream build and it works as expected. I have on only one comment: There is possibility to change the data object by OptaPlanner dock. If you click on Planning Entity or Planning solution, it will change the source content. Do you think that this could be also disabled when the permissions are set to read only? Thanks.

@tomasdavidorg I'll take a look at the optaplanner side, if this can be done quick I can do it, otherwise I suggest opening a new JIRA for this part and assign to the optaplanner team since all this stuff is maintained/developed by this team.

**Comment by tomasdavidorg** [comment]
@wmedvede Ok Thanks :slightly_smiling_face:

**Comment by kkufova** [comment]
@wmedvede, thank you for the explanation, I think it is very much possible that this was the problem. I'll check the WAR from the full downstream build.

**Comment by wmedvede** [comment]
Hi @kkufova @tomasdavidorg , ok, I rebased all locally with master, built and tested again, and updated all the jira references to the correct name "JBPM-8436". So all should be ok now. I'll keep an eye on the jenkins build. Thanks!

**Comment by wmedvede** [comment]
> Hi @wmedvede, I tested the war from full downstream build and it works as expected. I have only one comment: There is possibility to change a data object by OptaPlanner dock. If you click on Planning Entity or Planning solution, it will change the source content. Do you think that this could be also disabled when the permissions are set to read only? Thanks.

Hi @tomasdavidorg I confirm that none of the optaplanner widgets has implemented the setReadonly() method. So this must definitely be managed by the optaplanner team. 

Would you mind open a new ticket for this and assign to the proper scrum master/person?

This PR can still be moved forward since it provides the proper calculation of the readonly mode according with the role grants, etc. Finally since the setReadonly(XXX) is automatically propagated by the datamodeller to all the plugged domains like the optaplanner domain, as soon they have this method implemented they'll automatically benefited from this change.

Thanks!

**Comment by tomasdavidorg** [comment]
Thanks @wmedvede. I have created jira for that, see https://issues.jboss.org/browse/PLANNER-1482.

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by wmedvede** [comment]
artifacts were generated well for full build too, failing tests non related

org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromCustomRepository
org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testStandaloneEditorPerspective

**Comment by pefernan** [comment]
Merging since the tests failures seem to be unrelated to the changes. Thanks @wmedvede :D

**Pull request merged**
