### PR TITLE
JBPM-8828 - After deleting some Space, the re-usable activities cannot be configured properly

### PR DESCRIPTION
**Pull request by Josephblt**
https://issues.jboss.org/browse/JBPM-8828

The error happened because of an untreated exception. still happens, but
now it is being logged and handled in a better way. This way it does not
disrupt any editor functionality.

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @xiezhang7 , as you created this.. could you please do some review here? Thx!

**Comment by romartin** [comment]
@Josephblt there is no test case added or updated... could it be possible? Thx!

**Comment by Josephblt** [comment]
> @Josephblt there is no test case added or updated... could it be possible? Thx!

Hello @romartin. I think you missed it. This is the test class:
kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/query/BPMNProcessIdsResponseBuilder.java

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
ok thanks @xiezhang7 !
pls missing your review here @hasys , thx too!

**Comment by hasys** [comment]
Reassigning it to @LuboTerifaj. Thank you!

**Comment by hasys** [comment]
Hi @Josephblt , @xiezhang7 there is conflict file now in this PR. Can I ask you to fix the conflict and rerun full downstream build? After that @LuboTerifaj will be able to finish this PR review.

Thank you!

**Comment by Josephblt** [comment]
Jenkins execute full downstream builds

**Comment by romartin** [comment]
Hey @LuboTerifaj , plz missing your review here

**Comment by romartin** [comment]
Hey @LuboTerifaj , plz missing your review here, thx!

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
The PR is blocked by https://issues.jboss.org/browse/JBPM-8875

**Comment by hasys** [comment]
Blocker issue were fixed on master, this PR should be unblocked now. 

Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
JBPM-8875 pull-request: #3011

**Pull request merged**
