### PR TITLE
[7.44.x] DROOLS-5665: DMN editor not saving changes in properties panel in Business Central

### PR DESCRIPTION
**Pull request by danielzhe**
Cherry-pick from DROOLS-5665: DMN editor not saving changes in properties panel in Business Central ([#3465](https://github.com/kiegroup/kie-wb-common/commit/c7e62ad8d8a8a8e664596493c42cf6aacbc7d4be))

**JIRA**: [DROOLS-5665](https://issues.redhat.com/browse/DROOLS-5665)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins do fdb.

**Review by karreiro — APPROVED** [review]
Thank you, @danielzhe :-)

**Comment by karreiro** [comment]
Jenkins retest this.

**Comment by danielzhe** [comment]
Jenkins do fdb

**Review by yesamer — APPROVED** [review]

**Comment by danielzhe** [comment]
Jenkins do fdb

**Comment by yesamer** [comment]
jenkins retest this please

**Pull request merged**
