### PR TITLE
[DO NOT MERGE] Remove delay before showing Popover

### PR DESCRIPTION
**Pull request by manstis**
@jomarko @karreiro @danielzhe 

Hi, if you get a chance could you please try this branch (to see whether the issue with popover content is improved or worsened.. it makes no difference for me locally). I am hoping it makes things worse - as it'd go some way to proving my suspicion of a race condition between `errai-ui` `@Templated` components being processed and added to the DOM vs Bootstrap's `popover` using the result as the content of the `popover`......  here's hoping!

### CODE REVIEW

**Comment by manstis** [comment]
(or it also removes some dead code I found.. who knows, removal of the `CellEditorControlsViewImpl` view from the DOM may even fix things (but I doubt it) but it does mean the DOM is not polluted with unnecessary DIVs each time a popover or context menu is shown...

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
@manstis I tried this PR for a while for modelling a DMN model and the issue with missing expression types hasn't occurred on my machine. Also haven't spot any regression, from my point of view this can be merged if you wish, however probably need to manual recheck by someone else who spotted it previously on his machine.

**Comment by jomarko** [comment]
I tried as **kie-wb-common-dmn-webapp** so **kie-wb-distributions** webapp.

**Comment by manstis** [comment]
@karreiro I completely agree.. to be honest I was expecting this change to make the occurrence of the issue _more_ oftern not _less_! I will keep investigating potential causes before considering this OK to merge.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@karreiro @jomarko Please give me your opinions.

This PR doesn't really contain anything that _should_ fix the issue; but it does add some missing clean up. We do not know if the apparent inability to recreate the issue with the testing of this PR is by luck or by some form of magic; but unless this PR is battle proven more - i.e. tested more and more; we may never know.

@etirelli has said this can be merged if we feel it is low risk. Given neither of you found any regressions and it does add some missing cleanup I'm of the opinion to merge this PR and see if the issue remains over the coming weeks etc as the _fix_ is tested more and more. At the very least it does not put me in a worse place than we currently are.. having to refresh the browser if the popover is empty.

But I reiterate @karreiro opinion.. there's really nothing obvious in this PR to have fixed the issue; and to reiterate my expectation.. this PR should have _increased_ the occurrence of the issue!

**Comment by karreiro** [comment]
@manstis Since we're trying to _increase_ the occurrence of the issue, and we could not reproduce it anymore with/without this PR, I would merge this on Monday.

**Comment by manstis** [comment]
@karreiro @jomarko Sooo.. it appears the clean-up code *does* fix the issue!

Steps to reproduce (every time!):
# Create a DMN diagram
# Add a Decision node
# Set to the Decison node's expression to a Decision Table
# Click Input Clause column to show "Name & Data-type" popover
# Click anywhere else on the grid to close popover
# Close diagram
# Create another DMN new diagram
# Add a Decision node
# Try to select the expression type. Popover is empty.

These steps work fine with this PR.

The issue was that the `Popover` was binding itself to the wrong _container_ as duplicates were created between opening and closing and opening another diagram (session). Removal of the existing _container_ when the diagram (session) is closed prevents the wrong binding.

**Comment by manstis** [comment]
Let me see if I can write a test before this PR can be merged (but please do try to replicate in the _old_ world and with this PR.. if you have time).

**Comment by jomarko** [comment]
@manstis Hi, I can completely confirm your [comment](https://github.com/kiegroup/kie-wb-common/pull/2471#issuecomment-463601501). The steps there leads to the issue without your PR, with your PR no issue spotted.

**Comment by manstis** [comment]
@jomarko @karreiro Fix moved to https://github.com/kiegroup/kie-wb-common/pull/2481

**Pull request closed without merging**
