### PR TITLE
[RHPAM-1566] Not able to open task form from Task Inbox on business central

### PR DESCRIPTION
**Pull request by elguardian**
instance variable is null causing code to break when it is marshalled

### CODE REVIEW

**Comment by elguardian** [comment]
@pefernan let me know if this requires more changes. The test created an empty model an try the form.

**Comment by pefernan** [comment]
jekins retest this please

**Comment by elguardian** [comment]
jekins retest this please

**Comment by elguardian** [comment]
@pefernan all green

**Pull request merged**
