### PR TITLE
DROOLS-2230: Deadlock related to org.kie.workbench.common.services.backend.builder.core.LRUProjectDependenciesClassLoaderCache

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-2230

QE had dead-locks in failing Selenium tests. 

The changes in this PR resolve the issues as verified by @tomasdavidorg 

```Builder``` had the most extensive changes; whereby synchronised blocks were changed to safe-guard the smallest area possible. ```LRUCache``` implementations synchronised removed from public methods as the underlying ```Collection``` used by the cache is thread-safe in itself.

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by jomarko** [comment]
@manstis Hi, please, this is still not ready for a review?

**Comment by manstis** [comment]
@jomarko You can review if you like; it is being tested by Tomas David(?) (I'm not on VPN so  can't check the product JIRA). There is no test... I hoped the failing (and hopefully fixed) Selenium tests would be sufficient.

**Comment by tomasdavidorg** [comment]
@manstis Trying to test this but the downstream build didn't produce the kie-wb.war. I will try to build this locally.

**Comment by tomasdavidorg** [comment]
@manstis The fix helped :-). Thanks.

**Comment by manstis** [comment]
@jomarko @tomasdavidorg Please review (so I can submit a similar PR for 7.5.x **today**).

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@jomarko @tomasdavidorg I've added a new commit following a test failure in ```org.kie.workbench.common.services.datamodel.backend.server.builder.BuilderConcurrencyIntegrationTest``` in the 7.5.x [PR](https://github.com/kiegroup/kie-wb-common/pull/1352). The same has been cherry-picked there too.

I re-tested the original dead-lock issue and that remains "fixed". I also ran the failing test several times locally passing each time... let's see what Jenkins makes of it.. if green come Monday, I think these will be safe to merge (and watch me eat these words on Tuesday!)

**Comment by manstis** [comment]
Green 1.. let's try again.

Jenkins please retest this.

**Comment by manstis** [comment]
Test failures unrelated :-)

Let's try again.

Jenkins please retest this.

**Comment by manstis** [comment]
Test failure unrelated... try again.

Jenkins please retest this.

**Comment by manstis** [comment]
Test failure unrelated... try again.

Jenkins please retest this.

**Comment by manstis** [comment]
Test failure unrelated... try again.

Jenkins please retest this.

**Comment by manstis** [comment]
Green...

Jenkins please retest this.

**Comment by manstis** [comment]
Green...

Jenkins please retest this.

**Comment by manstis** [comment]
Green...

Jenkins please retest this.

**Comment by manstis** [comment]
Test failure unrelated... try again.

Jenkins please retest this.

**Comment by manstis** [comment]
Test failure unrelated... try again.

Jenkins please retest this.

**Comment by manstis** [comment]
Test failure unrelated... try again.

Jenkins please retest this.

**Comment by manstis** [comment]
Test failure unrelated... try again.

Jenkins please retest this.

**Pull request merged**
