### PR TITLE
DROOLS-3140: [DMN Designer] Function: Add additional Properties to drill-down

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-3140

This PR depends on https://github.com/kiegroup/kie-wb-common/pull/2188 being first merged.

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
@manstis please let me know once rebased.

**Comment by manstis** [comment]
@jomarko Rebased.

**Pull request merged**
