### PR TITLE
JBPM-8674: Stunner - Boundary error event causes broken process in Cz…

### PR DESCRIPTION
**Pull request by LuboTerifaj**
…ech language

This is a fix for https://issues.jboss.org/browse/JBPM-8674.

### CODE REVIEW

**Comment by hasys** [comment]
Hi @LuboTerifaj, code looks good, thank you, waiting for Full Downstream Build to finish testing.

### Check list
- [x] Affected version is set property
- [x] Is realization aligned to jira description?
- [ ] Both Jenkins jobs are green

### Code review
- [x] Code coverage
- [x] License headers
- [x] Static analyser gates
- [x] Code Style

### Acceptance Criteria
> * Run Business Central with CZ locale, and reproduce Steps To Reproduce

- [ ] Tested with full downstream build
  - [ ] Firefox
  - [ ] Chrome

### Found issues
>  **Blocker**, **Critical** and **Major** bugs and **Blocker** and **Critical** enhancements should be fixed before merge.
* None

### Used resources
Processes for quick test can be found here: TBD

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hello @romartin ,

can you please have a look at this PR as well?

Thank you!

**Pull request merged**
