### PR TITLE
[JBPM-8153] Container is removed from UI even though it was not possible to stop it.

### PR DESCRIPTION
**Pull request by elguardian**
offline detection is not correct in the console

### CODE REVIEW

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by elguardian** [comment]
jenkins please retest this

**Comment by domhanak** [comment]
@elguardian Hi, can this be closed or what is the status?

**Comment by elguardian** [comment]
please review.

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by cristianonicolai** [comment]
@elguardian would be possible to add some test for this?

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by mareknovotny** [comment]
jenkins retest this please

**Pull request closed without merging**
