### PR TITLE
JBPM-5571: Stunner - Improve notification message descriptions & Integration of the Problems Widget

### PR DESCRIPTION
**Pull request by alepintus**
Hi @romartin , @hasys ,
I have integrated  the message console  to stunner project showcase and I have added the listener to deliver error notifications to the message console.

For more information see [this ticket](https://issues.jboss.org/browse/JBPM-5571
).

Can you please review this PR?

Thanks.

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
ok to test

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
About point (2) in my last comment, added here  a screenshot as an example - if you save a bpmn diagram with no end event present, a warning popup appears, but nothing on the problems widget, and as the warning disappears at some point, I think would be good having the warn's description too in the widget.

**Comment by alepintus** [comment]
Hi @romartin, @hasys

PR updated with a new notification observer to deliver Warnings notifications to the message console.
I have also added a link to the BPM process relative to the errors and warnings displayed in the message console

Can you please review?

Thanks!

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @manstis Full downstream build is green now, PR is ready to merge. Thank you!

**Pull request merged**
