### PR TITLE
JBPM-7237: Form migration tool crashes with NPE

### PR DESCRIPTION
**Pull request by pefernan**
@jhrcek could you please take a look?

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by jhrcek** [comment]
@pefernan I think this retest won't help. It looks like FormDisplayerTest is [failing deterministically in all PRs](http://janhrcek.cz/random-failures/#/class/org.kie.workbench.common.stunner.forms.client.widgets.container.displayer.FormDisplayerTest/method/testRenderElementForSecondTimeWithValidationFailure)..

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Pull request merged**
