### PR TITLE
RHPAM-2920: Notification subject in Designer is shorter than in DB scripts

### PR DESCRIPTION
**Pull request by hasys**

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin, @LuboTerifaj,

just tested full doewsntream build, looks good to me. PR is ready for review. Thank you!

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
jenkins execute full downstream production build

**Comment by hasys** [comment]
Looks like I need to rebase PR to build a war file. Going to do it now.

<details>
  <summary>Error log</summary>
  <pre>[INFO] Drools Workbench - WebApp 7.38.0-SNAPSHOT .......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:49 min
[INFO] Finished at: 2020-05-25T08:57:49-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project drools-wb-dtable-xls-editor-client: Compilation failure: Compilation failure: 
[ERROR] /home/jenkins/workspace/KIE/master/upstream-downstream/kie-wb-common.downstream.production/kiegroup_drools-wb/drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-client/src/main/java/org/drools/workbench/screens/dtablexls/client/handlers/NewDecisionTableXLSHandler.java:[117,24] cannot find symbol
[ERROR]   symbol:   method getFilenameSelectedToUpload()
[ERROR]   location: variable uploadWidget of type org.kie.workbench.common.widgets.client.widget.AttachmentFileWidget
[ERROR] /home/jenkins/workspace/KIE/master/upstream-downstream/kie-wb-common.downstream.production/kiegroup_drools-wb/drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-client/src/main/java/org/drools/workbench/screens/dtablexls/client/handlers/NewDecisionTableXLSHandler.java:[117,78] cannot find symbol
[ERROR]   symbol:   method getFilenameSelectedToUpload()
[ERROR]   location: variable uploadWidget of type org.kie.workbench.common.widgets.client.widget.AttachmentFileWidget
[ERROR] /home/jenkins/workspace/KIE/master/upstream-downstream/kie-wb-common.downstream.production/kiegroup_drools-wb/drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-client/src/main/java/org/drools/workbench/screens/dtablexls/client/handlers/NewDecisionTableXLSHandler.java:[131,29] cannot find symbol
[ERROR]   symbol:   method getFilenameSelectedToUpload()
[ERROR]   location: variable uploadWidget of type org.kie.workbench.common.widgets.client.widget.AttachmentFileWidget
[ERROR] -> [Help 1]</pre>
</details>

**Comment by hasys** [comment]
jenkins execute full downstream production build

**Comment by hasys** [comment]
Hi @LuboTerifaj, @domhanak, it is finally green and ready for review. Thank you!

**Comment by LuboTerifaj** [comment]
Hey @hasys , there is no upstream FDB. Do you have any idea why?

**Comment by hasys** [comment]
Hi @LuboTerifaj, because it was replaced by `Linux - full downstream production`. You can download the build [here](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/upstream-downstream/job/kie-wb-common.downstream.production/5/artifact/kiegroup_kie-wb-distributions/business-central-parent/business-central-distribution-wars/business-central/target/).

image

**Comment by LuboTerifaj** [comment]
@hasys but this is not community build, but the productized one.

**Comment by hasys** [comment]
@LuboTerifaj there is no differences from this PR point of view. I compiled it because I saw that this one at least work now and PR can be tested. When Full Downstream Build will be fixed we can go back to it. But anyway I see no difference for this PR where to test it in community or in the product.

Do you need a community build anyway?

**Comment by hasys** [comment]
Thank you @LuboTerifaj!

@romartin this PR is ready for merge. Thank you!

**Pull request merged**
