### PR TITLE
[7.7.x] AF 1203  Pom Editor 

### PR DESCRIPTION
**Pull request by desmax74**
Pom Editor must remove/add/update-url from repos and pluginRepos during the migration using a pom-migration.json file

Cherryy picked from [AF-1203](https://github.com/desmax74/kie-wb-common/commit/370b7c94a08639459138a78603af0649b4199dc8)

https://issues.jboss.org/browse/AF-1203

### CODE REVIEW

**Comment by desmax74** [comment]
@porcelli @krisv @jakubschwan @jhrcek

**Comment by desmax74** [comment]
jenkins retest this

**Comment by desmax74** [comment]
jenkins retest this

**Comment by krisv** [comment]
jenkins retest this

**Comment by krisv** [comment]
jenkins retest this

**Pull request merged**
