### PR TITLE
KOGITO-368: [DMN Designer] User can not add an enumeration constraint

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/KOGITO-368

### CODE REVIEW

**Comment by manstis** [comment]
Hi @jomarko regarding the issue you found with manual testing.

I found that `-standalone` worked the same as `-kogito` i.e. re-opening the diagram and changing the constraint type to an enumeration whilst updating the UI to _look like_ an enumeration saving the data-type change and saving the diagram; re-opening still had it set as an expression.

I checked the resulting DMN file following the change to enumeration, save of data-type and save of diagram and the XML still shows the constraint type as expression. Therefore I feel this is not a new issue (if you can indeed re-test and verify the same behaviour) but a new issue.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@jomarko This PR is ready for re-review.

The [issue](https://github.com/kiegroup/kie-wb-common/pull/2985#pullrequestreview-309253610) you last raised appears to now work consistently for both `-standalone` and `-kogito` (all be it that it is still bugged in that if you save the diagram after changing the constraint type to enumeration and look at the DMN XML it shows expression and re-opening the file shows the constraint type as expression).

Since this behaviour is consistently (wrong) a new JIRA should be raised for the issue. 

In KOGITO the enumeration items overlap however that is covered by [KOGITO-526](https://issues.jboss.org/browse/KOGITO-526).

**Comment by jomarko** [comment]
```
[INFO]          [ERROR] Errors in 'jar:file:/home/jomarko/.m2/repository/org/kie/workbench/kie-wb-common-dmn-webapp-kogito-common/7.29.0-SNAPSHOT/kie-wb-common-dmn-webapp-kogito-common-7.29.0-SNAPSHOT-sources.jar!/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/BaseDMNDiagramEditor.java'
[INFO]             [ERROR] Line 269: The method destroy() is undefined for the type DecisionNavigatorDock
[INFO]             [ERROR] Line 272: The method destroy() is undefined for the type DiagramEditorPropertiesDock
[INFO]             [ERROR] Line 273: The method destroy() is undefined for the type PreviewDiagramDock
[INFO]          Tracing compile failure path for type 'org.kie.workbench.common.dmn.webapp.kogito.common.client.editor.BaseDMNDiagramEditor'
[INFO]             [ERROR] Errors in 'jar:file:/home/jomarko/.m2/repository/org/kie/workbench/kie-wb-common-dmn-webapp-kogito-common/7.29.0-SNAPSHOT/kie-wb-common-dmn-webapp-kogito-common-7.29.0-SNAPSHOT-sources.jar!/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/BaseDMNDiagramEditor.java'
[INFO]                [ERROR] Line 269: The method destroy() is undefined for the type DecisionNavigatorDock
[INFO]                [ERROR] Line 273: The method destroy() is undefined for the type PreviewDiagramDock
[INFO]                [ERROR] Line 272: The method destroy() is undefined for the type DiagramEditorPropertiesDock
[INFO]          [ERROR] Hint: Check the inheritance chain from your module; it may not be inheriting a required module or a module may not be adding its source path entries properly
[INFO]          Unification traversed 234763 fields and methods and 24485 types. 24424 are considered part of the current module and 24424 had all of their fields and methods traversed.
[INFO]       [ERROR] Compiler returned false
[INFO]       [WARN] recompile failed
[INFO]       [WARN] continuing to serve previous version

```

**Comment by manstis** [comment]
@jomarko It looks like you did not compile all of `kie-wb-common` (or at least `kie-wb-common-stunner`) in addition to `kie-wb-common-dmn`. This PR includes a change to a Stunner module.

**Comment by manstis** [comment]
hehehe @jomarko I agree the Universe is behaving odd for you as it [works](https://issues.jboss.org/secure/attachment/12457195/KOGITO-368-manstis.mkv) fine for me.

Can you please retry when you get a chance? (I'd suggest deleting all folders entitled `gwt-xxxx` in your `/tmp` folder and any folder called `jomarko` in `/tmp` too - or whatever your User ID is on your computer).

The last bit of my video is fixed by [this](https://github.com/kiegroup/kie-wb-common/pull/2992).

**Pull request merged**
