### PR TITLE
JBPM-5645: Stunner - Add Throwing Intermediate Signal Event

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
weird, seems like the tst points to https://github.com/mswiderski/designer-playground.git 
Hello @mswiderski, would you mind take look if it's ok that the tst below points to this git direction?
Thanks.

org.jbpm.designer.repository.VFSRepositoryGitFileSystemTest.testCopyAsset

org.eclipse.jgit.api.errors.TransportException: https://github.com/mswiderski/designer-playground.git: cannot open git-upload-pack
Stacktrace

java.lang.RuntimeException: org.eclipse.jgit.api.errors.TransportException: https://github.com/mswiderski/designer-playground.git: cannot open git-upload-pack
	at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:210)
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:504)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:326)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1236)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:234)
	at org.uberfire.java.nio.fs.jgit.util.commands.Fetch.execute(Fetch.java:64)
	at org.uberfire.java.nio.fs.jgit.util.GitImpl.fetch(GitImpl.java:248)
	at org.uberfire.java.nio.fs.jgit.util.commands.Clone.execute(Clone.java:72)
	at org.uberfire.java.nio.fs.jgit.util.Git.clone(Git.java:91)
	at org.uberfire.java.nio.fs.jgit.JGitFileSystemProvider.createNewGitRepo(JGitFileSystemProvider.java:664)
	at

**Comment by wmedvede** [comment]
let's give it another try since independently of the tst, the error above was random.

Jenkins execute full downstream build

**Comment by mswiderski** [comment]
@wmedvede frankly speaking looks weird to have it there. most likely some left overs from old days, @tsurdilo or was it another reason for it?

**Pull request merged**
