### PR TITLE
[7.2.x] RHBRMS-2874: Start/stop container buttons should be enabled/disabled only when the operation finished

### PR DESCRIPTION
**Pull request by karreiro**
Cherry picked from https://github.com/kiegroup/kie-wb-common/pull/995

---

Part of an ensemble:
- https://github.com/kiegroup/kie-wb-common/pull/1002
- https://github.com/kiegroup/droolsjbpm-integration/pull/1082

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins execute full downstream build

**Comment by karreiro** [comment]
```

**Comment by karreiro** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
Agreed

**Pull request merged**
