### PR TITLE
AF-2760 : Permission configured in business-central is not applied when doing git clone from outside of BC

### PR DESCRIPTION
**Pull request by RishiRajAnand**
**Thank you for submitting this pull request**

AF-2760: https://issues.redhat.com/browse/AF-2760

**Referenced Pull Requests**:
https://github.com/kiegroup/appformer/pull/1184

**Business Central**: [WAR file](https://drive.google.com/drive/folders/1VOyRYI3mhoB_ZsG9OKU7FhLhkC-pYsqM?usp=sharing)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by RishiRajAnand** [comment]
jenkins do cdb

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Review by Srihari1192 — APPROVED** [review]

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Comment by RishiRajAnand** [comment]
jenkins do cdb

**Comment by RishiRajAnand** [comment]
jenkins do cdb

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Comment by RishiRajAnand** [comment]
jenkins do cdb

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Comment by RishiRajAnand** [comment]
jenkins retest this

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by RishiRajAnand** [comment]
jenkins retest this

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Comment by RishiRajAnand** [comment]
jenkins retest this

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by akumar074** [comment]
Ensemble PR https://github.com/kiegroup/kie-wb-distributions/pull/1125

**Pull request merged**
