### PR TITLE
== DO NOT MERGE == [7.30.x] DROOLS-4772: [DMN Designer] Open Properties panel by default (#3021)

### PR DESCRIPTION
**Pull request by manstis**
**== DO NOT MERGE ==**

See https://issues.jboss.org/browse/RHDM-1160

There is some dispute as to whether we want to do this for DMN.

(cherry picked from commit 5c3a3a8c1a54e10de9a12132f925754dc801e1e7)

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by Josephblt** [comment]
Hello @manstis. I tested it with the web standalone app. I don't know if this is the right thing but the dock opened but the explorer view was selected. Is this right?

**Comment by manstis** [comment]
Hi @Josephblt unfortunately you'd need to run at least `drools-wb-webapp`.

This is the _first_ webapp to use the Stunner `-project-client` module that uses `org.kie.workbench.common.stunner.project.client.docks.StunnerDocksHandler` for dock support.

`kie-wb-distributions` is even better to use.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@Josephblt FDB requested.. you should get some WARs out of it to test with `kie-wb-distributions`.

**Comment by Josephblt** [comment]
Jenkins please execute full downstream build

**Comment by manstis** [comment]
Closing as this feature is not to be implemented for DMN.

See discussion on https://issues.jboss.org/browse/RHDM-1160

**Pull request closed without merging**
