### PR TITLE
KOGITO-475: [DMN Designer] Move kogito related modules to default (Maven) profile

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/KOGITO-475

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko Looking at the log I see all DMN modules compiled:
```
12:27:36 [INFO] Kie Workbench - Common - DMN ....................... SUCCESS [  0.043 s]
12:27:36 [INFO] Kie Workbench - Common - DMN - API ................. SUCCESS [  0.104 s]
12:27:36 [INFO] Kie Workbench - Common - DMN - Client .............. SUCCESS [  0.169 s]
12:27:36 [INFO] Kie Workbench - Common - DMN - Backend ............. SUCCESS [  0.178 s]
12:27:36 [INFO] Kie Workbench - Common - DMN - Project API ......... SUCCESS [  0.089 s]
12:27:36 [INFO] Kie Workbench - Common - DMN - Project Client ...... SUCCESS [  0.213 s]
12:27:36 [INFO] Kie Workbench - Common - DMN - Webapp Common ....... SUCCESS [  0.170 s]
12:27:36 [INFO] Kie Workbench - Common - DMN - Standalone Showcase webapp SUCCESS [  0.343 s]
12:27:36 [INFO] Kie Workbench - Common - DMN - Kogito Marshaller ... SUCCESS [  0.731 s]
12:27:36 [INFO] Kie Workbench - Common - DMN - Kogito webapp common  SUCCESS [  0.264 s]
12:27:36 [INFO] Kie Workbench - Common - DMN - Kogito runtime webapp SUCCESS [  0.334 s]
12:27:36 [INFO] Kie Workbench - Common - DMN - Kogito testing webapp SUCCESS [  0.499 s]
```

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@mbiarnes Hello, this PR is failing with Maven exit code 137.. which looks to mean [OOM](https://stackoverflow.com/questions/6773726/command-mvn-package-fails-with-status-137).

New modules are being added to the build and hence it's likely a FDB will now need more resources.

Is this something you can look into?

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@mbiarnes @mareknovotny Hello.. I think I've exhausted my retries of this PR.

Each fails with a [Maven Code 137](https://stackoverflow.com/questions/24989653/jenkins-maven-build-137-error) that is suggesting a VM OOM situation. This PR enables a handful of new modules relating to kogito that are currently not built as part of the _default_ maven profile. Other PRs without the new modules appear unaffected.

Could you please investigate? I'm able to build this repository locally, without problem (although I probably have different maven arguments to what our Jenkins uses).

**Comment by mareknovotny** [comment]
@manstis the build slave node has 24GB RAM (that is the max we can get now). Raising that limit will impact all our builds later (downstream, release) and merging this PR into master will impact all our builds and workflows. You need to figure out why the more memory is required.

We talked about it before DON'T add something related to KOGITO directly here in master. There were conversation that we will have only integration to be used by current 7.x stream and kogito tooling.  This is like snowballing effect with performance and slowdown the build which affects all of us.

**Comment by manstis** [comment]
@mareknovotny Understood.. I'll try something different.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@jomarko @mareknovotny I got the FDB green by changing the build configuration.

GWT compilation of `-webapp-kogito-xxx` is skipped unless the `kogito` profile is used.

This is OK as the two webapps are only used when testing with `mvn clean process-resources gwt:debug` so now we'll simply have to do `mvn clean process-resources gwt:run -Pkogito`. Module `-webapp-kogito-runtime` _could_ move to `kogito-tooling` when things are more stable and builds of the VSCode/GitHub plugins do not require manual copying of folders around.

**Pull request merged**
