### PR TITLE
DROOLS-4807: [DMN Designer] Do not group V&V messages by UUID

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/DROOLS-4807

@hasys @romartin Please see the comment [here](https://issues.redhat.com/browse/DROOLS-4807?focusedCommentId=13823269&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13823269) suggesting the change in this PR should apply to BPMN in addition to DMN.

### CODE REVIEW

**Comment by jomarko** [comment]
@manstis hello, here is the difference I see between master and your PR. Doesn't seem to me any change in number of messages. Do I miss something?

#### master
Screenshot from 2019-12-18 15-23-47

#### PR
Screenshot from 2019-12-18 15-14-02

**Comment by manstis** [comment]
@jomarko File attached to the JIRA.

**Comment by manstis** [comment]
@hasys @romartin New Year reminder to please review this PR :-)

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by hasys** [comment]
Hi @manstis, code and tests looks good to me, waiting for Full build to test. Thank you!

Jenkins execute full downstream build

**Comment by manstis** [comment]
FDB is likely to need https://github.com/kiegroup/kie-wb-common/pull/3095

**Comment by hasys** [comment]
@manstis ok, will wait for it. Thank you for the info.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by hasys** [comment]
Hi @manstis works great at runtime, thank you!

### Check list
- [x] Affected version is set property
- [x] Is realization aligned to jira description?
- [x] Are DMN and CM verified?
  - [x] DMN
- [x] Both Jenkins jobs are green
  * report an issue if not

### Code review
- [x] Code coverage
- [x] License headers
- [x] Static analyser gates
- [x] Code Style

### Acceptance Criteria
> * Create process add Start Event, Script Task, End Event, don't connect them
> * Press Validation Button
> * **Expected Result**: all error messages for Script Task will be reported on separate lines.

- [x] Tested with full downstream build
  - [x] Firefox

### Found issues
>  **Blocker**, **Critical** and **Major** bugs and **Blocker** and **Critical** enhancements should be fixed before merge.
* None

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@romartin Did you want to review before I merge?

**Pull request merged**
