### PR TITLE
DROOLS-2818: [DMN Designer] [IE11] Rename throws an Error

### PR DESCRIPTION
**Pull request by danielzhe**
Is the same situation of #2105 but in different method.

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by danielzhe** [comment]
@manstis merge, please

**Comment by danielzhe** [comment]
Jenkins please retest this.

**Comment by danielzhe** [comment]
Jenkins please retest this.

**Comment by danielzhe** [comment]
@manstis Merge, please.

**Pull request merged**
