### PR TITLE
JBPM-8429: Stunner - Error once updating form fields. 

### PR DESCRIPTION
**Pull request by romartin**
Hey @hasys 

Here is the fix for [JBPM-8429](https://issues.jboss.org/browse/JBPM-8429)

PS: Also refactored some tests by removing as much as possible duplicated code found.

Thanks!
Roger

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
hey @hasys - please don't spend time on this review yet, I've found a bug and I'm working on it. I'll let you know once it's ready again. 
Thanks and sorry for the inconveniences!

**Comment by romartin** [comment]
Hey @hasys - fixed and rebased, all ready for review, thanks! :+1:

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by hasys** [comment]
Hi @romartin,

I am still able to see some (another one) exception there: 
image

<details>
  <summary>Full stack trace</summary>
  <pre>Error: IllegalArgumentException: Enum constant undefined: LEFT
    at dfn.bX [as Rg] (Throwable.java:120)
    at dfn.eX [as Tg] (Throwable.java:112)
    at dfn._W (Throwable.java:66)
    at dfn.iX (Exception.java:29)
    at dfn.Ilb (RuntimeException.java:29)
    at new dfn (IllegalArgumentException.java:29)
    at ULn (InternalPreconditions.java:351)
    at M$ (Enum.java:57)
    at Oeb (DirectionLayout.java:33)
    at N$ (Enum.java:41)
    at t0V.u0V [as gd] (WiresTextDecorator.java:325)
    at aLX (Exceptions.java:40)
    at b_V (WiresTextDecorator.java:325)
    at v0V.x0V [as Gi] (WiresTextDecorator.java:337)
    at fLn (StreamImpl.java:317)
    at jLn.kLn [as Xf] (StreamImpl.java:317)
    at izn (Spliterators.java:463)
    at jzn.qzn [as om] (Spliterators.java:459)
    at gLn (StreamImpl.java:317)
    at hLn.iLn [as om] (StreamImpl.java:316)
    at szn (Spliterator.java:52)
    at hLn.Kzn [as Ni] (Spliterator.java:51)
    at kJn (StreamImpl.java:663)
    at ZIn (StreamImpl.java:587)
    at y_V (WiresTextDecorator.java:330)
    at iPQ.MOQ [as EEb] (WiresShapeViewExt.java:124)
    at gmX (FontHandler.java:191)
    at hmX (FontHandler.java:169)
    at sHU.tHU [as Fm] (BPMNShapeDef.java:41)
    at lHQ (AbstractElementShape.java:58)
    at tiX.uiX [as Xf] (AbstractElementShape.java:58)
    at dyn (Optional.java:66)
    at MKQ.sHQ [as uDb] (AbstractElementShape.java:56)
    at PhW (BaseCanvasHandler.java:249)
    at woW.iiW [as jMb] (BaseCanvasHandler.java:203)
    at hhW (AbstractCanvasHandler.java:317)
    at woW.phW [as lMb] (AbstractCanvasHandler.java:311)
    at woW.KhW [as QMb] (AbstractCanvasHandler.java:304)
    at XRW.YRW [as qBb] (UpdateCanvasElementPropertyCommand.java:33)
    at jqP (AbstractCanvasGraphCommand.java:158)
    at iqP (AbstractCanvasGraphCommand.java:91)
    at RTW.oqP [as sBb] (AbstractCanvasGraphCommand.java:87)
    at RTW.nqP [as qBb] (AbstractCanvasGraphCommand.java:87)
    at vqX (CommandManagerImpl.java:64)
    at O_W (CanvasCommandManagerImpl.java:87)
    at a0W.b0W [as gd] (CanvasCommandManagerImpl.java:87)
    at U_W (CanvasCommandManagerImpl.java:106)
    at M_W (CanvasCommandManagerImpl.java:84)
    at V_W.X_W [as Bhb] (CanvasCommandManagerImpl.java:84)
    at IGE (DelegateCommandManager.java:46)
    at SGE (AbstractSessionCommandManager.java:58)
    at dIE.YGE [as Hhb] (AbstractSessionCommandManager.java:55)
    at gIE.lIE [as Hhb] (Type_factory__o_k_w_c_s_c_c_c_SessionCommandManagerImpl__quals__j_e_i_Any_o_k_w_c_s_c_c_s_Session.java:89)
    at RGE (AbstractSessionCommandManager.java:55)
    at z3X (FormsCanvasSessionHandler.java:158)
    at B3X (FormsCanvasSessionHandler.java:145)
    at _2X (FormPropertiesWidget.java:181)
    at n3X.o3X [as dGb] (FormPropertiesWidget.java:179)
    at dMR (FieldChangeHandlerManagerImpl.java:126)
    at fMR (FieldChangeHandlerManagerImpl.java:116)
    at zMR (FieldChangeHandlerManagerImpl.java:85)
    at OMR (FormHandlerImpl.java:143)
    at PMR.QMR [as dGb] (FormHandlerImpl.java:143)
    at dMR (FieldChangeHandlerManagerImpl.java:126)</pre>
</details>

**Comment by romartin** [comment]
@hasys hmmm lemme check it, np. Thanks!

**Comment by romartin** [comment]
Hey @hasys 
I think that error you mention was due the code was not rebased, and it was not aligned with latest lienzo-core snapshot as well. I've rebased and cannot reproduce it anymore, also looking at lienzo code before @tiagodolphine 's lastest stuff and it makes sense it was due to a missing rebase.
So rebased everything and ready to test again.
Thanks!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin, not sure, looks like now build is broken. Doesn't look like it is related to this PR so let's try to rerun it.

Jenkins retest please

**Comment by romartin** [comment]
Hey @hasys 
It looks the JVM crashed during the build :(
```
22:22:53 [INFO] #
22:22:53 [INFO] # A fatal error has been detected by the Java Runtime Environment:
22:22:53 [INFO] #
22:22:53 [INFO] #  SIGSEGV (0xb) at pc=0x00007faee59f4c7b, pid=13850, tid=0x00007faed8343700
22:22:53 [INFO] #
22:22:53 [INFO] # JRE version: Java(TM) SE Runtime Environment (8.0_202-b08) (build 1.8.0_202-b08)
22:22:53 [INFO] # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.202-b08 mixed mode linux-amd64 compressed oops)
22:22:53 [INFO] # Problematic frame:
22:22:53 [INFO] # J 4631 C2 java.io.ObjectStreamClass.lookup(Ljava/lang/Class;Z)Ljava/io/ObjectStreamClass; (335 bytes) @ 0x00007faee59f4c7b [0x00007faee59f4bc0+0xbb]
22:22:53 [INFO] #
22:22:53 [INFO] # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
22:22:53 [INFO] #
22:22:53 [INFO] # An error report file with more information is saved as:
22:22:53 [INFO] # /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-downstream-pullrequests/hs_err_pid13850.log
22:22:53 [INFO] #
22:22:53 [INFO] # If you would like to submit a bug report, please visit:
22:22:53 [INFO] #   http://bugreport.java.com/bugreport/crash.jsp
22:22:53 [INFO] #
```
So re-firing the build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin,

no, rebase didn't fix the issue.

Screenshot from 2019-05-15 11-14-38

I did a small research and it looks to me that this exception is by design, see https://github.com/kiegroup/kie-wb-common/pull/2557/files#diff-30cc565a571993b66f4f513c00f0617dR338

If vertical alignment throws exception -> swallow it and try horizontal one.

@romartin, @tiagodolphine is my guess is correct? If yes, I think, it's better to find a better way to handle it.

I reported an issue for this task:
* [JBPM-8486](https://issues.jboss.org/browse/JBPM-8486) - Stunner - any forms property modification leads to printing errors in browser console

**Comment by tiagodolphine** [comment]
Hi @hasys , this was a way to overcome the behavior of the [Enum](https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html#valueOf-java.lang.Class-java.lang.String-)
API that throws an exception if none constant is found instead of return null, the code retuns null in case the exception of not found, one other option is to iterate over all the enum values and see which one maches the Constant, anyway we can handle this on a new jira you already created, but this log on the console it not good at all.
Tks

**Comment by romartin** [comment]
great research job @hasys , thanks! Yeah I'm also agree on trying to find out some other way to handle this stuff. :+1:

**Pull request merged**
