### PR TITLE
[7.7.x] RHPAM-1246: Stunner - Cannot import mortgages process

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin @hasys would you mind review this PR.
Adds a quick win for 7.0.2.
Thanks.

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by hasys** [comment]
ping @jsoltes

**Comment by jsoltes** [comment]
pong @hasys according to the new agile teams, I no longer review this - it's up to you and @LuboTerifaj

**Comment by wmedvede** [comment]
jenkins execute full downstream build

**Comment by wmedvede** [comment]
@krisv would you mind take a look at the acks for this https://issues.jboss.org/browse/RHPAM-1246, I think it might be nice to add this for the 7.0.2.
Thanks

**Comment by romartin** [comment]
@wmedvede the title says "do not merge", but at this point, it should be merged once approved, right? All ACKs have been also set.

**Comment by wmedvede** [comment]
@romartin @hasys all required acks are now in place, so this can be merged as soon it's approved

**Comment by romartin** [comment]
Jenkins please retest this

**Pull request merged**
