### PR TITLE
JBPM-9275 - Stunner - '^' character in Notification subject in User task breaks the process

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin,

I tested it locally and it works now, I can save and reload the process without issues, uploading a WAR (some connection issue, it takes time today), will attach it later.

@domhanak, @LuboTerifaj do we need your approve or we can assign second Software Engineer to a review?

Thank you!

## Business Central build
https://drive.google.com/file/d/16r5eNFShPjak1gsPmHq1XGBmzRHWBY8I/view?usp=sharing

## VS Code extension
https://drive.google.com/file/d/1IUKYH1Zvt-0HqiLdGm7rGTLPRaaHrAF0/view?usp=sharing

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute compile downstream build

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Hi @mareknovotny, @mbiarnes,

I can't retrigger regular PR build here, if you open current failed build you will see that it was fail almost 5 days ago:
image

But since than I already tried twice to retrigger it again, but without success:
image

Is it something known? How can I retrigger the build?

**Comment by hasys** [comment]
Hi @LuboTerifaj I think it is expected. Since it will be stored in the XML in the same way. In general I think it is the corner so thank you for the reported issue, let's discuss it there 👍

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest this

**Comment by romartin** [comment]
Jenkins retest this

**Comment by hasys** [comment]
Hi @kiegroup/gatekeepers this PR is ready for the merge, thank you!

**Pull request merged**
