### PR TITLE
[7.7.x] JBPM-6914: Changes in options are saved on cancel

### PR DESCRIPTION
**Pull request by pefernan**
Backport of https://github.com/kiegroup/kie-wb-common/pull/1872

@jsoltes could you please review?

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by ederign** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Pull request merged**
