### PR TITLE
    - New project showcase (based on drools-wb showcase)

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi @romartin , would you mind review this PR?
Thanks

**Comment by romartin** [comment]
Hey @hasys , this commit only affects the concrete Stunner showcase, it has no implications on the downstream projects, so does not makes sense neither downloading the generated war... but added you as a reviewer for double checking, if you want to :)

**Comment by romartin** [comment]
Jenkins execute full downstream

**Comment by romartin** [comment]
NOTE: Executing the downstream project builds just to double checks this has no implications and all it's fine

**Comment by wmedvede** [comment]
@romartin good catch, the README file was lost during the refactoring. It was added again.

**Comment by wmedvede** [comment]
@hasys I've added your commits with the profile and license fixes to the PR, thanks!

The error "Unsatisfied dependencies for type CaseManagementDefinitionSetResourceType" doesn't happen in my local. But we can take a look in case it's starts to happen again. Let's see if @romartin can give it a try.

**Comment by romartin** [comment]
Jenkins execute full downstream

**Comment by romartin** [comment]
@wmedvede  @hasys  I tested it yesterday and it was working fine, no issues. Anyway testing again just to double check... it's important having this showcase working well. Will let you know asap, thanks guys!

**Comment by romartin** [comment]
Please, can you @tiagodolphine or @alepintus check as well that this new showcase works for you? It works for me via command line but not for @hasys ... thx!

**Comment by hasys** [comment]
Hi @wmedvede, @romartin 
Thank you, I rebased this PR to master, recompiled entire Stunner and kiegroup/lienzo-core. Now it works (both gwt:run and sourceMaps profile as well), sorry for confusing you!

I have no IDEA Ultimate Edition, so won't be able to test it from IDE. It will be on you @romartin, @wmedvede, sorry.

**Comment by alepintus** [comment]
Hi @wmedvede @romartin @hasys ,
tested locally and all works fine from command line and also from IntelliJ IDEA.

Thanks!

**Comment by wmedvede** [comment]
@romartin @romartin the missing exclusions suggested by @romartin were added and rebased with master too. And it's working locally.
Let's try to move this forward too.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Pull request merged**
