### PR TITLE
KOGITO-1529: BPMN Editor - Cannot save a process once a service tasks' attributes are not properly set

### PR DESCRIPTION
**Pull request by romartin**
Hey @domhanak @LuboTerifaj 

This PR fixes the issue [KOGITO-1529](https://issues.redhat.com/browse/KOGITO-1529)

**[Not Urgent]** It cannot yet be tested until having [KOGITO-1426](https://issues.redhat.com/browse/KOGITO-1426) done, so no worries for now, but I could reproduce and fix it locally so creating the PR with the fix for further re-integration.

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hi @romartin can you please let me know once this is ready to review? Thanks!

**Comment by romartin** [comment]
Hey @LuboTerifaj 

Once this PR gets closed I'll be able to rebase on top of it and update this PR:

**Comment by romartin** [comment]
Hey @LuboTerifaj 

I've rebased this fix for service tasks on top of master, also tested and it works for me.  Could you please do a review here as well? It's important having this fix for the next kogito release.

CC @ederign @pefernan good job guys! :+1: 

Thanks!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Hey @romartin  I've tested in VSCode and I found an issue. I'm not sure it is related.

- Create a new process, add a service task.
- Close and reopen the process
- Select the Service Task and then modify/add some properties in the properties panel.
- Hit Ctrl + S to save

The Form validation will complain that Package may not be empty and won't save the process. 
If you inform the Package it will save the process. However if you close and reopen the process, the Package is not being saved.
WDYT?

**Comment by romartin** [comment]
Hey @handreyrc 

Good catch! But yeah it's not related, ti's already reported: https://issues.redhat.com/browse/KOGITO-1586

So are we good to go?? :)

Thx!

**Comment by romartin** [comment]
The test failure which is constantly failing is not related to this PR: `org.guvnor.ala.services.rest.tests.RestRuntimeProvisioningImplTest.testAPI`

Will not prevent from merging.

**Pull request merged**
