### PR TITLE
[8.0.x] JBPM-5531: Problems after deleting a form that is used as a subform in other form.

### PR DESCRIPTION
**Pull request by pefernan**
Copy of https://github.com/kiegroup/kie-wb-common/pull/1009

Dear @manstis @Rikkola @wmedvede @jsoltes this PR has the same changes than the previous 7.2.x  PR... but would you mind review it?

This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/493
https://github.com/kiegroup/kie-wb-common/pull/1011
https://github.com/kiegroup/drools-wb/pull/564
https://github.com/kiegroup/optaplanner-wb/pull/193
https://github.com/kiegroup/jbpm-wb/pull/819
https://github.com/kiegroup/kie-wb-distributions/pull/565
https://github.com/kiegroup/jbpm-form-modeler/pull/126

### CODE REVIEW

**Comment by manstis** [comment]
@pefernan Will review/approve when the 7.2.x PRs are merged.

**Comment by pefernan** [comment]
@manstis @wmedvede @Rikkola added all the change requests from 7.2 here too.

**Comment by Rikkola** [comment]
@pefernan did it all go in smoothly or was there any conflicts that might need special attention?

**Comment by pefernan** [comment]
@Rikkola everything smooth, no conflicts found.

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
Well, at least it seems that the jenkins issue isn't related with my changes.

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
OMG I see it green!

**Comment by pefernan** [comment]
@manstis could it be merged?

**Comment by manstis** [comment]
@pefernan @jsoltes hasn't reviewed/approved any of the PRs.

**Comment by pefernan** [comment]
omg you're right

**Comment by jsoltes** [comment]
@manstis no I have approved all of them...

**Comment by manstis** [comment]
@jsoltes You have now!

**Comment by manstis** [comment]
@wmedvede Could you please approve this?

**Comment by manstis** [comment]
@pefernan They're all green and approved.. all that's needed is this conflict to be fixed...

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
@manstis could you merge it before jenkins decides to make it fail?

**Comment by manstis** [comment]
@pefernan with the greatest of pleasure :-)

**Pull request merged**
