### PR TITLE
JBPM-6977: Stunner - missing "Is interrupting" property in events

### PR DESCRIPTION
**Pull request by alepintus**
Hi @romartin @hasys @wmedvede ,
Is Interrupting property added to StartErrorEvent.
For more information see [this ticket](https://issues.jboss.org/browse/JBPM-6977).

Could you please take a look?

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
ok to test

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by alepintus** [comment]
Hi @romartin ,
yes, it’s right. 
Thanks!

**Comment by evacchi** [comment]
@hasys have you checked whether these tests are now in the new PR #1460 ? I should have rebased and added those tests already

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Pull request merged**
