### PR TITLE
JBPM-8303 Stunner - Alerts panel opens everytime designer rules are violated

### PR DESCRIPTION
**Pull request by tiagodolphine**
Now the alerts panel remains closed/hidden when validation is triggered.

@romartin 
@LuboTerifaj

### CODE REVIEW

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj the save, rename, copy actions are handled by the workbench, not by stunner, so the alerts panel are being shown because the workbench is doing this. To test it you can try to open other editors: Data Object, Global Variables, Work item definition, etc and test the same scenario. With that said, we have some possibilities:
- Try to make Stunner force hiding the alerts panel on those actions, don't know if this is possible, we need to investigate.
- Modify the workbench, but this will impact the whole workbench, all the editors, this change is probably up to the foundation team, then it is necessary to speak to the guys there and open a JIRA.
@romartin @LuboTerifaj  WDYT?

**Comment by romartin** [comment]
Hey @LuboTerifaj , thanks for pointing this out, good point! Anyway agree with @tiagodolphine , that's a generic feature, so we should report a new issue for the fundation team about it. 

I've tested this fixed WAR and at least the error that @hasys reported on the ticket is not present, so I'm fine with this PR :+1:

**Comment by hasys** [comment]
Hi @tiagobento, @romartin, @LuboTerifaj,

I am also voting for the second possibility: create new issue for the foundation team. Since it is more generic task and will affect other editors. I think we should avoid workarounds as described in the first point: force Stunner to workaround Appformer issues.

**Comment by tiagodolphine** [comment]
So @romartin  @LuboTerifaj I think we can merge this PR, just need the approval, the next step is to open a new JIRA to foundation regarding this issue, can you do it please @LuboTerifaj, since you found the issue, it is better to explain.
Thanks.

**Comment by romartin** [comment]
yep please @LuboTerifaj , let's report the new issue and try to move this PR forward. I'll merge once having  the approval. 
Thanks in advance! :+1:

**Pull request merged**
