### PR TITLE
[AF-1843]: Removed "build already running" message

### PR DESCRIPTION
**Pull request by adrielparedes**
Message removed. The only thing I also found and may be we should consider to address a new issue is that two users can build the same branch at the same time, but need to investigate a bit more.

@porcelli would you mind to review?

### CODE REVIEW

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
jenkins execute full downstream build

**Comment by adrielparedes** [comment]
FDB Test failures are not related

**Comment by tomasdavidorg** [comment]
jenkins execute full downstream build

**Pull request merged**
