### PR TITLE
[DROOLS-3571] Rename Test Scenario

### PR DESCRIPTION
**Pull request by annabaker**

### CODE REVIEW

**Comment by annabaker** [comment]
@danielezonca @Rikkola

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by kkufova** [comment]
jenkins please retest this

**Comment by manstis** [comment]
@kkufova There's a long lasting failing test in `kie-wb-common`.

See the email to BSIG. It's probably not worth thrashing Jenkins until the test is fixed.

**Comment by annabaker** [comment]
jenkins please retest this

**Comment by annabaker** [comment]
@manstis can you please merge

**Pull request merged**
