### PR TITLE
[7.7.x] DROOLS-2555 : Broken welcome page layout in IE11

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit e7a62add60788f1562eb64b60d8497ab046c2bb1)

https://issues.jboss.org/browse/DROOLS-2555

Bundle, but can be merged individually.
https://github.com/kiegroup/kie-wb-common/pull/1801
https://github.com/kiegroup/kie-wb-distributions/pull/762

@jomarko If you could also take a look at this.

### CODE REVIEW

**Comment by Rikkola** [comment]
@tomasdavidorg Hi I see you were assigned as the tester. This one is the one that is urgent, but there is also one for master https://github.com/kiegroup/kie-wb-common/pull/1797.

**Comment by Rikkola** [comment]
jenkins please retest this

**Comment by Rikkola** [comment]
Come on. I would like to get this in today :-)

jenkins please retest this

**Comment by Rikkola** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by Rikkola** [comment]
Thanks for the restarts. Just image and style changes and they need at least 5 restarts :)

**Comment by Rikkola** [comment]
Locally I only get the following failures, but these are always there since the build does not work for some reason on my computer.

```
kie-wb-common-ala/kie-wb-common-ala-docker-provider/src/test/java/org/guvnor/ala/docker/executor/DockerExecutorTest.java
kie-wb-common-ala/kie-wb-common-ala-services-rest/src/test/java/org/guvnor/ala/services/rest/tests/RestPipelineImplTest.java
kie-wb-common-ala/kie-wb-common-ala-services-rest/src/test/java/org/guvnor/ala/services/rest/tests/RestRuntimeProvisioningImplTest.java
kie-wb-common-ala/kie-wb-common-ala-wildfly/kie-wb-common-ala-wildfly-provider/src/test/java/org/guvnor/ala/wildfly/executor/tests/WildflyExecutorTest.java
kie-wb-common-ala/kie-wb-common-ala-wildfly/kie-wb-common-ala-wildfly-provider/src/test/java/org/guvnor/ala/wildfly/executor/tests/WildflyRuntimeTest.java
```

So the ones that have been failing in this PR are passing.

**Comment by cristianonicolai** [comment]
Ok, so it keeps failing with unrelated/random test errors. I tested it locally and it seems to be all working fine. Consirering that changes are minimal, I'm happy to approve and merge.

**Pull request merged**
