### PR TITLE
AF-1040: Changes in the Project Settings are lost when switching to another tab

### PR DESCRIPTION
**Pull request by tiagobento**
See https://issues.jboss.org/browse/AF-1040

### CODE REVIEW

**Comment by tiagobento** [comment]
Jenkins, please retest this.

**Comment by tiagobento** [comment]
Jenkins, please retest this.

**Comment by tiagobento** [comment]
@paulovmr Could you take a look?

**Comment by tiagobento** [comment]
@jhrcek @tomasdavidorg Could one of you take a look as well?

**Comment by jhrcek** [comment]
@tiagobento sure. This one needs some local testing. 
Jenkins execute full downstream build

**Comment by tiagobento** [comment]
Thanks @jhrcek!

Jenkins execute full downstream build

**Comment by tiagobento** [comment]
Jenkins execute full downstream build

**Comment by tiagobento** [comment]
Jenkins execute full downstream build

**Comment by tiagobento** [comment]
Jenkins please execute full downstream build

**Comment by tiagobento** [comment]
Jenkins please execute full downstream build

**Pull request merged**
