### PR TITLE
RHPAM-2728 Not possible to migrate process containing multiple instance sub-process

### PR DESCRIPTION
**Pull request by hasys**
7.33.x cherry-pick of https://github.com/kiegroup/kie-wb-common/pull/3185

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Not sure why, but regular build was aborted

<details>
  <summary>Log</summary>
  <pre>01:16:34 [INFO] ------------------------------------------------------------------------
01:16:46 Skipping publisher since build result is ABORTED
01:16:46 Skipping publisher since build result is ABORTED
01:16:46 Archiving artifacts
01:16:50 Adding one-line test results to commit status...
01:16:50 Setting status of 820ae818e9f80a5ab68a6ba9237cd4db059478ea to FAILURE with url https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/7.33.x/job/pullrequest/job/kie-wb-common-pullrequests-7.33.x/4/ and message: 'Build finished. 14744 tests run, 33 skipped, 0 failed.'
01:16:50 Using context: Linux
01:16:51 No emails were triggered.
01:16:51 [WS-CLEANUP] Deleting project workspace...
01:16:51 [WS-CLEANUP] Deferred wipeout is used...
01:16:51 [WS-CLEANUP] done
01:16:51 Finished: ABORTED
</pre>
</details>

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Hi @LuboTerifaj, @romartin,

looks like regular build failing due to 2h timeout. @mbiarnes can we increase it?
But on master it is green, and also I tried to build -Dfull locally and all works.

I tested locally on standalone and kogito showcases in both cases I was able to load provided diagram without any issues.

I think this PR is ready for review. Thank you!

**Comment by hasys** [comment]
Hi @romartin, your turn and it is ready to go. Thank you!

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Pull request merged**
