### PR TITLE
JBPM-9432: Users and Groups reversed for Reassignment property

### PR DESCRIPTION
**Pull request by hasys**
**JIRA**: [JBPM-9432](https://issues.redhat.com/browse/JBPM-9432)

**Business Central**: [WAR file](https://drive.google.com/file/d/1OAc5b5NH4W3re5MUDhADsv7nu612ZYI1/view?usp=sharing)

**VS Code**: [plugin](https://drive.google.com/file/d/1pdEBMzPv52dVcg48jUzV2pVti0aY2Fau/view?usp=sharing)

<details>
<summary>
Hi @romartin, there is a fix for JBPM-9432, I tested showcase and full downstream build (I uploaded it to drive as well, see link above) and I also tested and uploaded a VS code plugin and all works good now as well.

All important checks are green, PR is ready for review. Thank you!

@LuboTerifaj, @domhanak tester is not set, but I am not sure what is the procedure now, so I will add you both to the PR. Thank you!

How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by hasys** [comment]
jenkins do fdb

**Review by romartin — APPROVED** [review]
Nice, thanks @hasys !

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @hasys ,

I have found one issue, but it is present also on master:

- [KOGITO-3693](https://issues.redhat.com/browse/KOGITO-3693) Users and groups are displayed twice in Reassignments

Otherwise I didn't find any issues.

However there are no test cases added.
Can you please add them?

Thank you!

**Comment by hasys** [comment]
Hi @LuboTerifaj, thank you great catch KOGITO-3693.

About tests, it had tests and tests also had the same typo. All fixed now.

Anyway I don't think we should write Setters/Getters test at all in form of Unit tests, as you can see from this issue it just doesn't work any way and typo from code duplicates to the tests.

**Comment by romartin** [comment]
hey @hasys @LuboTerifaj 
This issue is quite critical, so I'm agree on going ahead with the commit as it is, given the test case implementation requires for some extra effort as it's a declarative syntax issue.

**Review by LuboTerifaj — APPROVED** [review]
After the discussion on gchat and in the meeting, I think we can merge this. Thanks!

**Pull request merged**
