### PR TITLE
DROOLS-2335: Increase coverage of delete context entry command

### PR DESCRIPTION
**Pull request by jomarko**
@manstis please have a look.

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
Fail: `org.kie.workbench.common.services.backend.compiler.plugin.KieMetadataTest.compileAndLoadKieJarMetadataAllResourcesPackagedJar`

jenkins please retest this

**Comment by manstis** [comment]
@jomarko Unfortunately we are waiting for @mariofusco or @lanceleverich or @porcelli or @ederign to fix a ```drools-core``` issue that leads to the failing test. There was talk of disabling the test yesterday but the strongest opinion was to have the issue fixed... so until then... all PRs fail :-(

**Comment by porcelli** [comment]
jenkins please retest this

**Pull request merged**
