### PR TITLE
JBPM-6723: Stunner - Add BPMN Ad-Hoc Subprocess

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin @hasys @jsoltes , would you mind review this PR?
Thanks.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Index test fails in another project, can be ignore for this PR.

Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @wmedvede,

process name is overlap children:


I guess it is general issue for all containers, but it looks like it is the only one with centered name and that's why it was found only now.

**Comment by romartin** [comment]
I'm agree as well @wmedvede , probably just changing the name to the BOTTOM position for now works, it's what is being done in the other containers.

**Comment by wmedvede** [comment]
Hi @romartin , @hasys , yes I believe it's something that affects containers in general.
This is how it looks when the text is placed in the BOTTOM position.

image

Is there @romartin any padding or trick that can be done for making the text to be "painted" a bit upper the icon? or do you prefer I open a ticket for this?

**Comment by romartin** [comment]
oh @wmedvede yes I see... the text overlaps the icon :( mmm actually there is still not much to do here, as we're still working on the shape layouts task, so until not completed we'll be not able to apply some paddings, margins etc.
So as a quick solution what do you think @hasys @wmedvede about for this kind of subprocess setting the text on  `TOP`? I know it's not the ideal but actually we cannot place it neither on `BOTTOM`, as there is the icon, neither on the `CENTER`, as it would overlap the child shapes.

**Comment by wmedvede** [comment]
agreed, @romartin @hasys , the subprocess name was moved to the TOP.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
@hasys Hmmmm, yes, this might be a sort of "wordwrap" that can be probably configured/programmed at some point in the linezo/stunner api. But I don't now exactly. But yes, we'll have to open a JIRA for this. 
Thanks

**Comment by romartin** [comment]
Hey @hasys 
Yeah great findings! I think we have all these bugs under control:
- For 1) and 2) - There were some bugs about this and there exist an old PR for it, that will take a look before the GA https://github.com/kiegroup/kie-wb-common/pull/1216
- For 3) - This is supposed to be fixed once merging the [JBPM-6735](https://issues.jboss.org/browse/JBPM-6735) (see the ticket description, I would say it fixes exactly your issue...)

**Pull request merged**
