### PR TITLE
JBPM-8548 Stunner - Issue with ServiceTaks migrating from jBPM Designer to Stunner

### PR DESCRIPTION
**Pull request by tiagodolphine**
Fix issue with service tasks marshaling containing a `null` body/value on the data assignments.
To test it can be generated any diagram **jBPM designer** with service tasks export the `bpmn` and import as a new asset on Stunner.

@wmedvede
@hasys 
@romartin

### CODE REVIEW

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
please @wmedvede @hasys quick review here when possible.... thanks!

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
I pushed a new fix for it, I tested locally building the `jbpm-wb`.
@romartin @LuboTerifaj

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
@romartin all green

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj thanks for the review, I opened a JIRA on Friday to the issue you mentioned I got while testing as well, take a look https://issues.jboss.org/browse/JBPM-8558 feel free to add more details on the description.
Thanks.

**Pull request merged**
