### PR TITLE
DROOLS-3151: [DMN Designer] Decision Table: Improve contrast of Input- and OutputClause columns

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-3151

### CODE REVIEW

**Comment by jomarko** [comment]
@manstis code looks good to me and I see related appformer one is already merged, I think if you post screenshots of GDT, DMN and SceSim I will approve without manual testing.

**Comment by manstis** [comment]
@jomarko Yep... I was just in the process of doing that :-)

@jomarko @gitgabrio said he'll do scesim tomorrow.

**Comment by manstis** [comment]
drools-3151-dmn

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
