### PR TITLE
latest Zanata translation changes in kie-wb-common from 2018-05-11

### PR DESCRIPTION
**Pull request by kiereleaseuser**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
@manstis: these tests https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-common-pullrequests-7.5.x/lastCompletedBuild/testReport/ are failing in this PR

**Comment by manstis** [comment]
@mbiarnes The failures may be transient (```org.uberfire.java.nio.IOException: java.io.IOException: Failed to open server socket for /127.0.0.1:9418```) or (if they are constantly failing) may be environmental (wasn't there changes to the CI system recently?)

**Comment by mbiarnes** [comment]
these test fail also in the normal build

**Pull request merged**
