### PR TITLE
Layout editor enhancements

### PR DESCRIPTION
**Pull request by dgutierr**
Changes required by https://github.com/kiegroup/appformer/pull/101

@pefernan Can you review it please?

### CODE REVIEW

**Comment by dgutierr** [comment]
@pefernan Fixed the CSS you suggested.

I investigaded the "DOMException: WRONG_DOCUMENT_ERR". It's not related to this PR. It happens in the latest appformer version. @kkufova Can you verify whether this happens in the latest kie-wb. If so can you open a JIRA?  

@pefernan I'd say this PR is ready for approval. wdyt?

**Comment by kkufova** [comment]
@dgutierr, I checked the latest snapshot (`kie-wb-7.5.0-20171204.191641-294-eap7`) and no exception appears when adding an HTML component.

**Comment by kkufova** [comment]
@dgutierr, @pefernan, I can confirm that the exception appears in the latest snapshot as well (`kie-wb-7.5.0-20171204.191641-294-eap7`), which means that the problem is not related to this PR.

**Comment by ederign** [comment]
jenkins retest this

**Pull request merged**
