### PR TITLE
JBPM-6035: Show added constants only for current row in DataIOEditor

### PR DESCRIPTION
**Pull request by jlindop**
This Jira and PR were created because the same problem was recently fixed in Designer.
@romartin  , @hasys  Will you review please. Today is my last day, so if it needs changes will one of you make the necessary changes. (Hopefully none will be needed!). Thanks.

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Pull request merged**
