### PR TITLE
DROOLS-6268 : Fix for GRE in

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**:  

[DROOLS-6268](https://issues.redhat.com/browse/DROOLS-6268)

**referenced Pull Requests**: 

* https://github.com/kiegroup/kie-soup/pull/193
* https://github.com/kiegroup/drools/pull/3524
* https://github.com/kiegroup/kie-wb-common/pull/3619
* https://github.com/kiegroup/drools-wb/pull/1481

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Review by jomarko — COMMENTED** [review]
same question as in 7.52.x one

**Comment by Rikkola** [comment]
@jomarko updated this too

**Review by jomarko — APPROVED** [review]
Thank you @Rikkola

**Review by karreiro — APPROVED** [review]
Thank you, @Rikkola!

**Pull request merged**
