### PR TITLE
[7.3.x] GUVNOR-3394: [DMN Editor] Literal Expression: Line breaks for multiple line expressions

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-3394

This is the corollary of https://github.com/kiegroup/kie-wb-common/pull/1074 for 7.3.x.

(cherry picked from commit ed62be08a4488b0a4f469b35918ce6e0292d35aa)

Please note 7.3.x does not have the DMN Editor and hence the changes here are only for Stunner.

### CODE REVIEW

**Comment by manstis** [comment]
Part of an ensemble:-

- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/565
- https://github.com/AppFormer/uberfire/pull/852
- https://github.com/kiegroup/kie-wb-common/pull/1199

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
@hasys Just need your approval to this cherry-pick please.

**Comment by romartin** [comment]
@hasys yeah please, this one is important! Thanks!

**Pull request merged**
