### PR TITLE
[KOGITO-3426] - [DMN Designer] Creating a node using toolbox causes error

### PR DESCRIPTION
**Pull request by danielzhe**
This PR address two issues:
**JIRA**: [DROOLS-5667](https://issues.redhat.com/browse/DROOLS-5667)
**JIRA**: [KOGITO-3426](https://issues.redhat.com/browse/KOGITO-3426)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by danielzhe** [comment]
jenkins do fdb

**Review by karreiro — APPROVED** [review]
Excellent work, @danielzhe. Thank you!

**Comment by jstastny-cz** [comment]
```
[2020-09-23T22:48:21.000Z] [INFO] There is 1 error reported by Checkstyle 8.19 with /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-master.pullrequests/kie-wb-common-dmn/kie-wb-common-dmn-client/target/checkstyle-rules.xml ruleset.
[2020-09-23T22:48:21.000Z] [ERROR] src/main/java/org/kie/workbench/common/dmn/client/canvas/controls/builder/ObserverBuilderControl.java:[31,8] (imports) UnusedImports: Unused import - org.kie.workbench.common.dmn.api.definition.model.DRGElement.
```

**Comment by danielzhe** [comment]
Thank you, @jstastny-cz . Codestyle fixed.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by jstastny-cz** [comment]
Verified BC, VSCode pending.

**Review by jstastny-cz — APPROVED** [review]
LGTM, thanks

**Comment by karreiro** [comment]
Jenkins retest this.

**Pull request merged**
