### PR TITLE
AF-2824: Added some checks to prevent invalid values

### PR DESCRIPTION
**Pull request by adrielparedes**
**JIRA**: [AF-2824](https://issues.redhat.com/browse/AF-2824)

There was a problem when an old project does not contain that attribute set: [AF-2693](https://issues.redhat.com/browse/AF-2693)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by adrielparedes** [comment]
jenkins retest this

**Review by paulovmr — APPROVED** [review]

**Review by akumar074 — APPROVED** [review]
Thanks for the PR @adrielparedes

**Comment by tomasdavidorg** [comment]
Error when building kie-wb-distrribution:
```
[INFO] --- gwt-maven-plugin:2.9.0:compile (gwt-compile) @ business-monitoring-webapp ---
[INFO] Compiling module org.kie.bc.FastCompiledKIEWebapp
[INFO]    Tracing compile failure path for type 'org.kie.workbench.common.screens.library.api.preferences.LibraryProjectPreferences'
[INFO]       [ERROR] Errors in 'jar:file:/home/tdavid/.m2/repository/org/kie/workbench/screens/kie-wb-common-library-api/7.54.0-SNAPSHOT/kie-wb-common-library-api-7.54.0-SNAPSHOT-sources.jar!/org/kie/workbench/common/screens/library/api/preferences/LibraryProjectPreferences.java'
[INFO]          [ERROR] Line 65: The method getInteger(String, int) is undefined for the type Integer
[INFO]    [ERROR] Aborting compile due to errors in some input files
[INFO] [ERROR]
```

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by tomasdavidorg** [comment]
@adrielparedes I still see the gwt compilation issue. Are you able to build the kie-wb-distribution project?

**Comment by adrielparedes** [comment]
jenkins run fdb

**Review by tomasdavidorg — APPROVED** [review]
Tested. Looks good to me. Thanks 🙂

**Pull request merged**
