### PR TITLE
JBPM-7433: Stunner - New Marshaller: Process ID is not sanitized upon marshalling

### PR DESCRIPTION
**Pull request by evacchi**
fixes the two issues reported by @LuboTerifaj and @hasys 

@romartin

### CODE REVIEW

**Comment by evacchi** [comment]
jenkins please execute full downstream build

**Comment by evacchi** [comment]
I am splitting these issues

jenkins please execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by evacchi** [comment]
@hasys right now I'm just doing **exactly** what the old marshallers do. I think input sanitization should be handled at a higher level :)

**Comment by hasys** [comment]
Ok, thank you, sounds good for now, but before close Jira issue I guess will be good to consider points I mentioned above.
Jenkins execute full downstream build

**Comment by evacchi** [comment]
I have reported a separate jira about sanitization and default handling

**Comment by hasys** [comment]
@evacchi do you have links to keep it here for the record?

**Comment by evacchi** [comment]
@hasys https://issues.jboss.org/browse/JBPM-7431

**Comment by romartin** [comment]
what's the status for this guys? can be merged? thanks!

**Comment by evacchi** [comment]
To me, yes

**Comment by evacchi** [comment]
see #1725

**Pull request closed without merging**
