### PR TITLE
DROOLS-5053: Remove unused dependencies of kie-wb-common-server-ui-cl…

### PR DESCRIPTION
**Pull request by jomarko**
…ient module

For more details see https://issues.redhat.com/browse/DROOLS-5053

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Why only you do clean up of deps, @jomarko ? ;) I would expect that people who will change something in the code and this is projected into not needed dependency will do it in related PR.
Or if we do PR review we should probably check that there and to not bring new dependency which is not needed.
I get only if this is cleaning procedure for very long existing dependency. WDYT?

**Comment by mareknovotny** [comment]
There is 
`java.lang.ClassCastException: org.kie.dmn.feel.lang.impl.MapBackedType cannot be cast to org.kie.dmn.feel.lang.types.GenListType`
in all failed tests in kie-wb-common screens module tests

**Comment by mareknovotny** [comment]
ok, noticed there is fising PR https://github.com/kiegroup/drools/pull/2765 for this issue

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@mareknovotny is green now

**Pull request merged**
