### PR TITLE
KOGITO-560: Remove empty header from Kogito editors

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
@manstis Thanks for the review. I fixed the `-webapp-kogito-testing` and the DMN test. About the other gap, it is a different issue than the perspective panel, and does not happen in our iframes (vscode, github extensions, online-editor). In any case, I created a [different JIRA](https://issues.jboss.org/browse/KOGITO-570) to handle this, with less priority.

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
@romartin you may want to check BPMN (but I suspect it'll be fine).

**Pull request merged**
