### PR TITLE
[7.7.x] JPBMP 7384: Stunner - Add setting for enable/disable HiDPI

### PR DESCRIPTION
**Pull request by romartin**
(cherry picked from commit 764953881bc22d9535fc956396c75ddbeaf59fa2)
See https://issues.jboss.org/browse/RHPAM-1343
Depends on
* https://github.com/kiegroup/lienzo-core/pull/53
* https://github.com/kiegroup/lienzo-tests/pull/35

### CODE REVIEW

**Comment by romartin** [comment]
Hey @tiagodolphine 
Please can you review/approve this? Would like to include it for next 7.0.2... thnaks!

**Comment by tiagodolphine** [comment]
@romartin ok I'll do a manual test now if ok I'll approve.

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Also tested from the UI and it works.

**Pull request merged**
