### PR TITLE
RHPAM-754 Docking issues (cherry-pick JBPM-6178 to 7.7.x)

### PR DESCRIPTION
**Pull request by tiagodolphine**
Cherry pick commit 06b7fc202be44e2f392917ee7e0e9068ace1b9ec
Depends on https://github.com/kiegroup/lienzo-core/pull/15 to be merged
@romartin 
@LuboTerifaj

### CODE REVIEW

**Comment by tiagodolphine** [comment]
Jenkins retest this

**Comment by romartin** [comment]
Hey @tiagodolphine , does this PR depends on the lienzo one right? If so, please remember to add the dependencies to other PRs in the ticket's description... so whoever will merge will realize about it and we'll not broke the master build, otherwise forget my comments (as usually) :P

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
hey @romartin you are right, this PR depends on lienzo, I've updated the description.
Thanks.

**Comment by krisv** [comment]
@tiagodolphine @romartin can we try to get this PR merged before the end of this week?

**Pull request merged**
