### PR TITLE
RHPAM-3008: Change Service Tasks label in process modeler to Custom Tasks

### PR DESCRIPTION
**Pull request by handreyrc**
Hey @romartin: Please, could you review this PR?
Related PRs:
https://github.com/kiegroup/jbpm-wb/pull/1444

### CODE REVIEW

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Here goes the link to the artifacts for testing it:
https://drive.google.com/file/d/1dX6u7fTYp5PSbJpkqcNpzjZE8VQs4zX6/view?usp=sharing
Thanks

**Comment by romartin** [comment]
Please @handreyrc lemme know once builds are ok and so it's ready to merge. Thx!

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @handreyrc , can you please rebase this again and fire the CI builds? hopefully, if buidls are ok, I'll be able to merge. Thanks!

**Comment by handreyrc** [comment]
Jenkins execute compile downstream build

**Pull request merged**
