### PR TITLE
[7.30.x] RHPAM-2549: Stunner - User task throws exception when you try to move it.

### PR DESCRIPTION
**Pull request by romartin**
Hey @LuboTerifaj 

This is the cherry-pick for https://github.com/kiegroup/kie-wb-common/pull/3078 into `7.30.x` branch. 

See [RHPAM-2549](https://issues.redhat.com/browse/RHPAM-2549)

Please, notice this is a **BLOCKER issue** and it's urgent trying to have this merged tomorrow.

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
Ho Ho Ho... I hope Santa brings your wish.

**Comment by romartin** [comment]
@LuboTerifaj @hasys added more test cases to cover all sonarcloud checks.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
PS: Test failue on the [full build report](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/7.30.x/job/pullrequest/job/kie-wb-common-downstream-pullrequests-7.30.x/12/) is **NOT related**to this work

**Comment by mbiarnes** [comment]
@romartin @LuboTerifaj @hasys PLeaqse look at the failed test:
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/7.30.x/job/pullrequest/job/kie-wb-common-downstream-pullrequests-7.30.x/12/testReport/

**Comment by hasys** [comment]
Hi @mbiarnes, it is known random fail, see comment from @jesuino https://github.com/kiegroup/kie-wb-common/pull/3037#issuecomment-561825263 for more details.

**Comment by romartin** [comment]
ok @LuboTerifaj thanks, plz waiting for your approval to merge

**Comment by LuboTerifaj** [comment]
As I already promised in [comment](https://github.com/kiegroup/kie-wb-common/pull/3085#pullrequestreview-334534719), I've reported the issue under one, since all the issues have probably the same root cause: https://issues.redhat.com/browse/JBPM-8962

**Pull request merged**
