### PR TITLE
RHPAM-3134 : UI issue (in business-central) when more than one kie-server (with different ID) is connected

### PR DESCRIPTION
**Pull request by akumar074**
- Added ContainerSpec check
 - clean up

**JIRA**:  [RHPAM-3134](https://issues.redhat.com/browse/RHPAM-3134)

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Review by paulovmr — APPROVED** [review]

**Review by tomasdavidorg — CHANGES_REQUESTED** [review]
Hi @akumar074 

I tried the reproducer but I still can see an error dialog 
image

error in the dialog:
```
Uncaught exception: CDI Event exception: CommandType=CDIEvent, BeanType=org.kie.server.controller.api.model.events.ServerInstanceUpdated, ToSubject=cdi.event:org.kie.server.controller.api.model.events.ServerInstanceUpdated, BeanReference=ServerInstanceUpdated{serverInstance=ServerInstanceKey{serverInstanceId='sboot2@localhost:8095', serverName='sboot2@localhost:8095', serverTemplateId='sboot2', url='http://localhost:8095/rest/server'}} sent to [unavailable] Caused by: (TypeError) : Cannot read property 'j' of undefined
```

and there is this error in the log:
```
19:03:45,576 ERROR [org.kie.workbench.common.services.backend.logger.GenericErrorLoggerServiceImpl] (default task-4) Error from user: krisv Error ID: 1947060446 Location: ServerManagementPerspective|ServerManagementBrowser Exception: Uncaught exception: CDI Event exception: CommandType=CDIEvent, BeanType=org.kie.server.controller.api.model.events.ServerInstanceUpdated, ToSubject=cdi.event:org.kie.server.controller.api.model.events.ServerInstanceUpdated, BeanReference=ServerInstanceUpdated{serverInstance=ServerInstanceKey{serverInstanceId='sboot2@localhost:8095', serverName='sboot2@localhost:8095', serverTemplateId='sboot2', url='http://localhost:8095/rest/server'}} sent to [unavailable] Caused by: (TypeError) : Cannot read property 'j' of undefined
```

**Pull request merged**
