### PR TITLE
Revert "RHPAM-4387 xml-apis:xml-apis excluded (#3742)"

### PR DESCRIPTION
**Pull request by Ginxo**
This reverts commit 0237c63fd6d086d38f06752223435d78b04777b2.

Since https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2023 is merged ban-duplicated classes rule will not fail

**Thank you for submitting this pull request**

**JIRA**:https://issues.redhat.com/browse/RHPAM-4455

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* https://github.com/kiegroup/kie-wb-common/pull/3772
* https://github.com/kiegroup/jbpm-wb/pull/1568
* https://github.com/kiegroup/drools-wb/pull/1553
* https://github.com/kiegroup/kie-wb-distributions/pull/1188

**Business Central**: [WAR file](https://donwnload.here/something)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Review by lampajr — APPROVED** [review]
LGTM

**Comment by mareknovotny** [comment]
jenkins do fdb

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
please run also FDB for jdk8 from this PR level

**Comment by Ginxo** [comment]
JDK8 also triggered https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/fdb/job/kie-wb-common-main.fdb/97/

**Pull request merged**
