### PR TITLE
[RHBA-565]: Copied asset is open after ResourceCopiedEvent is observed

### PR DESCRIPTION
**Pull request by adrielparedes**
@barboras7 would you mind to review it please?

### CODE REVIEW

**Comment by barboras7** [comment]
Jenkins execute full downstream build

**Comment by barboras7** [comment]
Thanks @adrielparedes, I checked locally and the issue is fixed :+1:

**Comment by adrielparedes** [comment]
Jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins retest please

**Pull request merged**
