### PR TITLE
JBPM-5908: Stunner - SVG code generation issues with floating points for different locales.

### PR DESCRIPTION
**Pull request by romartin**
Hey @manstis @hasys 

This is a fix for an issue found by @paulovmr when trying to build the repository (using non European  locale). This is the [JIRA ticket](https://issues.jboss.org/browse/JBPM-5908) for it. Can you please take a look?

Thanks!

### CODE REVIEW

**Comment by manstis** [comment]
@hasys Please advise when you're happy for this to be merged.

**Comment by romartin** [comment]
oh @hasys good point! In fact I was trying to make the tests run in different locales for ensuring this bug  is not happening any more, but I was not able to do it... not sure why yet :( I was trying to do `Locale.setDefault` before running the test cases, but was that not successfull.  So the goal should be to run the tests in different languages and ensure same source files are generated...Any ideas how to do this @manstis @hasys ? Thanks in advance!

**Comment by romartin** [comment]
FYI - @manstis @hasys sorry guys, finally the `Locale.setDefault` is working on testing scope as well, so will use it for adding a test for this. Thanks!

**Comment by romartin** [comment]
@manstis @hasys Thanks for the feeback! There were missing two places to apply the fix as well, so well seen too @hasys thx!
I have added, in addition to the execution of all test cases, 3 test suite classes that run the test cases targeted for code generation in 3 different languages as well.
Thanks!

**Comment by manstis** [comment]
@hasys Please let me know when you're happy for this to be merged.

**Pull request merged**
