### PR TITLE
JBPM-7894: fix BpmnFileIndexerTest

### PR DESCRIPTION
**Pull request by xiezhang7**

### CODE REVIEW

**Comment by xiezhang7** [comment]
Hi @romartin @hasys @LuboTerifaj , this is to fix the test failure reported in [PR#2291](https://github.com/kiegroup/kie-wb-common/pull/2291#issuecomment-444474501) . Thanks.

**Comment by hasys** [comment]
Jenkins retest please

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by romartin** [comment]
ok to test

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Pull request merged**
