### PR TITLE
RHPAM-2759: Stunner - Service task Thumbnails are huge in Documentation

### PR DESCRIPTION
**Pull request by Josephblt**
This is just a cherry pick from this PR https://github.com/kiegroup/kie-wb-common/pull/3568

**JIRA**: [RHPAM-2759](https://issues.redhat.com/browse/RHPAM-2759)

**Business Central**: [WAR file](https://drive.google.com/file/d/1Z0PxXnMgP1gqV_W_1_ShnQKwT3zLiAcg/view?usp=sharing)

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by Josephblt** [comment]
Hello @romartin, @LuboTerifaj. If you guys could review/assign reviewers for this that would be great. Thanks.

**Comment by romartin** [comment]
Hey @LuboTerifaj 
Could you please check this cherry-pick? Deadline is tomorrow, would appreciate early review.
Thanks!

**Review by romartin — APPROVED** [review]

**Review by LuboTerifaj — APPROVED** [review]
It looks good to me. Thanks!

**Pull request merged**
