### PR TITLE
[BXMSPROD-1700] lock-treatment-tool version property

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-1700

- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2111
- https://github.com/kiegroup/appformer/pull/1322
- https://github.com/kiegroup/kie-wb-common/pull/3787
- https://github.com/kiegroup/process-migration-service/pull/84
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/781
- https://github.com/kiegroup/optaweb-employee-rostering/pull/860

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
Jenkins retest this

**Review by lampajr — APPROVED** [review]

**Comment by Ginxo** [comment]
Jenkins retest this

**Pull request merged**
