### PR TITLE
DROOLS-5075: Clear properties panel for top level output header cell

### PR DESCRIPTION
**Pull request by jomarko**
For more details see https://issues.redhat.com/browse/DROOLS-5075

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
Let me test this JIRA with a fix I'm making for [DROOLS-5060](https://issues.redhat.com/browse/DROOLS-5060).

I spotted similar behaviour when manually testing my changes and it was caused by the Properties Panel not refreshing itself because it thought its _state_ had not changed when selecting `DomainObjects` (i.e. `InputClause` and `OutputClause` columns)...

https://github.com/manstis/kie-wb-common/commit/58ccef00c5a2708d666e60c899497754d5e626cb#diff-f1dd890711635087509e2f37fd9fe0a4R273

I am writing some more tests for DROOLS-5060 then will submit a PR.

**Comment by manstis** [comment]
@jomarko I've tested my fix for DROOLS-5060 and it also resolves DROOLS-5075.

Unfortunately your fix here is not correct (but does work around the _stale state_ in the Properties Panel). When you click on a `InputClause` header the Properties Panel should show the properties for the Input Column. When you then click on the "top level" `OutputClause` header the Properties Panel should show the properties for the Decision. When you click on a sub-level `OutputClause` header the Properties Panel should show the properties for the Output Column.

**Comment by jomarko** [comment]
Closing in favor of https://github.com/manstis/kie-wb-common/commit/58ccef00c5a2708d666e60c899497754d5e626cb#diff-f1dd890711635087509e2f37fd9fe0a4R273

**Comment by jomarko** [comment]
@manstis sorry for wasting your time I linked DROOLS-5060 and RHDM-1247

**Pull request closed without merging**
