### PR TITLE
DROOLS-3175: Move getRelativeX/Y to single place

### PR DESCRIPTION
**Pull request by jomarko**
@manstis  would you mind to review? This is just some refactoring before real changes.

Ensemble with:
- https://github.com/kiegroup/appformer/pull/566
- https://github.com/kiegroup/drools-wb/pull/1019

### CODE REVIEW

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @jomarko  once the full build is success lemme know and I'll merge. Thanks!

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
@jomarko Did you want full downstream green before merge?

**Comment by jomarko** [comment]
@manstis yes, @romartin asked me for it so trying to get all green. Will let know when ready for merge.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Pull request merged**
