### PR TITLE
JBPM-5542: Stunner - Properties Panel and Process Explorer are shown for incorrect asset

### PR DESCRIPTION
**Pull request by pefernan**
@wmedvede @romartin since both of you are affected by this change could you please take a look?

@romartin btw the it seems that the SessionPausedEvent is never fired, the docks handler for stunner is listening for it to close the docks.

Comment: merge with https://github.com/AppFormer/uberfire/pull/670

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins retest this.

**Comment by romartin** [comment]
hey @pefernan , the code is not compiling neither for me locally neither on Jenkins, please can you take a look?

**Comment by pefernan** [comment]
@romartin fixed I forgot to commit one file ...

**Comment by romartin** [comment]
hey @pefernan , now it does compiles but no docks appear anymore on the stunner showcase :( Neither creating a new diagram neither opening a new one... So I have not tested neither kie-wb as we should first fix the stunner showcase.

**Comment by wmedvede** [comment]
Hi @pefernan @romartin let me know guys when this is fixed so I can do the data modeler side tests.

Thanks!

**Comment by pefernan** [comment]
@romartin can you take a look again??

**Comment by romartin** [comment]
hey @pefernan , the bug is not a blocker, but I would suggest to fix it in 7.0.x as well - just my opinion, feel free to ask @krisv / @etirelli  if you think so. Thanks!

**Comment by krisv** [comment]
+1, I already tagged the JIRA with 7.0.0.Final fixVersion

**Comment by wmedvede** [comment]
Hello @pefernan, I've tested it locally and seems like there's still a small issue. 
When a process file is opened, or a data object is opened, or when we switch form the editor tab to the source tab, and back to the editor tab, the dock with the explorer is collapsed. 
See the following video: https://youtu.be/GJcsCOV7oaw

**Comment by pefernan** [comment]
@wmedvede fixed the error you said. Check https://github.com/AppFormer/uberfire/pull/670

**Comment by wmedvede** [comment]
@pefernan ok, I'll re-test when https://github.com/AppFormer/uberfire/pull/670 is merged.

**Comment by manstis** [comment]
@pefernan The referenced Uberfire PR has been closed without merge.. what happens to this PR now?!

**Pull request closed without merging**
