### PR TITLE
[7.7.x] RHPAM-1268: Stunner - Clear diagram action is not working

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin @hasys , would you mind review this PR?
Please try to prioritize review/test so we can have this for the 7.0.2,
Thanks!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@hasys please let's try to see if we can review/merge thsi for next 7.0.2... would be a nice fix to include! thanks in advance!

**Comment by wmedvede** [comment]
Hi @hasys given that to get two green is like to win the lottery, so I'd suggest to just use the downstream results to test and move ahead in case there are no other reviews.
Thanks

**Pull request merged**
