### PR TITLE
AF-2673 [OpenShift] New Asset Package dropdown does not show packages

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**: [AF-2673](https://issues.redhat.com/browse/AF-2673)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
jenkins do fdb

**Comment by ederign** [comment]
Please, only merge this after @tomasdavidorg  and @adrielparedes approval.

**Comment by Rikkola** [comment]
Green FDB with my first try! Can't remember if that has ever happened before.

**Review by adrielparedes — APPROVED** [review]

**Review by tomasdavidorg — APPROVED** [review]
Tested locally. Thanks @Rikkola :slightly_smiling_face:

**Comment by mareknovotny** [comment]
@tomasdavidorg  @adrielparedes thanks for quick review, may I ask you if the same applies to backported PR too ? #3460

**Pull request merged**
