### PR TITLE
DROOLS-3248: [DMN Designer] QName: Default to be 'Any' not 'string'

### PR DESCRIPTION
**Pull request by danielzhe**
DROOLS-3248: [DMN Designer] QName: Default to be 'Any' not 'string'

### CODE REVIEW

**Comment by manstis** [comment]
@danielzhe It's probably _good practice_ to run `mvn clean install -Dgwt.compiler.skip=true` before submitting PRs to check all tests pass... and even `mvn clean install` (both on the root of `kie-wb-common-dmn`).

**Comment by manstis** [comment]
@jomarko well that's unexpected!

@tarilabs @etirelli does your compiler need changes? I'd have thought changing the default typeRef used in the Workbench from one built in type to another would work flaelessly.

**Comment by danielzhe** [comment]
@manstis My bad. I did it, but not in the root. I'm fixing the test.

**Comment by danielzhe** [comment]
Jenkins please retest this

**Comment by manstis** [comment]
@tarilabs @etirelli bump.. 

Strange the compiler complains about use of built in type "Any" and  Not "any".

**Comment by tarilabs** [comment]
> Strange the compiler complains about use of built in type "Any" and Not "any".

Can I have please the DMN model file exhibiting this issue, or a line of code reference, please?
So I check exactly the error message, and if any bug.
Thanks!

**Comment by danielzhe** [comment]
@tarilabs I'll send you one example to e-mail. Notice that in this PR we're changing the "any" to "Any", so maybe there is something more we need to do in order for this works.

**Comment by manstis** [comment]
@tarilabs I found a DMN file with either `Any` or `any` gives the error reported by @jomarko 

I'm attaching three files (all the same other than the typeRef; `any`, `Any` and `string`). 

Only `string` compiles.

[DROOLS-3248.zip](https://github.com/kiegroup/kie-wb-common/files/2558987/DROOLS-3248.zip)

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
