### PR TITLE
JBPM-8794: Stunner - some end events have incorrect icons.

### PR DESCRIPTION
**Pull request by romartin**
Hey @hasys 

See [JBPM-8794](https://issues.jboss.org/browse/JBPM-8794)

PS: Once merged, will also include this fix into the RHPAM 7.5.1 branch ( see [RHPAM-2413](https://issues.jboss.org/browse/RHPAM-2413) )

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Hey @hasys , good catch!! just updated and rebased again, thx!!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
great, thanks a lot @hasys for collaborating on the fixes too, really appreciated!!! 
Just pushed the fix from your [last comment](https://github.com/kiegroup/kie-wb-common/pull/2926#issuecomment-540494954) and rebased again. 
Let's see how J works now...

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @hasys , although full build failed on some unrelated tests, the artifacts were properly generated, so feel free to test it again, thanks!

**Comment by hasys** [comment]
Hi @romartin,

now it looks and works great. Thank you!

**Comment by romartin** [comment]
can you @hasys plz approve?

**Pull request merged**
