### PR TITLE
JBPM-7450: Stunner - Connectors' bendpoints - Bug fixings & improvements

### PR DESCRIPTION
**Pull request by romartin**
Hey @hasys  @tiagodolphine 

This is the continuation of https://github.com/kiegroup/kie-wb-common/pull/2000 but targeting now `master` branch.

See https://issues.jboss.org/browse/JBPM-7450

I've squashed all work from the PR referenced above and rebased with master, so it includes all comments, code improvements and bug fixes you previously found as well.

So rather than adding more unit tests on the lienzo side, it should be everying ok.

It **depends on**
https://github.com/kiegroup/lienzo-core/pull/56
https://github.com/kiegroup/lienzo-tests/pull/38

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin,

great work, looks very solid in all browsers now!

just one issue found:
image
When I moving around `second` lane all bendpoints are attached to it and move together with lane. When I move `first` lane all bendpoints are attached to Process itself and doesn't move with lane.

Question: on Tiago's videos with fixed bugs I can see that bendpoint outside of subprocess is moving together with subprocess. Is it also expected? I tried it on this PR and it is still valid. CC @wrnkld 

P.S. I guess it's better to finish tests for this PR and report remaining issue as separate Jira. WDYT?

**Comment by wrnkld** [comment]
@hasys Yes, I would expect bend points to move with the lane.

**Comment by hasys** [comment]
Ok, thank you @romartin, so remain just one issue and I suggest to finish this PRs (add missing tests) and merge it. Great work Roger!

P.S. I reported mentioned unrelated issues from closed PR: [JBPM-7502](https://issues.jboss.org/browse/JBPM-7502), [JBPM-7509](https://issues.jboss.org/browse/JBPM-7509), [JBPM-7510](https://issues.jboss.org/browse/JBPM-7510)

**Comment by romartin** [comment]
Hey @hasys @wrnkld 
Yeah tbh I'm running out of time, and also we should discuss a bit how bendpoints behave as within parents... it's not yet even clear for me. So as you suggest, I would prefer to create a new JIRA for this as well.
So working on tests now... will let you know!
Thanks!

**Comment by romartin** [comment]
Hey @hasys @tiagodolphine 

Just added more commits here, and in both lienzo core and test repositories, that apply your comments and added more tests as well. Time is up for me... I'm trying to close this PR, if possible today (Fri), so please can you give it a look?

@hasys I was not able to test the `WiresConnector.getIndexForSelectedSegment`, sorry it relies on the `context2d` from the `scratchpad` and this is still not working on the testing framework... I know we've to add thsi test at some point, but well I did not updated this method at all, so I don't expect breaking it. On the other hand, updated and added all test cases that were possible for controls and connector :+1: 

@tiagodolphine Once this gets merged you'll be able to start working on the pending issues about bendpoints

Thanks guys!!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Pull request merged**
