### PR TITLE
Clean up kie-wb-common-widgets/kie-wb-common-ui dependencies

### PR DESCRIPTION
**Pull request by jomarko**
@mareknovotny may I ask you for a review once the full downstream build is green?

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by mareknovotny** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by mareknovotny** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@mareknovotny  This seems as ready for merge.

**Pull request merged**
