### PR TITLE
[AF 1140 7.7.x] Poms Migration tool (#1671)

### PR DESCRIPTION
**Pull request by desmax74**
Depends on https://github.com/kiegroup/appformer/pull/346

### CODE REVIEW

**Comment by porcelli** [comment]
jenkins execute full downstream build

**Comment by porcelli** [comment]
jenkins execute full downstream build

**Comment by desmax74** [comment]
jenkins execute full downstream build

**Comment by desmax74** [comment]
jenkins execute full downstream build

**Pull request merged**
