### PR TITLE
BAPM-870 (Stunner) - Advanced properties Reusable Sub-Process

### PR DESCRIPTION
**Pull request by Josephblt**
https://issues.jboss.org/browse/BAPL-870

Added two extra properties on Reusable Process
On Entry Action
On Exit Action

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Hey @romartin. All set like we talked. Thanks.

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by hasys** [comment]
Hi @Josephblt,

you can use this test: https://github.com/kiegroup/kie-wb-common/blob/57e03c05c88c7806b56cd9b9c64fb1832768f911/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/java/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/marshalling/subprocesses/ReusableSubProcessTest.java

and this process: /home/kgaevski/Workspace/github/kiegroup/kie-wb-common/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-backend/src/test/resources/org/kie/workbench/common/stunner/bpmn/backend/service/diagram/reusableSubProcesses.bpmn

Just add non-empty value to a one of sub-process and check in tests that for one of subprocess value is still empty and for filled sub-process is not empty and has correct value (it will be good to add some specific symbols to it like ~`1@#!#%%$^ \n\r and so on. (probably inside of a string like System.out.println("&(^*&^(\n\r") for Java and print("~`!@#$%^&*()_+=-{}|\n\r][:\",.?") for JavaScript

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Hey @romartin, @hasys. Added the tests. All done now. Thanks.

**Pull request merged**
