### PR TITLE
RHPAM-2748 :Update locale selection drop down to include only the sup…

### PR DESCRIPTION
**Pull request by RishiRajAnand**
- Removed the code that includes non-translated locales

Part of an ensemble:
- https://github.com/kiegroup/kie-wb-common/pull/3191
- https://github.com/kiegroup/kie-wb-distributions/pull/1018

### CODE REVIEW

**Comment by RishiRajAnand** [comment]
I have just removed the locales names from the Constants.java, but haven't removed the .properties file as of now. @dgutierr Do we need to remove them as well ?

**Comment by manstis** [comment]
@RishiRajAnand Thank-you.. IMO they should be removed from (at least) `CommonConstants.properties` as this will be used by our i18n team to determine the translations needed. If the entry remains in that file, they will continue to translate it. If it is removed from that file they will not continue to translate it!

**Comment by RishiRajAnand** [comment]
@manstis Makes sense, removed the keys from CommonConstants.properties.

**Comment by RishiRajAnand** [comment]
Jenkins retest this please

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
we need also backport of these PRs to 7.33.x today

**Comment by RishiRajAnand** [comment]
@mareknovotny Sure, will do

**Comment by barboras7** [comment]
Hi,
I tried to put some of the previously available locales into the URL. See the behavior on the screenshot. Is this what we want to happen? (See the German words mixed with English
Screenshot from 2020-02-28 13-46-18
)

**Comment by manstis** [comment]
Thank-you for the check @barboras7.

Firstly, IIUC there should no longer be ANY German translations. Can you confirm you used the WAR generated from [this](https://github.com/kiegroup/kie-wb-distributions/pull/1018/) PR? Secondly, it can be _normal_ that missing translations for a locale fallback to English. So that alone is less of a worry (than there being ANY German translations!)

**Comment by RishiRajAnand** [comment]
@manstis @barboras7 I am looking into it now, Looking like I missed a change somewhere

**Comment by barboras7** [comment]
@manstis yes, I am using the correct .war file, I just double checked. 
@RishiRajAnand sure. Otherwise, it seems to work correctly, the above mentioned is my only concern

**Comment by RishiRajAnand** [comment]
@manstis This behavior is explained in https://issues.redhat.com/browse/ERRAI-1101, the description clearly states the following 
"With locale=de query param
This is the case when using a locale that has a translation in the properties bundle but wasn't added to the locale property in GWT module. UI code that uses TransationService displays German translation and fallback for untranslated keys works." 

So looks like we have to remove the .properties file too make it work. @manstis wdyt ?

**Comment by manstis** [comment]
@RishiRajAnand 
> So looks like we have to remove the .properties file too make it work. @manstis wdyt ?

i18n never fails to surprise me! I agree.. it looks like the now sprurious files need removing too.

**Comment by manstis** [comment]
@RishiRajAnand Please see https://github.com/kiegroup/kie-wb-common/pull/3194. Perhaps @mbiarnes has already done a clean-up and, if @barboras7, rebuilds the FBD the new WAR will be OK.

**Comment by mbiarnes** [comment]
Jenkins execute full downstream

**Comment by RishiRajAnand** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
I will merge this as the kiegroup/kie-wb-distributions#1018 is merged and 7.33.x branch PRs were merged too.
if there will be any issue with this change it will affect 7.33.x branch too, so we need to have fix on both.

**Pull request merged**
