### PR TITLE
AF-619: [Library] Null exception appears in Project Explorer when switching views

### PR DESCRIPTION
**Pull request by paulovmr**
Hi @barboras7 , could you check if this fixes the issue? Thanks!

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by barboras7** [comment]
Jenkins execute full downstream build

**Comment by barboras7** [comment]
@manstis I'm looking at it.. Just need to check that with the whole UI test suite (UI tests are pretty slow sometimes :) )

**Pull request merged**
