### PR TITLE
DROOLS-3936: Increase the coverage

### PR DESCRIPTION
**Pull request by jomarko**
Dependent on https://github.com/kiegroup/kie-wb-common/pull/3111/files

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
@manstis see description, will fail until the https://github.com/kiegroup/kie-wb-common/pull/3111 is not merged.

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
Failed tests:
```
org.guvnor.ala.docker.executor.DockerExecutorTest.testFlexAPI
org.guvnor.ala.services.rest.tests.RestRuntimeProvisioningImplTest.testAPI
```

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@kiegroup/gatekeepers can we please merge?

**Pull request merged**
