### PR TITLE
AF-1819: Fix KieMetadataTest.compileAndLoadKieJarMetadataAllResourcesPackagedJar()

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/AF-1819

### CODE REVIEW

**Comment by desmax74** [comment]
@lanceleverich FYI to re-enable this test when a fix will be ready

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by wmedvede** [comment]
seems like random error was produced during @manstis last build retry
1:55:07 ERROR: Error fetching remote repo 'origin'
11:55:07 hudson.plugins.git.GitException: Failed to fetch from https://github.com/kiegroup/kie-wb-common.git
11:55:07 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:862)
11:55:07 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1129)
11:55:07 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1160)
11:55:07 	at hudson.scm.SCM.checkout(SCM.java:495)
11:55:07 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1202)
11:55:07 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
11:55:07 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
11:55:07 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
11:55:07 	at hudson.model.Run.execute(Run.java:1724)
11:55:07 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
11:55:07 	at hudson.model.ResourceController.execute(ResourceController.jav

**Comment by wmedvede** [comment]
Jenkins please retest this

**Comment by ederign** [comment]
Jenkins please retest this

**Comment by wmedvede** [comment]
Jenkins please retest this

**Comment by wmedvede** [comment]
org.kie.workbench.common.services.backend.compiler.rest.client.MavenRestClientTest.org.kie.workbench.common.services.backend.compiler.rest.client.MavenRestClientTest

Failing for the past 1 build (Since Failed#1513 )
Took 24 sec.
add description
Error Message
Cannot deploy: compiler.war
Stacktrace
org.jboss.arquillian.container.spi.client.container.DeploymentException: Cannot deploy: compiler.war
	at org.jboss.as.arquillian.container.ArchiveDeployer.createException(ArchiveDeployer.java:214)
	at org.jboss.as.arquillian.container.ArchiveDeployer.deployInternal(ArchiveDeployer.java:179)
	at org.jboss.as.arquillian.container.ArchiveDeployer.deployInternal(ArchiveDeployer.ja
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126) [surefire-booter-2.22.1.jar:2.22.1]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418) [surefire-booter-2.22.1.jar:2.22.1]

Caused by: java.net.ConnectException: WFLYPRT0053: Could not connect to remote+http://127.0.0.1:9990. The connection failed
	at org.jboss.as.protocol.ProtocolConnectionUtils.connectSync(ProtocolConnectionUtils.java:128) ~[wildfly-protocol-6.0.2.Final.jar:6.0.2.Final]
	at org.jboss.as.protocol.ProtocolConnectionManager$EstablishingConnection.connect(ProtocolConnectionManager.java:259) ~[wildfly-protocol-6.0.2.Final.jar:6.0.2.Final]
	at org.jboss.as.protocol.ProtocolConnectionManager.connect(ProtocolConnectionManager.java:70) ~[wildfly-protocol-6.0.2.Final.jar:6.0.2.Final]
	at org.jboss.as.protocol.mgmt.ManagementClientChannelStrategy$Establishing.getChannel(ManagementClientChannelStrategy.java:167) ~[wildfly-protocol-6.0.2.Final.jar:6.0.2.Final]

**Comment by wmedvede** [comment]
Jenkins please retest this

**Comment by manstis** [comment]
Finally!

**Pull request merged**
