### PR TITLE
[7.7.x] RHPAM-443 Stunner - Issues once resizing a shape - cherry-pick

### PR DESCRIPTION
**Pull request by tiagodolphine**
Cherry-pick 97b8004857a7569c11d5bd1736da0f6c1819ae34 from JBPM-6702 

@romartin

### CODE REVIEW

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
jenkins retest this

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
look code good, waiting the build for testing

**Comment by tiagodolphine** [comment]
Jenkins retest this

**Comment by tiagodolphine** [comment]
Hi @hasys can you please review this one when possible.
Thanks

**Comment by romartin** [comment]
yes please @hasys , this ticket is a blocker for 7.7.x, please give this and the other blocker ones priority this time... let's see if we can merge it!! Thanks!

**Comment by tiagodolphine** [comment]
Hi @hasys  just waiting for your review on this.
thanks !!

**Pull request merged**
