### PR TITLE
[AF-1600] Fix MavenRestClientTest on jenkins

### PR DESCRIPTION
**Pull request by desmax74**
Fix the load of the Pom in the Arquillian Test when it runs on Jenkins @porcelli @jhrcek @domhanak @mbiarnes

### CODE REVIEW

**Comment by porcelli** [comment]
@desmax74 could you explain the issue this PR aim to solve?

**Comment by domhanak** [comment]
Roses are red,
violets are blue,
Jenkins execute full downstream build!

**Comment by domhanak** [comment]
@porcelli This test is failing on master daily build of kie-wb-common and also on 7.11.x

**Comment by jhrcek** [comment]
@desmax74 @porcelli could you please review and merge this? This has been failing for a long time (not rendomly) every day in daily build: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/dailyBuild/job/kieAllBuild-master/

**Comment by desmax74** [comment]
Removed the old setting used in the arquillian part, now is used always the util method to checks the env

**Comment by porcelli** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
@porcelli Green! Let's merge this, please.

**Pull request merged**
