### PR TITLE
RHPAM-955: Rename labels in B&D modal

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by sterobin** [comment]
@jomarko, also need to change the following values for that UI window:

- Container ID / Container Alias needs to be Deployment Unit ID / Deployment Unit Alias
- Start Containter? Needs to be Start Deployment Unit?

**Comment by jomarko** [comment]
@sterobin thanks for review, should be done now.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@romartin @manstis would you mind to have a look on this?

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@manstis this is ready for merge

**Pull request merged**
