### PR TITLE
RHDM-600:latest Zanata translation changes in kie-wb-common from 2018-05-31

### PR DESCRIPTION
**Pull request by kiereleaseuser**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
@manstis can you please merge this once green

**Comment by mbiarnes** [comment]
org.kie.workbench.common.services.backend.validation.asset.ValidatorTest.testValidateWhenTheresNoProject
test is failing also in the kieAllBuild of 7.5.x branch

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
