### PR TITLE
BAQE-488: Add test for creating data object which already exists

### PR DESCRIPTION
**Pull request by tomasdavidorg**
https://github.com/kiegroup/jbpm-designer/pull/808
https://github.com/kiegroup/kie-wb-common/pull/2023
https://github.com/kiegroup/drools-wb/pull/908

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
@ederign Could you please look at these short PRs. I tried to move the selenium test. More info here https://issues.jboss.org/browse/BAQE-488

**Comment by manstis** [comment]
@wmedvede Added you as a reviewer out of courtesy (as this is/was your area).

**Comment by wmedvede** [comment]
@manstis Thanks for https://github.com/kiegroup/kie-wb-common/pull/2023#issuecomment-411533661, I'll appreciate keeping an eye Data Modeler related PRs.

**Comment by tomasdavidorg** [comment]
Are we ok to merge this?

**Pull request merged**
