### PR TITLE
DROOLS-2565: [DMN Editor] Move showcase webapp to 'project' based instead of 'standalone'

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-2565

### CODE REVIEW

**Comment by manstis** [comment]
Part of an ensemble:

- https://github.com/kiegroup/kie-wb-common/pull/1975
- https://github.com/kiegroup/drools-wb/pull/888

**Comment by manstis** [comment]
@jomarko You've already approved.. just need @karreiro to pull his socks up! ;-)

**Comment by manstis** [comment]
(This is the only one I need merged before I can integrate into ```kie-wb-distributions```).

**Comment by manstis** [comment]
Thanks @karreiro Are you going to raise the new JIRA?

**Comment by karreiro** [comment]
@manstis I just [raised](https://issues.jboss.org/browse/DROOLS-2755) the issue.

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
