### PR TITLE
[JBPM-9311] KIE server will not always deploy services, stay in sync …

### PR DESCRIPTION
**Pull request by elguardian**
JIRA: https://issues.redhat.com/browse/JBPM-9311

template update event does not refresh the whole thing (ie. containers)

### CODE REVIEW

**Comment by elguardian** [comment]
depends on https://github.com/kiegroup/droolsjbpm-integration/pull/2237

**Comment by elguardian** [comment]
Jenkins retest this please.

**Review by gmunozfe — APPROVED** [review]
Looks good to me

**Comment by gmunozfe** [comment]
jenkins retest this

**Pull request merged**
