### PR TITLE
JBPM-6705 [Stunner] Multi-selection copy/cut and paste

### PR DESCRIPTION
**Pull request by tiagodolphine**
Now it is possible to copy/cut and paste multiple selection of elements on diagrams.
The position of pasting was changed to avoid overlapping elements, now it is considered the max Y position considering all the elements on the selection.

@romartin @hasys  can you please help to review the PR.
Thanks.

### CODE REVIEW

**Comment by tiagodolphine** [comment]
Jenkins retest this

**Comment by tiagodolphine** [comment]
Jenkins please retest this

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @tiagodolphine ,

Great job. Anyway for now found a minor issue, but I think it worth fixing it. 

When copy/pasting multiple elements and their connectors, you need to undo and redo twice - the first execution apply to the connectors and the second to the nodes... look at the following sequence (screenshots):
- Copying the following elements -> even-connector-task:
screenshot from 2018-01-08 22-20-14
- Pasting results in this:
screenshot from 2018-01-08 22-20-23
- Now clicking on the undo button - only connectors "disappear":
screenshot from 2018-01-08 22-20-33
- Clicking again on the undo button - now nodes "disappear":
screenshot from 2018-01-08 22-20-39

And same happens for "redo". It seems instead of compositing all the commands into a single one, there are two....

**Comment by tiagodolphine** [comment]
Hey @romartin thanks for the review, I have just pushed the fix the issue regarding undo/redo.

Thanks.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Removing @hasys as he's sick. I've retested this locally and build a successfull downstream build, merging it.

**Pull request merged**
