### PR TITLE
AF-1123 : Broken project cannot be deleted

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/AF-1123

### CODE REVIEW

**Comment by Rikkola** [comment]
@barboras7 @paulovmr Follow up for #1615

**Comment by Rikkola** [comment]
I'll group this and the fix for AF-1123 in on PR for 7.5.x and 7.7.x once we have this in.

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
Hi @Rikkola,
tried this locally by following the steps to reproduce from the AF-1123. What happened is that I get the "The project is broken" screen but there is "Loading assets..." popup that does not disappear and the business central seems to be broken (you can not do anything at all) and you need to refresh the page. 
screenshot from 2018-04-16 16-05-30

**Comment by Rikkola** [comment]
@barboras7 I need to double check this PR has the latest. I had the same problem, but fixed it.

**Comment by Rikkola** [comment]
@barboras7 You are right. Import leaves the popup open.

**Comment by Rikkola** [comment]
@barboras7 Ok. Fixed the import.

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins please retest this

**Comment by barboras7** [comment]
@Rikkola, I tested the fix locally and the above mentioned problem is fixed. What happens now is that if you import the broken project as described in the steps to reproduce of the issue, you are not able to access the project settings. You can open the Contributors and Metrics tab, but the Settings tab does not work. Is this intentional behaviour? This way, user is not able to access the pom.xml file.

**Comment by Rikkola** [comment]
Yes. Since you can not fix the pom.xml with the Project Editor and you can't break it either. At this point you can only do this with cloning the repository, so that is how it needs to be fixed.

**Comment by barboras7** [comment]
@Rikkola, yes, that makes sense. Maybe disabling the Settings tab in a broken project might be a good approach so that it is obvious that it should not work for now. Anyway, I'm not sure how much effort would be necessary for this and whether it's worth the time.

**Comment by Rikkola** [comment]
jenkins execute full downstream build

**Comment by Rikkola** [comment]
Jenkins, I'm not going to even ask you test this today since even I can't build anything locally. See you tomorrow.

**Comment by Rikkola** [comment]
All checks passed! This can go in :)

**Pull request merged**
