### PR TITLE
KOGITO-6703: Render DMN Text Annotations in Documentation

### PR DESCRIPTION
**Pull request by jomarko**
Backport of https://github.com/kiegroup/kie-tools/pull/835

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins do fdb

**Review by yesamer — APPROVED** [review]

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
@mareknovotny build passed after https://github.com/kiegroup/kie-wb-common/pull/3727, may I ask you for a merge?

**Pull request merged**
