### PR TITLE
JBPM-6820: Stunner - Data assignments editor show data types from all projects of Business Central instance

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/JBPM-6820

This PR just fixes the list of data-types shown in the "Task Data I/O" popup and "Process Data" properties.

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@hasys Please could you take a look when you have a moment free.

**Comment by hasys** [comment]
Looks like full downstream build wasn't triggered.
Jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@romartin @hasys Did you want to wait for a "full downstream" build before merge?

It seems to keep failing on the kie-wb-distribution Selenium/REST tests (time out deploying).

**Comment by romartin** [comment]
@manstis the build is fine!

**Comment by manstis** [comment]
@hasys Looks like @romartin has merged without your approval...

**Comment by romartin** [comment]
I absolutely trust on @manstis code, no need for review!! :P ... sorry guys, got back to the wrong tag and click on merge.... tbh I'm feeling lost last few days with so many PRs and branches and reviews... ./

**Comment by hasys** [comment]
Hi @manstis, @romartin, yes, it is quite a lot of staff last weeks. Will check it now with latest workbench community build :)

**Comment by hasys** [comment]
@manstis @romartin not sure, but I am still able to see data types from other project, will wait for fresh FullDownstream build or next workbench build to try again.

**Pull request merged**
