### PR TITLE
KOGITO-2667: [DMN Designer] Multiple DRDs support - Graph - Create a copy of DRG elements in the DRG

### PR DESCRIPTION
**Pull request by danielzhe**
**JIRA**: [KOGITO-2667](https://issues.redhat.com/browse/KOGITO-2667)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by danielzhe** [comment]
jenkins do fdb

**Comment by danielzhe** [comment]
@jstastny-cz Rebased.

**Comment by jstastny-cz** [comment]
Builds failing due to:
```
[2020-10-05T19:39:35.584Z] [INFO] There is 1 error reported by Checkstyle 8.19 with /home/jenkins/workspace/KIE/master/fdb/kie-wb-common-master.fdb/kie-wb-common-dmn/kie-wb-common-dmn-client/target/checkstyle-rules.xml ruleset.
[2020-10-05T19:39:35.584Z] [ERROR] src/main/java/org/kie/workbench/common/dmn/client/canvas/controls/builder/ObserverBuilderControl.java:[54,1] (imports) RedundantImport: Duplicate import to line 53 - org.kie.workbench.common.stunner.core.graph.content.HasContentDefinitionId.
```
Please fix the violation and run the fdb again. Thanks.

**Comment by danielzhe** [comment]
jenkins do fdb

**Comment by danielzhe** [comment]
Converted to draft because we need to discuss it more about to handle this case. We have a meeting scheduled and we'll be back to this PR after that.

**Comment by jstastny-cz** [comment]
@danielzhe should we close this one?

**Pull request closed without merging**
