### PR TITLE
[7.52.x] RHDM-1647: DMN - Reopened diagram with DRDs can not be edited

### PR DESCRIPTION
**Pull request by romartin**
Hey  @karreiro @jomarko 

Here is the fix for https://issues.redhat.com/browse/RHDM-1647

I've properly tested kogtio and BC, and both look good to me. In fact in kogtio the issue was not being exposed, user didn't notice about it, although it was some memory leak there anyway, but now everything ok!! :tada: 

Please the deadline for this PR is this Fri, would appreciate en **early review (targeting RHPAM 7.11)**.

Thanks in advance!

### CODE REVIEW

**Comment by romartin** [comment]
jenkins do fdb

**Comment by jomarko** [comment]
Manual review scenarios

RHDM-1647
- [ ] BC
- [ ] VS Code

Open BPMN, add some nodes, save, reopen, move nodes, undo movements
- [ ] BC
- [ ] VS Code

Open DMN without DRDs, add some nodes, save, reopen, move nodes, undo movements
- [ ] BC
- [ ] VS Code

Open DMN with DRDs, add some nodes into DRD1, add some nodes into DRD2, save, reopen, move nodes DRD1, move ndoes DRD2, undo movement DRD1, undo movement DRD2
- [ ] BC
- [ ] VS Code

Open BPMN, Open DMN without DRDs, add some nodes BPMN, add some nodes DMN, undo BPMN, undo DMN
- [ ] BC
- [ ] VS Code

**Comment by romartin** [comment]
Hey @jomarko @karreiro 

Here is the VSIX file for testing DMN editor -> https://drive.google.com/file/d/1twY9qLnLqeXNZl5XjZmF7t1YlUk8lvvR/view?usp=sharing

Thanks!

**Review by karreiro — COMMENTED** [review]
Thank you, @romartin! LGTM! However, I've noticed a small regression for this fix https://github.com/kiegroup/kie-wb-common/pull/3608 (on BC and VSCode).

Now we're losing undo/redo when we alternate between diagrams again. @danielzhe do you have any clues for us here?

**Comment by jomarko** [comment]
@romartin thank you. Also my only findings is related to asset swithing. Undo redo buttons are disabled for DMN , if user edit in parallel DMN and BPMN, compare
- your PR - edit-parallel-undo.webm attached to RHDM-1647
- master - edit-parallel-undo-master.webm attached to RHDM-1647

As @karreiro mentioned, it is realted to area of other opened PRs. Not sure what should be next steps. Report separately? Try to rebase this PR ith changes @karreiro mention?

**Comment by karreiro** [comment]
@jomarko actually, I believe that @romartin branch already includes the commit with Daniel's fix for undo/redo. My guess is that we're losing the undo/redo commands during the `ManagedSession#close`.

**Comment by romartin** [comment]
Hey @karreiro @jomarko 

The only reason I see for this it's because now I'm clearing the commands line, onc switching between diagrams, in order to release as much memory as possible.

So I'm just adding a new commit that does not clear the list of commands, also testing it locally, will upload VSIX as soon as possible too.

Thanks!

**Comment by romartin** [comment]
Hey @karreiro @jomarko 

Good catch! And also my assumption hopefully was true :)

I just added the fix commit, also uploaded again the VSIX => https://drive.google.com/file/d/10mmq66-1X4krZV0XPZRQqcUDbcUqxYFk/view?usp=sharing

Tested and it works for me.

Thanks!

**Comment by romartin** [comment]
jenkins do fdb

**Review by karreiro — APPROVED** [review]
Great stuff, @romartin! Thank you!

**Comment by romartin** [comment]
cool, thanks @karreiro !! 

Please @jomarko just waiting for your "good" feedback and approval (hopefully)  :)

Thanks guys!

**Review by jomarko — APPROVED** [review]
Thank you @romartin

**Pull request merged**
