### PR TITLE
JBPM-9290 - Stunner - make body field of Notification resizable

### PR DESCRIPTION
**Pull request by hasys**
**JIRA**: [JBPM-9290](https://issues.redhat.com/browse/JBPM-9290)

Hi @romartin this is a small fix we talked about. Thank you!

image

Hi @domhanak, @LuboTerifaj, will check this PR or we can reassign it to another developer?

### Full resize
https://drive.google.com/file/d/1t8EUEcpsY3MHfjbXclrwA11C3d9VfDFA/view?usp=sharing
### Vertical resize only
https://drive.google.com/file/d/1CIN4DT3bgEQWX-HxH7yf0NFUJQMnYufp/view?usp=sharing

### Full resize
https://drive.google.com/file/d/10jwlCy7fd4YVpEVAl7BRAKwGSEdtn_vv/view?usp=sharing
### Vertical resize only
https://drive.google.com/file/d/1XPXcgjLi3Nrd0_SGf6-RMxPuypjBJSIa/view?usp=sharing

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute compile downstream build

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
jenkins retest this

**Comment by hasys** [comment]
Hi @LuboTerifaj,

thank you for great findings.

This is a small improvement in the UX for the user and behavior of TextArea resize is default for the browser. In following month we will migrate to new Patternfly and there some plans to redo whole properties panel as well. I think this improvement is reasonably small and useful. If you don't think so we should close this PR since we have no resources dedicated for this improvement.

Thank you!

**Comment by romartin** [comment]
Hey @LuboTerifaj @hasys 

First of all, this is an improvmenet but we're not really tight to deliver it, so it shows your implication on the tool, so thanks a lot in advance!!

Well I suggested this change because I understood that was a quick win, honestly, but thanks to the good review, I just noticed it has some implications which I initially was not considering. Also considering that we're moving going to "replace" soon most of the forms/UI stuff, this is not really a priority.

Soo IMO, let's not spend time on something that has to be deprecated soon... I would just postpone this improvment for further work. Although I'll let the final word to you guys, if you really think it's easy to achieve let's go ahead... although I don't think it is, actually.

Anyway, sorry for the inconveniences for reporting this without having in mind all the implications, I've learned something today :) thanks guys for your work and collaboration. Just lemme know your thoughts

**Comment by hasys** [comment]
Hi @LuboTerifaj,

I pushed a change with Vertical resize only, will rebuild/upload it for comparing. Thank you for great review!

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
Hi @romartin, @LuboTerifaj, this PR is ready for rereview. Thank you!

**Comment by LuboTerifaj** [comment]
Jenkins execute fdb

**Review by LuboTerifaj — APPROVED** [review]
Hello @hasys ,

The issue found from my previous [comment](https://github.com/kiegroup/kie-wb-common/pull/3390#pullrequestreview-466839910) is reported here: https://issues.redhat.com/browse/JBPM-9319

According to acceptance criteria, it looks good to me.

Thanks!

**Review by romartin — APPROVED** [review]

**Pull request merged**
