### PR TITLE
GUVNOR-3352 [DMN Editor] Marshaller of extensions for UI aspects DMN 1.1

### PR DESCRIPTION
**Pull request by tarilabs**

### CODE REVIEW

**Comment by tarilabs** [comment]
Reference of `diamond.dmn`:
image

**Comment by tarilabs** [comment]
```
Test Result (1 failure / +1)
org.kie.workbench.common.stunner.bpmn.backend.service.indexing.BpmnFileIndexerTest.testBpmnIndexing
```

Jenkins, test again :8ball:

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
