### PR TITLE
[7.23.x] AF-2080: Check just public methods available

### PR DESCRIPTION
**Pull request by jomarko**
Dependent on #2727 . Will rebase once the original PR is in.

This PR update the test to be sure just public methods are offered for invocation.

### CODE REVIEW

**Comment by manstis** [comment]
@jozef https://github.com/kiegroup/kie-wb-common/pull/2727 has now been merged.

**Comment by jomarko** [comment]
@manstis thank you, I rebased, lets wait for jenkins

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@manstis please merge

**Pull request merged**
