### PR TITLE
JBPM-9703: DMN - Reopened diagram with DRDs can not be edited

### PR DESCRIPTION
**Pull request by romartin**
Hey @karreiro @jomarko 

Here is the cherry-pick for https://github.com/kiegroup/kie-wb-common/pull/3614 into master branch.

FYI - I've also duplicated https://issues.redhat.com/browse/RHDM-1647 into https://issues.redhat.com/browse/JBPM-9703

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
jenkins do fdb

**Review by jomarko — APPROVED** [review]
As this is a cherry-pick and current QE work load, approving without complex review. Thank you @romartin .

**Comment by karreiro** [comment]
jenkins do fdb

**Comment by romartin** [comment]
jenkins do fdb

**Pull request merged**
