### PR TITLE
AF-985: [Project Oriented] Project doesn't show all imported assets.

### PR DESCRIPTION
**Pull request by mbarkley**
A fix for AF-985 and a forward port of RHDM-382 are bundled together in this PR as they both affect related code.

The AF-985 fix will cause the project screen to reload whenever a place request to it is made, even if it is already in focus. This allows clicking on the breadcrumb to refresh.

### CODE REVIEW

**Comment by mbarkley** [comment]
@jsoltes Are you still able to reproduce the issue on this branch?

**Comment by jsoltes** [comment]
@mbarkley ok, actually not anymore in the scenario I described... But I can still reproduce it when importing a local project - with using the file:/// protocol. When you clone the project from the jira locally and then try to upload it, only 5 assets are visible.

**Comment by mbarkley** [comment]
@jsoltes I still cannot reproduce the issue, even importing the project from the file URL. It does take a few seconds for all the assets to appear.

It will update in stages (it polls for changes as there isn't an easy way to know when indexing is finished). Is it possible you are just not waiting long enough to see the fully loaded list?

**Comment by jsoltes** [comment]
@mbarkley I tried it again, am I am getting the same result. After waiting for more than 1 min, only 5 assets appeared. Maybe it is something environment specific? I am using a clean installation of kie-wb from the full downstream build on chrome.

**Comment by mbarkley** [comment]
Related PR: https://github.com/kiegroup/appformer/pull/218

**Comment by mbarkley** [comment]
@jsoltes Okay, I have an actual fix now that removes timing issues with indexing. It's not quite finished (currently if indexing is not finished the asset list shows the "no results" instead of the "indexing not finished" page) but it's most of the way there.

There is a related appformer PR you will have to build to test this.

**Comment by mbarkley** [comment]
@adrielparedes @paulovmr Would either of you care to review this? This removes the polling logic from asset list, and instead listens for an event that updates the screen after indexing has finished.

I probably will have to make one more change so that the screen can know if indexing has started or the project is truly empty.

//cc @manstis

**Comment by mbarkley** [comment]
Jenkins, please retest this.

**Comment by jsoltes** [comment]
jenkins please execute full downstream build

**Comment by adrielparedes** [comment]
@mbarkley it looks really good, I'm glad the polling was replaced. Let me wait for downstream build so I can use kie-wb to check screens.

**Comment by paulovmr** [comment]
@mbarkley Looks good, thanks. :)

**Comment by mbarkley** [comment]
Hehe, @jsoltes this is an example of why you shouldn't push the approve button until all the changes you want are in.

I will send another PR to fix the "waiting for indexing".

**Comment by jsoltes** [comment]
@mbarkley hah, okay. next time i will know :)

**Pull request merged**
