### PR TITLE
JBPM-5500: Removed Refresh Button

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
@romartin Waiting for your review.

@Christopher-Chianelli This PR will need updating to refer to 7.3.x.

**Comment by romartin** [comment]
Hey @Christopher-Chianelli, please do not forget this one, let's try to get this merged as soon as possible... Can you please fix the Jenkins build? Thanks!

**Comment by Christopher-Chianelli** [comment]
@romartin How do you ask Jenkins to retest? I tried accessing the tests but they are not available; I find it odd the normal build failed since the downstream build succeeded.

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by Christopher-Chianelli** [comment]
@romartin Apparently your retest "fixed" the Jenkins build.

**Comment by romartin** [comment]
hehe great @Christopher-Chianelli , so it seems ready to merge!! 
PS: Do not forget the merges on 7.x once this is done. Thx!

**Comment by Christopher-Chianelli** [comment]
@romartin This is the 7.x PR for an earlier master PR; do I need to merge to any other ones?

**Comment by romartin** [comment]
oh sorry @Christopher-Chianelli , got confused, it's all fine :) thanks!

**Pull request merged**
