### PR TITLE
Fix kie-takari-plugin version in tests

### PR DESCRIPTION
**Pull request by desmax74**
Fix kie-takari-plugin version in tests on 7.2.x

### CODE REVIEW

**Comment by desmax74** [comment]
@mbiarnes @psiroky

**Comment by manstis** [comment]
@porcelli @psiroky Soooo.. who want's to _actually_ merge this? 

Do we get CI builds on 7.2.x? Do we need one?

Are we waiting for anything?

**Comment by psiroky** [comment]
jenkins retest this -- yes, I am waiting to get a green build

**Comment by desmax74** [comment]
jenkins retest this

**Comment by desmax74** [comment]
jenkins retest this

**Pull request merged**
