### PR TITLE
[AF-2433] Fixed error when building the base kie template. (#3159)

### PR DESCRIPTION
**Pull request by ederign**
Cherry-pick of: https://github.com/kiegroup/kie-wb-common/pull/3159

### CODE REVIEW

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins please retest this

**Comment by ederign** [comment]
@mareknovotny fdb passed, let me re run again the regular build.

**Comment by ederign** [comment]
Jenkins please retest this

**Comment by mareknovotny** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Pull request merged**
