### PR TITLE
[AF-2464] Upgrade com.thoughtworks.xstream version (1.4.10 -> 1.4.11.1)

### PR DESCRIPTION
**Pull request by caponetto**
**Task**:[ AF-2464](https://issues.redhat.com/browse/AF-2464)

**Validation**:
1. Create a new project
2. Create an asset
3. Open the project explorer
4. Change to "_Repository view_" (Settings icon)
5. Find and open `pom.xml` file
6. Check `com.thoughtworks.xstream` dependency version

### CODE REVIEW

**Comment by caponetto** [comment]
Jenkins execute full downstream build

**Comment by porcelli** [comment]
isn’t possible to use the same variable version used by our Pom?

https://github.com/kiegroup/droolsjbpm-build-bootstrap/blame/master/pom.xml#L95

**Comment by caponetto** [comment]
> isn’t possible to use the same variable version used by our Pom?
> 
> https://github.com/kiegroup/droolsjbpm-build-bootstrap/blame/master/pom.xml#L95

I was just testing it!

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Pull request merged**
