### PR TITLE
RHPAM-2781: Data Modeller "Search Annotation" requires FQN of annotation to be used

### PR DESCRIPTION
**Pull request by akumar074**
- Changed the page title from "Search annotation" to "Load annotation"
 - Changed search field placeholder from "search annotation class name" to "load annotation class name"

**JIRA**: [RHPAM-2781](https://issues.redhat.com/browse/RHPAM-2781)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by akumar074** [comment]
jenkins do fdb

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
jenkins do fdb

**Comment by akumar074** [comment]
jenkins retest this

**Comment by akumar074** [comment]
jenkins retest this

**Comment by akumar074** [comment]
jenkins do fdb

**Comment by akumar074** [comment]
Hi @paulovmr @dupliaka Please review the PR.

**Review by dupliaka — APPROVED** [review]
LGTM

**Comment by akumar074** [comment]
jenkins retest this

**Comment by akumar074** [comment]
jenkins do fdb

**Review by paulovmr — APPROVED** [review]

**Pull request merged**
