### PR TITLE
[Stunner] Catching Intermediate Events tests (#1609)

### PR DESCRIPTION
**Pull request by LuboTerifaj**
(cherry picked from commit 4249d4d)

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
Hi @romartin @evacchi 
Can you please have a look at this?
Thanks!

**Comment by evacchi** [comment]
do we really need to backport this? new marshallers are not enabled (by default) in 7.7.x

**Comment by LuboTerifaj** [comment]
Hi @evacchi @romartin 
New marshaller is commented out anyway. My question is: Don't we want to have tests for old Marshaller in 7.7.x? Thanks.

**Comment by evacchi** [comment]
good question. Either way is fine for me, so let's ask @romartin

**Comment by romartin** [comment]
Hey @LuboTerifaj @evacchi 
Will proceed to close this PR, lemme know if any issues on this. The thing is that we're now on blockers only mode in `7.7.x`, and although this commit is just about tests, as they're  already present in master, I think there is no need to integrate this here.

**Comment by hasys** [comment]
Hi @romartin,

In my opinion tests only changes can't introduce new regressions. Also, we need tests merged and executed on our Jenkins with 7.7.x build to attach it to report about designer verification. So, I guess we can merge this PR with tests and any further tests only PRs as well.

**Comment by LuboTerifaj** [comment]
Hi @romartin 
Can you have a look at this cherry-pick as well?
Thank you.

**Comment by romartin** [comment]
Just failed a non related test. Merging, thanks!

**Pull request merged**
