### PR TITLE
FIX-KOGITO-2528 : FIX Issue on Master

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin can you review this PR, this fixes issue mentioned by @Josephblt 

**Thank you for submitting this pull request**

**JIRA**: [JBPM-0000](https://issues.redhat.com/browse/JBPM-0000)

**Referenced Pull Requests**:
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://donwnload.here/something)

**VS Code**: [plugin](https://donwnload.here/something)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Review by romartin — APPROVED** [review]

**Comment by romartin** [comment]
jenkins retest this

**Comment by inodeman** [comment]
Jenkins do fdb

**Comment by inodeman** [comment]
jenkins retest this

**Comment by inodeman** [comment]
Jenkins do fdb

**Comment by inodeman** [comment]
jenkins retest this

**Comment by inodeman** [comment]
Jenkins do fdb

**Comment by romartin** [comment]
The CI builds on the maven side are SUCCESS:

`15:59:07  [INFO] ------------------------------------------------------------------------
15:59:07  [INFO] BUILD SUCCESS
15:59:07  [INFO] ------------------------------------------------------------------------
15:59:07  [INFO] Total time:  01:42 h
15:59:07  [INFO] Finished at: 2021-04-26T11:59:07-04:00`

But the build result fails due to timeouts, which appear after maven compilation is sucessfull , and causing the whole build to fail:

`Waiting to resume part of KIE » master » pullrequest » kie-wb-common-master.pr #7: Finished waiting
Waiting to resume part of KIE » master » pullrequest » kie-wb-common-master.pr #7: ‘kie-psi-rhel7-xlarge-204’ is offline
Waiting to resume part of KIE » master » pullrequest » kie-wb-common-master.pr #7: ‘kie-psi-rhel7-xlarge-204’ is offline
Waiting to resume part of KIE » master » pullrequest » kie-wb-common-master.pr #7: ‘kie-psi-rhel7-xlarge-204’ is offline
Waiting to resume part of KIE » master » pullrequest » kie-wb-common-master.pr #7: ‘kie-psi-rhel7-xlarge-204’ is offline
Waiting to resume part of KIE » master » pullrequest » kie-wb-common-master.pr #7: ‘kie-psi-rhel7-xlarge-204’ is offline
Waiting to resume part of KIE » master » pullrequest » kie-wb-common-master.pr #7: ‘kie-psi-rhel7-xlarge-204’ is offline`

This fix is BLOCKING master upstream, I've been testing it locally and works fine, also it will not affect downstream modules as it's a compilation fix on a test case. So will proceed with merging to unblock work on master branch.

Thanks @inodeman

**Pull request merged**
