### PR TITLE
BAPL-764-migration-tool: Provide migration path from old Form Modeler to the new one

### PR DESCRIPTION
**Pull request by pefernan**
This PR adds the migration tool to move old forms to new format. This first PR only copies fields, layout & model settings. Advanced optiosn as formulas, custom layouts, JS callbacks are left on the old form until they are supported on the new forms engine.

This PR also adds a generic Migration Tool that allows to plug other migration tools via SPI and let's the user switch running each plugged migration tool individually or in batch mode.

Since there are a lot of changes. I'd like to split the review:

@Rikkola could you please take a look at the changes for the project migration tool?
@kkufova Hi! @jsoltes told me that you're the one in charge of forms while he's recovering. Could you please take a look? Ping me on IRC and I'll help you.
@romartin there has been some module changes, could you please check the stunner side too? Only package changes, nothing important.

This PR is part of an ensemble, merge with:

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/720
https://github.com/kiegroup/kie-wb-common/pull/1492
https://github.com/kiegroup/jbpm-designer/pull/754
https://github.com/kiegroup/jbpm-wb/pull/993
https://github.com/kiegroup/kie-wb-distributions/pull/704

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by Rikkola** [comment]
From my point of view it looks good. No existing tests broken and new added. So the work done here sounds good.

**Comment by Rikkola** [comment]
+1

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@mbarkley fixed the documentation. WDYT now?

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
@pefernan Hi, I think you will have to rebase your PRs for the build to pass. I was trying it locally (because I will have to make another migration) and the compilation is failing.

**Comment by pefernan** [comment]
@paulovmr thank you I'll do it right now.

**Comment by kkufova** [comment]
@pefernan, I built the whole PR locally with success. Please rebase on `master` (at least this repository, `jbpm-wb`, and `kie-wb-distributions`); the rebase may help the failing build. :-)

I have a few notes. Firstly, I think the tool is really easy to use, it's fast and straightforward. Well done!

However, there are three things I would like to discuss and possibly address:
1. Firstly, I experienced multiple `NullPointerException` exceptions during testing. I used [this](http://file.brq.redhat.com/~kkufova/niogitFolder/) `.niogit` directory (I had to rename it to `niogitFolder` to be able to upload it, but in this case, `niogitFolder` is `.niogit`) and [this](https://pastebin.com/iwWYhjs0) is the log. Is there anything we can do about the exceptions?

2. Next, I noticed that in the built Business Central (`./kie-wb-parent/kie-wb-distribution-wars/kie-wb/target/kie-wb-7.7.0-SNAPSHOT-eap7.war`), the following error appears every time you click anything and open Business Central:

screenshot from 2018-03-15 09-48-49

3. Lastly, could you please remove the unused code in 
`kie-wb-common/kie-wb-common-cli/kie-wb-common-cli-tools/kie-wb-common-cli-forms-migration/src/main/java/org/kie/workbench/common/forms/migration/legacy` we talked about? I think it would significantly simplify the copied code.

WDYT?

**Comment by pefernan** [comment]
@kkufova I'm rebasing everything all PR's now to fix the build issues... 

About your comments:

1. Good find I'll give it a try now.
2. Not sure if that issue is related to this PR but I'll take a look too.
3. Yes, that was my next step.

Thank you!

**Comment by kkufova** [comment]
NOTE: I was just informed that the error in the screenshot is not caused by this PR but it's available on `master`.

**Comment by kkufova** [comment]
@pefernan, good, thank you! I'm sorry about the number 2, apparently, the error is not caused by this PR.

**Comment by manstis** [comment]
@kkufova @pefernan IIRC there's a (merged) PR from @cristianonicolai that causes the jQuery error - I recall seeing some chatter about it on Github.

**Comment by pefernan** [comment]
@kkufova I found some git issues in your repo:

- on _repository1.git_ I get:
`error: refs/heads/master does not point to a valid object!
fet.
fatal: update_ref failed for ref 'HEAD': cannot update ref 'HEAD': trying to write ref 'HEAD' with nonexistent object 1958d5b00e5788804611e85da0c6ce7839d6625d
fatal: The remote end hung up unexpectedly
`
- on _system.git_ I get:
```
error: refs/heads/master does not point to a valid object!
error: refs/heads/social does not point to a valid object!
error: refs/heads/testadmin-uf-user does not point to a valid object!
fet.
fatal: update_ref failed for ref 'HEAD': cannot update ref 'HEAD': trying to write ref 'HEAD' with nonexistent object 6a36f8a9b7ad693dc4230092a57e7b91247eee8b
fatal: The remote end hung up unexpectedly

```Could you please check it? thanks!

**Comment by pefernan** [comment]
@kkufova fixed the issue you found

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by kkufova** [comment]
I'm adding the following information just to have it properly noted here, the matter was already discussed with @pefernan:

One `NullPointerException` still appears during migration of the `bpms-assets-6.4.x` repository. The repository is available [here](http://git.app.eng.bos.redhat.com/git/bpms-assets-6.4.x.git/), and the migration log can be found [here](https://pastebin.com/Dg7SSwJm). I used BPMS 6.4.9 CR2 version of the product. The `.niogit` directory used for migration is [here](https://drive.google.com/drive/folders/1w4ZRjrfMp8-7bbep3vVFXbXRq6e4fvvC?usp=sharing).

The `NullPointerException` appears when trying to migrate the `designer` project. Apparently, the migration tool fails because of `system.git`, that is created automatically after starting the server.

**Comment by pefernan** [comment]
@kkufova The last error was caused by a malformed BPMN proess. I added some checks to prevent breaking the migration in that case.

**Comment by kkufova** [comment]
@pefernan, please let me know when can I check again!

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@jsoltes could you please take a look at the integration tests ?

**Comment by pefernan** [comment]
@kkufova you should be able to test it but the problems in your git repo are still there.

**Comment by kkufova** [comment]
@pefernan, have you pushed the changes that allow the tool to continue in case there is a broken process in some project? I tried to build the PR locally, but I'm still getting NPEs. When I remove the projects with broken processes from the repository, the tool works really nice, so after the NPE problem is fixed, I'll give this PR +1.

**Comment by pefernan** [comment]
@kkufova sorry it seems that the push failed! just pushed the changes now.

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
It seems that the downstream build fails because of some test issues not related to this PR

**Comment by mbarkley** [comment]
Merged. The failures in the downstream build and related kie-wb-distributions PR look unrelated.

**Comment by romartin** [comment]
Hey @pefernan 
I'm running into issues at least with the [stunner-showcase-standalone](https://github.com/kiegroup/kie-wb-common/tree/master/kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone) - weld complains once running the server, sounds probably related to this?

`Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type FieldManager with qualifiers @Default\n  at injection point [BackedAnnotatedParameter] Parameter 1 of [BackedAnnotatedConstructor] @Inject public org.kie.workbench.common.forms.adf.engine.backend.formGeneration.BackendFieldElementProcessor(FieldManager, PropertyValueExtractor, Instance<FieldInitializer<? extends FieldDefinition>>)\n  at org.kie.workbench.common.forms.adf.engine.backend.formGeneration.BackendFieldElementProcessor.<init>(BackendFieldElementProcessor.java:0)\n"}},`

Anyway just looking into it, seems it could be missing some dependency? Will let you know asap.

**Comment by romartin** [comment]
Created https://github.com/kiegroup/kie-wb-common/pull/1517

**Pull request merged**
