### PR TITLE
JBPM-8914: Stunner - User task throws exception when you try to move it.

### PR DESCRIPTION
**Pull request by romartin**
Hey @LuboTerifaj 

This is the cherry-pick into `master` of https://github.com/kiegroup/kie-wb-common/pull/3085

See [JBPM-8914](https://issues.redhat.com/browse/JBPM-8914)

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by tomasdavidorg** [comment]
@romartin @LuboTerifaj  Hello, is there anything which blocks this PR to be merged? I can see that the PR for 7.30.x branch is already merged. Thanks.

**Pull request merged**
