### PR TITLE
JBPM-7976: Stunner - Marshallers: nested Sub-Processes are added twice to the parent Process

### PR DESCRIPTION
**Pull request by evacchi**
@krisv @tiagodolphine this should fix the issue

### CODE REVIEW

**Comment by evacchi** [comment]
Jenkins execute full downstream build

**Comment by evacchi** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Yes please @hasys , can you verify this as well? This way @evacchi can also create the PR for `7.14.x`, as this is a blocker... thanks in advance!

**Comment by hasys** [comment]
Hi @romartin, @evacchi, sorry but despite of build is green, there are no built wars in it due to  yesterday's issues in Jenkins configs.

Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @evacchi ,
This is a blocker, so it needs to be present on 7.14.x, please can you cherry-pick it? Tomorrow is the deadline... a bit urgent. 
Remeber there already exist the ticket https://issues.jboss.org/browse/RHPAM-1728
Thanks!

**Pull request merged**
