### PR TITLE
[7.7.x] RHPAM-1010: Stunner - MI SubProcess CompletionCondition is not stored

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin would you mind review this PR. 
Adding @hasys to the thread as usual but I know it's bank holiday in Czech Republic this Thursday and Friday.

**Comment by wmedvede** [comment]
Build timed out
Lets give it another try

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
The "simple build" got Build timed out, and he full one got a "No identified problem"

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
well the compilation is failing, seems that the mainstream is broken...

```
16:36:32 [INFO] -------------------------------------------------------------
16:36:32 [WARNING] COMPILATION WARNING : 
16:36:32 [INFO] -------------------------------------------------------------
16:36:32 [WARNING] /home/jenkins/workspace/kie-wb-common-downstream-pullrequests-7.7.x/upstream-repos/appformer/uberfire-client-api/src/main/java/org/uberfire/client/mvp/UberElement.java:[19,41] org.jboss.errai.common.client.api.IsElement in org.jboss.errai.common.client.api has been deprecated
16:36:32 [INFO] 1 warning
16:36:32 [INFO] -------------------------------------------------------------
16:36:32 [INFO] -------------------------------------------------------------
16:36:32 [ERROR] COMPILATION ERROR : 
16:36:32 [INFO] -------------------------------------------------------------
16:36:32 [ERROR] /home/jenkins/workspace/kie-wb-common-downstream-pullrequests-7.7.x/upstream-repos/appformer/uberfire-client-api/src/main/java/org/uberfire/client/promise/Promises.java:[37,1] cannot find symbol
16:36:32   symbol:   static DEFAULT_RPC_ERROR_CALLBACK
16:36:32   location: class
16:36:32 [ERROR] /home/jenkins/workspace/kie-wb-common-downstream-pullrequests-7.7.x/upstream-repos/appformer/uberfire-client-api/src/main/java/org/uberfire/client/promise/Promises.java:[182,13] cannot find symbol
16:36:32   symbol:   variable DEFAULT_RPC_ERROR_CALLBACK
16:36:32   location: class org.uberfire.client.promise.Promises
16:36:32 [INFO] 2 errors 
```

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
please @wmedvede keep an eye here and let me know when it's ready for checking the war, thanks!!

**Comment by wmedvede** [comment]
and again "Build timed out"

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
@romartin wow, we finally got the war generated. Will be much appreciated if you can take a look an we can hopefully include this in the 7.0.2.

**Comment by evacchi** [comment]
@romartin this has been fixed in #1732 (confirmed) bonus: #1956 because the constraint was not XML escaped

**Comment by romartin** [comment]
Tested manually and it works, the filed is being serialized with no issues. Thanks @wmedvede !

**Pull request merged**
