### PR TITLE
RHPAM-2647 : [GSS](7.z) Errors when building a project are shown to all users

### PR DESCRIPTION
**Pull request by RishiRajAnand**
**RHPAM-2647**: https://issues.redhat.com/browse/RHPAM-2647

**Referenced Pull Requests**:
https://github.com/kiegroup/appformer/pull/1096

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by adrielparedes** [comment]
jenkins do fdb

**Review by Srihari1192 — APPROVED** [review]

**Comment by RishiRajAnand** [comment]
jenkins do cdb

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by adrielparedes** [comment]
jenkins do fdb

**Review by paulovmr — APPROVED** [review]

**Pull request merged**
