### PR TITLE
JBPM-7654: Multiple Selector throws error on edit

### PR DESCRIPTION
**Pull request by jesuino**

### CODE REVIEW

**Comment by jesuino** [comment]
Hello @pefernan - thank you so much for all the coaching today! Here's a proposed solution, it works. What was done is: when the instance has a proxy we look for it, otherwise we just return the object.

Let me know the best way to test this tomorrow and if you think that this is the solution for it. 

Thanks!

**Comment by pefernan** [comment]
@jesuino thank you for the fix, let's add a test and we can merge. let's talk later.

**Comment by jesuino** [comment]
@pefernan Thanks again for your feedback. I added a test that checks that List with non bindable types (in our case Strings) are not passed to BindableProxyFactory.getBindableProxy - it will be called on time on isProxy method, but it should not be called a second time.

Thanks!

**Comment by pefernan** [comment]
@jesuino thank you looks fine for me. I'll trigger downstream build and when green +1 to merge

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by jesuino** [comment]
@pefernan Looks like the test failures are not related to this PR, could you please confirm?

**Comment by pefernan** [comment]
Jenkins execute full downstream build please

**Comment by pefernan** [comment]
@jesuino yes, this are unrelated failures, let's give it one more try

**Comment by jesuino** [comment]
@pefernan the failed tests still does not seem related - I will give it another try to see if it gets green tomorrow

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@ederign @porcelli double green!

**Comment by jesuino** [comment]
could this be merged, @ederign ?

**Pull request merged**
