### PR TITLE
DROOLS-3186: [DMN Designer] Remove Shape BorderSize and Font BorderSize properties

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-3186

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@karreiro Please see https://issues.jboss.org/browse/DROOLS-3195

**Comment by manstis** [comment]
@jomarko Fixed. Thank-you for finding :-)

drools-3186 fixed

**Pull request merged**
