### PR TITLE
RHPAM-2902 - Very similar icons between Task and Embedded Sub-Process

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin, @LuboTerifaj, @domhanak 

it looks like SVG and PNGs have different semantics/usage. PNGs are small icons (toolbox, palette, Diagram Explorer) and SVG used as sub-process markers directly on the canvas, that's why I replaced PNG and _added_ addition SVG for embedded sub-process (since now it is two different things - embedded subprocess icon and embedded subprocess representation on the canvas). Let me know if I did it wrong.

There is a screenshot how it looks like at runtime now:
Screenshot from 2020-05-25 12-43-17

cc @lazarotti

This PR is ready for review. Thank you!

### CODE REVIEW

**Comment by hasys** [comment]
jenkins execute full downstream production build

**Comment by hasys** [comment]
Build is fixed by https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1331

**Comment by hasys** [comment]
jenkins execute full downstream production build

**Comment by domhanak** [comment]
jenkins execute full downstream production build

**Comment by romartin** [comment]
jenkins execute full downstream production build

**Comment by hasys** [comment]
Hi @LuboTerifaj as discussed this PR is ready for review. War file can be dowloaded [here](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/upstream-downstream/job/kie-wb-common.downstream.production/18/artifact/kiegroup_kie-wb-distributions/business-central-parent/business-central-distribution-wars/business-central/target/) and tests are passed in repo build.

Thank you!

**Comment by domhanak** [comment]
@hasys I downloaded the war from your comment, but I am unable to see the new icon.

**Comment by hasys** [comment]
Hi @domhanak, full downstream build was done without my changes, since it is already 7.39, but my changes done on 7.38. Rebased and starting builds again. Sorry for inconvenience.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Full downstream build is green, but already removed because new build stores only last 10 and there where much more runs from Friday.

Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Thank you @domhanak,

@romartin PR is ready for merge, thank you!

**Pull request merged**
