### PR TITLE
RHPAM-2317 - Users cannot find the properties menu unless it's pointed out to them

### PR DESCRIPTION
**Pull request by Josephblt**
https://issues.jboss.org/browse/RHPAM-2317

This adds the possibility of having different labels and tooltips for the docks which was not supported.

This PR depends on this:
Appformer: https://github.com/kiegroup/appformer/pull/832

Video (Updated - Tooltip shows Properties instead of Open properties panel):
https://drive.google.com/file/d/1AbYsbhHG2RfZJjtSz3Kb2cKyQJG6tLsB/view?usp=sharing

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Hello @romartin. Could you please add @jomarko, @kywalker-rh to this PR review? Thanks.

**Comment by jomarko** [comment]
Please ping me when the full. d.b. is green.

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Hello @LuboTerifaj. About the Tooltip. In the other PR there is a comment by @kywalker-rh asking to set the tooltip back to properties. This one: https://github.com/kiegroup/appformer/pull/832#issuecomment-549859039

**Comment by romartin** [comment]
Hey @Josephblt @LuboTerifaj 

As commented before, plz let's focus only on the blocker issues for this PR and just report any other issue that may appear. That's an important task for next release we should deliver during this week, so plz give it top priority.. 

Thanks!

**Comment by romartin** [comment]
Yeah @kywalker-rh 

That's normal... a JIRA ticket, for example some new feature, can potentially affect multiple repositories. 

For example if some requirement in Stunner (`kie-wb-common`) also needs for some improvement on our fundation platform (`appformer`, etc), we'll have to change code in both `appformer` and `kie-wb-common` repositories, so we'll also create 2 PRs, once for the appformer repo and `another` for the `kie-wb-common` one.

Acutally our CI builds handle this, the WAR you tested, generated in any of both PRs, as a result for the builds, will contains the changes in both modules too.

It also means, we'll have to merge both at sime time, that's why we specify this usually on the PR's description (see this one, it says "depens on")

Hope it helps!

**Comment by Josephblt** [comment]
Hello @kywalker-rh, @romartin summed it up pretty well. Thanks.

**Comment by kywalker-rh** [comment]
Thanks for the description @romartin! That makes perfect sense. I wanted to make sure I understand it all since I'm new to the process.

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Two more related issues reported:
https://issues.jboss.org/browse/JBPM-8904
https://issues.jboss.org/browse/DROOLS-4772

**Comment by LuboTerifaj** [comment]
One more issue I've found: https://issues.jboss.org/browse/JBPM-8915

**Pull request merged**
