### PR TITLE
KOGITO-395 BPMN Serialization reusing ID

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin, @LuboTerifaj, @domhanak, @krisv 

this PR removes all ID without use from BPMN file in KOGITO (Business Central is not affected we have separate jira issue for it). Two ids are still generates on every save, but they are used somewhere, so I didn't remove it, we will handle it as separate jira issue.

### This PR removes IDs for following elements
* Documentaion
* LaneSet
* ioSpecification
* inputSet
* outputSet
* dataInputAssociation
* DataOutputAssociation
* Assignment
* TimerEventDefinition
* CompensateEventDefinition
* SignalEventDefinition
* errorEventDefinition
* completionCondition
* messageEventDefinition
* escalationEventDefinition
* conditionalEventDefinition
* terminateEventDefinition
* MultiInstanceLoopCharacteristics
* Potential Owner (User Task → Actor property)
* FormalExpression tags such as:
    * CompletionCondition
    * ConditionExpression
    * Condition
    * TimeDate
    * TimeDuration
    * from
    * to

ID's removed because they are not used and regenerated on every save and it creates a lot of nose and make impossible to see difference between two BPMN files.

You can check that IDs for mentioned elements never used in whole BPMN file. Just locate any mentioned element, copy ID and search it in the BPMN file. You will find just one occurrence 

### Element where IDs still regenerated on every save because they used somewhere else

* Definition tag (root tag), also used in 
    * Definition → Relationship → Target (XML)
    * Definition → Relationship → Source (XML)
* Message tag, also used in
    * messageEventDefinition tag as messageRef attribute

Listed elements will be fixed as separate jira issue.

I tested this PR with https://github.com/kiegroup/kogito-travel-agency-tutorial/tree/master/01-kogito-travel-agency I opened all 3 files in Kogito Webapp (VS Code plugin doesn't work to me again) and slightly modified it (just moved a node). Than saved new file versions without IDs to the test project and was able to pass all tests, compile and start the application. Also I did some REST request and all looks good to me.

@krisv can I ask you to confirm that if IDs are not used anywhere in the file - they are useless and can be removed?

So this PR is ready for review. Thank you!

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
jenkins execute full downstream build

**Comment by domhanak** [comment]
Looks good to me.
I created two new identical BPMN files in VSCode.
1. saved both
2. edited second one and diffed them.
3. Only id change I see is source and target as mentioned in comment.

Looks good to me. Thanks @hasys free to merge when FDB passes.

**Comment by hasys** [comment]
Hi @domhanak, it is green already. Thank you!

**Comment by krisv** [comment]
@domhanak went over the list of removed ids and I agree, I believe these are not referenced (at least not in the use cases we currently target afaik).

**Pull request merged**
