### PR TITLE
[7.3.x] RBPMS-4804: The new process editor cannot make straight lines

### PR DESCRIPTION
**Pull request by romartin**
Hey @manstis @hasys 
This is the cherry-pick for https://github.com/kiegroup/kie-wb-common/pull/1191 into 7.3.x branch. I'm doing it as @Josephblt is not present this week and this must be on the next release.
Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
@manstis oh I forget I can "request" for reviews now, yeah! feeling the power! xD

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin, @manstis, I need binaries to test PRs locally. Please, execute Full Downstream builds, it will help me to verify PRs faster.

**Comment by romartin** [comment]
here they're @hasys !! :)

**Comment by manstis** [comment]
Please check with @mbiarnes 7.3.x is not frozen.. this will need to now target 7.4.x.

**Comment by romartin** [comment]
Closing this pull request as this branch has been already frozen.

**Pull request closed without merging**
