### PR TITLE
[7.7.x] DROOLS-2629 : Complex enumerations are not selected in BRL multi value constraint (#1890)

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-2629

(cherry picked from commit ef1fe824ae41a9e0b4f940e1f9b2d1e1814ffc62)

Fix is in two PRs:
https://github.com/kiegroup/kie-soup/pull/49
https://github.com/kiegroup/kie-wb-common/pull/1913

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@Rikkola Please let me know when these 2 PRs are green so I can merge for 7.0.2.GA.

**Comment by Rikkola** [comment]
Jenkins please retest this.

**Comment by Rikkola** [comment]
@manstis Ok. Both are green now.

**Pull request merged**
