### PR TITLE
DROOLS-3214: [DMN Designer] Function: Add parameter data-types

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-3214

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Oeeee. what browser?

It doesn't do that for me in Chrome.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
@manstis.. I was testing in Safari 12.

However my guess is that it's not a specific Safari issue. Sometimes the `.kie-dmn-parameters-container` has the `[data-i18n-prefix="ParametersPopoverViewImpl."` as a parent, and sometimes it doesn't (as a could check in the element inspector). I *think* that I saw the `NameAndDataTypePopoverImpl` as a parent (instead of the `ParametersPopoverViewImpl`)..

That would explain why the `.kie-dmn-parameters-container` (from the [ParametersPopoverViewImpl.less](https://github.com/kiegroup/kie-wb-common/blob/99dd7a589fcbeacf813d91382b5365bd59c508aa/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/function/parameters/ParametersPopoverViewImpl.less#L26-L33)) was not applied. But I'm just guessing.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
@karreiro @manstis yes, that overlay is not safari specific issue. Can bee sen on other browsers too. Filed as [DROOLS-3221](https://issues.jboss.org/browse/DROOLS-3221)

**Comment by jomarko** [comment]
@manstis @tarilabs please have a look on this [commit](https://github.com/kiegroup/drools/pull/2123/commits/7ace7894da042e834553302dcb4e169b1bccb99b). The used DMN model was created using this PR, however the test throws these errors:
```
testFunctionInvocationFunctionWithContextInside[true](org.kie.dmn.core.DMNRuntimeTest)  Time elapsed: 0.176 sec  <<< ERROR!
java.lang.IllegalStateException: [Message [id=1, kieBase=defaultKieBase, level=ERROR, path=invocationFunctionWithContextInside.dmn, line=-1, column=0
   text=Unable to compile DMN model for the resource]]
	at org.kie.dmn.core.util.KieHelper.createJar(KieHelper.java:60)
	at org.kie.dmn.core.util.KieHelper.createAndDeployJar(KieHelper.java:43)
	at org.kie.dmn.core.util.KieHelper.getKieContainer(KieHelper.java:36)
	at org.kie.dmn.core.util.DMNRuntimeUtil.createRuntime(DMNRuntimeUtil.java:61)
	at org.kie.dmn.core.DMNRuntimeTest.testFunctionInvocationFunctionWithContextInside(DMNRuntimeTest.java:137)

testFunctionInvocationFunctionWithContextInside[false](org.kie.dmn.core.DMNRuntimeTest)  Time elapsed: 0.085 sec  <<< FAILURE!
java.lang.AssertionError: DMNMessage{ severity=ERROR, type=TYPE_DEF_NOT_FOUND, message='Unable to resolve type reference 'tForecast' on node 'compute forecast'', sourceId='_19C7C980-D4B8-4CD3-972B-86371F42A387', exception='', feelEvent=''}
DMNMessage{ severity=ERROR, type=TYPE_DEF_NOT_FOUND, message='Unable to resolve type reference 'tWeather' on node 'current weather'', sourceId='_D667D3E7-83CF-4D85-A04C-B768FE680DCE', exception='', feelEvent=''}
DMNMessage{ severity=ERROR, type=TYPE_DEF_NOT_FOUND, message='Unable to resolve type reference 'tForecast' on node 'forecast'', sourceId='_7DEA7BC3-3F6D-4EE7-AD57-217DF69396C5', exception='', feelEvent=''}
DMNMessage{ severity=ERROR, type=TYPE_DEF_NOT_FOUND, message='Unable to resolve type reference 'tWeather' on node 'compute forecast'', sourceId='_6F827F60-01D0-45E6-8899-C68A546E46F4', exception='', feelEvent=''}
DMNMessage{ severity=ERROR, type=TYPE_DEF_NOT_FOUND, message='Unable to resolve type reference 'tWeather' on node 'forecast'', sourceId='_DC8D7710-67C5-453F-A3C9-E282CCD7E819', exception='', feelEvent=''}
```

However I am not sure if the DMN I provided is correct, as syntactically so logically.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@jomarko On "unmarshalling" the 1.1 file the parameter `typeRef`s are `feel:number` whereas I would expect them to be simply `number` (as we convert to 1.2). If I manually change their typeRef to `number` (dropping the `feel` prefix) the import of 1.1 correctly shows the parameters as "number" in the UI.

@tarilabs Is this a marshalling error? Opening the 1.1 file gives `typeRef`s of `feel:number` whereas we're expecting 1.2 encoded built-in-types i.e. `number`?

**Comment by manstis** [comment]
@jomarko I've finished my analysis of your reported problems.

IDK what the outcome of your talks with @tarilabs regarding the file generated by our editor is.

The problem with the import of a 1.1 file seems to be in the marshalling, but need @tarilabs to confirm.

**Comment by manstis** [comment]
@tarilabs I propose something like this in `QNamePropertyConverter`:-
```
public static QName wbFromDMN(final javax.xml.namespace.QName qName) {
    if (Objects.isNull(qName)) {
        return null;
    }
    if (Objects.equals(qName.getPrefix(), Namespace.FEEL.getPrefix())) {
        return new QName(QName.NULL_NS_URI, qName.getLocalPart());
    }
    return new QName(qName.getNamespaceURI(),
        qName.getLocalPart(), 
        qName.getPrefix());
}
```

**Comment by manstis** [comment]
@tarilabs New commit added containing my proposal for the `QName` conversion.

@jomarko New commit also contains a fix for "drilling down" into invocation parameter properties.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@tarilabs You explained correctly; but did not fully understand my explanation of the issue.

When opening a DMN1.1 file the XML contains {{feel:number}}, which remains {{feel:number}} in the KIE DMN model (_your_ model). The marshaller for the UI kept {{feel:number}} however the UI DMN model now expects DMN1.2 encoding; so just {{number}}. I included an additional commit on this PR to make the {{QNamePropertyConverter}} always output DMN1.2 {{QName}} for the UI's use.

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
