### PR TITLE
JBPM-7381: Stunner - Clear diagram action is not working (#1924)

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit 286763a75a3d0900935f90b9864320dad9d24590)

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin @hasys this is the peer PR for the already merged into 7.7.x #1924 
would you mind review and merge?
Thanks.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Pull request merged**
