### PR TITLE
RHPAM-1706: Stunner - Diagram of running instance doesn't highlight nodes

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin @tiagobento @hasys ,
would you mind review this PR?

Note: as we spoke in the Stunner meeting the PR is a quick fix for letting BPMN work well. So I've basically added a simple extension to let BPMN work in the way it worked before, and CM work in with the code that was commented. So CM won't fail (in case it could fail because of the commented code) and BPMN will work as it did.

I've checked it in 7.14.x branch and the fix works well, i.e., BPMN is woking well.
Regarding CM I could see that the case management editor is not working in 7.14.x branch. Independently of the changes on this PR CM is not working in 7.14.x. As soon as CM file is create the following error is rasied "Activity not found" and the case management editor is not opened.

I've chatted with @xiezhang7  and it seems like the following PR https://github.com/kiegroup/kie-wb-common/pull/2272 fixes CM that in master. But I don't see this PR in 7.14.x, and not sure if it should/must be merged a the point we are now.

Anyway, my PR must still be merged to get the "highligted nodes issue fixed"

**Comment by romartin** [comment]
Great thanks @wmedvede . Although the CM is broken for the next release, that's not a priority, so let's go ahead with this. Please @xiezhang7, as commented, try to fix this on master branch when possible.
Thanks!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
Hi @hasys , it seems like we have the two greens now.
Would you mind take a look please since this is high  prioritary.

Thanks!

**Comment by xiezhang7** [comment]
Thanks @wmedvede !
@romartin I think this pull request also fixes case modeler, should I cherry-pick the commit and create a pull request to master?

**Comment by wmedvede** [comment]
Hi, @romartin @xiezhang7 , yes I think we should cherry-pick this into master to keep both branches synchronized but also given the comments/pointers we have there that highlights that a more polished solution is pending. I didn't it yet since given the hurries for the 7.14.x.
But it'l be much appreciated @xiezhang7 if you can manage to cherry-pick this into master.
Thanks!

**Comment by wmedvede** [comment]
@xiezhang7 Ideally we should have it in before this Friday EOD, if you find any issue or can't take it please let me know and I can do it.

**Comment by xiezhang7** [comment]
Thanks @wmedvede .

**Pull request merged**
