### PR TITLE
[Please do not merge] AF-1113: Display Git external URLs on Project Settings

### PR DESCRIPTION
**Pull request by tiagobento**
See: https://issues.jboss.org/browse/AF-1113

feature gif

### CODE REVIEW

**Comment by tiagobento** [comment]
@porcelli Can you please take a look? Should I open a PR in `master` too?

**Comment by porcelli** [comment]
please yes, open to master

**Comment by tiagobento** [comment]
@porcelli Opened https://github.com/kiegroup/kie-wb-common/pull/1558

**Comment by tiagobento** [comment]
@porcelli Do you think we should apply @srambach's suggestion to this PR? See the last comment: https://issues.jboss.org/browse/AF-1113

**Comment by porcelli** [comment]
@tiagobento yes i think so. it's good to follow UX :)

ps: the `default` would be `ssh`

**Comment by ederign** [comment]
@tiagobento this will be ported also for master right?

**Comment by tiagobento** [comment]
@ederign Yes, [there's an open PR](https://github.com/kiegroup/kie-wb-common/pull/1558) targeting `master` as well.

**Comment by tiagobento** [comment]
Will open another one targeting 7.7.x properly.

**Pull request closed without merging**
