### PR TITLE
Ala Maven test improvements

### PR DESCRIPTION
**Pull request by cristianonicolai**
Remove test dependency to external git repositories, replacing by local git repos created locally
Use simple Maven projects to speed up build time

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/657

**Comment by cristianonicolai** [comment]
@porcelli @wmedvede could you take a look on this?

**Comment by porcelli** [comment]
@cristianonicolai sorry that you invested on this, but `soon` we'll have the maven build merged - and we'll use it for Guvnor ALA =/

**Comment by cristianonicolai** [comment]
@porcelli not worth merging it at least for now?  It could still be used as a reference in our code history so that we avoid cloning remote git repositories in the future, as it does take some considerable time to clone and build.

**Pull request merged**
