### PR TITLE
JBPM-7825 (RHPAM-1048): Stunner - Intermediate Throwing Event can have more than one outgoing flow (#1859)

### PR DESCRIPTION
**Pull request by Josephblt**
Issue:
[RHPAM-1048](https://issues.jboss.org/browse/RHPAM-1048)
[JBPM-7825](https://issues.jboss.org/browse/JBPM-7285)

Cherry-pick:
commit 9eafbc4

7.7.x Branch PR's:
kiegroup/kie-wb-common
#1859

Master PR's:
kiegroup/kie-wb-common
[this one](https://github.com/kiegroup/kie-wb-common/pull/1883)

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
@romartin Hi. Could you review this please? Thanks

**Comment by elguardian** [comment]
wrong title... it should be JBPM-7285

**Comment by Josephblt** [comment]
> wrong title... it should be JBPM-7285

Sorry about that. Fixed it.

**Pull request merged**
