### PR TITLE
GUVNOR-3168 GUVNOR-3167 [DMN Editor] Write unmarshaller marshaller 

### PR DESCRIPTION
**Pull request by tarilabs**
Backport to 72x of #986

### CODE REVIEW

**Comment by tarilabs** [comment]
@manstis can you merge this one please?

**Comment by manstis** [comment]
When the related https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/501 is green, yes.

**Comment by tarilabs** [comment]
There's no reason to wait, this downstream build incorporated the -bootstrap downstream build, you can verify this in the Jenkins log of *this* downstream build 33:
```

Upstream repositories builder for PR builds started.
Working with PR: https://github.com/kiegroup/kie-wb-common/pull/1037
PR source branch: GUVNOR-3168-72x
PR target branch: 7.2.x
Cleaning-up directory /home/jenkins/workspace/kie-wb-common-downstream-pullrequests-7.2.x/upstream-repos
GitHub repositories that will be cloned and build:
	git://github.com/errai/errai:4.0.x:4.0.x-pr-build
	git://github.com/uberfire/uberfire:1.2.x:1.2.x-pr-build
	git://github.com/dashbuilder/dashbuilder:0.8.x:0.8.x-pr-build
	git://github.com/kiegroup/droolsjbpm-build-bootstrap:pull/501/merge:pr501-GUVNOR-3168-72x-merge
	git://github.com/kiegroup/droolsjbpm-knowledge:7.2.x:7.2.x-pr-build
	git://github.com/kiegroup/drools:7.2.x:7.2.x-pr-build
	git://github.com/kiegroup/optaplanner:7.2.x:7.2.x-pr-build
	git://github.com/kiegroup/jbpm:7.2.x:7.2.x-pr-build
	git://github.com/kiegroup/droolsjbpm-integration:7.2.x:7.2.x-pr-build
	git://github.com/kiegroup/kie-uberfire-extensions:7.2.x:7.2.x-pr-build
	git://github.com/kiegroup/guvnor:7.2.x:7.2.x-pr-build
	git://github.com/kiegroup/kie-wb-playground:7.2.x:7.2.x-pr-build
```

**Comment by tarilabs** [comment]
thanks @manstis :+1:

**Pull request merged**
