### PR TITLE
AF-1704: Case Management & Experimental integration

### PR DESCRIPTION
**Pull request by pefernan**
- Solved problems on Experimental Features Editor caused by using same names & descriptions
- API changes on Stunner Resource types to solved the issue with Case Management Resource Type, which wasn't well registered to the experimentals engine.

@romartin @hasys could you please take a look?

This is part of an ensemble, please merge with:
https://github.com/kiegroup/appformer/pull/527
https://github.com/kiegroup/kie-wb-common/pull/2272

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@hasys trying downstream on the appformer pr

**Comment by pefernan** [comment]
double green!

**Comment by hasys** [comment]
Hi @pefernan, it is double green, but war files for tests not generated, not sure what is it :(

@mareknovotny do you know should we just re-run build or it is something bigger?

**Comment by ederign** [comment]
@hasys when you review this, could you please also take a look on https://github.com/kiegroup/appformer/pull/527#pullrequestreview-175036199

**Comment by mareknovotny** [comment]
@hasys I looked at PR job builder and it seems @jhrcek already merged kie-jenkins-script PR for job builder change where the BC consolidation changes the wars, but AFAIK that PRs for BC consolidations are not still merged so now every PR builder results will miss the kie-wb*.wars as the config is set to look for business-central*.wars.

**Comment by jhrcek** [comment]
FYI: to make kie-wb be archived again we would need to merge this revert: 
https://github.com/kiegroup/kie-jenkins-scripts/pull/375
But waiting for confirmation from others before we do that.

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@hasys not double green but wars are there :D

**Comment by hasys** [comment]
Hi @pefernan,

thank you, downloading. Just to be sure, what is fixed in UI by this changes, it is not clear to me from PR description?

**Comment by pefernan** [comment]
@hasys it fixes two problems:
1.- the problem of not enabling the case editor when enabling its experimental feature
2.- inheritance problem on stunner resource types that was causing issues when integrating the case management resource type with experimentals. It was impossible to disable the case management resource type experimental feature.

**Comment by hasys** [comment]
Thank you @pefernan, works as a charm! Will take a quick look at the code now.

## Tested scenarios
### Experimental feature disabled
:heavy_check_mark: it is not possible to create Case file, 
:heavy_check_mark: existing files opens with Others editor
:heavy_check_mark: no Experimental preferences displayed in Workbench settings

### Editor & Resource were enabled, but Experimental feature disabled
:heavy_check_mark: it is not possible to create Case file, 
:heavy_check_mark: existing files opens with Others editor
:heavy_check_mark: no Experimental preferences displayed in Workbench settings

### Both Editor and Resource **dis**abled
:heavy_check_mark: it is **not** possible to create Case file, 
:heavy_check_mark: existing files opens with **Others** editor

### Both Editor and Resource **e**nabled
:heavy_check_mark: it is **possible** to create Case file, 
:heavy_check_mark: existing files opens with **Case Management Editor**

### **Editor e**nabled and **Resource dis**abled
:heavy_check_mark: existing files opens with **Case Management Editor**,
:heavy_check_mark: it is **not** possible to create Case file

### **Editor dis**abled and **Resource e**nabled
:heavy_check_mark: existing files opens with **Others** editor,
:heavy_check_mark: it is **possible** to create Case file

### BPMN project and Case Project.
I found this unrelated issue:
@xiezhang7, @tiagodolphine when Editor enabled I can see this editor not only in Case Project, but also in BPMN project. See picture below.

@tsurdilo also I can see Case Definition (legacy) there. See picture below.

image

**Comment by romartin** [comment]
Hey @pefernan , please feel free to merge this one by yourself when ready, as it depends on other PRs which I'm not sure if are ready to merge. Anyway great job and thanks a lot for this! :+1:

**Comment by pefernan** [comment]
@romartin let's try to get second green....

Jenkins execute full downstream build

**Comment by pefernan** [comment]
@romartin beer++;

**Pull request merged**
