### PR TITLE
[7.52.x] RHPAM-3250: Stunner - Not all illegal characters are removed from Data Object name

### PR DESCRIPTION
**Pull request by inodeman**
**Thank you for submitting this pull request**

**JIRA**: [JBPM-9242](https://issues.redhat.com/browse/JBPM-0000)

**Referenced Pull Requests**:
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://donwnload.here/something)

**VS Code**: [plugin](https://donwnload.here/something)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by inodeman** [comment]
Hi @romartin please find this PR for 7.52.x

**Comment by romartin** [comment]
Hey @LuboTerifaj 
This is the cherry-pick for https://issues.redhat.com/browse/JBPM-9242 
Can you please quickly verify?
Thansk!

**Comment by inodeman** [comment]
Hi @LuboTerifaj @romartin please find artifacts here. I tested and works as expected. https://drive.google.com/drive/folders/1dfkyqd6yi66O0NmnegLper_WqR-d1CHy?usp=sharing

**Review by romartin — APPROVED** [review]

**Review by LuboTerifaj — APPROVED** [review]
It looks good to me. Thanks!

**Pull request merged**
