### PR TITLE
JBPM-8620: Stunner - Cannot copy-paste with service tasks

### PR DESCRIPTION
**Pull request by romartin**
Hey @hasys 

See [comment](https://issues.jboss.org/browse/JBPM-8620?focusedCommentId=13751073&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13751073) in [JBPM-8620](https://issues.jboss.org/browse/JBPM-8620)

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin, works good, thank you. Just interesting: there are some changes on DMN and CM side, how can I test changes there? Should we ask @manstis or @xiezhang7 also take a look?

Also rerunning build to report failing tests, otherwise looks good to me, thank you!

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @hasys , good point. In general reviewers for CM and DMN are @LuboTerifaj  and @jomarko respectively, so asking for review if you guys agree :+1:

**Comment by manstis** [comment]
Jenkins please retest this.

@romartin I found, locally, an _enforcer_ issue on this PR following the `ip-bom` related changes.

**Comment by manstis** [comment]
@romartin Could you please ping me when this is ready for testing.

(I've looked through the changes and they LGTM.. but wanted to manually test DMN).

**Comment by romartin** [comment]
ok thanks @manstis , will let you know. About the enforcer issue on this PR, can I try to fix at this point, or is the master already broken? Thx in adv

**Comment by manstis** [comment]
@romartin `master` is still generally broken.. but we're getting closer to having it fixed.

**Comment by romartin** [comment]
@manstis thanks a lot!! lemme know if I can help too, np!! :+1:

**Comment by jomarko** [comment]
@manstis I was able to build locally when I used `-Denforcer.skip`.

I tried to copy all DMN node types. It works without an exception. However the content/expression  of `Decision` and `BKM` is not copied. Is that same even before this PR?

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
@jomarko I think failure to copy the _content_ of a `Decision` and `BusinessKnowledgeModel` is covered by https://issues.jboss.org/browse/DROOLS-2214

**Comment by romartin** [comment]
@manstis @jomarko thanks guys for the review! 

About the concrete issue on DMN I'm also agree with Mike, it looks not strictcly related to this work, so better addressing it in another PR. Anyway, as far as I remember once cloning a node, Stunner does the deep clone, so it clones recursively all properties for the beans, is that correct @tiagodolphine ? So not really sure yet why those two concrete objects on the DMN beans are not being cloned as well. I think we do this clone via "adapters", so once those properties can be read/write via the Stunner adapters, that should work out-of-the-box.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @xiezhang7, can I ask you to review CM part of this PR? Since @LuboTerifaj is on PTO this week and this issues is part of the 7.4.1 release. Thank you!

**Comment by xiezhang7** [comment]
> Hi @xiezhang7, can I ask you to review CM part of this PR? Since @LuboTerifaj is on PTO this week and this issues is part of the 7.4.1 release. Thank you!

@hasys sure.

**Comment by xiezhang7** [comment]
> Hi @xiezhang7, can I ask you to review CM part of this PR? Since @LuboTerifaj is on PTO this week and this issues is part of the 7.4.1 release. Thank you!

@hasys The CM part looks good. CM works as expected. Thanks.

**Comment by romartin** [comment]
Please @hasys or @LuboTerifaj , can you do the review for this? This fix is expected for next 7.4.1 release, so I need to have this merged into master before ASAP. 
Thanks in advance!

**Pull request merged**
