### PR TITLE
BAQE-400: Remove unused imports

### PR DESCRIPTION
**Pull request by jomarko**
Ensemble with:
- https://github.com/kiegroup/jbpm-designer/pull/758
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/726
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/301
- https://github.com/kiegroup/drools-wb/pull/840

### CODE REVIEW

**Comment by jomarko** [comment]
@romartin would you mind have a look on whole ensemble?

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins please retest this

**Pull request merged**
