### PR TITLE
AF-1669: Support slashes in branch names

### PR DESCRIPTION
**Pull request by paulovmr**
Part of an ensemble:
* https://github.com/kiegroup/appformer/pull/511
* https://github.com/kiegroup/kie-wb-common/pull/2228

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins retest this

jenkins execute full downstream build

**Comment by ederign** [comment]
jenkins retest this

**Comment by ederign** [comment]
@domhanak could you please assign to someone from qe?

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by barboras7** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins retest this

**Pull request merged**
