### PR TITLE
KOGITO-4530: [DMN Designer] Boxed Expressions - Decision Tables - HiDPI is not working as expected

### PR DESCRIPTION
**Pull request by danielzhe**
**JIRA**: [KOGITO-4530](https://issues.redhat.com/browse/KOGITO-4530)

New PR with new approach, affecting only DMN side, forcing HiDPI only for Kogito.

**VS Code**: [plugin](https://drive.google.com/file/d/1RTr0Ko-W2FejabZ5-YbBgf0n9P_WiJ1X/view?usp=sharing)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by danielzhe** [comment]
FYI: @romartin 

If you can check it in Mac: @ederign

**Comment by tiagobento** [comment]
Hi @danielzhe! I know you didn't tag me directly but I received an email about this issue and just tested it! I can confirm that it works and the Decision Tables are in HD now 😎

**Comment by romartin** [comment]
oh @danielzhe , honestlly this solution looks MUCH better for me, also really straight-forward, looks good to me yeah! :+1: 

For me just missing some quick test case to ensure this flag is always set on the entry point class, and that's it! Nice solution for now :+1: 

Thx

**Comment by danielzhe** [comment]
Thank you, @tiagobento!

Yes, I gonna make a test for it now that is confirmed that it work in Mac. Thank you, @romartin !

**Review by karreiro — APPROVED** [review]
Thank you, @danielzhe!

**Comment by jomarko** [comment]
QE has no resources to check this change. Please proceed without QE review.

**Comment by karreiro** [comment]
Jenkins retest this.

**Comment by karreiro** [comment]
@danielzhe May I proceed with the merge as soon as we get the CI green? This flag will be removed by https://issues.redhat.com/browse/KOGITO-5006, so I personally believe we don't need to unit test the `DMNKogitoCommonEntryPoint` flag.

**Comment by karreiro** [comment]
Jenkins retest this.

**Comment by danielzhe** [comment]
I agree with you, @karreiro . Also I'm facing some issues trying to mock `LienzoCore`, because `DMNKogitoCommonEntryPoint` uses PowerMockito as test runner and I'm unable to test `LienzoCore` with that.

**Comment by karreiro** [comment]
Jenkins retest this.

**Comment by karreiro** [comment]
Jenkins retest this.

**Comment by karreiro** [comment]
Jenkins retest this.

**Comment by danielzhe** [comment]
Hi, @tiagobento ! It's basically the same PR, but for non-kogito editors that you approved here: https://github.com/kiegroup/kogito-editors-java/pull/12
QE doesn't have time for check this one.

**Comment by danielzhe** [comment]
Jenkins retest this.

**Comment by karreiro** [comment]
Closed in favor of https://github.com/kiegroup/kie-wb-common/pull/3632 + https://github.com/kiegroup/kogito-editors-java/pull/12 - thank you, @danielzhe!

**Pull request closed without merging**
