### PR TITLE
DROOLS-2423: [DMN Designer] Clear command caches context entries

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-2423

This PR also includes fixes for:

- https://issues.jboss.org/browse/DROOLS-2424

@jomarko Unit Tests are to follow; however if you want to give the fixes an early check it'd be great.

### CODE REVIEW

**Comment by manstis** [comment]
Some Unit Tests in second commit... more to follow.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@jomarko This PR now includes all Unit Tests. Did you want to approve again?

Furthermore was you able to also test the other JIRA that this PR fixes?

**Comment by jomarko** [comment]
@manstis please provide explicit list of jiras this should fix, I will have a look one more time then.

**Comment by manstis** [comment]
@jomarko Hi, it's the three listed in the PR description (first comment). Thanks.

**Comment by manstis** [comment]
@jomarko Thanks for spending more time looking at this PR. I appreciate it.

Could you agree to merge for just DROOLS-2423 and DROOLS-2424; leaving DROOLS-2425 unresolved?

**Pull request merged**
