### PR TITLE
[8.0.x] JBPM-5429: AssigneeEditor should not appear in the form-modeler.

### PR DESCRIPTION
**Pull request by pefernan**
This PR fixes a smaill issue introduced by previous commit.

@jsoltes could you please review?

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by porcelli** [comment]
@pefernan mind check the conflicts?

**Comment by pefernan** [comment]
@porcelli done

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
@manstis could you please merge it?

**Pull request merged**
