### PR TITLE
DROOLS-3438: Unify Cell Dom Element factories

### PR DESCRIPTION
**Pull request by jomarko**
Ensemble together with:

- kiegroup/appformer#683
- kiegroup/drools-wb#1120

### CODE REVIEW

**Comment by manstis** [comment]
During testing I discovered this: https://issues.jboss.org/browse/DROOLS-3895

**Comment by jomarko** [comment]
@manstis @kkufova @gitgabrio please re-review.

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@manstis please merge when you have a moment. Or do we need to wait for 7.21.0.Final is out?

**Pull request merged**
