### PR TITLE
[7.3.x] [JBPM-5544] Text displayed in the model now support auto-wrap

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
@romartin This is a cherry pick of the commit that was merged into master into 7.3.x. Should I merge it into any other tags?

### CODE REVIEW

**Comment by manstis** [comment]
@romartin @Christopher-Chianelli AFAIK there will be no 7.4.x branch.. @mbiarnes might know.

@etirelli Sorry to drop your name.. is there a roadmap for releases? Is 8.0 next or do we keep adding to the 7.x series until the things we consider essential for 8.0 are completed?

**Comment by romartin** [comment]
okk thx @manstis , let's wait for confirmations too :)

**Comment by manstis** [comment]
@Christopher-Chianelli You really need to see some of these ```kie-wb-common``` PRs through to completion! Can this be merged? Should we kick-off another Jenkins build in case this PR is stale?

**Comment by Christopher-Chianelli** [comment]
@mantis This can be merged; the build will fail if the wildfly-dist property haven't been updated though. I say kick off the Jenkins build after the PR for wildfly-dist has been merged.

**Comment by Christopher-Chianelli** [comment]
Jenkins execute full downstream build

**Comment by Christopher-Chianelli** [comment]
Jenkins please retest

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Pull request merged**
