### PR TITLE
[7.3.x] JBPM-6283: Changing binding in the fields resets all properties to default values

### PR DESCRIPTION
**Pull request by pefernan**
Copy of #1126

@jsoltes could you review?

Closed the previous PR due to conflicts (https://github.com/kiegroup/kie-wb-common/pull/1129).

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
@hasys could you review this?

**Comment by jsoltes** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
@hasys ...and this one please!

**Pull request merged**
