### PR TITLE
JBPM-9351, JBPM-9348: BPMN Editor - Issues around Generic Service Task

### PR DESCRIPTION
**Pull request by romartin**
Hey @LuboTerifaj 

This PR fixes two **high priority issues**, please consider it's review as soon as possible.

**JIRAs**
- https://issues.redhat.com/browse/JBPM-9351:  Generic Service task creation disables process editing (BLOCKER)
- https://issues.redhat.com/browse/JBPM-9348: Cannot morph from/to subprocess or business rule tasks into service tasks (Critical)

Thanks!!

### CODE REVIEW

**Comment by romartin** [comment]
jenkins do fdb

**Comment by romartin** [comment]
jenkins do cdb

**Review by LuboTerifaj — APPROVED** [review]
Hello @romartin ,

thank you for the fix!

It looks good to me.

**Comment by romartin** [comment]
thanks @LuboTerifaj !

**Review by handreyrc — APPROVED** [review]
@romartin Great Job!
It fixes the issues.
Thanks

**Pull request merged**
