### PR TITLE
JBPM-8370: Stunner - Add marshaller test cases for Multiple Instance sub-process

### PR DESCRIPTION
**Pull request by LuboTerifaj**
Marshaller test cases for Multiple Instance sub-process.

Old marshaller has a bug, therefore one test is ignored.
For more information see: https://issues.jboss.org/browse/JBPM-8467

@wmedvede , @hasys can you have a look please?

Thanks!

### CODE REVIEW

**Comment by hasys** [comment]
Hi @LuboTerifaj, looks good to me, just please consider [comment](https://github.com/kiegroup/kie-wb-common/pull/2616#issuecomment-492613808) about https://github.com/hasys/kie-wb-common/commit/46e3d5891eb823432197ddf6a380146b5620f7ea to add also to this PR.

Thank you!

**Comment by LuboTerifaj** [comment]
@hasys ready to review again, thanks!

**Comment by LuboTerifaj** [comment]
Hi @romartin , this is ready to merge, thanks!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins please retest this

**Pull request merged**
