### PR TITLE
JBPM-8581 Stunner - Service Task is not usable at runtime

### PR DESCRIPTION
**Pull request by treblereel**
JIRA: https://issues.jboss.org/browse/JBPM-8581

### CODE REVIEW

**Comment by treblereel** [comment]
@romartin

**Comment by romartin** [comment]
Hey @hasys @LuboTerifaj added you both as reviews, because both have been involved on this, up to you who/how to mange this review, np! Thanks guys!

**Comment by romartin** [comment]
Please @treblereel , the build failed due to a test case failed, please fix it and fire the builds to generate all artifacts once done, so we can start the review and testing for this.
Thanks!

**Comment by treblereel** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin, @treblereel, can I ask you to provide some examples how to test it with WebService to speed up testing?

**Comment by romartin** [comment]
Hey @hasys I don't have any example TBH... do you have some @treblereel ?

**Comment by romartin** [comment]
Sounds great @hasys , it helps a lot, thanks for letting us move this forward! :+1: 
Thanks also @treblereel for the good job! :+1:

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Pull request merged**
