### PR TITLE
Stunner - New Marshallers: Process should use Package.DEFAULT_PACKAGE when appropriate

### PR DESCRIPTION
**Pull request by evacchi**
fix exception when process is created in the default package

@romartin @hasys please take a look

### CODE REVIEW

**Comment by evacchi** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Ohh, sorry @evacchi, full downstream build is already removed.

Jenkins execute full downstream build

**Comment by evacchi** [comment]
great @hasys 
@romartin this is ready to go yay

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins please retest this

**Pull request merged**
