### PR TITLE
DROOLS-5743 : Performing test is slow in Business central

### PR DESCRIPTION
**Pull request by Rikkola**
Revert "DROOLS-5458 : Project broken after test scenario run with possibly a class-loading issue"

DROOLS-5743 : Performing test is slow in Business central

This reverts commit 04764c519223089c0fc16c6824e0d1a94ceeeee6.

**JIRA**: [DROOLS-5743](https://issues.redhat.com/browse/DROOLS-5743)

**Referenced Pull Requests**:
* https://github.com/kiegroup/kie-wb-common/pull/3458
* https://github.com/kiegroup/drools-wb/pull/1434

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Review by yesamer — APPROVED** [review]
Approved!

**Comment by yesamer** [comment]
Asked @karreiro to review it in order to have 2 eng. approvals

**Review by karreiro — APPROVED** [review]
Thank you, @Rikkola!

**Review by tomasdavidorg — APPROVED** [review]

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers Can I get a merge please.

**Comment by manstis** [comment]
@Rikkola Do I need worry about the failing "Maven Build (8)"?

I see it passed on the related PR (do these check represent FDBs? if so it passing on one PR should be enough).

**Comment by Rikkola** [comment]
@manstis Checked and that should actually pass, but need to figure out how to restart it.
jenkins retest this

**Comment by Ginxo** [comment]
@Rikkola can you please rebase with master in order to update GA configuration, thanks

**Comment by mareknovotny** [comment]
@Rikkola it seems that the problem is related to status of the branch you sent the PR from, as there is very old version of Github action build chain configuration

**Comment by mareknovotny** [comment]
@Rikkola i restarted the Github Actions manually as that is limited in comparison to Jenkins CI which reacts on comment phrases.
You did just the Jenkins job rerun again, but no problem.
For Github Actions any gatekeeper can follow the link Details  there is a button for rerunning the jobs.
obrazek

**Comment by Rikkola** [comment]
Now the basic linux - pr build failed :D 

jenkins retest this

**Comment by Rikkola** [comment]
> Using context: Linux - Pull Request
> groovy.lang.MissingPropertyException: No such property: owner for class: java.util.AbstractMap$SimpleImmutableEntry
> 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
> 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)

Looks like the something might be blocking the builds. 

jenkins retest this

**Comment by mareknovotny** [comment]
well, that error is a result of not having an argument list returned from github API, maybe a API limit reached or some random error happened on API GH request

**Comment by Rikkola** [comment]
@mareknovotny Right. I think this is the second time I see this today.

**Comment by Rikkola** [comment]
@manstis Ok. Turned green.

**Pull request merged**
