### PR TITLE
JBPM-9339: Stunner: Events/Tasks can't be morphed into another node type

### PR DESCRIPTION
**Pull request by handreyrc**
**JIRA**: [JBPM-9339](https://issues.redhat.com/browse/JBPM-9339)

**Business Central**: [WAR file](https://drive.google.com/file/d/1HZQX2k_-Z_VlYDk6TkOO-aTAakIhl9K1/view?usp=sharing)

**VS Code**: [plugin](https://drive.google.com/file/d/1-vZTPFYdHkCAvfOc9DknJC3LyjFL0Vw7/view?usp=sharing)

**Online Editor**: [online-editor](https://drive.google.com/file/d/11nykqGT3PRtp7Vp5UgeKcbEQIbwsLNia/view?usp=sharing)

### CODE REVIEW

**Comment by handreyrc** [comment]
Jenkins run fdb

**Comment by handreyrc** [comment]
Hey @LuboTerifaj, please could you check this fix a blocker issue.
Thanks!

**Comment by handreyrc** [comment]
jenkins retest this

**Review by romartin — APPROVED** [review]
Thanks @handreyrc , looks good to me!

**Review by LuboTerifaj — APPROVED** [review]
It looks good to me.

**Review by paulovmr — APPROVED** [review]

**Pull request merged**
