### PR TITLE
latest Zanata translation changes in kie-wb-common from 2018-09-12

### PR DESCRIPTION
**Pull request by kiereleaseuser**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
@manstis I think this test has nothing to do with the translations. wdyt? I should be merged before the CR2 tag

**Comment by manstis** [comment]
@mbiarnes Agreed.

**Pull request merged**
