### PR TITLE
DROOLS-2300: Increase Coverage of adding and removing parameter

### PR DESCRIPTION
**Pull request by jomarko**
Dependent on #1456 

@manstis please have a look. Some coverage increase. I will rebase once your PR is in.

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko Ready for rebase...

**Comment by jomarko** [comment]
@manstis rebased

**Comment by manstis** [comment]
Thanks for adding the missing tests :-)

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@manstis green, please merge when you have a second.

**Pull request merged**
