### PR TITLE
KOGITO-3805: [DMN Designer] Convert DMN 1.1/1.3 models to version 1.2

### PR DESCRIPTION
**Pull request by karreiro**
**JIRA**: [KOGITO-3805](https://issues.redhat.com/browse/KOGITO-3805): [DMN Designer] Convert DMN 1.1/1.3 models to version 1.2

**VSCode**: [plugin.vsix](https://www.dropbox.com/s/m46k3ofkgr5kqct/plugin-KOGITO-3805.vsix?dl=0)

**Business Central**: [business-central.war](https://www.dropbox.com/s/p54p6uc6un5817l/business-central-webapp-KOGITO-3805.war?dl=0)

--

@danielzhe @vpellegrino, This PR specifically won't have QA review/feedback. Thus, I'm adding both of you as reviewers :-)

It _seems_ large, but the production code of this PR lives in the first commit (https://github.com/kiegroup/kie-wb-common/pull/3482/commits/5b1c25c8c57fe52ce69f02d6b4127ac1b8958d5d). The other commits contain some large DMN models used by the new test suite.

As you can see, the `MainJS` pre-patches Jsonix objects before the GWT-marshaller-service gets them, so everything works out of the box from the editor's perspective, and now we can open DMN 1.1, DMN 1.2, and DMN 1.3.

To cover that new logic with tests, this PR introduces this new backward compatibility test suite with `DMN11BackwardCompatibilityIT`, `DMN12BackwardCompatibilityIT`, and `DMN13BackwardCompatibilityIT`.

You can execute the suite by running this command into `kie-wb-common-dmn-webapp-kogito-runtime` directory:

```
mvn clean install -Pkogito -Dintegration-tests=true
```

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
I've slightly improved the execution time. Also, here's the [link of all images](https://www.dropbox.com/s/zsuvcaau5ul7bzu/test-result-images.zip?dl=0) for each test scenario. Thus, you can check how the editor is opening DMN 1.1/1.2/1.3 models ;-)

**Comment by karreiro** [comment]
Jenkins do fdb.

**Review by vpellegrino — APPROVED** [review]
Great work @karreiro 

In particular, I reviewed https://github.com/kiegroup/kie-wb-common/commit/5b1c25c8c57fe52ce69f02d6b4127ac1b8958d5d and https://github.com/kiegroup/kie-wb-common/pull/3482/commits/b3266026e50578da1628936c32d9903d6dbdde6f

Great stuff

**Comment by karreiro** [comment]
Thank you, @vpellegrino! I've removed trailing commas as suggested ;-)

**Comment by karreiro** [comment]
Jenkins do fdb.

**Review by danielzhe — APPROVED** [review]

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins retest this.

**Comment by karreiro** [comment]
Jenkins retest this.

**Comment by karreiro** [comment]
Jenkins retest this.

**Comment by karreiro** [comment]
Rebasing the branch.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins retest this.

**Comment by karreiro** [comment]
Jenkins retest this.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Pull request merged**
