### PR TITLE
JBPM-9282 Add wait spinner after user confirms warning alert in addin…

### PR DESCRIPTION
**Pull request by bxf12315**
…g deployment unit

**Thank you for submitting this pull request**

**JIRA**: [JBPM-9282](https://issues.redhat.com/browse/JBPM-9282)

**Referenced Pull Requests**:
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://donwnload.here/something)

**VS Code**: [plugin](https://donwnload.here/something)

<pre>
To retest a PR or trigger a specific build please add a comment:

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</pre>

### CODE REVIEW

**Review by nmirasch — APPROVED** [review]
Looks good to me.

**Comment by prashuts** [comment]
Jenkins execute full downstream build

**Comment by bxf12315** [comment]
jenkins do fdb

**Review by prashuts — APPROVED** [review]
Looks fine

**Pull request merged**
