### PR TITLE
[7.7.x] AF-1143 & AF-1123 : Fixes for broken pom.xml

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/AF-1123
https://issues.jboss.org/browse/AF-1143

### CODE REVIEW

**Comment by Rikkola** [comment]
@barboras7 and @paulovmr Here is the fix for 7.7.x. I mentioned that there would be a PR for 7.5.x, but I don't think we have these issues there. If you could please review this one.

**Comment by barboras7** [comment]
Jenkins please execute full downstream build

**Comment by barboras7** [comment]
Jenkins please execute full downstream build

**Comment by Rikkola** [comment]
Jenkins please execute full downstream build

**Comment by Rikkola** [comment]
Jenkins please execute full downstream build

Same failures as before. Last email from the nightly builds says the branch should be fine. So not sure what is going on here. I also doubt I broke these tests.

**Comment by Rikkola** [comment]
Jenkins please execute full downstream build

**Comment by Rikkola** [comment]
Jenkins please execute full downstream build

**Comment by Rikkola** [comment]
Jenkins please execute full downstream build

**Comment by Rikkola** [comment]
So this one is tricky. Since I get the same failing tests in plain 7.7.x branch.

**Comment by Rikkola** [comment]
And green. This one can go in.

**Comment by Rikkola** [comment]
Added a fix for the issue @jhrcek found.

**Comment by Rikkola** [comment]
@jhrcek Good news, thank you.

**Comment by Rikkola** [comment]
@manstis or who ever is responsible for the merges in this repository. If you could please merge this in.

**Comment by manstis** [comment]
@Rikkola Merged as separate 3 commits since they referenced different JIRA. Hope OK.

**Comment by Rikkola** [comment]
@manstis That is ok. Thank you.

**Pull request merged**
