### PR TITLE
[7.14.x] Stunner - standalone showcase fix

### PR DESCRIPTION
**Pull request by tiagodolphine**
Cherry pick commit 1ce306725edee48bff2a7b89b0ad1da2c4a35849 to **7.14.x**

@romartin 
@LuboTerifaj

### CODE REVIEW

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj I built and tested again the branch, and it is working well, I mean I got no errors, I have created a diagram and saved it.
The steps to test:
1 - Run `mvn clean install -Dgwt.compiler.skip=true -DskipTests -U` on _kie-wb-common_
2 - Run `mvn clean gwt:run ` on _kie-wb-common/kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-standalone_
3- Access http://localhost:8888/stunner.html

Thanks !

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj the steps I mentioned are to run the superdev mode based on the goal `gwt:run`, this starts an embedded jetty, there is no need to generate a war and deploy it on wildfly in this case.

@romartin can did you tried to build and run locally, if not can you give it a try, please? 
I built and tested, and got no errors, we need to find out the error @LuboTerifaj is getting.

Thanks guys.

**Comment by LuboTerifaj** [comment]
Hi @tiagodolphine 

It finally works to me.
But I still don't know how to run showcase in business central. How can I do that? Isn't the issue about running showcase in business-central?

Thank you.

**Pull request merged**
