### PR TITLE
JBPM-9511: Stunner: Inline Editor doesn't show after morphing a Task to user Task

### PR DESCRIPTION
**Pull request by handreyrc**
Hey @romartin, @inodeman: Please, could you review this PR?

**JIRA**: [JBPM-9511](https://issues.redhat.com/browse/JBPM-9511)
**JIRA**: [RHPAM-3350](https://issues.redhat.com/browse/RHPAM-3350)

**Business Central**: [WAR file](https://drive.google.com/file/d/1TUPhhuz-EwiIOnklK8Mlgi6lt55pRUef/view?usp=sharing)

**VS Code**: [extension_pack_kogito_kie_editors](https://drive.google.com/file/d/1-2j8Eol5aAZIK7SKKr8cXr4hFtNv7LJL/view?usp=sharing)

### CODE REVIEW

**Comment by handreyrc** [comment]
Jenkins run fdb

**Comment by handreyrc** [comment]
jenkins do fdb

**Comment by romartin** [comment]
Hey @LuboTerifaj 

Could you help on the QE side review for this PR, please? Otherwise, could you please reassign properly?
Please notice that's HIGH PRIORITY, as this ticket is expected to be fixed during actual week, and so present on the next RHPAM 7.10 release as well.

Thanks!

**Review by romartin — APPROVED** [review]

**Comment by romartin** [comment]
Hey @LuboTerifaj 
Please urgent review is pending here. This ticket is targeting 7.10, so would appreciate feedback in order trying to merge it this week.
Thanks!

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @handreyrc ,

I couldn't have reproduced the issue on master and when using this PR, it seems the whole editor responses much slower.

I don't recommend merging this PR.

Note, I tested only Business central in this iteration.
Can you please clarify to me why there are three different extensions linked in the PR? 

Thanks!

**Comment by handreyrc** [comment]
Hey @LuboTerifaj, 
This issue was introduced because I removed some shedulers fixing other issue. I just put them back in this PR. 
The forms loading is inferfering with the inline editor load, it is not 100% reproducible you have to insist double clicking on the node to reproduce it.
If the forms finish loading after the inline editor opens it fails. The point here is to wait for the forms thats why we have the delay.
The schedulers were alredy in the original implementation of the inline editor.

Thanks

**Review by LuboTerifaj — APPROVED** [review]
Hello @handreyrc ,

I double checked the issue and yes it was reproducible but only in Chrome or Kogito.

It works as expected now.

Thanks for the fix!

**Pull request merged**
