### PR TITLE
[7.3.x] JBPM-6283: Changing binding in the fields resets all properties to default values.

### PR DESCRIPTION
**Pull request by pefernan**
Copy of https://github.com/kiegroup/kie-wb-common/pull/1126

@jsoltes could you review?

### CODE REVIEW

**Comment by jsoltes** [comment]
@pefernan looks like there is a compilation error in FormEditorHelperTest...

**Comment by pefernan** [comment]
@jsoltes fixed issue, sorry

**Comment by jsoltes** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
@jsoltes found small issue: on TextBox changing binding to char property still displays max lengt

**Comment by jsoltes** [comment]
I found out the aforementioned issue appears only for model components. Created a video.
[char-textbox-maxlength.zip](https://github.com/kiegroup/kie-wb-common/files/1281469/char-textbox-maxlength.zip)

**Comment by pefernan** [comment]
@jsoltes review again

**Comment by pefernan** [comment]
@jsoltes ups forget it I must fix conflicts

**Pull request closed without merging**
