### PR TITLE
[7.7.x] RHPAM-886: Stunner - Ad-Hoc Subprocess - append end event via quick menu throws error

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin @hasys  @jsoltes would you mind review this PR?
Thanks.

**Comment by wmedvede** [comment]
would you mind take a look at the acks for @krisv  https://issues.jboss.org/browse/RHPAM-886
Thanks.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
@romartin @hasys all required acks are now in place, so this can be merged as soon it's approved

**Pull request merged**
