### PR TITLE
JBPM-9966 : Stunner - Ability to set the priority of a task as a process variable in the BC BPMN editor

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin this is the PR for the BC changes on Task priority, artifacts being generated. Will upload shortly

**Thank you for submitting this pull request**

**JIRA**: [JBPM-9966](https://issues.redhat.com/browse/JBPM-9966)

**Referenced Pull Requests**:
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://drive.google.com/drive/folders/17uT8z-SdFsdGM0wSlObkC26auR2VWLxt?usp=sharing)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by romartin** [comment]
Hey @LuboTerifaj 
Please this needs urgent review. This ticket is required by some customer and we need to get it merged ASAP.
Could you please start with the review?
Thanks!

**Review by romartin — APPROVED** [review]
All good for me, thanks @inodeman !

**Review by LuboTerifaj — COMMENTED** [review]
Hello @inodeman ,

there is no any validation for allowed values in the Priority property.

Does it make sense to you to add it?

Please have a look also at my inline comment.

Otherwise, everything works as expected.

Thank you!

**Comment by romartin** [comment]
Hey @LuboTerifaj 
Valiadtion is not expected on this field. Notice the ticket doesn't mention it as well.
This is because the field is now a free text, which mostly is intented for setting expressions or justt numeric values.
So I tihnk we can skip valudation, nobody expects that, and go ahead.
Thanks!

**Comment by LuboTerifaj** [comment]
Hello @romartin , no problem, we can keep it without a validation. It was just a suggestion. What do you think about helpMessage? Thanks!

**Comment by romartin** [comment]
Hey @LuboTerifaj 
Please see https://github.com/kiegroup/kie-tools/pull/839#issuecomment-1048297841
Thanks!

**Review by LuboTerifaj — APPROVED** [review]
It looks good to me now. Thank you!

**Comment by LuboTerifaj** [comment]
I have reported the issue about tooltip message here: https://issues.redhat.com/browse/JBPM-10026

**Pull request merged**
