### PR TITLE
[7.7.x] RHPAM-1125: Disable links in Servers view if not accessible

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/RHPAM-1125

---

Cherry picked from https://github.com/kiegroup/kie-wb-common/pull/1888

### CODE REVIEW

**Comment by jomarko** [comment]
Please get the acks before merging.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
The build is broken due the time out:
```
Build timed out (after 60 minutes)
```

**Comment by karreiro** [comment]
Jenkins please retest this.

**Pull request merged**
