### PR TITLE
RHBPMS-4984 Remove Picture widget from the editor 7.3.x

### PR DESCRIPTION
**Pull request by alessioscalici**
**WARNING** this is the same as https://github.com/kiegroup/kie-wb-common/pull/1220 and https://github.com/kiegroup/kie-wb-common/pull/1231, pointing to 7.3.x

@pefernan @jsoltes FYI

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@jsoltes your turn

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@alessioscalici could you please send this PR to 7.4.x branch?

**Comment by alessioscalici** [comment]
@pefernan done https://github.com/kiegroup/kie-wb-common/pull/1231

**Comment by pefernan** [comment]
Not needed

**Pull request closed without merging**
