### PR TITLE
AF-2438 : Dropdown with branches is missing in the branch management

### PR DESCRIPTION
**Pull request by akumar074**
- Moved KieSelectElement implementation from presenter to view

 * [Deployable WAR](https://drive.google.com/open?id=1r1sUenOL6gBSjvaWvg1H621_tpudsJsr) to test

### CODE REVIEW

**Comment by akumar074** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
Code looks well, but downstream fails. Waiting for the green to give it a try

**Comment by akumar074** [comment]
jenkins execute full downstream build please

**Comment by akumar074** [comment]
Full downstream build failure seems to be unrelated.

<details>
<summary>Error Log</summary>

```
21:13:50 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project jpa-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
21:13:50 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project jpa-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
21:13:50     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
21:13:50     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
21:13:50     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
21:13:50     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
21:13:50     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
21:13:50     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
21:13:50     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
21:13:50     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
21:13:50     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
21:13:50     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
21:13:50     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
21:13:50     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
21:13:50     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
21:13:50     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
21:13:50     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
21:13:50     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
21:13:50     at java.lang.reflect.Method.invoke (Method.java:498)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
21:13:50 Caused by: org.apache.maven.plugin.MojoExecutionException: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
21:13:50     at org.apache.maven.plugins.enforcer.EnforceMojo.execute (EnforceMojo.java:243)
21:13:50     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
21:13:50     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
21:13:50     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
21:13:50     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
21:13:50     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
21:13:50     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
21:13:50     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
21:13:50     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
21:13:50     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
21:13:50     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
21:13:50     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
21:13:50     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
21:13:50     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
21:13:50     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
21:13:50     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
21:13:50     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
21:13:50     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
21:13:50     at java.lang.reflect.Method.invoke (Method.java:498)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
21:13:50 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project camel-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
21:13:50 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project camel-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
21:13:50     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
21:13:50     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
21:13:50     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
21:13:50     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
21:13:50     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
21:13:50     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
21:13:50     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
21:13:50     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
21:13:50     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
21:13:50     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
21:13:50     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
21:13:50     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
21:13:50     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
21:13:50     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
21:13:50     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
21:13:50     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
21:13:50     at java.lang.reflect.Method.invoke (Method.java:498)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
21:13:50 Caused by: org.apache.maven.plugin.MojoExecutionException: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
21:13:50     at org.apache.maven.plugins.enforcer.EnforceMojo.execute (EnforceMojo.java:243)
21:13:50     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
21:13:50     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
21:13:50     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
21:13:50     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
21:13:50     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
21:13:50     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
21:13:50     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
21:13:50     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
21:13:50     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
21:13:50     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
21:13:50     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
21:13:50     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
21:13:50     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
21:13:50     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
21:13:50     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
21:13:50     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
21:13:50     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
21:13:50     at java.lang.reflect.Method.invoke (Method.java:498)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
21:13:50     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
21:13:50 [ERROR] 
21:13:50 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
21:13:50 [ERROR] 
21:13:50 [ERROR] For more information about the errors and possible solutions, please read the following articles:
21:13:50 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
21:13:50 [ERROR] 
21:13:50 [ERROR] After correcting the problems, you can resume the build with the command
21:13:50 [ERROR]   mvn <goals> -rf :jpa-workitem
21:13:50 Unexpected error while executing the Downstream repositories builder for PR builds! Error while executing Maven process, non-zero exit code!
21:13:50 java.lang.RuntimeException: Error while executing Maven process, non-zero exit code!
21:13:50 	at org.kie.jenkinsci.plugins.kieprbuildshelper.MavenProject.build(MavenProject.java:68)
21:13:50 	at org.kie.jenkinsci.plugins.kieprbuildshelper.AbstractPRBuilder.perform(AbstractPRBuilder.java:115)
21:13:50 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
21:13:50 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
21:13:50 	at hudson.model.Build$BuildExecution.build(Build.java:206)
21:13:50 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
21:13:50 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
21:13:50 	at hudson.model.Run.execute(Run.java:1810)
21:13:50 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
21:13:50 	at hudson.model.ResourceController.execute(ResourceController.java:97)
21:13:50 	at hudson.model.Executor.run(Executor.java:429)
21:13:50 Build step 'Build dependent downstream repositories (for PR builds)' marked build as failure
21:13:50 Terminating xvnc.
21:13:50 $ vncserver -kill :58
21:13:50 Killing Xvnc process ID 10143
21:13:52 Recording test results
21:13:58 Skipping publisher since build result is FAILURE
21:13:58 Skipping publisher since build result is FAILURE
21:13:58 Archiving artifacts
21:14:16 Adding one-line test results to commit status...
21:14:16 Setting status of 2e3b0e7c01e3bff80c3e72a55d1bd089f45b5386 to FAILURE with url https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-common-downstream-pullrequests/961/ and message: 'Build finished. 5176 tests run, 10 skipped, 0 failed.'
21:14:16 Using context: Linux - full downstream
21:14:17 [WS-CLEANUP] Deleting project workspace...
21:14:17 [WS-CLEANUP] Deferred wipeout is used...
21:14:17 [WS-CLEANUP] done
21:14:17 Finished: FAILURE
```
</details>

**Comment by akumar074** [comment]
jenkins execute full downstream build please

**Comment by akumar074** [comment]
jenkins execute full downstream build please

**Comment by akumar074** [comment]
jenkins execute full downstream build please

**Comment by akumar074** [comment]
jenkins execute full downstream build please

**Comment by akumar074** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
Thanks @akumar074

**Comment by mareknovotny** [comment]
we need also backport to 7.33.x branch

**Pull request merged**
