### PR TITLE
[7.18.x]  AF-1909 : Manual changes to kmodule.xml are overriden

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit 2abb3a60cf9541f14870316aa18764e71c23fb12)

https://issues.jboss.org/browse/AF-1909
@barboras7 @paulovmr Hi, same as the one for master.

### CODE REVIEW

**Comment by barboras7** [comment]
Jenkins execute full downstream build

**Comment by barboras7** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
Merging without @paulovmr approval as this is a cherry-pick and he's approved #2546.

**Comment by Rikkola** [comment]
Thanks @manstis

**Pull request merged**
