### PR TITLE
BAPL-678: BPMN Editor - Syntax Highlighting Editor

### PR DESCRIPTION
**Pull request by romartin**
Hey @LuboTerifaj @Josephblt 

This work incorporates the use of the [Monaco Editor](https://microsoft.github.io/monaco-editor/) on several fields in the BPMN editor, such as `script`, `onEntry/Exit` actions or sequence flows' `conditions`.

See https://issues.redhat.com/browse/BAPL-678

Assembly:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1429
- https://github.com/kiegroup/appformer/pull/1012
- https://github.com/kiegroup/kie-wb-common/pull/3372

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Fixed most of the sonarcloud issues guys, the missing ones are due to native stuff (html, dom, errai, etc). So hope that's everything fine for starting the review again. Thanks!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full compile build

**Comment by Josephblt** [comment]
Jenkins execute compile downstream build

**Comment by domhanak** [comment]
@romartin Hi, the FDB didn't run it seem there are conflicts in merging, see console log

**Comment by romartin** [comment]
@domhanak rebased, thanks for letting me know, let's see now...

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute compile downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute compile downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @LuboTerifaj 
Please just missing your review here. The artifact is built [here](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/compileDownstream/job/new-CDB-kie-wb-common-master.compile/37/artifact/kiegroup_kie-wb-distributions/business-central-parent/business-central-distribution-wars/business-central/target/business-central-7.42.0-SNAPSHOT-wildfly19.war) from the compile downstream build. I'll be off during next week, so please would really appreciate trying to get thsi closed before leaving.
Thanks in advance!

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @LuboTerifaj 
I [uploaded a WAR](https://github.com/kiegroup/kie-wb-common/pull/3372#issuecomment-671650968) in order to test this, as the FDB are not always working properly and it's not easy to obtain the artifacts. Can you please rely on it for testing the PR? 
Thx!

**Comment by LuboTerifaj** [comment]
Hello @romartin I am testing the PR with provided war. However I would also like to check the behaviour in business-central. Can you please upload business-central.war to the drive as well? Thank you!

**Comment by LuboTerifaj** [comment]
FDB hasn't been triggered. Jenkins execute full downstream build.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hey @romartin there is something wrong with FDB. I have reported the issue: https://issues.redhat.com/browse/BXMSPROD-969

**Comment by baldimir** [comment]
Jenkins execute fdb

**Comment by LuboTerifaj** [comment]
A trigger phrase has been changed to a new one. See [comment](https://github.com/kiegroup/kie-wb-common/pull/3372#issuecomment-680023021) above.

**Comment by romartin** [comment]
rebased from master upstream again

**Comment by romartin** [comment]
Jenkins execute fdb

**Comment by romartin** [comment]
Jenkins execute cdb

**Comment by romartin** [comment]
Hey @LuboTerifaj 

I've rebased this work and re-fired builds... also I've uploaded the artifacts for testing:

- BC WAR
- [VSCode extension](https://drive.google.com/file/d/1LyYVEhxjGl1nPCkZTUgASwaF7gnYx68O/view?usp=sharing)

Hope it's ready enough for you to move forward. Lemme know if any issues ASAP plz. Thanks!!

**Review by LuboTerifaj — APPROVED** [review]
Hello @romartin ,

I have found just one UX issue:

- Text area for scripts is cropped/shifted when inputting longer lines of code. The vertical scrollbar is shifted as well.
- See the screenshot below:
cropped-editor-area
- I think we can report the issue as a future enhancement.

I didn't find any more issues, hence it should be ready to merge.

Thank you!

**Comment by romartin** [comment]
Hey @LuboTerifaj 

Thanks for the review! Just please see [this comment](https://issues.redhat.com/browse/BAPL-678?focusedCommentId=14413789&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14413789), as we'll stil not merge yet.

**Comment by romartin** [comment]
Jenkins execute fdb

**Comment by romartin** [comment]
Jenkins execute cdb

**Comment by romartin** [comment]
ohh @mareknovotny @mbiarnes finally looks we're getting "green" builds again on this repo.... :tada:  thanks guys!!!

**Comment by romartin** [comment]
Build: romartin/BAPL-678

**Review by ederign — APPROVED** [review]

**Pull request merged**
