### PR TITLE
[7.18.x] AF-1865: [Streamline Development Lifcycle] Fix backguard compatibilities and improve 'dev mode' deployment policy

### PR DESCRIPTION
**Pull request by pefernan**
Backport of https://github.com/kiegroup/kie-wb-common/pull/2497

This change adds some improvements, the changes are:

* Ability to deploy SNAPSHOT and non-SNAPSHOT modules on DEVELOPMENT mode KieServers
* Changed default module version to  1.0.0-SNAPSHOT

This is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-integration/pull/1748
https://github.com/kiegroup/kie-wb-common/pull/2499
https://github.com/kiegroup/kie-docs/pull/1410

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build please.

**Comment by pefernan** [comment]
@jhrcek same error here... how can I do this https://github.com/kiegroup/kie-wb-common/pull/2497#issuecomment-466294082 here?

**Comment by jhrcek** [comment]
@pefernan [this PR](https://github.com/kiegroup/jbpm-designer/pull/835) seems to have fixed that issue.
I cherry-picked the same fix to 7.18. branch: https://github.com/kiegroup/jbpm-designer/pull/836
You can try convincing someone to merge that :-)

**Comment by pefernan** [comment]
@jhrcek I have permission but I'm going to ask someone... Thanks!

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Comment by pefernan** [comment]
Jenkins execute full downstream build please

**Comment by pefernan** [comment]
Jenkins execute full downstream build please

**Comment by pefernan** [comment]
@dgutierr @porcelli double green!

**Pull request merged**
