### PR TITLE
Code reformatted according to KIE Group format standard.

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin, @LuboTerifaj,

just some code style adjustments. It is good to have ability to execute formatter for entire project when you create you PR and after this PR it will be possible to not touch other files with wrong formatting.

### CODE REVIEW

**Comment by romartin** [comment]
@hasys @LuboTerifaj the https://github.com/kiegroup/kie-wb-common/pull/2480 has been already merged. Feel free to update this PR again, if necessary guys.

**Comment by hasys** [comment]
Hi @LuboTerifaj, @romartin, thank you for the info, rebased to master and formatted latest commits.

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@hasys ok all good now, so merging, thanks!

BTW @hasys please if you're planning to do some other refactoring consider waiting a few more... me and @manstis are trying to get our [submarine branch](https://github.com/kiegroup/kie-wb-common/tree/DROOLS-3727) up to date and merge it into master ASAP, so better if we can do this kind of refactoring once done. Thanks anyway for helping!! :+1:

**Comment by hasys** [comment]
@romartin,

sure, I can wait for merge for next refactoring, no problem. Thank you!

**Pull request merged**
