### PR TITLE
GUVNOR-3325: The value of an annotation cannot be set using the *Add new annotation* dialog (#1019)

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit a89e061a35bb91b0b0e30cf398833f2c0a775a8c)

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @manstis this is the peer PR for the already merged into 7.2.x https://github.com/kiegroup/kie-wb-common/pull/1026.

Would you mind review/merge when jenkins is green?

Thanks!

**Comment by wmedvede** [comment]
weird the failing test is not related with this commit at all.

org.kie.workbench.common.stunner.bpmn.backend.service.indexing.BpmnFileIndexerTest.testBpmnIndexing

Failing for the past 1 build (Since Unstable#1682 )
Took 5.7 sec.
Error Message

expected:<7> but was:<8>
Stacktrace

java.lang.AssertionError: expected:<7> but was:<8>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.kie.workbench.common.stunner.bpmn.backend.service.indexing.BpmnFileIndexerTest.testBpmnIndexing(BpmnFileIndexerTest.java:130)

**Comment by jhrcek** [comment]
@wmedvede seems like problem with unstable indexing tests. @hasys was fixing something like that in [this PR](https://github.com/kiegroup/kie-wb-common/pull/998/files) Perhaps similar test stabilization fix could be implemented for this randomly failing test too?

**Comment by wmedvede** [comment]
@jhrcek yes, seems like this is a randomly failing test. Hopefully someone on the stunner field can stabilize this test.

**Comment by wmedvede** [comment]
jenkins retest this

**Comment by hasys** [comment]
Hi @jhrcek, @wmedvede 

It is not a _randomly failing test_ on Stunner side. It is a **bug** on Uberfire side: https://issues.jboss.org/browse/AF-576

We can `fix` test do not fail, implement some workaround to ignore this bug, but I am not sure it is a right way to go.

**Comment by wmedvede** [comment]
now it fails but in another random failing test

**Comment by wmedvede** [comment]
jenkins retest this

**Comment by wmedvede** [comment]
this is the failing test right now

duplicate declaration of version (?) @ org.kie:kie-spring:[unknown-version], /home/jenkins/workspace/kie-wb-common-pullrequests/upstream-repos/droolsjbpm-integration/kie-spring/pom.xml, line 283, column 17
18:13:20 [ERROR] 'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket:jar is missing. @ org.kie.server:kie-server-controller-standalone:[unknown-version], /home/jenkins/workspace/kie-wb-common-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-controller/kie-server-controller-standalone/pom.xml, line 25, column 17
18:13:20 [ERROR] 'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket-common:jar is missing. @ org.kie.server:kie-server-controller-standalone:[unknown-version], /home/jenkins/workspace/kie-wb-common-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-controller/kie-server-controller-standalone/pom.xml, line 29, column 17
18:13:20 [ERROR] 'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket-common:jar is missing. @ org.kie.server:kie-server-controller-websocket:[unknown-version], /home/jenkins/workspace/kie-wb-common-pullrequests/upstream-

18:14:55 [ERROR]   
18:14:55 [ERROR]   The project org.kie.server:kie-server-controller-standalone:8.0.0-SNAPSHOT (/home/jenkins/workspace/guvnor-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-controller/kie-server-controller-standalone/pom.xml) has 2 errors
18:14:55 [ERROR]     'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket:jar is missing. @ org.kie.server:kie-server-controller-standalone:[unknown-version], /home/jenkins/workspace/guvnor-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-controller/kie-server-controller-standalone/pom.xml, line 25, column 17
18:14:55 [ERROR]     'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket-common:jar is missing. @ org.kie.server:kie-server-controller-standalone:[unknown-version], /home/jenkins/workspace/guvnor-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-controller/kie-server-controller-standalone/pom.xml, line 29, column 17
18:14:55 [ERROR]   
18:14:55 [ERROR]   The project org.kie.server:kie-server-controller-websocket:8.0.0-SNAPSHOT (/home/jenkins/workspace/guvnor-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-controller/kie-server-controller-websocket/pom.xml) has 2 errors
18:14:55 [ERROR]     'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket-common:jar is missing. @

**Comment by wmedvede** [comment]
jenkins retest this

**Comment by wmedvede** [comment]
This is the error right now

22:10:47 [INFO] ------------------------------------------------------------------------
22:10:47 [INFO] BUILD FAILURE
22:10:47 [INFO] ------------------------------------------------------------------------
22:10:47 [INFO] Total time: 07:50 min (Wall Clock)
22:10:47 [INFO] Finished at: 2017-08-03T18:10:47-04:00
22:10:49 [INFO] Final Memory: 1036M/1927M
22:10:49 [INFO] ------------------------------------------------------------------------
22:10:49 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project kie-wb-common-java-editor-client: Compilation failure: Compilation failure:
22:10:49 [ERROR] /home/jenkins/workspace/kie-wb-common-downstream-pullrequests/kie-wb-common-screens/kie-wb-common-java-editor/kie-wb-common-java-editor-client/src/main/java/org/kie/workbench/common/screens/javaeditor/client/editor/JavaEditorPresenter.java:[36,1] Internal error in org.uberfire.annotations.processors.WorkbenchEditorProcessorjava.lang.NoClassDefFoundError: org.uberfire.annotations.processors.AbstractGenerator
22:10:49 [ERROR] at org.uberfire.annotations.processors.WorkbenchEditorProcessor.<init>(WorkbenchEditorProcessor.java:48)
22:10:49 [ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
22:10:49 [ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
22:10:49 [ERROR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
22:10:49 [ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
22:10:49 [ERROR] at java.lang.Class.newInstance(Class.java:442)
22:10:49 [ERROR] at com.sun.tools.javac.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:265)
22:10:49 [ERROR] at com.sun.tools.javac.util.ServiceLoader$1.next(ServiceLoader.java:337)
22:10:49 [ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment$ServiceIterator.next(JavacProcessingEnvironment.java:359)
22:10:49 [ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment$ServiceIterator.next(JavacProcessingEnvironment.java:325)
22:10:49 [ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.j

**Comment by wmedvede** [comment]
Some files even not related to this PR seems to not build, seems like there has been changes in uberfire in the middle.
Will try to rebase with master and push again.

**Comment by wmedvede** [comment]
ok, it took about two hours to:
1) rebase locally and build all my guvnor PRs with other changes
2) go back all the needed repositories to master again, and build them
3) finally rebase this repo with master and build it

I hope there's luck this time!

**Comment by wmedvede** [comment]
Seems like there was luck this time.
Hello @manstis would you please merge this when you got 5 mins?
Thanks!

**Comment by wmedvede** [comment]
woot, seems like the build of this has automatically re-triggered again

**Comment by manstis** [comment]
@wmedvede Yes you are very lucky indeed ;-)

**Comment by manstis** [comment]
@wmedvede But I did see it was green when you first expressed your amazement so am happy to merge.

**Comment by wmedvede** [comment]
Hello @psiroky , regarding PRs build.

This build was green/green at half an hour back, or so. This is fine. 
This PR has no dependencies to any other PR.
Now I see that the full downstream build has automatically started for this PR, the question is this possible?

I mean, can the build start automatically again when no "jenkins retest XXX" command was executed, or nor changes where done to this PR or any other related PR?

**Comment by wmedvede** [comment]
@manstis oh, yes, but I'm wondering if this is possible. I mean, how can the full downstream build start if nothing related with this PR has changed?

**Comment by manstis** [comment]
@wmedvede Having seen @psiroky discussion with @tarilabs on a different PR I checked your comments on this PR too.. and agree; I see no (obvious) way this PR should/would/could have been re-triggered.

**Pull request merged**
