### PR TITLE
JBPM-6688: Forms & Stunner - Restore Stunner properties forms layout

### PR DESCRIPTION
**Pull request by pefernan**
This PR restores the paddings removed on the last Layout Editor changes.

@romartin @wmedvede @hasys  could you take a look?

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Not able to download war file, let's try again.

Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
try again!

**Comment by hasys** [comment]
Hi @pefernan,

it looks like it is real build fail. There are some issues in DMN editor:

`10:23:21 Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
10:23:21 /home/jenkins/workspace/kie-wb-common-downstream-pullrequests/kie-wb-common-dmn/kie-wb-common-dmn-webapp/src/main/java/org/kie/workbench/common/dmn/showcase/client/screens/properties/SessionPropertiesScreen.java:[80,49] cannot find symbol
10:23:21   symbol:   method asWidget()
10:23:21   location: variable formPropertiesWidget of type org.kie.workbench.common.stunner.forms.client.widgets.FormPropertiesWidget`

**Comment by pefernan** [comment]
@hasys wops I forgot about the dmn module

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Pull request merged**
