### PR TITLE
DROOLS-5499: Remove unused compile dependecies - kie-wb-common-server-ui-backend

### PR DESCRIPTION
**Pull request by jomarko**
For more details see: https://issues.redhat.com/browse/DROOLS-5499

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by Ginxo** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
The error is:
```
15:24:02  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project kie-wb-common-server-ui-backend: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
15:24:02  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project kie-wb-common-server-ui-backend: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
```
See my email on bsig mailing list: **PR checks blocked due to duplicated classes**

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by yesamer** [comment]
@jomarko Probably you could have the same issue with `netty-transport` dependency, can you please double check?
Screenshot from 2020-07-10 09-07-29

**Comment by mareknovotny** [comment]
@jomarko I see that the duplicated test depenendency is coming from `kie-server-integ-tests-common` dep

```
[INFO] +- org.kie.server:kie-server-integ-tests-common:jar:7.41.0-SNAPSHOT:test
[INFO] |  +- org.kie.server:kie-server-controller-standalone-impl:jar:7.41.0-SNAPSHOT:test
[INFO] |  +- org.kie.server:kie-server-rest-common:jar:7.41.0-SNAPSHOT:test
[INFO] |  |  +- io.prometheus:simpleclient:jar:0.5.0:test
[INFO] |  |  +- io.prometheus:simpleclient_common:jar:0.5.0:test
[INFO] |  |  \- io.prometheus:simpleclient_httpserver:jar:0.5.0:test
[INFO] |  +- org.jboss.resteasy:tjws:jar:3.9.3.SP1:test
[INFO] |  +- org.codehaus.cargo:cargo-core-api-container:jar:1.7.9:test
[INFO] |  |  +- org.codehaus.cargo:cargo-core-api-module:jar:1.7.9:test
[INFO] |  |  |  +- org.codehaus.cargo:cargo-core-api-util:jar:1.7.9:test
[INFO] |  |  |  \- org.codehaus.cargo:cargo-licensed-dtds:jar:1.7.9:test
[INFO] |  |  \- org.apache.geronimo.specs:geronimo-j2ee-deployment_1.1_spec:jar:1.1:test
[INFO] |  +- org.codehaus.cargo:cargo-core-api-generic:jar:1.7.9:test
[INFO] |  |  \- commons-discovery:commons-discovery:jar:0.5:test
[INFO] |  +- org.codehaus.cargo:cargo-core-container-weblogic:jar:1.7.9:test
[INFO] |  +- org.codehaus.cargo:cargo-core-container-wildfly:jar:1.7.9:test
[INFO] |  |  \- com.googlecode.json-simple:json-simple:jar:1.1.1:test
[INFO] |  \- io.netty:netty-transport-native-epoll:jar:4.1.46.Final:test
```

**Comment by mareknovotny** [comment]
@jomarko this exclusion instead of that you did works for me
```
diff --git a/kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/pom.xml b/kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/pom.xml
index f9f8d58e9e..765c9da013 100644
--- a/kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/pom.xml
+++ b/kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-backend/pom.xml
@@ -354,6 +354,11 @@
           <groupId>org.codehaus.cargo</groupId>
           <artifactId>cargo-core-uberjar</artifactId>
         </exclusion>
+        <!-- already on classpath - 'uberfire-commons' -->
+        <exclusion>
+          <groupId>io.netty</groupId>
+          <artifactId>netty-transport-native-epoll</artifactId>
+        </exclusion>
       </exclusions>
     </dependency>
     <dependency>
```

**Comment by mareknovotny** [comment]
btw kie-server-integ-tests and related modules are full of duplicates from my past experiences

**Comment by jomarko** [comment]
@mareknovotny thank you a lot, I applied your suggestion

**Comment by jomarko** [comment]
Failed test:
```
org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerKogitoSeleniumIT.testBusinessKnowledgeModel
```

A network issue downloading marionette browser driver.

**Comment by jomarko** [comment]
Jenkins please retest this

**Pull request merged**
