### PR TITLE
JBPM-5560: Support for BPMN2 Embedded Subprocess.

### PR DESCRIPTION
**Pull request by romartin**
Hey @manstis @hasys ,

This commit adds the support for the `BPMN2 Embedded Subprocess`. 

It's basically about:
- Adding the bean, properties and the shape
- Adding custom rules for it (it only accepts containment for nodes that do not have sequence flows associated or the source/target nodes for the sequence flows, if any, are on same parent as the candidate).
- Add the marshalling support
- Some other concrete fixes for bugs found while trying this..

See the JIRA ticket [here](https://issues.jboss.org/browse/JBPM-5650).

Thanks in advance for you help!!! :)

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
* Some addition notes: typo in PR name, issue name is not JBPM-5**56**0, but JBPM-5**65**0
* I posted use-cases I tested in original Jira issue
* Some of the mentioned issues on Embedded Subprocesses (for example known issues for containers) so we can extend existing Jiras to one more elements.
* There are a lot of different missing validations around Embedded Subprocess (but, it is also separate issue)
* And also missing "Variable Definitions" property we need to track it somewhere.

Thank you @romartin and let's keep in touch :)

**Comment by romartin** [comment]
Hey @hasys ,

Thanks for the reivew! Still looking at the different issues, but for now there are a couple of bugs that, as you say, are not related to the emb. subprocess itself, so created new tickets:
- [https://issues.jboss.org/browse/JBPM-6076](https://issues.jboss.org/browse/JBPM-6076)
- [https://issues.jboss.org/browse/JBPM-6077](https://issues.jboss.org/browse/JBPM-6077)

Still working on the other comments, will let you know once done. :)
Thanks!

**Comment by romartin** [comment]
Hey @hasys , @manstis 

Thanks for the review and intense tests! :)

Let's try to summarize and define what's related to the emb. subprocess task  and what's not, This way this PR won't get bigger, can be merged soon, and we can focus on each of the issues found later on...

So about the concrete emb. subpocess, these are the comments/updates:
- The embedded subprocess has concrete restrictions when using sequence flows, so what you see is not an error, is a validation message that says you're not allowed to do this, as both nodes linked by the sequence flow have different process parent instances.
- Good point - as group selection is not present yet, sometimes results uncomfortable to add elements, with already existing connectors, into a subprocess. 
IIMO I would keep this validation as it is, for now. Bypassing restrictions, because group selection is missing, probably leads to more logic to add and test that will be removed soon... WDYT?
- Changed the shape for emb. subprocess for using non-transparent backgrounds
- Added missing _variable definitions_ property, well seen!!

And the other bugs found, which are not related to this task, has been reported as :
- [https://issues.jboss.org/browse/JBPM-6076](https://issues.jboss.org/browse/JBPM-6076)
- [https://issues.jboss.org/browse/JBPM-6077](https://issues.jboss.org/browse/JBPM-6077)
- [https://issues.jboss.org/browse/JBPM-6084](https://issues.jboss.org/browse/JBPM-6084)

So what you think guys? Lemme know if I'm missing something please.
And sorry for the typo on the PR's title aargh :(
Thanks!

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @manstis @hasys 
I've rebased this commit as it was conflicted at this point, it as just an `import` so easy,,. Anyway both checks were passing!! Hope not having to wait too much again for the downstream build to pass... :/ 
THanks!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Looks good, thank you @romartin,
but I still able to reproduce some issues I mentioned above and not found it in Jira. So I reported it to keep it track:

- [JBPM-6103](https://issues.jboss.org/browse/JBPM-6103) - Still not possible to set value to Documentation and Script Language property;
- [JBPM-6101](https://issues.jboss.org/browse/JBPM-6101) - In my oppinion it is a bug and have to be fixed append nodes inside embedded subprocess;
- [JBPM-6102](https://issues.jboss.org/browse/JBPM-6102) - I didn't found issue about selection of group of element (and move it to subprocess), so I reported it;
- [JBPM-6104](https://issues.jboss.org/browse/JBPM-6104) - not possible to remove container with non empty container inside

I guess we can merge it now and fix bugs sometime later.

**Comment by romartin** [comment]
Great @hasys , thanks!

**Comment by romartin** [comment]
@manstis do you want to review it?

**Pull request merged**
