### PR TITLE
JBPM-7561 Stunner - Create Marshaller tests for Conditional Intermedi…

### PR DESCRIPTION
**Pull request by LuboTerifaj**
…ate Catching events

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
I forgot to add tests for boundary events. I will add them but need to investigate an issue with creating process. I am currently getting unexpected error.

**Comment by LuboTerifaj** [comment]
Hi @hasys @evacchi 

Can you have a look at this PR?

Thank you!

**Comment by evacchi** [comment]
please verify / report bugs with new marshallers

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by evacchi** [comment]
Jenkins retest please

**Pull request merged**
