### PR TITLE
[7.44.x] [DMN Designer] Multiple DRDs support - When a node is deleted in the DRG, undo/redo operations do not work properly

### PR DESCRIPTION
**Pull request by danielzhe**
**JIRA**: [KOGITO-3364](https://issues.redhat.com/browse/KOGITO-3364)

**Referenced Pull Requests**:
Merged: https://github.com/kiegroup/kie-wb-common/pull/3447

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by danielzhe** [comment]
Should QE approve this PR too, @karreiro, since the original is already merged on base? Thank you.

**Review by karreiro — APPROVED** [review]
Hi @danielzhe. AFAIK we still need QE feedback on this kind of PR.

Thank you for opening it :-)

**Comment by jstastny-cz** [comment]
@danielzhe @karreiro I am not insisting on QE being mandatory reviewer in all cases, it's just necessary to check FDB (cause the master and target branches might have already diverged and sth might not work properly). For simplicity you can add me to all backporting PRs, if you also simultaneously run the FDB for me, the review wouldn't take me too much time anyway.

**Comment by jstastny-cz** [comment]
jenkins do fdb

**Review by jstastny-cz — APPROVED** [review]
Verified in FDB.

**Pull request merged**
