### PR TITLE
JBPM-9352: Stunner - Warning when getContent is called while the model is invalid

### PR DESCRIPTION
**Pull request by romartin**
Hey @paulovmr @ederign 

As discussed with @porcelli , fixing the actual blocker issue by completely disabling validation in the bpmn editor.

See comments in https://issues.redhat.com/browse/JBPM-9352

BTW You know who should be the QE tester for this, if any? Can't see anyone on the ticket yet.

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins do fdb

**Comment by romartin** [comment]
Jenkins do cdb

**Review by porcelli — APPROVED** [review]

**Review by porcelli — COMMENTED** [review]
maybe add a test that will make sure that no validation is emitted on the getContent method call?

**Comment by romartin** [comment]
@porcelli in fact I removed the code that calls validation, even the validator injections, in order to don't have dead code (we can inject later on as well, once fixing it). Also removed the validator instance from the test case, so it's for sure not calling validation now, I don't think I can ensure validation is not being called because of the class is now not using any validator.

**Comment by LuboTerifaj** [comment]
Hello @domhanak would you mind to have a look at this PR? Thank you!

**Comment by romartin** [comment]
hey @ederign @paulovmr @domhanak @LuboTerifaj @porcelli 
For me this fix is ready, please let me know some feedback asap. 
Thanks guys!

**Comment by domhanak** [comment]
Thanks @romartin I tried to reproduce the warning but I can't with these changes.
I was able to save a BPMN process in invalid state.

Only time I couldn't was when I added sequence flow without target node. A notification that save operation was cancelled pops up. I believe this is correct behavior as sequence flow without target does not make sense. 
Approved.

**Review by domhanak — APPROVED** [review]

**Review by paulovmr — APPROVED** [review]

**Pull request merged**
