### PR TITLE
JBPM-8224 Stunner - Missing process variables for sub-processes on Documentation

### PR DESCRIPTION
**Pull request by tiagodolphine**
- Adding all sub-processes variables
- Adding all global variables

Now all variables are aggregated and showed on the documentation.

@romartin 
@LuboTerifaj

### CODE REVIEW

**Comment by tiagodolphine** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Hey @romartin, yes, all the test classes related to documentation is intended to be created on [JBPM-8171](https://issues.jboss.org/browse/JBPM-8171).

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj this PR is ok to be reviewed, the wars were generated.
Thanks.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Thanks @LuboTerifaj , yeah I agree with the improvement you opened, we can work on that on this new JIRA.

@romartin it ok to be merged.

**Pull request merged**
