### PR TITLE
JBPM-8757: Stunner - Process displays process name in editor title instead of file name

### PR DESCRIPTION
**Pull request by handreyrc**
@romartin, @inodeman Could you please review this PR?

### CODE REVIEW

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins retest please

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hey @romartin , full downstream build is still failing so I cannot test the PR.

**Comment by romartin** [comment]
I know @LuboTerifaj .. we're trying to fix all builds, nothing works :( sorry

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@mbiarnes @mareknovotny 

Still can see the message:
[ERROR] Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000000042fc00000, 573046784, 0) failed; error='Cannot allocate memory' (errno=12)

In last build from today, are all jenkins nodes already updated with new memory settings?

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Pull request merged**
