### PR TITLE
RHPAM-2413: Stunner - some end events have incorrect icons.

### PR DESCRIPTION
**Pull request by romartin**
Hey @hasys 

This is the cherry-pick for https://github.com/kiegroup/kie-wb-common/pull/2926 into `7.26.x` branch.

See [RHPAM-2413](https://issues.jboss.org/browse/RHPAM-2413)

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
oh @bdellasc !! sorry I think I forgot you was also going to address the PR reviews about UX, is that correct??? I'm really glad to confirm this, if so! 

If that's the case, plz confirm so I'll add you on the following reviews. 

Also let you know that I left a comment above `Jenkins execute full downstream build` - this fires a build of the whole KIE workbench, including the changes in this (and related) PR's. So now, you can wait (a few hours) until a "Linux - Full Downstream" result will appear at the bottom of this page, as with other build results...  

Screenshot from 2019-10-23 00-14-47

At this point, just click on the `Details` link that appears at the right side of the "LInux - Full Downstream" and you'll get redirected to the Jenkins results page, you can download the business central WAR from this page and try the chagnes from this PR in your laptop:

Screenshot from 2019-10-23 00-16-07

Hope this helps on the reviews! Plz lemme know if any Qs
Thx!

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @hasys  @bdellasc 

Although full build says it's failed, it's only because an (unrelated) test case, but the artifacts are properly generated and can be tested - just click on the `Details` link and download the WAR `business-central-7.26.1-SNAPSHOT-wildfly14.war`

Anyway I downloaded the WAR and re-tested and here is the screenshot for show all end events are looking:

Screenshot from 2019-10-23 00-12-23

Thx!

**Pull request merged**
