### PR TITLE
[RHPAM-2657] KieServer Scale-Up-From-Zero lifecycle hooks logic broken

### PR DESCRIPTION
**Pull request by rhtevan**
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>

Related JIRAs
https://issues.redhat.com/projects/RHPAM/issues/RHPAM-2657
https://issues.redhat.com/projects/RHPAM/issues/RHPAM-2008
https://issues.redhat.com/browse/JBPM-8585

Related PRs
https://github.com/kiegroup/droolsjbpm-integration/pull/1995

Followed-By PRs
https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/414
https://github.com/jboss-container-images/rhdm-7-openshift-image/pull/329
https://github.com/jboss-container-images/jboss-kie-modules/pull/352
https://github.com/kiegroup/kie-cloud-operator/pull/353

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@rhtevan can you make sure there is also a PR for the docs part, this needs to be updated or added to kie-docs, also so it is tracked by the docs team. @sterobin fyi

**Comment by rhtevan** [comment]
@cristianonicolai We do have a related [PR](https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/414) which includes required doc updates. Essentially, this is a minor refactoring of an existing switch property which has been documented [here](https://github.com/jboss-container-images/rhpam-7-openshift-image/blob/34a70b1a94f5cbab161d0e083a3d9a5fe75d40b9/businesscentral/image.yaml#L102-L104). That 'image.yaml' will guide the creation of the final product [documentation](https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.6/html-single/deploying_a_red_hat_process_automation_manager_freeform_managed_server_environment_on_red_hat_openshift_container_platform/index). (Search for KIE_WORKBENCH_CONTROLLER_OPENSHIFT_ENABLED)

**Comment by cristianonicolai** [comment]
@rhtevan what you saying is that docs team will look into the yaml file to create the updated/new version of the following content?
https://github.com/kiegroup/kie-docs/search?q=KIE_WORKBENCH_CONTROLLER_OPENSHIFT_ENABLED&unscoped_q=KIE_WORKBENCH_CONTROLLER_OPENSHIFT_ENABLED

**Comment by rhtevan** [comment]
@cristianonicolai A python script to auto generate and update *.adoc files. There's a comment of every generated adoc file, like this:
```
////
    AUTOGENERATED FILE - this file was generated via
    https://github.com/jboss-container-images/jboss-kie-modules/tree/master/tools/gen-template-doc/tools/gen_template_docs.py.
    Changes to .adoc or HTML files may be overwritten! Please change the
    generator or the input template (https://github.com/jboss-container-images/jboss-kie-modules/tree/master/tools/gen-template-doc/*.in)
////
```

**Pull request merged**
