### PR TITLE
AF-1251: Support to experimental features

### PR DESCRIPTION
**Pull request by pefernan**
AF-1449: Create a default view to show when displaying a disabled experimental feature
AF-1524: Add @ExperimentalFeature support for ResourceType
AF-1445: Experimental Feature Core API

@ederign @tomasdavidorg could you please take a look?

This is a part of an ensemble, please merge with:
https://github.com/kiegroup/appformer/pull/475
https://github.com/kiegroup/kie-wb-common/pull/2138
https://github.com/kiegroup/kie-wb-distributions/pull/819
https://github.com/kiegroup/drools-wb/pull/940
https://github.com/kiegroup/optaplanner-wb/pull/303
https://github.com/kiegroup/kie-docs/pull/1131

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by domhanak** [comment]
Roses are red,
violets are blue,
Jenkins execute full downstream build!

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Pull request merged**
