### PR TITLE
DROOLS-2432: [DMN Designer] Back to from DRD doesn't select proper element in DRG

### PR DESCRIPTION
**Pull request by karreiro**
See: https://issues.jboss.org/browse/DROOLS-2432

Before:
before

After:
after

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@karreiro I checked the PR manually and seems to work fine, thanks, just one question in the [DROOLS-2432](https://issues.jboss.org/browse/DROOLS-2432) comments.

**Comment by karreiro** [comment]
@jomarko Thanks for reporting. As we discussed on IRC, let's handle the mentioned issue separately :-)

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.
--

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Pull request merged**
