### PR TITLE
[master] JBPM-7031: Stunner - disable doing operation in view mode

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit 21c5f66005a3a9b0b3c0319d2710a125fe058e50)

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin @hasys this is the peer PR for the already merged into 7.7.x https://github.com/kiegroup/kie-wb-common/pull/1800

Would you mind review?
Thanks

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
Hi, @romartin @hasys , being realistic his will never get a green/green. Any chance to get this merged now that the full downstream seems to be ok?
Thanks.

**Comment by romartin** [comment]
hey @wmedvede 
Yeah np on merging if the failures are not related, but waiting for @hasys  review. We'd been all really busy last days sorry... so hope he'll be able to do the review soon.
Thanks!

**Comment by domhanak** [comment]
@wmedvede @romartin Is there any special reason, why reviews for cherry-picks are needed? I am curious and wanted to get this clarified :) 
Anyway I will take a look and review!

**Comment by wmedvede** [comment]
@domhanak AFAIK there are no special reason, but, we still need a gatekeeper to get this in, so at least one approval is required (it could be the gatekeeper itself as in this case), and in cases were QE still wants to verify if the PR also works in e.g. master it might be required a second approval. But yeah, it's expected that the "peer" PR should be something quick to get in.

**Comment by domhanak** [comment]
@wmedvede Thanks for the clatification! I assumed there could be some code master that might rbeak this so I run the workbench to be sure . Didn't run into any trouble and was unable to reproduce the issue.
Thanks!

**Pull request merged**
