### PR TITLE
AF-1028 : [Project Oriented] Standalone perspectives are broken

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/AF-1028

https://github.com/kiegroup/kie-wb-common/pull/1524
https://github.com/kiegroup/kie-wb-distributions/pull/714
https://github.com/kiegroup/kie-docs/pull/735

### CODE REVIEW

**Comment by Rikkola** [comment]
ping @barboras7 
and @jhrcek you were marked as the reporter for this.

There is still one issue, but I think it needs another ticket. This now gets you to the file if you set the path, but if you open any other file from the Project Explorer. It opens correctly, but the Project Explorer then disappears.

**Comment by jhrcek** [comment]
@Rikkola Should we file the ticket or would you like to do it?
I'm going to test this locally / update upstream selenium test for this tomorrow.
In the meantime Jenkins execute full downstream build, please.

**Comment by jhrcek** [comment]
@Rikkola I'm playing with this locally. I'm unable to make this work. I'm probably using wrong query string parameters..

Could you please provide few example URLs opening standalone editors that work?

I vaguely recall, that you were removing AuthoringPerspective recently, so this (what we're using in community selenium tests [here](https://github.com/kiegroup/kie-wb-distributions/blob/master/kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/StandalonePerspectivesIntegrationTest.java#L36-L39)) is probably not expected to work anymore?

```
http://localhost:8080/kie-wb/kie-wb.jsp?standalone=true&perspective=AuthoringPerspective
http://localhost:8080/kie-wb/kie-wb.jsp?standalone=true&perspective=AuthoringPerspective&header=AppNavBar
```

Also we'll definitely need update of [related documentation](https://github.com/kiegroup/kie-docs/blob/master/docs/product-user-guide/src/main/asciidoc/business-central-embedding-proc.adoc) in kie-docs..

**Comment by Rikkola** [comment]
Updated the docs with the examples.

**Comment by manstis** [comment]
@Rikkola Conflicts to fix and then good to go.

**Comment by Rikkola** [comment]
@manstis This for some weird reason only fixes the issue for kie-drools-wb and kie-wb is broken, so I'll be back on fixing this later. Might be on Monday since this ticket severity got downgraded and I have 3 with higher priority to fix tomorrow.

**Comment by manstis** [comment]
@Rikkola ok, no problem.. was just reviewing "green" and "approved" PRs to clear some up.

**Comment by Rikkola** [comment]
I'll check the failing test locally. I bet some recent changes are not merging right.

**Comment by Rikkola** [comment]
jenkins please retest this

**Comment by Rikkola** [comment]
These work locally. Trying this 
jenkins please retest this

**Comment by Rikkola** [comment]
These failed:   org.kie.workbench.common.services.backend.compiler.nio.kie.KieDefaultMavenCompilerTest.buildWithJGitDecoratorTest
    org.kie.workbench.common.services.backend.validation.asset.ValidatorTest.testFilterMessageWhenMessageIsInvalid
    org.kie.workbench.common.services.backend.validation.asset.ValidatorTest.testFilterMessageWhenMessageIsInvalid

jenkins please retest this

**Comment by Rikkola** [comment]
Thank you @manstis

**Pull request merged**
