### PR TITLE
[AF-1407-7.7.x]: git import is not backward compatible

### PR DESCRIPTION
**Pull request by adrielparedes**
Removed Mandatory dependencies validator and Plugin validator. They will be improved and added again in a future.

### CODE REVIEW

**Comment by mareknovotny** [comment]
just formal question, can you change the commit message to not duplicate the referenced AF-1407 jira? Instead of that please use RHPAM-1413 to be identified by JIRA integration properly?

**Comment by porcelli** [comment]
@mareknovotny AppFormer just uses community JIRAs references. the same commit messages will be ok as during squash can be fixed the commit message

**Comment by mareknovotny** [comment]
well, it will be still duplicated if you don't change PR title here. 
```
[AF-1407-7.7.x]: [AF-1407]
```

**Comment by ederign** [comment]
@mareknovotny can we wait until tomorrow to @tomasdavidorg take a look on this?

He already approved this PR on master, but we did some changes in order to make it simpler.

**Comment by mareknovotny** [comment]
@ederign yes, we can wait for @tomasdavidorg's review

**Pull request merged**
