### PR TITLE
KOGITO-2899: DMN: HTML elements are not being removed from DOM

### PR DESCRIPTION
**Pull request by handreyrc**
@karreiro, @romartin: Please, could you review this PR?
Thanks

### CODE REVIEW

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by handreyrc** [comment]
Jenkins execute compile downstream build

**Comment by handreyrc** [comment]
Jenkins execute compile downstream build

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Comment by karreiro** [comment]
Jenkins please execute compile downstream build.

**Comment by karreiro** [comment]
Jenkins please execute downstream build.

**Comment by handreyrc** [comment]
Jenkins execute full downstream build

**Pull request merged**
