### PR TITLE
RHPAM-2360 - Signal name cannot be dynamic

### PR DESCRIPTION
**Pull request by Josephblt**
https://issues.jboss.org/browse/RHPAM-2360

Signal now supports mixed expressions (static and dynamic).

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Hello @LuboTerifaj. All changes done. Changed the help message and the validation message. Just keep in mind, the validation message does not support internationalization. For that problem I created [JBPM-8807](https://issues.jboss.org/browse/JBPM-8807). Thanks

**Comment by romartin** [comment]
missing your review @LuboTerifaj  plz

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Hello @LuboTerifaj. All set. Fixed the message and the field accepts single char in the dynamic variables. Thx

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Pull request merged**
