### PR TITLE
DROOLS-4616: [DMN Designer] Data Types - Apply new layout in the DTList rows

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/DROOLS-4616

Screen Shot 2019-10-31 at 09 43 08

Notice: The tooltip in the Type label will be implemented by [DROOLS-4681](https://issues.jboss.org/browse/DROOLS-4681).

### CODE REVIEW

**Comment by karreiro** [comment]
(rebasing the branch... 👀)

**Comment by karreiro** [comment]
This PR is ready for the review 🚀

**Comment by jomarko** [comment]
@karreiro will do tomorrow.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
@danielzhe just friendly reminder. Please take a look when you have a moment :-)

**Comment by danielzhe** [comment]
@karreiro Approved! Very cool details. :)

**Pull request merged**
