### PR TITLE
KOGITO-6671: Render Question, Allowed Answers on Documentation Page

### PR DESCRIPTION
**Pull request by jomarko**
Backport of kiegroup/kie-tools#814

### CODE REVIEW

**Comment by jomarko** [comment]
Jenkins do fdb

**Review by yesamer — APPROVED** [review]
Thank you @jomarko for backporting this.

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
@yesamer please merge

**Comment by yesamer** [comment]
> @yesamer please merge

@jomarko I Don't have rights to merge here :(

**Comment by jomarko** [comment]
@kiegroup/gatekeepers please merge

**Pull request merged**
