### PR TITLE
Revert "Revert "DROOLS-5737: [DMN Designer] change in Decision Navigator does not dirty context"

### PR DESCRIPTION
**Pull request by danielzhe**
The original PR was already tested and merged, but it have some test issues (we didn't waited for the green build).

Then the original PR was reverted.

And this is just the "revert of the revert" with the fixed tests. There's really nothing to test, just asking for @jstastny-cz and @vpellegrino to take a look to see if is ok to merge.

Now we have a green.

ORIGINAL PR MERGED: https://github.com/kiegroup/kie-wb-common/pull/3468

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by danielzhe** [comment]
jenkins do fdb

**Comment by danielzhe** [comment]
jenkins do fdb

**Comment by danielzhe** [comment]
Jenkins retest this

**Comment by danielzhe** [comment]
Jenkins do fdb

**Review by vpellegrino — APPROVED** [review]
LGTM, thank you @danielzhe

**Comment by danielzhe** [comment]
Can you take a look at this, please, @jstastny-cz? It's an previous approved PR already merged, but we reverted due to a failing test. Now the test is fixed and all builds green. I don't think is necessary to re-test this since there's only changes in a single previous failing test.

**Review by jstastny-cz — APPROVED** [review]

**Comment by danielzhe** [comment]
Can someone of the @kiegroup/gatekeepers merge this one, please?

**Pull request merged**
