### PR TITLE
[7.7.x] JBPM-7148: [Workbench] Enable and make Stunner the default process editor

### PR DESCRIPTION
**Pull request by pefernan**
Backport of https://github.com/kiegroup/kie-wb-common/pull/1758

@romartin @manstis could you please review?

This is part of an ensemble, please merge with:
https://github.com/kiegroup/kie-wb-common/pull/1759
https://github.com/kiegroup/jbpm-designer/pull/781
https://github.com/kiegroup/kie-wb-distributions/pull/746

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
unrelated tests failures, I don't know what else to do

**Comment by manstis** [comment]
@pefernan Wait until https://github.com/kiegroup/kie-wb-distributions/pull/746 completes and then I'll merge (I don't care if it is green or red.. it's only a couple of properties files that should not break anything).

**Comment by manstis** [comment]
@pefernan Second thoughts, if I don't care about the status of https://github.com/kiegroup/kie-wb-distributions/pull/746 let's merge them all now anyway :-)

**Pull request merged**
