### PR TITLE
GUVNOR-3408: [DMN Editor] Loading DMN diagram causes UI error

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-3408

Fix following https://github.com/ahome-it/lienzo-core/pull/172

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Opps. Fat fingers. Closed by mistake. Re-opened.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@tarilabs FYI.. you should be OK now.

**Comment by tarilabs** [comment]
thanks @manstis

**Pull request merged**
