### PR TITLE
JBPM-6817: Stunner - Embedded sub-process has the same icon in toolbox as Ad-Hoc sub-process

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin, @wmedvede,

I am accidentally found how to fix one small issue.

In general, I guess, we need some global refactoring for easier test coverage here, but I am not sure about the future about this component does it cost to refactor now or not.

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin,

shape is missing for the Embedded subprocess [see here](https://github.com/kiegroup/kie-wb-common/tree/8bdc30b1439b3bdcc1ad46c50437bd39be977f38/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/resources/org/kie/workbench/common/stunner/bpmn/client/resources/images/shapes), but, if I correct, it is the same as for AdHoc subprocess shape.

Not sure, should I copy shape, rename it to more generic name or ask someone from UX to provide this shape.

CC @wrnkld

**Comment by romartin** [comment]
hey @hasys @wmedvede If you don't mind I'll close this PR as I'm actually working with UX on the shapes and icons re-design ([JBPM-6391](https://issues.jboss.org/browse/JBPM-6391)), so I've the changes from this commit also included in my work. I'll provide the PR for it soon.
Anyway thanks for the collaboration, jsut that it results now faster for me not rebasing again on top of this... so if you agree I'll assign the JBPM-6817 to me and fix it when comiting the work for the JBPM-6391, Does that sounds good?

**Comment by hasys** [comment]
Hi @romartin,

yes, sure. np.

**Pull request closed without merging**
