### PR TITLE
[7.67.x] JBPM-10083: Legacy (jBPM) Process Designer Removal

### PR DESCRIPTION
**Pull request by inodeman**
**Thank you for submitting this pull request**

**JIRA**: [JBPM-10083](https://issues.redhat.com/browse/JBPM-10083)

**Referenced Pull Requests**:
https://github.com/kiegroup/kie-wb-distributions/pull/1177
* link 2
* link 3 etc.

**Business Central**: [WAR file](https://drive.google.com/drive/folders/1V3MguR74O8CHxfqWL-ZdFYXyJSzXxn2A?usp=sharing)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by inodeman** [comment]
Hi @romartin @LuboTerifaj can you review this cherry-pick for 7.67.x branch, War file can be found here. https://drive.google.com/drive/folders/1V3MguR74O8CHxfqWL-ZdFYXyJSzXxn2A?usp=sharing

**Comment by LuboTerifaj** [comment]
Hello @inodeman ,

does the war you uploaded work properly on your machine?

I have got the following error in server.log:
`[stderr] (MSC service thread 1-5) Failed to bootstrap errai marshalling system!
ERROR [stderr] (MSC service thread 1-5) org.jboss.errai.marshalling.client.api.exceptions.InvalidMappingException: there is no custom mapping or default no-arg constructor to map: org.optaplanner.core.api.score.buildin.hardsoftdouble.HardSoftDoubleScore`

Could you please check that?

Thanks!

**Comment by inodeman** [comment]
Jenkins run fdb

**Comment by inodeman** [comment]
Hi @LuboTerifaj I downloader War file and ran it without any issues, did not see that log either

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by LuboTerifaj** [comment]
Hey @mareknovotny , this PR was not approved for merging. Please avoid merging PRs without reviewers approval. Thanks!

**Comment by mareknovotny** [comment]
well, this was backport and for 7.67.x-blue it was approved, so i take it as the same PR.

**Pull request merged**
