### PR TITLE
JBPM-5790: Case Modeller: Change containment rules for Diagram and St…

### PR DESCRIPTION
**Pull request by manstis**
…ages

See https://issues.jboss.org/browse/JBPM-5790

This PR changes the containment rules for "Diagram" to only only "Sub-processes" as direct descendants.

### CODE REVIEW

**Comment by manstis** [comment]
... and of course code-formatting has had a play with some of the classes.

**Comment by manstis** [comment]
@romartin Are you indisposed? You're my only peer for these reviews!

**Comment by romartin** [comment]
Hey @manstis , the bpmn stuff works good for me, but I'm not able to create/open any diagram for CM:

`Unable to complete your request. The following exception occurred: (TypeError) : Cannot read property 'getIconRendererType_0_g$' of null.`

I thinks this error is due to something about palette and its icons, probably @pefernan can help here.

**Comment by manstis** [comment]
@romartin Fixed.

**Pull request merged**
