### PR TITLE
JBPM-6701: Stunner - Issues when nesting BPMN containers

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/JBPM-6701

Before:
before

After:
after

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
Looking on the code, I have question as the jira description mentions also general containers, but it seems to me this PR solves just nesting of lanes, am I right @karreiro?

**Comment by karreiro** [comment]
@jomarko yes, the scope of the fix comprehend only Lanes. Nevertheless, I've tested elements that can contain others (like _SubProcess/Event_) and they're working fine.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
(rebasing the branch ^)

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by jomarko** [comment]
Found issue filed as [JBPM-7178](https://issues.jboss.org/browse/JBPM-7178)

**Pull request merged**
