### PR TITLE
KOGITO-3547: [DMN Designer] Embeddable editors - Enable included models tab on embeddable editors

### PR DESCRIPTION
**Pull request by karreiro**
**JIRA**: [KOGITO-3547](https://issues.redhat.com/browse/KOGITO-3547): [DMN Designer] Embeddable editors - Enable included models tab on embeddable editors

**VS Code**: [plugin](https://www.dropbox.com/s/9c1fg3b7hdjnnl3/plugin-KOGITO-3547.vsix?dl=0)

---

Screen Shot 2020-10-06 at 16 05 29
Screen Shot 2020-10-06 at 16 04 00

---

<pre>
To retest a PR or trigger a specific build please add a comment:

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</pre>

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Hey @jstastny-cz,

@paulovmr is currently working on a new channel, the **EMBEDDED** channel - which's not available yet.

This PR prepares the editor to receive this new channel. You can test the VSCode plugin linked in this PR and check that the Included Models tab is still working, and the logo of drools still works on the Documentation tab as well :-)

**Review by paulovmr — APPROVED** [review]

**Review by jstastny-cz — APPROVED** [review]
Looks good.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Pull request merged**
