### PR TITLE
AF-2760 :Permission configured in business-central is not applied when doing git clone from outside of BC

### PR DESCRIPTION
**Pull request by RishiRajAnand**
(cherry picked from commit a86587f03fd1a9d8f95b6f8d1749d77a1b974f5a)

**Thank you for submitting this pull request**

**AF-2760**: https://issues.redhat.com/browse/AF-2760

**Referenced Pull Requests**:
https://github.com/kiegroup/appformer/pull/1194

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Comment by RishiRajAnand** [comment]
jenkins retest this

**Review by Srihari1192 — APPROVED** [review]

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Comment by RishiRajAnand** [comment]
jenkins retest this

**Comment by RishiRajAnand** [comment]
jenkins do fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Ensemble PR https://github.com/kiegroup/kie-wb-distributions/pull/1123

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
@Srihari1192 @adrielparedes Test failures are unrelated

**Comment by akumar074** [comment]
Jenkins run fdb

**Review by adrielparedes — APPROVED** [review]

**Comment by adrielparedes** [comment]
@RishiRajAnand let me know when FDB is green so I can merge

**Comment by akumar074** [comment]
FDB Test failures are related to the change.

**Comment by akumar074** [comment]
* FDB Test failures are NOT related to the change.

**Pull request merged**
