### PR TITLE
KOGITO-2166 - VSCode editor - Package property: default is not a valid Java package name

### PR DESCRIPTION
**Pull request by Josephblt**
https://issues.redhat.com/browse/KOGITO-2166

Removing this as it is not related to the Package property

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by evacchi** [comment]
@Josephblt so shall i remove the change to the file you mentioned?

**Comment by evacchi** [comment]
not sure why the build is still red though

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Please @hasys missing your review. Thanks!

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by romartin** [comment]
Please @domhanak  @LuboTerifaj  this issue is important and it's pretty easy to verify. Could we please try to move this forward?

Thanks in advance!

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins please retest this

**Comment by domhanak** [comment]
jenkins execute full downstream production build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Please @Josephblt lemme know once builds are ok and I'll merge.

Thanks everyone for your great work!

**Comment by Josephblt** [comment]
jenkins execute full downstream production build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
jenkins execute full downstream production build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hey @romartin this is ready to merge.

**Pull request merged**
