### PR TITLE
JBPM-9448: Remove the Case Modeler (Tech Preview) asset type

### PR DESCRIPTION
**Pull request by hasys**
**JIRA**: [RHPAM-3229](https://issues.redhat.com/browse/RHPAM-3229)

**Business Central**: [WAR file](https://drive.google.com/file/d/1PWc_rTpYm7Y0z0gr2lBPmrlOh63lEAV6/view?usp=sharing)

**VS Code**: not needed

<details>
<summary>
Hi @romartin, @LuboTerifaj, I tested locally built Business Central and won't create Case Management asset there. PR is ready for review, thank you!
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by hasys** [comment]
jenkins do cdb

**Review by romartin — APPROVED** [review]
Cool, thanks @hasys , looks good to me!

**Comment by LuboTerifaj** [comment]
Jenkins execute fdb

**Comment by hasys** [comment]
Jenkins retest this

**Comment by hasys** [comment]
Hi @LuboTerifaj why do we need fdb here? fdc is green and I attached WAR file to the PR.

**Comment by LuboTerifaj** [comment]
@hasys we always trigger the full downstream build to run tests and generate war or has something changed?

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @hasys ,

Case Management (Preview) option from Settings -> Roles/Groups/Users -> Editors hasn't been removed.

Can you please have a look at it?

Thank you!

**Comment by romartin** [comment]
maybe the WAR is not generated properly @hasys ?

**Comment by hasys** [comment]
Hi @LuboTerifaj, great catch, fixed:

image

I updated link from PR description.

Thank you!

**Comment by hasys** [comment]
jenkins do fdb

**Comment by hasys** [comment]
@LuboTerifaj, @romartin,

about fdb it wasn't stable for a long time and since I still building WAR file locally, PR build executes all tests from this repo, fdc checks that nothing broken for anybody from other teams I guess we are safe do not use fdb now.

Keep in mind that fdb keeps only 10 last builds now, and if review is happening with a week delay it is just no chance it will keep the build file for this amount of time.

**Comment by hasys** [comment]
Hi @romartin, I crated a community ticked [JBPM-9448](https://issues.redhat.com/browse/JBPM-9448) and updated PR title with community issue number as you asked.

Thank you, good catch!

**Comment by romartin** [comment]
thanks @hasys !

**Review by LuboTerifaj — APPROVED** [review]
It looks good to me. Thanks @hasys .

**Comment by hasys** [comment]
Hi @romartin,

PR is ready for merge. Thank you!

**Pull request merged**
