### PR TITLE
AF-557: Add breadcrumbs on the Admin perspective

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
Part of an ensemble:
* https://github.com/AppFormer/uberfire/pull/766
* https://github.com/kiegroup/kie-wb-common/pull/968

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Hi @paulovmr, works fine. The only thing which might be confusing for the users is when you switch from Roles dock to Users dock the breadcrumb value does not change.

screenshot from 2017-07-11 10-52-57
screenshot from 2017-07-11 10-53-08

**Comment by paulovmr** [comment]
Hi @tomasdavidorg , after some thinking, I decided to change the breadcrumbs to "Admin > Security", since all categories (roles, users and groups) can be accessed from there. Also, I don't think it's necessary to explicitly show which one is opened in the breadcrumbs, since there are tabs already showing that.

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Thanks @paulovmr, +1.

**Comment by manstis** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Pull request merged**
