### PR TITLE
DROOLS-3234 : Add a Donut widget to improve the visualisation of test report screen

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-3234

This has been a time sink for few reasons. I suggest this layout since if we make the donut look like the wireframe we need to edit the widget and that is even more time consuming.

Optionally we can drop the legend specified in the Donut widget and make a custom separate item that looks like the original design. This will not take that long.

image

### CODE REVIEW

**Comment by Rikkola** [comment]
Let's wait with the reviews. There is some doubts about what the right donut is.

**Comment by kkufova** [comment]
@Rikkola, could you please rebase the PR on `master`?

**Comment by kkufova** [comment]
I'm waiting with the review until [DROOLS-3378](https://issues.jboss.org/browse/DROOLS-3378) is fixed.

**Comment by Rikkola** [comment]
@kkufova @lclay2 the number formatting can be changed. Everything else on the other hand is likely to change once https://github.com/kiegroup/appformer/pull/506 lands in.

**Comment by kkufova** [comment]
@Rikkola, could you please check this and let me know whether another review is required?

**Comment by Rikkola** [comment]
@kkufova number of passed/failed tests is now a whole number.

**Comment by Rikkola** [comment]
Also the donut works without internet connection. So I assume it is now setup as it should be.

**Comment by kkufova** [comment]
@Rikkola, could you please take a look at the failing tests?

**Comment by Rikkola** [comment]
Fixed TestRunnerReportingScreenTest.testRunTimeInMinutes. I doubt the other test is relevant to this.

**Comment by Rikkola** [comment]
@kkufova perhaps hiding the donut is the reset for it, since I don't think the widget supports anything better.

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
@manstis 

Can you please squash and merge this?

**Pull request merged**
