### PR TITLE
JBPM-7434: Stunner - New Marshallers: Sequence flow default magnet is center

### PR DESCRIPTION
**Pull request by evacchi**
@LuboTerifaj @hasys @romartin

### CODE REVIEW

**Comment by evacchi** [comment]
jenkins execute full downstream build

**Comment by evacchi** [comment]
@romartin yup -- and to reproduce old marshallers behavior (which is... to work around that issue :P)

**Comment by romartin** [comment]
@LuboTerifaj missing review please

**Comment by evacchi** [comment]
see #1725

**Pull request closed without merging**
