### PR TITLE
[7.7.x] RHPAM-838 (JBPM-7118): Stunner - Mediators (zoom,pan) not working properly

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/RHPAM-838

---

Cherry picked from https://github.com/kiegroup/kie-wb-common/pull/1675

---

Part of an ensemble:
- https://github.com/kiegroup/lienzo-core/pull/23
- https://github.com/kiegroup/lienzo-tests/pull/19
- https://github.com/kiegroup/kie-wb-common/pull/1702

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Comment by karreiro** [comment]
Jenkins execute full downstream build.

**Pull request merged**
