### PR TITLE
New contributors for spaces and projects

### PR DESCRIPTION
**Pull request by paulovmr**
Part of an ensemble:
* https://github.com/kiegroup/appformer/pull/508
* https://github.com/kiegroup/kie-wb-common/pull/2222
* https://github.com/kiegroup/drools-wb/pull/979

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins retest this
jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins retest this

jenkins execute full downstream build

**Comment by barboras7** [comment]
@paulovmr, @ederign Hi guys,
I have some questions regarding this feature:
1. When you create a project, all space contributors are copied to the project being created. When you delete some space contributors, they are still present in the project contributors. With a big number of projects and spaces, this might get a bit messy. (This both applies to creating and deleting space contributors, the changes are not propagated to projects)
2. The naming "Contributors" clashes with the "Contributors" in the Metrics tab 
3. Why is this not a part of the security management?
4. If we call the tab "Contributors", shouldn't everyone that contributes somehow to the project/space be in the list? (taking GitHub as an example, everyone who make a commit is a contributor)
5. Could the list of "Contributors" be up-to-date with the users deleted from the business central? If this is not implemented now, we might forget about this in the future and it might lead to some confusion. 
6. Does adding a contributor with "Contributor" role make sense? If there will be no special permissions that this role has.

Could you, please, somehow answer these questions? Maybe the implementation "as is" makes sense with more context provided :slightly_smiling_face:

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
@barboras7 Hi, here are the answers:

1. I agree, I think it is best to remove those contributors from the children projects as well. I will change that. 
2. I don’t think it is a problem, because both refer to the same users (space/project contributors).
3. As part of this Jira (https://issues.jboss.org/browse/AF-1639), we plan to use both security management and contributors to manage permissions related to spaces and projects. We think this new approach offers an improved usability, because this way the admin/owner can define which are the contributors of a space/project, while the security perspective allows to define which spaces/projects an user has access to (“opposite flow”).
4. For now only the ones that were registered in the tab will be shown there. In the future we can think in a way to improve this.
5. Yes, I will do that improvement too.
6. This role will allow users to create projects inside the spaces, and also modify projects in which they are contributors. Deploy won’t be allowed.

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
Hi @paulovmr,
I checked the new version of the PR and it looks good. However, I have one concern/question. When you delete a user from the business central, it disappears from the contributors list only after you stop the business central and start it again. Could this be somehow fixed or is there some logic that prevents us from fixing it?

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by barboras7** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
Hi @barboras7 , I've fixed the delete user behaviour you commented, now the user should disappear right after the deletion happens.

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins execute full downstream build

**Comment by paulovmr** [comment]
Reopened here: https://github.com/kiegroup/kie-wb-common/pull/2350

**Pull request closed without merging**
