### PR TITLE
DROOLS-3425 : Unexpected behavior of docks when multiple editors are opened

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-3425

@wmedvede This should fix, but not sure since having trouble with the showcase.

### CODE REVIEW

**Comment by wmedvede** [comment]
@manstis or @romartin would you mind guys merge this PR?
Thanks!

**Comment by wmedvede** [comment]
FYI @Josephblt

**Comment by manstis** [comment]
@wmedvede Do we need QE to review (since the changed class isn't just for Stunner standalone)?

**Comment by romartin** [comment]
Can you please @hasys @Josephblt review this please?? Thanks!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin, @Rikkola,

I am not able to reproduce this issue neither with 7.20.Final nor with latest issue.

So, I tested Full Donwstream Build all looks good, I didn't notice changes. Probably, @kkufova will know more about this.

**Comment by kkufova** [comment]
I have no idea what this issue is about. As far as I know, we already merged a bunch of PRs that addressed the issue. @Rikkola, could you please let me know what this PR solves?

**Comment by Josephblt** [comment]
Hey guys. Just tested this and it looks goods. All Stunner docks are in place:

- Diagram Properties
- Explore Diagram
- Project Explorer

They all work as expected.
Code is fine by me, too. 
Thanks

**Comment by Rikkola** [comment]
@kkufova this was just for the webapp that the stunner devs use. This does not affect the war we release.

**Pull request merged**
