### PR TITLE
[7.3.x] JBPM-6389 : Upload file in task form is not working for eap7

### PR DESCRIPTION
**Pull request by nmirasch**
changed the reference to the document upload file servlet, making it relative removing the slash

### CODE REVIEW

**Comment by nmirasch** [comment]
@pefernan could you take a look on this? thanks!

**Comment by pefernan** [comment]
@neus could you provide same fix for 8.0?

**Comment by nmirasch** [comment]
@pefernan sure, I was waiting this PR merge before generating that, to make sure the code is absolutely approved :)

**Comment by jsoltes** [comment]
@nmirasch @pefernan I am sorry, I missed notification for this one... jenkins execute full downsteam build

**Comment by jsoltes** [comment]
jenkins execute full downstream build

**Comment by jsoltes** [comment]
@nmirasch do you mind cherry-picking to master, too?

**Pull request merged**
