### PR TITLE
DROOLS-4321: [DMN Designer] Search feature - DMN Data Types must be searchable elements

### PR DESCRIPTION
**Pull request by karreiro**
See: https://issues.jboss.org/browse/DROOLS-4321

---

Part of an ensemble:
- https://github.com/kiegroup/appformer/pull/762
- https://github.com/kiegroup/kie-wb-common/pull/2791
- https://github.com/kiegroup/drools-wb/pull/1207

### CODE REVIEW

**Comment by jomarko** [comment]
@karreiro thank you for the PR, I will review once the #2785 is in.

**Comment by karreiro** [comment]
@jomarko The https://github.com/kiegroup/kie-wb-common/pull/2785 was merged, so this PR is ready for the review :-)

**Comment by karreiro** [comment]
@jomarko thank you for the comment :-)

I'm already working on the fixes for these scenarios:
- I) Search when data types collapsed;
- II) Search data type, edit it, save, continue the search;
- III) Search data type, remove it same as above;
- IV) Search Data Type, Search Model, Search Data Type.

However, I think we could open a UX JIRA for these:
- V) Search Constraints;
- VI) Search Is List.

It's easy to index other fields. But I wouldn't do that for now. Considering our graph, we look only the at the name of DRG elements; we don't look at their type. Personally, as a user, I think that would be unexpected to find a Data Type that has some constraint that matches with my search term. Thus, I think we need a more in-depth discussion about it.

Thanks again for the comment.

**Comment by jomarko** [comment]
@karreiro thank you, please let me know when I should review again.

**Comment by karreiro** [comment]
@jomarko Changes applied, and the issues are fixed :-)

Notice that the fixes required new PRs at `appformer` (https://github.com/kiegroup/appformer/pull/762) and `drools-wb` (https://github.com/kiegroup/drools-wb/pull/1207).

**Pull request merged**
