### PR TITLE
DROOLS-4724: [DMN Designer] Do not default to a LiteralExpression when no expression is defined

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-4724

Unit Test for kogito marshaller will be in https://issues.jboss.org/browse/KOGITO-406

Unit Test for existing backend marshalling is included in this PR.

I've manually tested (creating, saving and re-opening) with:-
- `-webapp-standalone` (server side marshalling)
- `-webapp-kogito-testing` (client side marshalling)
- Business Central (server side marshalling)

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Hi @jomarko I've fixed the issue with `ContextEntry` as proposed by @tarilabs on the JIRA.

All good to re-review (I've tested successfully with `-webapp-standalone` and `-webapp-kogito-testing`.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by jomarko** [comment]
@manstis the failing tests are suspicious, haven't we broken something by our work on grid performance, scrolling .... ?

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@jomarko It's a concern for sure.. however _other_ PRs seem to be building OK.

I'm recompiling this repository and `drools-wb` with tests locally to check.

**Comment by manstis** [comment]
@jomarko Please see my email "[bsig] Migrating to jUnit 5".

It appears a change in `droolsjbpm-build-bootstrap` has broken the build. https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1124 will revert it.. but IDK that then breaks OptaPlanner.

**Comment by jomarko** [comment]
@manstis thank you, let me know once full build is green please.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
@jomarko FDB is now green.

**Comment by jomarko** [comment]
@manstis ok, will review tomorrow, if no issue found, will ask gatekeepers to merge

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
(Closed accidentally, reopened)

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
@jomarko Given the lack of [reply](https://issues.redhat.com/browse/DROOLS-4724?focusedCommentId=13823166&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13823166) from Matteo re: the only outstanding issue being different levels of message for BKMs I think this PR can be merged and I'll make a JIRA for `kie-dmn` stating the difference in levels reported by `kie-dmn-validation` and `KieBuilder`. WDYT?

**Pull request merged**
