### PR TITLE
KOGITO-5003: DMN editor removing edges for duplicate Decision Nodes on canvas

### PR DESCRIPTION
**Pull request by danielzhe**
**JIRA**: [KOGITO-5003](https://issues.redhat.com/browse/KOGITO-5003)

This is the backport for kie-wb-common of https://github.com/kiegroup/kogito-editors-java/pull/52

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by jstastny-cz** [comment]
jenkins do fdb

**Review by karreiro — APPROVED** [review]
Thank you, @danielzhe! Great stuff!

**Comment by danielzhe** [comment]
jenkins do fdb

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by danielzhe** [comment]
Jenkins do fdb.

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Pull request merged**
