### PR TITLE
JBPM-5618:  disabling the radio widgets if radioGroup is read-only

### PR DESCRIPTION
**Pull request by alessioscalici**
Updating each radio button disabled status while refreshing the radioGroup widget
@pefernan can you please review it?

### CODE REVIEW

**Comment by pefernan** [comment]
ok to test

**Comment by pefernan** [comment]
+1 thanks @alessioscalici

**Comment by manstis** [comment]
ok to test

(But I think this is unnecessary)

**Comment by pefernan** [comment]
@manstis is it ok to merge this?

**Pull request merged**
