### PR TITLE
JBPM-7560 Stunner - Create Marshaller tests for Conditional Start Events

### PR DESCRIPTION
**Pull request by LuboTerifaj**

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
Hi @hasys @evacchi 
Can you have a look?

Thank you!

**Comment by evacchi** [comment]
please verify / report bugs with new marshallers

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Pull request merged**
