### PR TITLE
[7.48.x] KOGITO-4539: [DMN Designer] DMN takes too long to open models with too many nodes

### PR DESCRIPTION
**Pull request by karreiro**
**JIRA**: [KOGITO-4539](https://issues.redhat.com/browse/KOGITO-4539): [DMN Designer] DMN takes too long to open models with too many nodes

Cherry-picked from https://github.com/kiegroup/kie-wb-common/pull/3578

--

**- Business Central war (7.48.x)**: [war file](https://www.dropbox.com/s/urwzxb1h2pdtmdr/KOGITO-4539-7.48.x-business-central.war?dl=0)

**- VS Code plugin (7.48.x)**: [plugin file](https://www.dropbox.com/s/4kjegh5fwp6qqrh/KOGITO-4539-7.48.x-vscode.vsix?dl=0)

--

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins do fdb.

**Comment by jomarko** [comment]
Tasks to be performed during manual review as we touched Decision Navigator refresh mechanism.

Verify Decision Navigator is refreshed after:
- [ ] closing and reopening diagram
- [ ] opening another diagram
- [ ] switching tabs of editor
- [ ] switching DRDs
- [ ] switching expression and graph editor

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by karreiro** [comment]
Jenkins please retest this.

**Review by Rikkola — APPROVED** [review]

**Review by jomarko — APPROVED** [review]

**Pull request merged**
