### PR TITLE
DROOLS-3371: [DMN Designer] Add Decision Service to Palette

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-3371

This PR simply adds a `DecisionService` node to the Palette.

The node can be added to the diagram and `Decision` added to it.

Saving/loading is covered by https://issues.jboss.org/browse/DROOLS-3372

The UX design of the palette item and node is covered by https://issues.jboss.org/browse/DROOLS-3373

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@jomarko Updates made in new PR.

**Comment by jomarko** [comment]
@manstis hi, both dimensions and dragging inside/outside are fixed now?

**Comment by manstis** [comment]
@jomarko Absolutely.

**Comment by manstis** [comment]
@danielzhe Could you please review?

I added you as an approver as this PR mainly contains Stunner related changes.

If you'd rather somebody else review please say and I'll reassign.

**Comment by danielzhe** [comment]
It worked good. I think maybe we can work on the icons on the palette, because Decision Service is equals to Decision and is very close to Business Knowledge Model. I don't know you already discussed this in the past. Maybe some colours too?

**Comment by manstis** [comment]
@danielzhe Thank-you for the review; the icons are temporary until https://issues.jboss.org/browse/DROOLS-3373 is completed and we replace the ones used here with ones from UX.

**Pull request merged**
