### PR TITLE
AF-613: Example projects URL should be customizable by a system property

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
@porcelli could you take a look? Thanks!

**Comment by paulovmr** [comment]
@porcelli I've now used real system properties instead of mocking them. WDYT?

**Comment by porcelli** [comment]
jenkins please test this

**Comment by paulovmr** [comment]
jenkins please test this

**Comment by paulovmr** [comment]
[7.3.x](https://github.com/kiegroup/kie-wb-common/pull/1169) PR.

**Pull request merged**
