### PR TITLE
JBPM-8544: Stunner - Assignments type is not visible for Assignments of Catching and Start event

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi @romartin @hasys would you mind review this PR?
Thanks.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
full build failed as usual in non related stuff but no information was provided, artifacts were not generated

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by wmedvede** [comment]
looks like CI is failing a again, probably due to outdated nexus

07:48:56 [WARNING] The requested profile "business-central" could not be activated because it does not exist.
07:48:56 [WARNING] The requested profile "wildfly" could not be activated because it does not exist.
07:48:56 [WARNING] The requested profile "sourcemaps" could not be activated because it does not exist.
07:48:56 [WARNING] The requested profile "no-showcase" could not be activated because it does not exist.
07:48:56 [ERROR] Failed to execute goal on project optaplanner-wb-domain-editor-backend: Could not resolve dependencies for project org.optaplanner:optaplanner-wb-domain-editor-backend:jar:7.24.0-SNAPSHOT: Could not find artifact org.drools:drools-wb-globals-editor-api:jar:7.24.0-SNAPSHOT in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/) -> [Help 1]
07:48:56 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project optaplanner-wb-domain-editor-backend: Could not resolve dependencies for project org.optaplanner:optaplanner-wb-domain-editor-backend:jar:7.24.0-SNAPSHOT: Could not find artifact org.drools:drools-wb-globals-editor-api:jar:7.24.0-SNAPSHOT in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/)
07:48:56     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:249)
07:48:56     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:145)
07:48:56     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:246)
07:48:56     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:200)
07:48:56     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Pull request merged**
