### PR TITLE
KOGITO-990 BPMN modeler saving data assignments does not save process model

### PR DESCRIPTION
**Pull request by hasys**
All **Save** labels of properties editors replaced to **OK**

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
@hasys something wrong with regular build

**Comment by hasys** [comment]
Hi @domhanak, sorry fixed.

Sonar Cloud failing due to duplications introduced earlier, this PR is just renames and label changes. Widgets refactoring is not a part of this Jira issue.

Thank you!

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins fails looks unrelated to my changes

<details>
  <summary>Error log</summary>
  <pre>11:15:49 [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ curriculumcourse ---
11:15:49 [INFO] 
11:15:49 [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ optacloud ---
11:15:49 [INFO] kieMap not present
11:15:49 [INFO] KieModule successfully built!
11:15:49 [ERROR] Failed to execute goal org.kie:kie-maven-plugin:7.34.0-SNAPSHOT:build (default-build) on project mortgage-process: Execution default-build of goal org.kie:kie-maven-plugin:7.34.0-SNAPSHOT:build failed: Unable to get KieModule, Errors Existed: Error Messages:
11:15:49 [ERROR] Message [id=1, kieBase=defaultKieBase, level=ERROR, path=com/myspace/mortgage_app/MortgageApprovalProcess.bpmn, line=-1, column=0
11:15:49 [ERROR]    text=Process Compilation error The method getProperty() is undefined for the type Object]
11:15:49 [ERROR] ---
11:15:49 [ERROR] Warning Messages:
11:15:49 [ERROR] ---
11:15:49 [ERROR] Info Messages:
11:15:49 [ERROR] -> [Help 1]
11:15:49 [INFO] 
11:15:49 org.apache.maven.lifecycle.LifecycleExecutionException[INFO] --- kie-maven-plugin:7.34.0-SNAPSHOT:injectreactive (default-injectreactive) @ itorders ---
11:15:49 : Failed to execute goal org.kie:kie-maven-plugin:7.34.0-SNAPSHOT:build (default-build) on project mortgage-process: Execution default-build of goal org.kie:kie-maven-plugin:7.34.0-SNAPSHOT:build failed: Unable to get KieModule, Errors Existed: Error Messages:
11:15:49 Message [id=1, kieBase=defaultKieBase, level=ERROR, path=com/myspace/mortgage_app/MortgageApprovalProcess.bpmn, line=-1, column=0
11:15:49    text=Process Compilation error The method getProperty() is undefined for the type Object]
11:15:49 ---
11:15:49 Warning Messages:
11:15:49 ---
11:15:49 Info Messages:
11:15:49 
11:15:49     [INFO] 
11:15:49 [INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ itorders ---
11:15:49 at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
11:15:49     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
11:15:49     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
11:15:49     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
11:15:49     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:200)
11:15:49     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:196)
11:15:49 [INFO] Changes detected - recompiling the module!
11:15:49     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
11:15:49     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
11:15:49     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
11:15:49     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
11:15:49     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
11:15:49     at java.lang.Thread.run (Thread.java:748)
11:15:49 Caused by: org.apache.maven.plugin.PluginExecutionException: [INFO] Using 'UTF-8' encoding to copy filtered resources.
11:15:49 Execution default-build of goal org.kie:kie-maven-plugin:7.34.0-SNAPSHOT:build failed: Unable to get KieModule, Errors Existed: Error Messages:
11:15:49 Message [id=1, kieBase=defaultKieBase, level=ERROR, path=com/myspace/mortgage_app/MortgageApprovalProcess.bpmn, line=-1, column=0
11:15:49    text=Process Compilation error The method getProperty() is undefined for the type Object]
11:15:49 ---
11:15:49 Warning Messages:
11:15:49 ---
11:15:49 Info Messages:
11:15:49 
11:15:49     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:145)
11:15:49     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
11:15:49     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
11:15:49     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
11:15:49     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
11:15:49     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:200)
11:15:49     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:196)
11:15:49     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
11:15:49     at java.util.concurrent.Executors$RunnableAdapter.call[INFO] Compiling 1 source file to /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-pullrequests/upstream-repos/kie-wb-playground/optacloud/target/test-classes
11:15:49 [INFO] Copying 2 resources
11:15:49  (Executors.java:511)
11:15:49     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
11:15:49     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
11:15:49     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
11:15:49     at java.lang.Thread.run (Thread.java:748)
11:15:49 Caused by: java.lang.RuntimeException: Unable to get KieModule, Errors Existed: Error Messages:
11:15:49 Message [id=1, kieBase=defaultKieBase, level=ERROR, path=com/myspace/mortgage_app/MortgageApprovalProcess.bpmn, line=-1, column=0
11:15:49    text=Process Compilation error The method getProperty() is undefined for the type Object]
11:15:49 ---
11:15:49 Warning Messages:
11:15:49 ---
11:15:49 Info Messages:
11:15:49 
11:15:49     at org.drools.compiler.kie.builder.impl.KieBuilderImpl.getKieModule (KieBuilderImpl.java:519)
11:15:49     at org.drools.compiler.kie.builder.impl.KieBuilderImpl.getKieModule[INFO] Changes detected - recompiling the module!
11:15:49  (KieBuilderImpl.java:525)
11:15:49     at org.drools.compiler.kie.builder.impl.KieBuilderImpl.getKieModule (KieBuilderImpl.java:500)
11:15:49     at org.kie.maven.plugin.BuildMojo.buildDrl (BuildMojo.java:151)
11:15:49     at org.kie.maven.plugin.BuildMojo.execute (BuildMojo.java:113)
11:15:49     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
11:15:49     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
11:15:49     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
11:15:49     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
11:15:49     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
11:15:49     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:200)
11:15:49     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:196)
11:15:49     at java.util.concurrent.FutureTask.run[INFO] Compiling 1 source file to /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-pullrequests/upstream-repos/kie-wb-playground/curriculumcourse/target/test-classes
11:15:49 [INFO] 
11:15:49 [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ itorders ---
11:15:49  (FutureTask.java:266)
11:15:49     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
11:15:49     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
11:15:49     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
11:15:49     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
11:15:49     at java.lang.Thread.run (Thread.java:748)
11:15:49 [ERROR] 
11:15:49 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
11:15:49 [ERROR] 
11:15:49 [ERROR] For more information about the errors and possible solutions, please read the following articles:
11:15:49 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
11:15:49 [ERROR] 
11:15:49 [ERROR] After correcting the problems, you can resume the build with the command
11:15:49 [ERROR]   mvn <goals> -rf :mortgage-process
11:15:49 [INFO] Changes detected - recompiling the module!
11:15:49 [INFO] 
11:15:49 [INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ itorders ---
11:15:49 [INFO] Building jar: /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-pullrequests/upstream-repos/kie-wb-playground/evaluation/target/evaluation-7.34.0-SNAPSHOT.jar
11:15:49 [INFO] Building jar: /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-pullrequests/upstream-repos/kie-wb-playground/mortgages/target/mortgages-7.34.0-SNAPSHOT.jar
11:15:49 Unexpected error while executing the Upstream repositories builder for PR builds! Error while executing Maven process, non-zero exit code!
11:15:49 java.lang.RuntimeException: Error while executing Maven process, non-zero exit code!
11:15:49 	at org.kie.jenkinsci.plugins.kieprbuildshelper.MavenProject.build(MavenProject.java:68)
11:15:49 	at org.kie.jenkinsci.plugins.kieprbuildshelper.AbstractPRBuilder.perform(AbstractPRBuilder.java:115)
11:15:49 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
11:15:49 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
11:15:49 	at hudson.model.Build$BuildExecution.build(Build.java:206)
11:15:49 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
11:15:49 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
11:15:49 	at hudson.model.Run.execute(Run.java:1810)
11:15:49 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
11:15:49 	at hudson.model.ResourceController.execute(ResourceController.java:97)
11:15:49 	at hudson.model.Executor.run(Executor.java:429)
11:15:49 Build step 'Build required upstream repositories (for PR builds)' marked build as failure
11:15:49 Recording test results
11:15:52 Skipping publisher since build result is FAILURE
11:15:52 Skipping publisher since build result is FAILURE
11:15:52 Archiving artifacts
11:15:54 Adding one-line test results to commit status...
11:15:54 Setting status of 8101df75de1a653a0dbaf9bb422988869d3338d3 to FAILURE with url https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-common-pullrequests/1658/ and message: 'Build finished. No test results found.'
11:15:54 Using context: Linux
11:15:54 Email was triggered for: Failure - Any
11:15:54 Sending email for trigger: Failure - Any
11:15:54 #1657 is still in progress; ignoring for purposes of comparison
11:15:54 Sending email to: kgaevski@redhat.com
11:15:57 [WS-CLEANUP] Deleting project workspace...
11:15:57 [WS-CLEANUP] Deferred wipeout is used...
11:15:57 [WS-CLEANUP] done
11:15:57 Finished: FAILURE</pre>
</details>

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Hi @romartin, @domhanak,

I rebased to master due to conflicts, now it is ready for review. Thank you!

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
@hasys I can't open any process in VSCode with these changes. I ll try rebuilding again... the editor keeps loading infinitely

**Comment by hasys** [comment]
Hi @domhanak I finally fixed local issues with VS Code plugin compilation, don't know what it was to be honest. I now compiling whole `kie-wb-common` and using `yarn run build` **without** `prod` or `fast` and it works.

I rebased changes to master branch so it should be good for you as well. Thank you!

image

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @domhanak,

Sonar Cloud failing due to duplication introduced earlier, this PR is just renames and label changes. Widgets refactoring is not a part of this Jira issue.

I rebased PR and was able to run it in VS Code. PR is ready for review.

Thank you!

**Pull request merged**
