### PR TITLE
Add missing dependencies for JDK 11 (#2524)

### PR DESCRIPTION
**Pull request by LuboTerifaj**
Missing dependencies for annotation and jaxb.

(cherry picked from commit 318151c15002ae94af57f5ae907a2469511d6f86)

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
https://issues.jboss.org/browse/JBPM-8308

**Comment by LuboTerifaj** [comment]
Hello @romartin @hasys ,
This is just cherry pick. I am not sure whether it can be merged in to 7.18.x branch, since there are dependencies changes also without scope test. If not, fell free to close the PR.
Thank you!

**Comment by hasys** [comment]
@LuboTerifaj, @romartin,

in my opinion if it changes not only Test scope it should be merged on master only. Probably, we can remove general dependencies from this PR and merge only Test scope dependencies, if it make sense. If not - just close this PR for 7.18.x branch.

Thank you!

**Comment by romartin** [comment]
Hey @LuboTerifaj agree with @hasys , is it really necessary to add support to JDK11 in 7.18.x branch as well? I would just close this PR and let master be on JDK11, if not really an urgency... thanks!

**Comment by LuboTerifaj** [comment]
@hasys, @romartin no problem. I was not sure about it. Let's close it then. Thanks!

**Pull request closed without merging**
