### PR TITLE
JBPM-7824 (RHPAM-1046): Stunner - Intermediate Events can have more then one incoming flow

### PR DESCRIPTION
**Pull request by Josephblt**
Issue:
[RHPAM-1046](https://issues.jboss.org/browse/RHPAM-1046)
[JBPM-7824](https://issues.jboss.org/browse/JBPM-7284)

Cherry-pick:
commit 510c51c

7.7.x Branch PR's:
kiegroup/kie-wb-common
#1860

Master PR's:
kiegroup/kie-wb-common
[this one](https://github.com/kiegroup/kie-wb-common/pull/1882)

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
@romartin Hi. Could you review this please? Thanks

**Comment by romartin** [comment]
Just minor thing please @Josephblt - can you change the commit message and use the `RHPAM` instead of the `JBPM` ticket? Thanks!

**Comment by Josephblt** [comment]
@romartin Hey, all done. Fixed the conflicts and the commit message. By the way I missed that comment about the commit message. Sorry about that.

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Pull request merged**
