### PR TITLE
JBPM-7753 Stunner - Create Marshaller tests for Escalation intermedia…

### PR DESCRIPTION
**Pull request by LuboTerifaj**
…te Events

There is an issue with docked events when using old Marshaller. There are failing two tests.
@tiagodolphine @evacchi Can you have a look please?

Thank you.

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
Hi @hasys , @evacchi
 
Can you have a look please?

Thanks.

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by hasys** [comment]
Hi @LuboTerifaj,

there are 3 tests failing in this PR, see Jenkins for more details. I can reproduce it locally.

**Comment by evacchi** [comment]
I don't know about the other, but the 2 migration failures seem mere rounding errors

**Comment by LuboTerifaj** [comment]
@evacchi , @hasys 

They should not fail, right?

Shall I put ignore annotation there and open Jira for that?

Thank you.

**Comment by evacchi** [comment]
well it's not an error per se, they are equal minus an epsilon. Maybe @tiagodolphine has forgotten a rounding routine?

**Comment by LuboTerifaj** [comment]
Hi @tiagodolphine 

Can you have a look if you have a time (see comments above)?

Thank you.

**Comment by romartin** [comment]
hey @LuboTerifaj , what's the status for this? any work missing? Thanks!

**Comment by romartin** [comment]
Sorry closed by error :/ Reopening

**Comment by LuboTerifaj** [comment]
Hi @romartin 

I am wating for @tiagodolphine comment.

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj  @evacchi yeah considering the error on the failing test, it seems that is a matter of rounding on some point on the Bounds, on the Double attributes. But I didn't change anything on that as far as I remember.
Can it be anything changed on the marshaling processing?

**Comment by LuboTerifaj** [comment]
Hi @tiagodolphine , @evacchi 

Do you plan to provide fix or shall I report it and ignore failing tests?

Thank you.

**Comment by evacchi** [comment]
Hi guys, I took a look at the problem, here's my findings

- 2 tests fail for OLD marshaller, 1 test fails for NEW marshaller 
- OLD:
  - testDockerInfo: expected: "126.0^24.5|", actual: "126.0^24.0|"
  - testMigrationInfo:  
    Expected :UL=[524.0, 574.3958] | LR=[580.0, 630.3958]
    Actual   :UL=[524.0, 574.3958129882812] | LR=[580.0, 630.3958129882812]
- NEW:
  - testMigrationInfo:
    Expected :UL=[524.0, 574.3958] | LR=[580.0, 630.3958]
    Actual   :UL=[524.0, 574.3958129882812] | LR=[580.0, 630.3958129882812]

As you can see, the only failing test for NEW fails exactly in the same way as OLD so I assume this is in fact not a bug, but rather the test should be fixed, as both OLD/NEW marshallers exhibit the same behavior. As for the other failing test in OLD, it's not failing in NEW, so either OLD or NEW is lying :-)

**Comment by LuboTerifaj** [comment]
Hi @evacchi 

I think, it is a bug, since the issue does not apply to the other events. Even the tests, which are failing, are not part of this PR. 

So what will we do with this?

Thanks.

**Comment by evacchi** [comment]
there is no issue in the code itself, I'd rather fix the BPMN file truncating to the nearest integer. By doing so, all tests will pass. This is ok, since the library we use to render the XML file does not give us control over the truncation of floating point numbers (at least, as far as I know): the tests are failing only because of rounding, not because of real errors. So I'd just update the BPMN file by using this one https://gist.github.com/evacchi/6a5fbdfe416f612fd1a6687a470d50d8

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by romartin** [comment]
hey @LuboTerifaj lemme when this is ready please

**Comment by LuboTerifaj** [comment]
Hello @evacchi ,

thank you for the hint. I have updated the PR.

Can you have a look at it again please (@hasys, @evacchi )?

Thank you!

**Comment by hasys** [comment]
Hi @LuboTerifaj,

fix looks good to me. Let's make build green again, and it is ready to go, thank you @LuboTerifaj!

**Comment by LuboTerifaj** [comment]
Hi @hasys 

Can you approve it? 

It seems, that the PR is ready to go. Can you merge it then @romartin?

Thank you!

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Pull request merged**
