### PR TITLE
JBPM-7245  Diagram SVG is not highlighted on the WB

### PR DESCRIPTION
**Pull request by tiagodolphine**
Changes on svg export to support Diagram SVG is not highlighted on the WB .

It was necessary to encode information regarding shape type (backgournd, border) that is needed by the **jbpm-process-svg** module that render the highlights on the SVG nodes. This is used but the kie-server that in fact uses the jbpm-process-svg.

Depends on PRs:
https://github.com/kiegroup/lienzo-core/pull/36
https://github.com/kiegroup/appformer/pull/368
https://github.com/kiegroup/droolsjbpm-integration/pull/1474

PS: unit tests will be updated later, the PR is to be tested ASAP since this is a blocker.

@romartin
@LuboTerifaj
@hasys 

PS2: To test this it will be necessary to deploy the **kie-wb** abd the **kie-server** generated by the full downstream, since the process is generated on the kie-wb but the SVG highlight is handled buy the kie-server.

### CODE REVIEW

**Comment by tiagodolphine** [comment]
jenkins execute full downstream build

**Comment by tiagodolphine** [comment]
Jenkins retest this

**Comment by tiagodolphine** [comment]
Hi @hasys, thanks for your quick review.
About the color scheme I'm setting the border and the background to gray on the completed activities, but I can change these colors, for instance, background grey and border black or any other combination. Changing the border color on the completed tasks may solve the subprocess issue as well, because the border and background are on the same color.

This is quick to change and I can do this before open the cherry pick to 7.7 WDYT ?
@romartin @hasys  @krisv @ibek

**Comment by hasys** [comment]
@tiagodolphine, yes sounds good to me to make borders black or different gray should be enough for now.

**Comment by wrnkld** [comment]
I agree that a darker border is fine for now.

**Comment by tiagodolphine** [comment]
@wrnkld ok, great, can you please send the hex code of a darker color you think may be good for now.
Thx.

**Comment by wrnkld** [comment]
#030303 thank you @tiagodolphine

**Comment by tiagodolphine** [comment]
Done, it was pushed https://github.com/kiegroup/droolsjbpm-integration/pull/1474/commits/7be96ea5c24a119a96dbd80f338417462c559efe

**Comment by tiagodolphine** [comment]
jenkins execute full downstream build

**Pull request merged**
