### PR TITLE
JBPM-6876: Stunner - easy way to migrate from Stunner to current Designer

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @romartin  @hasys would you mind review this PR?
Thanks.

depends on:
	https://github.com/kiegroup/appformer/pull/241
	https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/721

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
I found 2 issues: 

- After migrating, all events are shifted on the canvas (their shapes). See pictures:
screenshot from 2018-03-16 13-56-07
screenshot from 2018-03-16 13-56-40

- When you delete migrated process, it isn't removed from list of assets in project and if ypu click on that process, error is displayed: "org.uberfire.java.nio.file.NoSuchFileException".

**Comment by wmedvede** [comment]
hi, @LuboTerifaj the events shifting showed in the screenshot above is out of scope of this particular JIRA/PE. It's related with the elements corrdinates in two different drawing mechanisms, and how each designer is drawing the figures.
 Could you please open a JIRA and assign to @romartin so he can find the best suited person for taking a look.
Thanks!

**Comment by wmedvede** [comment]
@LuboTerifaj for the second issue you mentioning, what showcase/war file are you using for your tests?. If you have a link form where I can download it please add it here.
I don't discard it can be an issue, but this has work well when I tested it in kie-wb during development, etc. So I'm tempted to think about the index/.niogit repository is corrupt in the installation used for the tests, or some other change in the middle.

Thanks

**Comment by hasys** [comment]
Hi @wmedvede, @LuboTerifaj 

about second issue. It is know issue for new LibraryView widged. And not related to this PR.

@barboras7 can provide more details if needed.

**Comment by LuboTerifaj** [comment]
Hi @wmedvede
I will open Jira for the first issue.
Relating to second issue, I have downloaded kie-wb-7.7.0-SNAPSHOT-wildfly11.war (from full downstream build) but now, it doesn't matter if it is not related to this PR.

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by hasys** [comment]
Hi @wmedvede,

works good. Just one note (see below). Also I removed some unused fields, see https://github.com/wmedvede/kie-wb-common/pull/2.

* When I logged in to Business Central I got this message to Server log:
```
16:45:39,168 ERROR [org.jboss.errai.bus.client.util.ErrorHelper] (default task-86) *** Message delivery failure ***
Bus: org.jboss.errai.bus.server.ServerMessageBusImpl@4e3c148f
Message: CommandType=RemoteSubscribe, BeanType=org.kie.workbench.common.stunner.bpmn.project.client.editor.BPMNMigrateDiagramEvent, ToSubject=cdi.event:Dispatcher, Qualifiers=[]
errorMessage: Error calling remote service: cdi.event:Dispatcher
exception: java.lang.RuntimeException: Failed to dispatch CDI Event
disconnect: false
```

If I just refresh home page I am getting more and more error messages. Also, subjectively it freezes Loading scree for a while before show this error message.

Also

**Comment by wmedvede** [comment]
Hi @hasys the issue
16:45:39,168 ERROR [org.jboss.errai.bus.client.util.ErrorHelper] ... reported above is fixed and the your addings in https://github.com/wmedvede/kie-wb-common/pull/2 were manually added as part of fixes for going quicker.
So the PR is now updated properly.
Thanks!

**Comment by barboras7** [comment]
Hey guys, 
regarding the above mentioned issue, as Kirill already said - it is a known issue. If you want to look at it, you can find it here [RHBA-560](https://issues.jboss.org/browse/RHBA-560).

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Pull request merged**
