### PR TITLE
KOGITO-1577: Esc doesn't cancel context menus in DMN grid

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/KOGITO-1577

_Context menus_ were not responding to keyboard events.

After a couple of days of trying alternatives this is the _only_ working solution I could find.

### CODE REVIEW

**Comment by jomarko** [comment]
### Code review
no comments

### Manual review
- [ ] BC, expression type
- [ ] BC, name and type
- [ ] BC, insert, delete, clear
- [ ] BC, navigate to parent expression
- [ ] BC, cancel autocomplete, edit mode
- [ ] VSCode, expression type
- [ ] VSCode, name and type
- [ ] VSCode, insert, delete, clear
- [ ] VSCode, navigate to parent expression
- [ ] VSCode, cancel autocomplete, edit mode

**Comment by manstis** [comment]
Hi @jomarko I think this is good to re-review now.

> in firefox, user can not type value in literal expression cell

I could only replicate this by using `ESC` to cancel/exit the Monaco/expression editor. However the same behaviour is also present in `master` and hence I think the issue should be a new JIRA for @karreiro to investigate.

> in firefox, ctlr+space show context menu and immediately disappear

I could not replicate this (with my latest changes).

> when selected 'unspecified' context entry, popup can not bu discarded by esc key

The _context menu_ is the widget shown to add/delete row/column etc in response to a right-mouse-click. All others, including the "Unspecified" expression selector, are _popovers_ and respond to left-mouse-click. That said I have updated this PR to ensure _popovers_ also respond to `ESC` to cancel.

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Hi @jomarko could you please complete your review when you get a moment.

@karreiro has confirmed the issue with "in firefox, user can not type value in literal expression cell" is also present in `master` and has suggested a new JIRA be created.

Thank-you.

**Pull request merged**
