### PR TITLE
DROOLS-3245: [DMN Designer] Updating Name from Properties Panel does not update '<< Back to XYZ' link or Decision Navigator

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-3245

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@desmax74 Hi, this [test](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-common-pullrequests/902/testReport/org.kie.workbench.common.screens.datasource.management.util/MavenArtifactResolverTest/resolveArtifactNotOffline/) appears to keep failing:
```
org.kie.workbench.common.screens.datasource.management.util.MavenArtifactResolverTest.resolveArtifactNotOffline
``` 
Could you please investigate?

**Comment by desmax74** [comment]
"Could not find artifact org.uberfire:uberfire-m2repo-editor:pom:2.9.0-SNAPSHOT" but the version on the master is 2.12.0-SNAPSHOT

**Comment by manstis** [comment]
Great find @jomarko thanks. Fixed with new commit.

**Pull request merged**
