### PR TITLE
BAPL-1515: Stunner - Inline text edition

### PR DESCRIPTION
**Pull request by handreyrc**
**JIRA**: [BAPL-1515](https://issues.redhat.com/browse/BAPL-1515) 
Hey @romartin, @inodeman: Please could you review this PR?
Thanks!

### CODE REVIEW

**Comment by handreyrc** [comment]
Hey @romartin, @LuboTerifaj : I've fixed SonarCloud complaints and I'm also adding the artifacts for testing.
Please, could you take a look?
[business-cetral](https://drive.google.com/file/d/1KyX_navD7KIEdnLGkRwrZcwuk979VSQ1/view?usp=sharing)
[VSCode](https://drive.google.com/file/d/1Arwgro2Lgwyy3CRXJVinw0uwq-099z8e/view?usp=sharing)

Thanks!

**Comment by handreyrc** [comment]
Jenkins execute compile downstream build

**Comment by handreyrc** [comment]
Jenkins retest this

**Comment by handreyrc** [comment]
Jenkins run fdb

**Comment by handreyrc** [comment]
Jenkins run fdb

**Comment by handreyrc** [comment]
Jenkins run fdb

**Comment by romartin** [comment]
Hey @handreyrc 

Just trying to test the UI by using the BC WAR you uploaded, but I'm not able to run it, once deploying this WAR in a wildlfy I got [this error](https://gist.github.com/romartin/fd1615e3aa572226a8d444f145acb9c6)

**PLEASE URGENT** - maybe it's not an issue due to the updates on this PR itself, but try to rebase and rebuild the BC WAR ASAP, and then check it properly deploys on a wildfly, otherwise neither me or @LuboTerifaj can proceed with testing.

I'm going to try now the VSCode extension you uploaded, will let you know.

Thanks!

**Comment by romartin** [comment]
@handreyrc on the other hand, code looks great!! Nothing to say on the code review, everything looking good to me! Thanks! :+1: 

Sooo just please @handreyrc ensue both uploaded artifacts for testing are working properly, so @LuboTerifaj  and me can go ahead.

Thx!

**Review by romartin — CHANGES_REQUESTED** [review]
Hey @handreyrc 

Code looks great, although I found some early bugs on DMN side for now. Please do some sometests to ensure basic functionality is working, otherwise we'll spend too many time on the review iterations, as this bugs are found on just doing a basic change. Examples:

- [BUG] Once deploying a `DMN Decision` and renaming to something else, sometimes it works, sometimes it doesn't work at all, and sometimes it just updates the name but missing some last characters... Example: try to rename a decision to "Decision-2", will see it results on just "Decision," or rename to "Decision" and will result on "Decisio" (no final `n`). So strange behavior around this, at least on DMN. Pleaes also check BPMN.

- [IMPROVEMENT] Didn't we agreed to not use any placeholders? Once deploying a `DMN Decision` node, and editing the name, it's necessary to remove current text and replace it by the new one


So **PLEASE ensure** both following points to avoid unnecessary iteration on the reviews, we're not having much time to deliver this...:
- Some basic smoketest for BPMN and DMN (see bugs found above)
- The uploaded artifcats (BC + VSCode ext) are working properly

Thanks!!

**Comment by handreyrc** [comment]
Hey @romartin , it is strange I tested BC on wildfly before sharing. I'll check it.
Thanks.

**Comment by romartin** [comment]
no worries @handreyrc , maybe I'm doing something wrong as well... just check it when possible and lemme know. Also checkthe DMN bugs so we can get early feedback from lubo too.
Thanks for the great effort here!! :+1:

**Comment by romartin** [comment]
Hey @handreyrc @LuboTerifaj 

Sorry I was deploying the BC WAR in a wrong wildfly version.

Anyway,I've tested both BC and vscode extension, for both BPMN and DMN, and the artifacts work but the bug I mention above still aplies: for example ,in the BPMN editor, just drop a task and rename it to Task1 - the name will still be "Task", instead of Task1, same issues for DMN, see comment.

So please @handreyrc focus on fixing the issues, upload the artifacts again and let us know when it's ready for review.

Thansk!

**Comment by handreyrc** [comment]
Jenkins run fdb

**Comment by handreyrc** [comment]
Hey @romartin, @LuboTerifaj:
* I fixed the [BUG]  on typing reported above.
* Regarding to the place holders we will keep as is as for now, as agreed (@romartin). 

Here go the links for the updated artifacts:
[business-central](https://drive.google.com/file/d/1aPTxN-zQIGXUaYUyps5Tyj1telN0FpJ-/view?usp=sharing)
[VSCode](https://drive.google.com/file/d/1oPSr0VitkwGZjAVY_VDUzTTvmkW2QAyF/view?usp=sharing)

Thanks!

**Comment by romartin** [comment]
Hey @handreyrc 

Thanks for the fixes, now is working much better! Anwyay I still have found:

- 1) In the BPMN editor, the multi-line (by Shift+Enter) is not properly working. If I use new lines on the inline editor, once storing the  new text, it results on no new lines at all (both shape label and "name" field do not have any new line). If I use new lines in the name form field, the shape label appears with all new-lines properly, but once editing the text by using the inline editor no new-lines appear again. So the issue appears both ways

- 2) In general, on both editors, when trying to edit the name by double clicking on a shape, it sometimes doesn't work at first time, or the inline editor just appears/dissappears, and then you end up on double clicking again, then the shape looses it selection, then double clicking again and it works... :) I mean, it's not a blocking issue, but maybe worth trying to provide as much as possible a good user experience here, and it's a feature being used a lot

Can you please take a look at both issues? I would say 1) is a blocking one, and 2) would be a good nice to have.

Thanks again, good work! Looks great!

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @handreyrc ,

I have found several issues during my review:

- **New lines** input using inline text edition **are removed** when the changes are confirmed by pressing the enter.

- If a user double clicks on an activity with name, **a cursor is placed on the beginning** of String.
  - There are more possibilities what approach could be chosen here. Some of my thoughts are down below:
    - The cursor could be placed behind the whole String to make appending any text more easily.
    - The whole String could be selected to make deleting and then adding a new text more easily.
    - The cursor could be placed on the position where a user clicked to make editing more easily.
  - The approaches mentioned above could be used also in combination depending on where a user clicks, whether on the text or just on the node.

- Editing **task's text is shifted** in comparison with tasks that are not being edited. 
  - Steps to reproduce:
     1\. Create any task.
     2\. Double click on it.
    - See the shift.
   
- If a user double clicks on **a node without name**, default "Name" appears, what is expected. However, **after confirming it** by pressing enter, the name **restores its value to empty one**.

- **Input String is cut**. 
  - If a user double clicks on Event without name, inputs one, two or three characters, just zero, one or two characters are added to Name.
    - Steps to reproduce:
      1\. Create an event.
      2\. Double click on it.
      3\. Input "ab" and press enter.
      4\. Input "cd" and press enter.
      5\. Repeat the steps 3 and 4 and observe the behaviour.
    
- If **a text is pasted** into the inline editor, after pressing enter, **the changes are not saved**.
  - Steps to reproduce:
    1\. Copy any text.
    2\. Double click on a node.
    3\. Delete the current text OR select it.
    4\. Paste the previously copied text and press enter.
  - Only the first paste doesn't work. The others do, hence it looks like the issue is related to previous one mentioned above.    
    
- **Scrolling doesn't work** if editing a node with a long text.
  - Furthermore, with the current implementation, **the cursor is not visible since it is placed on the beginning of String** but the editing area shows only the end of String.
    
- If a node has a long name and a user starts editing it, **the part of the text is visible on the backround**. The same text is basically shown two times, what can be really disruptive.
  - From my point of view, the backround text should be totally hidden when editing or its shade should be changed to separate editing text from original one.
 
- **Editing window doesn't cover the whole sub-processes**. If the middle of sub-process is reached with long text in x axis, the text is moving up even there is a place for showing input string.
  - It causes that the issue with text visible on backround mentioned above is even more disruptive in this particular case than in other nodes.
  - The same issue **applies also to DMN decision service** in DMN editor.
 
-  The currently **edited node is see through**.
   - It causes that if a user edits the text on the node that is placed in sub-process or Lane with long names, these names are visible on the currently edited node. Again, this can be really disruptive.

- If **a node is placed near to the left border** of the canvas and it is visible entirely, **it is not possible to edit it** even if there is enough space for displaying inline editor.

- Inline editing **doesn't work in Case Management (Preview)** editor.

Note, I have change acceptance criteria regarding multiline support. DMN editor supports multiline editions as well. Not only single line editions as it was stated there.

Thank you!

**Comment by handreyrc** [comment]
Jenkins run fdb

**Comment by handreyrc** [comment]
Hey @romartin , @LuboTerifaj,

I worked on the issues you reported this is our latest:

*When trying to edit the name by double clicking on a shape, it sometimes doesn't work at first time, or the inline editor just appears/dissappears.
**Issue fixed

* New lines input using inline text edition are removed when the changes are confirmed by pressing the enter.
** Issue fixed

*If a user double clicks on an activity with name, a cursor is placed on the beginning of String.
**This component actually isn't a textarea. It is a div with the tag contenteditable which allows the inline edition of the div content. It has some limitations when it comes to the cod and control over the cursor is one of them. I noticed that the latest version of errai has a component "TextBox" that could possibly  solve the problem. We can leave as is or open a new issue since it is not a simple fix. WDYT?

*Editing task's text is shifted in comparison with tasks that are not being edited.
**The parameters were refined, however a perfect match does not seem possible due to line height and line break strategy.

*If a user double clicks on a node without name, default "Name" appears, what is expected. However, after confirming it by pressing enter, the name restores its value to empty one.
**Issue Fixed. The implementation was changed to solve the issue. Now placeholders really are supported if the node has an empty name.

*Input String is cut.
**Issue fixed

*Only the first paste doesn't work. The others do.
**Issue fixed

*Scrolling doesn't work if editing a node with a long text.
**The scroll is disabled because it depends on the cursor position. 
If the cursor is on the canvas while editing a node name, the canvas will respond to the scroll instead of the edition box.
It could be enabled, however, the user has to rest the mouse over the edition box while scrolling and it will also increase text shift issue because of the additional scrollbar space.
We can keep as is. WDYT?

*If a node has a long name and a user starts editing it, the part of the text is visible on the backround. The same text is basically shown two times, what can be really disruptive.
**Issue fixed. When node name is being edited it is set to "" until the user decides to cancel or save the edition.

*Editing window doesn't cover the whole sub-processes. If the middle of sub-process is reached with long text in x axis, the text is moving up even there is a place for showing input string.
**Issue fixed. The idea for containers such as lane and sub-process is not to offer a too long editing area. The same rules of the lane were applied restricting width and height.

*If a node is placed near to the left border of the canvas and it is visible entirely, it is not possible to edit it even if there is enough space for displaying inline editor.
**The intent was to prevent palette overlap while editing a node name underneath. However, it causes the node to be unresponsive when it is within palette width range. This behavior was disabled so we will have this overlap.
We can open a new issue since it is not an easy fix. WDYT?

*Inline editing doesn't work in Case Management (Preview) editor.
**It doesn't work, however,  it does't cause errors and the user can still use the properties panel in order to edit node names. Case Management Preview is legacy, so I recommend to leave as is. WDYT?

Here go the latest artifacts for testing:
[business-central](https://drive.google.com/file/d/1ptQoM3uC2b2NaNgWoTLDaXc3ZKS24vu6/view?usp=sharing)
[VSCode](https://drive.google.com/file/d/1laj6ji7rVijSLeJmTKAHp3BessY2Q4MY/view?usp=sharing)

Thanks!

**Comment by handreyrc** [comment]
Hey @LuboTerifaj, could you take a look at the comments above?
I was taking to @romartin  and maybe we could prioritize the core of the new feature and then address minor issues in new Jiras.
So we can move forward if it is good enough.

Thanks

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @handreyrc ,

Several issues have been fixed. However, there are still some (**bold** text) that needs to be fixed. See my comments below: 

- **New lines** input using inline text edition **are removed** when the changes are confirmed by pressing the enter.
  - The issue is still **not fixed in Firefox**.

- _If a user double clicks on an activity with name, a cursor is placed on the beginning of String._
  - I agree with reporting the issue: https://issues.redhat.com/browse/RHPAM-3164
	
- _Editing task's text is shifted in comparison with tasks that are not being edited._ 
  - Yeah, I think we can keep it as it is.
   
- _If a user double clicks on a node without name, default "Name" appears, what is expected. However, after confirming it by pressing enter, the name restores its value to empty one._
  - The Name is still displayed. However a cursor is not placed in the beginning od String, so it doesn't evoke a feeling that the "Name" should be used. However, **the cursor is placed on different position in Firefox** in comparison with Chrome and VSCode. Would it be possible to unify it? 
  - The fix with temporarily setting the name to empty value causes that in **VSCode**:
    - there is **a validation message next to the Name property** for all nodes: `may not be empty`.
    - there is shown **a warning pop-up message**  for Data Objects: `Error(s): []`. 

    
- _Scrolling doesn't work if editing a node with a long text._
  - I have reported the issue: https://issues.redhat.com/browse/RHPAM-3165
    
-  _The currently edited node is see through._
   - The issue is reported here: https://issues.redhat.com/browse/RHPAM-3166

- _If a node is placed near to the left border of the canvas and it is visible entirely, it is not possible to edit it even if there is enough space for displaying inline editor._
  - I agree with reporting the issue: https://issues.redhat.com/browse/RHPAM-3167

- _Inline editing doesn't work in Case Management (Preview) editor._
  - Agree with not fixing it since the editor is not under active development right now. However I have reported the issue for tracking purposes: https://issues.redhat.com/browse/RHPAM-3168.

I have found two more issues:
- If you place any **activity** (task or sub-process) or **Text annotation** "under" the opened Properties panel and you start **editing its name** by activating Inline text editor, **the text is visible over the Properties panel**.
   - It shouldn't be editable, or the editing text should be displayed next to the panel on the left side as it is currently implemented for other nodes.
   - The behaviour should be also unified within all nodes.
- The similar issue to the issue mentioned above applies also to **expanded Palette**, but it applies to all nodes in this case.

Thank you!

**Comment by romartin** [comment]
Hey @LuboTerifaj 

Could we postpone the issues related to Firefox for a further tix? Firefox is not really supported, we are only supporting Chrome at this point, also the VSCode engine as well.

This way, we should be missing two fixes for this 

- The VSCode issue on forms (empty Name)
- The issue around Textr Annotation

WDYT? We don't have time for more I think... thanks!

**Review by LuboTerifaj — APPROVED** [review]
Hello @romartin , @handreyrc ,

The Firefox is definitely supported!

The issue with new line characters is not a blocker since a user can still edit name using Properties panel. However it should be fixed asap:
- [RHPAM-3170](https://issues.redhat.com/browse/RHPAM-3170) Inline text editor doesn't support new lines in Firefox

I am okay with fixing other issues in separate jiras since they are corner cases or not related to product:
- [RHPAM-3171](https://issues.redhat.com/browse/RHPAM-3171) The cursor's position is different in Firefox when using Inline text editor
- [RHPAM-3172](https://issues.redhat.com/browse/RHPAM-3172) Editing text using Inline editor is shown over Properties panel or Expanded Palette
- [KOGITO-3362](https://issues.redhat.com/browse/KOGITO-3362) Renaming the node using Inline editor shows a validation message
- [KOGITO-3363](https://issues.redhat.com/browse/KOGITO-3363) Renaming Data Object using Inline editor shows a warning pop-up message

Thanks!

**Comment by handreyrc** [comment]
Jenkins run fdb

**Comment by handreyrc** [comment]
Hey @romartin  I refactored the editing process to not change the model as we agreed.
I also fixed the issue with new lines in firefox and the warning messages in VSCode.
Please, could you review those changes?

Hey @LuboTerifaj  here are the issues covered in the latest and the artifacts for testing.
Please, could you check them?

Issues addressed:
* [RHPAM-3170](https://issues.redhat.com/browse/RHPAM-3170)
* [KOGITO-3362](https://issues.redhat.com/browse/KOGITO-3362)
* [KOGITO-3363](https://issues.redhat.com/browse/KOGITO-3363)

Artifact links:
* [business-central](https://drive.google.com/file/d/15SABBKYcSI0yJSYWltPj3BssGnc5Xcqo/view?usp=sharing)
* [VSCode](https://drive.google.com/file/d/1ilKxAPk8CKdQUYzkebbtWM9_ZBNmm5dL/view?usp=sharing)
* [online-editor](https://drive.google.com/file/d/1Q3zXo3dTlc3NZWf7-rpFQabW7-nUdlJ5/view?usp=sharing)

Thanks!

**Comment by handreyrc** [comment]
Jenkins retest this

**Comment by LuboTerifaj** [comment]
Jenkins execute fdb

**Comment by handreyrc** [comment]
Jenkins execute fdb

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @handreyrc ,

unfortunately the fixes have broken Inline text editor in Firefox:

- If you create any node, click on canvas and then active Inline editor of created node, the text is shown two times: currently edited as well as the original one on the node. The text is not readable.

I have found one more issue that needs to be fixed:
- If you input a new line to Data Object Name using Inline editor, an unexpected system error occurs and after closing and reopening the process, the process is broken and xml editor is opened.

Thanks!

**Comment by ederign** [comment]
@karreiro in case that this PR impacts DMN, could you please take a look at it?

**Comment by handreyrc** [comment]
Jenkins run fdb

**Comment by handreyrc** [comment]
Hey @romartin I changed the code to work as we discussed in our latest talk. 
Could you take a look please?

Hey @LuboTerifaj  we are ready for more one round of tests! 
Regarding to the issue below:
* If you input a new line to Data Object Name using Inline editor, an unexpected system error occurs and after closing and reopening the process, the process is broken and xml editor is opened.
- The problem wasn't introduced by this PR, and actually a proper fix requires changes in the engine and then in stunner.  
These are the Jiras created for this specific issue:
* [KOGITO-3389](https://issues.redhat.com/browse/KOGITO-3389)
* [KOGITO-3389](https://issues.redhat.com/browse/RHPAM-3184)

Here go the issues covered in the latest and the artifacts for testing.
Please, could you check them?

Issues addressed:
* [RHPAM-3170](https://issues.redhat.com/browse/RHPAM-3170) Inline text editor doesn't support new lines in Firefox
* [KOGITO-3362](https://issues.redhat.com/browse/KOGITO-3362) Renaming the node using Inline editor shows a validation message
* [KOGITO-3363](https://issues.redhat.com/browse/KOGITO-3363) Renaming Data Object using Inline editor shows a warning pop-up message
* If you create any node, click on canvas and then active Inline editor of created node, the text is shown two times: currently edited as well as the original one on the node. The text is not readable.

Artifact links:
* [business-central](https://drive.google.com/file/d/1_hXUGpco7h83L5TEbVcxaymnIp2JILZP/view?usp=sharing)
* [VSCode](https://drive.google.com/file/d/1CVkmGoNy2fVA4faFDweatUIcyAg8ox_D/view?usp=sharing)
* [online-editor](https://drive.google.com/file/d/1guEQ-bhY2gOnJE2wGj58roRix_7kHpAo/view?usp=sharing)

Best regards!

**Comment by handreyrc** [comment]
Jenkins run fdb

**Comment by romartin** [comment]
Please @LuboTerifaj urgent review missing here. Thanks!

**Review by romartin — APPROVED** [review]
Hey @handreyrc 

I've no found any major issues, so great updates, thanks! So after reporting some improvements for further work, approving this work, for me it's more than good for being included in the next release.

BTW @karreiro are you going to review this as well? Just asking before we're trynig to get this merged during this week, so if you're also interested please reserve some slot for this sooner than later, otherwise lemme know and I'll remove you as a reviewer.

CC @LuboTerifaj 

Thank you all guys!!

**Review by karreiro — COMMENTED** [review]
Thank you for this PR, @handreyrc. It improves the user experience on both editors a lot, excellent work! :-)

Just a minor issue. When users click outside the node, we're canceling user changes.

It seems like a regression to me. Currently, DMN and BPMN editors apply changes when users click outside the node, also the properties panel is still applying changes when users click outside of the name text box. Thus, for consistency, and to not break users expectation, I believe we should persist the node name when users click outside.

Thank again, for the excellent work! :-)

**Comment by romartin** [comment]
good catch @karreiro , I also think would be better to keep the same experience as before and performing the name change once clicking outside the node.
You think @handreyrc is it easy to change?

**Comment by handreyrc** [comment]
@romartin @karreiro, sure we don't any regression. 
I have this behaivor implemented in the OnBlur event and theoretically it should be a simple change. 
I'll do it.
Thanks

**Review by LuboTerifaj — APPROVED** [review]
Hello @handreyrc , @romartin ,

as discussed on the call, confirming changes by clicking outside the node will not be included in this PR. Reported issue can be found here:
- [JBPM-9376](https://issues.redhat.com/browse/JBPM-9376) _Confirm changes by clicking outside the Inline text editor_
 
Regarding the issue with new lines in Data Objects, it is reported here:
- [RHPAM-3196](https://issues.redhat.com/browse/RHPAM-3196) _Data Object's Name with new line characters breaks the process_
 
I have found two more minor issues:
- [RHPAM-3197](https://issues.redhat.com/browse/RHPAM-3197) _Stunner - The node's name is not shown after deactivating Inline editor_
- [RHPAM-3198](https://issues.redhat.com/browse/RHPAM-3198) _Stunner - Not possible to activate immediately any Property when Inline editor is activated_

I didn't find any other significant issues.
- The rest is reported and can be found either in this comment and my comments above or all of them are linked in the pr's jira: [BAPL-1515](https://issues.redhat.com/browse/BAPL-1515).

Thank you!

**Comment by romartin** [comment]
Hey @karreiro , after some discussions we're working on the thing you reported as a separate issue, which the goal is to be present as for the next release, but this way it allows us to merge this bigger one PR first at least. See https://issues.redhat.com/browse/JBPM-9376

Could you then please approve it? Again, we're working on the fix for JBPM-9376 and will provide the PR for it ASAP. CC @handreyrc 

Thanks!

**Review by karreiro — APPROVED** [review]
Thanks, @romartin @handreyrc!

**Pull request merged**
