### PR TITLE
RHDM-251 - Wildfly 11 upgrade

### PR DESCRIPTION
**Pull request by mareknovotny**
another round of reverted PR https://github.com/kiegroup/kie-wb-common/pull/1377

### CODE REVIEW

**Comment by mareknovotny** [comment]
Please check also GWT SDM mode as @mbarkley created an extension for that to not fail with logging conflict in JDK logging vs. JBoss logging

**Comment by mareknovotny** [comment]
Jenkins retest this, please

**Comment by mareknovotny** [comment]
Jenkins retest this, please

**Comment by mbarkley** [comment]
@romartin Added you as a reviewer so you can confirm the stunner webapps work correctly.

@manstis Can you verify the DMN webapp works or tag someone else to confirm?

**Comment by romartin** [comment]
@mbarkley sure thanks! I'm just testing it... anyway we found issues in one showcase and @wmedvede just created a new one, the PR is already approved and we need to merge it as it's blocking our developments, so probably you'll have to rebase this once it gets merged, sorry for the inconveniences, lemme know if  I can help.  See https://github.com/kiegroup/kie-wb-common/pull/1440

**Comment by mbarkley** [comment]
@romartin In which showcase did you find problems? What were the problems?

**Comment by romartin** [comment]
@mbarkley I mean not due to the wildfly upgrade, it's already broken in master. 

The showcase is this one -> https://github.com/kiegroup/kie-wb-common/tree/master/kie-wb-common-stunner/kie-wb-common-stunner-showcase/kie-wb-common-stunner-showcase-project

I don't really have all the details about this, @wmedvede did the checks and fixes he can help. But since last changes in the library and some other workbench areas, it seems that this concrete showcase got broken, for example, the project explorer was not diplaying the right assets and the VFS repository was incorrect too. @wmedvede did the research for this and finally he created a new one based on the actual drools-wb, so we expect no more issues as this one includes almost everything....

**Comment by romartin** [comment]
@mbarkley I'm just waiting for the full downstream build to complete for merging now the https://github.com/kiegroup/kie-wb-common/pull/1440, we need a showcase working asap in order to move fordward.... So please lemme know if that's finally good for you as well.

**Comment by mbarkley** [comment]
@romartin Ah okay. So the only thing this upgrade has a realistic chance of breaking is deploying to WildFly in SDM. So from our side we just need to know that you are able to start SDM (from IntelliJ or the command line) and that the war deploys to the embedded WildFly.

We can wait for you to merge #1440. Please get @mareknovotny's attention here when it's merged so he can rebase.

**Comment by romartin** [comment]
@mbarkley yes sure, I'm testing the SDM for your PR right now just to double check, then I'll merge the https://github.com/kiegroup/kie-wb-common/pull/1440 and I'll let you and @mareknovotny know, so you can rebase and then lemme know again, then I'll retest it! Thanks!

**Comment by mbarkley** [comment]
Thanks @romartin. If you do encounter an error deploying, you could speed things up by trying to add [this](https://github.com/kiegroup/kie-wb-common/pull/1431/files#diff-dffe52d6e9e3a87125d6baf30b234bf7R56) dependency to the webapp POM and seeing if that fixes it.

**Comment by romartin** [comment]
ok @mareknovotny @mbarkley just merged https://github.com/kiegroup/kie-wb-common/pull/1440 Please lemme know once rebased and I'll retest again,

**Comment by mareknovotny** [comment]
@romartin rebased, you can try it

**Comment by romartin** [comment]
@mareknovotny great, thanks! I'm my last try before I got [this error](https://gist.github.com/romartin/a6e1e0a581da20dbcb0b257099171476). So I ran the build for kie-wb-common-wf-sdm-extensions, which was failing to some compilation issues on some errai classes, I think can be done due to the artifact is still not present on nexus, so now building lastest errai's master branch locally, hope this will solve the issue. Or should I built some concrete branch? Thanks!

**Comment by mareknovotny** [comment]
@romartin you need to build only PR https://github.com/errai/errai/pull/330 in errai repo
It is expected you can't download it as the whole set of PRs are only in PR queue

**Comment by wmedvede** [comment]
@mareknovotny Please as part of your tests, and prior the final merge be sure that the projects also build.
Because after the initial attempt that was made last week, I could see that even for the showcases that worked, e.g. the drools-wb showcase, as soon you logged in and tried to build a project, the errors below were produced. Or you can also use the kie-wb-distributions generated .wars or showcases. But please try it.

This is the error.

[ERROR] java.lang.NoClassDefFoundError: Could not initialize class org.guvnor.ala.util.VariableInterpolation
[ERROR]         at org.guvnor.ala.pipeline.execution.PipelineExecutor.lambda$continuePipeline$0(PipelineExecutor.java:101)
[ERROR]         at org.guvnor.ala.pipeline.StageUtil$1.execute(StageUtil.java:38)
[ERROR]         at org.guvnor.ala.pipeline.StageUtil$1.execute(StageUtil.java:33)
[ERROR]         at org.guvnor.ala.pipeline.execution.PipelineExecutor.continuePipeline(PipelineExecutor.java:94)
[ERROR]         at org.guvnor.ala.pipeline.execution.PipelineExecutor.execute(PipelineExecutor.java:76)
[ERROR]         at org.kie.workbench.common.services.backend.builder.ala.BuildPipelineInvoker.invokeLocalBuildPipeLine(BuildPipelineInvoker.java:88)
[ERROR]         at org.kie.workbench.common.services.backend.builder.ala.BuildPipelineInvoker$Proxy$_$$_WeldClientProxy.invokeLocalBuildPipeLine(Unknown Source)
[ERROR]         at org.kie.workbench.common.services.backend.builder.service.BuildServiceHelper.invokeLocalBuildPipeLine(BuildServiceHelper.java:152)
[ERROR]         at org.kie.workbench.common.services.backend.builder.service.BuildServiceHelper.localBuild(BuildServiceHelper.java:67)
[ERROR]         at org.kie.workbench.common.services.backend.builder.service.BuildServiceHelper$Proxy$_$$_WeldClientProxy.localBuild(Unknown Source)
[ERROR]         at org.kie.workbench.common.services.backend.builder.service.BuildServiceImpl.build(BuildServiceImpl.java:64)
[ERROR]         at org.kie.workbench.common.services.backend.builder.service.BuildServiceImpl$Proxy$_$$_WeldClientProxy.build(Unknown Source)

**Comment by mareknovotny** [comment]
@wmedvede I don't understand your comment, are you saying that the CI didn't show this compilation error ? I tried it and see CI checks where are only known test failures with index tests.

**Comment by mareknovotny** [comment]
Certainly I did the local build too, so I am confused what you ran to get the error.

**Comment by wmedvede** [comment]
@mareknovotny What I'm saying is that after the changes, I could see that even when it was possible to build the different showcases or the applications in kie-wb-applications, then if you take for example one the generated applications and deploy it in WF11 to see if the generated application works properly.
What I could see was that for example if you import the mortages project and try to build it, the build errors above was produced. 

[ERROR] java.lang.NoClassDefFoundError: Could not initialize class 
org.guvnor.ala.util.VariableInterpolation

I'm not sure that this will happen now with this new PR, but I have the filling the PR might be introducing changes/errors at some library version, or , whatever that makes the build fail.

So please check that all continues working as before, because if this build errors are still produced it'll block all the people that needs to work with the different workbenches.

To test it you can do:

1) take whatever of the kie workbenches generated in your local kie-wb-distribution project, e.g. kie-wb-7.7.0-SNAPSHOT-wildfly10.war (not sure if it was renamed to wildfly11 but anyway)
2) deploy the picked WB in a WF11
3) login, and try to create a project an add assets to it, or just use the mortgages project and try to build it.

Be sure that the build errors above are not produced.
Thanks!

**Comment by mareknovotny** [comment]
@wmedvede so you don't have now any error AFAIU, right? I think the review is about trying the web app too, even I can do that and I will, If you review this PR, please verify the functionality too.

**Comment by wmedvede** [comment]
Hi @mareknovotny I'm working in other branch, issue, right now, and it takes years to switch to all the branches affected by this PR, and rebuild all this locally. So given that you probably has all this work done locally please give it a try. 
And of course is there are more people that has all this and they can check it'll be great.

Thanks!

**Comment by mareknovotny** [comment]
@wmedvede I tried and deployed **kie-wb*-wildfly11.war** on wf 11 just fine, created mortgages from sample projects and added there in Applicant some new field and run  `Build & Deploy`. All ran fine without deployment errors

**Comment by wmedvede** [comment]
@mareknovotny after building all PR branches "RHDM-251" locally and having to rebase some repos in the middle with master. This were my findings.

1) I was able to run kie-wb-commons/.../ kie-wb-common-stunner-showcase-project with SDM (mvn clean gwt:run) and worked well. Also NO build errors.

2) I was able to start drools-wb/drools-wb-webapp in SDM, and login, but got the build errors  I commented before.

3) I was able to start optaplanner-wb/optaplanner-wb-webapp in SDM, and login, but got the build errors I commented before.

4) I was able to start jbpm-wb/jbpm-wb-showcase in SDM, but I couldn't login. I don't know if it's something the happen before the changes since I'm not familiar with this showcase. I couldn't try the build.

5) I was able to start kie-wb-distributions/kie-wb-parent/kie-wb-webapp in SDM, and login, but got the build errors I commented before.

6) for the build generated in 5) I was able to deploy the generated kie-wb-7.7.0-SNAPSHOT-wildfly11 file in a standalone WF11, login, and the build worked fine.

**Comment by mbarkley** [comment]
@wmedvede Can you tell me the steps you did to reproduce the issue in drools-wb. I tried importing an example and got a different error (related to the LogManager issue). Adding the dependency to disable logging might have fixed the issue, but I wasn't able to tell because logging went away. I will have to continue investigating on Monday to see if I can disable the WF logmanager while still enabling logging in the webapp.

**Comment by wmedvede** [comment]
@mbarkley  This were the steps.
1) local build of all RHDM-251 branches
2) go to drools-wb/drools-wb-webapp  and start it with mvn clean gwt:run
3) login with admin/admin
4) import the mortgages project
5) open e.g. the Applicants class, add a new field and save
6) The errors will be thrown as part of the incremental build triggered by 5)
7) If you clear the messages console with the "clear" button, and force the project build again, the error will be produce again, and so on.

**Comment by mareknovotny** [comment]
@mbarkley I tried what @wmedvede listed and it is true I can see that build error too
but before and I suspect that it is the core issue is 
```
[INFO] ERROR 26-02 10:45:42,482 (AbstractLoggingWriter.java:write:71) 	 java.lang.RuntimeException: An error occurred while executing the Local Source Config stage.
[INFO] ERROR 26-02 10:45:42,483 (AbstractLoggingWriter.java:write:71) 	 	at org.guvnor.ala.pipeline.execution.PipelineExecutor.continuePipeline(PipelineExecutor.java:126)
[INFO] ERROR 26-02 10:45:42,483 (AbstractLoggingWriter.java:write:71) 	 	at org.guvnor.ala.pipeline.execution.PipelineExecutor.execute(PipelineExecutor.java:76)
[INFO] ERROR 26-02 10:45:42,483 (AbstractLoggingWriter.java:write:71) 	 	at org.kie.workbench.common.services.backend.builder.ala.BuildPipelineInvoker.invokeLocalBuildPipeLine(BuildPipelineInvoker.java:88)
``` 
So this should the issue with logging again.

**Comment by mareknovotny** [comment]
@wmedvede I rebased and added SDM dev extension for disabling JBoss logging into drools-wb too https://github.com/kiegroup/drools-wb/pull/811

**Comment by mareknovotny** [comment]
I was not able to start kie-wb-distributions/kie-wb-parent/kie-wb-webapp in SDM and the error is not clear to me as it behaves differently and I can't login to jbpm-wb-webapp in SDM too.

**Comment by mbarkley** [comment]
@mareknovotny @wmedvede I was able to fix logging in drools-wb-webapp with this commit. AFAICT adding the Errai SDM dependency + these changes fixes all problems.

@mareknovotny Could you please merge these changes to drools-wb-webapp and also apply the same changes to the stunner showcase?

@wmedvede Could you please confirm (once merged) that everything works?

**Comment by mareknovotny** [comment]
@wmedvede  @mbarkley  Done

**Pull request merged**
