### PR TITLE
reduced extraJvmaArgs to 11g

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
this is a PR to test the FDB

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by jomarko** [comment]
Just question how we computed11G? for DMN we use for gwt maven plugin 4096M, not saying I am against 11G.

**Comment by mareknovotny** [comment]
@jomarko there there tryouts to use 16G but on multithreaded maven build.
I pointed out to @mbiarnes that we have just 24G on our node slave, so if by any change runs that kie-wb-common with something in parallel it can be easily going over 24G.

**Comment by domhanak** [comment]
@mbiarnes any updates?

**Pull request closed without merging**
