### PR TITLE
JBPM-6103 - Fix  Documentation value are not persisted on Embedded Subprocess	

### PR DESCRIPTION
**Pull request by tiagodolphine**
Now documentation mashalling is ok and the value persisted is displayed properly.
Some refactory were made for cleaning code and make the test for this issue possible.

@romartin

### CODE REVIEW

**Comment by manstis** [comment]
When PRs are merged commits can (now) be squashed. IDK when the feature became available but I know it is now.

**Comment by romartin** [comment]
@manstis !?!? that's new for me... so you mean is a feature from github, jenkins.. ?? Is it done automatically?

**Comment by manstis** [comment]
It's a Github feature. When a "gatekeeper" merges a PR Github offers the ability to "squash and merge".

**Comment by tiagodolphine** [comment]
Great, so it's now mandatory to squash all commits into one anymore? If so ok otherwise I can squash them, no problem.
@romartin @manstis

**Comment by romartin** [comment]
@manstis good to know thx!
IMO squashing would be better, at least for me,  because I use to click on "show all changes from latest commit..." in IntelliJ, so I can see a clear review of all affected classes...

**Comment by romartin** [comment]
Jenkins complains but I'd been able to build, test and run it, all good.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Pull request merged**
