### PR TITLE
JBPM-8768: Stunner - Remove sun packages usages from Stunner

### PR DESCRIPTION
**Pull request by LuboTerifaj**
https://issues.jboss.org/browse/JBPM-8768

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by romartin** [comment]
Jenkins retest please

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
just question, can't we now remove some maven dependency?

**Comment by romartin** [comment]
Hey @jomarko , I don't think so, I think `refect` pakage is part of the jdk/jre, so not specific maven dep should be related to this

@LuboTerifaj once builds fixed, plz lemme know and I'll merge! 

Thx guys!

**Comment by jomarko** [comment]
@romartin ok, thank you

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by hasys** [comment]
Hi @LuboTerifaj,

there are some issues with this PR, that's why Jenkins build is red. Please revise it here:
<details>
  <summary>Stack Trace</summary>
  <pre>14:30:09 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project kie-wb-common-stunner-client-common: Compilation failure
14:30:09 [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-pullrequests/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/event/screen/ScreenEventPublisherTest.java:[81,42] no suitable method found for thenReturn(java.lang.Object)
14:30:10 [ERROR]     method org.mockito.stubbing.OngoingStubbing.thenReturn(java.util.Set) is not applicable
14:30:10 [ERROR]       (argument mismatch; java.lang.Object cannot be converted to java.util.Set)
14:30:10 [ERROR]     method org.mockito.stubbing.OngoingStubbing.thenReturn(java.util.Set,java.util.Set...) is not applicable
14:30:10 [ERROR]       (argument mismatch; java.lang.Object cannot be converted to java.util.Set)
14:30:10 [ERROR] -> [Help 1]
14:30:10 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project kie-wb-common-stunner-client-common: Compilation failure
14:30:10 /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-pullrequests/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/event/screen/ScreenEventPublisherTest.java:[81,42] no suitable method found for thenReturn(java.lang.Object)
14:30:10     method org.mockito.stubbing.OngoingStubbing.thenReturn(java.util.Set) is not applicable
14:30:10       (argument mismatch; java.lang.Object cannot be converted to java.util.Set)
14:30:10     method org.mockito.stubbing.OngoingStubbing.thenReturn(java.util.Set,java.util.Set...) is not applicable
14:30:10       (argument mismatch; java.lang.Object cannot be converted to java.util.Set)
14:30:10 
14:30:10     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
14:30:10     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
14:30:10     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
14:30:10     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
14:30:10     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
14:30:10     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
14:30:10     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
14:30:10     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
14:30:10     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
14:30:10     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
14:30:10     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
14:30:10     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
14:30:10     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
14:30:10     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
14:30:10     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
14:30:10     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
14:30:10     at java.lang.reflect.Method.invoke (Method.java:498)
14:30:10     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
14:30:10     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
14:30:10     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
14:30:10     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
14:30:10 Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
14:30:10 /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-common-pullrequests/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/event/screen/ScreenEventPublisherTest.java:[81,42] no suitable method found for thenReturn(java.lang.Object)
14:30:10     method org.mockito.stubbing.OngoingStubbing.thenReturn(java.util.Set) is not applicable
14:30:10       (argument mismatch; java.lang.Object cannot be converted to java.util.Set)
14:30:10     method org.mockito.stubbing.OngoingStubbing.thenReturn(java.util.Set,java.util.Set...) is not applicable
14:30:10       (argument mismatch; java.lang.Object cannot be converted to java.util.Set)
14:30:10 
14:30:10     at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1220)
14:30:10     at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:180)
14:30:10     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
14:30:10     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
14:30:10     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
14:30:10     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
14:30:10     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
14:30:10     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
14:30:10     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
14:30:10     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
14:30:10     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
14:30:10     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
14:30:10     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
14:30:10     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
14:30:10     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
14:30:10     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
14:30:10     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
14:30:10     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
14:30:10     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
14:30:10     at java.lang.reflect.Method.invoke (Method.java:498)
14:30:10     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
14:30:10     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
14:30:10     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
14:30:10     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
14:30:10 [ERROR] 
14:30:10 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
14:30:10 [ERROR] 
14:30:10 [ERROR] For more information about the errors and possible solutions, please read the following articles:
14:30:10 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
14:30:10 [ERROR] 
14:30:10 [ERROR] After correcting the problems, you can resume the build with the command
14:30:10 [ERROR]   mvn <goals> -rf :kie-wb-common-stunner-client-common</pre>
</details>

**Comment by LuboTerifaj** [comment]
@hasys I triggered the build because the previous one was already deleted. Yeah, I need to have a look at it, but strange since it was not failing before.

**Comment by domhanak** [comment]
@LuboTerifaj @romartin @hasys What is the status of this PR?

**Comment by LuboTerifaj** [comment]
Hi @domhanak 

I run test locally on master with java 11 and it has passed.

The PR is out of date.

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by LuboTerifaj** [comment]
Jenkins build has been removed too soon but I didn't have any issues with the PR locally. I am retriggering the build again.
Jenkins retest please.

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by LuboTerifaj** [comment]
Jenkins retest please.

**Comment by LuboTerifaj** [comment]
Hey @romartin , @hasys , 

do you have any idea why the builds don't work?

I have run the tests for the changed class locally and they have passed, so the PR should be ready to merge, but the build must be green first.

Thank you!

**Comment by hasys** [comment]
Hi @LuboTerifaj,

I think it is because your PR is 7.40.0-SNAPSHOT but current master is 7.42.0-SNAPSHOT, please try to rebase to master and retrigger it again. Thank you!

**Comment by LuboTerifaj** [comment]
@hasys , I think it was failing also before, but good point, I will rebase it with master and trigger it again. Thanks!

**Comment by hasys** [comment]
Jenkins execute compile downstream build

**Comment by LuboTerifaj** [comment]
Hi @romartin , @hasys , 

Jenkins build is green, however the full downstream build is missing.

Do we need FDB even there was a change only in test?

Thanks!

**Comment by hasys** [comment]
Jenkins execute compile downstream build

**Comment by hasys** [comment]
Hi @LuboTerifaj, it should be at least green to be sure that we do not broke anything for anyone.

**Comment by LuboTerifaj** [comment]
Hi @hasys , @romartin ,

CDB is green, but I am not sure whether it is sufficient. Do you know what is the difference between FDB and CDB?

I also see other builds for openjdk8 and openjdk11, but they are still failing with unrelated issues.

Which builds should be green to make the PR's merging possible?

Thank you!

**Comment by hasys** [comment]
Hi @LuboTerifaj,

Full Downstream Compile build do full downstream compilation and ensure that PR won't break compilation for others. But at the same time it doesn't execute tests and do not build WAR files.

Missing WAR files we are compensating by providing WAR from local build. Tests for `kie-wb-common` repository run under PR build. So in fact the only difference is tests in other repositories. But if I correct all dependent on Stunner projects are also in `kie-wb-common` so I wouldn't expect issues there. At worse case we will get report about failing tests on the next day after the merge from nightly builds.

So FDC looks a good alternative of FDB meanwhile FDB is limited and not properly working.

About `openjdk8` and `openjdk11` IIRC it is experiments and they are not ready yet so we can ignore them.

So PR build and FDC builds should be enough for PR to be merged in my opinion.

Thank you @LuboTerifaj!

@romartin I think this PR is ready for merge. Thank you!

**Comment by LuboTerifaj** [comment]
Hi @hasys , thank you for clarification!

**Pull request merged**
