### PR TITLE
RHPAM-1033 - Allow to model Process Level SLA in new process designer

### PR DESCRIPTION
**Pull request by Josephblt**
https://issues.jboss.org/browse/RHPAM-1033

SLA Due Date property is now available at process level.

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by Josephblt** [comment]
Hello @LuboTerifaj, @romartin. Added the information on the @Ignore annotations. Basically this is due to differences between the old and new marshallers. 

For now just having the property available/editable seems good enough, in my opinion. So, we should go ahead and make this available. But I too believe validation is important and we should address this in the JIRA [JBPM-8292](https://issues.jboss.org/browse/JBPM-8292) as soon as we have time for it.

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Great job @Josephblt , merging - thanks!

**Pull request merged**
