### PR TITLE
KOGITO-224 : Stunner - Press ENTER to define a type

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin @hasys can you check this PR?

### CODE REVIEW

**Comment by romartin** [comment]
Hey @mareknovotny @mbiarnes @krisv 

Just noticed that the status for `KOGITO` tickets seems not to be automatically changed to `PR sent`, while creating a PR like this one (just we did it manually for this [ticket](https://issues.jboss.org/browse/KOGITO-224)). I think this happens for `JBPM` and `RHPAM`, at least, am I correct? If so, is it possible to apply same "hook" or whatever approach you're using?

Thanks ina advance!

**Comment by romartin** [comment]
@hasys Adding you as a reviewer also because, although being a `KOGITO` specific ticket, it applies everywhere. Thx!

**Comment by romartin** [comment]
@inodeman @hasys TBH I still don't poperly understand neither the ticket's goal and so neither the fix is clear for me, can you please verify what's expected? Thx in advance!

**Comment by krisv** [comment]
Regarding automatic github PR linking and updates, can you check with @mbiarnes ?

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by mareknovotny** [comment]
> Regarding automatic github PR linking and updates, can you check with @mbiarnes ?
there needs to be invited https://github.com/orgs/kiegroup/people/jboss-jira-hook to able to post web hooks to jira project. Invite him for kogito repositories and that would be enough I think.

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Hi @inodeman,

I think Enter button shouldn't be ignored by rather should do deactivation of text field to "save" entered data. WDYT?

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by inodeman** [comment]
Hi @hasys, the thing is all over forms the behavior is not to use enter to loose focus on a field, I am afraid if I change this, then it will not be consistent with the whole app. I changed the implementation to use a simple change in the same way that other special characters are used. Let me know

**Comment by inodeman** [comment]
Jenkins execute full downstream build

**Comment by inodeman** [comment]
Jenkins retest please

**Comment by inodeman** [comment]
Hi @romartin added tests for both textboxes

**Comment by hasys** [comment]
Hi @inodeman,

make sense, thank you, I reported future enhancement for property disabling: 
* [JBPM-8935](https://issues.redhat.com/browse/JBPM-8935)

### Check list
- [x] Affected version is set property
- [x] Is realization aligned to jira description?
- [x] Both Jenkins jobs are green
  * Selenium issues are not related and handled by https://github.com/kiegroup/kie-wb-distributions/pull/998

### Code review
- [x] Code coverage
- [x] License headers
- [x] Static analyser gates
- [x] Code Style

### Acceptance Criteria
> For acceptance criteria see jira description

- [x] Tested with full downstream build
  - [x] Firefox
  - [x] Chrome

### Found issues
>  **Blocker**, **Critical** and **Major** bugs and **Blocker** and **Critical** enhancements should be fixed before merge.
* None

**Comment by romartin** [comment]
Hey @hasys 

From your report above I dont' see any issues.. but it's still not approved :) Is it some action missing? otherwise plz feel tree to approve once possible, so I'll merge.

thanks!

**Pull request merged**
