### PR TITLE
GUVNOR-3394: [DMN Editor] Literal Expression: Line breaks for multiple line expressions

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-3394

This requires https://github.com/ahome-it/lienzo-core/pull/187 to be merged and a new release of Lienzo to be made (which will require a change to ```droolsjbpm-build-bootstrap``` ```pom.xml```). Furthermore I'll need to make additional changes to this PR once https://github.com/kiegroup/kie-wb-common/pull/1063 is merged (that does not require a new Lienzo release!)

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko FYI (this PR is a long way off from being "mergable"!)

@Christopher-Chianelli Could you please give this your thoughts (you're the last person to touch ```Text```).

**Comment by jomarko** [comment]
@manstis well, what is your proposal please? Should I postpone review until this is mergable?

**Comment by manstis** [comment]
@jomarko That's up to you! I doubt _this_ PR will change.

**Comment by Christopher-Chianelli** [comment]
@manstis Your solution looks good to me, but please read my comments on your lienzo PR.

**Comment by manstis** [comment]
Part of an ensemble:

- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/564
- https://github.com/AppFormer/uberfire/pull/849
- https://github.com/kiegroup/kie-wb-common/pull/1074

**Comment by romartin** [comment]
oh great @manstis , just giving it a try! Thanks!

**Pull request merged**
