### PR TITLE
JBPM-9788 - Unable to define Business Rule Task assignment if there is a process variable

### PR DESCRIPTION
**Pull request by Josephblt**
The combo box now filters for duplicate values.

**JIRA**: [JBPM-9788](https://issues.redhat.com/browse/JBPM-9788)

**Referenced Pull Requests**:

**Business Central**: [WAR file](https://drive.google.com/file/d/17NnDgcohckv5Okef6Itn-HseXd8KZfKu/view?usp=sharing)

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins do fdb

**Comment by Josephblt** [comment]
Jenkins do cdb

**Comment by Josephblt** [comment]
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins do fdb

**Review by jomarko — APPROVED** [review]
Thank you @Josephblt

**Comment by Josephblt** [comment]
Jenkins do fdb

**Comment by Josephblt** [comment]
Hello @romartin. I believe this is ready to merge. Thanks.

**Pull request merged**
