### PR TITLE
AF-2516 : NoSuchFileException appears when data object with unsaved changes is renamed

### PR DESCRIPTION
**Pull request by akumar074**
* Change in Data Object rename operations sequence to first move file then modify the content

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by akumar074** [comment]
Jenkins execute full downstream build please

**Comment by Srihari1192** [comment]
Jenkins execute full downstream build

**Comment by akumar074** [comment]
Jenkins execute full downstream build

**Comment by akumar074** [comment]
Jenkins do full downstream build please

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by Srihari1192** [comment]
@akumar074 When we modify source code of data object and rename a file, getting error in server log as 

```
ERROR [org.kie.workbench.common.screens.datamodeller.backend.server.DataModelerServiceImpl] (default task-6) An error was produced during class refactoring at file renaming for file: default://master@MySpace/proj13/src/main/java/com/myspace/dfsd.java. The file renaming will continue without class refactoring: java.lang.NullPointerException
    at org.kie.workbench.common.screens.datamodeller.backend.server.DataModelerServiceImpl.rename(DataModelerServiceImpl.java:782)
    at org.kie.workbench.common.screens.datamodeller.backend.server.DataModelerServiceImpl$Proxy$_$$_WeldClientProxy.rename(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

ERROR [org.guvnor.common.services.backend.exceptions.ExceptionUtilities] (default task-13) Exception thrown: There is no batch process.: java.lang.RuntimeException: There is no batch process.
```

**Comment by akumar074** [comment]
@Srihari1192 let's test this on new changes I pushed recently, after the FDB is complete.

**Review by Srihari1192 — APPROVED** [review]

**Pull request merged**
