### PR TITLE
JBPM-6511: Remove the Business Dashboards entry from mega menu

### PR DESCRIPTION
**Pull request by dgutierr**
Changes required by https://github.com/kiegroup/kie-wb-distributions/pull/653

- Removed "Apps" from the list of available perspectives in the security UI page selector dropdowns.
- "Business Dashboards" renamed to "Page Authoring"

@manstis @jhrcek Can you review it as well? Thanks!

### CODE REVIEW

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Strange. Full downstream build failed with:

12:04:14 [ERROR] /home/jenkins/workspace/kie-wb-common-downstream-pullrequests/downstream-repos/drools-wb/drools-wb-webapp/src/main/java/org/drools/workbench/client/home/HomeProducer.java:[29,1] cannot find symbol
12:04:14   symbol:   static BUSINESS_DASHBOARDS
12:04:14   location: interface
12:04:14 [ERROR] /home/jenkins/workspace/kie-wb-common-downstream-pullrequests/downstream-repos/drools-wb/drools-wb-webapp/src/main/java/org/drools/workbench/client/home/HomeProducer.java:[55,45] cannot find symbol
12:04:14   symbol:   variable BUSINESS_DASHBOARDS
12:04:14   location: class org.drools.workbench.client.home.HomeProducer

But I see the changes are done in HomeProducer and the branches in kie-wb-distribution and this PR are named the same, so it should build correctly. Trying again:

Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Still failing with the same error. @dgutierr can you please take a look?

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by dgutierr** [comment]
@manstis This one as well please :-)

**Pull request merged**
