### PR TITLE
[7.0.x] GUVNOR-3032: Example import: Optimize playground repository cloning

### PR DESCRIPTION
**Pull request by mcimbora**
@manstis This is a 7.0.x version of https://github.com/kiegroup/kie-wb-common/pull/814.

### CODE REVIEW

**Comment by manstis** [comment]
@etirelli Is 7.0.x frozen? Can we still merge bug fixes for inclusion in 7.0.0.Final?

**Comment by etirelli** [comment]
@manstis @mcimbora If this is critical for the 7.0 release, then yes, you may merge.

**Comment by mcimbora** [comment]
@manstis I'm for inclusion in 7.0.x as this fixes a defect of cloning the playground repository multiple times (which causes additional indexing to kick in.

**Comment by manstis** [comment]
@etirelli @mcimbora it's significant enough.. so merging :-)

**Pull request merged**
