### PR TITLE
[DROOLS-2619] Fix test names to follow surefire and failsafe patterns

### PR DESCRIPTION
**Pull request by barboras7**

### CODE REVIEW

**Comment by jhrcek** [comment]
@barboras7 nice catch!

@manstis @desmax74 @pefernan @romartin since you implemented those tests, please be aware in the future, that test classes must be [named in a certain way](http://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html#Inclusions) in order for surefire to find them and run the tests.

Although it is possible to manually configure `includes` of surefire-maven-plugin, I'd suggest we keep things simple and just keep standard surefire convention and name the test classes so that they name with "Test" (in particular not Test**s**)

**Comment by barboras7** [comment]
Hi @desmax74,
could you please take a look at the failing PomEditorWithGitTest? It seems that you implemented it. Also @manstis, could you please look at the IndexDrlInvalidDrlTest?
Thanks.

**Comment by desmax74** [comment]
@barboras7 sure, but tomorrow because today I'm still in Barcelona

**Comment by desmax74** [comment]
@barboras7  the error on jenkins is a npe on the FileSystemProviders.getProvider(FileSystemProviders.java:125) but I can't reproduce locally let me retry on jenkins

**Comment by desmax74** [comment]
jenkins retest this

**Comment by desmax74** [comment]
@barboras7 trying to obtain more informations with a logback-test here https://github.com/kiegroup/kie-wb-common/pull/1829

**Comment by barboras7** [comment]
@desmax74 sure, thanks a lot for the effort. Please, let me know if I can help somehow/when you have some updates about the issue

**Comment by barboras7** [comment]
jenkins retest this

**Comment by barboras7** [comment]
Thanks a lot, @manstis. The test is green now :)

**Comment by jhrcek** [comment]
@barboras7 could you please rebase and get this merged?

**Comment by barboras7** [comment]
@manstis Could you please merge this? The check is green now and the PR is rebased.

**Pull request merged**
