### PR TITLE
KOGITO-628: Configure Errai to return default values for missing i18n keys

### PR DESCRIPTION
**Pull request by jesuino**
The issue from KOGITO-628 is caused by ERRAI-1101. The solution is make Errai return the default value for a missing locale key.

### CODE REVIEW

**Comment by jesuino** [comment]
@manstis I think you may be the one to review this because you are aware of ERRAI-1101 :-)

**Comment by manstis** [comment]
@jesuino Did it fix the problem then!?!? :-)

**Comment by jesuino** [comment]
> @jesuino Did it fix the problem then!?!? :-)

Yes, it was a long trip until finding this param, but in my tests it fixed the issue

**Comment by manstis** [comment]
@jomarko You're the _tester_ on the JIRA.

IDK if we should have @hasys check BPMN?

**Comment by manstis** [comment]
@jesuino Could you please also make the following changes on this PR:

Delete [this](https://github.com/kiegroup/kie-wb-common/blob/21252c97edb9905b880dc8077981ad14840df66f/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/main/resources/org/kie/workbench/common/dmn/showcase/FastCompiledDMNKogitoRuntimeWebapp.gwt.xml).

Change [this](https://github.com/kiegroup/kie-wb-common/blob/21252c97edb9905b880dc8077981ad14840df66f/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/pom.xml#L513) to reference `DMNKogitoRuntimeWebapp.gwt.xml`

**Comment by jesuino** [comment]
@manstis  done - quickly tested locally and it looks fine

**Comment by jomarko** [comment]
@jesuino @manstis I can confirm this works when I run `kie-wb-common-dmn-webapp-kogito-testing`, however I am not able to run `vsix` extension.
1. I build `kie-wb-common-dmn-webapp-kogito-runtime` as `mvn clean install -Pkogito`
2. I put produced war file into `kogito-tooling/packages/kie-bc-editors-unpacked/dmn/`
3. I run `yarn run build:prod` from `kogito-tooling` root but getting an error

```
lerna ERR! yarn run build:prod exited 2 in '@kogito-tooling/microeditor-envelope-protocol'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by manstis** [comment]
@jomarko I was able to build and test in VSCode OK. 

These are my steps (not much different to yours).

1. Build `kie-wb-common-webapp-kogito-runtime` as you did (with `-Pkogito`).
2. Copy resulting `kie-wb-common-dmn-webapp-kogito-runtime.war` somewhere and unzip it.
3. Copy content (other than `WEB-INF` folder) to `kogito-tooling/packages/unpacked-gwt-editors/dmn`
4. Run `yarn run init` in `kogito-tooling`
5. Run `yarn run build:prod` in `kogito-tooling`
6. Install resulting `kogito-tooling/packages/vscode-extension-pack-kogito-kie-editors/dist/vscode_extension_kogito_kie_editors_0.2.5.vsix` in VSCode
7. Open a `.dmn` file.

**Comment by manstis** [comment]
@jomarko I deleted my clone of `kogito-tooling` and fetched it again from GitHub.

Repeating my (modified) steps above (correcting folder name for unpacked editor) it works OK for me.

**Comment by manstis** [comment]
@jesuino @tiagobento IDK if you can help @jomarko.

He's having difficulties building the VSCode plugin for this PR.

**Comment by tiagobento** [comment]
@manstis @jesuino @jomarko The build steps posted by @manstis look spot on to me. Did you try that?

**Comment by jesuino** [comment]
@jomarko you can download my build with the fix from this link -> https://drive.google.com/file/d/12isaOiQGabzJ9SGu2RfT6CX9ptRUXf5q/view?usp=sharing

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by jomarko** [comment]
@tiagobento yes I am following exactly steps as @manstis do, currently getting this error:
```
chrome-extension-pack-kogito-kie-editors: $ rm -rf dist && webpack --mode production --devtool none
chrome-extension-pack-kogito-kie-editors: fatal: No names found, cannot describe anything.
chrome-extension-pack-kogito-kie-editors: Error: Command failed: git describe --tags `git rev-list --tags --max-count=1`
chrome-extension-pack-kogito-kie-editors: fatal: No names found, cannot describe anything.
chrome-extension-pack-kogito-kie-editors:     at checkExecSyncError (child_process.js:621:11)
chrome-extension-pack-kogito-kie-editors:     at Object.execSync (child_process.js:657:15)
chrome-extension-pack-kogito-kie-editors:     at getLatestGitTag (/home/jomarko/redhat/github/kiegroup/kogito-tooling/packages/chrome-extension-pack-kogito-kie-editors/webpack.config.js:24:6)
chrome-extension-pack-kogito-kie-editors:     at getRouterArgs (/home/jomarko/redhat/github/kiegroup/kogito-tooling/packages/chrome-extension-pack-kogito-kie-editors/webpack.config.js:37:61)
chrome-extension-pack-kogito-kie-editors:     at module.exports (/home/jomarko/redhat/github/kiegroup/kogito-tooling/packages/chrome-extension-pack-kogito-kie-editors/webpack.config.js:50:54)
chrome-extension-pack-kogito-kie-editors:     at handleFunction (/home/jomarko/redhat/github/kiegroup/kogito-tooling/node_modules/webpack-cli/bin/utils/prepareOptions.js:21:13)
chrome-extension-pack-kogito-kie-editors:     at prepareOptions (/home/jomarko/redhat/github/kiegroup/kogito-tooling/node_modules/webpack-cli/bin/utils/prepareOptions.js:9:5)
chrome-extension-pack-kogito-kie-editors:     at requireConfig (/home/jomarko/redhat/github/kiegroup/kogito-tooling/node_modules/webpack-cli/bin/utils/convert-argv.js:117:14)
chrome-extension-pack-kogito-kie-editors:     at /home/jomarko/redhat/github/kiegroup/kogito-tooling/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
chrome-extension-pack-kogito-kie-editors:     at Array.forEach (<anonymous>)
chrome-extension-pack-kogito-kie-editors:     at module.exports (/home/jomarko/redhat/github/kiegroup/kogito-tooling/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
chrome-extension-pack-kogito-kie-editors:     at /home/jomarko/redhat/github/kiegroup/kogito-tooling/node_modules/webpack-cli/bin/cli.js:71:45
chrome-extension-pack-kogito-kie-editors:     at Object.parse (/home/jomarko/redhat/github/kiegroup/kogito-tooling/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
chrome-extension-pack-kogito-kie-editors:     at /home/jomarko/redhat/github/kiegroup/kogito-tooling/node_modules/webpack-cli/bin/cli.js:49:8
chrome-extension-pack-kogito-kie-editors:     at Object.<anonymous> (/home/jomarko/redhat/github/kiegroup/kogito-tooling/node_modules/webpack-cli/bin/cli.js:366:3)
chrome-extension-pack-kogito-kie-editors:     at Module._compile (internal/modules/cjs/loader.js:959:30)
chrome-extension-pack-kogito-kie-editors:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
chrome-extension-pack-kogito-kie-editors:     at Module.load (internal/modules/cjs/loader.js:815:32)
chrome-extension-pack-kogito-kie-editors:     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
chrome-extension-pack-kogito-kie-editors:     at Module.require (internal/modules/cjs/loader.js:852:19)
chrome-extension-pack-kogito-kie-editors:     at require (internal/modules/cjs/helpers.js:74:18)
chrome-extension-pack-kogito-kie-editors:     at Object.<anonymous> (/home/jomarko/redhat/github/kiegroup/kogito-tooling/node_modules/webpack/bin/webpack.js:156:2)
chrome-extension-pack-kogito-kie-editors:     at Module._compile (internal/modules/cjs/loader.js:959:30)
chrome-extension-pack-kogito-kie-editors:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
chrome-extension-pack-kogito-kie-editors:     at Module.load (internal/modules/cjs/loader.js:815:32)
chrome-extension-pack-kogito-kie-editors:     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
chrome-extension-pack-kogito-kie-editors:     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
chrome-extension-pack-kogito-kie-editors:     at internal/main/run_main_module.js:17:11
chrome-extension-pack-kogito-kie-editors: error Command failed with exit code 1.
chrome-extension-pack-kogito-kie-editors: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
chrome-extension-pack-kogito-kie-editors: error Command failed with exit code 1.
chrome-extension-pack-kogito-kie-editors: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
chrome-extension-pack-kogito-kie-editors: error Command failed with exit code 1.
chrome-extension-pack-kogito-kie-editors: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build:prod exited 1 in 'chrome-extension-pack-kogito-kie-editors'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
```

**Comment by jomarko** [comment]
@jesuino thank you for the vsix, does this PR just prevent from an exception somewhere?

Because if I change language of my vscode to Japanese, still have DMN designer in english. While in business-central it works for Japanese.

Screenshot from 2019-12-04 09-25-32

**Comment by jesuino** [comment]
@jomarko Thanks for the feedback.

The fix is simply return the default value when the translation key is not present. This should work with Japanese as well, because I know that there is *_ja.properties for Stunner at least.

I will check and let you know.

**Comment by tiagobento** [comment]
@jomarko right. that happens when you don't have tags on your local git clone. we need the tags because we reference the latest one when building the chrome extension.

**Comment by jomarko** [comment]
@tiagobento sory for stupid question, how to fix this, just `git fetch all` ?

**Comment by tiagobento** [comment]
@jomarko good question. i think it depends on the version of git you're using, but try `git fetch --tags` :D

**Comment by jomarko** [comment]
@tiagobento cool, fetching tags helped, should we added into some readme? or am I the only one for who it is non intuitive?

**Comment by tiagobento** [comment]
good point! i'll add that to the list of things i have to do soon :) thx for pointing that out @jomarko !

**Comment by jomarko** [comment]
thank you @tiagobento

**Comment by jesuino** [comment]
Just to document what I discussed with @jomarko -> The language pack installed on VSCode will not have effect on editors, only the OS language. If the OS lang is not supported then it will use English by default.

**Comment by jesuino** [comment]
Jenkins execute full downstream build

**Pull request merged**
